### ISSUE TITLE
opencensus includes lgpl 3.0 only

### ISSUE THREAD

**Issue by cblomart** [olivere/elastic#1001]
Following license check with app.fossa.io i got the following flagged issue:
```Requires you to (effectively) disclose your source code if the library is statically linked to your project. Not triggered if dynamically linked or a separate process.```

This is due to the fact that opencensus-go uses thrift that includes the license requirement.

For the reading i have of its use here, it seems only experimental for tracing.

PS: i try to package my project as staticaly linked go (eventually in a container)

**Comment by olivere** [comment]
Hmm... IANAL. Wasn't aware of that. Will look into it tomorrow. If all goes wrong, I will remove the tracing support for Open Census. It's experimental anyway.

**Comment by olivere** [comment]
@cblomart I wonder where they got that from. The opencensus-go library is Apache Licensed, see 
https://github.com/census-instrumentation/opencensus-go/blob/master/LICENSE

**Comment by olivere** [comment]
@cblomart Oh, I'm sorry, you already mentioned it's Thrift. But [Thrift](https://thrift.apache.org) it also licensed under [Apache License v2.0](http://www.apache.org/licenses/) (see [GitHub repo as well](https://github.com/apache/thrift)). I guess it's a false flag von Fossa.

![image](https://user-images.githubusercontent.com/134848/50545575-64b76600-0c18-11e9-9790-b0e3d6aa5863.png)

**Comment by cblomart** [comment]
Thanks for looking this up @olivere. I know that checking licenses is not fun or interesting.
After looking up a bit the thrift repository, it seems that the LGPL license is there because it is also delivered as a debian package.
I set these issues as ignored on fossa for my project and contacted support@fossa.io to signal the possibility of a "wrong positive".
Thanks again for your time and a happy new year

**Comment by olivere** [comment]
Hmm... here's a response from Carlos of the Fossa team:

> Carlos (FOSSA)
> 
> @Oliver Eilhard Depending on which version of Thrift project you were on if it's before 0.9.3 than there were traces of LGPL. It looks like we matched a mention of LGPL in the "Changes" Folder -> https://github.com/apache/thrift/blob/master/CHANGES You can ignore the issue if you're using the latest version.
> 
> CHANGES
> ```
> Apache Thrift Changelog
> 
> Breaking Changes since 0.11.0 [for 0.12.0]:
> --------------------------------------------------------------------------------
>    * [THRIFT-4529] - Rust enum variants are now camel-cased instead of uppercased to conform to Rust naming conventions
>    * [THRIFT-4448] - Support for golang 1.6 and earlier has been dropped.
> ...
> ```
>
> Hope that helps!

I'm not sure how to properly handle that as I'm not in control of what exact version of Thrift the OpenConsensus team is using. It might help to open an issue on the openconsenus-go repository to get their feedback.

To protect users from any issues, I'm thinking about removing the openconsensus code until we're sure how to properly resolve this. What do you think?

**Comment by olivere** [comment]
@cblomart According to https://github.com/census-instrumentation/opencensus-go/issues/1005, they seem to be okay with that and will tag Thrift with a versions that's good to go anyway.
