### ISSUE TITLE
Fields dropped from Watch

### ISSUE THREAD

**Issue by abaehre** [olivere/elastic#1006]
### Which version of Elastic are you using?

[ x ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
https://github.com/olivere/elastic/blob/release-branch.v6/xpack_watcher_get_watch.go#L74
(the Do function on *XPackWatcherGetWatchService) returns all fields of the watch.

### Please describe the actual behavior
Fields that are not included in the struct XPackWatch (https://github.com/olivere/elastic/blob/release-branch.v6/xpack_watcher_get_watch.go#L118) are truncated during the json.Unmarshal in Do (https://github.com/olivere/elastic/blob/release-branch.v6/xpack_watcher_get_watch.go#L98)

### Any steps to reproduce the behavior?
Here's an example of "throttlePeriod" being dropped in a Go Playground. https://play.golang.org/p/s2d0ikMEDg-

You can also reproduce by doing a "Put" and then a "Get" of a watch with a field that isn't currently in the XPackWatch struct.

### Notes
This should be able to be fixed by adding all fields that a Watch may have to the XPackWatch struct. Doing so will stop the truncation of those fields.

Example fields that are found in https://github.com/elastic/examples - 

https://github.com/elastic/examples/blob/master/Alerting/Sample%20Watches/cpu_iowait_hosts/watch.json#L2

https://github.com/elastic/examples/blob/master/Alerting/Sample%20Watches/errors_in_logs/watch.json#L53

https://github.com/elastic/examples/blob/master/Alerting/Sample%20Watches/filesystem_usage/watch.json#L69

**Comment by olivere** [comment]
Thanks for reporting. That part of the package has been PR'd by a contributor, so I will have to dig into it. Will do so in the next release.

**Comment by abaehre** [comment]
I wouldn't necessarily describe `XPackWatch` as "flexible". Right now because it is a struct it will drop all watcher options not included in the struct. This makes the `Do` method (https://github.com/olivere/elastic/blob/release-branch.v6/xpack_watcher_get_watch.go#L74) unusable   if you need to retrieve any of those options. 

If there was a method (I may just be missing it) that did the same thing returning a map[string]interface or just an interface that would allow for users to unmarshal into their own struct. However, based on the function composition it must be unmarshalled into the `XPackWatch`. 

If you'd like I can attempt to submit a PR that would allow both as options while keeping the API you've established consistent.

**Comment by olivere** [comment]
I didn't dig into the details, but at first sight it seems like a Watch doesn't just come up with arbitrary fields but is defined by what looks like [`Watch.java`](https://github.com/elastic/elasticsearch/blob/6.x/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/watcher/watch/Watch.java#L136-L162). There might be some fields missing. But I cannot see where e.g. that `throttledPeriod` in [your Go snippet](https://play.golang.org/p/s2d0ikMEDg-) may come from. Any hints how and when Elasticsearch might return that?

**Comment by olivere** [comment]
Upon a 2nd look, the `throttle_period` is defined in the [`Watch.java`](https://github.com/elastic/elasticsearch/blob/6.x/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/watcher/watch/Watch.java#L136-L162).

A PR with all the fields defined in that `Watch.java` added to `XPackWatch` would help indeed. Otherwise I'll do that for the next release.

**Comment by abaehre** [comment]
I'm actually not super well-versed in the options available either. I just noticed they were getting stripped in the code I was looking at. When I looked into it I found https://github.com/elastic/examples, I would assume that those used valid fields, and my watch json files were based off of those.

**Comment by olivere** [comment]
I've expanded the XPack Watcher API structures in https://github.com/olivere/elastic/commit/f438c83fc2528cee94667573c4f86367e1653097. Maybe you can double-check if that's complete.

**Comment by abaehre** [comment]
I think that that looks correct. I appreciate all the work you've done on this.

**Comment by olivere** [comment]
f438c83 will be part of 6.2.17.
