### ISSUE TITLE
Question: Nesting Bool Queries?

### ISSUE THREAD

**Issue by willmichael** [olivere/elastic#1008]
### Which version of Elastic are you using?

[ x ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior

I run into a problem when trying to nest BoolQueries that isn't necessarily a problem with your library, but maybe you can help me!  

What I'm trying to do is:
```
outerQuery := elastic.NewBoolQuery()
var SomeBoolQueries []*elastic.BoolQuery
outerQuery.Must(SomeBoolQueries...)

cannot use (type []*elastic.BoolQuery) as type []elastic.Query in argument 
to outerQuery.Should
```
Simply passing in a *elastic.BoolQuery works, so I think it's due to the way pointers and variadic functions operate, but I was wondering if you know a workaround. I'm a little new to the go language, so any help is appreciated!

**Comment by olivere** [comment]
Yes, that's the way it works in Go. You either have to copy over the slice from `[]*elastic.BoolQuery` to `[]elastic.Query`, or you work around it like e.g. this:

```go
var mustQueries []elastic.Query
if someCondition {
  mustQueries = append(mustQueries, elastic.NewWhateverQuery(...))
}
if someOtherCondition {
  mustQueries = append(mustQueries, elastic.NewWhateverQuery(...))
}

bq := elastic.NewBoolQuery().Must(mustQueries...)
```

**Comment by willmichael** [comment]
Thanks!
