### ISSUE TITLE
cluster nodes api doesn't work when using private ips

### ISSUE THREAD

**Issue by oryband** [olivere/elastic#101]
```bash
$ curl -XGET http://mycluster/_nodes
```
```json
...
"hnUF4ljFQfWDEpfCM2LZvg": {
  "name": "es-fe-4",
  "transport_address": "inet[/10.128.196.97:9300]",
  "host": "es-fe-4",
  "ip": "127.0.1.1",
  "version": "1.3.9",
  "build": "0915c73",
  "http_address": "inet[/10.128.196.97:9200]",
  "attributes": {
    "data": "false",
    "max_local_storage_nodes": "1",
    "master": "false"
  },
  "http": {
    "bound_address": "inet[/0:0:0:0:0:0:0:0%0:9200]",
    "publish_address": "inet[/10.128.196.97:9200]",
    "max_content_length_in_bytes": 104857600
  }
},
...
```
The API returns unreachable private ips. is there any alternative request or another way to get the public ips? This practically renders sniffing unusable :(

**Comment by oryband** [comment]
@ofir-petrushka @gadisr

**Comment by olivere** [comment]
Hi there. First of all, Elastic simply returns the response of Elasticsearch, so this is probably not specific to Elastic, right?

There have been similar issues with e.g. Docker and there's a [wiki entry](https://github.com/olivere/elastic/wiki/Docker) related to this. You basically have to tell ES to bind to the public interface.

HTH

**Comment by oryband** [comment]
@olivere yeah, this is an es problem, not this repo's. i just thought asking here for good advice. wouldn't this cause all the nodes to communicate with each other via their public address instead of their private one? i still want them communicate with each other privately (to save on public traffic), but publish their public ip via this api.

**Comment by olivere** [comment]
@oryband I think there are different communication mechanisms between the ES nodes as described in the [network settings](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html). The nodes should communicate via TCP internally via [transport](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-transport.html). There's different settings for [HTTP](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html), which is what Elastic (and most official clients) use.

**Comment by olivere** [comment]
Did you resolve the issue? If so, would be nice to add your experience to the Wiki page.

**Comment by oryband** [comment]
not yet, still working on it @ofir-petrushka

**Comment by olivere** [comment]
Any progress on this? Would be happy if I could add your insights to the [Wiki page](https://github.com/olivere/elastic/wiki/Docker), if you have anything to add.

**Comment by oryband** [comment]
hey @olivere , i think there is a solution, but we're still working on our new es cluster. we will be done with it soon and i will update you if we succeed or not. i'll close this issue then.

**Comment by oryband** [comment]
@olivere update:

1. Yes, there is a way to set HTTP publish address to be public while keeping *transport* publish address as private.
2. However, we eventually decided to keep the HTTP address private, since the primary clients working with out elasticsearch cluster will be hosted on the same datacenter. This gives us the benefit of saving on traffic, since private is usually cheaper.
3. If, however, in the future we change our minds - I can verify we can switch public address to be public instead.
4. My only wish is to be able to publish 2 different HTTP addresses: one private and one public. This would've given us the flexibility the use the *node API* from within the datacenter (using private traffic), and from outside (using public one). From what I saw in the docs, I don't think this is possible. Do you have any idea regarding this?

In any case, thank you very much for the help. Feel free to add this to the wiki and close this issue.

**Comment by olivere** [comment]
@oryband Hmm... just thinking loud... If you have multiple nodes in your cluster, couldn't you split them into nodes that bind to a "private" IP and nodes that bind to a "public" IP. Then you could create two Elastic clients in your code: one for the private and the other for the public IPs?!

Elastic can only use the HTTP endpoint. Most other transports are deprecated AFAIK, e.g. [Thrift is deprecated as of 1.5 and disabled in Elasticsearch 2.0](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-thrift.html). If you want to use the transport protocol, you can only do so with the [Java API](https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/index.html) AFAIK.

**Comment by oryband** [comment]
@olivere how could the clients differentiate between the frontends which publish public ip and the ones publishing a private ip? by trying them out and failing, then deciding they're unreachable? sounds a bit off. Also, this practically divides the available frontends by half (one half for public access, other half for private).

**Comment by olivere** [comment]
The Elastic clients would have to be explicitly setup, by you, to only listen only to the nodes they were configured (sniffing disabled). Yes, it splits the frontends by half. But the frontends should only be used for receiving and parsing your requests: The cluster will happily execute all your requests with all of its nodes as they communicate with the transport protocol.

But maybe I'm missing something. It's Monday morning, after all ;-)

Feel free to open the issue again if there's something new to add.

**Comment by oryband** [comment]
i see, nice idea. thanks for the tech support ;)
