### ISSUE TITLE
bug s with "cluster state" api on "routing_table" field

### ISSUE THREAD

**Issue by xiazihao** [olivere/elastic#1010]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ latest] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
using cluster_state api, parse "routing_table" correct.

### Please describe the actual behavior
Because the struct "routing_table" is wrong.
In code "	RoutingTable map[string]*clusterStateRoutingTable `json:"routing_table"`  ",
expect  "  	RoutingTable *clusterStateRoutingTable `json:"routing_table"`  ".

### Any steps to reproduce the behavior?
It's easy to reproduce.

**Comment by olivere** [comment]
Sorry for the delay. I will look at it in the next release.

**Comment by olivere** [comment]
Hmm... I've [added a test](https://github.com/olivere/elastic/commit/5105d2e4e4844bab149f41767a230ea9c15da42f) to see if and how this fails and cannot see where it goes wrong.

```
...
  "routing_table" : {
    "indices" : {
      ...
    },
    ...
  },
  ...
```

How do I reproduce?

**Comment by xiazihao** [comment]
Check content in "RoutingTable",the inner struct is nil. RoutingTable is not a map
![image](https://user-images.githubusercontent.com/20250372/51803613-2605e180-2292-11e9-9945-eacec95d3193.png)
![image](https://user-images.githubusercontent.com/20250372/51803620-3d44cf00-2292-11e9-9f48-98a9270659a3.png)

**Comment by olivere** [comment]
Ah... my bad. Will change. Thanks.
