### ISSUE TITLE
Fix typo in HighlightQuery

### ISSUE THREAD

**Issue by olivere** [olivere/elastic#1017]
There seems to be some typos in recent versions, e.g. [`HighlighQuery` here](https://github.com/olivere/elastic/blob/release-branch.v6/highlight.go#L128).

Have to look into v5 as well.

**Comment by nagypeterjob** [comment]
Hello Oliviere,

I have created two pull requests for v5 & v6 respectively to address this issue and fix the typos:
#1018 
#1019 

I hope these PRs free you up a bit. Keep up the great work!
