### ISSUE TITLE
Bulk API does not set Content-Type: application/x-ndjson

### ISSUE THREAD

**Issue by chloe899** [olivere/elastic#1020]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
{Status:406, Message:"Content-Type header [] is not supported"}

### Please describe the actual behavior

{Status:406, Message:"Content-Type header [] is not supported"}

### Any steps to reproduce the behavior?

	req := elastic.NewBulkUpdateRequest()
        req.Doc(xxxStruct)
	req.Id(xxxStruct.Id)
	req.Routing(xxxRouting)
	req.Index(xxxIndex)
	req.Type(xxxType)
       req2 := elastic.NewBulkUpdateRequest()

        req2.Doc(xxxStruct)
	req2.Id(xxxStruct.Id)
	req2.Routing(xxxRouting)
	req2.Index(xxxIndex)
	req2.Type(xxxType)

         builder := client.Bulk()
	builder.Add(req)
	builder.Add(req2)

        builder.Do()

**Comment by olivere** [comment]
Hmm... I can't see why that should be missing. It's [clearly set here](https://github.com/olivere/elastic/blob/release-branch.v6/bulk.go#L255). Are you sure you're using the latest version? Can you have a look at [this line in `client.go`](https://github.com/olivere/elastic/blob/release-branch.v6/client.go#L29)?

**Comment by chloe899** [comment]
Hello, I have read the code, and code not exist at  bulk.go  of master branch.
The readme doc write the v6 package url is github.com/olivere/elastic.

**Comment by olivere** [comment]
The `master` branch is defunct. You need to look at the `release-branch.v6` for `v6` and `release-branch.v5` for `v5` etc.

DO NOT USE the `master` branch.
