### ISSUE TITLE
Is there any API's to limit the size of data retrived from elastic DB ?

### ISSUE THREAD

**Issue by orangemail** [olivere/elastic#1021]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v6 (for Elasticsearch 6.x)

Hi ,

I was looking out to see  if there is a way to limit the data retrieved based on size. 

i.e If I do a query, the size of data should not cross some specified size (say for example data outcome could not exceed 2MB).

Can you please suggested if there are API to handle this in elastic ?

Regards,

Sathish.S

**Comment by olivere** [comment]
You mean you want to limit the HTTP response from Elastic(search) by size? Hmmm... maybe you could [create your own `http.Transport`](https://github.com/olivere/elastic/wiki/HttpTransport) and let Elastic use that.

Limiting the size can be done [by an `io.LimitedReader`](https://golang.org/pkg/io/#LimitedReader), something [like this](https://github.com/olivere/httputil/blob/master/httputil.go#L45). 

Maybe you can also configure something on the Elasticsearch server side, I've never had that problem that I cannot trust internal systems.
