### ISSUE TITLE
Unable to run pipeline while updating

### ISSUE THREAD

**Issue by rgavriel** [olivere/elastic#1022]
### Which version of Elastic are you using?

[ ] elastic.v6 (for Elasticsearch 6.x)
[X] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behaviour
Provide UpdateService with Pipeline to run after the update append. Like IndexService or UpdateByQueryService

### Please describe the actual behaviour
method not implemented

### Any steps to reproduce the behaviour?
Given `client` instance of `*elastic.Client`
client.Update().Pipeline("my_pipeline_name")...

**Comment by olivere** [comment]
Can you please post a complete example of the problem and the error as reported by Elasticsearch? I have several tests to check for elastic generating the correct JSON to send to ES, so it may be an issue with your code e.g. not having the given pipeline.

**Comment by rgavriel** [comment]
My bad, ES doesn't support pipelines on update up until version 6.
