### ISSUE TITLE
Highlighting does not add span tags around matches

### ISSUE THREAD

**Issue by mitjafelicijan** [olivere/elastic#1025]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
Lets say I search for "ok" string which returns correct records from database but does not add span around the resulting matched words.

Current result: `Suspicious packages sent to Robert De Niro, and is it ok to dress as someone you know for Halloween?`

### Please describe the actual behavior
Desired result: `Suspicious packages sent to Robert De Niro, and is it <span>ok</span> to dress as someone you know for Halloween?`

### Any steps to reproduce the behavior?
	searchTerm := string(ctx.QueryArgs().Peek("q"))

	query := elastic.NewBoolQuery()
	query = query.Should(elastic.NewTermQuery("headline", searchTerm))
	query = query.Should(elastic.NewTermQuery("description", searchTerm))

	highlight := elastic.NewHighlight()
	highlight = highlight.Fields(elastic.NewHighlighterField("*"))
	highlight = highlight.PreTags("<span>").PostTags("</span>")

	searchResult, err := client.Search().
		Index("local").
		Highlight(highlight).
		Query(query).
		Sort("createdAt", true).
		From(0).Size(10).
		Pretty(true).
		Do(ctx)

**Comment by olivere** [comment]
There is a [test for the highlighter](https://github.com/olivere/elastic/blob/75ab10f9a5111c2d2050c31448646b594f64b043/highlight_test.go#L139-L212) that successfully returns the tag:

```
{
  "took" : 46,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "elastic-test",
        "_type" : "doc",
        "_id" : "1",
        "_score" : 1.0,
        "_source" : {
          "user" : "olivere",
          "message" : "Welcome to Golang and Elasticsearch.",
          "retweets" : 0,
          "created" : "0001-01-01T00:00:00Z"
        },
        "highlight" : {
          "message" : [
            "Welcome to <em>Golang</em> and Elasticsearch."
          ]
        }
      }
    ]
  }
}
```

Can you please compare your code to the test? I'm not saying there's no problem in elastic, I just want to make sure that it's not something e.g. related to your mapping.

**Comment by claudioontheweb** [comment]
I have the same problem. I implemented it the same way as in the provided Test.

`boolQuery := elastic.NewBoolQuery().
		Must(elastic.NewQueryStringQuery(queryValue)).
		MustNot(elastic.NewMultiMatchQuery("test", "contenttype"))

	hl := elastic.NewHighlight().
		Field("content").
		PreTags("<em>").
		PostTags("</em>")

	searchResult, err := es.Client.Search().
		Index(index).
		Highlight(hl).
		Query(boolQuery).
		RestTotalHitsAsInt(true).
		From(from).Size(size).
		Pretty(true).
		Do(*es.Ctx)
	if err != nil {
		log.Info("Error performing Elastic Search")
		return nil, err
	}`
