### ISSUE TITLE
How to automatically create an index when it does not exist in bulk request?

### ISSUE THREAD

**Issue by hel2o** [olivere/elastic#1026]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[X ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
How to automatically create an index when it does not exist in bulk request?

### Any steps to reproduce the behavior?
this is my code ，How to modify to achieve the purpose？
```golang
func SquidLogBulkInsertToES(logs []models.SquidLog) (res *elastic.BulkResponse, err error) {
	
	squidLogIndex:= fmt.Sprintf("squidlog%s",time.Now().Format("2006-01-02"))
	
	bulkRequest := elastic.NewBulkService(esClient)
	for _, l := range logs {
		request := elastic.NewBulkIndexRequest().
			Index(squidLogIndex).
			Doc(l)
		bulkRequest = bulkRequest.Index(squidLogIndex).Type("squidlog").Add(request)
	}
	res, err = bulkRequest.Do(ctx)
	return
}
```

**Comment by olivere** [comment]
Elasticsearch has automatic index creation, see https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#index-creation.

Notice that you should probably create a template for your index so that an initial mapping is used when creation the index automatically.
