### ISSUE TITLE
Update by Query with Pipeline param

### ISSUE THREAD

**Issue by andrew-greiner** [olivere/elastic#1028]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[X ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
POST index/_update_by_query?pipeline=set-partnerIds
{
  "query": {
    "match": {
      "id.keyword": "unique-identifier"
    }
  }
}

### Please describe the actual behavior
No issue, just having difficult understanding the correct manner in which to apply the "?pipeline=set-partnerIds" argument on the _update_by_query.

Absolutely top notch job on this btw

**Comment by olivere** [comment]
Heja. [`Pipeline` is here](https://github.com/olivere/elastic/blob/release-branch.v6/update_by_query.go#L237-L241). Looks something like this:

```
res, err := client.UpdateByQuery().
  Index("...").
  Type("...").
  Pipeline("set-partnerIds").
  Query(elastic.NewMatchQuery("id.keyword", "unique-identifier")).
  Do(ctx)
```
