### ISSUE TITLE
How to "wait" for elastic search

### ISSUE THREAD

**Issue by rayjlinden** [olivere/elastic#1029]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[X ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

In our sandbox environment we are launching a bunch of docker services including Elasticsearch.  As such I want our go code to be resilient to ES not being available - particularly on start-up.  Indeed, I want to make sure it has started enough such that calls to populate an index will actually work.  As such I have the following line of code to wait for the index to turn "green".

	_, err := esClient.ClusterHealth().Index(lambdaState.personasIndexName).WaitForStatus("green").Timeout(lambdaState.ElasticsearchStartupTimeout).Do(ctx)

Sometimes this works.  But other sometimes I get this failure:
Get http://elasticsearch:9200/_cluster/health/personas?timeout=180s\u0026wait_for_status=green: dial tcp 172.17.0.6:9200: connect: connection refused

In this case, I believe ES is rather slow to start and may not have even opened up the port yet.

I'd like for the call to retry in this case as well and not fail (unless it hits the timeout period, of course).

### Please describe the actual behavior

Call to wait for index returns an error before timeout is up.

**Comment by olivere** [comment]
There are many different options.

First, you could use a tool like [`netcat`](https://en.wikipedia.org/wiki/Netcat) to wait for Elasticsearch in your setup. [Here's an example](https://github.com/olivere/elastic/blob/release-branch.v6/.travis.yml#L30) I use when running the tests on Travis.

Second, you could manually wait for a valid TCP connection to `elasticsearch:9200` in your `main.go` with something like this:

```go
package main

import (
	"context"
	"flag"
	"net"
	"os"
	"time"
)

func main() {
	var (
		timeout = flag.Duration("t", 5*time.Second, "Timeout")
	)
	flag.Parse()

	ctx, cancel := context.WithTimeout(context.Background(), *timeout)
	defer cancel()
	d := net.Dialer{}
	_, err := d.DialContext(ctx, "tcp", flag.Arg(0))
	if err != nil {
		os.Exit(1)
	}
}
```

Third, you could use configuration settings in elastic to increase the timeouts when creating an Elasticsearch client. See `SetHealthcheckTimeoutStartup ` and `SetSnifferTimeoutStartup ` on [this Wiki page](https://github.com/olivere/elastic/wiki/Configuration).

Fourth, you could simply exit your application with a failure and let Docker restart it for you. Eventually, it will come up.
