### ISSUE TITLE
When should I use realtime vs search mode?

### ISSUE THREAD

**Issue by snowzach** [olivere/elastic#1030]
I am working on some code where I am getting a bunch of documents by ID. Using the Get function I am getting a lot of "elastic is dead" messages even with sniffing and healtcheck turned off. 

Out of frustration I tried this Realtime = true and the performance is wayyyyy better and I have yet to get a dead message.

**Comment by olivere** [comment]
What do you mean by „realtime = true“?

I suppose with dead you mean that the request could not be sent to any node in the cluster because none of them responded in time. If that’s true, you should really work on your cluster setup. Enabling health checks in that case are good because it could find dead nodes even before sending a request to a node, enhancing the chances of routing it to a node that is alive on the first try.

**Comment by snowzach** [comment]
I guess the realtime flag forces a refresh when necessary. It's on the elastic Get api and supported by this library. I was thinking it was part of my problem but apprently not. 

So, my real issue is that even when I have sniff and healthcheck disabled, I am still getting the `1.1.1.1 is dead` message but it does not appear that my server is actually down.

Is there perhaps a timeout setting for the Get function that is triggering making this library think the server is dead? There is no timeout on the Get function of this library. 

Thanks for any help.

**Comment by olivere** [comment]
Yes, you can pass Refresh(...) in certain APIs. But that comes with a cost.

I’m really confused about your cluster setup. Why is the IP 1.1.1.1? Elastic simply uses the IP you pass with SetURL if you disable sniffing and health checks. If you keep sniffing enabled, it will call the Cluster State API to get the IPs of all nodes at startup and use those, periodically re-executing that process in health checks. In the end, Elastic will make a normal HTTP call to some IP. If that’s failing, that’s a networking problem.

**Comment by olivere** [comment]
BTW: If you want to experiment with your own HTTP client, use the SetHttpClient confiag option. See the Wiki for details.
