### ISSUE TITLE
Add Headers to ReindexService

### ISSUE THREAD

**Issue by reaVen-** [olivere/elastic#1031]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
Headers like the X-Opaque-Id header introduced in ES 6 should be exposed both during creating and retrieving of reindex operations. 

https://www.elastic.co/guide/en/elasticsearch/reference/current/tasks.html#_identifying_running_tasks

This is very useful for small services that should be able to crash and recover at any point. Because the services does not need to keep its own state.

### Please describe the actual behavior
Headers are exposed in the TaskInfo struct when creating reindex operations using for example cURL, but there is no possibility to add the header when creating the reindex-operation using the client.

I have added a revised reindex.go file that includes the changes needed to make this work.
tested it using our 6.5.1 cluster.

the file is based on v6.2.16

[reindex_changes.tar.gz](https://github.com/olivere/elastic/files/2822185/reindex_changes.tar.gz)

**Comment by olivere** [comment]
I see. They introduced this `X-Opaque-Id` header somewhere in 6.x and I think I didn't yet add it everywhere. BTH I think we should be able to add headers to each and every request, not only a particular type of endpoint. I will see how we can achieve that transparently.

**Comment by olivere** [comment]
I added this to `ReindexService` as part of 6.2.17 release (352af50).
