### ISSUE TITLE
Retrieve the generated elasticsearch query to include in the response

### ISSUE THREAD

**Issue by casertap** [olivere/elastic#1035]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?
[X ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
I would like to somehow get the generated query to elasticsearch to include it in my response. Could be a string or a json object.

### Please describe the actual behavior
I am using the DSLQuery example: https://github.com/olivere/elastic/wiki/QueryDSL
I pretty much do what the `Find` method in the example do.
I create a `service`, build the query and trigger a search: `sr, err := search.Do(ctx)`
I then, parse the response and construct my custom response to return to my client 

How can I intercept the generated elasticsearch query and include it in response as a `json.RawMessage` or if not possible a `string` ?

Thanks

**Comment by olivere** [comment]
To get the generated request body, you can do this:

```
var query elastic.Query
...
query = ... generate some query ...
...
src, err := query.Source()
if err != nil {
  ...
}
out, err := json.Marshal(src)
if err != nil {
  ...
}
fmt.Printf("Generated query:\n%s\n", out)
```

If you want to trace the data sent between client and server, you can enable [trace logging](https://github.com/olivere/elastic/wiki/Logging).

HTH

**Comment by casertap** [comment]
Hi @olivere 
Still trying to do the same thing few months later, sorry.
I did not find a solution to go from my `SearchService` to the `Source` of the query
I have this
```
	search := client.Search().Index(indexName).Type(typeName).Pretty(f.pretty)
	search = f.query(search)
	search = f.aggs(search)
	search = f.postfilter(search)
	search = f.sorting(search)
	search = f.paginate(search)
	search = f.collapse(search)
	sr, err := search.Do(ctx)
```
How can I extract the `Source` from the `SearchService` please?

**Comment by olivere** [comment]
There currently is no way to get the generated API request sent to Elasticsearch. There are builders for queries etc., and that's what you asked for in the issue. But that's different to getting the whole HTTP request as sent to Elasticsearch.

As a workaround, you can create a [`SearchSource`](https://github.com/olivere/elastic/blob/release-branch.v7/search_source.go) that [can be passed to the `SearchService`](https://github.com/olivere/elastic/blob/release-branch.v7/search.go#L46-L53) (it is used by `SearchService` under the covers anyway). That `SearchService` has a [`Source` method](https://github.com/olivere/elastic/blob/release-branch.v7/search_source.go#L357-L580) that might help in what you want (excluding query parameters sent in the URL).
