### ISSUE TITLE
search query not working for particular key

### ISSUE THREAD

**Issue by kchetans** [olivere/elastic#1036]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ *] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behaviour
**I am trying to get data by candidateId from elastic** 
```
my Json
  {
 	"candidateId": "123",
 	"contactDetails": {
 		"address": "",
 		"city": "",
 		"communicationAddress": {
 			"city": ""
 		}
 	}
 }
```

when i used 
### for get all data 
```
query := elastic.MatchAllQuery{}
    result, err := rs.GetElasticSearch().Search().Index("candidate").Query(query).Do(context.Background())
	if err != nil{
		fmt.Println("err",err.Error())
		if err != nil {
				panic(err)
		}
		return
	}
	fmt.Printf("Query took %d milliseconds\n", result.TookInMillis)
  
```     
###  I tried
 ```
  termQuery := elastic.NewTermQuery("candidateId", "123")
  result, err:=rs.GetElasticSearch().Search().Index("candidate").Query(termQuery).Do(context.Background())
	if err != nil{
		fmt.Println("err",err.Error())
		if err != nil {
				panic(err)
		}
		return
	}
	fmt.Printf("Query took %d milliseconds\n", result.TookInMillis)
       

```
### AND
  ```

     query := elastic.NewBoolQuery()
	musts := []elastic.Query{elastic.NewTermQuery("candidateId", "123")}
	query = query.Must(musts...)
  result, err := rs.GetElasticSearch().Search().Index("candidate").Query(query).Do(context.Background())
	if err != nil{
		fmt.Println("err",err.Error())
		if err != nil {
				panic(err)
		}
		return
	}
	fmt.Printf("Query took %d milliseconds\n", result.TookInMillis)

```
### In both case I got 
```
  {
    "result": {
        "hits": {
            "total": 0
        },
        "_shards": {
            "total": 5,
            "successful": 5,
            "failed": 0
        }
    }
}


```

**Comment by olivere** [comment]
What type is `userName` and `candidateId`. Please post the results this curl call:

```
curl '<your-es-instance-url>/candidate/_mapping?pretty=true
```

I guess you're confusing ES with a database. When you need exact matches and use a `string` mapping, you need to do `userName.keyword`instead of `userName`.

**Comment by kchetans** [comment]
@olivere 
In curl or kibana it's coming perfect but using golang above query not working
**It's candidateId**
> http://localhost:9200/candidate/_mapping?pretty=true


```
{
	"candidate": {
		"mappings": {
			"_doc": {
				"properties": {
					"candidateId": {
						"type": "text",
						"fields": {
							"keyword": {
								"type": "keyword",
								"ignore_above": 256
							}
						}
					},
					"contactDetails": {
						"properties": {
							"address": {
								"type": "text",
								"fields": {
									"keyword": {
										"type": "keyword",
										"ignore_above": 256
									}
								}
							},
							"city": {
								"type": "text",
								"fields": {
									"keyword": {
										"type": "keyword",
										"ignore_above": 256
									}
								}
							},
							"communicationAddress": {
								"properties": {
									"address1": {
										"type": "text",
										"fields": {
											"keyword": {
												"type": "keyword",
												"ignore_above": 256
											}
										}
									},
									"city": {
										"type": "text",
										"fields": {
											"keyword": {
												"type": "keyword",
												"ignore_above": 256
											}
										}
									},
									"country": {
										"type": "text",
										"fields": {
											"keyword": {
												"type": "keyword",
												"ignore_above": 256
											}
										}
									},
									"countryId": {
										"type": "text",
										"fields": {
											"keyword": {
												"type": "keyword",
												"ignore_above": 256
											}
										}
									}
								}
							}


						}
					}
				}
			}
		}
	}
}
```

**Comment by olivere** [comment]
Replace

```
elastic.NewTermQuery("candidateId", "123")
```

with

```
elastic.NewTermQuery("candidateId.keyword", "123")
```

and it'll work.

You can see the problem here:

```
...
"candidateId": {
  "type": "text",
  "fields": {
    "keyword": {
      "type": "keyword",
      "ignore_above": 256
    }
  }
},
...
```

The field `candidateId` is mapped to type `text`. Type [`text`](https://www.elastic.co/guide/en/elasticsearch/reference/current/text.html) is used to index full-text data by means of an analyzer. It is by no-means similar to what a database column of e.g. type `varchar` does. What you really want is type [`keyword`](https://www.elastic.co/guide/en/elasticsearch/reference/current/keyword.html), which is also available as you can see by your mapping, with the same field: You only have to append `.keyword` to the field name, hence `candidateId.keyword`.

If you want an exact match with a string, you typically need to do it against fields of type `keyword`. Also notice that you can't sort a field of type `text`, but you can sort a field of type `keyword`.

Please [read the documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-data-types.html), especially [this blog post regarding the removal of the `string` type](https://www.elastic.co/blog/strings-are-dead-long-live-strings).

Elasticsearch is NOT a database.

**Comment by olivere** [comment]
Sorry, the link to the documentation was wrong. [This one is better](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-types.html).
