### ISSUE TITLE
Restore endpoints

### ISSUE THREAD

**Issue by scotthew1** [olivere/elastic#1037]
I've been playing with the snapshot endpoints, but just realize that the restore endpoint isn't supported yet. is there any plan to add support for this in the near future?

### Which version of Elastic are you using?

[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

**Comment by olivere** [comment]
Sure, that can be easily added as well. I will mark it as a todo for the next release. It's not that hard.

**Comment by olivere** [comment]
Just merged and about to be released.
