### ISSUE TITLE
Specifying min_score in UpdateByQuery

### ISSUE THREAD

**Issue by IchorPop** [olivere/elastic#1039]
### Which version of Elastic are you using?

[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

Sorry if this is a simple question; I have looked at the unit tests and the documentation but can't figure it out:

How would I specify min_score in the UpdateByQuery function? Essentially I want to write the following in Go:

```
POST index_name/_update_by_query
{
  "script": {
    "source": "ctx._source.f_name='johnny'",
    "lang": "painless"
  },
    "query":{
      "bool" : {
        "must": [
          {"match":{"f_name" : "john"}},
          {"match":{"l_name" : "smith"}}
          ]
      }
    },
    "min_score":1.0
}
```

I have this so far, which is just missing the min_score part:

```
condition1 := elastic.NewMatchQuery("f_name","john")
condition2 := elastic.NewMatchQuery("l_name","smith")
query := elastic.NewBoolQuery().Must(condition1,condition2)
script := elastic.NewScript("ctx._source.f_name = 'johnny'")
result,err := client.UpdateByQuery().
    Index(index).
    Type("_doc").
    Query(query).
    Script(script).
    Do(ctx)

```

**Comment by olivere** [comment]
I think you have to use SearchSource, for min_score is rather “unusual” (as they say in the docs here: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-min-score.html).

SearchSource is basically a query plus all search-related stuff. I’ll check if I can make min_score more accessible in a future release.

**Comment by olivere** [comment]
Hmm... it seems UpdateByQuery doesn’t yet use SearchSource (like SearchService does). So unfortunately, it may not be possible to set min_score yet. I’ll have to refactor UpdateByQuery 😞

**Comment by IchorPop** [comment]
Thanks for the quick reply. This is odd, since 

```
condition1 := elastic.NewMatchQuery("f_name","john")
condition2 := elastic.NewMatchQuery("l_name","smith")
query := elastic.NewBoolQuery().Must(condition1,condition2)
script := elastic.NewScript("ctx._source.f_name = 'johnny'")
result,err := client.UpdateByQuery().
    Index(index).
    Type("_doc").
    Query(query).
    Script(script).
    Do(ctx)
```

updates all returned documents, even those with extremely low scores. Is there that updates on exact matches?

**Comment by olivere** [comment]
The documents to be updated are those that match the query, no? So if you want exact matches, you probably want TermQuery, TermsQuery etc.

**Comment by IchorPop** [comment]
Ah yes, I was trying to use min_score to get reliable matches, but I should be using TermQuery or TermsQuery. Thanks you!

**Comment by olivere** [comment]
I think this issue is resolved with a workaround. Closing for now.
