### ISSUE TITLE
change Id to ID in 3.0 version?

### ISSUE THREAD

**Issue by dashaus** [olivere/elastic#104]
Hi!,
I have read [CHANGELOG for 3.0 version](https://github.com/olivere/elastic/blob/release-branch.v3/CHANGELOG-3.0.md), and I have a doubt... Do you intend to change Id to ID?. For example:

`ScrollId` 
to 
`ScrollID`

```go
res, err = client.Get().Index("one").Type("tweet").Id("no-such-id").Do()
```
to
```go
res, err = client.Get().Index("one").Type("tweet").ID("no-such-id").Do()
```

**Comment by olivere** [comment]
I have mixed feelings about it. While it's probably more idiomatic Go there is no real value for end-users. While I also prefer `.ID(...)` or `.ScrollID(...)`, it feels awkward as a paremeter, e.g. in `.Do(scrollID string)`. What are your pros/cons to it?

**Comment by dashaus** [comment]
Yes, I only say it because is the idiomatic way (and for me, is cleaner because it would have more consistency with another libraries) but I don't have problem to see `Id` instead of `ID`, this is a minor problem.

Thanks!

**Comment by olivere** [comment]
I'll put it on my todo list for 3.0. BTW: You're welcome to test Elastic 3 with ES 2.0 :-)

**Comment by dashaus** [comment]
ok, thanks! :+1:

**Comment by olivere** [comment]
For self-reference: Perhaps change awkward `scrollID` parameters to just `scroll` like in [this example](https://github.com/nlopes/slack/commit/74f694f00b7277e3823415cdfe1aabc3ff2e435e).

**Comment by olivere** [comment]
I'm sorry but I decided not to change `Id` to `ID` in 3.0.
