### ISSUE TITLE
Error 400 (Bad Request): request body is required [type=parse_exception]

### ISSUE THREAD

**Issue by zionhuang** [olivere/elastic#1041]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v6 (for Elasticsearch 6.x)
[~] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
```
func UpdateWorksheet(ctx context.Context, es *WorksheetES) (err error) {
	_, err = esClient.Index().
		Index(indexName).
		Type("detail").
		Id(fmt.Sprintf("%d", *stringToInt64Point(es.ID))).
		BodyJson(es).
		Do(ctx)
	return
}
```
struct as bodyJson to update, most success, but occasionally  appear 400
### Please describe the actual behavior
Error 400 (Bad Request): request body is required [type=parse_exception]
### Any steps to reproduce the behavior?
occasionally  appear

**Comment by olivere** [comment]
Maybe sometimes `es` is `nil`, or creates invalid JSON? Could also be a data race. Hard to test without a reproducible test case. I can assure you that Index API works fine. We're indexing millions of documents every day.

**Comment by olivere** [comment]
Maybe you can [enable the trace log](https://github.com/olivere/elastic/wiki/Logging) and see what's actually being sent over the wire. Let me know if the problem persists.
