### ISSUE TITLE
if I use domain ,get panic: no active connection found: no Elasticsearch node available

### ISSUE THREAD

**Issue by hantmac** [olivere/elastic#1042]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

- elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
`connect to es successfully.`

### Please describe the actual behavior
`panic: no active connection found: no Elasticsearch node available`

### Any steps to reproduce the behavior?
```
var client *elastic.Client
//use domain
//var host = "http://user:password@xxxx.com"
// use ip
var host = "http://user:password@11.1.1.1:9200"
If I use domain, connect to es failed.
if I use ip, successfully.
```

**Comment by olivere** [comment]
From the example code, it looks like you forgot the port number in the host variable. Just a typo?

**Comment by hantmac** [comment]
> forgot the port number in the host variable.
if I forgot the port number in the host variable, which port number will be used by default?

**Comment by olivere** [comment]
If you specify the host by yourself, you’re responsible for passing the correct details, including the port. If you don’t pass the URL, http://127.0.0.1:9200 is used by default.

**Comment by hantmac** [comment]
> If you specify the host by yourself, you’re responsible for passing the correct details, including the port. If you don’t pass the URL, http://127.0.0.1:9200 is used by default.
> […](#)
> Am 16.02.2019 um 14:58 schrieb Jack ***@***.***>: forgot the port number in the host variable. if I forgot the port number in the host variable, which port number will be used by default? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

I mean, if my domain name is followed by a SLB that helps me forward to the ES node, does this package support this usage?

**Comment by olivere** [comment]
If you use a Load Balancer, you should disable sniffing (see the Wiki). Otherwise it will pick up the node IPs returned by the cluster and do round-robin.

**Comment by hantmac** [comment]
> If you use a Load Balancer, you should disable sniffing (see the Wiki). Otherwise it will pick up the node IPs returned by the cluster and do round-robin.

That works for me!
Thanks!
