### ISSUE TITLE
The query result is empty

### ISSUE THREAD

**Issue by admover** [olivere/elastic#1044]
I use ajax to query every 10 seconds.

### Which version of Elastic are you using?
[-] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
I hope to find it every time.

### Please describe the actual behavior
But, the result is 
![image](https://user-images.githubusercontent.com/8574628/53080443-a804c580-3533-11e9-8f3e-e9311434e647.png)

my code:
```
func getAggBusi() ([]Business, error) {
	mapQuery := elastic.NewBoolQuery()
	mapQuery = mapQuery.Filter(elastic.NewRangeQuery("timestamp").Gte("now-5m").Lt("now"))
	mapQuery = mapQuery.Must(elastic.NewMatchQuery("gl2_source_input", "584a6f843ea66d52526320f2"))

	domainAgg := elastic.NewTermsAggregation()
	domainAgg = domainAgg.Field("domain").Size(10)

	searchResult, err := common.DBElastic.Search().
		Query(mapQuery).
		Size(0).
		Aggregation("domain", domainAgg).
		Pretty(true).
		Do(context.Background())
	if err != nil {
		return nil, err
	}

	domAggs, found := searchResult.Aggregations.Terms("domain")
	if !found {
		return nil, err
	}

	log.Println(domAggs.Buckets)  // line 51

	var business []Business
	for _, domAggItem := range domAggs.Buckets {
		business = append(business, Business{
			Name:  domAggItem.Key.(string),
			Count: domAggItem.DocCount,
		})
	}

	return business, nil
}
```

### Any steps to reproduce the behavior?
yes

**Comment by olivere** [comment]
I'm not sure why this happens. I'm using this successfully in a variety of applications. Maybe you can [enable the trace log](https://github.com/olivere/elastic/wiki/Logging) to see what's being sent on the wire, then post that here.
