### ISSUE TITLE
Compression for PercentilesAggregation not working.

### ISSUE THREAD

**Issue by mca312** [olivere/elastic#1045]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v6 (for Elasticsearch 6.x)
[X] elastic.v5 (for Elasticsearch 5.x) (5.6.14)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
When adding .Compression(10) to a Percentiles Aggregation, the compression gets added correctly to the ES aggregation.  The documentation described here (https://www.elastic.co/guide/en/elasticsearch/reference/5.6/search-aggregations-metrics-percentile-aggregation.html#search-aggregations-metrics-percentile-aggregation-compression) says to add compression, the query needs 
```
"percentiles" : {
   "field" : "load_time",
   "tdigest": {
      "compression" : 200 
   }
}
```

### Please describe the actual behavior
Compression is being added to the query as:
```
"percentiles" : {
   "field" : "load_time",
   "compression" : 200 
}
```

Resulting in the error "Error 400 (Bad Request): [percentiles] unknown field [compression]"

### Any steps to reproduce the behavior?
NewPercentilesAggregation().Field("load_time").Percentiles(20).Percentiles(80).Compression(10)

**Comment by olivere** [comment]
Yes, this seems like a bug. Thanks for reporting.

[This seems wrong](https://github.com/olivere/elastic/blob/release-branch.v6/search_aggs_metrics_percentiles.go#L118-L120). It should be [generated like this (v6)](https://github.com/elastic/elasticsearch/blob/6.7/server/src/main/java/org/elasticsearch/search/aggregations/metrics/percentiles/PercentilesAggregationBuilder.java#L284-L293) and [like this for v5](https://github.com/elastic/elasticsearch/blob/5.6/core/src/main/java/org/elasticsearch/search/aggregations/metrics/percentiles/PercentilesAggregationBuilder.java#L245-L254).

**Comment by olivere** [comment]
This should be handled correctly in 6.2.17 and 5.0.80.
