### ISSUE TITLE
geo_distance

### ISSUE THREAD

**Issue by aloneliu** [olivere/elastic#1046]
how to  build this???????

{
  "from":0,
  "size":5,
  "sort": { 
  	"_geo_distance" : { 
  		"order" :"asc",
  		"unit" : "km",
  		"location" : { 
  			"lat"  : "31.46667",   "lon" : "121.10000 "
  		}
  	} 
  },
			"query": {
    "bool": {
      "filter": {
       "match": {
          "type": "comments"
        }
      }
    }
  }
}

**Comment by olivere** [comment]
Please have a look at the tests. It's a bit of a hassle, I agree. But there is no way I can write all of those queries being asked for.

Without any guarantee, it should be something like this (not tested!):

```
matchQ := elastic.NewMatchQuery(...)
query := elastic.NewBoolQuery().Filter(matchQ)
sort := elastic.NewGeoDistanceSort("location").
		Point(31.46667, 121.1).
		Order(true).
		Unit("km")
res, err := client.Search().Query(query).From(0).Size(5).Sort(sort)
```

See [`sort_test.go`](https://github.com/olivere/elastic/blob/release-branch.v6/sort_test.go), [`search_queries_match_test.go`](https://github.com/olivere/elastic/blob/release-branch.v6/search_queries_match_test.go) etc.
