### ISSUE TITLE
Include template name in template response

### ISSUE THREAD

**Issue by chambodn** [olivere/elastic#1049]
Hi,
My point is more a question or a feature request than a pure issue.

### Which version of Elastic are you using?

[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
Executing 
```
esClient.IndexGetTemplate("").Do(context.Background())
```
I want to retrieve the complete list of templates stored **including names**. However, the struct
https://github.com/olivere/elastic/blob/cb2d6d05f9451337c8852815c23ca057922687eb/indices_get_template.go#L126-L133
does not include template name. 

### Please describe the actual behavior
Is there a way to enhance the actual _IndicesGetTemplateResponse_ to include "template_name"?

### Any steps to reproduce the behavior?
N/A

**Comment by olivere** [comment]
Of course. If that field exists in the response, it must be returned. I’ll investigate.

**Comment by chambodn** [comment]
Oups... Actually `esClient.IndexGetTemplate("").Do(context.Background())` returns a map[string]*IndicesGetTemplateResponse where key is actually the template name...

https://github.com/olivere/elastic/blob/f82cf7c66881f3f18d0354a68086e9aa2f9a48d1/indices_get_template.go#L95-L123

No need to investigate...
