### ISSUE TITLE
Range filter and Terms Filter

### ISSUE THREAD

**Issue by tommoholmes** [olivere/elastic#105]
i have query such `{
    "query": {
        "filtered": {
            "query": {
                "query_string": {
                    "query": "laptop"
                }
            },
            "filter": {
                "and": [
                    {
                       "range": {
                        "value": {
                        "gte": 3799000,
                        "lte": 10950000
                        }
                      },
                    },
                    {
                     "terms" : { "brand" : ["apple", "samsung"] }
                    }
                ]
            }
        }
    }
}`
and when i'm using your api code like
`q := elastic.NewQueryFilter(NewQueryStringQuery(json.Title))
            q := elastic.NewAndFilter()
            rangeFilter := elastic.NewRangeFilter("price").From(0).To(25880000)
            q = q.Add(rangeFilter)
            termsBrands := elastic.NewTermsFilter("brand", "apple", "samsung")
            q = q.Add(termsBrands)
            // rangeFilter := elastic.NewRangeFilter("price").From(json.Range.Min).To(json.Range.Max)
            builder := client.Search().Index("witch").Query(&q).From(json.Limit.From).Size(json.Limit.Size).Sort("price", true)
            searchResult, err := builder.Do()
                if err != nil {
                    panic(err)
                }`
and this error is `SearchPhaseExecutionException[Failed to execute phase [query], all shards failed`

**Comment by olivere** [comment]
Can you post the output of the elasticsearch.log file for that request? It should contain more hints about the source of the problem.

**Comment by tommoholmes** [comment]
this is error log `http: panic serving 127.0.0.1:35205: elastic: Error 400 (Bad Request): SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[dp_M3az2TOWR0-uKF0Q9Ag][witch][0]: SearchParseException[[witch][0]: from[0],size[-1]: Parse Failure [Failed to parse source [{"from":0,"query":{"and":{"filters":[{"range":{"price":{"from":0,"include_lower":true,"include_upper":true,"to":25880000}}},{"terms":{"brand":["apple","samsung"]}}]}},"size":21,"sort":[{"price":{"order":"asc"}}]}]]]; nested: QueryParsingException[[witch] No query registered for [and]]; }{[dp_M3az2TOWR0-uKF0Q9Ag][witch][1]: SearchParseException[[witch][1]: from[0],size[-1]: Parse Failure [Failed to parse source [{"from":0,"query":{"and":{"filters":[{"range":{"price":{"from":0,"include_lower":true,"include_upper":true,"to":25880000}}},{"terms":{"brand":["apple","samsung"]}}]}},"size":21,"sort":[{"price":{"order":"asc"}}]}]]]; nested: QueryParsingException[[witch] No query registered for [and]]; }{[dp_M3az2TOWR0-uKF0Q9Ag][witch][2]: SearchParseException[[witch][2]: from[0],size[-1]: Parse Failure [Failed to parse source [{"from":0,"query":{"and":{"filters":[{"range":{"price":{"from":0,"include_lower":true,"include_upper":true,"to":25880000}}},{"terms":{"brand":["apple","samsung"]}}]}},"size":21,"sort":[{"price":{"order":"asc"}}]}]]]; nested: QueryParsingException[[witch] No query registered for [and]]; }{[dp_M3az2TOWR0-uKF0Q9Ag][witch][3]: SearchParseException[[witch][3]: from[0],size[-1]: Parse Failure [Failed to parse source [{"from":0,"query":{"and":{"filters":[{"range":{"price":{"from":0,"include_lower":true,"include_upper":true,"to":25880000}}},{"terms":{"brand":["apple","samsung"]}}]}},"size":21,"sort":[{"price":{"order":"asc"}}]}]]]; nested: QueryParsingException[[witch] No query registered for [and]]; }{[dp_M3az2TOWR0-uKF0Q9Ag][witch][4]: SearchParseException[[witch][4]: from[0],size[-1]: Parse Failure [Failed to parse source [{"from":0,"query":{"and":{"filters":[{"range":{"price":{"from":0,"include_lower":true,"include_upper":true,"to":25880000}}},{"terms":{"brand":["apple","samsung"]}}]}},"size":21,"sort":[{"price":{"order":"asc"}}]}]]]; nested: QueryParsingException[[witch] No query registered for [and]]; }]`

**Comment by olivere** [comment]
Hmm... something is wrong. Can you try this and see if that works against your index?

```go
package main

import (
	"encoding/json"
	"log"

	elastic "gopkg.in/olivere/elastic.v2"
)

func main() {
	qs := elastic.NewQueryStringQuery("laptop")
	af := elastic.NewAndFilter()
	af = af.Add(elastic.NewTermsFilter("brand", "apple", "samsung"))
	af = af.Add(elastic.NewRangeFilter("price").From(0).To(2000))

	fq := elastic.NewFilteredQuery(qs).Filter(af)
	ss := elastic.NewSearchSource().Query(&fq)

	src := ss.Source()
	out, err := json.MarshalIndent(src, "", "  ")
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("%s", string(out))
}
```

If not, let me know the elasticsearch.log output.

**Comment by tommoholmes** [comment]
Oke thanks Oliver

**Comment by tommoholmes** [comment]
what if i have terms in array
` af = af.Add(elastic.NewTermsFilter("brand", [apple,dell]
))`

**Comment by olivere** [comment]
I'm not sure I understand. What you posted is invalid Go code. Please read e.g. [Arrays and Slices](http://blog.golang.org/go-slices-usage-and-internals). You're probably looking for `...` to "expand" the array.
