### ISSUE TITLE
Go client requires _type to be set, while ES itself does not require it

### ISSUE THREAD

**Issue by starius** [olivere/elastic#1050]
### Which version of Elastic are you using?

[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

Go client does not return error if I do not set `_type`. (`Type()` methods.) 

### Please describe the actual behavior

Go client returns error if I do not set `_type`.

### Any steps to reproduce the behavior?

Just use `Index` service without setting `_type` with `Type()` method. Go client returns error:
https://github.com/olivere/elastic/blob/f82cf7c66881f3f18d0354a68086e9aa2f9a48d1/index.go#L236-L238
Comment out those strings and then it works and ES response is OK.

**Comment by olivere** [comment]
Hmm. In [the latest REST API spec for 6.x](https://github.com/elastic/elasticsearch/blob/6.7/rest-api-spec/src/main/resources/rest-api-spec/api/index.json#L18-L22) the `type` is still marked as required.

**Comment by olivere** [comment]
In the [7.x branch](https://github.com/elastic/elasticsearch/blob/7.x/rest-api-spec/src/main/resources/rest-api-spec/api/index.json#L18-L21) it is no longer required. This is in line with the plan for [removing mapping types](https://www.elastic.co/guide/en/elasticsearch/reference/6.7/removal-of-types.html).
