### ISSUE TITLE
Unable to create new connection after tunnelling

### ISSUE THREAD

**Issue by akshaynitsxr** [olivere/elastic#1052]
### Which version of Elastic are you using?

[ x] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
The connection should be established with DB on  `client, err = elastic.NewClient(elastic.SetURL( url ) )`

### Please describe the actual behavior
Getting an error **context deadline exceeded** while trying to create NewClient on elasticsearch using tunnelling.
The curl result is giving the proper response though.

### Any steps to reproduce the behavior?
After tunnelling I am getting an error **context deadline exceeded** on 
`client, err = elastic.NewClient(elastic.SetURL( url ) )`

**Comment by olivere** [comment]
If you're doing anything in between the connection between your client and Elasticsearch, you must almost always disable sniffing.

```
client, err = elastic.NewClient(..., elastic.SetSniff(false))
```

Please [read the wiki](https://github.com/olivere/elastic/wiki/Sniffing).
