### ISSUE TITLE
how to get search rate ( aggregation) ?

### ISSUE THREAD

**Issue by hackertron** [olivere/elastic#1056]
Hello , newbie here. I want help with getting search rate from elasticsearch , something like this but i am not sure how to get that aggregation 

`
{
	"searchRate": [
		{
			"key_as_string" : "2019-03-13T13:26:30.000Z",
			"key" : 1550064390000,
			"doc_count": 0,
			"rate": 0,
		},
		{
			"key_as_string" : "2019-03-14T13:27:00.000Z",
			"key" : 1550064420000,
			"doc_count": 9,
			"rate": 1.633,
		}
	]
}
`

**Comment by olivere** [comment]
I guess you're looking for an [aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations.html). What kind of aggregation is that?
