### ISSUE TITLE
script fails during string concatenation

### ISSUE THREAD

**Issue by abhirj87** [olivere/elastic#1059]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

Expected case:
GET someindex/_search?size=0
```
{
  "aggs": {
    "cr_time": {
      "terms": {
        "script": {
          "lang": "painless",
          "source": "((doc['long_field'].value/86400)*86400) + ' '"          
        }
      }
    }
  }
}
```

Same doesn't work when I try to use the following

`elastic.NewScript(" ((doc['long_field'].value/86400)*86400) + ' '").Lang("painless")`
It throws error: 
```
"elastic: Error 500 (Internal Server Error): all shards failed [type=search_phase_execution_exception]"
```

If I remove the string concatenation part then it works:
`elastic.NewScript(" ((doc['long_field'].value/86400)*86400)").Lang("painless")`

### Please describe the actual behavior
Following query works fine in Kibana not it the go elastic search client:
Expected case:
GET someindex/_search?size=0
```
{
  "aggs": {
    "cr_time": {
      "terms": {
        "script": {
          "lang": "painless",
          "source": "((doc['long_field'].value/86400)*86400) + ' '"          
        }
      }
    }
  }
}
```

### Any steps to reproduce the behavior?
1. NewScript fails when string concatenation is applied.
`elastic.NewScript(" ((doc['long_field'].value/86400)*86400) + ' '").Lang("painless")`
It throws error: 
```
"elastic: Error 500 (Internal Server Error): all shards failed [type=search_phase_execution_exception]"
```
2. It even fails when such a script is invoked as a stored script
```
POST _scripts/date_round
{
  "script":{
    "lang": "painless",
    "source":
    "((doc['long_value_field'].value/86400)*86400) + ' ' "
  }
}
```

Now, the following fails:
```elastic.NewScriptStored("date_round").Lang("painless")```

**Comment by olivere** [comment]
Can you please have a look into the ES log or enable trace logging to see the details of the error. This probably has nothing to do with the Go client but is a „normal“ ES issue.

**Comment by abhirj87** [comment]
Thanks for the update. I'll give it a try and let you know.

**Comment by olivere** [comment]
Closed for inactivity.
