### ISSUE TITLE
From size not working

### ISSUE THREAD

**Issue by tommoholmes** [olivere/elastic#106]
when I'm use `builder := client.Search().Index("witch").Query(&q).From(21).Size(42).Sort("price", true)`
it's display from 0 until 42
but when I'm use `builder := client.Search().Index("witch").Query(&q).From(0).Size(21).Sort("price", true)`
it's display from 0 until 21

**Comment by olivere** [comment]
With `from=21` and `size=42`, you will get 42 results, starting at result 21. You can read about `from/size` in the [Elasticsearch docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html). See also [this test](https://github.com/olivere/elastic/blob/master/search_source_test.go#L26).
