### ISSUE TITLE
[Feature] SAML Login 

### ISSUE THREAD

**Issue by messias72** [olivere/elastic#1060]
### Which version of Elastic are you using?

[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

Hi,

since we enable SAML we can not login with Basic Auth so we can not use this libary anymore.
It would be nice if someone can implement a SAML Login / Auth.

Infos: https://www.elastic.co/guide/en/x-pack/current/_configure_elasticsearch_for_saml_authentication.html
https://www.elastic.co/blog/how-to-enable-saml-authentication-in-kibana-and-elasticsearch

best regards

**Comment by olivere** [comment]
I'm not a SAML expert, but can't you try to [wrap the `*http.Client`](https://github.com/olivere/elastic/wiki/HttpTransport) with a SAML library like e.g. [`github.com/crewjam/saml`](https://github.com/crewjam/saml).

**Comment by messias72** [comment]
Hi,

if I understand the library this is for a IDP and SP implementation but I only want to login to an application and do not want to write my own. The SP is elasticsearch and the IDP is already connected to elasticsearch. Im looking for a library for an easy login to a SAML proteced site.
Thx for your help.

best regards

**Comment by olivere** [comment]
You're probably right. As I said, I'm not an expert with SAML. With OAuth 2.0 you can abstract away the task of initial authentication and refreshing tokens with [`github.com/golang/oauth2`](https://github.com/golang/oauth2). In the end, it [gives you a `*http.Client`](https://github.com/golang/oauth2/blob/master/example_test.go#L47) that wraps the OAuth stuff and you can use it like a normal HTTP client. I though there might be something out there that does the same for SAML.

I would prefer that approach as authentication is orthogonal to what this library is trying to solve.
