### ISSUE TITLE
Its taking more time to close the exisiting client connection

### ISSUE THREAD

**Issue by orangemail** [olivere/elastic#1062]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior

I'm have opened a connection like following inside a function.

// Create a client and connect to http://192.168.2.10:9201
client, err := elastic.NewClient(elastic.SetURL("http://192.168.2.10:9201"))
if err != nil {
  // Handle error
  panic(err)
}
defer client.Stop().

Issue is it takes, more than 2 min to close the function. 
I understand that client.Stop() will be executed only after function exits. The outcome of the function I'm getting less than 10 seconds. 

Is there any way to specify time to close the connection?

**Comment by orangemail** [comment]
Any suggestions ?

**Comment by olivere** [comment]
Hmm... I usually create one client in the `main` function of the application and don't call `Stop`, as the application will exit anyway when `main` exits. How do you setup your `client`?

**Comment by orangemail** [comment]
Hi Olivere..Thanks for response....

Actually, my application does not exists. It is server which listens for some inputs,
and based on those inputs I will open a Elastic client, fetch data from elastic and need to close the 
elastic DB connection.......

Elastic Client is called inside a Handler function. 
Now after I quit that handler I expect that, DB connection to get closed since I use client.Stop().
It it stopping, but it takes more 1 to 2 min to close the connection.

Handler expection is completing with less than 5 sec, but closing the DB connection is taking much time.

**Comment by olivere** [comment]
If you use Elastic on a request scope, you should definitely switch to [`elastic.NewSimpleClient`](https://github.com/olivere/elastic/wiki/Client#newsimpleclient). It opens a connection much more quickly and closing is not necessary because it doesn't start any other goroutines for e.g. healthchecks and sniffing. Use [`elastic.NewClient`](https://github.com/olivere/elastic/wiki/Client) for a long-running client that can be shared by many goroutines.

**Comment by orangemail** [comment]
Ya sure, I will try using it.. 
Just on doubt, whether NewSimpleClient will support all the configurations supported by NewClient. 
List of configurations are given below.

https://github.com/olivere/elastic/wiki/Configuration

**Comment by olivere** [comment]
In general, yes. See [here](https://github.com/olivere/elastic/blob/release-branch.v6/client.go#L243-L248). But e.g. enabling the sniffer when the sniffing process isn't started is certainly a no-op.

**Comment by orangemail** [comment]
Thanks ..I will try the elastic.NewSimpleClient() with few options then.

**Comment by olivere** [comment]
I'll close this for now. If you keep having issues, just let me know and I'll re-open.

**Comment by orangemail** [comment]
Hi .. I tried working with elastic.NewSimpleClient(). I can still see connection is not getting closed immediately, after querying. With the command "netstat -tunlpa" I see that 9200 port is taking few delay around 2 to 3 min on average to close. I see the status as "TIME_WAIT" .. Is there any other suggestions ?

**Comment by olivere** [comment]
That might be normal behaviour with HTTP connections in the standard library. We use the normal HTTP client, but you may specify your own with different timeouts etc.

**Comment by orangemail** [comment]
It was taking around 1 min to close the connection now.  As you said that was dependent on HTTP settings defined in file /proc/sys/net/ipv4/tcp_fin_timeout.

Thanks for the info.  :-)
