### ISSUE TITLE
[Question] NewTemplateQuery has already removed ?

### ISSUE THREAD

**Issue by bokuweb** [olivere/elastic#1063]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

I would like to search with search template like following
```
/_search/template
{
  "id": "xxxxx",
  "params": {
    "size": 50,
    ....
  }
}
```

So, I found this test https://github.com/olivere/elastic/blob/master/search_queries_template_query_test.go#L25-L38.
However I can not use ` NewTemplateQuery` with v6.
Is it already removed?? What should I do to access `/_search/template` with v6??
Should I use `NewRawStringQuery` ?

**Comment by olivere** [comment]
What does „I cannot use“ actually mean? What is the error message? Did you enable trace log to get all the details of the error message that ES logs? If so, can you paste it here?

**Comment by bokuweb** [comment]
@olivere Sorry, I mistaken. It means I can not find `NewTemplateQuery` with v6.
Is this removed? If so what should I do to access /_search/template with v6??

<img width="533" alt="スクリーンショット 2019-04-01 14 19 31" src="https://user-images.githubusercontent.com/10220449/55304993-3b151180-5489-11e9-899b-59693e2f6c84.png">

**Comment by olivere** [comment]
Oh, I see. Hmm... that's strange. I have to look into this. Maybe it's been deprecated or has changed significantly in ES 6.x. If it didn't, you can simply copy over the query from v5. It should work right out of the box. That's at least a workaround.

**Comment by bokuweb** [comment]
@olivere Thanks for your response. I'll try that workaround. Sorry I don't know where should I see in v5.
If you are ok could you tell me where should I see and copy...

**Comment by olivere** [comment]
Now that you're asking, I've looked it up. The Template Query was [deprecated in 5.x](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/query-dsl-template-query.html), so it doesn't exist any more in ES 5.x and you should move away from it. Hence it does no longer exist in v5, v6 and v7.

You might copy it over from v3 (which targets ES 2.x), which is probably the latest version of it. See [`search_query_template.go`](https://github.com/olivere/elastic/blob/release-branch.v3/search_queries_template_query.go) in [`release-branch.v3`](https://github.com/olivere/elastic/tree/release-branch.v3).

**Comment by bokuweb** [comment]
@olivere Thanks for your response :)
I would like to access `_search/template` with v6 , do you have any examples about this?

https://www.elastic.co/guide/en/elasticsearch/reference/5.6/search-template.html

**Comment by olivere** [comment]
Unfortunately, that's still a missing feature. See #977.

**Comment by bokuweb** [comment]
Thanks
