### ISSUE TITLE
How to point an alias to a different index

### ISSUE THREAD

**Issue by rayjlinden** [olivere/elastic#1064]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[X ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

I'd like to swap an alias to point from index to another - as an atomic operation.
I've read how to do this on the Elasticsearch docs - but am unclear how to do that with this SDK.

Can I get a little guidance?

**Comment by olivere** [comment]
There are some tests that illustrate the syntax in [`indices_put_alias_test.go`](https://github.com/olivere/elastic/blob/release-branch.v6/indices_put_alias_test.go). Together with the [official documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html) it's just a bit trial and error.
