### ISSUE TITLE
How to get _id and _version from a search result?

### ISSUE THREAD

**Issue by loohill** [olivere/elastic#1067]
### Which version of Elastic are you using?

[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
Being able to get values of the `_id` and `_version` fields from the `SearchResult`

**Comment by olivere** [comment]
It's part of the [`SearchHit`](https://github.com/olivere/elastic/blob/release-branch.v6/search.go#L514-L537).
