### ISSUE TITLE
Update from 6.2.16 to 6.2.17 results in poor performance

### ISSUE THREAD

**Issue by VibyJocke** [olivere/elastic#1069]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[X] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behaviour
No change in request latencies when updating to 6.2.17. 

### Please describe the actual behaviour
Request latencies more than doubled.

### Any steps to reproduce the behaviour?
I just updated to 6.2.17 and noticed that all requests (measured with a timer around bulkRequest.Do()) took more than twice as long. Looking at the ES metrics I could find no abnormal behaviour regarding latencies or rates, and looking at tracing of my client code did not reveal anything either. Switched back to 6.2.16 and everything looked fine again.
I'm curious if anyone else has experienced this.

**Comment by olivere** [comment]
Interesting. I cannot see why that is. Here's the list of changes between the two versions: https://github.com/olivere/elastic/compare/v6.2.16...v6.2.17

Although there were changes in the `BulkService`, they shouldn't have any impact on the performance. https://github.com/olivere/elastic/commit/07d32edbf0aca2e283726a15f8c2a663d3ae202e is the only change to the code. Other changes were purely cosemtic, such as changing the links to the documentation from version 6.2 to 6.7.

**Comment by VibyJocke** [comment]
Yes, I looked through the commit log and couldn't find anything obvious either, so hopefully it's just something on my side, but I thought I would create an issue if anyone else have observed any similar problems. Below I've attached a screenshot from my environment during the time that 6.2.17 was deployed, and just switching back to .16 with no other changes restored the performance.
<img width="366" alt="Screenshot 2019-04-08 at 15 46 07" src="https://user-images.githubusercontent.com/6437192/55728960-7f6a5980-5a15-11e9-873e-1dac5f775281.png">

**Comment by olivere** [comment]
Are you using easyjson for that matter? I had to recreate the generated code for the serialiser die to the change of the Version type. Maybe we need to dig into that.

**Comment by VibyJocke** [comment]
> Are you using easyjson for that matter? I had to recreate the generated code for the serialiser due to the change of the Version type. Maybe we need to dig into that.

Interesting, yes, I'm setting UseEasyJSON on BulkIndexRequest, particularly because I experienced somewhat poor performance earlier (indexing perhaps unusually large bulks).

**Comment by olivere** [comment]
Hmm... yes, serialization in standard library is not the fastest in the world, but it works okay for the common use cases. Maybe then easyjson is the culprit here.

**Comment by VibyJocke** [comment]
Perhaps, but this also affected search performance.

**Comment by VibyJocke** [comment]
I disabled easyjson and tried to upgrade again and this time there was no performance difference compared with 6.2.16 👍 Why it affected search when I only set it on indexing requests I have yet to figure out, but that could likely be something strange with my code.

**Comment by VibyJocke** [comment]
Thank you for your quick response and help, this can be closed if you have no reason to keep it open 👍

**Comment by olivere** [comment]
Sure. Happy to help.
