### ISSUE TITLE
close connections

### ISSUE THREAD

**Issue by baxterbln** [olivere/elastic#107]
Hello,

in the moment we testing your really nice package on our application but we had a problem with the open connections to the elasticserver. After benchmarks test or in our testing environment we had a lot open (zombie) connections with TIME_WAIT. 

lsof -p say:
server  24086 root  276u  sock      0,7      0t0 63140932 can't identify protocol

netstat -an -p tcp
tcp        0      0 XXXXX:59824    XXX:9200         TIME_WAIT   -

Our connection func is:

func NewElasticSession() *elastic.Client {
	       
	httpClient := &http.Client{
		Transport: &BasicAuthTransport{
			username:  ReadIniString("elastic user"),
			password:  ReadIniString("elastic pass"),
		},
	}
	
        elastic.SetTraceLog(log.New(os.Stdout, "", log.LstdFlags))
        elastic.SetInfoLog(log.New(os.Stdout, "", log.LstdFlags))
        client, err := elastic.NewClient(
                elastic.SetHttpClient(httpClient),
                elastic.SetURL(elasticServer),
                elastic.SetSniff(true),
		elastic.SetHealthcheckInterval(10*time.Second),
		elastic.SetMaxRetries(5),
		elastic.SetErrorLog(log.New(os.Stderr, "ELASTIC ", log.LstdFlags)),
		elastic.SetInfoLog(log.New(os.Stdout, "", log.LstdFlags)))
	if err != nil {
		panic(err)
	}

	exists, err := client.IndexExists(index).Do()
	if err != nil {
		panic(err)
	}
	if !exists {
		_, err := client.CreateIndex(index).Do()
		if err != nil {
			panic(err)
		}
	}

	return client
}

**Comment by olivere** [comment]
Hi there! Hmm, I've been using Elastic on server processes for months and I've never come up with that. But your method name got my curious... Do you perhaps create one connection per session? You should really create just one (or a handful) client per app and share it.

**Comment by baxterbln** [comment]
Yes, that´s correct. I will try to set one connection on startup and shared ist with the functions

**Comment by baxterbln** [comment]
nope. Same result. Tested on three different servers. Do you have a example for how do use the client -> server call?

**Comment by olivere** [comment]
[This](https://gist.github.com/olivere/eaee7a20524ab2beba71) should do the trick.

**Comment by baxterbln** [comment]
Thank you olivere, looks better.;-)

**Comment by baxterbln** [comment]
hey, after testing same problem again. Sorry... We are testing with screaming frog and ab

If there a option to close the connection manually from your package?

Testing requests:

develop 22598 xxx    6u  IPv6 36817934      0t0     TCP localhost:28551->localhost:35451 (ESTABLISHED)
develop 22598 xxx    7u  IPv4 36823474      0t0     TCP 192.168.1.103:36854->xxx.xxx.xxx.xxx:9200 (ESTABLISHED)
develop 22598 xxx    8u  IPv4 36818914      0t0     TCP 192.168.1.103:56250->xxx.xxx.xxx.xxx:9200 (ESTABLISHED)
develop 22598 xxx    9u  IPv6 36817460      0t0     TCP localhost:28551->localhost:35455 (ESTABLISHED)
develop 22598 xxx   10u  IPv6 36817464      0t0     TCP localhost:28551->localhost:35456 (ESTABLISHED)
develop 22598 xxx   11u  IPv6 36817468      0t0     TCP localhost:28551->localhost:35457 (ESTABLISHED)
develop 22598 xxx   12u  IPv6 36817472      0t0     TCP localhost:28551->localhost:35458 (ESTABLISHED)
develop 22598 xxx   13u  IPv6 36817476      0t0     TCP localhost:28551->localhost:35459 (ESTABLISHED)
develop 22598 xxx   14u  IPv4 36820170      0t0     TCP 192.168.1.103:59606->xxx.xxx.xxx.xxx:9200 (ESTABLISHED)
develop 22598 xxx   15u  IPv4 36820185      0t0     TCP 192.168.1.103:33831->xxx.xxx.xxx.xxx:9200 (ESTABLISHED)
develop 22598 xxx   16u  IPv4 36820187      0t0     TCP 192.168.1.103:49130->xxx.xxx.xxx.xxx:9200 (ESTABLISHED)
develop 22598 xxx   17u  IPv4 36820554      0t0     TCP 192.168.1.103:36850->xxx.xxx.xxx.xxx:9200 (CLOSE_WAIT)
develop 22598 xxx   18u  IPv4 36821357      0t0     TCP 192.168.1.103:36852->xxx.xxx.xxx.xxx:9200 (CLOSE_WAIT)
develop 22598 xxx   19u  IPv4 36821419      0t0     TCP 192.168.1.103:36853->xxx.xxx.xxx.xxx:9200 (CLOSE_WAIT)
develop 22598 xxx   20u  IPv4 36823631      0t0     TCP 192.168.1.103:36856->xxx.xxx.xxx.xxx:9200 (ESTABLISHED)
develop 22598 xxx   21u  IPv4 36823683      0t0     TCP 192.168.1.103:36857->xxx.xxx.xxx.xxx:9200 (ESTABLISHED)
develop 22598 xxx   22u  IPv4 36824119      0t0     TCP 192.168.1.103:36858->xxx.xxx.xxx.xxx:9200 (ESTABLISHED)
develop 22598 xxx   23u  IPv4 36823880      0t0     TCP 192.168.1.103:36859->xxx.xxx.xxx.xxx:9200 (ESTABLISHED)
develop 22598 xxx   24u  IPv4 36824179      0t0     TCP 192.168.1.103:36861->xxx.xxx.xxx.xxx:9200 (ESTABLISHED)
develop 22598 xxx   25u  IPv4 36824199      0t0     UDP localhost:51594->xxx-Aspire-X1900:domain 

After 5 Minutes:

develop 22598 xxx    7u  sock      0,7      0t0 36823474 can't identify protocol
develop 22598 xxx    8u  IPv4 36818914      0t0      TCP 192.168.1.103:56250->xxx.xxx.xxx.xxx:9200 (ESTABLISHED)
develop 22598 xxx   14u  IPv4 36820170      0t0      TCP 192.168.1.103:59606->xxx.xxx.xxx.xxx:9200 (ESTABLISHED)
develop 22598 xxx   15u  IPv4 36820185      0t0      TCP 192.168.1.103:33831->xxx.xxx.xxx.xxx:9200 (ESTABLISHED)
develop 22598 xxx   16u  IPv4 36820187      0t0      TCP 192.168.1.103:49130->xxx.xxx.xxx.xxx:9200 (ESTABLISHED)
develop 22598 xxx   17u  sock      0,7      0t0 36820554 can't identify protocol
develop 22598 xxx   18u  sock      0,7      0t0 36821357 can't identify protocol
develop 22598 xxx   19u  sock      0,7      0t0 36821419 can't identify protocol
develop 22598 xxx   20u  sock      0,7      0t0 36823631 can't identify protocol
develop 22598 xxx   21u  sock      0,7      0t0 36823683 can't identify protocol
develop 22598 xxx   22u  sock      0,7      0t0 36824119 can't identify protocol
develop 22598 xxx   23u  sock      0,7      0t0 36823880 can't identify protocol
develop 22598 xxx   24u  sock      0,7      0t0 36824179 can't identify protocol
develop 22598 xxx   25u  sock      0,7      0t0 36826840 can't identify protocol

**Comment by olivere** [comment]
@baxterbln Hmm. This seems odd. To be honest I'm using Elastic in production for over a year now and haven't seen this, so I'm not sure what causes this.

I know this typically happens when you open a HTTP connection, read the body but forgot to close it e.g. with `defer resp.Body.Close()`. I'm not sure if closing connections manually is the root cause of the bug; it may hide a problem, but my experience is that they typically come back and hit you even harder.

Can you extract a small test program that illustrates the behaviour? Also: What OS (`uname -a`), Go (`go version`), and Elasticsearch (`curl 127.0.0.1:9200`) version are you using? Which version of Elastic are you using (and what's the import path)?

**Comment by baxterbln** [comment]
3.18.0-13-generic #14-Ubuntu SMP Fri Feb 6 09:55:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
go version go1.3.3 linux/amd64
Elasticsearch 1.7.0

For the go application we use gorilla as framwork. I show what a part i can extract and send you this code.

**Comment by olivere** [comment]
An example of your code would be perfect.

In the meantime can you check if a simple infinite loop [like this](https://gist.github.com/olivere/64023cb33dba39d7b5d3) increases the connection count? It doesn't do so here.

**Comment by olivere** [comment]
Just for reference: There was [an issue](https://github.com/golang/go/issues/6981) with not closing the response body on errors with Go 1.3. But it should have been fixed. Any reason not to upgrade to 1.4 (and 1.5 is just around the corner)?

**Comment by baxterbln** [comment]
no, the ist our test environment. on the production server we use at the moment 1.4.2.

The interesting part is with low traffic we had no problems with the close of the connections, its only a problem high traffic (more then 10-20 req/sec)

**Comment by baxterbln** [comment]
is fixed, fault on my side

**Comment by Vavilen** [comment]
baxterbln, I have a similar problem. How did you solve it? Thanks!

**Comment by lelvisl** [comment]
@baxterbln how did you solve it?

**Comment by olivere** [comment]
@lelvisl Do you perhaps create one client per request? With `elastic.NewClient`, you should only create one client per application. It's thread-safe and you can safely use one client with multiple goroutines.

**Comment by lelvisl** [comment]
@olivere I already solve this problem by custom http client
```go
	cli, err = elastic.NewSimpleClient(
		elastic.SetURL(c.Elastic.Url),
		elastic.SetHttpClient(&http.Client{Transport: &http.Transport{
			MaxIdleConns:       10,
			IdleConnTimeout:    30 * time.Second,
			DisableCompression: true,
			Dial: (&net.Dialer{
				Timeout:   30 * time.Second,
				KeepAlive: 30 * time.Second,
			}).Dial,
		}}),
	)
```

**Comment by anynone** [comment]
solve this problem by disableKeepAlives
```golang
		client, err := elastic.NewClient(
			elastic.SetURL(elasticHost),
			elastic.SetBasicAuth(elasticUser, elasticPass),
			elastic.SetSniff(false),
			elastic.SetHttpClient(&http.Client{Transport: &http.Transport{
				MaxIdleConns:       10,
				IdleConnTimeout:    30 * time.Second,
				DisableCompression: true,
				DisableKeepAlives: true,
				DialContext: (&net.Dialer{
					Timeout:   30 * time.Second,
					KeepAlive: 30 * time.Second,
				}).DialContext,
			}}))
```

**Comment by Yiling-J** [comment]
So in our load test case, we start 1 server pod and send 300 concurrency requests(total 100000 requests) using apache bench. And TIME_WAIT socket count keep increasing. I think the solution is just increasing **MaxIdleConnsPerHost**(default 2) to match your concurrency level per pod. This is how Go http works [link](https://stackoverflow.com/questions/39813587/go-client-program-generates-a-lot-a-sockets-in-time-wait-state).
