### ISSUE TITLE
The client is stateful

### ISSUE THREAD

**Issue by sorenvonsarvort** [olivere/elastic#1070]
# The problem

In `elastic.v6` when You invoke `client.Sort(...)` it should create a new client instance, instead of modifying the existing one.

The existing implementation leads to creepy bugs if You use sorting, paging in HTTP handlers:

```func HandleGet(client *elastic.SearchService) http.HanlderFunc { ... }```

Invoked several times `client = client.Sort("id", order)` creates the following JSON:

```json
"sort":[{"id":{"order":"desc"}}]
"sort":[{"id":{"order":"desc"}},{"id":{"order":"desc"}}]
```

# The question

Is this behavior is okay?

# The solution

One of he possible solutions is to copy the SearchService and return a pointer to the copy.

```go
// Sort adds a sort order.
func (s *SearchService) Sort(field string, ascending bool) *SearchService {
    ns := SearchService {
        s.pagingParameter,
        s.sortingParameters,
        s.allOtherParameters.
    }
    ns.sortingParameters.field = field
    ns.sortingParameters.ascending = ascending
    return &ns
}
```

**Comment by olivere** [comment]
The client is stateful, the services are not. Your parameter `client *elastic.SearchService` is misleading, as you're naming a `client` a `service`.

If you want to perform a query, instantiate it with the `client` (of type `*elastic.Client`), e.g.:

```
search := client.Search(...)
...
```

Use `search` hereafter for a single Search operation. You can certainly pass it around to other methods/functions, but remember a Service is request-scoped. [Here's an example from the wiki.](https://github.com/olivere/elastic/wiki/QueryDSL).

**Comment by sorenvonsarvort** [comment]
Excuse me for the misleading names.

Here is the correct case:

```go
func setupEndpoints(client *elastic.Client) {
    // We provide the handler with a search service instance, which knows in what index we are going to search
    r.Get("/articles", handleEntries(client.Search("articles")))
    r.Get("/users", handleEntries(client.Search("users")))
    r.Get("/etc", handleEntries(client.Search("etc")))
}

func handleEntries(searchService *elastic.SearchService) http.HandlerFunc {
    return func(w http.ResponseWriter, r *http.Request) {
        searchService.Query(...).Sort(...) // on every call the new sort parameters are appended to the existing ones
    }
}
```

To avoid such a behavior some workarounds must be introduced, which make the code more complex.

It is worth to say "Request scoped" means the "services" are designed to be used as request scoped, so the responsibility to maintain such a property lies with the user. I thing it is okay, but also this is not clearly enough stated in the docs.

In my opinion the "services" instances must be immutable, so I decided to fork and maintain own version.

Anyway, thank You for the greatest ES client in the Golang ecosystem and great support!

**Comment by olivere** [comment]
You should simply pass the `client`, now the `client.Search("...")`, then everything's fine.

I typically create a type per HTTP handler, because I typically inject more than just an ES client. I also don't pass an `*elastic.Client` around, but use an interface to make it easy to mock/test things. Like so:

```
// ArticlesRepository is a generic interface to articles. You can search,
// add or remove, or delete articles.
type ArticlesRepository interface {
  Search(context.Context, SearchRequest) (*SearchResponse, error)
  ...
}

// ESArticlesRepository is a concrete implementation of the
// ArticlesRepository interface. It uses Elasticsearch as the backend,
// but that is an implementation detail and users shouldn't be aware
// of that. Outside users should only work against ArticlesRepository instead.
type ESArticlesRepository struct {
  ArticlesRepository
  
  es *elastic.Client
}

func NewESArticlesRepository(client *elastic.Client) *ESArticlesRepository {
 return &ESArticlesRepository{es: client}
}

func (r *ESArticlesRepository) Search(ctx context.Context resp SearchRequest) (*SearchResponse, error) {
  search := r.es.Search("articles")
  ...
}

// In main, we create an ESArticlesRepository and wire up the dependencies.
func main() {
  repo := NewESArticlesRepository(client)
  setupEndpoints(repo)
  ...
}

// setupEndpoints and the HTTP side only uses interfaces. This makes
// it super simple to test the HTTP handlers (by e.g. mocking an ArticlesRepository),
// and keeps the dependencies under control.
func setupEndpoints(repo ArticlesRepository) {
  r.Get("/articles", &ArticlesSearchHandler{repo: repo}
  ...
}

// ArticlesSearchHandler performs a search on articles.
// Notice that ArticlesSearchHandler and the HTTP side doesn't need
// to know anything about Elasticsearch and stuff.
type ArticlesSearchHandler struct {
  repo ArticlesRepository
  ...
}

// ServeHTTP implements the HTTP request. All it does is set up a
// SearchRequest and send it to the repository implementation.
func (h *ArticlesHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
  // Parse query parameters etc. and set up a SearchRequest, then use
  // the repository to execute the search. This decouples the HTTP side
  // from the "business logic".
  req := SearchRequest{
    Keywords: httputil.QueryString(r, "keywords", ""),
    Sort: httputil.QueryString(r, "sort", "name"),
    ...
  }
  resp, err := h.repo.Search(r.Context(), req)
  ...
}
```
