### ISSUE TITLE
Does NewClient need to use http.Client that has set a timeout?

### ISSUE THREAD

**Issue by yueyuan4** [olivere/elastic#1073]
### Which version of Elastic are you using?

[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the behavior
 As described in the code comments，NewClient, by default, is meant to be long-lived and shared across your application. If you need a short-lived client, e.g. for request-scope,consider using NewSimpleClient instead.
I am planning to use newClient in my application.Should I use my own http.Client that has set a timeout or use http.DefaultClient?

**Comment by olivere** [comment]
That is totally up to you and your use case.

**Comment by yueyuan4** [comment]
thank you
