### ISSUE TITLE
Adding to SearchService after using Source

### ISSUE THREAD

**Issue by erickertz** [olivere/elastic#1074]
### Which version of Elastic are you using?

[ ] elastic.v6 (for Elasticsearch 6.x)

This is moreso just a question rather than an issue. Im using SeachService.Source to set a preconfigured string query to SearchService. However, depending on certain conditions, I would like to further add to this query using the SearchService functions. Is this possible? Thanks!

**Comment by olivere** [comment]
When using `Source`, you're on your own.

But if all you want to do is control the query with your own "source", you can use `elastic.NewRawStringQuery()` ([example code](https://github.com/olivere/elastic/blob/release-branch.v7/search_queries_raw_string_test.go)) and control the rest of the search service with the DSL.

Does this help?

**Comment by erickertz** [comment]
Thanks for clarifying. Pretty much I have a bunch of pre configured queries as strings and I was hoping to load them into SearchService but then also continue to use the features of SearchService to further build upon the query. I think i'll have to tweak my approach. Thanks again!
