### ISSUE TITLE
Unmarshal when no docs result

### ISSUE THREAD

**Issue by danisimba** [olivere/elastic#1075]
[ ] elastic.v6 (for Elasticsearch 6.x)
This is the error:
json: cannot unmarshal number into Go struct field SearchHits.total of type elastic.TotalHits

And this is the returned data from es:
{"took":1,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]},"aggregations":{"bedrooms":{"buckets":[{"key":"1","from":1.0,"to":2.0,"doc_count":0},{"key":"2","from":2.0,"to":3.0,"doc_count":0},{"key":"3","from":3.0,"to":4.0,"doc_count":0},{"key":"4","from":4.0,"to":5.0,"doc_count":0},{"key":"5","from":5.0,"to":100.0,"doc_count":0}]},"environments":{"buckets":[{"key":"1","from":1.0,"to":2.0,"doc_count":0},{"key":"2","from":2.0,"to":3.0,"doc_count":0},{"key":"3","from":3.0,"to":4.0,"doc_count":0},{"key":"4","from":4.0,"to":5.0,"doc_count":0},{"key":"5","from":5.0,"to":100.0,"doc_count":0}]},"parkings":{"buckets":[{"key":"-1","from":-1.0,"to":0.0,"doc_count":0},{"key":"1","from":1.0,"to":2.0,"doc_count":0},{"key":"2","from":2.0,"to":3.0,"doc_count":0},{"key":"3","from":3.0,"to":100.0,"doc_count":0}]},"locations.raw":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[]},"bathrooms":{"buckets":[{"key":"1","from":1.0,"to":2.0,"doc_count":0},{"key":"2","from":2.0,"to":3.0,"doc_count":0},{"key":"3","from":3.0,"to":4.0,"doc_count":0},{"key":"4","from":4.0,"to":100.0,"doc_count":0}]},"category.raw":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[]}}}

**Comment by olivere** [comment]
Can you provide the code that generated this? I’ve never seen anything like this.

**Comment by danisimba** [comment]
It is not a code issue. The error appears only since the last release.

	query := elastic.NewBoolQuery()
	query.Filter(elastic.NewTermQuery("site", site.Host))
	query.Filter(elastic.NewTermQuery("status", "ok"))

	if filter.Text != "" {
		query.Must(elastic.NewMultiMatchQuery(filter.Text, "title", "locations", "category").Type("cross_fields").Operator("AND"))
		// query.Should(elastic.NewMultiMatchQuery(filter.Text, "title", "locations", "category").Type("phrase"))
		// query.Should(elastic.NewMultiMatchQuery(filter.Text, "title", "locations", "category").Operator("AND"))
		// query.Must(elastic.NewMatchQuery("all", filter.Text).Operator("AND"))
	}

	if filter.ID != "" {
		query.Filter(elastic.NewTermQuery("id", filter.ID))
	}

	if filter.PriceFrom > 0 || filter.PriceTo > 0 {
		priceFrom, err := util.RateCurrency(filter.PriceFrom, filter.Currency)
		if err != nil {
			priceFrom = 0
		}

		priceTo, err := util.RateCurrency(filter.PriceTo, filter.Currency)
		if err != nil {
			priceTo = 0
		}

		if priceFrom > priceTo {
			priceTo = priceFrom
			filter.PriceTo = filter.PriceFrom
		}

		query.Filter(elastic.
			NewRangeQuery("usd_price").
			From(priceFrom).
			To(priceTo))
	}

	if filter.Location != "" {
		query.Must(elastic.NewTermQuery("locations.raw", filter.Location))
	}

	if filter.Category != "" {
		query.Must(elastic.NewTermQuery("category.raw", filter.Category))
	}

	if filter.Bedrooms > 0 {
		query.Filter(elastic.NewTermQuery("bedrooms", filter.Bedrooms))
	}

	if filter.Environments > 0 {
		query.Filter(elastic.NewTermQuery("environments", filter.Environments))
	}

	if filter.Bathrooms > 0 {
		query.Filter(elastic.NewTermQuery("bathrooms", filter.Bathrooms))
	}

	if filter.AreaFrom > 0 || filter.AreaTo > 0 {
		field := "totalArea"
		if filter.AreaType == "Cubierta" {
			field = "area"
		}

		if filter.AreaFrom > filter.AreaTo {
			filter.AreaTo = filter.AreaFrom
		}

		query.Must(elastic.NewRangeQuery(field).From(filter.AreaFrom).To(filter.AreaTo))
	}

	if filter.Parkings > 0 || filter.Parkings == -1 {
		query.Filter(elastic.NewTermQuery("parkings", filter.Parkings))
	}

	if filter.Old > 0 {
		query.Filter(elastic.NewTermQuery("old", filter.Old))
	}

	if filter.Page == 0 {
		filter.Page = 1
	}

	search := es.Search().
		Index("ads").
		Type("ad").
		Query(query).
		Sort("created_at", false).
		From(int(filter.Page-1) * 20).
		Size(20)

	termAggregations := []string{}

	termAggregations = append(termAggregations, "locations.raw", "category.raw")

	for _, item := range termAggregations {
		search = search.Aggregation(item, elastic.
			NewTermsAggregation().
			Field(item).
			Size(30))
	}

	search = search.Aggregation("bedrooms", elastic.
		NewRangeAggregation().
		AddRangeWithKey("1", 1, 2).
		AddRangeWithKey("2", 2, 3).
		AddRangeWithKey("3", 3, 4).
		AddRangeWithKey("4", 4, 5).
		AddRangeWithKey("5", 5, 100).
		Field("bedrooms"))

	search = search.Aggregation("environments", elastic.
		NewRangeAggregation().
		AddRangeWithKey("1", 1, 2).
		AddRangeWithKey("2", 2, 3).
		AddRangeWithKey("3", 3, 4).
		AddRangeWithKey("4", 4, 5).
		AddRangeWithKey("5", 5, 100).
		Field("environments"))

	search = search.Aggregation("bathrooms", elastic.
		NewRangeAggregation().
		AddRangeWithKey("1", 1, 2).
		AddRangeWithKey("2", 2, 3).
		AddRangeWithKey("3", 3, 4).
		AddRangeWithKey("4", 4, 100).
		Field("bathrooms"))

	search = search.Aggregation("parkings", elastic.
		NewRangeAggregation().
		AddRangeWithKey("-1", -1, 0).
		AddRangeWithKey("1", 1, 2).
		AddRangeWithKey("2", 2, 3).
		AddRangeWithKey("3", 3, 100).
		Field("parkings"))

	sr, err := search.Do(ctx)
	if err != nil {
		return nil, err
	}

**Comment by danisimba** [comment]
The error throws in decode.go:

// Decode decodes with json.Unmarshal from the Go standard library.
func (u *DefaultDecoder) Decode(data []byte, v interface{}) error {
	return json.Unmarshal(data, v)
}

**Comment by olivere** [comment]
What import path do you use? And what’s the version of the client (look inside client.go, there’s a Version const)?

**Comment by danisimba** [comment]
I'm using v7.0.0 ... sorry -and thx- olivere :(

**Comment by Rolex01** [comment]
I have an identical problem. How to cure?
I also use version 7

**Comment by olivere** [comment]
If you use ES 7.x, you should be using elastic 7.x. If you’re using ES 6.x, you should be using elastic 6.x. See the docs.

**Comment by tiagoapimenta** [comment]
@olivere could you help me? My ES is 6.x, according to [this wiki](https://github.com/olivere/elastic/wiki/Changes#versions) the one without suffix should get this, but when I run

    go get github.com/olivere/elastic

The result on file `~/.go/src/github.com/olivere/elastic/client.go` is the version 7! How am I suppose to get version 6?

**Comment by tiagoapimenta** [comment]
I am able to get it by the following command:

    go get gopkg.in/olivere/elastic.v6

I do not know why the "at" syntax does not work (`repository@branch`), but if there is another better solution I'd be glad, once my entire project is importing `github.com/olivere/elastic`, changing it will be a pain in the neck, otherwise you could recommend never use `github` on the docs and stick with the `gopkg.in` even to the current version since it may not be the current anymore after a while, I mean, if there is no other way besides this.

**Comment by alex-roman** [comment]
@olivere I'm having the same issue. Thanks for the lib!
@tiagoapimenta I solved it with Gopkg.toml
```
[[constraint]]
  name = "github.com/olivere/elastic"
  version = "6.2"
```
`go dep ensure`

**Comment by olivere** [comment]
> @olivere could you help me? My ES is 6.x, according to [this wiki](https://github.com/olivere/elastic/wiki/Changes#versions) the one without suffix should get this, but when I run
> 
> ```
> go get github.com/olivere/elastic
> ```
> 
> The result on file `~/.go/src/github.com/olivere/elastic/client.go` is the version 7! How am I suppose to get version 6?

You can use a dependency mananger like [`dep`](https://golang.github.io/dep/) to use v6. You just need to tag the dependency version to `v6.x.y`, with `v6.2.17` being the latest v6 version as of writing this. With Go 1.11+ I recommend to use [Go modules](https://github.com/golang/go/wiki/Modules).

**Comment by olivere** [comment]
@tiagoapimenta Go getting `gopkg.in/olivere/elastic.v6` is not a solution, as the import path used in v6 is still `github.com/olivere/elastic`. What you did is simply checkout the code with git, using gopkg.in as a proxy.

**Comment by WNZhao** [comment]
1 step `go get -v -u github.com/olivere/elastic`
2 step `go get gopkg.in/olivere/elastic.v6`
3 step is key important `import "gopkg.in/olivere/elastic.v6"`, if you use `import "github.com/olivere/elastic"` and do not install `gopkg.in/olivere/elastic.v6` it will report error `cannot unmarshal number into Go struct field SearchHits.total of type elastic.TotalHits`.

**Comment by olivere** [comment]
gopkg.in is just a Git proxy. So go get works, but as mentioned in the README, you must not use gopkg.in with v6 or later.

**Comment by xxbandy** [comment]
I have the same problem with the codes from http://olivere.github.io/elastic/.

```
  // Search with a term query
  termQuery := elastic.NewTermQuery("user", "olivere")
  searchResult, err := client.Search().
    Index("twitter").   // search in index "twitter"
    Query(termQuery).   // specify the query
    Sort("user", true). // sort by "user" field, ascending
    From(0).Size(10).   // take documents 0-9
    Pretty(true).       // pretty print request and response JSON
    Do(ctx)             // execute
  if err != nil {
    // Handle error
    panic(err)
  }
``` 
throw  "panic: json: cannot unmarshal number into Go struct field SearchHits.total of type elastic.TotalHits"

and my elasticsearch version is 6.4.3
