### ISSUE TITLE
Some client HTTP errors should return detailed result 

### ISSUE THREAD

**Issue by netixx** [olivere/elastic#1079]
### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
Using `NewDeleteByQueryService` should return detailed list of failures, even if request reply code is 403.

For example, I have indexes which are locked in read-only, and the query fails, but I could use the content of `Failures` to recover from those errors (using the DELETE api for example).

### Please describe the actual behavior
Error is returned, and result structure is nil, preventing potential recovery of error by analysing the `Failures` field of the result.

### Any steps to reproduce the behavior?
```go
result, err := elasticlib.NewDeleteByQueryService(client).Index(*index).Query(boolQuery).Do(context.Background())
if err != nil {
  fmt.Println(err)
  fmt.Println(result) // is nil
}
```

**Comment by olivere** [comment]
You can get all sorts of details about the error that ES returns. See [here](https://github.com/olivere/elastic/blob/release-branch.v7/errors.go#L66-L163) to get an idea. To get the underlying error details, you need to typecheck and cast the error with something like this:

```
if eserr, ok := err.(*elastic.Error); ok {
  fmt.Println(eserr.Status)
  fmt.Println(eserr.Details.Reason)
  ...
}
```

Elastic cannot return things that ES doesn't return though.
