### ISSUE TITLE
Handling 413 Request Entity To Large

### ISSUE THREAD

**Issue by gabrielf** [olivere/elastic#108]
Hi! While using elastic to reindex an elasticsearch index I got the error "unexpected end of JSON input". The root cause was that a post elastic made to /_bulk caused nginx to return a "413 Request Entity To Large" with the body:

```html
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>
```

which obviously does not parse as JSON. This particular error is always returned as html regardless of the Accept header sent. 

I wonder if perhaps checkResponse should return an error if the response cannot be parsed as JSON as other parts of the code seem to expect that: https://github.com/olivere/elastic/blob/master/errors.go#L39-L46

**Comment by olivere** [comment]
Hi! Looks like a good idea to return some kind of error in that case. I was always expecting to perform requests against Elasticsearch which is trying very hard to always return JSON. Let me see what's the best approach to this...

**Comment by olivere** [comment]
Fixed in [this commit](https://github.com/olivere/elastic/commit/8cd94a389c396600ef82042d44b0e124a8ad838d).

Feel free to update with `go get -u http://gopkg.in/olivere/elastic.v2`.

**Comment by gabrielf** [comment]
Perfect! Now I get "elastic: Error 413 (Request Entity Too Large)" under the same circumstances which is much easier to troubleshoot. Thanks!
