### ISSUE TITLE
connection to elastic was canceled

### ISSUE THREAD

**Issue by jc0425** [olivere/elastic#1081]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[O] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
connection success to elastic

### Please describe the actual behavior
dial tcp: lookup {elasitc lb} on x.x.x.x:port: dial udp x.x.x.x:port: operation was canceled

Actually, I don't know why above issue occur. But above error occur when we using elastic.v6

the result of netstat test (9200 port is elastic's port)
```
bash-4.4# netstat -n | grep -i 9200 | grep -i time_wait | wc -l
135
bash-4.4# netstat -n | grep -i 9200 | grep -i established | wc -l
2
```

**Comment by olivere** [comment]
This is a networking issue. Elastic is using a plain-old HTTP connection with a `*http.Client` under the hood. Please try to fix the underlying networking issue.
