### ISSUE TITLE
Getting odd error when creating index

### ISSUE THREAD

**Issue by rayjlinden** [olivere/elastic#1082]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

My code works fine on my dev box.  My go code is something like this:
		createIndex, err := lambdaState.esClient.CreateIndex(index).BodyString(mapping).Do(context.Background())

the mapping is kind of long so not included.  In any case, it works fine when run locally.

### Please describe the actual behavior

When I run on was I get the following error:
    "error": "error trying to create index: elastic: Error 500 (Internal Server Error): Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes [type=not_x_content_exception]",

### Any steps to reproduce the behavior?
Well, I'm only seeing this in AWS so I'm not sure how to reproduce.

**Comment by rayjlinden** [comment]
I turned off Gzip compression and things started working.  Does AWS Elasticsearch not support gzip?  Could they not give a better error message?

**Comment by olivere** [comment]
I’m not sure. They sign the request and maybe they also gzip anyway, so maybe the gzip has been done twice, hence the error. The error is by Elasticsearch as far as I can tell. I can’t change ES nor Amazons implementation of ES; the only thing we could do is to document the issue.

**Comment by olivere** [comment]
I added a remark about compression in the [Wiki](https://github.com/olivere/elastic/wiki/Using-with-AWS-Elasticsearch-Service).
