### ISSUE TITLE
Is an example or docs for composite aggregation pagination?

### ISSUE THREAD

**Issue by PearceDuan** [olivere/elastic#1086]
### Which version of Elastic are you using?

[ x ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the actual behavior
composite agg(date_histogram) support pagination just like search scroll, but I can not find the docs or example,
thanks

**Comment by olivere** [comment]
Here's probably an [example of the `after` setting](https://github.com/olivere/elastic/blob/release-branch.v7/search_aggs_bucket_composite_test.go#L12-L38) in a composite aggregation. I guess you're looking for that.

HTH.
