### ISSUE TITLE
Question: running v7 without go modules 

### ISSUE THREAD

**Issue by hoffoo** [olivere/elastic#1092]
I realize this isn't directly supported - unfortunately we aren't able to migrate to go modules quite yet. 

Is it at all possible to run the v7 branch with the old vendor method? 

Thanks!

**Comment by olivere** [comment]
Hmm... it should be possible if you skip the whole go-get infrastructure. Some people choose to have a per-project workspace, and they should be able to skip go-get and simply checkout with git, and either choosing an import path without the v7 or move directories around a bit. It might get a bit more complex if you choose to import one of the subpackages, e.g. elastic/config.

But it should be doable while not being supported out of the box.

**Comment by hoffoo** [comment]
thanks!
