### ISSUE TITLE
use elasticsearch7，cannot find package  github.com/olivere/elastic/v7/config

### ISSUE THREAD

**Issue by yongge666** [olivere/elastic#1095]
go get gopkg.in/olivere/elastic.v7
package github.com/olivere/elastic/v7/config: cannot find package "github.com/olivere/elastic/v7/config" in any of:
        D:\Go\src\github.com\olivere\elastic\v7\config (from $GOROOT)
        D:\Go\bin\src\github.com\olivere\elastic\v7\config (from $GOPATH)
        E:\go\src\github.com\olivere\elastic\v7\config
package github.com/olivere/elastic/v7/uritemplates: cannot find package "github.com/olivere/elastic/v7/uritemplates" in any of:
        D:\Go\src\github.com\olivere\elastic\v7\uritemplates (from $GOROOT)
        D:\Go\bin\src\github.com\olivere\elastic\v7\uritemplates (from $GOPATH)
        E:\go\src\github.com\olivere\elastic\v7\uritemplates

**Comment by olivere** [comment]
As described, you need to use github.com/olivere/elastic/v7 as import path.

**Comment by yongge666** [comment]
please tell me how can i get the package elastic/v7 ？

**Comment by olivere** [comment]
GO111MODULE=on go get github.com/olivere/elastic/v7

See https://github.com/golang/go/wiki/Modules for all details on Go modules.

**Comment by RyouZhang** [comment]
if i can‘t use go module，how can I get the source？

**Comment by olivere** [comment]
You can get the source right from here. If you want to get them from the command line, simply do:

```
$ git checkout https://github.com/olivere/elastic
```
