### ISSUE TITLE
Type deprecation

### ISSUE THREAD

**Issue by moserke** [olivere/elastic#1096]
Wanted to inquire about the deprecation of `type`.  Does this mean the client will no longer be able to specify a document type while sending to an index and if so what is the reasoning for removing this?  Or is that functionality moving somewhere else?

https://github.com/olivere/elastic/blob/release-branch.v7/index.go#L63

**Comment by olivere** [comment]
The client is just following what the good people are doing on the server side. Before I try to explain all the reasoning behind this, I should probably send you a bunch of links where Elastic explains.

https://www.elastic.co/blog/moving-from-types-to-typeless-apis-in-elasticsearch-7-0
https://www.elastic.co/guide/en/elasticsearch/reference/master/removal-of-types.html

**Comment by moserke** [comment]
Thanks for the links.  That's helpful!  Just getting in to ES so good to know of this change
