### ISSUE TITLE
Which function can be used to sort by _id

### ISSUE THREAD

**Issue by alsmn** [olivere/elastic#1100]
elastic.v5 (for Elasticsearch 5.x)

Which function can be used to sort by _id field?
It seems that Sort() can not achieve sorting of _id field.
Thanks.

**Comment by olivere** [comment]
If you say it doesn't work: what's the error you get?

Sorting by `_id` works in the console, though you should take [these remarks (at the end)](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-id-field.html) into account.

```
$ curl 'localhost:9200/_search?pretty=true&sort=_id'
...
```

So you should be able to use [`elastic.NewFieldSort(...)`](https://github.com/olivere/elastic/blob/release-branch.v5/sort_test.go#L107-L122) or use one of the [shortcuts on the `SearchService`](https://github.com/olivere/elastic/blob/release-branch.v5/search.go#L237-L253).
