### ISSUE TITLE
Implement Saved Objects API?

### ISSUE THREAD

**Issue by phillbaker** [olivere/elastic#1107]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

Use the [saved objects API](https://www.elastic.co/guide/en/kibana/6.3/saved-objects-api.html).

### Please describe the actual behavior

Not implemented.

### Any steps to reproduce the behavior?

N/a.

Would you accept a PR implementing the Saved Objects API? Or is it outside the scope of this library because it's focused on Kibana?

**Comment by olivere** [comment]
I'm sorry but this library is for Elasticsearch, not Kibana. I think you can simply use a plain-old `*http.Client` to work with Kibana. You don't have to do load-balancing and all this stuff that Elasticsearch requires.
