### ISSUE TITLE
Query not returning any hits, while manual rest request is 

### ISSUE THREAD

**Issue by hkyq** [olivere/elastic#1109]
### Which version of Elastic are you using?

[*] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

Hello, I have a question about this code. I am trying to search the `movies` index with this:

```go
func (d Db) Search() {
	ctx := context.Background()
	termQuery := elastic.NewTermQuery("title", "dude")
	searchResult, err := client.Search().
		Index("movies").
		Query(termQuery).
		Pretty(true). // pretty print request and response JSON
		Do(ctx) // execute
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(searchResult.TotalHits())
		var m movie
		for _, item := range searchResult.Each(reflect.TypeOf(m)) {
			if m, ok := item.(movie); ok {
				fmt.Println(m.Title)
			}
		}
	}
```

But it doesn't return any hits, while doing `curl -X GET "localhost:9200/movies/_search?q=title:dude&pretty=true"` returns

```
{
        "_index" : "movies",
        "_type" : "movie",
        "_id" : "q38sKmsB--Bc7AtBz0ee",
        "_score" : 2.6603975,
        "_source" : {
          "title" : "Dude, Where’s My Car?",
          "url" : "xxxxxx"
        }
      }
```

I don't have a mapping setup. Does anyone know why this is?

Here's how I add a movie:

```go
func (d Db) AddMovie(title string, url string) {
	m := movie{title, url}
	_, err := client.Index().
		Index("movies").
		BodyJson(m).
		Type("movie").
		Refresh("wait_for").
		Do(context.Background())
	if err != nil {
		// Handle error
		log.Error("Could not add movie to ElasticSearch")
	}
}
```

Thanks!

**Comment by olivere** [comment]
I can't say what's wrong without seeing the mapping for the index. Notice that if you don't add a mapping, ES will automatically choose a field of type `text` for something that looks like a `string` in Go.

Please read the documentation on [`text`](https://www.elastic.co/guide/en/elasticsearch/reference/current/text.html) and [`keyword`](https://www.elastic.co/guide/en/elasticsearch/reference/current/keyword.html); maybe that's already the solution to your problem. Otherwise send me a reproducible test case and I'll re-open.

**Comment by hkyq** [comment]
@olivere 

I've created this mapping:

```go
const mapping = `
{
   "mappings":{
      "properties":{
         "title":{
            "type":"text"
         },
         "url":{
            "type":"keyword",
            "index":true
         }
      }
   }
}

`
```

And changed the add function: 

```go
func (d Db) AddMovie(title string, url string) {
	m := movie{title, url}
	_, err := client.Index().
		Index("movies").
		BodyJson(m).
		Refresh("wait_for").
		Do(context.Background())
	if err != nil {
		// Handle error
		fmt.Println(err)
		log.Error("Could not add movie to ElasticSearch")
	}
}
```

But I still get the same result :/

**Comment by olivere** [comment]
That's correct. Exact matches (`TermQuery`) don't work with type `text`. Use `keyword` and exact matches will work.

BTW: The `curl -X GET "localhost:9200/movies/_search?q=title:dude&pretty=true"` is not an exact query but a [`QueryStringQuery`](https://github.com/olivere/elastic/blob/release-branch.v7/search_queries_query_string.go) or a [`SimpleQueryStringQuery`](https://github.com/olivere/elastic/blob/release-branch.v7/search_queries_simple_query_string.go)—not sure which one is used in ES 7.x.

**Comment by hkyq** [comment]
Ah, thank you. Still a noob as you can see ;)
