### ISSUE TITLE
Declare variabel

### ISSUE THREAD

**Issue by tommoholmes** [olivere/elastic#111]
I want to make API with elastic. I have some trouble
I want to declare variabel.
this my code 
```go
var q struct{}
if json.Title != ""{
    q = elastic.NewMatchQuery("title", json.Title)
}else{
    q = elastic.NewMatchAllQuery()
}
builder := client.Search().Index("witch").Query(q).From(json.From).Size(21).Sort("price", true)
topTagsHitsAgg := elastic.NewTopHitsAggregation().Size(10).FetchSource(true)
topTagsAgg := elastic.NewTermsAggregation().Field("brand").Size(0).SubAggregation("top_tag_hits", topTagsHitsAgg)
builder = builder.Aggregation("top", topTagsAgg)
searchResult, err := builder.Do()
```
but when i runing this code
warning cannot use elastic.NewMatchQuery("title", json.Title) (type elastic.MatchQuery) as type struct {} in assignment

**Comment by olivere** [comment]
When you write sth like json.Title, Go expects you to have a struct called json with a field called Title.

You should really do the Go tour at golang.org to get the basics of the language.

**Comment by olivere** [comment]
For your error: q is of type struct{} when the NewMatchQuery returns an interface type called elastic.Query.

**Comment by tommoholmes** [comment]
What you mean olivere?

**Comment by olivere** [comment]
Declare q as follows and your error is going away:

var q elastic.Query

You see, I am happy to help with questions regarding Elastic or Elasticsearch. But unfortunately I can't help with basic questions regarding Go, like declaring variables. There are many sites on the web that can help you to learn Go much better than I ever could. :-)

**Comment by tommoholmes** [comment]
hhehe sorry
I think elastic.NewMatchAllQuery() or elastic.NewMatchQuery("title", json.Title) is sturct 
Thanks olivere
I have searching but not yet
