### ISSUE TITLE
Failed to parse content to map

### ISSUE THREAD

**Issue by Sunbo2017** [olivere/elastic#1110]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v7 (for Elasticsearch 7.x)

### Please describe the expected behavior

When I use BodyString() to create mappings,I meet Error 400 (Bad Request): Failed to parse content to map [type=parse_exception].
I use the example code in "https://github.com/olivere/elastic/wiki/CreateIndex"
How should I resolve it.

**Comment by Sunbo2017** [comment]
I find the example code in "https://github.com/olivere/elastic/wiki/CreateIndex" has a question:
type should be "keyword" rather than "string"

**Comment by olivere** [comment]
The `string` should still be allowed AFAIK, at least for v6 (which maps it to a multi-field with `__.keyword`). Not sure of v7 though.
