### ISSUE TITLE
Add XPack Security APIs

### ISSUE THREAD

**Issue by olivere** [olivere/elastic#1113]
See [Security APIs](https://www.elastic.co/guide/en/elasticsearch/reference/7.1/security-api.html) and the [REST API spec](https://github.com/elastic/elasticsearch/blob/7.1/x-pack/plugin/src/test/resources/rest-api-spec/api/security.authenticate.json).

While #1089 is a good start, it is incomplete and has a few issues.

- [ ] Authenticate
- [ ] Clear cache
- [ ] Clear cached roles
- [x] Change passwords
- [ ] Create API key
- [ ] Delete privileges
- [x] Delete role
- [x] Delete role mapping
- [x] Delete user
- [x] Disable user
- [x] Enable user
- [ ] Get API key
- [ ] Get privileges
- [x] Get role
- [ ] Get role mapping
- [ ] Get token
- [x] Get user
- [ ] Get user privileges
- [ ] Has privileges
- [ ] Invalidate API key
- [ ] Invalidate token
- [ ] Put privileges
- [x] Put role
- [x] Put role mapping
- [x] Put user

**Comment by sangeethdba** [comment]
@olivere is it possible to have xpack put user for elastic version 6

**Comment by olivere** [comment]
@sangeethdba Sure, that's probably very easy to achieve (if there are not a lot of changes between 6.x and 7.x). To backport, you only need to copy over [`xpack_security_put_user*.go`](https://github.com/olivere/elastic/blob/release-branch.v7/xpack_security_put_user.go) to 6.x and add the [`XPackSecurityPutUser` function](https://github.com/olivere/elastic/blob/release-branch.v7/client.go#L2162-L2165) into `client.go` of 6.x.

If you want to try, I'm happy to get a PR. Otherwise, I'll mark this as an open issue.

**Comment by sangeethdba** [comment]
https://github.com/olivere/elastic/pull/1517

**Comment by sangeethdba** [comment]
@olivere https://github.com/olivere/elastic/pull/1517

**Comment by olivere** [comment]
A lot of them are implemented now. So closing this an creating an issue per missing API.
