### ISSUE TITLE
cannot unmarshal number into Go struct field SearchHits.total of type elastic.TotalHits

### ISSUE THREAD

**Issue by chenyangguang** [olivere/elastic#1114]
I hope *search.go* file can transform response correct by  *SearchService.Do()* func at line  462 *if err := s.client.decoder.Decode(res.Body, ret); err != nil { * .

I create a function by SearchService.Do ![image](https://user-images.githubusercontent.com/7223579/59318958-86566680-8cfb-11e9-90d1-c8de98069597.png)
AND print the response format  err with : 
![image](https://user-images.githubusercontent.com/7223579/59319007-bb62b900-8cfb-11e9-9761-5e9d74a0e798.png)

Then it appear to say: 
```
cannot unmarshal number into Go struct field SearchHits.total of type elastic.TotalHits
```

**Comment by olivere** [comment]
Which version of Elastic are you using, and what is the version of Elasticsearch that you are working with?

**Comment by chenyangguang** [comment]
> Which version of Elastic are you using, and what is the version of Elasticsearch that you are working with?

The latest Elastic , clone  master branch from github.com/olivere/elastic  yesterday 3:00pm.

**Comment by olivere** [comment]
@chenyangguang Then please use the correct version. See [README](https://github.com/olivere/elastic/blob/release-branch.v7/README.md#releases).

**Comment by chenyangguang** [comment]
> @chenyangguang Then please use the correct version. See [README](https://github.com/olivere/elastic/blob/release-branch.v7/README.md#releases).

ok, Thanks.

**Comment by chenyangguang** [comment]
Ok, Thanks.
