### ISSUE TITLE
How to retrieve  entire source doc?

### ISSUE THREAD

**Issue by mohankumaru** [olivere/elastic#1115]
I have an index with too many fields like one docs has 6 fields and other has different number of fields, together there are nearly thousand different fields on total.

i followed this [https://github.com/olivere/elastic/wiki/Search](url), it works fine but i cannot create a struct of all the fields and do `json.Unmarshal(*hit.Source, &t)` on that.
is there any way i can retrieve entire source with out the fields struct.

i use elasticsearch version -7

**Comment by olivere** [comment]
I'm afraid I don't understand. You mean you don't know in advance how many/which fields you have? You can try to serialize into a `map[string]interface{}` then.

**Comment by olivere** [comment]
Closed for inactivity.
