### ISSUE TITLE
Send bearer token in the request

### ISSUE THREAD

**Issue by mohankumaru** [olivere/elastic#1116]
I have token based authentication in my elasticsearch(bearer token),
how do i send the bearer token along side while creating client,

like for example in python you do like,
`es = Elasticsearch('http://127.0.0.1:9200',ca_certs=False,verify_certs=False,headers={'content-type': 'application/x-ndjson'},headers={'Authorization : Bearer' fsydftfwet7657qtwfdt})`

**Comment by olivere** [comment]
Oh, interesting. There's no direct support for this in the client, but you can pass your own `*http.Client` and modify HTTP request/response as [described here](https://github.com/olivere/elastic/wiki/HttpTransport). HTH.

**Comment by mohankumaru** [comment]
Can you provide httpclient for this,

i tried this one 
`package main

import (
	"crypto/tls"
	"net/http"

	"github.com/olivere/elastic"
)

var (
	elasticClient *elastic.Client
)

type BasicAuthTransport struct {
	token string
}

func (tr *BasicAuthTransport) RoundTrip(r *http.Request) (*http.Response, error) {
	r.Header.Add("Authorization", "Bearer eH8AILKg8dNzX0vYNfmOcMxfx2")
	return http.DefaultTransport.RoundTrip(r)
}

func main() {
	http.DefaultTransport.(*http.Transport).TLSClientConfig = &tls.Config{InsecureSkipVerify: true}
	httpClient := &http.Client{
		Transport: &BasicAuthTransport{
			token: "eH8AILKg8dNzX0vYNfmOcMxfx2",
		},
	}
	var err error
	elasticClient, err = elastic.NewClient(elastic.SetURL("https://127.0.0.1:9200"), elastic.SetHttpClient(httpClient))
	//info, code, err := elasticClient.Ping("https://127.0.0.1:9200").Do(context.Background())
	if err != nil {
		panic(err)
	}
	//fmt.Printf("Elasticsearch version %s ,response code %d\n", info.Version.Number, code)
}
`

but it throws me **panic: no active connection found: no Elasticsearch node available**

**Comment by olivere** [comment]
Are you using v6 or v7?

The problem probably doesn't have to do anything with your issue. It's just a connection problem. Try without your own HTTP client first. If that works, add your HTTP client.

**Comment by mohankumaru** [comment]
I use elasticsearch v7,
i tried removing http client,
i get this,
`panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x602098]

goroutine 1 [running]:
github.com/olivere/elastic.(*PingService).Do(0x1286bfb4, 0x6e4a20, 0x12852058, 0x0, 0x0, 0x0, 0x0)
        C:/Users/mkumaru/go/src/github.com/olivere/elastic/ping.go:80 +0x58`

**Comment by mohankumaru** [comment]
I checked my elasticsearch logs ,it shows access denied.
go is contacting elastics server ,but the problem is with  handler.
I way i have coded , elastic throws access denied if token is not present or invalid
can you check whats wrong with that httpclient

**Comment by olivere** [comment]
> I use elasticsearch v7,
> i tried removing http client,
> i get this,
> 
> ```
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xc0000005 code=0x0 addr=0x0 pc=0x602098]
> 
> goroutine 1 [running]:
> github.com/olivere/elastic.(*PingService).Do(0x1286bfb4, 0x6e4a20, 0x12852058, 0x0, 0x0, 0x0, 0x0)
>         C:/Users/mkumaru/go/src/github.com/olivere/elastic/ping.go:80 +0x58```
> ```

That's a null pointer exception. You're probably not checking errors properly.

**Comment by olivere** [comment]
> I checked my elasticsearch logs ,it shows access denied.
> go is contacting elastics server ,but the problem is with handler.
> I way i have coded , elastic throws access denied if token is not present or invalid
> can you check whats wrong with that httpclient

You first need to make sure you can contact the Elasticsearch server, without this library, e.g. with `curl` or something like that. If permission is denied, you must find the reason why that is.

Try e.g.:

```
$ curl -i -H 'Accept: application/json' -H "Authorization: Bearer yourtoken" -X GET "http://localhost:9200/_count?pretty=true"
```

Does that work at all?

**Comment by olivere** [comment]
Also: You're using `https` in your example. Is that correct?

**Comment by mohankumaru** [comment]
I checked it in postman it worked,  and its https,
i am able to login but elasticsearch says not an ssl record exception.
because in my code i use `http.DefaultTransport.(*http.Transport).TLSClientConfig = &tls.Config{InsecureSkipVerify: true}`

and set transport for bearer token .
how do i solve this

**Comment by olivere** [comment]
You can try with sniffing disabled first: elastic.SetSniff(false) passed as an option to NewClient.

**Comment by mohankumaru** [comment]
thanks, it worked
