### ISSUE TITLE
Pipeline func not found on ReindexDestination

### ISSUE THREAD

**Issue by siff-jason** [olivere/elastic#1119]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

Should be able to set the ingest pipeline on the ReindexDestination - according to the docs (https://www.elastic.co/guide/en/elasticsearch/reference/6.4/docs-reindex.html - search for "pipeline").

### Please describe the actual behavior

The function doesn't exist so trying to set it will fail to compile:

```
.../reindex.go:52:56: elastic.NewReindexDestination().Index(dstIndex).Pipeline undefined (type *elastic.ReindexDestination has no field or method Pipeline)
```

### Any steps to reproduce the behavior?

Just add .Pipeline() which will cause it to fail to compile, e.g.

```
dst := elastic.NewReindexDestination().Index(dstIndex).Pipeline("myPipeline")
```

NOTE: I also manually tested with the pipeline specified and the reindex worked as expected so seems like it should be fine to add.

**Comment by olivere** [comment]
Yes. Will add to next release of v6 and v7.
