### ISSUE TITLE
No Elasticsearch Node Available

### ISSUE THREAD

**Issue by Sawon90** [olivere/elastic#112]
Can you please tell me why I am getting error. panic: no Elasticsearch node available. From java api this works. 

	client, err := elastic.NewClient(elastic.SetURL("http://localhost:9300"))
	if err != nil {
		panic(err)
	}

	get1, err := client.Get().
	Index("emdad").
	Type("java").
	Id("1").
	Do()

	if err != nil {
		panic(err)
	}
	if get1.Found {
		fmt.Printf("Got document %s in version %d from index %s, type %s\n", get1.Id, get1.Version, get1.Index, get1.Type)
	}

**Comment by olivere** [comment]
I think it should be port 9200 for HTTP endpoints. 9300 is for the transport/TCP protocol.

**Comment by Sawon90** [comment]
I have found the problem. My Elasticsearch version was old. I upgrade it to 1.7.1 and its works. Thanks
