### ISSUE TITLE
Is there a plan to support GeoShape Query? 

### ISSUE THREAD

**Issue by EyeInSpace** [olivere/elastic#1122]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)

### Please describe the expected behavior
support GeoShape query

**Comment by olivere** [comment]
We tried a few times (see #939), but for now you can only use [`RawStringQuery`](https://github.com/olivere/elastic/blob/release-branch.v7/search_queries_raw_string.go) and build it for yourself.
