### ISSUE TITLE
index doc blocked

### ISSUE THREAD

**Issue by cjdxhjj** [olivere/elastic#1124]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[* ] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
index doc blocked, even through i try to catch and print the error, but it dos not display any thing, here is my code
![image](https://user-images.githubusercontent.com/5616997/60064350-b4439e00-9732-11e9-95ce-caaf9f7c0413.png)

if r, err := client.Index().Index(index).Id(document.Id).BodyString(document.Source).Do(ctx); err != nil {
	log.Fatalln(err.Error())
	log.Println("id:" + r.Id + ",result" + r.Result)
}

### Please describe the actual behavior
i wrote a prog to sync doc from old version es,
if client, err := elastic.NewClient(option, elastic.SetBasicAuth("my_admin", "dbn002385")); err == nil {
		ctx := context.Background()
		for {
			document := <-doc
			if document.Id != "0" {
				log.Println("写入文档:" + document.Id)
				if r, err := client.Index().Index(index).Id(document.Id).BodyString(document.Source).Do(ctx); err != nil {
					log.Fatalln(err.Error())
					log.Println("id:" + r.Id + ",result" + r.Result)
				}
			} else {
				break
			}
		}
	} else {
		log.Println("连接服务器[" + url + "]失败:" + err.Error())
	}

**Comment by olivere** [comment]
This seems more like a problem with the concurrency in your code. Are you sure your code isn't blocking at `document := <-doc`? Do you have a complete, running sample? I will re-open if the problem turns out to be in the library.

**Comment by cjdxhjj** [comment]
my program is to transfer data from v6 to v7,here is my fetch doc code
func FetchDocs(index, typeName, url string, doc chan EsDoc) {
	arr := strings.Split(url, ",")
	var option elastic.ClientOptionFunc
	for i, it := range arr {
		arr[i] = "http://" + it + ":9200"
	}
	if len(arr) > 1 {
		option = elastic.SetURL(arr...)
	} else {
		option = elastic.SetURL(arr[0])
	}
	if client, err := elastic.NewClient(option); err == nil {
		defer client.Stop()
		scroll := client.Scroll(index).Type(typeName).Size(30)
		buf := bytes.Buffer{}
		ctx := context.Background()
		var num = 0
		for {
			if result, err := scroll.Do(ctx); err == nil {
				for _, hit := range result.Hits.Hits {
					num += 1
					log.Println("第" + strconv.Itoa(num) + "个文档,id:" + hit.Id)
					buf.Reset()
					buf.Write(*hit.Source)
					doc <- EsDoc{ Id: hit.Id, Source: buf.String()}
				}
			} else if err == io.EOF {
				doc <- EsDoc{ Id: "0"}
				break
			} else {
				println("同步出错:" + err.(error).Error())
			}
		}

	} else {
		println("连接es出错:" + err.(error).Error())
	}
}

and my main.go
docChan := make(chan EsDoc, 30)
	wg := sync.WaitGroup{}
	wg.Add(2)
	go func() {
		FetchDocs(index, index, sUrl, docChan)
		wg.Done()
	}()
	go func() {
		StoreDoc(index, tUrl, docChan)
		wg.Done()
	}()
	wg.Wait()
	time.Sleep(time.Second * 3)
	log.Println("finish")

my code run ok at most of times, but on one index, it alway block at range of [490, 500], it dos not log any other message,i can't figure out what happend
