### ISSUE TITLE
IndicesAnalyzeResponseToken should have PositionLength field.

### ISSUE THREAD

**Issue by bbfsdev** [olivere/elastic#1126]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.
[V] elastic.v7 (for Elasticsearch 7.x)
[V] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
IndicesAnalyzeResponseToken when Analyzing should also have PositionLength field, not only in explain.

### Please describe the actual behavior
IndicesAnalyzeResponseToken don't have PositionLengtth field and is not populated in decode from json.

### Any steps to reproduce the behavior?
DELETE test
{}

PUT test
{
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 0,
    "analysis": {
      "filter": {
        "synonym_graph": {
          "type": "synonym_graph",
          "synonyms": [
                "זוהר לעם,זוהר,ספר הזוהר,הזוהר"
           ],
          "tokenizer": "keyword"
        },
        "he_IL": {
          "locale": "he_IL",
          "type": "hunspell",
          "dedup": "true"
        }
      },
      "analyzer": {
        "hebrew_synonym": {
          "filter": [
            "synonym_graph",
            "he_IL"
          ],
          "tokenizer": "standard"
        }
      }
    }
  },
  "mappings": {
    "results": {
      "properties": {
        "content": {
          "fields": {
            "language": {
              "type": "text",
              "analyzer": "hebrew_synonym"
            }
          },
          "type": "text",
          "analyzer": "standard"
        }
      }
    }
  }
}

GET test/_analyze 
{
  "analyzer": "hebrew_synonym", 
  "text":  "מבוא לספר זוהר"
}

Run this through API, should get PositionLength for tokens.

**Comment by olivere** [comment]
Will be part of the next v6 and v7 release, although I think we need to review this once they fixed JSON from camelCase to snake_case. Watch out for this as it might be fixed in the next releases!

**Comment by bbfsdev** [comment]
Thanks!
