### ISSUE TITLE
Passing in http client with timeout for an index/bulkindex request

### ISSUE THREAD

**Issue by mmandolesi-g** [olivere/elastic#1130]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[ X] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
A passed in `http.Client` with a `net.Dialer.Timeout` value of 30 seconds actually times out on requests that take longer than 30 seconds.

### Please describe the actual behavior
I pass in a `http.Client` with the `net.Dialer.Timeout` value set to 30 seconds in the `http.Transport`. But I see requests go up to 55 seconds pretty commonly. Not sure why this Timeout value isn't being respected. Any ideas on what could be wrong here?

**Comment by olivere** [comment]
Just guessing, but maybe that's due to retries?!

**Comment by olivere** [comment]
No response, so closing for now. Let me know if this needs to be re-opened.
