### ISSUE TITLE
Problem to create client with api key

### ISSUE THREAD

**Issue by pzentenoe** [olivere/elastic#1131]
Hi, I'm using this version of the library

[X ] elastic.v7 (for Elasticsearch 7.x)

### Please describe the expected behavior

I need to create an elasticsearch client with an apikey since the service is not mine. in the configurations of the library does not appear the option to send the apikey

**Comment by olivere** [comment]
How do you pass the API key. If it's via Basic Auth, you can use [`elastic.SetBasicAuth`](https://github.com/olivere/elastic/blob/release-branch.v7/client.go#L483-L492).

**Comment by pzentenoe** [comment]
```
// SetBasicAuth can be used to specify the HTTP Basic Auth credentials to
// use when making HTTP requests to Elasticsearch.
func SetBasicAuth(username, password string) ClientOptionFunc {
	return func(c *Client) error {
		c.basicAuthUsername = username
		c.basicAuthPassword = password
		c.basicAuth = c.basicAuthUsername != "" || c.basicAuthPassword != ""
		return nil
	}
}
```

In which part of the function can I set the API KEY?
I only see the username and password params

**Comment by olivere** [comment]
I don't know how you have to pass the API key. You have to find out. I never had to set an API key when connecting to Elasticsearch.

If you have to pass an API key as user/password in the `Authorization` header via HTTP Basic Auth, you can use the method described above.

**Comment by pzentenoe** [comment]
the apikey is passed in the header of the elasticsearch api call.
They will not give me the elasticsearch user and password credentials since that has to do with the infrastructure team so they provide only the apikey
How can I pass that header?

**Comment by olivere** [comment]
You can create your own HTTP client/transport like described here: https://github.com/olivere/elastic/wiki/HttpTransport
