### ISSUE TITLE
Least permissions for sniffing and healtcheck

### ISSUE THREAD

**Issue by adubkov** [olivere/elastic#1134]
What the least permissions  does user need to enable both `sniffing` and `Healthcheck`?
I don't want grant cluster: monitor every user I have. It is too broad.

Or is there a way to specify different user which will be used in client to do specifically these two operations?

**Comment by olivere** [comment]
I don't understand. [Sniffing](https://github.com/olivere/elastic/wiki/Sniffing) and [health checks](https://github.com/olivere/elastic/wiki/Healthcheck) have nothing to do with permissions. Can you clarify?

**Comment by adubkov** [comment]
I'm using x-pack to create users and grand them access only to specific set of indexes.
Sniffing and health checks works for me when I grant them `cluster: monitor` permission, which is too broad for that. I'm looking for specific permissions those users require to let it work.

As an option I could use separate "monitoring" user for sniff\healthcheck but rest request should be executed with specific user creds.

**Comment by olivere** [comment]
Ah, now I understand.

Hmm... I'm not an expert on X-Pack Security. But I can tell you which APIs are being used for sniffing and healthchecks.

For sniffing, it's the Cluster Nodes API at `/_nodes/http`.

For healthchecks, it's does a `HEAD` request on the `publish_address` reported by `/_nodes/http` for each node in the cluster.

Example output of `curl 'localhost:9200/_nodes/http?pretty=true'`:

```
$ curl 'localhost:9200/_nodes/http?pretty=true'
{
  "_nodes" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "cluster_name" : "elasticsearch",
  "nodes" : {
    "_53ubIdDTvGQHiqy5rPYhA" : {
      "name" : "_53ubId",
      "transport_address" : "172.22.0.6:9300",
      "host" : "172.22.0.6",
      "ip" : "172.22.0.6",
      "version" : "6.8.0",
      "build_flavor" : "oss",
      "build_type" : "docker",
      "build_hash" : "65b6179",
      "roles" : [
        "master",
        "data",
        "ingest"
      ],
      "http" : {
        "bound_address" : [
          "0.0.0.0:9200"
        ],
        "publish_address" : "172.22.0.6:9200",
        "max_content_length_in_bytes" : 104857600
      }
    }
  }
}
```

I'd be nice to you can add a section in the wiki about your findings wrt permissions required for X-Pack Security. Maybe [here's a good place to add a section](https://github.com/olivere/elastic/wiki/Sniffing).
