### ISSUE TITLE
Retrieve the fields and values inside the search hit

### ISSUE THREAD

**Issue by mohankumaru** [olivere/elastic#1136]
Is there any way to retrieve or access the fields inside the search hit.

**Comment by olivere** [comment]
You're probably looking for `FetchSourceContext`. Here are [a few tests](https://github.com/olivere/elastic/blob/release-branch.v7/fetch_source_context_test.go) and [an example](https://github.com/olivere/elastic/blob/60d62e5b2d1c728d7cbbeb7ed9a284303ea4acd4/get_test.go#L68-L70).

**Comment by mohankumaru** [comment]
Hi,
Thanks for your responsse.I didn't know about that.
I have an array of fields to be included in search hit.
is it possible to pass this array of strings to **Include()** function at once.

**Comment by olivere** [comment]
Yes. Both [`Include` and `Exclude` are variadic functions](https://github.com/olivere/elastic/blob/release-branch.v7/fetch_source_context.go#L44-L56).

So if you have an array, say `fields := []string{"a", "b", "c"}`, you can pass it with `Include(fields...)`.

**Comment by mohankumaru** [comment]
but i get this message ,
``cannot use authorized_attributes (type []string) as type string in argument to elastic.NewFetchSourceContext(true).Includego``
 
when i pass in the string

**Comment by mohankumaru** [comment]
Hey thank you, it worked
