### ISSUE TITLE
sniffer and healtcheck lead to goroutine leak. v6.2.7

### ISSUE THREAD

**Issue by czlhs** [olivere/elastic#1137]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[X] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Any steps to reproduce the behavior?
Running for a long time, such as one month, it will must reproduce. 
the goroutine pprof:
```
goroutine profile: total 191418
95701 @ 0x42f22f 0x43ecb8 0x7c7cbf 0x45c571
#	0x7c7cbe	github.com/olivere/elastic.(*Client).sniffer+0x15e	/Users/ahxia/go/src/github.com/olivere/elastic/client.go:850

95701 @ 0x42f22f 0x43ecb8 0x7c9894 0x45c571
#	0x7c9893	github.com/olivere/elastic.(*Client).healthchecker+0x163	/Users/ahxia/go/src/github.com/olivere/elastic/client.go:1044
```
total 191418 goroutine, sniffer and healthchecker occupy 191402

**Comment by czlhs** [comment]
I wonder if it need to call Client.Stop explicitly after using the client.

**Comment by olivere** [comment]
Yes, you do. Typically, I create the client in main, then forget about it.
