### ISSUE TITLE
.Parent() is missing on an .Exists() call (Parent-Child Relationships)

### ISSUE THREAD

**Issue by vishalshah-org** [olivere/elastic#114]
Hi @olivere - Specifying a parent is necessary for parent-child relationship API calls for deriving the routing information. Its possible on a `.Get()` but is missing on `.Exists()` resulting in a 400, as the routing information by default is derived from the parent (child is in the same shard).

Simple fix needed to allow specifying the parent just like `.Get()`. For now, I am using a `.Get()` and looking up `result.Found` to simulate an exists in such a case, but as you can imagine is a bit inefficient.

Thanks.
V

**Comment by olivere** [comment]
Hi @vishalshah-org. Thanks for reporting. I just updated it to the latest version.

Make sure to change your import path to `gopkg.in/olivere/elastic.v2` because master will soon target Elasticsearch 2.0 and has some breaking changes.

**Comment by vishalshah-org** [comment]
@olivere thanks! yes, will update import paths, oooh we r going live on the 5th, this was a good catch :)
