### ISSUE TITLE
How to get aggregation type from elastic search response?

### ISSUE THREAD

**Issue by omurbekjk** [olivere/elastic#1140]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
I am building complex ES aggregations with different types.
How do I get type of aggregation from ES response?
Ex:
```
  "aggregations": {
    "cars": {
      "aggregations": {
        "model": {
          "aggregations": {
            "category": {
              "terms": {
                "field": "model.key",
                "size": 500
              }
            }
          },
          "nested": {
            "path": "cars"
          }
        }
      },
      "terms": {
        "field": "users",
        "size": 500
      }
    }
  }
``` 
### Please describe the actual behavior
```
// aggregations elastic.Aggregations
for aggName, aggValue := range aggregations {
		fmt.Println(aggValue)
        // Extract type of aggregation here
        // aggregations.Nested(aggName) ?
        // aggregations.Terms(aggName) ?
}
```
What is the best way to extract type from ES response?

**Comment by olivere** [comment]
There is an example of nearly all aggregation types in [`search_aggs_test.go`](https://github.com/olivere/elastic/blob/release-branch.v7/search_aggs_test.go).
