### ISSUE TITLE
use elasticsearch7，cannot find package github.com/olivere/elastic/v7/config

### ISSUE THREAD

**Issue by RyouZhang** [olivere/elastic#1144]
What？？The v7 branch，changed import path？？？

How can I get the source，use other package manager tools？

**Comment by olivere** [comment]
You simply use Go modules and do:

```
$ export GO111MODULE=on
$ mkdir ~/src/myproject
$ cd ~/src/myproject
$ go mod init myproject.com
$ go get github.com/olivere/elastic/v7
go: finding github.com/olivere/elastic/v7 v7.0.4
go: downloading github.com/olivere/elastic/v7 v7.0.4
go: extracting github.com/olivere/elastic/v7 v7.0.4
```

Then you can import `github.com/olivere/elastic/v7/...` packages in your code.

You can [read more about Go modules here](https://github.com/golang/go/wiki/Modules).
