### ISSUE TITLE
config in directory v7 incorrect

### ISSUE THREAD

**Issue by 90wukai** [olivere/elastic#1145]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ -] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

We use dep as package manager. But, can't update es to v7, because of config import incorrect!

whole project change to go module is too difficult!!!

**Comment by olivere** [comment]
Well, Go modules is part of all supported Go versions, so we use it. If you want, you can fork the project, put all code under a `v7` subdirectory and use that with `dep`. Last I looked, [`dep` doesn't support Go modules and/or versions in the import path](https://github.com/golang/dep/issues/2139).

Switching projects to Go modules took us between a few minutes and half a day; it's not so complicated. We've move a dozen projects already.
