### ISSUE TITLE
Having Trouble Getting Match All Query to Work

### ISSUE THREAD

**Issue by mmcken3** [olivere/elastic#1148]
I am having trouble getting the match all query to return all results when being run from code. If I run the standard match all query on the same index from my Kibana console then the match all runs correctly. I can also run a MGet query from code using the package by passing in the specific ids and the results are all returning correctly. See example code at the end where this issue is present. 

### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

The match all query would return all of the results for the index it is being run on.

### Please describe the actual behavior

The match all query is returning 0 results when using the query from the v7 package.

### Any steps to reproduce the behavior?

I have filled in about 10 documents into my index, and am passing around a variable with the index name stored in it to ensure that the index name is always consistent. 

My import at the top of the file is like so `elastic "github.com/olivere/elastic/v7"`

The variable name `c` you see in the code is an initialized `*elastic.Client`

Here is the code I have using the match all query:

```
	q := elastic.NewMatchAllQuery()
	if noLimit {
		return c.Search(idx).Query(q).Do(ctx)
	}
	return c.Search(idx).Size(limit).Query(q).Do(ctx)
```

For me using both a limit and no limit the number of results returned when running this code is 0. If I run the standard match all query from the kibana console on the same index I see all results.

I can also use the Mget from the package to see all results when giving it all of the ids like so:

```
	mgetsvc := c.MultiGet()
	for _, id := range ids {
		item := elastic.NewMultiGetItem().Type("doc").Index(idx).Id(id)
		mgetsvc.Add(item)
	}
	resp, err := mgetsvc.Do(ctx)
```

I am struggling to figure out why when I run these queries back to back the first returns no results but the second does return results. Any assistance would be appreciated!

**Comment by olivere** [comment]
Hmm... more often than not these issues are due to the mapping. E.g. if you do a simple query with a string type, ES does a fulltext query, not an exact query. What you typically have to use is `name.keyword` for exact matches instead of `name`.

Can you double-check that this isn't the problem? Can you post your mapping and a small set of documents and a query for me to reproduce?

**Comment by mmcken3** [comment]
Here is a small example mapping and a few documents:
```
PUT /testing
PUT /testing/_mapping
{
  "properties": {
    "id": {
      "type": "text",
      "fields": {
        "keyword": {
          "type": "keyword",
          "ignore_above": 256
        }
      }
    },
    "value": {
      "type": "text",
      "fields": {
        "keyword": {
          "type": "keyword",
          "ignore_above": 256
        }
      }
    }
  }
}
```
```
{
    "id": "id-1",
    "value": "value 1"
}
{
    "id": "id-2",
    "value": "value 2"
}
{
    "id": "id-3",
    "value": "value 3"
}
{
    "id": "id-4",
    "value": "value 4"
}
```
It presents an interesting case where when creating the index and mapping from code, or from kibana, the match all query in code does not work at first, but the MGets and single Gets always seem to be successful. However, if the match all is run from kibana I get all of the results returned. The minute I go and create a doc in kibana and not a doc from code then I can run a successful match all from code.

**Comment by olivere** [comment]
That's as expected. I hope [this recipe](https://github.com/olivere/elastic/blob/release-branch.v7/recipes/text_vs_keyword/main.go) does illustrate the point.
