### ISSUE TITLE
Missing term filtering on significant terms aggregation

### ISSUE THREAD

**Issue by jc0n** [olivere/elastic#1149]
### Which version of Elastic are you using?

[X ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior

The significant terms aggregation supports term filtering with `exclude`/`include` parameters. These don't appear to have been implemented yet.

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-significantterms-aggregation.html#_filtering_values

**Comment by olivere** [comment]
Yep, thanks for finding all these things. It's hard to keep on top of Elasticsearch :-)

For self-reference: https://github.com/elastic/elasticsearch/blob/7.2/server/src/main/java/org/elasticsearch/search/aggregations/bucket/significant/SignificantTermsAggregationBuilder.java#L302-L304

**Comment by olivere** [comment]
Will be included in 6.2.24 and 7.0.7.
