### ISSUE TITLE
Sort query is throwing an error

### ISSUE THREAD

**Issue by joicemjoseph** [olivere/elastic#1151]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

- [x] elastic.v7 (for Elasticsearch 7.x)

- [ ] elastic.v6 (for Elasticsearch 6.x)
- [ ] elastic.v5 (for Elasticsearch 5.x)
- [ ] elastic.v3 (for Elasticsearch 2.x)
- [ ] elastic.v2 (for Elasticsearch 1.x)

### JSON Query
```
{
  "_source": {
    "includes": [
      "timestamp"
    ]
  },
  "size": 1,
  "sort": [
    {
      "timestamp": {
        "order": "desc"
      }
    }
  ]
}
```
### JSON Response
```
{
"hits" : {
    "total" : 12635,
    "max_score" : null,
    "hits" : [
      {
        "_index" : "xxxxx",
        "_type" : "json",
        "_id" : "xxxxx+0+12634",
        "_score" : null,
        "_source" : {
          "timestamp" : "2019-07-28T06:00:11.74Z"
        },
        "sort" : [
          1564293611740
        ]
      }
    ]
  }
}
```
### Elastic Library Error
```
"json: cannot unmarshal number into Go struct field SearchHits.total of type elastic.TotalHits"
```

### Steps to reproduce

Run this query, 
`searchResult, err = es.client.Search(_index).
		Sort(timestampField, false).
		FetchSourceContext(fsc).
		Size(1).
		Do(es.ctx)`

### Line that throws error
[452](https://github.com/olivere/elastic/blob/release-branch.v7/search.go#L462)

**Comment by olivere** [comment]
It seems you're using Elastic.v7 against Elasticsearch 6.x. Is that correct?

**Comment by joicemjoseph** [comment]
Yes. I am trying to migrate from 6.x

**Comment by olivere** [comment]
For ES 6.x, you need to use v6.
For ES 7.x, you need to use v7.

You cannot mix them.
