### ISSUE TITLE
Check connect to Elasticsearch fail

### ISSUE THREAD

**Issue by thangld322** [olivere/elastic#1152]
I try to check connect to Elasticsearch cluster before setting things up but the error it returns is always nil.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
Return error when connecting to elasticsearch failed.

### Please describe the actual behavior
It returns `nil`

### Any steps to reproduce the behavior?
```
    _, err = elastic.NewClient(
        elastic.SetURL("http://127.0.0.1:xyz"),
        elastic.SetSniff(false),
        elastic.SetHealthCheck(true))
    if err != nil {
        panic(err)
    }
```
The err is still nil even when I pass `xyz` as port.
My question is how can I check connect to ES cluster.
Thanks.

**Comment by olivere** [comment]
You can ping the cluster, just like you do with `database/sql`. Here's an example: https://github.com/olivere/elastic/blob/release-branch.v7/ping_test.go.
