### ISSUE TITLE
Missing SeqNo and PrimaryTerm in GetResult structure

### ISSUE THREAD

**Issue by milinykh** [olivere/elastic#1153]
### Which version of Elastic are you using?

[X] elastic.v7 (for Elasticsearch 7.x)

### Please describe the expected behavior

Get and Multi Get requests return `_seq_no` and `_primary_term` fields. Please add them to the GetResult structure.

**Comment by olivere** [comment]
See also: https://github.com/olivere/elastic/pull/1143.

**Comment by milinykh** [comment]
Indeed. https://github.com/olivere/elastic/pull/1143 covers it.
