### ISSUE TITLE
Missing IfSeqNo and IfPrimaryTerm in IndexService, DeleteService, BulkIndexRequest and BulkDeleteRequest

### ISSUE THREAD

**Issue by milinykh** [olivere/elastic#1154]
### Which version of Elastic are you using?

[X] elastic.v7 (for Elasticsearch 7.x)

### Please describe the expected behavior

ES supports `if_seq_no` and `if_primary_term` parameters in Index, Delete and Bulk API for optimistic concurrency (e.g. https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#optimistic-concurrency-control-index). Please add support for these parameters.

**Comment by olivere** [comment]
We can make this work in https://github.com/olivere/elastic/pull/1143.

**Comment by milinykh** [comment]
Quite a few things are missing from https://github.com/olivere/elastic/pull/1143 as it is now. I've left a comment there.

**Comment by olivere** [comment]
Optimistic concurrency control will be available in v6.2.22 and v7.0.5 (or later).

Notice that you can check with `elastic.IsConflict(err)` if 409 was returned. See e.g. [here](https://github.com/olivere/elastic/blob/release-branch.v7/update_test.go#L280-L292).

**Comment by milinykh** [comment]
Thanks! Unfortunately, `elastic.IsConflict(err)` doesn't work for errors, which are returned by bulk requests.

**Comment by olivere** [comment]
@milinykh Can you create a test that illustrates that? IIRC bulk requests return errors for the individual item, so it's not entirely clear what `elastic.IsConflict(...)` should do, at least on the response-level. But we could change it to return `true` on the item-level.

**Comment by milinykh** [comment]
Currently, I check for conflicts in bulk response on per-item basis using the following logic:
```go
strings.HasPrefix(bulkResponseItem.Error.Type, "version_conflict")
```
It is somewhat hackish, but works for ES 5-7. So if `elastic.IsConflict(...)` supports `ErrorDetails` as an argument and implements somewhat similar logic, that should be fine.

I'll try to come up with a test when I have some time to spare.
