### ISSUE TITLE
AND/OR operators for BoolQuery

### ISSUE THREAD

**Issue by Nakeuh** [olivere/elastic#1155]
### Which version of Elastic are you using?

[ ] elastic.v6 (for Elasticsearch 6.x)

### Feature request 

I am currently trying to build a Go program that would use string requests of the form `aaa AND (bbb AND (aaa AND ccc)) AND ((ccc AND ddd) AND eee)` to request data from Elasticsearch.

For that, I expected to use the QueryDSL API, but unfortunately, the AND/OR operators seems to not have be implemented yet. Is this feature planned in a close future ?

**Comment by olivere** [comment]
You do `AND` and `OR` by using `Must` and `Should` etc. with a `BoolQuery`. See e.g. https://www.elastic.co/de/blog/lost-in-translation-boolean-operations-and-filters-in-the-bool-query.

**Comment by Nakeuh** [comment]
Thanks, for the quick answer ! I will look into it.
Sorry to bother you for nothing, and thanks for this project :)
