### ISSUE TITLE
Remove ValidationFailures from ClusterHealthResponse

### ISSUE THREAD

**Issue by EmilGedda** [olivere/elastic#1159]
### Which version of Elastic are you using?

[ x ] elastic.v7 (for Elasticsearch 7.x)

As of [4613d3bcf](https://github.com/elastic/elasticsearch/commit/4613d3bcf9b0cec5358e8494908f523bbc33b2ce) (3 years ago) Elasticsearch removed the `validation_failure` field from the Cluster Health endpoint. 

This field should also be removed [from the ClusterHealthResponse type](https://github.com/olivere/elastic/blob/release-branch.v7/cluster_health.go#L218) to match these changes.

More info: https://github.com/elastic/elasticsearch/issues/16979 and https://github.com/elastic/elasticsearch/pull/17773

**Comment by olivere** [comment]
Thanks for finding this. I bet there are dozens of these issues. You simply cannot keep up with the pace of ES. Will fix in the next release.
