### ISSUE TITLE
Is there an Indices Boost function to boost results from a specific index?

### ISSUE THREAD

**Issue by otherBoy** [olivere/elastic#1160]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
Is there an Indices Boost function to boost results score from a specific index?

**Comment by olivere** [comment]
Yes. You need to create the search via `SearchSource`. Here's an example: https://github.com/olivere/elastic/blob/f0e7dce2ae96d599cb81b94741494f4dd77b4331/search_source_test.go#L207-L223

**Comment by otherBoy** [comment]
Got it. Thanks :)
