### ISSUE TITLE
Scroll doesn't allow aggregations

### ISSUE THREAD

**Issue by craigching** [olivere/elastic#1167]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

When specifying a scroll query, I should be able to include an aggregation, e.g. a date histogram.

### Please describe the actual behavior

The Scroll() API doesn't have a way to specify an aggregation.  For instance, I can execute the following query and Elasticsearch will return a date histogram:

```
#!/bin/sh

curl -s \
     -v \
     'http://XXX.XXX.XXX.XXX:9200/my_index/_search?scroll=1m' \
     -H 'Content-Type: application/json' \
     --data-binary \
'{
  "aggs": {
    "2": {
      "date_histogram": {
        "field": "timeMillis",
        "interval": "30s",
        "time_zone": "America/Chicago",
        "min_doc_count": 1
      }
    }
  },
  "query": {
    "bool": {
      "must": [
        {
            "match_all": {}
        },
        {
          "match_phrase": {
            "application": {
              "query": "my_app"
            }
          }
        },
        {
          "range": {
            "timeMillis": {
              "gte": 1565909258105,
              "lte": 1565910158105,
              "format": "epoch_millis"
            }
          }
        }
      ],
      "filter": [],
      "should": [],
      "must_not": []
    }
  }
}'
```

But I can't find a way to do that with this library.

**Comment by olivere** [comment]
You can use [`SearchSource`](https://github.com/olivere/elastic/blob/release-branch.v7/search.go#L47-L54), which is a very abstract way of specifying the search query, including aggregations. [See here](https://github.com/olivere/elastic/blob/release-branch.v7/search_source_test.go) for a few examples.
