### ISSUE TITLE
Error text is incomplete

### ISSUE THREAD

**Issue by PaulWaldo** [olivere/elastic#1169]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[ X] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
When an error is returned by Elastic, a fully detailed message is returned describing the problem in detail

### Please describe the actual behavior
The error object just says "Error 400 (Bad Request): failed to parse field [location] of type [geo_shape] [type=mapper_parsing_exception]".

Using a debugger, I see that the error object has an unexposed `RootCause` field.  This tells me "expected number but found: ','".  This additional piece of information is very helpful, but hidden.

### Any steps to reproduce the behavior?
Attempt to create a malformed document and print the error returned.

**Comment by olivere** [comment]
You can simply try to cast to elastic.Error, which exposes all error details: https://github.com/olivere/elastic/blob/release-branch.v7/errors.go#L67

**Comment by PaulWaldo** [comment]
@olivere I have tried that, but had no luck.  See the comment with the compiler error below.  Am I being thick-headed?
```
	response, err = api.elasticClient.Index().
		Index(api.index).
		Type(api.docType).
		Id(id).
		BodyJson(newE).
		Do(context.Background())
	if err != nil {
		switch theErr := err.(type){
		case elastic.Error:
			// The line above gives compiler error
			// err (variable of type error) cannot have dynamic type elastic.Error (missing method Error)
		}
		fmt.Printf("Error creating document from '%s', error is '%s'\n", newE, err)
	}
```

**Comment by olivere** [comment]
Maybe it’s because it’s a pointer receiver. But there’s a test that does just that. See https://github.com/olivere/elastic/blob/release-branch.v7/errors_test.go#L43
