### ISSUE TITLE
Use of res.Found for Get() returning 404?

### ISSUE THREAD

**Issue by wcamarao** [olivere/elastic#1172]
### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

Assume a `Get()` call returning http status not found:

```
res, err := client.Get().Index(index).Id(id).Do(ctx)
if err != nil {
	// It would be great to report only infrastructure/internal server errors here.
}
if !res.Found {
	// So this property could be used to report not found errors.
}
```

### Please describe the actual behavior

However:

```
res, err := client.Get().Index(index).Id(id).Do(ctx)
if err != nil {
	// Why is an error returned here for http status not found?
}
if !res.Found {
	// That error makes this property confusing for handling not found errors.
}
```

Looking into https://github.com/olivere/elastic/blob/60d62e5b2d1c728d7cbbeb7ed9a284303ea4acd4/get_test.go it seems like there's no test/use case for `res.Found = false`.

So, if I want to handle not found errors (which are expected) in a different way from infrastructure or internal server errors (which are not expected), I'd have to write:

```
if err != nil {
	if elerr, ok := err.(*elastic.Error); ok {
		if elerr.Status == http.StatusNotFound {
			// Handle not found error
		}
	}
	// Handle infrastructure/internal server error
}
```

Would you suggest any better alternatives to this? Or maybe I'm missing something?

Thanks

**Comment by olivere** [comment]
It's the default for all clients, see e.g. the notes in the [`ResponseException`](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-low-usage-responses.html).

> A `ResponseException` is not thrown for `HEAD` requests that return a 404 status code because it is an expected `HEAD` response that simply denotes that the resource is not found. All other HTTP methods (e.g., `GET`) throw a `ResponseException` for 404 responses unless the ignore parameter contains 404.

We have the ignore parameters as well, but still behave like the official clients.

IIRC the `found` attribute is deprecated or—at least—not longer used, as it basically mirrors the 404 status code.

An example of handling this is:

```
res, err := <get-document>
if elastic.IsNotFound(err) {
  ...
  return ...
}
if err != nil {
  ...
  return ...
}
...
```

(or use a `switch...case...`)

So it's a bit like `io.EOF`, signalling something but not being an error in itself.

**Comment by wcamarao** [comment]
Sorry I missed `IsNotFound` from the get test and many thanks for your quick reply.
