### ISSUE TITLE
how to use rollup search ?

### ISSUE THREAD

**Issue by wuxinwei** [olivere/elastic#1174]
Hey, guys, I can not found any thing about rollup search after I was viewed all godoc, Can anyone tell my how to perform a rollup search request by using olivere/elastic sdk ? 
Thank you !

### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

**Comment by olivere** [comment]
What do you mean by rollup search?

**Comment by olivere** [comment]
Ah, Xpack? Sorry, that’s not implemented yet.

**Comment by wuxinwei** [comment]
> What do you mean by rollup search?

**Comment by wuxinwei** [comment]
> Ah, Xpack? Sorry, that’s not implemented yet.

Yes, I mean the rollup search, OK, I need to found other way.

**Comment by olivere** [comment]
You can always use Client.PerformRequest, but there’s no DSL.

**Comment by saifat29** [comment]
@olivere Querying from a rollup index is a very essential feature, are there any plans to support it?

**Comment by olivere** [comment]
@saifat29 I'm accepting PRs. Will create a new tracking issue for it: #1262. But in reality it's basically the Search API with a different endpoint, very easy to use with `PerformRequest` and the existing DSL for Search API.
