### ISSUE TITLE
Log request based on response

### ISSUE THREAD

**Issue by koushki** [olivere/elastic#1176]
### Which version of Elastic are you using?
elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
I would like to log the Http request if the response is 502, it looks it is not possible since the request is not returning by `PerformRequest` function. it would be nice if we can somehow inspect the request after we have the response.

we are already using `elastic.SetTraceLog` but with the method, we have to log all requests. and it is not flexible enough.

**Comment by olivere** [comment]
There's no direct way to achieve that. But you could use your own `http.Transport` to do that. See [the wiki](https://github.com/olivere/elastic/wiki/HttpTransport) for details.
