### ISSUE TITLE
Please support real go module

### ISSUE THREAD

**Issue by douglarek** [olivere/elastic#1177]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[*] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

A real go module package should have a go.mod file.
### Please describe the actual behavior

Go 1.13 go mod does not recognise `github.com/olivere/elastic/v6 v6.2.23` module
### Any steps to reproduce the behavior?

import `github.com/olivere/elastic/v6` in a real go module project.

**Comment by olivere** [comment]
We're supporting Go modules starting with elastic.v7. While it'd be possible to do so in v6, it won't make too much sense and might even break existing code. You should be able to use 6.x in a Go Modules enabled Go project, even though v6 doesn't nicely support Go modules.
