### ISSUE TITLE
Exist Filter not Working

### ISSUE THREAD

**Issue by tommoholmes10** [olivere/elastic#118]
I want to use exit filter, when i use with this code in my terminal it's working
``curl -is -XGET 'localhost:9200/witch/_search?pretty' -d '{"query":{"filtered":{"filter":{"exists":{"field":"title"}},"query":{"match":{"site":"berrybenka"}}}}}'``
but when I use this code, is not working
```go
                var q elastic.Query
                if json.Title != ""{
                    // q = elastic.NewMatchQuery("title", json.Title)
                    q = elastic.NewQueryStringQuery(json.Title)
                }else{
                    q = elastic.NewMatchAllQuery()
                }
                f := elastic.NewExistsFilter("title")
                q   = elastic.NewFilteredQuery(q).Filter(f)
                builder := client.Search().Index("witch").Query(q).From(json.From).Size(21).Sort("price", true)
                topTagsHitsAgg := elastic.NewTopHitsAggregation().Size(10).FetchSource(true)
                topTagsAgg := elastic.NewTermsAggregation().Field("brand").Size(0).SubAggregation("top_tag_hits", topTagsHitsAgg)
                builder = builder.Aggregation("top", topTagsAgg)
                searchResult, err := builder.Do()
```
please help me

**Comment by olivere** [comment]
Hi there!

The [`Exists` filter](https://github.com/olivere/elastic/blob/release-branch.v2/search_filters_exists.go) looks good. Maybe it doesn't [do what you expect](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/query-dsl-exists-filter.html) it to do, e.g. blank strings are non-null values?

If you want to see what Elastic is sending to Elasticsearch, it is best to enable the [trace log](https://github.com/olivere/elastic/wiki/Logging). You can use also use `SearchSource` to build up your query and print it to screen if you're curious. Here's an example of that technique:

```go
package main

import (
	"encoding/json"
	"fmt"

	elastic "gopkg.in/olivere/elastic.v2"
)

func main() {
	//client, _ := elastic.NewClient()

	var q elastic.Query
	q = elastic.NewQueryStringQuery("some human query")
	f := elastic.NewExistsFilter("title")
	q = elastic.NewFilteredQuery(q).Filter(f)

	builder := elastic.NewSearchSource().Query(q).From(0).Size(21).Sort("price", true)

	src, _ := json.MarshalIndent(builder.Source(), "", "  ")
	fmt.Print(string(src))
}
```

Cheers.

**Comment by tommoholmes10** [comment]
it's  blank strings.. It's still not working well.. Still search with blank strings. When I print and I run with curl it's working well

I'm very confused, Why it's still not working

**Comment by olivere** [comment]
Okay. Let's try again. Please give me the following:

1. The `curl` command you paste to the command line (the one that returns the results that you expect).
2. A working Go program that you think will do what 1. is supposed to do but doesn't.

**Comment by tommoholmes10** [comment]
it's ``curl`` code 
``curl -is -XGET 'localhost:9200/witch/_search?pretty' -d '{"from": 0,"query": {"filtered": {"filter": {"exists": {"field": "title"}},"query": {"match_all": {}}}},"size": 21,"sort": [{"price": {"order": "asc"}}]}'``
it's working well, but when I use code elastic it's not working to search Exist Filter
```go
 var q elastic.Query
if json.Title != ""{
q = elastic.NewMultiMatchQuery("something",  "title", "brand")
}else{
q = elastic.NewMatchAllQuery()
}
f := elastic.NewExistsFilter("title")
q = elastic.NewFilteredQuery(q).Filter(f)
builder := client.Search().Index("witch").Query(q).From(0).Size(21).Sort("price", true)
```

**Comment by olivere** [comment]
This code does produce exactly the request you have in your `curl` command (almost exactly byte-by-byte):

```go
package main

import (
	"encoding/json"
	"fmt"

	elastic "gopkg.in/olivere/elastic.v2"
)

func main() {
	var q elastic.Query
	q = elastic.NewMatchAllQuery()
	f := elastic.NewExistsFilter("title")
	q = elastic.NewFilteredQuery(q).Filter(f)

	builder := elastic.NewSearchSource().Query(q).From(0).Size(21).Sort("price", true)

	src, _ := json.MarshalIndent(builder.Source(), "", "  ")
	fmt.Printf("%v\n", string(src))

	// Here's how to execute the search
	/*
	client, _ := elastic.NewClient()
	res, _ := client.Search("witch").SearchSource(builder).Do()
	fmt.Printf("%d results\n", res.TotalHits())
	*/
}
```

Output:

```json
{
  "from": 0,
  "query": {
    "filtered": {
      "filter": {
        "exists": {
          "field": "title"
        }
      },
      "query": {
        "match_all": {}
      }
    }
  },
  "size": 21,
  "sort": [
    {
      "price": {
        "order": "asc"
      }
    }
  ]
}
````
