### ISSUE TITLE
how not return the source field？

### ISSUE THREAD

**Issue by yinpeihao** [olivere/elastic#1185]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

* [x] elastic.v7 (for Elasticsearch 7.x)
* [ ] elastic.v6 (for Elasticsearch 6.x)
* [ ] elastic.v5 (for Elasticsearch 5.x)
* [ ] elastic.v3 (for Elasticsearch 2.x)
* [ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
don't return source field

### Please describe the actual behavior
err:es search project err:elastic: Error 400 (Bad Request): Expected [START_OBJECT] but found [VALUE_BOOLEAN] [type=parsing_exception]

### Any steps to reproduce the behavior?
In this way, I can get the result
```golang
	searchService.Source(false)
	searchService.Query(boolQuery)
```
But in this way,I get an error（err:es search project err:elastic: Error 400 (Bad Request): Expected [START_OBJECT] but found [VALUE_BOOLEAN] [type=parsing_exception]）
```golang
         //searchService.Source(false)
	searchService.Query(boolQuery)
``` 
how not return the source field？

**Comment by olivere** [comment]
I think you might want to use FetchSource(false) and its Include and Exclude functions. See https://github.com/olivere/elastic/blob/release-branch.v7/fetch_source_context_test.go for some tests.
