### ISSUE TITLE
In NodesStatsIndexingStats struct IsThrottled not present

### ISSUE THREAD

**Issue by yogiraj99** [olivere/elastic#1189]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?
* elastic.v7 (for Elasticsearch 7.x)
* previously using elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
* IsThrottled in NodesStatsIndexingStats should be there as it was there in elastic.v5
https://github.com/olivere/elastic/blob/ca187de54e8160a36bd3e2a85cd30447d83b80ed/nodes_stats.go#L336

### Please describe the actual behavior
* IsThrottled in NodesStatsIndexingStats is not there in elastic.v7 
https://github.com/olivere/elastic/blob/ff6418bc5a1d8b53f334e39ca004cc8d593fc42c/nodes_stats.go#L337

In NodesStatsIndexingStats struct IsThrottled was there in elastic.v5 but its not there in both elastic.v6 and elastic.v7

#### Es5 response
<img width="617" alt="ES5 Response" src="https://user-images.githubusercontent.com/34642513/65015417-247f4b80-d93f-11e9-994f-01c82b2cf950.png">

#### Es7 also gives it in response
<img width="618" alt="es7 Response" src="https://user-images.githubusercontent.com/34642513/65015369-f994f780-d93e-11e9-96a0-f3c6e345bd41.png">

**Comment by olivere** [comment]
I will have a look in the Java code, maybe there are other fields missing (or have been added lately). Thanks for filing an issue.
