### ISSUE TITLE
Distance Feature Query

### ISSUE THREAD

**Issue by raynigon** [olivere/elastic#1202]
Since Elasticsearch 7.2 there is a distance_feature query available, see: https://www.elastic.co/guide/en/elasticsearch/reference/7.2/query-dsl-distance-feature-query.html

### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
Able to using the Distance Feature Query

### Please describe the actual behavior
Distance Feature Query not implemented

**Comment by olivere** [comment]
Seems like we were working on the same issue...
