### ISSUE TITLE
Got "no Elasticsearch node available" from a Google Cloud Function environment

### ISSUE THREAD

**Issue by dorian-y** [olivere/elastic#1206]
### Which version of Elastic are you using?

[X ] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[X] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
The following function works well in a docker environment
```
	es, errOpen := elastic.NewClient(
		elastic.SetURL(esURL),
	)
```
I expected the same success in Cloud Function environment.

### Please describe the actual behavior
I read all your tips about constraint environment like AppEngine https://github.com/olivere/elastic/wiki/App%20Engine.

Then I tried with disabling HealthCheck, then Sniffing then I finally tried :
```
	es, errOpen := elastic.NewSimpleClient(
		elastic.SetURL(esURL),
	)
```
I get the following error:
`health check timeout: Head http://MY_DOMAIN:9200: context deadline exceeded: no Elasticsearch node available`

### Any steps to reproduce the behavior?
Elastic search Server version : 6.8.3
Tried first with Olivere Elastic v5 then v6 then v7

Here is the result of the cluster information
`curl 'http://MY_DOMAIN:9200/_nodes/http?pretty'`
```
{
  "_nodes" : {
    "total" : 7,
    "successful" : 7,
    "failed" : 0
  },
  ....
```

From a network point of view in the GCP infrastructure : the Cloud Function and ElasticSearch server are in the same region.

The cluster is OK. I can connect to it by other mean.

Do you have any ideas? 
Thanks for any clues.

**Comment by olivere** [comment]
Please try SetSniff(false) and SetHealthcheck(false). Also, use NewSimpleClient as you generally don’t have a long-running application with serverless.

If you have ES 6.x, you must use elastic.v6.

**Comment by dorian-y** [comment]
Thanks for your quick answer. It works with v6, NewSimpleClient, SetSniff & SetHealthCheck at false

**Comment by zhenik** [comment]
Also works with v7
