### ISSUE TITLE
about bool filter 

### ISSUE THREAD

**Issue by darksea** [olivere/elastic#121]
i write:

		package main
		
		import (
			"encoding/json"
			"fmt"
			"gopkg.in/olivere/elastic.v2"
		)
		
		func main() {
			filter := elastic.NewBoolFilter()
		
			filter.Must(elastic.NewTermFilter("Status", 1))
		
			data, err := json.Marshal(filter.Source())
			if err != nil {
				panic(err)
			}
		
			fmt.Println(string(data))
		}

output is:

{"bool":{}}

why?

**Comment by olivere** [comment]
Hi!

The problem is that filters are value types in Elastic 2.0. So when you must always chain filters, as they return a new value in every setter.

Try this instead:

```go
filter = filter.Must(elastic.NewTermFilter("Status", 1))
```

This will change in Elastic 3.0 which targets Elasticsearch 2.0.

**Comment by darksea** [comment]
is bool query is same?

**Comment by olivere** [comment]
Yes. All queries and filters in Elastic 2. Just always chain setters like this and you'll never do wrong:

```go
c = c.Something(...)
````

**Comment by darksea** [comment]
thanks
