### ISSUE TITLE
TermsQuery with TermsLookup is not constructed properly

### ISSUE THREAD

**Issue by prvn** [olivere/elastic#1212]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
When using terms lookup from other index, query should look like
```
{
  "query" : {
    "bool" : {
      "filter" : {
        "terms" : {
          "proteins" : {
            "index" : "microarrays",
            "type" : "experiment",
            "id" : "experiment1234",
            "path" : "upregulated_proteins"
          }
        }
      }
    }
  }
}
```

for Golang code

```
termLookup := elastic.NewTermsLookup().
		Index("microarrays").
		Type("experiment").
		Id("experiment1234").
		Path("upregulated_proteins")
client.Search("index1").Type("doc").Query(elastic.NewBoolQuery().Filter(termLookup))
```

### Please describe the actual behavior
We get a query that looks like

```
{
"query": {
        "bool": {
            "filter": {
                "id": "experiment1234",
                "index": "microarrays",
                "path": "upregulated_proteins",
                "type": "experiment"
            }
        }
    }
}
```
which is wrong, because the `NewTermsLookup` doesn't take name which needs to go in as key into the filter

### Any steps to reproduce the behavior?

Manual query construction for this as mentioned in https://www.elastic.co/blog/terms-filter-lookup works fine, trying above golang code doesn't create correct query

Even though I wrap the termLookup in `NewTermsQuery`, it generates something like `termLookupQuery := elastic.NewTermsQuery("proteins", termLookup)`. I get something like
```
{
    "query": {
        "bool": {
            "filter": {
                "terms": {
                    "proteins": [
                        {}
                    ]
                }
            }
        }
    }
}
```
which doesn't work too

**Comment by olivere** [comment]
You're using `elastic.NewTermsLookup` as a query, which isn't what it's supposed to do.

[Here's a test](https://github.com/olivere/elastic/blob/release-branch.v7/search_queries_terms_test.go#L47-L63) to illustrate what, I think, you're trying to achieve. Does that help?

**Comment by prvn** [comment]
That works, thanks for the update, didn't realize TermsQuery itself has the lookup. Thank you!
