### ISSUE TITLE
I cannot get elasticSearchV7 when using go mod. go get gopkg.in/olivere/elastic.v7 

### ISSUE THREAD

**Issue by givetimetolife** [olivere/elastic#1213]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

hi，I cannot get elasticSearchV7 when using go mod.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)

### Please describe the expected behavior
Use go mod get olivere/elasticV7

MacBook-Pro:portal kexiao$ go get gopkg.in/olivere/elastic.v7
go: finding gopkg.in/olivere/elastic.v7 v7.0.8
go: finding gopkg.in/olivere/elastic.v7 v7.0.8
go get gopkg.in/olivere/elastic.v7: gopkg.in/olivere/elastic.v7@v7.0.8: invalid version: go.mod has non-....v7 module path "github.com/olivere/elastic/v7" at revision v7.0.8

**Comment by olivere** [comment]
That's expected. The import path is `github.com/olivere/elastic/v7`, as [documented here](https://github.com/olivere/elastic/blob/release-branch.v7/README.md#releases).
