### ISSUE TITLE
Got error : 'dial tcp ES_server_ip:9200: i/o timeout'

### ISSUE THREAD

**Issue by dorian-y** [olivere/elastic#1216]
### Which version of Elastic are you using?
[ ] elastic.v7 (for Elasticsearch 7.x)
[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
Expected that  the following query succeeds in deleting a given index
```
	req := es.DeleteByQuery().
		Index(index).
		Type(index).
		Query(elastic.NewMatchAllQuery())

	_, err := req.Do(ctx)
```

### Please describe the actual behavior
But got the following error
```
Post http://elasticsearch.my.domain:9200/myentity/myentity/_delete_by_query: dial tcp ES_server_ip:9200: i/o timeout
```
### Any steps to reproduce the behavior?

* Deploy a topic triggered cloud function

* The ES client is created using NewSimpleClient 
```
	// open connection
	es, errOpen := elastic.NewSimpleClient(
		elastic.SetURL(esURL),
		elastic.SetHealthcheck(false),
		elastic.SetSniff(false),
	)
```

* The function passes the context  `ctx context.Context` from its first parameter :
```
func MyCloudFunction(ctx context.Context, m PubSubMessage) error {
``` 
through the application, down to the `req.Do(ctx)` function :
```
	req := es.DeleteByQuery().
		Index(index).
		Type(index).
		Query(elastic.NewMatchAllQuery())

	_, err := req.Do(ctx)
```

**Information on context management**
When trying multiple debug things, first I made `ctx := context.Background()` and used this context for the ES Query instead of passing the Cloud function ctx =>  But this try made no difference, the error was the same.

Do you have any idea ?
Thanks for any clues.

**Comment by olivere** [comment]
The

  dial tcp ES_server_ip:9200: i/o timeout

... generally means that Go is unable to connect to a hostname of ES_server_ip at port 9200. Can you double check your configuration, please.

**Comment by dorian-y** [comment]
Hi,
Thank you for the quick answer.
We are checking with our infrastructure department if there is anything related to network configuration into our Cloud infrastructure.

**Comment by olivere** [comment]
Let me know if the problem persists and I’ll reopen.
