### ISSUE TITLE
Usage in a k8s pod with kube2iam

### ISSUE THREAD

**Issue by yogeek** [olivere/elastic#1218]
### Which version of Elastic are you using?

AWS ElasticSearch Service v5.5

### Question

We have successfully used this lib into a kubernetes pod to connect to an AWS ElasticSearch Service cluster by passing AWS credentials directly to the pod.

But now we would like to use [kube2iam](https://github.com/jtblin/kube2iam) to allow the pod to use an AWS role tranparently.
How is it possible to do this with your client please ?

**Comment by olivere** [comment]
I'm not using AWS, so I can't help you there.

From skimming over the README in the kube2iam project, it seems that it's running as a sidecar and acting as a proxy, so you probably only have to change the IP address of the ES cluster and use the one from the proxy. But, as I said, this is more a gut feeling than real know-how.

I'm sorry.

**Comment by yogeek** [comment]
@olivere In fact, kube2iam is deployed as a daemonset in the cluster and an iptables rule intercepts all requests destinated to AWS API to redirect them to kube2iam. Then, kube2iam get a temporary sts token from AWS (by using a role of the EC2 instance) to get credentials for the call made in the pod code.

So, is this a way for your code to make a call to AWS api without passing any credentials (like you would do if you used aws CLI for example) or are you limited by your utilization of aws sdk ?

**Comment by olivere** [comment]
OK. In terms of elastic, it simply does HTTP request/response to a URL that you define. So kube2iam should be able to do that transparently, or it wouldn’t be that useful. Simply find the correct URL and disable sniffing and healthchecks, and you should be ready to go.

**Comment by yogeek** [comment]
Just tested with sniffling and healthchecks disabled : it still does not work :(

**Comment by olivere** [comment]
You should be able to debug with plain HTTP request/response. I don't think elastic is any special here. If you can do HTTP request/response in your environment, you can use elastic.

**Comment by yogeek** [comment]
@olivere Some updates !

Here is a working code :

```
myClient := &http.Client{}
sess, err := session.NewSessionWithOptions(session.Options{
				SharedConfigState: session.SharedConfigEnable,
})
if err != nil {
    log.Bg().Error("Unable create AWS session", zap.Error(err))
	return nil, err
}
creds = sess.Config.Credentials
signer := v4.NewSigner(creds)
awsClient, err = aws_signing_client.New(signer, myClient, "es", conf.ElasticSearch.Region)
if err != nil {
	log.CheckErr("aws signing failed", err)
	return nil, err
}
esClient, err := elastic.NewClient(
		elastic.SetURL(conf.ElasticSearch.URL),
		elastic.SetScheme("https"),
		elastic.SetHttpClient(awsClient),
		elastic.SetSniff(false),
		elastic.SetHealthcheck(false),
)
```

You can ping @lmolas (who implemented it) for more details if needed.
