### ISSUE TITLE
Connection Dead

### ISSUE THREAD

**Issue by tommoholmes10** [olivere/elastic#122]
I have some scenario, How to handle if connection from ES die. If connection suddenly die, it's can retry connect again.this is my code.
```go
package main
import (
"github.com/olivere/elastic"
"fmt"
"time"
// "strings"
)
func main() {
    //client, _ := elastic.NewClient()
  for {
    delay := time.After(ForeverLoopDelay)
    client, _ := elastic.NewClient(
      elastic.SetHealthcheck(true),
      elastic.SetSniff(true),
      elastic.SetHealthcheckInterval(30 * time.Second),
      elastic.SetURL("http://localhost:9200/"),
      )
    info, code, err := client.Ping().Do()
    if err != nil {
    // Handle error
      panic(err)
    }
    fmt.Printf("Elasticsearch returned with code %d and version %s", code, info.Version.Number)
    <-delay
  }

}
```
it's cannot retry connect, and I get error 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x47e581]

goroutine 1 [running]:
github.com/olivere/elastic.(*PingService).Do(0xc20803b1a0, 0x0, 0x0, 0x0, 0x0)
	/home/tomo/Documents/go/src/github.com/olivere/elastic/ping.go:102 +0x471
main.main()
	/home/tomo/Documents/scraper/ex.go:37 +0x200

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
exit status 2
```

**Comment by olivere** [comment]
You shouldn't do that. Elastic already retries failed requests, does load balancing via round-robin, finds dead and healthy connections, detects new and removes dead nodes from the cluster. That's what the [healthchecks](https://github.com/olivere/elastic/wiki/Healthcheck) and [sniffing](https://github.com/olivere/elastic/wiki/Sniffing) procedures do.

Of course errors can still happen. You should check them on the request level, and even retry. But you should not create a new client when an error occurs. You should have one Elastic client per cluster, initialized on startup.

A new client were only necessary if you must switch clusters while running. And that's a lot more complex.

**Comment by olivere** [comment]
Here's a version that should do your infinite loop, and you can shut down ES in between.

```go
package main

import (
	"fmt"
	"log"
	"time"

	"gopkg.in/olivere/elastic.v2"
)

func main() {
	ForeverLoopDelay := 5 * time.Second
	client, err := elastic.NewClient(
		elastic.SetHealthcheck(true),
		elastic.SetSniff(true),
		elastic.SetHealthcheckInterval(30*time.Second),
		elastic.SetURL("http://localhost:9200/"),
	)
	if err != nil {
		panic(err)
	}
	for {
		delay := time.After(ForeverLoopDelay)
		info, code, err := client.Ping().Do()
		if err != nil {
			log.Printf("%v... retrying", err)
		} else {
			fmt.Printf("Elasticsearch returned with code %d and version %s\n", code, info.Version.Number)
		}
		<-delay
	}
}
```

**Comment by tommoholmes10** [comment]
Okee I see, thanks.

**Comment by dipakrp** [comment]
I have similar issue. In my case, we are using AWS ES service so we have disabled the snipping. The API works fine in general, but whenever AWS upgrades ES service, there is some downtime of about an hour or so during which it starts throwing no connection available exceptions. We have healthcheck every 3 second. After 45-60 min new clusters are up by AWS, but API still keeps throwing that no node available / dead nodes errors. Any idea why it keeps throwing this error? In most cases, it works fine - API is able to detect whenever the servers are up, but if it's down for long time, it's not able to detect it.

**Comment by olivere** [comment]
Please disable both sniffing and health checks.
