### ISSUE TITLE
No method Rescore in SearchService

### ISSUE THREAD

**Issue by Chators** [olivere/elastic#1223]
Hi,

I am a beginner on this client and I have a problem to rescore a result.
I would like to be able to use it when I use the SearchService object (https://github.com/olivere/elastic/blob/83b6b3154663f7294e3b2151b72fc7f4c64848b7/search_source.go#L48) however there is no extension for the method rescore (https://github.com/olivere/elastic/blob/83b6b3154663f7294e3b2151b72fc7f4c64848b7/search_source.go#L237) while Query, Sort have it...
Is that normal ? 

thank you

Edit:
I solved my problem by creating a NewSearchSource.Rescorer that I put in my searchService using the SearchSource method. However, this is a bit of a shame^^

**Comment by olivere** [comment]
The `SearchSource` is used in various places. Most functions on `SearchService` use an underlying `SearchSource`, but not all of them are shadowed. What you can always do is to define a `SearchSource` yourself, and pass it to `SearchService` with `SearchSource(ss *SearchSource)`, as [illustrated here](https://github.com/olivere/elastic/blob/release-branch.v7/search_test.go#L790-L802).
