### ISSUE TITLE
Bulk request in a private elasticsearch cluster from elastic.io

### ISSUE THREAD

**Issue by tomiok** [olivere/elastic#1225]
Hi @olivere, how can I include authorization token in a bulk request?

### Which version of Elastic are you using?

[x ] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
Some way to add request options in bulk request

### Please describe the actual behavior
cannot add request options in a bulk operation

**Comment by olivere** [comment]
A recent update added `http.Header` to all services. For Bulk service, it's [these two methods](https://github.com/olivere/elastic/blob/release-branch.v7/bulk.go#L87-L100). I hope that will solve your issue.

**Comment by tomiok** [comment]
@olivere Thanks Oliver
