### ISSUE TITLE
Elastic v7 go.mod declares dependency on Elastic v6 starting in v7.0.7

### ISSUE THREAD

**Issue by rwynn** [olivere/elastic#1227]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[X ] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

The go.mod file for Elastic v7 will not need to reference any artifacts from Elastic v6.

### Please describe the actual behavior

The following commit introduces a change to go.mod that seems incorrect.  

https://github.com/olivere/elastic/commit/a9864cc75396a14da6ddd5e3cef6b81dc564ed87

Adds to go.mod...
github.com/olivere/elastic v6.2.23+incompatible

### Any steps to reproduce the behavior?

Add the following dependency to your client project's go.mod

github.com/olivere/elastic/v7 v7.0.8

Run `go mod tidy` and notice that go.sum will/may include an reference to elastic v6.

**Comment by olivere** [comment]
Oh, thanks for finding this! I will have a look, hopefully today.

**Comment by olivere** [comment]
Hmm... looks like it is transitive. I cannot find any reference in v7 to `"github.com/olivere/elastic"`, but e.g. the tracing with Jaeger now uses `"github.com/olivere/elastic"` [for storing data in ES](https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/es/dependencystore/storage.go), while ES supports opentracing, which itself uses Jaeger.

But I cannot reproduce the issue with a simple ...

```
$ go test . ./aws/... ./config/... ./trace/... ./uritemplates/...
```

... right now.
