### ISSUE TITLE
Error When Enable Sniff

### ISSUE THREAD

**Issue by tommoholmes10** [olivere/elastic#123]
I get Error when enable snif. This is my code
```go
    client, _ := elastic.NewClient(
    elastic.SetHealthcheck(true),
    elastic.SetSniff(true),
    elastic.SetHealthcheckInterval(30*time.Second),
    elastic.SetURL(some_URL, some_URL),
```
this is my error message
``
http: panic serving 127.0.0.1:59197: runtime error: invalid memory address or nil pointer dereference
goroutine 33 [running]:
net/http.func·011()
	/usr/lib/go/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0x87e620, 0xbc0493)
	/usr/lib/go/src/pkg/runtime/panic.c:248 +0x18d
github.com/olivere/elastic.(*Client).PerformRequest(0x0, 0x8f2910, 0x4, 0xc2080dd480, 0xe, 0xc2080ef470, 0x784b60, 0xc2080ef4a0, 0x0, 0x0, ...)
	/home/tomo/go/src/github.com/olivere/elastic/client.go:789 +0xd76
github.com/olivere/elastic.(*SearchService).Do(0xc2080d6500, 0x908ad0, 0x0, 0x0)
	/home/tomo/go/src/github.com/olivere/elastic/search.go:324 +0xb7d
main.func·003(0xc208042a50)
``

**Comment by olivere** [comment]
Please handle the error returned from `elastic.NewClient`. What is it?

**Comment by tommoholmes10** [comment]
``panic: no Elasticsearch node available``

**Comment by olivere** [comment]
Try to figure out why Elastic does not find your Elasticsearch node/cluster. Earlier this morning I wrote [this wiki page](https://github.com/olivere/elastic/wiki/Connection-Problems) that may help you diagnose your issues.

**Comment by tommoholmes10** [comment]
hahaha I still don't understand.. Sorry

**Comment by olivere** [comment]
?

What is the output of `curl -s -XGET 'http://127.0.0.1:9200/_nodes/http?pretty=1'`?

**Comment by tommoholmes10** [comment]
I get it
``
{
  "cluster_name" : "elasticsearch",
  "nodes" : {
    "x5ico2ZwTBK-ff_Wk5kxMw" : {
      "name" : "Betty Brant",
      "transport_address" : "inet[/172.31.30.101:9300]",
      "host" : "ip-172-31-30-101",
      "ip" : "172.31.30.101",
      "version" : "1.7.1",
      "build" : "b88f43f",
      "http_address" : "inet[/172.31.30.101:9200]",
      "http" : {
        "bound_address" : "inet[/0:0:0:0:0:0:0:0:9200]",
        "publish_address" : "inet[/172.31.30.101:9200]",
        "max_content_length_in_bytes" : 104857600
      }
    }
  }
}
``

**Comment by olivere** [comment]
So can you ping `172.31.30.101:9200` from the server where Elastic runs on?

What's the output of `curl '172.31.30.101:9200'`?

**Comment by tommoholmes10** [comment]
I cannot ping it.

**Comment by olivere** [comment]
There you have it: Your connection problem.

You need to get Elasticsearch to bind to a network interface that is accessible from the server where Elastic runs on. Once you can `curl` to the `IP:port` returned by the Nodes Info API you can successfully use Elastic.

You may read up [the Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html) or the [this wiki page](https://github.com/olivere/elastic/wiki/Docker) (it is for Docker but it's a general "problem" not specific to Docker really).

**Comment by olivere** [comment]
Let me know if the problem still occurs. Closing for now.
