### ISSUE TITLE
Subaggregations not working as intended

### ISSUE THREAD

**Issue by zyriu** [olivere/elastic#1231]

**Comment by olivere** [comment]
Would be nice if you'd have kept the issue alive. Maybe others have the same problem, and it wasn't your problem but a documentation issue. Even if it was a naive issue: No need to hide. We all have bad days. We've all been there.

**Comment by zyriu** [comment]
Thanks for your kind comment. But really, as a beginner in both elastic search and golang, it was just 100% me being silly and not thinking about the issue (or lack thereof) enough.
