### ISSUE TITLE
connect go-elasticsearch 

### ISSUE THREAD

**Issue by ZP-AlwaysWin** [olivere/elastic#1233]
Now I connect to elasticsearch only to use username&password to authenticate，but username&password usually in plain text, exposed to the outside, very unsafe.
so I want to know is there a way to use the key file for authentication.

**Comment by olivere** [comment]
You have several options here. In the most simplest case using `https` already helps a lot. You might also be able to connect via anything that `net/http` is capable of doing and ES, as the server, accepts. You can [configure your own HTTP client as described here](https://github.com/olivere/elastic/wiki/HttpTransport), and the library will use that.
