### ISSUE TITLE
Unexpected panic since client.mu.Rluck

### ISSUE THREAD

**Issue by Petelin** [olivere/elastic#1234]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[ x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
never panic

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x7754ea]
goroutine 3775 [running]:
panic(0x28c85c0, 0x52c6a90)
	golang/go/src/runtime/panic.go:565 +0x2c5 fp=0xc00d419c28 sp=0xc00d419b98 pc=0x43b6e5
runtime.call256(0x0, 0x2e9a590, 0xc00c2013b0, 0x9800000098)
	golang/go/src/runtime/asm_amd64.s:522 +0x55 fp=0xc00d419e50 sp=0xc00d419d40 pc=0x4698a5
panic(0x28c85c0, 0x52c6a90)
	golang/go/src/runtime/panic.go:522 +0x1b5 fp=0xc00d419ee0 sp=0xc00d419e50 pc=0x43b5d5
runtime.panicmem(...)
	golang/go/src/runtime/panic.go:82
runtime.sigpanic()
	golang/go/src/runtime/signal_unix.go:390 +0x411 fp=0xc00d419f10 sp=0xc00d419ee0 pc=0x4515e1
sync.(*RWMutex).RLock(...)
	golang/go/src/sync/rwmutex.go:48
gopkg.in/olivere/elastic%2ev6.(*Client).PerformRequest(0x0, 0x340e840, 0xc00d3b5200, 0x2db3fb4, 0x4, 0xc00d39d560, 0x1a, 0xc00d4331d0, 0x28316a0, 0xc00d433200, ...)
	/home/ubuntu/jenkins/workspace/go/pkg/mod/gopkg.in/olivere/elastic.v6@v6.2.10/client.go:1252 +0xea fp=0xc00d41a1c0 sp=0xc00d419f10 pc=0x7754ea
gopkg.in/olivere/elastic%2ev6.(*SearchService).Do(0xc00c640a90, 0x340e840, 0xc00d3b5200, 0xa, 0xbf6bae7d0f64eec7, 0xd0824062c)
	/home/ubuntu/jenkins/workspace/go/pkg/mod/gopkg.in/olivere/elastic.v6@v6.2.10/search.go:401 +0x143 fp=0xc00d41a318 sp=0xc00d41a1c0 pc=0x7d3d63
```

### Please describe the actual behavior
unexpect panic 

### Any steps to reproduce the behavior?
no. just happen once.

**Comment by olivere** [comment]
First of all, please use a valid import path. Use `github.com/olivere/elastic` for v6 as [described here](https://github.com/olivere/elastic/blob/release-branch.v7/README.md#releases).

Then you accessed [this line](https://github.com/olivere/elastic/blob/v6.2.10/client.go#L1252) with a `*elastic.Client` of `nil`, hence the `0x0` in `(*Client).PerformRequest(0x0, `. Please make sure you use a valid `*elastic.Client` instance.
