### ISSUE TITLE
why scroll api return empty scrollId?

### ISSUE THREAD

**Issue by huanghantao** [olivere/elastic#1238]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior

I want to get scrollId.

### Please describe the actual behavior

I get empty scrollId.

### Any steps to reproduce the behavior?

it is my code:

```go
scroller := e.Es.Scroll(e.IndexName).Type("_doc").Size(100)
```

and `e.Es` is `*elastic.Client`. I can make sure the client can connect to the es server. And the index is existed.

**Comment by olivere** [comment]
When you [call `Do`](https://github.com/olivere/elastic/blob/release-branch.v7/scroll.go#L302-L312) on that `scroller`, you get the first slice of results, which is a `*SearchResult `. A `SearchResult`, when used in the context of a Scroll operation, [has a `ScrollId`](https://github.com/olivere/elastic/blob/release-branch.v7/search.go#L649).

**Comment by huanghantao** [comment]
thx.
This problem is caused by inconsistent versions of the client and server.
