### ISSUE TITLE
How can I wait until elastic is ready?

### ISSUE THREAD

**Issue by aanm** [olivere/elastic#124]
I'm connecting to elastic with the following code:
```go
		c, err := elastic.NewClient(
			elastic.SetURL("http://"+ip+":"+port),
			elastic.SetMaxRetries(10),
			elastic.SetSniff(false),
			elastic.SetErrorLog(l.New(fe, "", l.LstdFlags)),
			elastic.SetInfoLog(l.New(fo, "", l.LstdFlags)),
			elastic.SetTraceLog(l.New(ft, "", l.LstdFlags)),
		)
```
but I always get the following error:
```
2015/08/31 16:01:57 elastic: http://127.0.0.1:9200 is dead
```
Because elasticsearch isn't ready when the program reaches that code.
So is there any option that "waits" until elasticsearch is ready? I'm using `SetMaxRetries` but I'm not sure if there's also an option for timeout or something. Elastic is probably offline or not ready at all to receive connections so it would be great to have something that kept trying if it has failed and wait a couple seconds to try again.

**Comment by olivere** [comment]
Hi there!  I think it'd be better if the application would be responsible for retrying. You know, applications are different: Some want to retry indefinitely, some have very hard limits and need to fail fast (or timeout).

Using `SetMaxRetries` will help. It's a very simple process actually. The retry interval doubles with every retry starting at a random value around 100ms. I've successfully avoided to make the retry interval configurable until now ;-)

If your servers fail regularly, you could try to set a lower [health check interval](https://github.com/olivere/elastic/wiki/Healthcheck) to quickly pick up new nodes as they come alive again.

But you should reconsider using an Elasticsearch server that fails regularly or is on a slow network link. What kind of use case do you have for Elasticsearch?

**Comment by olivere** [comment]
Oh... I see you need to wait at startup... See [here](https://github.com/olivere/elastic/wiki/Client) and search for `SetHealthcheckTimeoutStartup`. That might help.

**Comment by aanm** [comment]
Thanks a lot for the reply!
Yeah, I need to wait at startup but the `SetHealthcheckTimeoutStartup` doesn't seem to work. The problem is that elastic IP might be unreachable and on that case `SetHealthcheckTimeoutStartup` doesn't seem to have the effect I want, right?

**Comment by olivere** [comment]
Hmm... you're right. The healthcheck doesn't cover that case that Elasticsearch is completely unavailable ([code](https://github.com/olivere/elastic/blob/release-branch.v2/client.go#L699)). I need to review this case.

Until then, you need a workaround such as this (untested; not even compiled ;-)):

```go
func getClient(retries int) (*elastic.Client, error) {
  wait := 1
  for {
    client, err := elastic.NewClient(...)
    if err == elastic.ErrNoClient {
      retries--
      if retries < 0 {
        return nil, err
      }
      time.Sleep(wait * time.Second)  // wait a while
      wait += wait  // maybe even increase wait time on every retry
    }
    if err != nil {
      return nil, err
    }
    return client, nil
  }
}

```

**Comment by aanm** [comment]
@olivere Thanks a lot for the support! I hope it will be on time to implement that on v3. ;-)

**Comment by olivere** [comment]
@aanm Waiting for Elasticsearch should now be possible with [this commit](https://github.com/olivere/elastic/commit/dbc490db7dacbcb6b7f1acd1e616647f6a79b86c) even if ES is unavailable when `NewClient` is called.

Here's the [test code](https://github.com/olivere/elastic/blob/release-branch.v2/client_test.go#L161).

Code has been ported into `release-branch.v3` as well.

**Comment by aanm** [comment]
@olivere Thanks but what happens it doesn't seem to work.

```go
		ec.Client, err = elastic.NewClient(
			elastic.SetURL("http://"+ip+":"+port),
			elastic.SetMaxRetries(10),
			elastic.SetHealthcheckTimeoutStartup(10*time.Second),
			elastic.SetSniff(false),
			elastic.SetErrorLog(l.New(fe, "", l.LstdFlags)),
			elastic.SetInfoLog(l.New(fo, "", l.LstdFlags)),
			//elastic.SetTraceLog(l.New(ft, "", l.LstdFlags)),
		)
		if err == nil {
			l.Printf("Success!\n")
		} else {
			l.Printf("Error %+v\n", err)
		}
```
```
2015/09/02 15:56:49 Trying to connect to ElasticSearch to 192.168.50.1, 9200
2015/09/02 15:56:49 Error no Elasticsearch node available
```

**Comment by olivere** [comment]
Okay. I'll have a look. Is the output correct in that it fails immediately after trying to connect? Did you update the package via `go get -u gopkg.in/olivere/elastic.v2`?

**Comment by aanm** [comment]
@olivere No, I did `go get -u github.com/olivere/elastic` it is still the same, no? At least my Godep.json shows:

```json
		{
			"ImportPath": "github.com/olivere/elastic",
			"Comment": "v2.0.1-3-gd0e282d",
			"Rev": "d0e282de523c8d0dde137367cca3f364588f765b"
		},
```

**Comment by olivere** [comment]
You should switch to gopkg.in/olivere/elastic.v2.

**Comment by aanm** [comment]
@olivere I switched it now with `gopkg.in/olivere/elastic.v2`, same error sorry.

**Comment by olivere** [comment]
@aanm Do you perceive a delay before the error occurs? It should be around the timeout you set via `SetHealthcheckTimeoutStartup `.

**Comment by aanm** [comment]
@olivere I was using 10 seconds, I changed to 60 and seems to work. Thank you! :-)
