### ISSUE TITLE
how using scroll and range query work together

### ISSUE THREAD

**Issue by achilsh** [olivere/elastic#1243]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
i want to using scroll api to query data from es in batches, the es query handle include range query also， 
but result.Hits.TotalHits value is eq to value which query  not include range query.
my query logic like as described above.

### Please describe the actual behavior
	tmStampQuery := elastic.NewRangeQuery("timestamp")
	tmStampQuery.Gte(*beginTime)
	tmStampQuery.Lt(*endTime) 
       //just is range query

	filterQury := elastic.NewBoolQuery().Filter(tmStampQuery)  //is bool query include range

	includeField := []string{"locate"}
	excludeField := []string{}

	fieldVal := &elastic.FetchSourceContext{}
	fieldVal.SetFetchSource(true)
	fieldVal.Include(includeField...)
	fieldVal.Exclude(excludeField...)
	
	result, err := esClient.Scroll().  //use scroll to query 
		Index(indexName).
		Type(typeName).
		Query(filterQury ).
		SearchSource(elastic.NewSearchSource().FetchSourceContext(fieldVal)).
		Size(10000).
		Do(context.Background()) {
}

**Comment by achilsh** [comment]
my query body json like this
GET /test_index/_search
{
  "query": {
    "bool": {
      "filter": [
        {
          "range": {
            "timestamp": {
              "gte": "2019-11-01T00:00:00.0778218+08:00",
              "time_zone": "+08:00",
              "lte": "2019-11-01T07:48:50.1132008+08:00"
            }
          }
        }
      ]
    }
  },
  "_source": {
    "include": [
      "locate",
      "timestamp"
    ]
  }
}

**Comment by olivere** [comment]
If you're using `SearchSource`, you _must_ specify all parameters like `Query` with it as well. In other words: If you're using `SearchSource`, you specify the whole body with it.

**Comment by achilsh** [comment]
Could you give some example for this. if  i  not use searchsource, the scroll and rangeq can work together, the scroll result is value which is ranged by queried by condition?

**Comment by olivere** [comment]
In your case, you simply need to put the `Query(...)` into the search source, not mix both `Query` and `SearchSource`.

Here are [a lot of examples of how to setup search source](https://github.com/olivere/elastic/blob/release-branch.v7/search_source_test.go).

**Comment by achilsh** [comment]
ye,i try do like this:
	includeField := []string{"locate","timestamp"}
	excludeField := []string{}

	fieldVal := &elastic.FetchSourceContext{}
	fieldVal.SetFetchSource(true)
	fieldVal.Include(includeField...).Exclude(excludeField...)

	tmStampQuery := elastic.NewRangeQuery("timestamp").Gte(beginTime).Lt(endTime).TimeZone("+08:00")
	rangeQuery:= elastic.NewBoolQuery().Filter(tmStampQuery)

	result, err := esClient.Scroll().
		Index(*indexName).
		Type(*typeName).
		SearchSource(elastic.NewSearchSource().Query(rangeQuery).FetchSourceContext(fieldVal)).
		Size(size).
		Do(context.Background()){}

this solution is valid, thanks for your help.
