### ISSUE TITLE
Batch Upsert Script

### ISSUE THREAD

**Issue by mztikz** [olivere/elastic#1245]
### Which version of Elastic are you using?

[ V ] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

Hey , I am sending this script : ```
req := elastic.NewBulkUpdateRequest().ScriptedUpsert(true).Index(ew.index).Id(tmp.Id).Script(script).Type("message")```

I am receiving error that document is missing (and he is missing its on purpose) I would expect that if its missing It will create a new document 
any Idea why its not working (I cannot set it as doc as upsert because it wont let me add Doc and script on the same request)
Script is : 
```
script := elastic.NewScript("if ((ctx._source.doc != null) && (ctx._source.doc.updated_at > params.doc.updated_at)) { ctx.op='noop'; } else { ctx._source.doc=params.doc }")
script.Param("doc", tmp)
script.Lang("painless")
```
I would add any additional necessary info.
Would appreciate any help / code snipping that will help me , Thanks a lot .

**Comment by olivere** [comment]
Could it be that you're only missing [`bulk_as_upsert`](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html#bulk-update), aka `BulkAsUpsert(true)`? Not sure if scripting and upserts really work together.

This is more of an ES question, not one of the Go driver.

**Comment by mztikz** [comment]
Hey , 
Just wanted to update i manage to make it work , 
Here is the code sample for people who might need it in the future : 

```
script := elastic.NewScript("if (ctx._source != null && ctx._source.updated_at > params.doc.updated_at) { ctx.op='noop'; } else { ctx._source=params.doc }")
script.Param("doc", tmp)
script.Lang("painless")

req := elastic.NewBulkUpdateRequest().ScriptedUpsert(true).Index(ew.index).Id(tmp.Id).Script(script).Upsert(tmp)
bulk = bulk.Add(req)

.... 
_ , err : =bulk.do(ctx)
```

BTW, 
Do not use .Type("type") if your using ES 6+ (Its deprecated and it wont work , it will do some kind of error)
