### ISSUE TITLE
Issue applying size and from to a match_all query

### ISSUE THREAD

**Issue by EwanValentine** [olivere/elastic#1248]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
The ability to define a match all query with a size and from defined. 

### Please describe the actual behavior
No limit or offset behaviour seems to be applied to a match all query.

### Any steps to reproduce the behavior?

My code:
```golang
userRes, err := s.client.Search().
		Index("users").
		Query(userTerm).
		Pretty(true).
		From(offset).
		Size(limit).
		Do(ctx)
```

I'm passing in, say a from of `0` and a size of `10`, I'm actually getting the max limit of `10000` back instead.

**Comment by olivere** [comment]
Please double-check. I've done just that a few minutes ago and it worked fine. Enable trace log to see what's really being sent over the wire.

Otherwise, share runnable code so that we can reproduce.

**Comment by EwanValentine** [comment]
Hmm, my function is:

```golang
func (s *EsSearch) FindAll(ctx context.Context, limit, offset int) ([]*model.User, error) {
	log.Println("limit offset: ", limit, offset)
	userTerm := elastic.NewMatchAllQuery()
	userRes, err := s.client.Search().
		Index("users").
		Query(userTerm).
		Pretty(true).
		From(offset).
		Size(limit).
		Do(ctx)

	if err != nil {
		return nil, errors.Wrap(err, "error fetching user")
	}

        log.Println(userRes.Hits.Hits)

        // redacted
}
```

Limit and offset are being printed out exactly as expected. I enabled trace log, but I'm not seeing a raw query for this being outputted (I am for some other queries ran else-where).  

In-fact, one I am seeing is: 

```json
{\"from\":0,\"size\":100,\"query\":{\"script_score\":{\"query\":{\"match_all\":{\"boost\":1.0}},\"script\":{\"source\":\"dotProduct(params.query_vector, doc['item_vector'])\",\"lang\":\"painless\",\"params\":{\"query_vector\":[vector data redacted]}},\"boost\":1.0}}}}]
```

Which looks as though the size/from are in the wrong part of the query?

**Comment by olivere** [comment]
Why do you think that? See [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/7.5/search-request-body.html#request-body-search-from-size).

**Comment by EwanValentine** [comment]
Hmm. Not sure in that case. Apologies for the noise.

**Comment by olivere** [comment]
> I enabled trace log, but I'm not seeing a raw query for this being outputted (I am for some other queries ran else-where).

That should indicate that you're probably not going through that code path.

Anyway. I'm very sure that `from` and `size` are correct in the client. That'd be such an obvious problem—we should've seen that before over the last few years.

**Comment by EwanValentine** [comment]
I was looking at `res.Hits.TotalHits.Value` thinking it was the results count! My bad! 🤦🏻‍♂️
