### ISSUE TITLE
Creating index example from wiki throws root mapping error

### ISSUE THREAD

**Issue by chedched** [olivere/elastic#1249]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ X] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
Create an index called "twitter" with the corresponding mapping.

### Please describe the actual behavior
Error message: Failed to parse mapping [properties]: Root mapping definition has unsupported parameters:  [location : {type=geo_point}] [suggest_field : {payloads=true, type=completion}] [tags : {type=keyword}] [type=mapper_parsing_exception]

### Any steps to reproduce the behavior?
I simply followed the steps described at https://github.com/olivere/elastic/wiki/CreateIndex. I'm aware that mapping types have been removed in V7 (https://www.elastic.co/guide/en/elasticsearch/reference/6.5/removal-of-types.html), but can't see how this should produce the mentioned error. 

As I'm quite new to Golang I suspect that I got something wrong, but the code on the Wiki page is actually pretty self explanatory.  Here is what I tried:

```
client, err := elastic.NewClient()
if err != nil {
	// Handle error
	panic(err)
}

// Create a new index.
mapping := `{
	"settings":{
		"number_of_shards":1,
		"number_of_replicas":0
	},
	"mappings":{
		"properties":{
			"tags":{
				"type":"keyword"
			},
			"location":{
				"type":"geo_point"
			},
			"suggest_field":{
				"type":"completion",
				"payloads":true
			}
		}
	}
}`

ctx := context.Background()
createIndex, err := client.CreateIndex("twitter").BodyString(mapping).Do(ctx)
if err != nil {
    // Handle error
    panic(err)
}
if !createIndex.Acknowledged {
    // Not acknowledged
}
```
Any help is highly appreciated - thank you!

**Comment by olivere** [comment]
You need to remove that `"payloads": true`, and it'll work. I've prepared [a gist](https://gist.github.com/olivere/3e2a833bbdcc2154c1686bb7fca6b958).

**Comment by olivere** [comment]
I fixed the Wiki page.

**Comment by chedched** [comment]
Thanks a lot for reacting that quickly!
