### ISSUE TITLE
Debugger hags on s.client.mu.RLock()

### ISSUE THREAD

**Issue by CssHammer** [olivere/elastic#1250]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

If using debugger and there is no elastic instance - ping results to hang of debugger. 
The line of hang is https://github.com/olivere/elastic/blob/release-branch.v7/ping.go#L122
**s.client** is **nil** in this case and debugger can`t proceed for some reason.

### Please describe the expected behavior

Code flow goes forth

### Please describe the actual behavior

Debugger hangs.

### Any steps to reproduce the behavior?

OS: MacOS Catalina
Go: go1.13.3 darwin/amd64

Make sure there is no elastic instances reachable.

**Comment by olivere** [comment]
If client is nil, there is something wrong with initialisation. How do you create and access the Ping API. Can you share a code snippet?

**Comment by CssHammer** [comment]
Ok, I found the issue in my codebase, but I think you should check pointers for nil everytime you call them to avoid panics.

**Comment by olivere** [comment]
No. It’s an error if the caller passes a nil.
