### ISSUE TITLE
SamplerAggregation contains fields that are no longer present in the ES counterpart

### ISSUE THREAD

**Issue by panychek** [olivere/elastic#1251]
### Which version of Elastic are you using?

elastic.v7 (for Elasticsearch 7.x)
elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
The `maxDocsPerValue` and `executionHint` fields do not belong here. The Sampler aggregation was broken into 2 different aggs in v5.0, and the diversity part was moved to the [Diversified Sampler](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-aggregations-bucket-diversified-sampler-aggregation.html) aggregation.

### Any steps to reproduce the behavior?
For example, this:
```go
agg := elastic.NewSamplerAggregation().MaxDocsPerValue(2);
childAgg := elastic.NewSumAggregation().Field("some_field");
agg.SubAggregation("sub_agg", childAgg);
```
will result in:
```
Error 400 (Bad Request): Unsupported property "max_docs_per_value" for aggregation "agg [type=parsing_exception]
```

The same goes for `execution_hint`

**Comment by olivere** [comment]
Yes, removed them. Finally.
