### ISSUE TITLE
suggester[term] doesn't support field [min_word_len] [type=parsing_exception]

### ISSUE THREAD

**Issue by fengbenming** [olivere/elastic#1254]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
elastic:   Version: 6.8.3, Build: oss/tar/0c48c0e/2019-08-29T19:05:24.312154Z, JVM: 1.8.0_40
olivere:   github.com/olivere/elastic v6.2.26+incompatible

expect min_word_length 
### Please describe the actual behavior
when I run the term suggester program, I got the error:  "suggester[term] doesn't support field [min_word_len] [type=parsing_exception]",  the olivere v7 is also.
how can I solve this problem, is there any configure extra need to set ?

**Comment by olivere** [comment]
Looks like it has changed to min_word_length now: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html If it’s min_word_len in elastic, that’s a bug.

**Comment by fengbenming** [comment]
tks

**Comment by olivere** [comment]
It's a bug, and it needs fixing: See [here](https://github.com/olivere/elastic/blob/release-branch.v7/suggester_term.go#L219-L221). So re-opening.

**Comment by olivere** [comment]
Will be fixed in 7.0.10 and 6.2.27.
