### ISSUE TITLE
feature, supporting other `content-type`

### ISSUE THREAD

**Issue by jmoh932** [olivere/elastic#1255]
Well, from ES side, we could specify the http header `Accept` with `json`, `yaml`, `cbor` and `smile`. All of them could work and get the suitable right responses.

Will this client library consider to support the other three content types?

**Comment by olivere** [comment]
No, quite possibly not.

This library doesn't care too much about the details of the payload or its encoding. It cares about a Go developer trying to get Go types from ES with a DSL.

In that sense it is a higher-level library than the official ES client you can find at [github.com/elastic/go-elasticsearch](https://github.com/elastic/go-elasticsearch). With the latter, you can control every detail of the HTTP request, including its encoding.

If you still want to control HTTP request/response details with this library, you can use [`client.PerformRequest`](https://github.com/olivere/elastic/blob/release-branch.v7/client.go#L1247-L1268), which all services use behind the scenes.
