### ISSUE TITLE
No error returned when the index was read-only

### ISSUE THREAD

**Issue by ikingme** [olivere/elastic#1258]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)

### Please describe the expected behavior
When the index changes to be read-only, write data to es should return an error. https://www.elastic.co/guide/en/elasticsearch/reference/7.x/disk-allocator.html

### Please describe the actual behavior
With the PUT RESTFUL api, the error can be shown with "cluster_block_exception [index [XXXXX] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)]". But with BulkSerivce.Do function no error was returned.

**Comment by olivere** [comment]
I have to look into this, but I'm confident that elastic doesn't add anything to what ES responds. But maybe it's some odd scenario that's happening. Can you create a test that illustrates the issue?

**Comment by ikingme** [comment]
@olivere 
I'm sorry for feeding back late.
The steps to reproduce  the problem:

1. Set the index to read-only with cluster setting API:
"index.blocks.read_only":true

2. Try to index a document with SDK's index api，got the error  "Error 403 (Forbidden): index[XXX]  blocked by: [FORBIDDEN/5/index read-only (api)]; [type=cluster_block_exception]". It's OK .
for example, client.Index().Index("").Id("").BodyString().Do

3. But with the bulk api，the error was nil

**Comment by olivere** [comment]
Okay, I'll try that. Thanks.

**Comment by olivere** [comment]
Added a test (abd061bc20cd5245f4be381d3aebdc68c9f01a2c) but unable to reproduce. Works as expected.
