### ISSUE TITLE
search_after has no method to clear value but only can append

### ISSUE THREAD

**Issue by mizeng** [olivere/elastic#1260]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
When I have to use search_after for several times to fetch all the data, I found the client can only append new search_after values but not replace the old one.

Code Example
```
baseQuery := e.client.Search().Index(query.TableName).Size(e.cfg.MaxFetchDocs).
		Query(hashTermQuery).Sort("_uid", true)
// init first query
			searchResult, err := baseQuery.Do(ctx) // execute
			if err != nil {
				level.Error(util.Logger).Log("msg", fmt.Sprintf("Query in index %s met error!", query.TableName))
				return nil
			}
			if searchResult.Hits.TotalHits > int64(e.cfg.MaxFetchDocs) { // need to run "search_after"
				var sortValue interface{}
				for {
					//  Get Sort value from last SearchResult
					sortValue = searchResult.Hits.Hits[e.cfg.MaxFetchDocs-1].Sort[0]
					fmt.Println(sortValue)
					// Search
					searchResult, err = baseQuery.SearchAfter(sortValue).Do(ctx) // execute
```

Running Result
```
lokiindex#HDU5aW8BUA0rscJrN6Fs
map[query:map[term:map[hash:fake:d18161:logs:job1]] search_after:[lokiindex#HDU5aW8BUA0rscJrN6Fs] size:5 sort:[map[_uid:map[order:asc]]]]
lokiindex#ITU5aW8BUA0rscJrN6Fs
map[query:map[term:map[hash:fake:d18161:logs:job1]] search_after:[lokiindex#HDU5aW8BUA0rscJrN6Fs lokiindex#ITU5aW8BUA0rscJrN6Fs] size:5 sort:[map[_uid:map[order:asc]]]]
```
### Please describe the actual behavior
Can we have a method to clear the search_after in SearchService, like "baseQuery.clearxxx()" in above? Otherwise I have to deep clone the baseQuery above which is so heavy.

Something like this
```
func (s *SearchService) SearchAfterClear() *SearchService {
	s.searchSource.searchAfterSortValues = nil
	return s
}
```

**Comment by olivere** [comment]
You can work around this by creating a new query instead of reusing the old one.

**Comment by mizeng** [comment]
building new query will make the code really ugly especially in the cases I have to change search_afater for multiple times to iterate all the data set. Is that fair enough?

**Comment by chrisharrisonkiwi** [comment]
Agreed with @mizeng If I have to make an entirely new query in the middle of the logic it's going to make quite a mess of an otherwise clean codebase. 😱
