### ISSUE TITLE
When index is automatically created in batch operation, can you specify loading mapping?

### ISSUE THREAD

**Issue by zhousheng2** [olivere/elastic#1261]
### Which version of Elastic are you using?
[ ] elastic.v7 (for Elasticsearch 7.x)

### Please describe the expected behavior
When using "elastic. Newbulkindexrequest()" to write data in bulk, the index can be created automatically. Can you specify the mapping to create it? like  this:
`
  {
  "settings": {
    "number_of_shards": 5,
    "number_of_replicas": 1,
    "refresh_interval": "10s",
    "merge": {
      "policy": {
        "floor_segment": "100m",
        "max_merged_segment": "100m"
      },
      "scheduler": {
        "max_thread_count": "1"
      }
    },
    "translog": {
      "flush_threshold_size": "100m"
    },
    "analysis" : {
      "analyzer" : {
        "ik" : {
          "tokenizer" : "ik_smart"
        }
      }
    }
  },
  "mappings": {
    "properties": {
      "HdicCity.CityName": {
        "type": "text",
        "analyzer": "ik_smart"
      },
      "HdicBizcircle.BizcircleName": {
        "type": "text",
        "analyzer": "ik_smart"
      },
      "HdicCommunity.CommunityName": {
        "type": "text",
        "analyzer": "ik_smart"
      },
      "HdicCommunity.LineNames": {
        "type": "text",
        "analyzer": "ik_smart"
      },
      "HdicCommunity.StationNames": {
        "type": "text",
        "analyzer": "ik_smart"
      }
    }
  }
}

`

### Please describe the actual behavior
Currently, the index created automatically cannot specify the number of segments, and cannot specify the word breaker
### Any steps to reproduce the behavior?
I don't know if there are any examples for customers to refer to

**Comment by olivere** [comment]
You can e.g. use [index templates](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html) to do so, and it's good practice. Please read the documentation.
