### ISSUE TITLE
Hello , can I ask a question ?  how to implement this query by /olivere/elastic 

### ISSUE THREAD

**Issue by zhang555** [olivere/elastic#1264]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[yes] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
no

### Please describe the actual behavior
no

### Any steps to reproduce the behavior?
no

I write a query , but I dont know how to change this to golang .

could you offer some help ?

this is my query:
``` 

{
  "query": {
    "bool": {
      "should": [
        {
          "range": {
            "chair_num": {
              "gt": 0
            }
          }
        },
        {
          "range": {
            "is_show": {
              "gt": 0
            }
          }
        }
      ],
      "must": {
        "match": {
          "show_id": 1112635
        }
      }
    }
  },
  "size": 50,
  "sort": {
    "online_num": {
      "order": "desc"
    }
  }
}


```

**Comment by olivere** [comment]
There are so many tests in the repository that illustrated that, see e.g. [`search_queries_bool_test.go`](https://github.com/olivere/elastic/blob/release-branch.v7/search_queries_bool_test.go#L12-L33).

In general, you should go from the inside out. Without actually testing it, it should be something like this:

```go
chairNumQ := elastic.NewRangeQuery("chair_num").Gt(0)
isShowQ := elastic.NewRangeQuery("is_show").Gt(0)
showIDQ := elastic.NewMatchQuery("show_id", 1112635) // ? Match is for text ?
boolQ := elastic.NewBoolQuery().Must(showIDQ).Should(chairNumQ, isShowQ)
resp, err := client.Search(...).Query(boolQ).Size(50).Sort("online_num", false).Do(...)
if err != nil {
  ...
}
<use resp here>
```

**Comment by zhang555** [comment]
thanks a lot
