### ISSUE TITLE
Scrolling error: cannot unmarshal number into Go struct field SearchHits.hits.total of type elastic.TotalHits

### ISSUE THREAD

**Issue by SebScoFr** [olivere/elastic#1265]
I am using version v7.0.10 of this library along with Elastic 7.5.1 which is the latest available in Elastic Cloud.

Here is the code (trimmed for the sake of this example):

```golang
scroll := elasticsearch.Client.Scroll("my_index").
    Query(query).
    Size(100).
    IgnoreUnavailable(true)
for {
    results, err := scroll.Do(context.Background())
    if err == io.EOF {
        return nil
    }
    if err != nil {
        log.Printf("Error while scrolling: %s", err.Error()) // <--- HERE
        continue
    }
}
```

This is triggering the error:

> Error while scrolling: json: cannot unmarshal number into Go struct field SearchHits.hits.total of type elastic.TotalHits

Is this because v7.0.10 of this library is different from the one I use in Elastic Cloud (Even though it's still ES7)? Anything else I am doing wrong?

Note: This seems to be only happening while scrolling. Other Search queries are working correctly.

**Comment by olivere** [comment]
The error indicates that you're using a combination of Elasticsearch 6 and elastic v7 or vice versa. The reason for this error is that ES 7.x changed the response structure to return the total hits.

See e.g. https://github.com/olivere/elastic/issues/1007 for a detailed discussion.

**Comment by SebScoFr** [comment]
@olivere As mentioned, I am using v7.0.10 with Elasticsearch 7.5.1

**Comment by olivere** [comment]
This is [the breaking change in ES 7.x](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#hits-total-now-object-search-response), and elastic v7 will parse that just fine. There is a [test for it](https://github.com/olivere/elastic/blob/release-branch.v7/search_test.go#L34-L36) (also for [Scroll API](https://github.com/olivere/elastic/blob/release-branch.v7/scroll_test.go#L64-L66)), and we're using it in production for months now.

I don't know why it is wrong in your combination.

**Comment by SebScoFr** [comment]
@olivere This is the content of my go.mod file:

```golang
module my/module

go 1.13

require (
        ...
	github.com/olivere/elastic/v7 v7.0.10
        ...
)
```

And a screenshot of our Elastic Cloud cluster.
![Screenshot 2020-01-13 at 15 13 34](https://user-images.githubusercontent.com/22073633/72267318-c70eb900-3617-11ea-9c9c-aa9ca39cc0b1.png)

This is very confusing, but I'll keep digging. Thank you.
