### ISSUE TITLE
Questions about dependencies in go.mod

### ISSUE THREAD

**Issue by harudark** [olivere/elastic#1266]
### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
I have two questions about go.mod.
1) Has `go mod tidy` been run?
Here's git diff result after running `go mod tidy` for v7.0.10:
```
diff --git a/go.mod b/go.mod
index 64b6e55..ddddc8d 100644
--- a/go.mod
+++ b/go.mod
@@ -3,15 +3,24 @@ module github.com/olivere/elastic/v7
 go 1.13

 require (
+       github.com/VividCortex/gohistogram v1.0.0 // indirect
        github.com/aws/aws-sdk-go v1.27.0
+       github.com/codahale/hdrhistogram v0.0.0-20161010025455-3a0bb77429bd // indirect
        github.com/fortytw2/leaktest v1.3.0
-       github.com/golang/mock v1.2.0 // indirect
+       github.com/go-kit/kit v0.8.0 // indirect
        github.com/google/go-cmp v0.3.1
+       github.com/google/uuid v1.1.1
+       github.com/kr/pretty v0.2.0 // indirect
        github.com/mailru/easyjson v0.7.0
+       github.com/olivere/env v1.1.0
        github.com/opentracing/opentracing-go v1.1.0
        github.com/pkg/errors v0.8.1
        github.com/smartystreets/go-aws-auth v0.0.0-20180515143844-0c1422d1fdb9
+       github.com/smartystreets/gunit v1.1.1 // indirect
+       github.com/uber/jaeger-client-go v2.21.1+incompatible
+       github.com/uber/jaeger-lib v2.2.0+incompatible
        go.opencensus.io v0.22.2
-       google.golang.org/api v0.3.1 // indirect
+       go.uber.org/atomic v1.5.1 // indirect
+       golang.org/x/sync v0.0.0-20190423024810-112230192c58
        gopkg.in/check.v1 v1.0.0-20180628173108-788fd7840127 // indirect
 )
```

2) Some modules like `github.com/olivere/env`, `github.com/uber/jaeger-client-go/log` are only used in recipe. In my opinion, these modules shouldn't be included in dependencies list of Elastic client.
One possible solution is to create an empty go.mod in recipe directory: 
https://github.com/golang/go/wiki/Modules#can-an-additional-gomod-exclude-unnecessary-content-do-modules-have-the-equivalent-of-a-gitignore-file.
Another option I can come up with is to move recipe to another repo.
What's your thoughts? Thank you very much in advance. :)

### Any steps to reproduce the behavior?
n/a

**Comment by olivere** [comment]
Yes, I should clean that up when I find some time.
