### ISSUE TITLE
Bug with empty fields in NewMultiMatchQuery 

### ISSUE THREAD

**Issue by ciolo** [olivere/elastic#1268]
### Which version of Elastic are you using?

[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
The MultiMatch query with empty fields should match the string to search in all eligible fields in documents.

### Please describe the actual behavior
If I not set the fields in query the library add double quote in fields array and this behaviour return wrong hits. 

### Any steps to reproduce the behavior?
Not set fields in NewMultiMatchQuery. E.g.:
`multiMatchQuery = NewMultiMatchQuery("string_to_match")`

**Comment by olivere** [comment]
I'm not sure what you're asking. But to me it sounds like you're asking the library to detect if you're using ES in a wrong way. It's your responsibility as an author to provide a mapping and let ES do the right thing in general. The client is just a technical component to make ES easier to access from the Go programming language.

If I understood you wrong, please advise. A running example illustrating the problem is always best.

**Comment by ciolo** [comment]
Yeah you're right, my explanation is not quite understandable. I'd like to search for a string in all fields of a document and the best option (I think) is a **MultiMatch** query. If I run this query in kibana dev tools:
`{
  "query": {
    "multi_match": {
      "query": "accident",
      "fields": []
    }
  }
}`
I get 484 hits. So, I use this statement:
`NewMultiMatchQuery("accident")` with the field `fields` empty. When I ran the code I intercepted the query with tcpdump and found that this query was being generated:
`{
  "query": {
    "multi_match": {
      "query": "incidente",
      "fields": [""]
    }
  }
}`
(Note the double quote in `fields`)
But this query return 0 hits. 
So based on your answer, my question is: is it a bug or am I wrong?

**Comment by olivere** [comment]
Okay, I see. That explains it. Thanks for the insight. In essence, there's no way (or at least no easy way) to express the 1st query with elastic. I will look into this.

**Comment by ciolo** [comment]
Ok, thank u.

**Comment by olivere** [comment]
I'm a bit hesistant to always include the `"fields"` field in the multi-match query, as that would potentially lead to existing apps suddenly behaving differently.

Does adding `"fields":["*"]` instead of `"fields":[]` match the same documents?
