### ISSUE TITLE
How can I store JSON with elastic?

### ISSUE THREAD

**Issue by hacpai** [olivere/elastic#127]
Hello, elastic is a cool project.

I will add the support of elasticsearch in [cadvisor](https://github.com/google/cadvisor).

In cadvisor, Stat object is the marshalled JSON of the ContainerStats struct found in [info/v2/container.go](https://github.com/google/cadvisor/blob/master/info/v2/container.go)

So I have a question, how can I store this stat object in ElasticSerach with elastic?

**Comment by olivere** [comment]
Hi! Elastic is just a simple library to make Elasticsearch available to the Go programming language. Your questions sounds like a more general question about how to store and retrieve data in Elasticsearch. For this, I think you first need to get familiar with Elasticsearch. The free [Definite Guide ebook](https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html) is a perfect introduction to the concepts of Elasticsearch. Especially the [data in, data out chapter](https://www.elastic.co/guide/en/elasticsearch/guide/current/data-in-data-out.html) might help you answering your question. Also, the [online docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html) and the chapter about [mappings](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html) might be valuable.

HTH. Cheers.

**Comment by hacpai** [comment]
@olivere Thank you. 

The elastic is very good.

I read the store JOSN with elastic like this.

```go
 createIndex, err := client.CreateIndex("twitter").Do()
  // Index a tweet (using JSON serialization)
  tweet1 := Tweet{User: "olivere", Message: "Take Five", Retweets: 0}
put1, err := client.Index().
    Index("twitter").
    Type("tweet").
    Id("1").
    BodyJson(tweet1).
    Do()
```

If I write like this:

```go
put1, err := client.Index().
    Index("twitter").
    Type("tweet").
    BodyJson(tweet1).
    Do()
```

Did elastic generate iid automatically?

**Comment by olivere** [comment]
Elasticsearch can create an identifier for you, automatically. Here's the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#_automatic_id_generation).

HTH.
