### ISSUE TITLE
Need to Set  Cluster Name while creating  NewClient

### ISSUE THREAD

**Issue by vishalsingla** [olivere/elastic#1270]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?
[ ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
while creating New Client need to set cluster name

### Please describe the actual behavior
while creating New Client need to set cluster name

### Any steps to reproduce the behavior?
No method of cluster name while creating NewClient

**Comment by olivere** [comment]
The cluster name is a [server-side setting](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster.name.html) that AFAIK cannot be controlled or even set by any client.

Can you explain what you mean? How'd you do that without this client with e.g. `curl`?
