### ISSUE TITLE
v5 version avg aggragation not support missing operator

### ISSUE THREAD

**Issue by lifenglsf** [olivere/elastic#1272]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
I want to avg aggragation support missing operator

### Please describe the actual behavior
query result Inconsistent

**Comment by olivere** [comment]
v5 is no longer supported.
