### ISSUE TITLE
is v6 still unsafe for production? 

### ISSUE THREAD

**Issue by saecula** [olivere/elastic#1273]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[x] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

Quick question about the status of your README: "This is a development branch that is actively being worked on. DO NOT USE IN PRODUCTION! If you want to use stable versions of Elastic, please use Go modules for the 7.x release (or later) or a dependency manager like dep for earlier releases." 
It looks like this might be an outdated statement referring to the tagged version, but I want to make sure. Should v6 still not be used for production? If that's true, what is the latest (< 6) that is safe?

Thank you!

**Comment by olivere** [comment]
Hi! I have personally used [all releases stated here](https://github.com/olivere/elastic/blob/release-branch.v7/README.md#releases) in production.

The warning is just for people that try to use the `master` and `release-branch.vX` branches directly.

HTH.

**Comment by LuckyWindsck** [comment]
@olivere 
Excuse me, I am still getting a little bit confused to the warning statement.
I understand that you are warning people who try to use development branches. 

> Hi! I have personally used [all releases stated here](https://github.com/olivere/elastic/blob/release-branch.v7/README.md#releases) in production.

However, each release stated refers to a `release-branch.vX` branch, which seems to contradict with your comment.

Can I still use the version stated in [Releases](https://github.com/olivere/elastic/blob/release-branch.v7/README.md#releases) in production?

**Comment by olivere** [comment]
There is a git branch for each version of the library (v6, v7 etc.). It moves forward as I work on it. From time to time, I'll tag the current state of the source and give it a version. You should only ever use those tagged versions, not the current state of the source.

See [here](https://github.com/olivere/elastic/releases) for a list of tagged releases (=versions).

Your favourite dependency manager uses these versions by default. E.g. when you just now use Go modules in your project and do `go get github.com/olivere/elastic/v7`, you will get version `v7.0.15`.
