### ISSUE TITLE
How to use Sort with Body in elasticClient

### ISSUE THREAD

**Issue by Shahtaj-Khalid** [olivere/elastic#1275]
Hi, 
I'm trying to use Sort() witha Body in elasticClient like below:

    query, err := filter.GetQuery()
	if err != nil {
		return nil, err
	}
	svc := r.elasticClientInternal.Scroll(r.stateIndex).Type(esType).Size(esScrollSize).Body(query).Sort(esType, true)

My goal is to sort with "_doc".

But I came to know that SORT doesn't have any importance if the BODY is provided. Is there way to use sort along with the body?

Kindly let me know, Thanks.

**Comment by olivere** [comment]
If you use `Body`, you're on your own. It overwrites everything you define with the DSL.

If you want to query and sort by `_doc` in the Scroll API without `Body`, you can use:

```
svc := client.Scroll(index).Type(typ).Query(query).Size(size).SortBy(elastic.SortByDoc{})
```

See the tests for more inspiration.

**Comment by Shahtaj-Khalid** [comment]
@olivere So we just can't use "sort" along with "Body" at all?
Also can you please tell me how can I check if scroll indeed is applied at all or not, without "body" as well? I tried logging the client response "svc" but it doesn't show any key that specifies that sort is applied on this query.

**Comment by olivere** [comment]
As I said: You either use Body or the DSL. You can’t mix them.

You can enable tracing to log request and response. See the wiki.
