### ISSUE TITLE
Wish ES dependency had more fine grained packages

### ISSUE THREAD

**Issue by hacpai** [olivere/elastic#128]

**Comment by olivere** [comment]
What do you mean?

**Comment by hacpai** [comment]
elastic is made up of 326 files. I think elastic file structure can make more fine grained.

Is it a good idea?

**Comment by olivere** [comment]
What's the purpose of doing it? At first sight, yes, it could obviously be split into multiple packages: Queries, Services etc. But put yourself into the shoes of the end-user. It would require you to e.g. import two, three or four packages instead of just one. For what benefit? Please explain.

P.S.: I mustn't do that with v2 as it would be a breaking change.

**Comment by hacpai** [comment]
@olivere This is my new PR with elastic. 

https://github.com/google/cadvisor/pull/875

It seems that the ElasticSearch dependency is too much compare with other packages like influxdb-clinet 
https://github.com/google/cadvisor/tree/master/Godeps/_workspace/src/github.com/influxdb/influxdb/client

**Comment by olivere** [comment]
@hacpai Well, the Elasticsearch API is huge. The last time I counted it had about 600 API endpoints.

But again: What is the benfit other than a smaller binary?

I'm not familiar with cAdvisor. But it seems you're only interested in log shipping log to the ELK stack. Is that correct? Then what about ripping out the bulk functionality of Elastic and use it in your cAdvisor plugin. It's pretty stable, even with Elasticsearch 2.0.

**Comment by hacpai** [comment]
@olivere Thank you @olivere .

This is a good idea.

**Comment by olivere** [comment]
It think [libbeat](https://github.com/elastic/libbeat) uses a similar approach [here](https://github.com/elastic/libbeat/tree/master/outputs/elasticsearch). Maybe it's easier to extract.
