### ISSUE TITLE
NewIndicesPutMappingService has "Type" undefined

### ISSUE THREAD

**Issue by harshit98** [olivere/elastic#1280]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
Current version 7.x for `NewIndicesPutMappingService` does not have "Type".
Ref: https://godoc.org/github.com/olivere/elastic#NewIndicesPutMappingService

### Please describe the actual behavior
```
mappingService := elastic.NewIndicesPutMappingService(ESClient)

	_, err = MappingService.
		BodyJson(CategoryMapping()).
		Type("category").
		Index(index).
		Do()
```
The "Type" was supported in version 2.x for `NewIndicesPutMappingService`.
Ref: https://godoc.org/gopkg.in/olivere/elastic.v3#IndicesPutMappingService

### Any steps to reproduce the behavior?
I'm migrating from v2 to v7 due to which I'm trying to fix breaking changes. If I'm creating a mapping service, how should I provide the document type in ES v7 ?

**Comment by olivere** [comment]
In v7, types are deprecated but still allowed. People typically use unique indices where they formerly had types and a unique type name is used and can be dropped when migrating to v8. So e.g. `cars/model` and `cars/brand` becomes `models/_doc` and `brands/_doc`. See [here](https://www.elastic.co/guide/en/elasticsearch/reference/master/removal-of-types.html) for details.

**Comment by harshit98** [comment]
@olivere I tried to do the following:

```
ctx := context.Background()

mappingService := elastic.NewIndicesPutMappingService(ESClient)

	_, err = MappingService.
		BodyJson(CategoryMapping()).
		Index(index).
		Do(ctx)
```

Now, I'm getting errors due to the `mappings type is missing`. Is there any alternative for this to do it in Golang? I'm using alternative to mapping types "Custom Type Field" but not sure, how should I deal it in Golang?

**Comment by olivere** [comment]
There is an [example recipe for mapping](https://github.com/olivere/elastic/blob/release-branch.v7/recipes/mapping/mapping.go). Maybe that helps.

**Comment by harshit98** [comment]
@olivere I'm trying to send my mappings like this:

```
func CategoryMapping() map[string]interface{} {
	mapping := map[string]interface{} {
		"properties": map[string]interface{} {
			"type": map[string]interface{}{"type": "keyword"},
			"product_id": map[string]interface{}{"type": "integer"},
			"product_name": map[string]interface{}{"type": "text"},
		},
	}

	return mapping
}

ctx := context.Background()

mappingService := elastic.NewIndicesPutMappingService(ESClient)

	_, err = MappingService.
		BodyJson(CategoryMapping()).
		Index(index).
		Do(ctx)
```
And I'm getting this error:

`Error creating mappings [elastic: Error 400 (Bad Request): Validation Failed: 1: mapping type is missing;`

I tried to create an index manually by putting mappings in the form of JSON. Somehow it works. But the code gives me error 400. How should I solve it ?

**Comment by olivere** [comment]
That's because the root field is not `mappings` in your `map`. Serialize your `mapping` variable into JSON, compare it with the example, and you'll see what's wrong.

**Comment by harshit98** [comment]
@olivere I didn't get it. I tried to replicate this problem locally. 

```
func LocationMapping() map[string]interface{} {
	// Location Mapping
	mapping := map[string]interface{} {
		"properties": map[string]interface{}{
			"lat": map[string]interface{}{"type": "float"},
			"lon": map[string]interface{}{"type": "float"},
		},
	}

	return mapping
}

_, err = elastic.NewIndicesPutMappingService(client).BodyJson(LocationMapping()).Index("user_location", ).Do(ctx)
```
And then in Kibana I get this response when I hit `GET /user_location`:

```
{
  "user_location" : {
    "aliases" : { },
    "mappings" : {
      "properties" : {
        "lat" : {
          "type" : "float"
        },
        "lon" : {
          "type" : "float"
        }
      }
    },
    "settings" : {
      "index" : {
        "creation_date" : "1580973901638",
        "number_of_shards" : "1",
        "number_of_replicas" : "1",
        "uuid" : "xIYjICIwTEujJdg6jF82HQ",
        "version" : {
          "created" : "7050199"
        },
        "provided_name" : "user_location"
      }
    }
  }
}
```
which seems to work but I didn't get the reason for above mappings issue.

**Comment by olivere** [comment]
The remark about `mappings` was when you set up the index and the mapping in one step, like [illustrated here](https://github.com/olivere/elastic/blob/release-branch.v7/recipes/mapping/mapping.go#L99).

However, [this code works fine for me](https://play.golang.org/p/7HecVKix5JL). I see no problem. Please send a reproducible test that I can run so I can fix.

**Comment by harshit98** [comment]
Awesome! now I got it where the mistake was. I was missing `mappings` root field. Also, earlier I was using: 

```
mappingService := elastic.NewIndicesPutMappingService(ESClient)

_, err = mappingService.
	   BodyJson(CategoryMapping()).
	   Index(index).
           Do(ctx)
```
I was doing multiple type mapping on single index in ES v2.3. Now this hack works:

```
newIndex, err := client.CreateIndex("category").BodyJson(CategoryMapping()).Do(ctx)
```
And because of this, in new ES v7 version, I guess I've to follow for every single type - it should have it's respective index. Thanks @olivere for help.
