### ISSUE TITLE
sort by _score

### ISSUE THREAD

**Issue by mehrdad-dev** [olivere/elastic#1281]
Hi , i want sort result search by _score filed .
But i can't find any way for this in olivere .
i can sort result by doc , but i want _score for beter result.

my code for search:
```
query := elastic.NewRawStringQuery(q)
searchResult, err := s.client.Search().
    Index(config.AppConfig.EsIndexProfile).
    Query(query).
    SearchAfter(cursor).
    SortBy(elastic.SortByDoc{}).
    Size(size).
    Pretty(true).
    Do(ctx)
```
**Can you help me ?**

### Which version of Elastic are you using?
elastic.v7 (for Elasticsearch 7.x)

**Comment by olivere** [comment]
You can find [related test cases here](https://github.com/olivere/elastic/blob/release-branch.v7/sort_test.go#L53-L105).

**Comment by mehrdad-dev** [comment]
i try to your code but response have a error :

```
 elastic: Error 400 (Bad Request): all shards failed [type=search_phase_execution_exception] 
```

```
	sorter := elastic.NewScoreSort()
	searchResult, err := s.esClient.Search().
		Index(config.AppConfig.EsIndexProfile).
		Query(query).
		SearchAfter(cursor).
		Size(size).
		SortBy(sorter).
		Pretty(true).
		Do(ctx)
```

**Comment by olivere** [comment]
Please enable tracing and send the error details.

**Comment by mehrdad-dev** [comment]
i can't find a way for sort result by _score .
when i sort by _id or doc the result is so bad . 
because is search is autocomplete and i want sort by score .

**Comment by mehrdad-dev** [comment]
when i use true for sort in search i have response but when i use false show this error :
`command call: failed to send a request: rpc error: code = Unknown desc = elastic: Error 400 (Bad Request): all shards failed [type=search_phase_execution_exception]
`


	query := elastic.NewRawStringQuery(q)
	searchResult, err := s.client.Search().
		Index(config.AppConfig.EsIndexProfile).
		Query(query).
		SearchAfter(cursor).
		Sort("_score", true).
		Size(size).
		Pretty(true).
		Do(ctx)

**Comment by mehrdad-dev** [comment]
also this code for _score with Ascending false show error :

	query := elastic.NewRawStringQuery(q)
	searchResult, err := s.client.Search().
		Index(config.AppConfig.EsIndexProfile).
		Query(query).
		SearchAfter(cursor).
		SortBy(elastic.SortInfo{Field: "_score", Ascending: false}).
		Size(size).
		Do(ctx)

**Comment by mehrdad-dev** [comment]
please check this @olivere

**Comment by olivere** [comment]
Again, please enable trace logging. All you have to do is add something like this to the set of configuration options:

```
client, err := elastic.NewClient(
  ...
  elastic.SetTraceLog(log.New(os.Stderr, "", 0)),
  ...
)
```

The above will log all requests and responses to standard error. There you'll see what Elasticsearch logs as errors, in all its glory details.

Sorting by score is done by passing `elastic.NewScoreSort()`. If that doesn't work, something else is wrong. We need to have the details, otherwise I can't help.

**Comment by mehrdad-dev** [comment]
thanks @olivere 
this is log elastic search : 
```
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip

b8
{"query":{"multi_match":{"fields":["full_name","user_name","title","first_name","last_name"],"query":"مهرداد"}},"search_after":[0],"size":10,"sort":[{"_score":{"order":"desc"}}]}
0


HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=UTF-8

{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Sort must contain at least one field."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"profile_staging","node":"EK91cdzbQt2VM5sI4kHz3g","reason":{"type":"illegal_argument_exception","reason":"Sort must contain at least one field."}}],"caused_by":{"type":"illegal_argument_exception","reason":"Sort must contain at least one field.","caused_by":{"type":"illegal_argument_exception","reason":"Sort must contain at least one field."}}},"status":400}

```

**Comment by mehrdad-dev** [comment]
when i delete line search after  query is working !

**Comment by olivere** [comment]
Syntax being created by elastic seems okay to me. The [`search_after` has a few issues you might want to consider](https://www.elastic.co/guide/en/elasticsearch/reference/7.5/search-request-body.html#request-body-search-search-after) (see the note in the documentation), but I'm afraid this is out of scope for my support of this client. Using the score as a stable indicator for pagination seems questionable to me.
