### ISSUE TITLE
Plans for span query? 

### ISSUE THREAD

**Issue by rbUUbr** [olivere/elastic#1284]
Hello! It is awesome library, thanks for it! Do you have any milestone plans for span query? And are there some challenges with it? I'm asking it because I need this functionality, and I would like to try to implement this. Are there some plans or problems for span query?

**Comment by olivere** [comment]
No plans, but IIRC there's a tracking issue for years now. You're the first to ask though. Seems Span Queries are not that popular.

If you need it today, you can revert back to [`RawStringQuery`](https://github.com/olivere/elastic/blob/release-branch.v7/search_queries_raw_string.go) ([examples](https://github.com/olivere/elastic/blob/release-branch.v7/search_queries_raw_string_test.go)).
