### ISSUE TITLE
Version 6 is not installed

### ISSUE THREAD

**Issue by ielyanov** [olivere/elastic#1286]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?
[ ] elastic.v6 (for Elasticsearch 6.x)

====
I execute command 
`docker-compose up -d --build
`
But i got error

`Step 23/28 : RUN go get gopkg.in/olivere/elastic.v6
 ---> Running in 51279699b16d
Removing intermediate container 51279699b16d
 ---> 7ee7009f0dab
Step 24/28 : RUN go get github.com/mailru/easyjson
 ---> Running in 8e0e46af8e25
Removing intermediate container 8e0e46af8e25
 ---> 576078d57fa8
Step 25/28 : RUN go install ./...
 ---> Running in fb3b52ec19f7
../../olivere/elastic/client.go:24:2: cannot find package "github.com/olivere/elastic/v7/config" in any of:
	/usr/local/go/src/github.com/olivere/elastic/v7/config (from $GOROOT)
	/go/src/github.com/olivere/elastic/v7/config (from $GOPATH)
../../olivere/elastic/bulk.go:15:2: cannot find package "github.com/olivere/elastic/v7/uritemplates" in any of:
	/usr/local/go/src/github.com/olivere/elastic/v7/uritemplates (from $GOROOT)
	/go/src/github.com/olivere/elastic/v7/uritemplates (from $GOPATH)
ERROR: Service 'pusher' failed to build: The command '/bin/sh -c go install ./...' returned a non-zero code: 1
`

What`s wrong?

**Comment by olivere** [comment]
The import path is wrong. See [here](https://github.com/olivere/elastic/blob/release-branch.v7/README.md#releases).

**Comment by ielyanov** [comment]
I install the package for version 6 (gopkg.in/olivere/elastic.v6). 
Why should I install version 7 packages?
github.com/olivere/elastic/v7/uritemplates
github.com/olivere/elastic/v7/config
