### ISSUE TITLE
Why when installing version 6, golang requires installing subpackages of version 7 ?

### ISSUE THREAD

**Issue by ielyanov** [olivere/elastic#1287]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[ Х] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
Why when installing version 6, golang requires installing subpackages of version 7 ?

**Comment by olivere** [comment]
It shouldn't. And in [this public gist](https://gist.github.com/olivere/4a18aaf6ea4d503ce1e575e11a815b6e), it doesn't.
