### ISSUE TITLE
SetSniff Always uses IP Address Rather than CNAME

### ISSUE THREAD

**Issue by grollojbv** [olivere/elastic#1290]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[X] elastic.v7 (for Elasticsearch 7.x)
[X] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

When elastic.SetSniff(true) and the ES server is configured to send an http.publish_address of the form:

"publish_address": "some.server.com/127.0.0.1:9200"

I would expect the client library to use the published CNAME ("some.server.com") when communicating with the node rather than the IP address. 

If TLS is enabled on the ES server nodes, even with elastic.SetScheme('https'), we run into problems communicating with the TLS enabled nodes as the server certificate is tied to the CNAME rather than the IP address. Unless we pass in an HTTP Client with TLS configured to InsecureSkipVerify, communication with the sniff'd nodes will fail.

### Please describe the actual behavior

The IP address is used for communicating withe the sniff'd nodes.

### Any steps to reproduce the behavior?

As the CNAME/IP:PORT form is the default in ElasticServer 7+, running a local ES 7+ is the easiest way to replicate the behavior. By enabling SetSniff, we can see that the elastic client reports having discovered a node in the cluster. For example:

"elastic: http://127.0.0.1:9200 joined the cluster"

It appears the behavior stems from the extractHostname() function in client.go, specifically at line 1009-1011. If a '/' is found, the address post-slash is used as the hostname by the client.

Believe that the following diff would change the behavior to allow for extracting the CNAME instead of the IP address and using that:

[client.go.patch.txt](https://github.com/olivere/elastic/files/4247041/client.go.patch.txt)

**Comment by olivere** [comment]
I've not yet seen a server introducing itself with a pattern like `"publish_address": "some.server.com/127.0.0.1:9200"`. You say you can configure a server to send such a publish address. How do you enforce that behaviour?

```
$ curl localhost:9200/_nodes/http | jq .
...
"publish_address": "127.0.0.1:9200",
...
```

**Comment by grollojbv** [comment]
From a fresh download of ElasticSearch 7.6.0, getting the IP address as you show is definitely the default. If you add a `http.publish_host` setting to the **elasticsearch.yml** configuration, you can replicate:

```
$ cat config/elasticsearch.yml
....
http.publish_host: localhost
...

$ curl localhost:9200/_nodes/http | jq .
... 
"publish_address": "localhost/127.0.0.1:9200",
...
```

In ElasticSearch 6.8.4, in addition to setting the `http.publish_host` configuration directive, a JVM option needs to be toggled as well:

```
$ cat config/jvm.options
...
-Des.http.cname_in_publish_address=true
...
```

I found reference to that JVM flag for 6.8 ElasticSearch servers in a few places:

https://github.com/elastic/elasticsearch/issues/22029
https://discuss.elastic.co/t/http-publish-host-was-printed-as-ip-port-instead-of-hostname-ip-port/170820/2

**Comment by olivere** [comment]
OK. Thanks for finding this. I agree that when a CNAME is returned in `publish_address`, it should be preferred to using the IP address. I will look up what the official clients do and replicate their behaviour.

**Comment by grollojbv** [comment]
Sounds great. I haven't looked at the official client behavior, but if there's anything I can do to help, I'd be glad to contribute.
