### ISSUE TITLE
Unable to create Elasticsearch client: health check timeout: no Elasticsearch node available

### ISSUE THREAD

**Issue by fnadav** [olivere/elastic#1294]
Hi,

I have an EC2 and Elasticsearch in the same VPC.
I can call on the elasticsearch https url just fine with curl from the EC2 instance,
but i fail to connect with monstache. for the following url i get:
```
elasticsearch-urls = ["https://...eu-central-1.es.amazonaws.com:443"]
```
```
Unable to create Elasticsearch client: 
health check timeout: no Elasticsearch node available
```
i've been going through the board and found [this very similar issue](https://github.com/rwynn/monstache/issues/250).
however in my case i dont have a '/' in my url.

would appreciate the help :]
ps, if i wanted to insert `elastic.SetHealthcheck(false);` in the code, where would i put it?

#### MORE INFO:
connection to docdb was no problem. elasticsearch failed.
i tried this with monstache 4.19.4, 6.5.2 and elastic 6 and 7 - always same result.

```
# curl -I https://...eu-central-1.es.amazonaws.com:443
HTTP/2 200 
date: Tue, 17 Mar 2020 13:24:44 GMT
content-type: application/json; charset=UTF-8
content-length: 514
access-control-allow-origin: *
```

also, i called 
```
curl -XGET https://...eu-central-1.es.amazonaws.com:443/_nodes/https | jq .
```
and got:
```
{
  "_nodes": {
    "total": 0,
    "successful": 0,
    "failed": 0
  },
  "cluster_name": ".:.",
  "nodes": {}
}
```
i dont actually know what the check does, but maybe its relevant.
elasticsearch definitely works tho, i have data there i can read.

**Comment by fnadav** [comment]
O_O

Worng board, very sorry :man_facepalming: :pray:

**Comment by kevinjqiu** [comment]
@fnadav  did you figure out the issue?  I'm having the exact same issue.  I have `SetSniff(false)`, and I can `curl -I ...` to my elasticsearch node and get `200 OK`, plus `elasticsearch:9200/_nodes/http` shows that all nodes are healthy.

**Comment by faskiri** [comment]
the issue seems to be the content-length


```
curl https://.....es.amazonaws.com -u admin:admin -v -XHEAD --http1.1
...
> HEAD / HTTP/1.1
> Host: ...es.amazonaws.com
> Authorization: Basic ...=
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Fri, 06 Nov 2020 17:55:54 GMT
< Content-Type: application/json; charset=UTF-8
< Content-Length: 537
< Connection: keep-alive
< Access-Control-Allow-Origin: *
<hangs - notice the content-length>

```
Without --http1.1 though, the request completes, with curl reporting an error
```
<
* transfer closed with 537 bytes remaining to read
* stopped the pause stream!
* Connection #0 to host ...es.amazonaws.com left intact
curl: (18) transfer closed with 537 bytes remaining to read
* Closing connection 0
```
