### ISSUE TITLE
Type in document index request deprecated

### ISSUE THREAD

**Issue by sanderdekoning** [olivere/elastic#1295]
I have configured the Elastic client with a warning logger ```client.SetErrorLog(...)```. Since doing this, my logs are spammed full of the following Warning logs:
```
Elasticsearch-7.5.2-8bec50e1e0ad29dad5653712cf3bb580cd1afcdf "[types removal] Specifying types in document index requests is deprecated, use the typeless endpoints instead (/{index}/_doc/{id}, /{index}/_doc, or /{index}/_create/{id})
```

How can I resolve this error/warning?

### Which version of Elastic are you using?

[X ] elastic.v7 (for Elasticsearch 7.x)

**Comment by olivere** [comment]
You can [remove types](https://www.elastic.co/guide/en/elasticsearch/reference/7.6/removal-of-types.html) from your application.

**Comment by sanderdekoning** [comment]
Thank you for the quick response, I appreciate your time! Is this a configuration in the Elastic client or in the Elastic stack configuration? The article didn't make it very clear to me. If this is out of scope of the client and is a server configuration that is incorrect I apologise for not recognising this before opening this issue.

**Comment by olivere** [comment]
You need to redesign your application to no longer use types. 7.x deprecates types, and 8.x removes them, so you only have indices now. In a nutshell: If you have an index and a type (e.g. `maps/city` or `crm/customer`), you need to reindex them to use indices only (e.g. `cities` or `customers`).

**Comment by sanderdekoning** [comment]
I see, thank you. I'll be sure to get you another shot of caffeine! It is https://github.com/sohlich/elogrus which is causing these logs. If you are familiar with it would the following line reflect the deprecated call? https://github.com/sohlich/elogrus/blob/266128d24c17cba982509f36849c70386b8c71c2/hook.go#L189

**Comment by olivere** [comment]
Yes, that's probably it. You could solve it by e.g. moving the type name into the index name. But be sure to take care of mappings etc. It's not a simple solution (and a breaking change), but I understand why the Elasticsearch people did it.

**Comment by sanderdekoning** [comment]
Moving the type name into the index name would work in my case, since all I am using Elasticsearch for is to ingest the logs produced by the Go program.

I'll probably fork the project and remove the line mentioned before, and prepending my index name with the type.
