### ISSUE TITLE
Graceful shutdown

### ISSUE THREAD

**Issue by sanderdekoning** [olivere/elastic#1296]
Is `func (c *Client) Stop() {` the correct function to gracefully shutdown the Elastic client (ie ensuring that all outgoing messages are delivered and not interrupted)? I want to make sure that when the Go program exits it waits for Elastic to deliver any outstanding messages. 

### Which version of Elastic are you using?

[X ] elastic.v7 (for Elasticsearch 7.x)

**Comment by olivere** [comment]
As you can see in [`Stop` method](https://github.com/olivere/elastic/blob/release-branch.v7/client.go#L792-L815), the only thing that happens is that the healthchecks and the sniffer are stopped.

If you're using `BulkProcessor`, you should be able to run [`Close` or its alias `Stop`](https://github.com/olivere/elastic/blob/release-branch.v7/bulk_processor.go#L350-L389) on it, not the `Client`.

`BulkProcessor` is basically for fire-and-forget bulk indexing. If you have more specific requirements than that, it's probably worthwhile to write your own bulk indexing: It's not that hard, and you control every aspect of it.

**Comment by sanderdekoning** [comment]
Great, thank you. I'll run `client.Flush().Do(ctx)` for now until I can close BulkProcessors directly
