### ISSUE TITLE
A way to aggressively remove nodes with full thread queues (HTTP 429)

### ISSUE THREAD

**Issue by kal-g** [olivere/elastic#1297]
### Which version of Elastic are you using?
[X] elastic.v7 (for Elasticsearch 7.x)

### Problem

Currently, when an ES node returns 429s, it doesn't really affect client behavior, causing requests to continue going to this node and be dropped, even if there are other underloaded nodes available.

### What I'm trying to do

As far as I can tell, the only thing that health check does is check for a 200 etc. I want to expand on this behavior by removing nodes that have returned a certain number of non-200 responses from client requests since the last health check.

Unfortunately, it doesn't seem like the health check provides a callback to modify results (like sniffer does). Is the best way to move forward to add a callback to the healthcheck, and then track the required request metrics on my own?

The other way to move forward in the short-term seems to be to do the same thing in the sniffer with the existing callback, and reduce the sniffing interval to something useable for this purpose.

**Comment by olivere** [comment]
While it probably might be possible to exclude nodes on the client side, I don't think this is a good mitigation strategy. There's a reason for these 429's, and excluding those nodes and instead throwing the data on other nodes will make them return 429 in a few seconds as well. The obvious strategy for sending too many requests is sending less requests, e.g. by throttling, or increasing capacity so that you don't run into 429 in the first place.

**Comment by kal-g** [comment]
Actually, capacity for the cluster is more than sufficient, it's usually a single node with a backed up queue while all other nodes are handling load fine with completely empty thread pool queues. We already use autoscalers to scale out the system, but because utilization is so low in this case they don't even kick in.

Seems like a poor strategy to throttle all requests just because a single node is behaving poorly, it doesn't really consider the heterogeneous behavior of nodes that could happen due to a variety of reasons.

**Comment by kal-g** [comment]
I believe the issue is further exacerbated once the thread pool gets full, because it seems all the CPU is used up rejecting the flood of incoming requests, and the node stops progressing at all. Often these nodes never recover without explicit measures.

**Comment by kal-g** [comment]
I just came across this documentation (https://github.com/olivere/elastic/wiki/Requests) and it seems based on the code that what I described above should already be happening? If a node returns a 429 it should be removed from the connection pool right?

**Comment by olivere** [comment]
The `Retrier` can be [configured (and implemented) as you like](https://github.com/olivere/elastic/blob/release-branch.v7/client.go#L715-L725), and it decides whether to retry a request or mark the node as dead. By default, the [retrier doesn't do any retries](https://github.com/olivere/elastic/blob/release-branch.v7/client.go#L97-L98), implemented by [`StopRetrier`](https://github.com/olivere/elastic/blob/release-branch.v7/retrier.go#L36-L50). In production, we generally use [`BackoffRetrier`](https://github.com/olivere/elastic/blob/release-branch.v7/retrier.go#L52-L68) with something like:

```go
client, err := elastic.NewClient(
  ...,
  elastic.SetRetrier(
    elastic.NewBackoffRetrier(
      elastic.NewExponentialBackoff(time.Duration(100*time.Millisecond), time.Duration(1*time.Minute)),
    ),
  ),
  ...
)
```

Notice that you can pass specific retriers to [Bulk API](https://github.com/olivere/elastic/blob/release-branch.v7/bulk.go#L108-L113).

[Bulk Processor](https://github.com/olivere/elastic/blob/release-branch.v7/bulk_processor.go) is a bit different again in that you only [pass a backoff](https://github.com/olivere/elastic/blob/release-branch.v7/bulk_processor.go#L138-L142) ([exponential by default](https://github.com/olivere/elastic/blob/release-branch.v7/bulk_processor.go#L64-L67)) and [the status codes when to retry](https://github.com/olivere/elastic/blob/release-branch.v7/bulk_processor.go#L144-L149) (defaults are [here](https://github.com/olivere/elastic/blob/release-branch.v7/bulk_processor.go#L21)).
