### ISSUE TITLE
json: cannot unmarshal number into Go struct field SearchHits.hits.total of type elastic.TotalHits

### ISSUE THREAD

**Issue by wangjuelong** [olivere/elastic#1298]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

- [x] elastic.v7 (for Elasticsearch 7.x)
- [ ] elastic.v6 (for Elasticsearch 6.x)
- [ ] elastic.v5 (for Elasticsearch 5.x)
- [ ] elastic.v3 (for Elasticsearch 2.x)
- [ ] elastic.v2 (for Elasticsearch 1.x)

go mod github.com/olivere/elastic/v7 v7.0.12
elasticsearch version:7.1.1

### Please describe the expected behavior
``` go
searchResult, err := elastic.NewSearchService(client).Index(index).RestTotalHitsAsInt(true).Do(context.Background())
if err != nil {
    fmt.Println(err)	// it occurs
    return
}
fmt.Println(searchResult.TotalHits())
```
the error occurred==>`json: cannot unmarshal number into Go struct field SearchHits.hits.total of type elastic.TotalHits`
### Please describe the actual behavior
It should return the real total count of the docs.
The error occurred because the RestTotalHitsAsInt parameter caused the result data not to be the result of the expected SearchResult

### Any steps to reproduce the behavior?

Follow the description of the expected behavior

**Comment by olivere** [comment]
Thanks for finding this. It will be fixed in 7.0.15.
