### ISSUE TITLE
ExponentialBackoff refers to "timeouts" when it means delay

### ISSUE THREAD

**Issue by kal-g** [olivere/elastic#1299]
[These lines](https://github.com/olivere/elastic/blob/a408b21bce29babd8dc736e28e946598a9fc5dd2/backoff.go#L70-L72) refer to a timeout for exponential backoff. 

However, as shown [here](https://github.com/olivere/elastic/blob/ee5b21a59b5b29ffd208679b6dbe96a7edb31d5a/client.go#L1370-L1386), this value is just used for delay, not timing out those requests.

**Comment by olivere** [comment]
The article which is linked to in the [documentation](https://github.com/olivere/elastic/blob/a408b21bce29babd8dc736e28e946598a9fc5dd2/backoff.go#L67-L68) states these as such, so I kept the naming.
