### ISSUE TITLE
Unit testing difficulties due to lack of query struct property accessors or exported properties

### ISSUE THREAD

**Issue by chrisharrisonkiwi** [olivere/elastic#1300]
### Which version of Elastic are you using?
[ ] elastic.v7 (for Elasticsearch 7.x)

### Please describe the expected behavior
I am unable to write unit tests to see the query string being generated by this library due to the structs properties not being exported.
If the properties like **BoolQuery.mustClauses** etc had an accessor or were exported by naming them with a cap then we could check the query being generated is as expected without the need to run the query against an actual ElasticSearch instance and checking results.

Would it be possible to update the properties from:
**BoolQuery.mustClauses** to **BoolQuery.MustClauses** etc ?

### Please describe the actual behavior
Within our codebases we have no way of pulling the generated query as a string, this makes writing unit tests against our own code bases difficult when checking against the generated queries

**Comment by olivere** [comment]
If you want to test if the JSON being generated by this library works, you're essentially unit testing this library, not your code.

If you want to see whether the `BoolQuery` generates the correct JSON, you can do so as [illustrated by this test](https://github.com/olivere/elastic/blob/release-branch.v7/search_queries_bool_test.go#L12-L33).

I'm not sure what you mean with testing the query string though.

**Comment by chrisharrisonkiwi** [comment]
Thanks for that example, I think it might just be what I need.
I get that it would appear that I might be attempting to unit test the library, but I was more looking for my API generates the correct JSON.
(End to end, not just the query builder itself.)

Thanks for the example, very much appreciate this all being open source btw!
