### ISSUE TITLE
missing error field in struct TasksGetTaskResponse

### ISSUE THREAD

**Issue by huyhvq** [olivere/elastic#1301]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)
go mod github.com/olivere/elastic/v7 v7.0.6
elasticsearch version:7.3.0

### Please describe the expected behavior
API get task by ID `_tasks/{id}` must return error field.
Ex:
```json
{
  "completed" : true,
  "task" : {
    "node" : "MO-PoeuPSX66JG1Vp02e8A",
    "id" : 128023221,
    "type" : "transport",
    "action" : "indices:data/write/update/byquery",
    "status" : {
      "total" : 154435,
      "updated" : 0,
      "created" : 0,
      "deleted" : 0,
      "batches" : 1,
      "version_conflicts" : 0,
      "noops" : 0,
      "retries" : {
        "bulk" : 0,
        "search" : 0
      },
      "throttled_millis" : 0,
      "requests_per_second" : -1.0,
      "throttled_until_millis" : 0
    },
    "description" : "update-by-query [ahjhjdongok_alias] updated with Script{type=inline, lang='painless', idOrCode='asddds', options={}, params={ahjhj='do ngok'}}",
    "start_time_in_millis" : 1585629334222,
    "running_time_in_nanos" : 11128042,
    "cancellable" : true,
    "headers" : { }
  },
  "error" : {
    "type" : "script_exception",
    "reason" : "compile error",
    "script_stack" : [
      "asddds",
      "^---- HERE"
    ],
    "script" : "asddds",
    "lang" : "painless",
    "caused_by" : {
      "type" : "illegal_argument_exception",
      "reason" : "Variable [asddds] is not defined."
    }
  }
}
```

### Please describe the actual behavior
Missing error field on _tasks api response `TasksGetTaskResponse`
https://github.com/olivere/elastic/blob/0e429faaa934317f89b23fd6005f91364fb5c1a0/tasks_get_task.go#L164-L168
### Any steps to reproduce the behavior?
POST wrong script using `_update_by_query` API
```
POST /ahjhjdongok_alias/_update_by_query?wait_for_completion=false&scroll_size=500&conflicts=proceed
{

  "script": {
    "source": "asddds",
    "params": {
      "ahjhj":  "do ngok"
    }
  }
}
```

**Comment by olivere** [comment]
Thanks for getting me notified of this. Your PR does introduce a new `ErrorDetail` struct which is incomplete, plus we already have [`ErrorDetails`](https://github.com/olivere/elastic/blob/release-branch.v7/errors.go#L72-L85) plus it doesn't add a test. I will add my own implementation in 7.0.14.
