### ISSUE TITLE
How to use retrier to handle http timeout error

### ISSUE THREAD

**Issue by i19** [olivere/elastic#1303]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
```
type MyRetrier struct {
	backoff elastic.Backoff
}

func NewMyRetrier() *MyRetrier {
	return &MyRetrier{
		backoff: elastic.NewConstantBackoff(time.Second),
	}
}

func (r *MyRetrier) Retry(ctx context.Context, retry int, req *http.Request, resp *http.Response, err error) (time.Duration, bool, error) {
	println("call myRetry")

	// Stop after 5 retries
	if retry >= 5 {
		return 0, false, nil
	}

	// Let the backoff strategy decide how long to wait and whether to stop
	wait, stop := r.backoff.Next(retry)
	return wait, stop, nil
}

func main(){
	client, _ := elastic.NewClient(
		elastic.SetRetrier(NewMyRetrier()),
		elastic.SetHttpClient(&http.Client{Timeout: time.Second * 5 }),
	)

	c, f := context.WithTimeout(context.TODO(), time.Second * 15)
	defer f()
	resp, err := client.GetMapping().Index("").Do(c)
}
```

I tried to use `SetRetrier` to handle http timeout error.  so when timeout occur, it can process request again.

### Please describe the actual behavior

When http timeout error occur, it just returned, and not  retry as expected.  

Then i found this, i'm confused

https://github.com/olivere/elastic/blob/release-branch.v7/client.go#L1366-L1368

so, what should i do ?

**Comment by olivere** [comment]
So are you trying to retry on some HTTP error, or do you want to retry when the context times out?

**Comment by i19** [comment]
i want to retry when the context times out.

**Comment by olivere** [comment]
OK, that's unexpected and should probably better be solved in the application layer. Unfortunately I can't change that behaviour because that would confuse other users that rely on exactly that behaviour of a context error being a way to make sure the request exits right away.

I wonder why you would like to retry on context errors. What kind of errors would stop the request then?

**Comment by olivere** [comment]
If there's an error with the context, the application layer must handle this.

**Comment by ats0stv** [comment]
@olivere what is the case in case of HTTP timeout. Say I have a `SimpleBackOff` with ticks as `[100,100,100]` and I set the HTTP timeout to, for example 10ms, will the client retry on three times with 100ms interval as soon as HTTP timeout happens?

**Comment by olivere** [comment]
@ats0stv Now that's two questions, I suppose: When do retries happen and how does `SimpleBackoff` work.

To answer the first question: In the end, all requests run the [`PerformRequest`](https://github.com/olivere/elastic/blob/release-branch.v7/client.go#L1309-L1507) method. This is where HTTP and retries happens.

By default, `PerformRequest` handles only a certain set of exceptions, i.e.

1. `ErrNoClient` (cluster is not available)
2. situations in which the HTTP request returns an `error` and
3. all requests that return a status code specified by [`SetRetryStatusCodes`](https://github.com/olivere/elastic/blob/release-branch.v7/client.go#L733-L742) slice (default: `nil`, but typically something like `429`, `501` etc.)

The ticks are only applied when retry actually happens, i.e. in the above 3 cases.

So to answer the first part of your question: How does your "HTTP timeout" occur? Does it occur in an exception with the HTTP request? Or does `httpClient.Do(...)` return no error but a status code of e.g. 500? Given the above explanation, you can answer the question yourself.

Regarding the actual logic of `SimpleBackoff`, it's like you said: After the retry logic sets in (in your example: 10ms), it will try 3 times with a pause of 100ms in between the tries. So if your 2nd request takes 1536msec to get to another timeout, it will wait for 100msec and try again. You typically want [`ExponentialBackoff`](https://github.com/olivere/elastic/blob/release-branch.v7/backoff.go#L65-L95) to wait exponentially longer with lots of timeouts to prevent the [thundering herd problem](https://en.wikipedia.org/wiki/Thundering_herd_problem).

EDIT: Typos.
