### ISSUE TITLE
AWS Auth Signing doesn't work for ElasticSearch record Updates

### ISSUE THREAD

**Issue by veqryn** [olivere/elastic#1306]
### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
I am running an update using this library, against elasticsearch service in aws.
All my writing and reading of records works, but the update doesn't.

```go
	// Example:
	updateScript := elastic.NewScriptInline("ctx._source.platform = params.platform").
		Lang("painless").
		Param("platform", params.Value)

	query := pixelFilterParamsQuery(start, end, params.Filter)
	query = query.Filter(elastic.NewExistsQuery(params.Field))

	update := es.client.UpdateByQuery().
		Index(indices).
		Type(typePixel).
		IgnoreUnavailable(true).
		WaitForCompletion(true).
		Refresh("true").
		Slices("auto").
		AbortOnVersionConflict().
		Query(query ).
		Script(updateScript)

	response, err := update.Do(ctx)
```

I have tracing logging turned on with the olivere/elastic client, and I get the following in my logs:

```
POST /ecm-2020-03-29%2Cecm-2020-03-30%2Cecm-2020-03-31/pixel/_update_by_query?conflicts=abort&ignore_unavailable=true&refresh=true&slices=auto&wait_for_completion=true HTTP/1.1
Host: xxxxxxxxx.us-east-1.es.amazonaws.com
User-Agent: elastic/6.2.29 (linux-amd64)
Transfer-Encoding: chunked
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip
fe
{\"query\":{\"bool\":{\"filter\":[{\"range\":{\"ts\":{\"from\":1585526400,\"include_lower\":true,\"include_upper\":false,\"to\":1585527300}}},{\"exists\":{\"field\":\"plat\"}}]}},\"script\":{\"lang\":\"painless\",\"params\":{\"plat\":\"desktop\"},\"source\":\"ctx._source.plat = params.plat\"}}
0
```

```
HTTP/2.0 403 Forbidden
Content-Length: 192
Access-Control-Allow-Origin: *
Content-Type: application/json
Date: Wed, 08 Apr 2020 22:29:18 GMT
X-Amzn-Requestid: xxxxx-7076-44dd-87d6-c5104ce241ea
{\"message\":\"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\"}
```

### Please describe the actual behavior
It should work.

### Any steps to reproduce the behavior?
Try running various update commands against aws es.

### Thoughts:
I think there is something going wrong during the signing of this request.
Like I mentioned earlier, I run a lot of other get/read queries, and none of them have issues.
We probably need to abandon https://github.com/smartystreets-archives/go-aws-auth in favor of some other signing library, as that one is archived and deprecated in 2018.

**Comment by olivere** [comment]
I don't use AWS so that's probably why I do not have such a big focus on problems on that Cloud provider. In fact, the `aws` package was never meant to be part of this library. But anyway...

Can you try the [`aws/v4` package](https://github.com/olivere/elastic/blob/release-branch.v7/aws/v4/aws_v4.go)? ~It uses the [official signer](https://docs.aws.amazon.com/sdk-for-go/api/aws/signer/v4/) instead of the deprecated library.~ Correction: It _wraps_ the official signer to be usable as a `http.RoundTripper`.

Maybe we can add a recipe on how to use the official AWS Go SDK.

**Comment by veqryn** [comment]
Hm, I didn't see that was added.
Just looking at it, I see it does something a bit weird:
```go
	switch req.Body {
	case nil:
		_, err = st.signer.Sign(req, nil, "es", st.region, now)
	default:
		buf, err := ioutil.ReadAll(req.Body)
		if err != nil {
			return nil, err
		}
		req.Body = ioutil.NopCloser(bytes.NewReader(buf))
		_, err = st.signer.Sign(req, bytes.NewReader(buf), "es", st.region, time.Now().UTC())
	}
	if err != nil {
		return nil, err
	}
	resp, err := st.client.Do(req)
	if resp != nil && resp.Body != nil {
		defer resp.Body.Close()
	}
	if err != nil {
		return nil, err
	}
	if resp.Body != nil {
		buf := new(bytes.Buffer)
		_, err = buf.ReadFrom(resp.Body)
		if err != nil {
			return nil, err
		}
		resp.Body = ioutil.NopCloser(bytes.NewReader(buf.Bytes()))
	}
	return resp, nil
```

1. If the req.Body is not a ReadSeeker, the ioutil.ReadAll will cause the whole body to be read, then when the request gets sent out the request body will not have any more content left in it.

2. Why is the response being read completely?  What if I'm streaming down 1 gazillion records and want to read them one by one so that I don't run out of memory.

If you agree these are problems, I can make a PR to fix it. Please let me know.

**Comment by olivere** [comment]
As you can see from the [CREDITS](https://github.com/olivere/elastic/blob/release-branch.v7/aws/v4/CREDITS), this is not my code, but borrowed from [this library](https://github.com/sha1sum/aws_signing_client). It was just embedded as an example. It should've better been placed in the `recipes` directory.

If there's a better way to implement that (not an AWS expert), I'm all for it. But I'm probably unable to support it. If you want to do that, I'm all for it.

**Comment by veqryn** [comment]
Ok, I've made PR's:

v7 pr: https://github.com/olivere/elastic/pull/1307

v6 pr: https://github.com/olivere/elastic/pull/1308

If possible, a new release/tag for v6 and v7 would be greatly appreciated after merging those.

**Comment by olivere** [comment]
@veqryn The PRs for v6 and v7 are being merged as I write. Notice that the PRs also remove some code that makes sure the actual response body is closed. That seemed to be a problem on AWS ES, at least in 2019, reported in #1192 and fixed in https://github.com/olivere/elastic/commit/27b7f560a121aba6b83f2a93b532935bf8beb0b5.

Can you perhaps have an eye on this to make sure it won't reappear?

**Comment by veqryn** [comment]
Thank you.

As far as that issue goes, that is not at all specific to AWS or the v4 signer.
If Golang returns a non-nil http response, the body should always be closed by whoever is reading the response body, not by some wrapper that would prevent the ability to stream the content.

Quote from http documentation on client.Do():

> If the returned error is nil, the Response will contain a non-nil Body which the user is expected to close. If the Body is not both read to EOF and closed, the Client's underlying RoundTripper (typically Transport) may not be able to re-use a persistent TCP connection to the server for a subsequent "keep-alive" request.
The request Body, if non-nil, will be closed by the underlying Transport, even on errors.
On error, any Response can be ignored. A non-nil Response with a non-nil error only occurs when CheckRedirect fails, and even then the returned Response.Body is already closed.

Looks like you already knew all that, and indeed quoted the same in that PR.
