### ISSUE TITLE
Cannot get elastic.v2

### ISSUE THREAD

**Issue by tommoholmes10** [olivere/elastic#131]
when I run ```go get gopkg.in/olivere/elastic.v2```
I get error message like this
```go/src/gopkg.in/olivere/elastic.v2/client.go:755: unknown http.Client field 'Timeout' in struct literal```

**Comment by olivere** [comment]
That's strange... just tried it; no problem. Can you try it with the -v option. Here's my output:

```sh
$ go get -v gopkg.in/olivere/elastic.v2
Fetching https://gopkg.in/olivere/elastic.v2?go-get=1
Parsing meta tags from https://gopkg.in/olivere/elastic.v2?go-get=1 (status code 200)
get "gopkg.in/olivere/elastic.v2": found meta tag main.metaImport{Prefix:"gopkg.in/olivere/elastic.v2", VCS:"git", RepoRoot:"https://gopkg.in/olivere/elastic.v2"} at https://gopkg.in/olivere/elastic.v2?go-get=1
gopkg.in/olivere/elastic.v2 (download)
gopkg.in/olivere/elastic.v2/uritemplates
gopkg.in/olivere/elastic.v2
```

Also: Which version of git are you using (`git version`)?

**Comment by olivere** [comment]
And which version of Go are you using?

**Comment by olivere** [comment]
You need at least Go version 1.3, as it was the first to have [`http.Client.Timeout`](http://golang.org/pkg/net/http/#Client) ([Go 1.3 release notes](https://golang.org/doc/go1.3)).

Elastic basically supports the current and the previous release version. They are automatically tested on Travis.
