### ISSUE TITLE
Interval field returns nil in AggregationBucketHistogramItems

### ISSUE THREAD

**Issue by rbUUbr** [olivere/elastic#1310]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
Interval field returns provided interval value

### Please describe the actual behavior
Interval field returns nil
<img width="677" alt="image" src="https://user-images.githubusercontent.com/18901132/79132223-996e1300-7db2-11ea-9118-859149398297.png">

### Any steps to reproduce the behavior?
code snippet for reproducing
```go
func do() {
  service := buildService()
  res, _ := service.Do(context.Background())
  histogram, found := res.Aggregations.Histogram("hist")
  if found {
	interval := histogram.Interval.(float64) // here we do have nil
  }
}
func buildService() *elastic.SearchService{
         return elastic.Client.
		Search().
		Index(MyIndex).
		Query(elastic.NewBoolQuery()).
                Aggregation("hist", buildHistogramAgg("subscribersCount", 100.0, 400.0))

}
func buildHistogramAgg(field string, min, max float64) elastic.Aggregation {
	return elastic.NewHistogramAggregation().
		Field(field).
		ExtendedBoundsMax(max).
		ExtendedBoundsMin(min).
		Interval(5)
}
```

Suggested solution: remove Interval field from the `AggregationBucketHistogramItems`

**Comment by rbUUbr** [comment]
json response from ES
```json
{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 3,
    "successful" : 3,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 10000,
      "relation" : "gte"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "hist" : {
      "buckets" : [
        {
          "key" : 100.0,
          "doc_count" : 9723
        },
        {
          "key" : 200.0,
          "doc_count" : 4150
        },
        {
          "key" : 300.0,
          "doc_count" : 2228
        },
        {
          "key" : 400.0,
          "doc_count" : 39
        }
      ]
    }
  }
}
```

**Comment by olivere** [comment]
It seems ES stopped returning the `interval` field from the response, but I can't find the issue or the PR in the ES repository.
