### ISSUE TITLE
Can I use elastic.v7 for both elasticsearch 5.x and 7.x

### ISSUE THREAD

**Issue by chaobian** [olivere/elastic#1312]
### Which version of Elastic are you using?
elastic.v7 (for Elasticsearch 7.x)

We have two ES clusters, one is ES 5.X while the other is 7.X. The mapping is almost the same. Can we use elastic.v7 to support both cluster?

**Comment by olivere** [comment]
You can certainly try, but some responses are simply different in ES 5.x and ES 7.x, e.g. the number of total hits is (by default) returned differently in ES 5/6 and ES 7. See here for e.g. a [list of breaking changes in 7.x](https://www.elastic.co/guide/en/elasticsearch/reference/7.6/breaking-changes-7.0.html).

Also, ES sometimes changed the way to retrieve the list of nodes in the cluster. It doesn't make any guarantees on that the ES 7 client will find the nodes in an ES 5 cluster.

In general, I would provide an interface to perform operations against an ES cluster. Here's [an example of that](https://github.com/olivere/esdiff/tree/master/elastic). That also makes testing so much easier, as you can mock the ES cluster.
