### ISSUE TITLE
Can I use Olivere.v6 for elasticsearch 7.x in Production?

### ISSUE THREAD

**Issue by mukulGoelTokopedia** [olivere/elastic#1315]
I want to use the olivere elastic.v6 library for elasticsearch 7.x in Production. I want to use elasticsearch 7.x but don't want to use GO Modules. So I am trying to use olivere's elastic.v6 library.
What would be the problems that I might face while doing so? or Is there an alternate solution to my problem?

**Comment by olivere** [comment]
You can try, but there are no guarantees. ES 6 and 7 also do return things differently, e.g. the total number of hits (unless you opt in to changing that), so you're on your own.

With regards to Go modules vs. GOPATH style, you can try to vendor the dependencies, which should be doable. I haven't tried it though.
