### ISSUE TITLE
Incorrect escaping of index names in _cat/indices API

### ISSUE THREAD

**Issue by ishanjain28** [olivere/elastic#1317]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
I expect the program to return a list of all matching indices.

### Please describe the actual behavior
It fails with `elastic: Error 403 (Forbidden)` errors.

### Any steps to reproduce the behavior?

1. Create a ES Cluster which contains indexes like, `index-2019.10.1`, `index-2019.10.2` and so on although just 2 are sufficient to demonstrate issue. 

2. Build and run this bit of code on this cluster. All it does is connect to the cluster and get all indices that match `index-2019.10`

<summary>
<details>

```go
package main

import (
	"context"
	"fmt"
	stdlog "log"
	"os"

	"github.com/olivere/elastic/v7"
	log "github.com/sirupsen/logrus"
)

func main() {
	esAddr := "http://localhost:9200"

	esclient, err := elastic.NewClient(
		elastic.SetErrorLog(stdlog.New(os.Stderr, "ELASTIC ", stdlog.LstdFlags)),
		elastic.SetInfoLog(stdlog.New(os.Stdout, "", stdlog.LstdFlags)),
		elastic.SetURL(esAddr),
		elastic.SetSniff(false),
		elastic.SetHealthcheck(false),
	)

	v, err := getAllMatchingIndices(esclient,
		"index-2019.10.*")
	if err != nil {
		log.Error(err)
	}
	fmt.Println(v)
}

func getAllMatchingIndices(client *elastic.Client, srcIndexPattern string) ([]string, error) {
	out, err := client.
		CatIndices().
		Columns("index").
		Index(srcIndexPattern).
		Do(context.Background())
	if err != nil {
		return nil, err
	}
	list := make([]string, len(out))
	for i, v := range out {
		list[i] = v.Index
	}
	return list, nil
}
```

</details>
</summary>

3. That's it. This program will fail with access denied errors. 

Whereas, If you send a similar request manually with curl, It'll work just fine. 

```sh
curl http://localhost:9200/_cat/indices/index-2019.10\*\?format\=json\&h\=index
```

The issue here is incorrect escaping of index. The relevant code is in `cat_indices.go`. 

I am not fully aware of what a index *should* look like after escaping but here is what path ends up looking like in this case,

> _cat/indices/index-2019.10.%2A

i.e. `*` is replaced with `%2A` which messes with Elasticsearch's http API.

I tried couple of different inputs like passing, `index-2019.10.\\*` and replacing `"index-2019.10.*"` with "`index-2019.10.*`" (raw literals, wrapped with backticks) but neither of these worked. The library just escapes absolutely everything.

**Comment by ishanjain28** [comment]
In v7 API, Requests delete index endpoint are also incorrectly escaped. 

A request like, `-X DELETE <host>/index_1,index_2,index_3` is escaped to `-X DELETE <host>/index_1%2Cindex_2%2Cindex_3` which then results in 403 errors. Commas **should** not be escaped in this case.

**Comment by olivere** [comment]
I've added two integration tests in https://github.com/olivere/elastic/commit/5c0861c21dfa010ad37a270bd6cc16127deb824c to check the behaviour. I can't reproduce the reported issue.

Feel free to send a reproducible test case and I can reopen to inspect.
