### ISSUE TITLE
Loss of precision when building query with Int64

### ISSUE THREAD

**Issue by ns-xlz** [olivere/elastic#1318]
my es sdk version is elastic.v6 (for Elasticsearch 6.x).
there is a loss of precision when I try to build a query with Int64.

my code like bellow:
`mustMatchQuery.Must(elastic.NewMatchQuery("parentOrderId", 459751182159713792))`

final query :
`{"query":{"bool":{"must":{"match":{"parentOrderId":{"query":459751182159713800}}}}},"size":1}`

query parameter lost precision, how can I fix it?

**Comment by olivere** [comment]
I can't reproduce. Added a test in https://github.com/olivere/elastic/commit/6f5b7504c2ad00d3d7732580534d651fdbfe4f27. Please send a reproducible test case and I can re-open.
