### ISSUE TITLE
NewIdsQuery - deprecation warning

### ISSUE THREAD

**Issue by mimol91** [olivere/elastic#1319]
### Which version of Elastic are you using?
[x] elastic.v7 (for Elasticsearch 7.x)

### Please describe the expected behavior
NewIdsQuery should not have `Deprecated` tag

### Please describe the actual behavior

Currently using `NewIdsQuery` trigger deprecation warning, even if the function itself is correct, and is not deprecated in ES7.

This function probably should not accept any argument, as there is no type in ES7

**Comment by olivere** [comment]
I agree. The deprecation is not correct in its current form. I will look at it in the next release.
