### ISSUE TITLE
Deprecation API

### ISSUE THREAD

**Issue by HYY-yu** [olivere/elastic#1321]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ X ] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

When I send a query like:

```
searchSource := elastic.NewSearchSource().
		IndexBoost(util.ProjectCon.ESIndexArticle, float64(util.ProjectCon.ESIndexBoostArticle)).
		IndexBoost(util.ProjectCon.ESIndexFeed, float64(util.ProjectCon.ESIndexBoostFeed)).
		Highlight(highligt).
		From(offset).
		Size(limit).
		Query(boolQuery)
```
I can receive a message from elasticsearch:
`
Deprecation warning: [299 Elasticsearch-7.6.1-aa751e09be0a5072e8570670309b1f12348f023b "Object format in indices_boost is deprecated, please use array format instead"]
`
I think we can hide this warn.

**Comment by olivere** [comment]
Yes, that's probably easy to solve. Thanks.
