### ISSUE TITLE
Failure to unmarshar search results received from cross-cluster elasticsearch

### ISSUE THREAD

**Issue by npac** [olivere/elastic#1322]
### Which version of Elastic are you using?

[X ] elastic.v7 (for Elasticsearch 7.x)

### Please describe the expected behavior
Search results are expected to successfully unmarshal 

### Please describe the actual behavior

Following error is observed.

> json: cannot unmarshal object into Go struct field SearchResult._clusters of type []*elastic.SearchResultCluster

### Any steps to reproduce the behavior?
Send empty search query to cross-cluster instance
Here is what the response looks like...

```
$ curl -X POST http://cross-cluster-elastic:9200/cluster1:metricbeat*, cluster2:metricbeat*/_search?pretty
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 0,
    "successful" : 0,
    "skipped" : 0,
    "failed" : 0
  },
  "_clusters" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : 0.0,
    "hits" : [ ]
  }
}

```

**Comment by olivere** [comment]
Can you confirm that the cluster is also ES 7.x?

```
$ curl -X GET http://cross-cluster-elastic:9200/
...
```

EDIT: I'm asking because there's a comment [here](https://github.com/olivere/elastic/blob/release-branch.v7/search.go#L648):

```
Clusters        []*SearchResultCluster `json:"_clusters,omitempty"`    // 6.1.0+
```

**Comment by npac** [comment]
Sure, here is the confirmation.
```bash
$ curl  -X GET http://cross-cluster-elastic:9200/
{
  "name" : "censored",
  "cluster_name" : "my-analytics-cross-cluster",
  "cluster_uuid" : "vHGieTNQQ2W0__Eg3NlWIA",
  "version" : {
    "number" : "7.5.2",
    "build_flavor" : "default",
    "build_type" : "rpm",
    "build_hash" : "8bec50e1e0ad29dad5653712cf3bb580cd1afcdf",
    "build_date" : "2020-01-15T12:11:52.313576Z",
    "build_snapshot" : false,
    "lucene_version" : "8.3.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by olivere** [comment]
Thanks. That looks like a bug. I have to figure out what ES is doing there. There must be a reason why it's been a slice and when it changed. Will fix in the next release.

**Comment by npac** [comment]
ES 6.x has the same result,  it is not a slice. It seams like the release-branch.v6/search.go does not care to unmarshal _cluster field. I noticed this issue only after upgrade of ES. I guess it was always an object.
