### ISSUE TITLE
hwo to get elastic.v7   

### ISSUE THREAD

**Issue by qianlnk** [olivere/elastic#1331]
[ ] elastic.v7 (for Elasticsearch 7.x)

go get -v gopkg.in/olivere/elastic.v7    
get "gopkg.in/olivere/elastic.v7": found meta tag get.metaImport{Prefix:"gopkg.in/olivere/elastic.v7", VCS:"git", RepoRoot:"https://gopkg.in/olivere/elastic.v7"} at //gopkg.in/olivere/elastic.v7?go-get=1
gopkg.in/olivere/elastic.v7 (download)
github.com/olivere/elastic (download)
package github.com/olivere/elastic/v7/config: cannot find package "github.com/olivere/elastic/v7/config" in any of:
        /usr/local/go/src/github.com/olivere/elastic/v7/config (from $GOROOT)
        $gppath/src/github.com/olivere/elastic/v7/config (from $GOPATH)
package github.com/olivere/elastic/v7/uritemplates: cannot find package "github.com/olivere/elastic/v7/uritemplates" in any of:
        /usr/local/go/src/github.com/olivere/elastic/v7/uritemplates (from $GOROOT)
       $gppath/src/github.com/olivere/elastic/v7/uritemplates (from $GOPATH)

go version                                                                                                      
go version go1.14.2 darwin/amd64

and go mod

go mod vendor             

go: finding module for package gopkg.in/olivere/elastic.v7
go: found gopkg.in/olivere/elastic.v7 in gopkg.in/olivere/elastic.v7 v7.0.15
go: gitlab.xunlei.cn/acc-sec/ugc-supervisor/service imports
        gopkg.in/olivere/elastic.v7: gopkg.in/olivere/elastic.v7@v7.0.15: parsing go.mod:
        module declares its path as: github.com/olivere/elastic/v7
                but was required as: gopkg.in/olivere/elastic.v7

**Comment by olivere** [comment]
As described [here](https://github.com/olivere/elastic/blob/release-branch.v7/README.md#releases):

```
$ go get github.com/olivere/elastic/v7
...
```

**Comment by qianlnk** [comment]
@olivere 

I have import

elastic "github.com/olivere/elastic/v7"

but it use elastic.v6 actually

**Comment by olivere** [comment]
In the question above you asked for v7:

```
[ ] elastic.v7 (for Elasticsearch 7.x)
```

So for v6, you should be able to do add `github.com/olivere/elastic` to your dependency manager, e.g. `dep`.
