### ISSUE TITLE
Not able to get all the Http Headers of response

### ISSUE THREAD

**Issue by dilwaria** [olivere/elastic#1333]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[# ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

I have proxy passed the elasticsearch via Nginx 
```
http {
  server {
    listen 8080;
    location / {
     add-header cache-control "public";
      proxy_pass http://localhost:9200;
    }
  }
}
```

### Please describe the expected behavior
When i hit the my elastic via net/http module i am able to retrieve this added header :
`testing-header map[Cache-Control:[public]  Server:[nginx] Date:[Tue, 19 May 2020 11:09:12 GMT] Content-Type:[application/json; charset=UTF-8] Content-Length:[199] Connection:[keep-alive]]
`

But when i am fetching response headers in from client.go  : 
(https://github.com/olivere/elastic/blob/release-branch.v7/client.go#L1364 )

```
	// Get response
		res, err := c.c.Do((*http.Request)(req).WithContext(ctx))

		fmt.Println("in res", res)
		fmt.Println("in res now", res.Header)
```
i am geting the partial header 

`in res &{200 OK 200 HTTP/1.1 1 1 map[Content-Type:[application/json; charset=UTF-8]] 0xc4200ee900 -1 [] false true map[] 0xc420138d00 <nil>}
in res now map[Content-Type:[application/json; charset=UTF-8]]
`

**Comment by olivere** [comment]
Did you disable sniffing and healthchecks with `SetSniff(false)`and `SetHealthchecks(false)`?

**Comment by dilwaria** [comment]
NO, i didnt

**Comment by olivere** [comment]
Please try that. With sniffing enabled, the first step is to ask the ES cluster for the IPs of the individual nodes and perform node balancing between them. See [here](https://github.com/olivere/elastic/wiki/Sniffing) for a better description.

**Comment by deepakvarshney** [comment]
Hi Olivere,

I think the issue is we are not receiving headers in gopkg.in/olivere/elastic.v6.SearchResult Header attribute that we are setting in nginx config.
Can you please explain how it is related to sniffing?

**Comment by olivere** [comment]
When sniffing, you are not going through nginx and the proxy you set up. Instead, only the first request to find the cluster nodes goes through the proxy. After that, the client is talking to the nodes directly.

**Comment by dilwaria** [comment]
Hello Olivere,
Is this sniffing behavior also exists in ` gopkg.in/olivere/elastic.v5` also . Do we need to make similar changes, if we are using v5 to get the headers there.

And also one more thing  if we do not do sniffing changes then requests will go though nginx -> elastic  or  directly  to elastic ?

**Comment by olivere** [comment]
Sniffing has been in there since v1, and it's defaults have never been changed.

If you disable sniffing, all requests will go to the URL you specified.
If you enable sniffing (the default), only the initial request will go to the URL you specify—in order to get the actual IPs of the nodes, which are used for client-side balancing then.

Notice that if you disable sniffing, _you_ are responsible for load balancing. Nginx is a very good solution for load-balancing as a proxy before ES. You should probably look once your cluster gets a bit of load. Or use a dedicated ES node for doing the LB.
