### ISSUE TITLE
func SetURL(urls ...string) ClientOptionFunc not robust

### ISSUE THREAD

**Issue by hanjm** [olivere/elastic#1339]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[☑️] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
return error: invalid url: 127.0.0.1:9200
1. should chek urls and fail fast, before (*Client).startupHealthcheck.
2. error should carry necessary context infomation, such as url. otherwise misleading to locate problem.
### Please describe the actual behavior
return error: health check timeout: no Elasticsearch node available

### Any steps to reproduce the behavior?
elastic.NewClient(elastic.SetURL(xxx:9200))

I found some one other has meet similar situation, especial <https://github.com/olivere/elastic/issues/58>, and such as  <https://github.com/olivere/elastic/issues?q=health+check+timeout> it is very confuse with sniff issue .

the root cause is the NewClient does not validate the url. then dohealthCheck will always timeout, and just reutrn health check timeout, no other error context message. it is very confusing. i think SetURL shoud check url and return error before dohealthCheck.
here should be better.

```go
// SetURL defines the URL endpoints of the Elasticsearch nodes. Notice that
// when sniffing is enabled, these URLs are used to initially sniff the
// cluster on startup.
func SetURL(urls ...string) ClientOptionFunc {
	return func(c *Client) error {
		switch len(urls) {
		case 0:
			c.urls = []string{DefaultURL}
		default:
			for _, v := range urls {
				if _, err := url.Parse(v); err != nil {
					return fmt.Errorf("invalid url:%s, err:%s", v, err)
				}
			}
			c.urls = urls
		}
		return nil
	}
}
```

**Comment by olivere** [comment]
The main issue you have is that 127.0.0.1:9200 is not a valid URL. That’s what the error message states. Please try http://127.0.0.1:9200 instead.

**Comment by hanjm** [comment]
hi  @olivere , here should be better?

```go
// SetURL defines the URL endpoints of the Elasticsearch nodes. Notice that
// when sniffing is enabled, these URLs are used to initially sniff the
// cluster on startup.
func SetURL(urls ...string) ClientOptionFunc {
	return func(c *Client) error {
		switch len(urls) {
		case 0:
			c.urls = []string{DefaultURL}
		default:
			for _, v := range urls {
				if _, err := url.Parse(v); err != nil {
					return fmt.Errorf("invalid url:%s, err:%s", v, err)
				}
			}
			c.urls = urls
		}
		return nil
	}
}
```

**Comment by olivere** [comment]
Sorry, I'm not sure I understand. You mean you want the `SetURL` method to check the URLs passed? Yes, that can be done. But in general, simply use a valid URL.

**Comment by hanjm** [comment]
yes. i think SetURL shoud check url and return error before dohealthCheck. thanks:)

**Comment by olivere** [comment]
It's actually a bit more complex that initially thought. The client will, by default, ignore invalid URLs when specified in `SetURL(...)`. The reason for that is that URLs are [canconicalized here](https://github.com/olivere/elastic/blob/release-branch.v7/canonicalize.go#L21-L31) and invalid URLs are simply skipped.

So if you only pass invalid URLs, it will fall back to the default URL, which—in your case—seem to be unavailable and run into the given error.

So, yes, the URLs can and probably should be checked. But the reason for your error is somehow different than you probably think.
