### ISSUE TITLE
more_like_this query: specify documents instead of text

### ISSUE THREAD

**Issue by brocaar** [olivere/elastic#134]
First of all thanks for providing this great library :-)

I'm currently working on a ``more_like_this`` query and I noticed that your implementation might be slightly off compared to the documentation: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-mlt-query.html

Your ``NewMoreLikeThisQuery`` requires a ``likeText`` argument. However, following the documentation, the ``like_text`` argument in the ES query is optional, since it is possible to provide a list of ``docs`` too (ES 1.7.x). Or did I miss something?

**Comment by olivere** [comment]
Thanks for the kind words.

Yes, you're right. Seems I have to back-port the [`MoreLikeThisQuery` from elastic.v3](https://github.com/olivere/elastic/blob/release-branch.v3/search_queries_more_like_this.go) ... it has all the latest changes to the `MoreLikeThisQuery`.

Notice that Elastic documentation is very good, but I use the Java source as the definite "source of truth" (insert Linus quote here :-)). Here's [`MoreLikeThisQueryBuilder`](https://github.com/elastic/elasticsearch/blob/1.7/src/main/java/org/elasticsearch/index/query/MoreLikeThisQueryBuilder.java) for reference.

**Comment by brocaar** [comment]
Thanks for your quick respond and fix!

**Comment by olivere** [comment]
I backported the majority of `MoreLikeThis` as implemented in Elastic v3 (targeting Elasticsearch 2.x).

Notice that `MoreLikeThis` has [changed significantly](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/query-dsl-mlt-query.html) in ES 2.x. E.g. you can have "unlike" and more than one "like text".
