### ISSUE TITLE
Idea: Add helpers to avoid rewriting code in similar projects

### ISSUE THREAD

**Issue by rbUUbr** [olivere/elastic#1346]
Hi! This is really great library that helps us to build flexible API over ElasticSearch. Currently we do have a need to build our own helpers over this library to build some complex queries over our data. In our code we do have something like this (one of examples):
`shared.BuildTermsQuery("tags", []string{"tag1", "tag2"})`
and `BuildTermsQuery` function:
```go
// BuildTermsQuery builds terms query for elasticsearch
func BuildTermsQuery(field string, values []string) elastic.Query {
	terms := make([]interface{}, len(values))
	for i, key := range values {
		terms[i] = key
	}

	return elastic.NewTermsQuery(field, terms...)
}
```
I would like to propose adding helper functions in this library that will add some syntax sugar to build  queries over nested data, to build list of `term` queries with `must` relation and some other examples. It will help users to not rewrite their own code in 2 or more projects.

I would like to add some syntax sugar, that will help users to write complex queries over their data.
WDYT about it? I can add more examples/add PR with examples if you think that it can be possible.

**Comment by olivere** [comment]
What about `NewTermsQueryFromStrings(field string, values ...string)`?
