### ISSUE TITLE
Highlight Tags not working

### ISSUE THREAD

**Issue by bonjourclaudio** [olivere/elastic#1347]
I have the same problem. I implemented it the same way as in the provided Test.

```golang
boolQuery := elastic.NewBoolQuery().
		Must(elastic.NewQueryStringQuery(queryValue)).
		MustNot(elastic.NewMultiMatchQuery("test", "contenttype"))

	hl := elastic.NewHighlight().
		Field("content").
		PreTags("<em>").
		PostTags("</em>")

	searchResult, err := es.Client.Search().
		Index(index).
		Highlight(hl).
		Query(boolQuery).
		RestTotalHitsAsInt(true).
		From(from).Size(size).
		Pretty(true).
		Do(*es.Ctx)
	if err != nil {
		log.Info("Error performing Elastic Search")
		return nil, err
	}
```

_Originally posted by @claudioontheweb in https://github.com/olivere/elastic/issues/1025#issuecomment-642639662_

**Comment by olivere** [comment]
It's hard to debug without a reproducible test case. E.g. in the example above, I have no idea what the mapping of your index looks like. Please provide a complete test case, otherwise we'll be digging for hours.

Notice that there is a [unit test for this](https://github.com/olivere/elastic/blob/75ab10f9a5111c2d2050c31448646b594f64b043/highlight_test.go#L139-L212) in the code base, so maybe just change that and send it along.

**Comment by bonjourclaudio** [comment]
This is the mapping of the index that I get through the [Get Mapping API](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-mapping.html):

```json
{
   "tools":{
      "mappings":{
         "tools":{
            "properties":{
               "alias":{
                  "type":"text",
                  "fields":{
                     "keyword":{
                        "type":"keyword",
                        "ignore_above":256
                     }
                  }
               },
               "content":{
                  "type":"text",
                  "fields":{
                     "keyword":{
                        "type":"keyword",
                        "ignore_above":256
                     }
                  }
               },
               "name":{
                  "type":"text",
                  "fields":{
                     "keyword":{
                        "type":"keyword",
                        "ignore_above":256
                     }
                  }
               }
            }
         }
      }
   }
}
```

So my goal is to highlight the search query for the property "content".

I hope this helps.

**Comment by bonjourclaudio** [comment]
I just found the reason. I was looking at the source field instead of the highlight field from the Elastic Search response. My bad!
