### ISSUE TITLE
when to support xpack sql api?

### ISSUE THREAD

**Issue by chenlexing** [olivere/elastic#1348]

**Comment by olivere** [comment]
Some, but not all, of XPack API is already supported. See the `xpack_*.go` files in the repository.

**Comment by olivere** [comment]
Oh, I misread the title. It was about XPack SQL API... I have no plans to support that for now. But PRs are welcome.

**Comment by chenlexing** [comment]
> Oh, I misread the title. It was about XPack SQL API... I have no plans to support that for now. But PRs are welcome.

please support XPack SQL API as soon as you can do，thanks a lot！
