### ISSUE TITLE
Not Support Other Bucket in Filters Aggreagtaion

### ISSUE THREAD

**Issue by idu-2012** [olivere/elastic#1350]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
The other_bucket parameter can be set to add a bucket to the response which will contain all documents that do not match any of the given filters

https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-aggregations-bucket-filters-aggregation.html

**Comment by olivere** [comment]
Sorry for the late response. Interesting. I've never seen that. Will add it in one of the next releases.

Self-reference: 

* [Documentation](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-aggregations-bucket-filters-aggregation.html#other-bucket)
* [Code](https://github.com/elastic/elasticsearch/blob/7.8/server/src/main/java/org/elasticsearch/search/aggregations/bucket/filter/FiltersAggregator.java)
