### ISSUE TITLE
how to get all records ?

### ISSUE THREAD

**Issue by hongliu9527** [olivere/elastic#1352]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)

### Please describe the expected behavior
        res,err := elkClient.Search().Index(HMCollectorIndexName).Query(boolSearch).Sort(order,ascending).Do(context.Background())
	if err != nil{
		logger.Error("get point data failed, code:%d indexName:%s err:%v",code,HMCollectorIndexName,err)
		return nil,err
	}

### Please describe the actual behavior
  I need to get all the mached records, but only get 10 by default, how could I get all the record without using Size()?

**Comment by olivere** [comment]
You can find an [example here](https://github.com/olivere/elastic/blob/release-branch.v7/recipes/scroll/scroll.go).

With `Search`, you only get the hits ordered by some score. With `Scroll`, you get each document. Notice that Elasticsearch is not a database!
