### ISSUE TITLE
NewTermsQuery can not use?

### ISSUE THREAD

**Issue by admanheart** [olivere/elastic#1353]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[X ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
i want to creat a query like this : 
{
    "query": {
        "bool": {
            "filter": {
                "range": {
                    "@timestamp": {
                        "from": "2020-07-02T07:51:16.364095Z",
                        "include_lower": false,
                        "include_upper": true,
                        "to": null
                    }
                }
            },
            "must": [{
                    "term": {
                        "datatype.keyword": "cluster"
                    }
                }, {
                    "terms": {
                        "clusterName.keyword": ["a", "b", "c"]
                    }
                }
            ]
        }
    }
}

so i use a NewTermsQuery func, the values is a string slice ,not always ensure len, so i give this function values like []string{"a","b", "c"}, i want is  "terms": { "clusterName.keyword": ["a", "b", "c"]  },  but i got this "terms": { "clusterName.keyword": [ ["a", "b", "c"] ] } , and the query failed with : [terms] unknown token [END_ARRAY] after [clusterName.keyword], is that ok to use?

**Comment by olivere** [comment]
You probably want something like [this](https://github.com/olivere/elastic/blob/release-branch.v7/search_queries_terms_test.go#L65-L82). HTH.
