### ISSUE TITLE
'NewRangeAggregation()'  can't get buckets

### ISSUE THREAD

**Issue by ryan961** [olivere/elastic#1354]
[ ] elastic.v7 (for Elasticsearch 7.x)

I use 'NewRangeAggregation()' to query.
I got '_agg, found := service.Aggregations.Range("rangeAgg")_'  and _'fmt.Printf("%c",agg)_', the result is '&{map[%!c(string=buckets):[{ " 1 . 5 9 3 9 9 3 6 E 9 - 1 . 5 9 3 9 9 4 2 E 9 " : { " f r o m " : 1 . 5 9 3 9 9 3 6 E 9 , " t o " : 1 . 5 9 3 9 9 4 2 E 9 , " d o c _ c o u n t " : 7 1 , " 1 " : { " v a l u e " : 7 1 } } , " 1 . 5 9 3 9 9 3 6 E 9 - 1 . 5 9 3 9 9 4 8 E 9 " : { " f r o m " : 1 . 5 9 3 9 9 3 6 E 9 , " t o " : 1 . 5 9 3 9 9 4 8 E 9 , " d o c _ c o u n t " : 1 3 8 , " 1 " : { " v a l u e " : 1 3 7 } } , " 1 . 5 9 3 9 9 3 6 E 9 - 1 . 5 9 3 9 9 5 4 E 9 " : { " f r o m " : 1 . 5 9 3 9 9 3 6 E 9 , " t o " : 1 . 5 9 3 9 9 5 4 E 9 , " d o c _ c o u n t " : 1 8 4 , " 1 " : { " v a l u e " : 1 8 3 } } , " 1 . 5 9 3 9 9 3 6 E 9 - 1 . 5 9 3 9 9 6 E 9 " : { " f r o m " : 1 . 5 9 3 9 9 3 6 E 9 , " t o " : 1 . 5 9 3 9 9 6 E 9 , " d o c _ c o u n t " : 2 3 1 , " 1 " : { " v a l u e " : 2 3 0 } } , " 1 . 5 9 3 9 9 3 6 E 9 - 1 . 5 9 3 9 9 6 6 E 9 " : { " f r o m " : 1 . 5 9 3 9 9 3 6 E 9 , " t o " : 1 . 5 9 3 9 9 6 6 E 9 , " d o c _ c o u n t " : 3 1 1 , " 1 " : { " v a l u e " : 3 1 0 } } , " 1 . 5 9 3 9 9 3 6 E 9 - 1 . 5 9 3 9 9 7 2 E 9 " : { " f r o m " : 1 . 5 9 3 9 9 3 6 E 9 , " t o " : 1 . 5 9 3 9 9 7 2 E 9 , " d o c _ c o u n t " : 3 9 2 , " 1 " : { " v a l u e " : 3 9 1 } } , " 1 . 5 9 3 9 9 3 6 E 9 - 1 . 5 9 3 9 9 7 8 E 9 " : { " f r o m " : 1 . 5 9 3 9 9 3 6 E 9 , " t o " : 1 . 5 9 3 9 9 7 8 E 9 , " d o c _ c o u n t " : 4 6 6 , " 1 " : { " v a l u e " : 4 6 5 } } , " 1 . 5 9 3 9 9 3 6 E 9 - 1 . 5 9 3 9 9 8 4 E 9 " : { " f r o m " : 1 . 5 9 3 9 9 3 6 E 9 , " t o " : 1 . 5 9 3 9 9 8 4 E 9 , " d o c _ c o u n t " : 5 2 5 , " 1 " : { " v a l u e " : 5 2 4 } } }]]   [] map[]}% _'_.   
But _'fmt.Println(agg.Buckets)'_  is []. I can't get Buckets from response.

**Comment by olivere** [comment]
You can find examples of extracting aggregations in the tests, e.g. [here](https://github.com/olivere/elastic/blob/release-branch.v7/search_aggs_test.go#L763-L885).
