### ISSUE TITLE
Elasticsearch 5.x  NewCompletionSuggester 返回score 为0 

### ISSUE THREAD

**Issue by linzhenlong** [olivere/elastic#1355]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[*] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
在用 NewCompletionSuggester  发现返回结果得分全部为0
 
### Please describe the actual behavior
源码search.go 中

// SearchSuggestionOption is an option of a SearchSuggestion.
// See https://www.elastic.co/guide/en/elasticsearch/reference/5.6/search-suggesters.html.
type SearchSuggestionOption struct {
	Text         string           `json:"text"`
	Index        string           `json:"_index"`
	Type         string           `json:"_type"`
	Id           string           `json:"_id"`
	Score        float64          `json:"score"`
	Highlighted  string           `json:"highlighted"`
	CollateMatch bool             `json:"collate_match"`
	Freq         int              `json:"freq"` // from TermSuggestion.Option in Java API
	Source       *json.RawMessage `json:"_source"`
}

### Any steps to reproduce the behavior?
Score        float64          `json:"score"`  应该 为   Score        float64          `json:"_score"`

**Comment by olivere** [comment]
Oh well... now also ES 5.x... we had that in 6.x as well. See #747.

**Comment by olivere** [comment]
Here's the fix for ES 6.x: https://github.com/olivere/elastic/pull/747#issuecomment-385431239

**Comment by olivere** [comment]
Fixed in #1364
