### ISSUE TITLE
Incoherent error if basic auth is not provided

### ISSUE THREAD

**Issue by adrianlzt** [olivere/elastic#1357]
### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)

### Please describe the expected behavior
In case of a elasticsearch server with basic auth activated, if we are not providing it, the error should notify this problem.

### Please describe the actual behavior
Currently the error is:
```
health check timeout: no Elasticsearch node available
```

### Any steps to reproduce the behavior?
I am using [skydive](http://skydive.network/) with elasticsearch as the backend.

The elasticsearch server has TLS and authorization via HTTP basic auth.

If I don't configure the basic auth, the error reported id:
```
2020-07-08T10:01:49.846+0200    ERROR   elasticsearch/client.go:426 (*Client).Start     archer: Elasticsearch not available: health check timeout: no Elasticsearch node available
```

That error is generated when calling ``elastic.NewClient()``

The HEAD call to elasticsearch return a ``401 Unauthorized``

**Comment by olivere** [comment]
Thanks for reporting. Could it be that the actual error is not because HTTP Basic Auth failed (it's actually [in the code](https://github.com/olivere/elastic/blob/81e9b9e88dcb5e23cebadf7262130f9c60b0b175/client.go#L1162-L1164)), but due to a context timeout when checking health at startup? That would mean the error is correct in that the timeout came before the 401.

**Comment by adrianlzt** [comment]
Using http and sniffing traffic with wireshask:

Skydive (elasticsearch client) logs:
```
2020-07-09T10:24:06.826+0200    INFO    client/election.go:105 (*MasterElector).start   archer: starting as the master for /master-analyzer-es-graph-flush: archer
2020-07-09T10:24:11.839+0200    ERROR   elasticsearch/client.go:448 (*Client).Start     archer: Elasticsearch not available: creating elasticsearch client: health check timeout: no Elasticsearch node available
2020-07-09T10:24:17.855+0200    ERROR   elasticsearch/client.go:448 (*Client).Start     archer: Elasticsearch not available: creating elasticsearch client: health check timeout: no Elasticsearch node available
```

Connections seen by wireshark:
![image](https://user-images.githubusercontent.com/3237784/87016009-6f1fcc00-c1ce-11ea-8dcc-de52fe7264d2.png)

So, looks like there is no timeout.

**Comment by olivere** [comment]
I added a [test](https://github.com/olivere/elastic/commit/100bf4f0f593e1352c5dd96dbab8c0c0cf3f3b44) for that, but cannot reproduce.

**Comment by adrianlzt** [comment]
Script to reproduce the issue (using github.com/olivere/elastic/v7 v7.0.17):

```go
package main

import (
	"fmt"

	elastic "github.com/olivere/elastic/v7"
)

func main() {
	_, err := elastic.NewClient(
		elastic.SetURL("http://127.0.0.1:9200"),
		//elastic.SetBasicAuth("elastic", "elastic"),
	)
	if err != nil {
		panic(fmt.Sprintf("client: %v", err))
	}
}
```

Output:
```
panic: client: health check timeout: no Elasticsearch node available
```

Elastic was started with:
```
docker run -e xpack.security.enabled=true -d --name elastic -p 9200:9200 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.7.0
```

And this command to setup the auth (inside the container):
```
./elasticsearch/bin/x-pack/setup-passwords interactive                                                                                                                                                               
```

**Comment by olivere** [comment]
I see what you're after, and looking into the PR. However, the bug is not reproducible with the above code. You start the with sniffing enabled, so `Client` sniffs the nodes in the cluster, which return a Docker-internal IP, which is not accessible to the host. Hence, you get the error.

Doesn't work:

```
package main

import (
	"fmt"

	elastic "github.com/olivere/elastic/v7"
)

func main() {
	_, err := elastic.NewClient(
		elastic.SetURL("http://127.0.0.1:9200"),
		elastic.SetBasicAuth("elastic", "secret"),
	)
	if err != nil {
		panic(fmt.Sprintf("client: %v", err))
	}
}
```

Does work:

```
package main

import (
	"fmt"

	elastic "github.com/olivere/elastic/v7"
)

func main() {
	_, err := elastic.NewClient(
		elastic.SetURL("http://127.0.0.1:9200"),
		elastic.SetBasicAuth("elastic", "secret"),
		elastic.SetSniff(false),
	)
	if err != nil {
		panic(fmt.Sprintf("client: %v", err))
	}
}
```

So I think Basic Auth is working. Now I'll look into the error reporting.

**Comment by olivere** [comment]
I hope this does the job. If it doesn't, let me know and I'll re-open.

Summary:

```
package main

import (
	"fmt"
	"net/http"

	elastic "github.com/olivere/elastic/v7"
)

func main() {
	_, err := elastic.NewClient(
		elastic.SetURL("http://127.0.0.1:9200"),
		elastic.SetBasicAuth("invalid-user", "invalid-password"),
		elastic.SetSniff(false),
	)
	switch {
	case elastic.IsUnauthorized(err):
		fmt.Printf("unauthorized")
	case elastic.IsStatusCode(err, http.StatusUnauthorized): // works as well
		fmt.Printf("authentication failed")
	case err != nil:
		panic(fmt.Sprintf("client: %v", err))
	}
}
```
