### ISSUE TITLE
Getting Context error from elasticsearch

### ISSUE THREAD

**Issue by amanjain97** [olivere/elastic#1358]
### Which version of Elastic are you using?

[X] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
No `elastic.IsContextErr()` expected.

### Please describe the actual behavior
I have deployed 10 pods and only one of them gives `Context error` from elastic client.
Error log:
`Post http://elasticsearch-client:9200/myindex/_search?request_cache=true: dial tcp: lookup elasticsearch-client: read: connection refused`

Currently, I am using elastic.NewClient() and sniffing is disabled. I want to understand what are the cases that cause context error and how can I debug this. Let me know if you need any other information.

**Comment by olivere** [comment]
This is not an error from the library, but one of the underlying Go runtime. The error indicates that the node failed to connect to a host called `elasticsearch-client` on port `9200`. I have no idea why that happens, but that's the problem.
