### ISSUE TITLE
Sorter of V5, V7 Compatibility problem

### ISSUE THREAD

**Issue by nolan4954** [olivere/elastic#1360]
The error is :
model/ListEs.go:436:45: cannot use sorts (type []"gopkg.in/olivere/elastic.v5".Sorter) as type []"github.com/olivere/elastic/v7".Sorter in argument to es.DefaultSearchService.Query(query).SortBy

why Query of V5, V7 is OK, but Sorter is error ???

**Comment by olivere** [comment]
The sorter from v5 and the sorter from v7 have different types (they come from a different package/module after all). So you can't mix them. Also, v5 and v6 and v7 cannot be mixed, in general. They are different versions of the same library.
