### ISSUE TITLE
MultiSearchTemplate support

### ISSUE THREAD

**Issue by HYY-yu** [olivere/elastic#1361]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[X ] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

Now, We don't have multi search template [https://www.elastic.co/guide/en/elasticsearch/reference/7.0/search-multi-search.html](url). I think it's a very important feature , so may I ask when can we support it ? 

or , can I have other way to deal with it ?

**Comment by olivere** [comment]
Multi Search API is already supported. Please [look at the tests](https://github.com/olivere/elastic/blob/release-branch.v7/msearch_test.go) for usage examples.

**Comment by olivere** [comment]
Re-reading it, you're looking for search templates. Management of search templates is supported through e.g. `PutScript` etc. Executing search templates currently isn't. But you can [use `RawQuery`](https://github.com/olivere/elastic/blob/release-branch.v7/search_queries_raw_string_test.go) so build your own query, as a workaround.
