### ISSUE TITLE
XPack Get Watch API is returning invalid/missing data

### ISSUE THREAD

**Issue by olivere** [olivere/elastic#1362]
The XPack Get Watch API is returning invalid or missing data as layed out in [this PR](https://github.com/olivere/elastic/pull/1345). We need to reflect the library and check for latest changes.

**Comment by phillbaker** [comment]
Thanks @olivere would you mind if I cherry picked https://github.com/olivere/elastic/pull/1363 into a PR for the v6 branch?

**Comment by olivere** [comment]
@phillbaker No, not at all.
