### ISSUE TITLE
Struct for mappings

### ISSUE THREAD

**Issue by fgblomqvist** [olivere/elastic#1370]
### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

For `GetMapping().Do(ctx)` to return a more structured result.

### Please describe the actual behavior

It returns a `map[string]interface{}`.

### Thoughts

It would be nice if it would at least return a partially typed struct. E.g. so that you could easily call `result.Properties` and get a `map[string]interface{}`. Right now the returned data is seemingly the full raw result, meaning that you always have to dig into `mappings` -> `properties`. But maybe there are some weird return formats that I'm missing that doesn't have that structure.

**Comment by olivere** [comment]
Mapping is one of the most dynamic payloads I can think of. Adding a bit of structure to it is probably not really worth it. In our projects, we're currently setting them up as either files that come with the application or even strings added into the binary, using `text/template` or something to dynamically change aspects like number of shards/replicas.

I've extended the [Mapping recipe](https://github.com/olivere/elastic/blob/release-branch.v7/recipes/mapping/mapping.go) to illustrate what I mean. See [these lines](https://github.com/olivere/elastic/blob/release-branch.v7/recipes/mapping/mapping.go#L104-L123).

HTH.

**Comment by olivere** [comment]
Oh, as for Get Mapping API, even ES server only provides generic access to the mappings field, see [here](https://github.com/elastic/elasticsearch/blob/7.8/server/src/main/java/org/elasticsearch/action/admin/indices/mapping/get/GetMappingsResponse.java#L66-L72).

**Comment by olivere** [comment]
And one final one. To make your life easier when working with dynamic JSON structures, [github.com/tidwall/gjson](https://github.com/tidwall/gjson) is very useful.

**Comment by fgblomqvist** [comment]
Hmm I see. Yeah I had a hard time finding info about the structure of mappings, and the way we have it set up it's more "basic". But oh well, thanks!
