### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by rbUUbr** [olivere/elastic#1371]
Hi there! I'm using v7.0.6 of this library, and I found out, that there is a case with nested top hits aggregation, when memory is leaking :(  here is example for reproducing:

```go
func buildTagsAggregationQuery(input, companiesTopHits *Input, connection *ElasticSearchConnection) *elastic.SearchService {
        query := elastic.NewBoolQuery()
	tagsAggregation := elastic.NewNestedAggregation().Path("tags").SubAggregation(
		"tags",
		elastic.NewTermsAggregation().Field("tags.slug").Size(input.First+input.Offset).SubAggregation(
			"users_reverse_nested", elastic.NewReverseNestedAggregation().SubAggregation(
				"users_top_hits",
				elastic.NewTopHitsAggregation().Size(20).From(0))).SubAggregation(
		"bucket_sort", elastic.NewBucketSortAggregation().Size(input.First).From(input.Offset)))
	service := connection.
		Search().
		Index("users").
		Size(0).
		Aggregation("tags", tagsAggregation).
		Query(query)
	return service
}
```
I found out, that there is issue with nesting top hits aggregation, I even removed unpacking of the result, but there is still memory leak in my application

**Comment by rbUUbr** [comment]
as far as I understood, the reason for this issue is that `encoding/json` occupies new memory for each of nested aggregations, because I parsing search result from this aggregation dynamically, wdyt, if I will create struct for this case, should it help? In my understanding, it should help because no additional memory will used to parse `top_hits` nested aggregation and it all will be parsed at once.

**Comment by olivere** [comment]
To be honest, I can't see how the library could leak memory. It's also quite hard to guess what's going on with a small snippet of code. A reproducible test and a description of the method you use to check that is leaks memory would help.

**Comment by rbUUbr** [comment]
@olivere I will provide it! thanks

**Comment by rbUUbr** [comment]
@olivere I found out, that I have not memory leak in this case, but just have a big amount of resources used to unpack json
