### ISSUE TITLE
ScriptSorting based on field value

### ISSUE THREAD

**Issue by lawanya-dwivedi** [olivere/elastic#1372]
How can I achieve the following script sorting in golang?

`{
  "size": 10000, 
  "query": {
    "match_all": {}
  },
  "sort": [{
        "_script": {
            "type": "number",
            "script": {
                "lang": "painless",
                "inline": "if(params.scores.containsKey(doc['genre'].value)) { return params.scores[doc['genre'].value];} return 100000;",
                "params": {
                    "scores": {
                        "Horror": 0,
                        "Comedy": 0,
                        "Romance": 1
                    }
                }
            },
            "order": "asc"
        }
    }]
}` @olivere

**Comment by olivere** [comment]
Unfortunately I don't have the time to solve and test all coding questions sent to me. But please have a look at the tests. There are lots of them, and most of them are also turn out to be good to learn how to use the DSL. As for script sorting, there's e.g. [these tests](https://github.com/olivere/elastic/blob/release-branch.v7/sort_test.go#L206-L238).
