### ISSUE TITLE
Use headers set using `elastic.SetHeaders()` in health check

### ISSUE THREAD

**Issue by NadeemAfana** [olivere/elastic#1374]
### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
The headers set using `elastic.SetHeaders()` should be used in health checks.

### Please describe the actual behavior
The headers set using `elastic.SetHeaders()` are not being used in health checks and thus 401 is returned when the server requires authentication. This happens when the client is not using basic auth but an API key instead.

### Any steps to reproduce the behavior?
Use ES 7 client configured to use an API key. I am getting the following error
```
panic: health check timeout: no Elasticsearch node available
```

**Comment by olivere** [comment]
This was [recently added](https://github.com/olivere/elastic/blob/release-branch.v7/client.go#L1109-L1118). Could you make sure you use 7.0.18? If the issue still persists, comment again and I'll reopen.
