### ISSUE TITLE
supports pagination?

### ISSUE THREAD

**Issue by keets2012** [olivere/elastic#1376]
hi,
    I'm using v5.x, does go-mysql-elasticsearch API supports pagination? I don't find in source code.

`From()`` size()` not works for me.

thx!

**Comment by olivere** [comment]
Elasticsearch has only limited support for "general" pagination. For lack of a better term I describe "general pagination" as the way you can do pagination like SQL, with `limit` and `offset`.

First of all, pagination is very costly, especially if you need sorting. Remember that ES has to get all documents from the nodes, then sort them, then return only a fraction of it to you. Now think what needs to happen if you try to do something like `SELECT * FROM my-index ORDER BY name OFFSET 1_000_000 LIMIT 10`. That'll take a while.

"General" pagination is therefore only supported (by default) for an offset of 10_000. See the [documentation](https://www.elastic.co/guide/en/elasticsearch/guide/current/pagination.html) for details.

You can do pagination in different ways in Elasticsearch. One way is to use the Scroll API ([here's an example](https://github.com/olivere/elastic/blob/release-branch.v7/recipes/scroll/scroll.go)). Scrolling is like a cursor iterating over the index. It is OK, and even better if you don't need sorting. Keep in mind that the cursor expires after a while, so you have to keep scrolling.

Another option you have is to use [`search_after`](https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#search-after). In general, the [documentation for pagination](https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html) is quite good.
