### ISSUE TITLE
Return descriptive error on startup healthcheck error

### ISSUE THREAD

**Issue by fiskeben** [olivere/elastic#1378]
### Which version of Elastic are you using?

[x ] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

Connecting to a cluster with invalid credentials should fail with an error that indicates what the cause of the error is, for example by including the HTTP status code and/or body of the response.

### Please describe the actual behavior

Connecting to a cluster with invalid credentials returns the error `health check timeout: no Elasticsearch node available`.

### Any steps to reproduce the behavior?

Create a client and connect to a cluster that requires valid credentials.

**Comment by olivere** [comment]
May I ask which version you're currently using? I'm asking because in 7.0.19 we've addressed [exactly that](https://github.com/olivere/elastic/commit/42d2a9dc74f943cc1998194d442dff60da13765e), if I see that correctly.

**Comment by fiskeben** [comment]
I was using 7.0.14. Upgrading to 7.0.19 does return a better error message and solve my problem. I did search the issue tracker for similar issues but didn't find any. Apparently I didn't do a good enough job.

Thank you and sorry for the inconvenience.
