### ISSUE TITLE
Wrong Default Tie Breaker When Using Multi Match with Type Bool Prefix

### ISSUE THREAD

**Issue by Haroldov** [olivere/elastic#1379]
# Which version of Elastic are you using?

[X] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
The multi_match query with a bool prefix should default the tie breaker to one

### Please describe the actual behavior
The multi_match query with a bool prefix defaults the tie breaker to zero

### Any steps to reproduce the behavior?
Looking at the code file: search_queries_multi_match.go line: 96 evidence this bug. Check this: 
https://github.com/elastic/elasticsearch/blob/6dd4d2b7a6bd17232c0a93a5a48a4e23327dea81/server/src/main/java/org/elasticsearch/index/query/MultiMatchQueryBuilder.java#L135

**Comment by Haroldov** [comment]
I created an issue because I tried to send a PR but I couldn't since I got permission denied

**Comment by olivere** [comment]
Yes, that seems like a problem. On the other hand, I think we shouldn't even send a tie breaker unless necessary. By doing so, we could circumvent changing defaults in Elasticsearch in the first place.

**Comment by Haroldov** [comment]
I agree with you, unless specified the tie_breaker shouldn't be send within the query DSL
