### ISSUE TITLE
Using Glide to update an error

### ISSUE THREAD

**Issue by laojie** [olivere/elastic#1381]
[ERROR]	Error scanning github.com/olivere/elastic/v7/config: cannot find package "." in:
	/Users/laojie/.glide/cache/src/https-github.com-olivere-elastic/v7/config
[ERROR]	Error scanning github.com/olivere/elastic/v7/uritemplates: cannot find package "." in:
	/Users/laojie/.glide/cache/src/https-github.com-olivere-elastic/v7/uritemplates
[ERROR]	Failed to retrieve a list of dependencies: Error resolving imports

@olivere

**Comment by olivere** [comment]
I'm sorry, but v7 is targeted to using Go modules exclusively. There might be ways around it, like downloading and vendoring the package. I personally haven't used GOPATH-style versioning for years now.

If I find the time I will check for a way to use it with Glide and document it in the Wiki.

**Comment by laojie** [comment]
Thank you for your reply, we do not upgrade to V7 for the time being, we will keep using The V5 version, hope you support Glide

**Comment by olivere** [comment]
The version of Elastic and Elasticsearch are related. If you use Elasticsearch 5.x, you must use elastic v5. Same for v6 and v7. It _might_ work with different versions, but there is no support for it.
