### ISSUE TITLE
Accessing Aggregation result

### ISSUE THREAD

**Issue by jonathanjordy** [olivere/elastic#1385]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ X ] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
I've been doing some project and I found some difficulties in accessing an aggregation result. I'm using `github.com/olivere/elastic/v7` and here's a snip of my code:

        `idQ := elastic.NewTermsQuery("gpid", pIDsInterface...)
	postQ := elastic.NewMatchQuery("a_type", "gift")

	sumAggs := elastic.NewSumAggregation().Field("gift")

	searchQuery = elastic.NewBoolQuery()
	searchQuery = searchQuery.Must(postQ).Filter(idQ)

	countService = esclient.Count().
		Index("uact").
		Query(searchQuery)

	result, err = countService.Do(ctx)
	if err != nil {
		fmt.Println("[CountQueryError]Error= ", err)
	}

	searchService = esclient.Search().
		Index("uact").
		Query(searchQuery).
		Size(int(result)).
		Aggregation("t_gift", sumAggs)

	searchResult, err = searchService.Do(ctx)
	if err != nil {
		fmt.Println("[SearchQueryError]Error= ", err)
	}

	a, found := searchResult.Aggregations.Terms("t_gift")

	fmt.Println(a.Buckets)

	for _, b := range a.Buckets {

		fmt.Println("insideLoop")

	}`

Here's the structure of my ES data:
`
    doc = {
         "a_type" : "gift",
         "gpid" : pid,
         "gift" : gift,
         "created_at" : datetime.datetime.now()
     }
`

I'm hoping to get the result of the aggregation where it sums up all the `gift` from ES.

### Please describe the actual behavior
I receive an empty bucket that made the iteration is not iterated. I got `[ ]` when printing the `a.Buckets`. But I got `true` when printing `found`.

### Any steps to reproduce the behavior?
The code above

Any suggestion? Do you know what I did wrong? 
Thanks in advance!

**Comment by jonathanjordy** [comment]
I've enable the trace log and i got this

`
{
   "took":1,
   "timed_out":false,
   "_shards":{
      "total":1,
      "successful":1,
      "skipped":0,
      "failed":0
   },
   "hits":{
      "total":{
         "value":6,
         "relation":"eq"
      },
      "max_score":1.033473,
      "hits":[
         {
            "_index":"uact",
            "_type":"_doc",
            "_id":"2Om7NHQBsBs4KKv3qdI_",
            "_score":1.033473,
            "_source":{
               "a_type":"gift",
               "gpid":13,
               "gift":71000,
               "created_at":"2020-08-28T18:02:28.671908"
            }
         },
         {
            "_index":"uact",
            "_type":"_doc",
            "_id":"7-noNHQBsBs4KKv39NIZ",
            "_score":1.033473,
            "_source":{
               "a_type":"gift",
               "gpid":83,
               "gift":73000,
               "created_at":"2020-08-28T18:51:56.981762"
            }
         },
         {
            "_index":"uact",
            "_type":"_doc",
            "_id":"8OnoNHQBsBs4KKv39NJT",
            "_score":1.033473,
            "_source":{
               "a_type":"gift",
               "gpid":83,
               "gift":32000,
               "created_at":"2020-08-28T18:51:57.007407"
            }
         },
         {
            "_index":"uact",
            "_type":"_doc",
            "_id":"8unWNXQBsBs4KKv3htK9",
            "_score":1.033473,
            "_source":{
               "a_type":"gift",
               "gpid":63,
               "gift":14000,
               "created_at":"2020-08-29T00:41:24.730419"
            }
         },
         {
            "_index":"uact",
            "_type":"_doc",
            "_id":"8-mVNnQBsBs4KKv3btID",
            "_score":1.033473,
            "_source":{
               "a_type":"gift",
               "gpid":63,
               "gift":61000,
               "created_at":"2020-08-29T08:21:45.264061"
            }
         },
         {
            "_index":"uact",
            "_type":"_doc",
            "_id":"9OmVNnQBsBs4KKv3btJU",
            "_score":1.033473,
            "_source":{
               "a_type":"gift",
               "gpid":63,
               "gift":81000,
               "created_at":"2020-08-29T08:21:45.334152"
            }
         }
      ]
   },
   "aggregations":{
      "t_gift":{
         "value":332000.0
      }
   }
}
`

The data is there, but I don't know how to access it.

**Comment by olivere** [comment]
There is a test illustrating basically all aggregations available in [`search_aggs_test.go`](https://github.com/olivere/elastic/blob/release-branch.v7/search_aggs_test.go).

For your use case, you defined a `SumAggregation` ...

```
sumAggs := elastic.NewSumAggregation().Field("gift")
```

... but tried to extract a `TermsAggregation`:

```
a, found := searchResult.Aggregations.Terms("t_gift")
```

You can access results from `SumAggregations` like so:

```
	// sumRetweets
	{
		agg, found := searchResult.Aggregations.Sum("sumRetweets")
		if !found {
			t.Errorf("expected %v; got: %v", true, found)
		}
		if agg == nil {
			t.Fatalf("expected != nil; got: nil")
		}
		if agg.Value == nil {
			t.Fatalf("expected != nil; got: %v", *agg.Value)
		}
		if *agg.Value != 120.0 {
			t.Errorf("expected %v; got: %v", 120.0, *agg.Value)
		}
	}
```

**Comment by jonathanjordy** [comment]
> 
> 
> There is a test illustrating basically all aggregations available in [`search_aggs_test.go`](https://github.com/olivere/elastic/blob/release-branch.v7/search_aggs_test.go).
> 
> For your use case, you defined a `SumAggregation` ...
> 
> ```
> sumAggs := elastic.NewSumAggregation().Field("gift")
> ```
> 
> ... but tried to extract a `TermsAggregation`:
> 
> ```
> a, found := searchResult.Aggregations.Terms("t_gift")
> ```
> 
> You can access results from `SumAggregations` like so:
> 
> ```
> 	// sumRetweets
> 	{
> 		agg, found := searchResult.Aggregations.Sum("sumRetweets")
> 		if !found {
> 			t.Errorf("expected %v; got: %v", true, found)
> 		}
> 		if agg == nil {
> 			t.Fatalf("expected != nil; got: nil")
> 		}
> 		if agg.Value == nil {
> 			t.Fatalf("expected != nil; got: %v", *agg.Value)
> 		}
> 		if *agg.Value != 120.0 {
> 			t.Errorf("expected %v; got: %v", 120.0, *agg.Value)
> 		}
> 	}
> ```

Thank you for your reply. it works!!!
