### ISSUE TITLE
Unable to retry HTTP 504 Status Code (Gateway Timeout)

### ISSUE THREAD

**Issue by aymkhalil** [olivere/elastic#1387]
### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[X] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
Elastic retrier would not kick in if the client received an HTTP 504  (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/504) from a cluster behind a load balancer (Like AWS Elasticsearch).

### Please describe the actual behavior
504 are not retired. The reason is, isContextError() are not considered for retrying https://github.com/olivere/elastic/blob/release-branch.v6/client.go#L1368. If you look at the isContextError() implementation: https://github.com/olivere/elastic/blob/release-branch.v6/errors.go#L102, it categorized Temporary url.error as context error although they are not. In fact, Temporary indicate a transient issue that could be fixed retrying - in my case the context was not being cancelled nor the deadline was exceeded.

I noticed the same implementation of isContextError() exists in the 7.x branch. 

* Is there a reason why Temporary errors are not considered for retry? Any harm in doing so maybe other folks encountered?
* Even if the library prefers not retrying those, would it be possible for the library client to override this behavior? It is nice that we have full control of the how the retrier behaves, but not being able to control when it kicks in sounds limiting - especially if someone implements their retrier logic like:

```go
func (r *DefaultRetrier) Retry(ctx context.Context, retry int, req *http.Request, resp *http.Response, err error)(time.Duration, bool error) {
    isRetriableHttpStatus := resp.StatusCode >= 500 
    maxRetriesReached := retry >= r.numMaxRetries
    shouldRetry := !maxRetriesReached && isRetriableHttpStatus

  if shouldRetry {
    wait, goahead := r.backoff.Next(retry)
    return wait, goahead, nil
  }

  return 0, false, nill
}
```

it gives the impression that StatusCode should be retired, but it is not.

### Any steps to reproduce the behavior?
I tried reproducing using https://golang.org/pkg/net/http/httptest/ but the 504 returned are not url.Error so the Temporary effect doesn't happen. I'm only able to see this in production logs with AWS Elasticsearch

What would be your recommendation to achieve the desired behavior?

Thanks!,
Ayman

**Comment by olivere** [comment]
I will need more time to look into this in full depth.

**Comment by nullren** [comment]
@olivere i came to file a similar issue as this.

in `client.go` after the request is made, [only if there is an error in the http client is the retry executed](https://github.com/olivere/elastic/blob/release-branch.v7/client.go#L1384-L1437). a non-erroring http client signals a successful http request and response, but [does not necessary represent a successful response](https://play.golang.org/p/DxKq5cyqVmf) from the http server.

 i think this library should allow for clients to specify status codes to retry on and possibly default to retrying on 502, 503, and 504 (common status codes people retry on).

[here is an example](https://github.com/elastic/go-elasticsearch/blob/master/estransport/estransport.go#L307-L315) of where `go-elasticsearch` retries based on status.

**Comment by olivere** [comment]
Still haven't found the time to look into this, I'm sorry. I only have limited experience with AWS ES service, and the few cases where I did, AWS ES behaved very strange. I will have to review this in detail, starting a real AWS ES cluster etc.

@nullren Retries should be possible using a combination of a [custom `http.Transport`](https://github.com/olivere/elastic/wiki/HttpTransport) and/or [retrier](https://github.com/olivere/elastic/wiki/Retrier-and-Backoff). But I agree: There should an out-of-the-box solution for using AWS ES clusters with elastic.

**Comment by olivere** [comment]
@nullren Thanks for the details. I see what you're after, and it probably isn't AWS-related in any way.

**Comment by olivere** [comment]
@nullren Care to review #1410?

**Comment by elireisman** [comment]
👋 @nullren is out for a bit but I 👀 this and it looks great, thanks again for the fast turnaround 🙇
