### ISSUE TITLE
Service for creating new-style component and index templates in v7.8

### ISSUE THREAD

**Issue by lobocv** [olivere/elastic#1388]
Hi, first of all thank you for this package, it is so much nicer to use than the official client. Amazing work.

~~I noticed that there seems to be no way to add a component template?~~
~~There is a service for adding an index template though.~~ 

### Which version of Elastic are you using?

[X] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
Ability to create a index and component templates in v7.8 clusters. See new template docs for v7.8:
https://www.elastic.co/guide/en/elasticsearch/reference/7.8/index-templates.html

### Please describe the actual behavior
Component / Index template service does not exist

**Comment by lobocv** [comment]
Sorry, I just realized that component templates are new in v7.8 and AWS only supports up to v7.7. So looks like I won't be using component templates after all (darn).
Feel free to close this issue or leave it open since it would be a nice feature to add eventually.

**Comment by olivere** [comment]
Looks similar to #1393, so I will close this.

**Comment by olivere** [comment]
New index template APIs should be done with #1393. Component template APIs are #1414.
