### ISSUE TITLE
Consecutive calls to update by query fails from second call

### ISSUE THREAD

**Issue by priyankamang** [olivere/elastic#1392]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
I'm trying to call UpdateByQuery more than once using the same client. All calls to UpdateByQuery should actually update documents in ElasticSearch which happens if I use a rest-API

### Please describe the actual behavior
The first call successfully updates the index but from the second onwards I get success but the document is not actually updated.

### Any steps to reproduce the behavior?
Create an index and query with _id and any other field and try to update another field in the index.

**Comment by olivere** [comment]
We're using it every day, in many many calls. Can you post code to reproduce? Did you [refresh](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update-by-query.html#_refreshing_shards_2)?

**Comment by priyankamang** [comment]
`ubqs := elastic.NewUpdateByQueryService(s.Client)
	ubqs.Index(s.GetIndex())
	ubqs.Query(bQuery)
	ubqs.Script(script)
	ubqs.Conflicts("proceed")
	ubqs.ErrorTrace(true)
	ubqs.RequestsPerSecond(-1)
	ubqs.WaitForCompletion(true)
	ubqs.ProceedOnVersionConflict()
	bsresp, err := ubqs.Do(ctx)
	if err != nil {
		s.log.Errorf("error running update by query: %v\n", err)
	}
	s.log.Infof("Bulk scroll Resp: %+v", bsresp)`

This is how I'm updating.

Do we have to refresh after every single update?

**Comment by priyankamang** [comment]
Thanks. I'm refreshing using refresh option with in  elastic.NewUpdateByQueryService.
