### ISSUE TITLE
inner hit should support second level of collapsing

### ISSUE THREAD

**Issue by KaitoHH** [olivere/elastic#1394]
### Which version of Elastic are you using?
elastic.v7 (for Elasticsearch 7.x)

### Please describe the expected behavior
According to [this doc](https://www.elastic.co/guide/en/elasticsearch/reference/7.9/collapse-search-results.html), second level of collapsing is supported by specifying `collapse` field inside `inner_hits`. However, it seems there is no `Collapse(collapse *CollapseBuilder)` method inside `InnerHit`. How should I specify the second level of collapsing?

```jsonc
GET /my-index-000001/_search
{
  "query": {
    "match": {
      "message": "GET /search"
    }
  },
  "collapse": {
    "field": "geo.country_name",
    "inner_hits": {
      "name": "by_location",
      "collapse": { "field": "user.id" },  // this line
      "size": 3
    }
  }
}
```

### Please describe the actual behavior
Maybe add the `Collapse(collapse *CollapseBuilder)` method inside `InnerHit` struct?

**Comment by remithomasn7** [comment]
The second level of collapsing is a great feature. I am interested to know when you'll have time to add it @olivere.
Thanks again for all your work here.

**Comment by olivere** [comment]
Yes, sorry for the delay. It's been hard recently to keep up with my obligations at work and maintaining this library. It's on the list for the next release.
