### ISSUE TITLE
How to convert Boolean query string into es.Query

### ISSUE THREAD

**Issue by xiaosun1995** [olivere/elastic#1395]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)

### Please describe the expected behavior

Hi guys i was trying to parse a boolean query string, like: `(('A'[field_1]) AND ('B'[field_2]))  OR (('C'[field_1]) AND ('D'[field_2]))`

Is there has a parser which can directly convert this query string into es.BoolQuery()?
Or any advice about how to do it?

**Comment by olivere** [comment]
No, there is no such parser. This library simply passed on your data to ES as is. QueryStringQuery is complex and error-prone, [`SimpleQueryStringQuery`](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html) is more forgiving—maybe that's good enough for your use case. In all but the very simplest of use cases I see people building their own query though.
