### ISSUE TITLE
Delete document in wiki is still using deprecated Type()

### ISSUE THREAD

**Issue by rizkiyoist** [olivere/elastic#1396]
I'm trying to learn how to use this, but stumbled upon a problem:

### Which version of Elastic are you using?
elastic.v7 (for Elasticsearch 7.x)

### Please describe the expected behavior
The example for delete document is still using Type() which is deprecated.
https://github.com/olivere/elastic/wiki/Delete
And since it is deprecated, what is the equivalent code for delete document?

### Please describe the actual behavior
Delete document is using Type()

### Any steps to reproduce the behavior?
https://github.com/olivere/elastic/wiki/Delete

**Comment by olivere** [comment]
Yes, and that document is still valid for ES 6.x and earlier. I've added a notice for ES 7.x and later.
