### ISSUE TITLE
Error running example code

### ISSUE THREAD

**Issue by jay-khatri** [olivere/elastic#1397]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

Hi there! I'm using the example code [here](https://olivere.github.io/elastic/) to set up a basic elastic search client and I'm getting the error: 
```
2020/09/26 16:50:29 error creating index: elastic: Error 400 (Bad Request): Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [tweet : {properties={image={type=keyword}, created={type=date}, location={type=geo_point}, message={fielddata=true, store=true, type=text}, user={type=keyword}, suggest_field={type=completion}, tags={type=keyword}}}] [type=mapper_parsing_exception]
```

Could this be an error related to the elastic version? I'm using the most up-to-date:
```
Version: 7.9.2, Build: default/tar/d34da0ea4a966c4e49417f2da2f244e3e97b4e6e/2020-09-23T00:45:33.626720Z, JVM: 15
```

And for reference, the code I'm running is here:
https://gist.github.com/jay-khatri/928c4a02aef061c8ac6299b6feb9f3d3

**Comment by jay-khatri** [comment]
Ahh, seems like it has to do with ES7 compatibility?
https://stackoverflow.com/questions/55699623/elasticsearch-7-root-mapping-definition-has-unsupported-parameters-mapper-par

I'm good now, sorry to bother 😅. Should the example be updated?

**Comment by olivere** [comment]
ES 7 deprecated types, and they will be gone with ES 8.

The [example for v7](https://github.com/olivere/elastic/blob/release-branch.v7/recipes/mapping/mapping.go) doesn't have types any more, so I don't know which example you're referring to?
