### ISSUE TITLE
Steps to troubleshoot no Elasticsearch node available

### ISSUE THREAD

**Issue by Russiancold** [olivere/elastic#1399]
### Which version of Elastic are you using?

[x ] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
Create client

### Please describe the actual behavior
Getting error health check timeout: no Elasticsearch node available

I'm creating a client with tls and basic auth:
```
client, err := elastic.NewClient(
		elastic.SetSniff(config.GetBool("mailmetaindexopts.sniff")),
		elastic.SetURL(url),
		elastic.SetHealthcheckInterval(config.GetDuration("mailmetaindexopts.healthcheckinterval")),
		elastic.SetHttpClient(&http.Client{
			Transport:     &http.Transport{
				TLSClientConfig:        tlsCfg,
			},
			Timeout:       config.GetDuration("mailmetaindexopts.timeout"),
		}),
		elastic.SetBasicAuth(config.GetString("mailmetaindexopts.user"), config.GetString("mailmetaindexopts.pass")),
	)
```

**Comment by Russiancold** [comment]
Sniff is disabled.

**Comment by olivere** [comment]
Can you also disable health checks, please? [Here's](https://github.com/olivere/elastic/wiki/Connection-Problems#how-to-figure-out-connection-problems) a very old (but still correct) description of why this might happen.
