### ISSUE TITLE
Ids Search not working well

### ISSUE THREAD

**Issue by tommoholmes** [olivere/elastic#140]
Hai, how to run run ids query. I run with curl like this
``
curl -XPOST "http://localhost:9200/test/_search?pretty" -d '{"filter":{ "query": {"ids":{ "values": [ "search" ] } } } }'
``
and I get result, but when I try with 
```go
        q := elastic.NewIdsQuery("filter").Ids(message)
        builder := client.Search().Index("witch").Query(q).Size(21)
        searchResult, err := builder.Do()
```
my result zero

**Comment by olivere** [comment]
There are many ways to query for IDs. If you have one ID, you can use [`TermQuery`](https://github.com/olivere/elastic/blob/master/search_queries_term_test.go#L12). If you have many, you can use [`TermsQuery`](https://github.com/olivere/elastic/blob/master/search_queries_terms_test.go#L26). Of course, you can also use [`IdsQuery`](https://github.com/olivere/elastic/blob/master/search_queries_terms_test.go#L26). If there is any problem with them, please send a reproducible example.
