### ISSUE TITLE
Can't figure out how to translate kibana request into equivalent...

### ISSUE THREAD

**Issue by vynjo** [olivere/elastic#1402]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

I can't figure out how to reproduce a kibana visualization (copied the request into Dev Tools): 
```json
POST /my_index/_search
{
  "aggs": {
    "2": {
      "date_range": {
        "field": "checked_at",
        "ranges": [
          {
            "from": "now-7d/d",
            "to": "now-6d/d"
          }
        ]
      }
    }
  },
  "size": 0,
  "query": {
    "bool": {
      "filter": [
        {
          "match_all": {}
        }
      ]
    }
  }
}
```
I've tried 
`q := elastic.NewBoolQuery()`
`q = q.Must(elastic.NewRangeQuery("eschecked_at").From("now-7d/d").To("now-6d/d").TimeZone("UTC"))`

And a bunch of other combinations, but I can't figure out how to get both the aggs and bool. I know I've missing something simple - any guidance would be greatly appreciated.

Awesome, awesome repo. All your work is so appreciated.

**Comment by olivere** [comment]
You're using a query, not an aggregation.

It should be something like:

```
q := elastic.NewBoolQuery().Filter(elastic.NewMatchAllQuery()).
  Aggregation("2", elastic.NewDateRangeAggregation().Field("checked_at").Range(...))
```

Please see [`search_aggs_test.go`](https://github.com/olivere/elastic/blob/release-branch.v7/search_aggs_test.go) for example code on most of the supported aggregations.

**Comment by vynjo** [comment]
Thank you, very much.
