### ISSUE TITLE
Does the code support async search now?

### ISSUE THREAD

**Issue by cocodee** [olivere/elastic#1404]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[X] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
support async search

**Comment by olivere** [comment]
No, it doesn't yet.

**Comment by olivere** [comment]
Self-reference: https://www.elastic.co/guide/en/elasticsearch/reference/7.9/async-search.html

**Comment by olivere** [comment]
It will be part of 7.0.22. You can find an example of using it in [this test](https://github.com/olivere/elastic/blob/release-branch.v7/xpack_async_search_test.go).

**Comment by cocodee** [comment]
> It will be part of 7.0.22. You can find an example of using it in [this test](https://github.com/olivere/elastic/blob/release-branch.v7/xpack_async_search_test.go).

Thank you very much
