### ISSUE TITLE
Why is there no place to set the client after it's created

### ISSUE THREAD

**Issue by pibigstar** [olivere/elastic#1405]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

i want to use  elastic.NewClientFromConfig to create client, then set the httpClient for add trace, but i found that not have  a place to change it，please help me, thanks！

**Comment by olivere** [comment]
Elastic uses a sort of Builder pattern, i.e. you configure the client and then it's read-only. If you'd be able to change settings between requests, the client would need to be prepared for changes at any time, making it much more complicated.

Why do you want to change the HTTP client in between requests? If you still need this behaviour, you could still build it into the custom HTTP client, and make Elastic simply use the "sometimes changing" HTTP client.

To add a trace log with `NewClientFromConfig`, you can use the [`TraceLog` setting](https://github.com/olivere/elastic/blob/release-branch.v7/config/config.go#L26). If you want to use instrumentation/tracing, you could do that e.g. in a [custom HTTP transport](https://github.com/olivere/elastic/wiki/HttpTransport), and toggle its behaviour there.
