### ISSUE TITLE
DNS cache and re-try

### ISSUE THREAD

**Issue by dipakrp** [olivere/elastic#1406]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
Connection should be reset in case of DNS IP change. 

### Please describe the actual behavior
Some times we see continuous timeouts for 10 minutes, and then it fixes by itself after DNS TTL expires. Is it possible to detect DNS IP change, re-create the connection & retry the request?

**Comment by olivere** [comment]
It's out of scope for an ES client library to handle DNS issues. I think there is a Go issue related to that (can't find it now). And I'm pretty sure you can somehow build it into a custom `http.Transport`, or even replace the `net.DefaultResolver` with one that does what you want it to do.
