### ISSUE TITLE
ClearScrollService.Do() method getting stuck

### ISSUE THREAD

**Issue by Gautam04** [olivere/elastic#1407]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[x] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
Ideally the scroll should get cleared successfully.

### Please describe the actual behavior
Based on log messages added in the program it was discovered that the ClearScrollService.Do() was getting stuck and control did not return from this function call.

### Any steps to reproduce the behavior?
This problem does not occur during every run, but it occurs frequently. The following code is being used:

```Golang

       esClient = elastic.NewClient(elastic.SetURL(url), elastic.SetMaxRetries(3), elastic.SetSniff(false), elastic.SetHealthcheck(requireHealthCheck), elastic.SetBasicAuth(username, password))
	scrollId := ""
	scroller := esClient.Scroll(Index).Size(100)

	if Type != "" {
		scroller = scroller.Type(Type)
	}

	if SortField != "" {
		scroller = scroller.Sort(SortField, !DescSort)
	}

	if Query != nil {
		kind := reflect.ValueOf(Query).Kind()
		var queryString string
		switch kind {
		case reflect.String:
			queryString = Query.(string)
		case reflect.Map:
			b, _ := json.Marshal(Query)
			queryString = string(b)
		}

		query := elastic.RawStringQuery(queryString)
		scroller = scroller.Scroll("15m").Query(query)
	}

	for {
		var results *elastic.SearchResult
		var esErr error


		if scrollId != "" {
			scroller = scroller.ScrollId(scrollId)
		}
		results, esErr = scroller.Do(context.Background())


		if esErr != nil {
			if esErr == io.EOF {
				break
			} else {
				return esErr
			}
		}

		scrollId = results.ScrollId

		for _, hit := range results.Hits.Hits {
			//process the hits
		}
	}
	esClient.ClearScroll(scrollId).Do(context.Background())
	return nil

```

Terminating and restarting the program usually solves the problem, but need to find the root cause of why it happens.

**Comment by olivere** [comment]
I'm sorry, I can't reproduce. I used [this program and it worked fine](https://play.golang.org/p/uaUcs93i9l7):

```
$ ./scroll2 -index=warehouse -size=100
resp = &{Succeeded:true NumFreed:1}
```

It looks like you sometimes try to clear the scroll with an empty `scrollId` in the end. That is not necessary if the scrolling is complete. You also don't capture possible errors there, so maybe ES will give you a hint.

We don't clear scroll operations at all, even in production. It's never been a problem, and we have a big cluster with many scroll operations. But your mileage may vary.

Notice there is a [recipe for using Scroll API](https://github.com/olivere/elastic/blob/9c681f12c6/recipes/scroll/scroll.go) that maybe of help.

HTH
