### ISSUE TITLE
Clarification on compression confusing AWS Elasticsearch

### ISSUE THREAD

**Issue by nisargap** [olivere/elastic#1408]
Using es6 i ran into this issue using the official go-elasticsearch client as well and in my http RoundTripper I had to do `DisableCompression: true` in order for AWS ES to work properly during blue green deploys when old nodes are deleted and traffic is transitioned over to new nodes. 

To fix my issue with the official client integrating with AWS I also added retries on timeouts. It was peculiar that I only saw this issue during b/g deploys (total ops/sec dropped to 0 for an extended period of time). I'm wondering why this might be the case

**Comment by nisargap** [comment]
cc: @olivere

**Comment by nisargap** [comment]
As additional context im using ES 6.8

**Comment by olivere** [comment]
I'm pretty sure this doesn't have anything to do with compression. I guess it's the same reason why other people complain about AWS ES service. See e.g. #1387 and other issues regarding AWS ES. I'm closing this issue in favour of the other open issues regarding AES.
