### ISSUE TITLE
Connection seems to connect to 127.0.0.1 instead of proper URL:

### ISSUE THREAD

**Issue by ShawnMilo** [olivere/elastic#141]
Although I specify a non-localhost server, the library seems to ignore it and try to connect to localhost anyway.

The code works when I actually have an Elasticsearch instance listening on `localhost:9200`. Also possibly relevant: If I use a Docker container running the official Elasticsearch image, and forward local port 9200 to the Docker port 9200, everything is fine. But if I forward another port, say 10200 to the Docker port 9200, it also fails.

Code:

```go
// connectToElasticsearch sets the global es variable to an Elasticsearch connection.
func connectToElasticsearch() {
        var err error
        esURL := os.Getenv("HAYSTACK_URL")
    log.Println("esURL: ", esURL)
        es, err = elastic.NewClient(elastic.SetURL(esURL))
        if err != nil {
                log.Fatalf("Unable to connect to Elasticsearch at URL %s: %s\n", esURL, err)
        }
        _, _, err = es.Ping().Do()
        if err != nil {
                log.Fatal("Unable to ping Elasticsearch: ", err)
        }
        index = os.Getenv("HAYSTACK_INDEX")
        if index == "" {
                index = "haystack"
        }
}
```

Output:

```sh
2015/10/04 17:12:52 esURL:  http://172.17.0.60:9200
2015/10/04 17:12:52 Unable to ping Elasticsearch: Get http://127.0.0.1:9200/: dial tcp 127.0.0.1:9200: getsockopt: connection refused
Command exited with non-zero status 1
```

**Comment by olivere** [comment]
Please set the URL when using the Ping service. The Ping service is special in that, by default, it uses 127.0.0.1:9200. Search the issues and/or the wiki for an explanation (on my iPhone, sorry).

**Comment by ShawnMilo** [comment]
Yeah, sorry -- I found out that this is a dupe of #86.

I was having two different problems and got them confused. First it was failing to connect (not ping). It turns out that the environment variable was missing the `http://` prefix, adding that fixed it. However, after adding the `http://`, I saw it was still getting an error and failed to notice that it was a different problem.

Thanks!
