### ISSUE TITLE
Suggestion: a err in code need to handle

### ISSUE THREAD

**Issue by NewHongjayGitHub** [olivere/elastic#1411]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?
 elastic.v7 (for Elasticsearch 7.x)

 in file search.go ,line 693,  following code
`if err := json.Unmarshal(hit.Source, v.Addr().Interface()); err == nil {
			slice = append(slice, v.Interface())
}`

when err is not nil, i think its better to give a hint or return the err to the caller.
if there is something i missed, forgive me!

**Comment by olivere** [comment]
One could do that, yes. But the `Each` method is a helper method, and it'll lose most of its value as a shortcut if you add the `error` as a 2nd return parameter. If you really want to capture the case of an error, feel free to deserialize yourself.

Also notice that `Each` has the following warning in the documentation:

```go
// Notice that Each will ignore errors in
// serializing JSON and hits with empty/nil _source will get an empty
// value.
```

**Comment by NewHongjayGitHub** [comment]
> One could do that, yes. But the `Each` method is a helper method, and it'll lose most of its value as a shortcut if you add the `error` as a 2nd return parameter. If you really want to capture the case of an error, feel free to deserialize yourself.
> 
> Also notice that `Each` has the following warning in the documentation:
> 
> ```go
> // Notice that Each will ignore errors in
> // serializing JSON and hits with empty/nil _source will get an empty
> // value.
> ```
thx for your reply, i almost got it, when return err as 2nd ，other records can be parsed correctly that behind this err parsed record  will lose.
In my case, a record parsing error，others records have the same error，so `Each`  method rerurn nil, but i dont know why.   then i check the `Each` method code, deserialize records by myself， find the err.  Its my code bug.   
Anyway i agree with ur design of `Each` method, i learn a lot from it. thx again !
