### ISSUE TITLE
How can I fetch source fields that I want to returen when I use NewMultiMatchQuery to search？

### ISSUE THREAD

**Issue by YoungWing** [olivere/elastic#1412]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
I want to the "title" field be returned, I can pass "_source", like following:
GET /products/test/_search
{
  "_source": ["title"],
  "query" : {
      "multi_match": {
      "query":       "test",
      "type":        "cross_fields", 
      "operator": "and", 
      "fields":      [ "title", "desc"]
      }
    },
    "from":0,
    "size":20
}

But how should I do like this when I use NewMultiMatchQuery to search？

thx

**Comment by YoungWing** [comment]
PS：I use elastic.v7.

**Comment by olivere** [comment]
You can find [an example of using `FetchSource` here](https://github.com/olivere/elastic/blob/9c681f12c6d53fe41ae9d91b86926bb7d5c3f81c/search_source_test.go#L84-L101). It's not dependent on the type of query. You can use `FetchSource` at various places, e.g. when defining a `SearchSource`, or by [passing it directly into Search API](https://github.com/olivere/elastic/blob/9c681f12c6/search.go#L215-L226) via a [`FetchSourceContext`](https://github.com/olivere/elastic/blob/9c681f12c6/fetch_source_context.go). 

HTH
