### ISSUE TITLE
Client.Ping() created with default URL

### ISSUE THREAD

**Issue by notzippy** [olivere/elastic#142]
Just starting with your API, was wondering why the NewPingService(Client) returns a ping service with the default (127.0.0.0) URL ? Would it not be useful to set it with the first URL specified in the client (if available) ?

**Comment by notzippy** [comment]
NVM Client.Ping().URL() does the trick...

**Comment by olivere** [comment]
Just FYI: I have [edited the Wiki page for Ping](https://github.com/olivere/elastic/wiki/Ping) to describe why `Ping` works the way it does.

**Comment by notzippy** [comment]
:+1:
