### ISSUE TITLE
Add SQL REST API

### ISSUE THREAD

**Issue by olivere** [olivere/elastic#1421]
See https://www.elastic.co/guide/en/elasticsearch/reference/7.9/sql-rest.html

**Comment by dai-pch** [comment]
hi, i'm wondering when will this feature ready?

**Comment by yf393136248** [comment]
HI, @olivere , Is this feature ready now?

**Comment by olivere** [comment]
Hi @yf393136248, no it's not. And it very probably never will be part of Elastic. As described in #1533, this repository is going into maintenance mode and I strongly suggest everyone updating to the [official Go client](https://github.com/elastic/go-elasticsearch), which is now in a state that I can recommend. And it already has [support for running SQL queries](https://github.com/elastic/go-elasticsearch/blob/main/esapi/api.xpack.sql.query.go).
