### ISSUE TITLE
How do I implement this query

### ISSUE THREAD

**Issue by ruanlianjun** [olivere/elastic#1431]
### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)

### Any steps to reproduce the behavior?
```
GET /attractions/restaurant/_search
{
  "query": {
    "filtered": {
      "filter": {
        "geo_distance_range": {
          "gte":    "1km", 
          "lt":     "2km", 
          "location": {
            "lat":  40.715,
            "lon": -73.988
          }
        }
      }
    }
  }
}
```

**Comment by olivere** [comment]
There are hundreds of tests in the project that you illustrate how to use the builders. E.g. for `geo_distance_range` we have [these tests](https://github.com/olivere/elastic/blob/release-branch.v7/search_aggs_bucket_geo_distance_test.go).

Feel free to dig around to see examples for filtered queries etc.
