### ISSUE TITLE
Add Point in Time API functionality

### ISSUE THREAD

**Issue by Ryan3435** [olivere/elastic#1433]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[X] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
 Elasticsearch seems to recommend moving away from the Scroll API for deep pagination and recommends using the `search_after` parameter combined with a point in time (PIT) for preserving index state as seen here https://www.elastic.co/guide/en/elasticsearch/reference/current/scroll-api.html

The point in time API is a newer feature that doesn't seem to be implemented in this package yet but has been implemented in the Java API https://github.com/elastic/elasticsearch/pull/61062

The rest APIs for opening and closing PITs can be found here:
https://github.com/elastic/elasticsearch-net/blob/7.10/src/ApiGenerator/RestSpecification/XPack/close_point_in_time.json
https://github.com/elastic/elasticsearch-net/blob/7.10/src/ApiGenerator/RestSpecification/XPack/open_point_in_time.json

and the reference for the Point in Time API is here https://www.elastic.co/guide/en/elasticsearch/reference/current/point-in-time-api.html

I would like to get a jump on moving my code over to using this method rather than scrolling if this is the new recommendation. If you are accepting of pull requests I can work on adding this functionality.

### Please describe the actual behavior
Doesn't seem to be implemented yet.

### Any steps to reproduce the behavior?
N/A

**Comment by olivere** [comment]
Initial support will be added to 7.0.24.
