### ISSUE TITLE
Raw aggregate query

### ISSUE THREAD

**Issue by notzippy** [olivere/elastic#144]
For user input I created a new aggregate called JSonAggregate, simply converts a passed in string to an interface. I don't know if you would even need / want it, (if you did I can do a PR if you like) but the code is pretty simplistic

	type JSonAggregate struct {
		AggInterface interface{}
	}
	
	func (s *JSonAggregate) Source() (i interface{}) {
		return s.AggInterface
	}
	func NewJsonAggregate(source string) (aggInterface elastic.Aggregation) {
		var interfaceData interface{}
		if e:= json.Unmarshal([]byte(source),&interfaceData);e!=nil {
			panic( e)
		} else {
			aggInterface = &JSonAggregate{AggInterface:interfaceData}
		}
		return
	}

**Comment by olivere** [comment]
Can you write an example of what you use it for and how to use it? Maybe I don't quite understand.

**Comment by notzippy** [comment]
In my case I wanted to allow the user to enter in the aggregation in a free form textarea input field on a web page , so lets say they entered in

    { 
        "min_price" : { "min" : { "field" : "price" } }
    }

Assuming textinput is a string populated with the above

	search, err := Client.Search("*").
		Aggregation("user_aggs", NewJsonAggregate(textinput)).
                Size(200).
                do()

**Comment by olivere** [comment]
I see. Hmm... I don't have a strong desire to include this into core elastic as it's rather advanced. You also need to handle the results accordingly based on what the user entered in the query as aggregation results are very different based on the user's input. But it's perfectly okay for you to use it like that!

Thanks for your suggestion.
