### ISSUE TITLE
add support for create in bulk requests

### ISSUE THREAD

**Issue by visheyra** [olivere/elastic#1445]
When using this driver it's not possible to bulk create request.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[*] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

Bulk create request are not supported by this driver while elasticsearch supports it.

### Please describe the actual behavior

There is no BulkCreate request of the type BulkableRequest (only create delete and index)

### Any steps to reproduce the behavior?

Not relevant

**Comment by olivere** [comment]
You could as well use `NewBulkIndexRequest(...).OpType("create")`, but I will add a `BulkCreateRequest` in 7.0.24 as well.
