### ISSUE TITLE
Missing option to set size on Reindex Source

### ISSUE THREAD

**Issue by mimol91** [olivere/elastic#1446]
ES allows to set size on reindex source
```
POST _reindex
{
  "source": {
    "index": "source",
    "size": 100
  },
  "dest": {
    "index": "dest"
  }
}
```
It seems that this option is not added in library.

**Comment by olivere** [comment]
The Reindex API is actually implemented in terms of the Java API. The `size` parameter comes from the `SearchRequest` (see Java code [here](https://github.com/elastic/elasticsearch/blob/v7.12.0/server/src/main/java/org/elasticsearch/index/reindex/ReindexRequest.java#L315)). That `getSearchRequest` actually returns a [`SearchRequest`](https://github.com/elastic/elasticsearch/blob/v7.12.0/server/src/main/java/org/elasticsearch/action/search/SearchRequest.java), which has the `Size` parameter and is mirrored by [`SearchRequest`](https://github.com/olivere/elastic/blob/9eedc113c1/search_request.go) in the Go code (which also has the [`Size`](https://github.com/olivere/elastic/blob/9eedc113c109559b6305d0d2e0b2c3719c2c3758/search_request.go#L198-L202) parameter).

So you can achieve the same by passing the size through [`ReindexSource.Request(...)`](https://github.com/olivere/elastic/blob/9eedc113c1/search_request.go).
