### ISSUE TITLE
include_type_name is not supported in elastic v7.0.22

### ISSUE THREAD

**Issue by elmir-b** [olivere/elastic#1448]
### Which version of Elastic are you using?

[x ] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
According to https://www.elastic.co/guide/en/elasticsearch/reference/7.0/indices-create-index.html 

Before 7.0.0, the mappings definition used to include a type name. Although specifying types in requests is now deprecated, a type can still be provided if the request parameter include_type_name is set.

### Please describe the actual behavior
In version 7.0.22 include_type_name is not supported. It is deprecated, but I think it makes sense to keep it supported as long as it is supported in the elasticsearch 

### Any steps to reproduce the behavior?
Check https://github.com/olivere/elastic/blob/release-branch.v7/indices_create.go - parameter is not supported

Is there any particular reason for this?

**Comment by elmir-b** [comment]
not supported in es v7

**Comment by phillbaker** [comment]
@olivere would you accept a PR to port 85d05c9f48e5101b51ce553928c4d11c2098e9a1 to the v7 branch so that it can be used for backward compatibility?

**Comment by olivere** [comment]
@phillbaker We _could_ add `include_type_name` but there is no `update_all_types` in the [Put Mapping API for 7.x](https://github.com/elastic/elasticsearch/blob/v7.14.0/rest-api-spec/src/main/resources/rest-api-spec/api/indices.put_mapping.json). So if we add the latter, we break the client.

Of course, one could add the given methods as a no-op, but that's unfortunate: If we start doing that we'd need to keep them around forever, and the API surface is big enough already for my mind.

**Comment by phillbaker** [comment]
Whoops, you're quite right @olivere, what would you think about limiting the scope to just `include_type_name`?

**Comment by olivere** [comment]
@phillbaker Yes, `include_type_name` would be OK. I'll fix that in a minute (already working on elastic as we chat). It's wrong anyway, as [it currently _has_ `update_all_types`](https://github.com/olivere/elastic/blob/release-branch.v7/indices_put_mapping.go#L36). Oh my.

**Comment by olivere** [comment]
@phillbaker Will release 7.0.28 today. That version will include the fix.

**Comment by phillbaker** [comment]
Fantastic, thanks so much @olivere!

**Comment by okhowang** [comment]
`include_type_name` is lack in `GetFieldMapping` too.
