### ISSUE TITLE
Request parameter timeout for raw source search

### ISSUE THREAD

**Issue by koiek12** [olivere/elastic#1452]
In my use case of the library, I want to have query parameter timeout because I have to call search API only with raw source(Source func instead of SearchSource). But the library only support timeout for SearchSource usage. 

### Which version of Elastic are you using?

[ v ] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
Currently, query parameter level timeout in Search API(https://www.elastic.co/guide/en/elasticsearch/reference/7.10/search-search.html#search-search-api-query-params) is not supported by the library. TimeoutInMillis and Timeout func of SearchService only set internal searchSource's timeout like this
```
func (s *SearchService) Timeout(timeout string) *SearchService {
	s.searchSource = s.searchSource.Timeout(timeout)
	return s
}

func (s *SearchService) TimeoutInMillis(timeoutInMillis int) *SearchService {
	s.searchSource = s.searchSource.TimeoutInMillis(timeoutInMillis)
	return s
}
```

### Please describe the actual behavior
Can it be supported by the library?

**Comment by olivere** [comment]
Both [`Timeout`](https://github.com/olivere/elastic/blob/release-branch.v7/search.go#L135-L139) and [`TimeoutInMillis`](https://github.com/olivere/elastic/blob/release-branch.v7/search.go#L155-L159) are there. Am I missing something?
