### ISSUE TITLE
Delete with multiple field condition

### ISSUE THREAD

**Issue by ghost** [olivere/elastic#1455]
1. Clean records based on multiple fields.

```go
	// Delete all documents by sandrae
	q := elastic.NewTermQuery("user", "sandrae")
	res, err := es.DeleteByQuery().Index(PageIndexName).Query(q).Pretty(true).Do(context.TODO())
	if err != nil {
		return err
	}
```

How to attach other conditions, a user belongs to `city :'Alaska'`?

2. I am expecting bulk Delete API to perform the same operation
```json
[{
   "user":"peter", "interest": ["photography", "swimming"]
}, 
{
   "user":"sandra", "interest": ["marshal-arts"]
} ]
```
Again multiple fields but for bulk operations. Any references or wiki could be helpful

**Comment by olivere** [comment]
All types of queries can be passed into `DeleteByQuery`, so you can achieve what you want by e.g. a [`BoolQuery`](https://github.com/olivere/elastic/blob/release-branch.v7/search_queries_bool_test.go).
