### ISSUE TITLE
Search is failing with `json: cannot unmarshal object into Go struct field SearchHits.total of type int64.`

### ISSUE THREAD

**Issue by batrasaurabh90** [olivere/elastic#1457]
Search is failing with `json: cannot unmarshal object into Go struct field SearchHits.total of type int64.`

### Which version of Elastic are you using?

- [x] elastic.v7 (for Elasticsearch 7.x)
- [ ] elastic.v6 (for Elasticsearch 6.x)
- [ ] elastic.v5 (for Elasticsearch 5.x)
- [ ] elastic.v3 (for Elasticsearch 2.x)
- [ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
Search should work properly.

### Please describe the actual behavior
Search is failing with `json: cannot unmarshal object into Go struct field SearchHits.total of type int64.`

### Any steps to reproduce the behavior?
Use elastic.v7 (7.0.22) with elasticsearch7 and run search from function
```
func searchAffectedServicesfromESWithSizeLimit(resourceID *string, sizeLimit int64) (result *elastic.SearchResult, err error) {
	ctx := context.Background()
	var getServices elastic.FetchSourceContext
	getServices.SetFetchSource(true)
	getServices.Include(dbconsts.Id_Field_Name)
	getServices.Include(dbconsts.InventoryInfo_Field_Name)
	searchResults, err := esClient.Get().Search(dbconsts.ActiveRelatedInventoryIndex.String()).
		Type(dbconsts.InventoryrelationshipType.String()).Size(int(sizeLimit)).
		Query(elastic.NewNestedQuery("childrenIds",
		elastic.NewTermsQuery("childrenIds.id", *resourceID))).FetchSourceContext(&getServices).Do(ctx)
	if err != nil {
		// log it
	}
	return searchResults, nil
}
```

**Comment by alexshtin** [comment]
Are you sure you are running ES7? I saw this when used `elastic.v7` client with ES6.

**Comment by batrasaurabh90** [comment]
Yes, I am sure that I am using ES7. 
And if I understand correctly, SearchHits.total is changed to object in ES7. Right?

**Comment by vikumar-ciena** [comment]
@alexshtin  is right .

**Comment by olivere** [comment]
ES7 changed the way total hits are returned (see [breaking changes](https://www.elastic.co/guide/en/elasticsearch/reference/7.12/breaking-changes-7.0.html#hits-total-now-object-search-response)). You can revert back to the old behaviour by specifying `rest_total_hits_as_int=true` to the query (see [docs](rest_total_hits_as_int)), but you'd be better off to use the ES7 defaults.
