### ISSUE TITLE
Ping Service does not utilize passed client's set elastic URL

### ISSUE THREAD

**Issue by spiritedsnowcat** [olivere/elastic#1460]
### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

When creating a new `elastic.PingService` through `elastic.NewPingService`, the `elastic.Client` argument should be utilized to set the URL of the ping service.

### Please describe the actual behavior

When creating a new `elastic.PingService` through `elastic.NewPingService`, the URL set for the `elastic.Client` is ignored and it will instead ping the default URL (`http://127.0.0.1:9200`). 

https://github.com/olivere/elastic/blob/be977d75416e9a352a0853165c9d1786e3d43c51/ping.go#L57

### Any steps to reproduce the behavior?

```
client, _ := elastic.NewClient(
        elastic.SetURL(elasticURL),
        elastic.SetSniff(false),
        elastic.SetHealthcheck(false))
    
pingService := elastic.NewPingService(client)
_, _, err := pingService.Do(context.Background())
fmt.Println(err)
```

**Comment by zhaoyunxing92** [comment]
I've seen that ping requires manual `URL` setting

```go
func (s *PingService) URL(url string) *PingService {
	s.url = url
	return s
}
```

Complete example

```go
	client, err := elastic.NewClient(
		elastic.SetURL("http://a.b.c.d:9200"),
		elastic.SetHealthcheckTimeoutStartup(10*time.Second),
		elastic.SetSniff(false))
	if err != nil {
		panic(err)
	}
	service := elastic.NewPingService(client)
	service.URL("http://a.b.c.d:9200")
	// Ping the Elasticsearch server to get e.g. the version number
	info, code, err := service.Do(context.Background())
	if err != nil {
		// Handle error
		panic(err)
	}
	fmt.Print(info, code)
```

But you can call it directly,I don't think the right way to do it is directly to `elastic.NewPingService(client)`, @olivere Consider making it private
```go
	client, err := elastic.NewClient(
		elastic.SetURL("http://a.b.c.d:9200"),
		elastic.SetHealthcheckTimeoutStartup(10*time.Second),
		elastic.SetSniff(false))
	if err != nil {
		panic(err)
	}
	info, code, err := client.Ping("http://a.b.c.d:9200").Do(context.Background())
	if err != nil {
		// Handle error
		panic(err)
	}
	fmt.Print(info, code)
```

**Comment by olivere** [comment]
Yes, that's true and by design. The Ping API asks for the actual URL to ping for. That's because the connection to an Elasticsearch cluster could e.g. take not one URL but (if sniffing is disabled) many. So which URL would the Ping API then choose to ping. So by design, you need to pass the URL to ping for to the Ping API.
