### ISSUE TITLE
Error 400 (Bad Request): all shards failed [type=search_phase_execution_exception]

### ISSUE THREAD

**Issue by agolebiowska** [olivere/elastic#1463]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[X] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
All my queries works the same way.

### Please describe the actual behavior
Hi, I have a big amount of `Error 400 (Bad Request): all shards failed [type=search_phase_execution_exception]` errors in multiple services. When I am reproducing this issue locally I can get this same error by making a mistake in a query, but in production some of my queries works and the rest gives this error. I don't see anything relevant in ES logs, how can I know what is wrong with my query? Do you have more ideas on how to debug this?

This is my code: 

`func (es *Client) IsItemIDExists(ctx context.Context, ID string, alias string) (bool, error) {`
	`query := elastic.NewTermQuery("_id", ID)`
	`res, err := es.client.Search().Index(alias).Type(typeDoc).Query(query).Do(ctx)`
	`if err != nil {`
		`return false, errors.New(fmt.Sprintf("ERROR: %v", err.Error()))`
	`}`
	`return res.TotalHits() > 0, nil`
`}`

### Any steps to reproduce the behavior?
Running the function to query data.

**Comment by olivere** [comment]
The best way to debug this kind of things is to [enable the trace log](https://github.com/olivere/elastic/wiki/Logging) to see what's actually been sent over to ES, and what ES returns and complains about.
