### ISSUE TITLE
Elastic.co, AWS OpenDistro, and Olivere

### ISSUE THREAD

**Issue by cjcjameson** [olivere/elastic#1466]
Where do folks stand amid the upcoming changes to the Elastic.co license, and expansion of [AWS's Open Distro](https://opendistro.github.io/for-elasticsearch/) ?

Beyond Elastic.co v7.10 (after the license changes) , can and will `olivere/elastic` continue to work with new versions?

What if olivere/elastic became part of the AWS OpenDistro umbrella? Would that give this repo more love and resources for keeping it maintained? Or would that add headache?

**Comment by cjcjameson** [comment]
Related to #1240

**Comment by cjcjameson** [comment]
https://discuss.opendistrocommunity.dev/t/golang-client-libraries-olivere-elastic-elastic-go-elasticsearch/5174/3?u=cjcjameson

**Comment by olivere** [comment]
Hi C.J. My personal view on this is that this library should benefit the community. To best serve the community, my goals for this library are 1) to be stable, 2) to limit the amount of breaking changes during minor versions, and 3) work on as many Elasticsearch versions and distros as possible.

My take on the future of this library is written down in #1240. I'd like to apologize for currently not being very active in working on this library. Day-time work related issues are more important to me right now. I see quite a number of very useful contributions in the form of PRs, but on the other hand I've not seen too many things that actively prevent people from using the library. Having said that, I really hope to pour in some days and work on the queue of PRs and issues that's already there, and even add some more stuff that I have on my list.

**Comment by cjcjameson** [comment]
Awesome! I like the vision, and good to know that the corporate machinations aren't really shaking you. And major props for this repo overall, it's a shining example I like telling my friends about.
