### ISSUE TITLE
in golang, float64, eg:11.0，bulk to es ,i get long type, but i want float type

### ISSUE THREAD

**Issue by likeweilikewei** [olivere/elastic#1467]
### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)

### Please describe the expected behavior
in golang, float64, eg:11.0，bulk to es ,i get long type, but i want float type

labels := make(map[string]interface{})
labels["test"] = 1.0
elastic.NewBulkUpdateRequest().Id(u.Uid).DocAsUpsert(true).Doc(labels)

at last, in labels, i get map[test:1] ,so in es, its type is long, not float。
how can i get float type in es whitout set es type.

**Comment by olivere** [comment]
That's a general ES issue, not one specific to the Go driver.

It depends on two factors:

1. If you didn't specify a mapping, then ES will automatically try to figure out the datatype for the unknown field at the time the field is first written. If you supply 1.0, it will probably figure that that's an integer.
2. JSON doesn't have an integer type, so all numeric data coming back from parsing JSON in Go that end up in a field of type `interface{}` will become a `float64` by default, even integers. There are several ways to work around these issues, but that's beyond the scope of this issue.

**Comment by likeweilikewei** [comment]
> That's a general ES issue, not one specific to the Go driver.
> 
> It depends on two factors:
> 
>     1. If you didn't specify a mapping, then ES will automatically try to figure out the datatype for the unknown field at the time the field is first written. If you supply 1.0, it will probably figure that that's an integer.
> 
>     2. JSON doesn't have an integer type, so all numeric data coming back from parsing JSON in Go that end up in a field of type `interface{}` will become a `float64` by default, even integers. There are several ways to work around these issues, but that's beyond the scope of this issue.

Thank you very much to help me first.
I did a test: 

POST /test_index/_bulk
{ "update" : {"_id" : "1"} }
{ "doc" : {       "test" :1.0},"doc_as_upsert": true }

in ES type:

        "test" : {
          "type" : "float"
        }

So, ES can detect float whit .0，i found in that, interface{} will delete the .0， so ES do not know it is a float type。so i wonder if the go driver can find it is a float type, even it look without .0

	labels := make(map[string]interface{})
	labels["test"] = 1.0

**Comment by olivere** [comment]
This library uses the JSON serialiser from the Go standard library, so there is nothing we can do if that decides to serialise 1.0 as 1 in the payload.

**Comment by likeweilikewei** [comment]
> This library uses the JSON serialiser from the Go standard library, so there is nothing we can do if that decides to serialise 1.0 as 1 in the payload.

I understanded, happ to received your reply, thanks
