### ISSUE TITLE
Why is msearch query created from *SearchRequest Source and not Query?

### ISSUE THREAD

**Issue by ssardana96** [olivere/elastic#1468]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x ] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
msearch should be created from *SearchRequest Query and not *Source

**Comment by olivere** [comment]
Please return an actual failing test case so that I can review. The msearch API was very probably implemented by looking at the original Java source code from Elasticsearch. So there's very probably a good reason that things are like they are, although it's been years since I added it.
