### ISSUE TITLE
fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by xiaochao** [olivere/elastic#1479]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ *] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
 goroutine 38 [running]:
 31 runtime.throw(0xb9188c, 0x26)
 30   /usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc00036b868 sp=0xc00036b838 pc=0x437772
 29 runtime.mapiternext(0xc0012ec4e0)
 28   /usr/local/go/src/runtime/map.go:853 +0x554 fp=0xc00036b8e8 sp=0xc00036b868 pc=0x412514
 27 runtime.mapiterinit(0xaaf1a0, 0xc000729b90, 0xc0012ec4e0)
 26   /usr/local/go/src/runtime/map.go:843 +0x1c5 fp=0xc00036b908 sp=0xc00036b8e8 pc=0x411ec5
 25 reflect.mapiterinit(0xaaf1a0, 0xc000729b90, 0x0)
 24   /usr/local/go/src/runtime/map.go:1331 +0x54 fp=0xc00036b938 sp=0xc00036b908 pc=0x466a94
 23 reflect.Value.MapKeys(0xaaf1a0, 0xc000e174e0, 0x95, 0x0, 0x0, 0x0)
 22   /usr/local/go/src/reflect/value.go:1215 +0xc7 fp=0xc00036b9c8 sp=0xc00036b938 pc=0x4c90e7
 21 encoding/json.mapEncoder.encode(0xba4270, 0xc00058a100, 0xaaf1a0, 0xc000e174e0, 0x95, 0x100)
 20   /usr/local/go/src/encoding/json/encode.go:785 +0xff fp=0xc00036bb40 sp=0xc00036b9c8 pc=0x66637f
 19 encoding/json.mapEncoder.encode-fm(0xc00058a100, 0xaaf1a0, 0xc000e174e0, 0x95, 0x100)
 18   /usr/local/go/src/encoding/json/encode.go:777 +0x65 fp=0xc00036bb80 sp=0xc00036bb40 pc=0x6720a5
 17 encoding/json.structEncoder.encode(0xc000226900, 0x3, 0x4, 0xc000294f30, 0xc00058a100, 0xaf49e0, 0xc000e174d0, 0x99, 0xaf0100)
 16   /usr/local/go/src/encoding/json/encode.go:759 +0x2ab fp=0xc00036bc18 sp=0xc00036bb80 pc=0x66602b
 15 encoding/json.structEncoder.encode-fm(0xc00058a100, 0xaf49e0, 0xc000e174d0, 0x99, 0xff0100)
 14   /usr/local/go/src/encoding/json/encode.go:730 +0x7f fp=0xc00036bc70 sp=0xc00036bc18 pc=0x67201f
 13 encoding/json.(*encodeState).reflectValue(0xc00058a100, 0xaf49e0, 0xc000e174d0, 0x99, 0xc000360100)
 12   /usr/local/go/src/encoding/json/encode.go:358 +0x82 fp=0xc00036bca8 sp=0xc00036bc70 pc=0x663722
 11 encoding/json.(*encodeState).marshal(0xc00058a100, 0xaf49e0, 0xc000e174d0, 0x100, 0x0, 0x0)
 10   /usr/local/go/src/encoding/json/encode.go:330 +0xf4 fp=0xc00036bd08 sp=0xc00036bca8 pc=0x663314
  9 encoding/json.Marshal(0xaf49e0, 0xc000e174d0, 0x30, 0xc000123500, 0x30, 0x0, 0x0)
  8   /usr/local/go/src/encoding/json/encode.go:161 +0x52 fp=0xc00036bd80 sp=0xc00036bd08 pc=0x662952
  7 github.com/olivere/elastic/v7.(*BulkIndexRequest).Source(0xc00007f260, 0xc00036bee0, 0x2, 0x0, 0x1, 0x1)
  6   /home/xxx/golang/pkg/mod/github.com/olivere/elastic/v7@v7.0.23/bulk_index_request.go:240 +0x39a fp=0xc00036be68 sp=0xc00036bd80 pc=0x7ddd3a
  5 github.com/olivere/elastic/v7.(*bulkWorker).work(0xc000296d00, 0xc34fc0, 0xc000124000)
  4   /home/xxx/golang/pkg/mod/github.com/olivere/elastic/v7@v7.0.23/bulk_processor.go:484 +0x46b fp=0xc00036bfc8 sp=0xc00036be68 pc=0x7e138b
  3 runtime.goexit()
  2   /usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00036bfd0 sp=0xc00036bfc8 pc=0x46cc01
  1 created by github.com/olivere/elastic/v7.(*BulkProcessor).Start
  0   /home/xxx/golang/pkg/mod/github.com/olivere/elastic/v7@v7.0.23/bulk_processor.go:336 +0x1ce

**Comment by olivere** [comment]
It seems like the `map` you're passing on to the library is being modified concurrently somewhere inside your library. Make sure to pass a copy of the map, or protect the map accordingly.

**Comment by xiaochao** [comment]
I read data from channel. All code shows below:
![image](https://user-images.githubusercontent.com/1953662/114504078-d9373700-9c60-11eb-9efa-d9d306592212.png)
![image](https://user-images.githubusercontent.com/1953662/114504033-cc1a4800-9c60-11eb-9910-9fce21e42597.png)

**Comment by olivere** [comment]
That's the consumer side. Can you also post the code on the provider side?

You can also simplify the code to a `for range` loop, like:

```go
for data := range esChan {
  ...
}
```

Make sure that your code will even run if the bulk processor yields an error when started. In the above snippet, you simply log the error, but continue anyway.

I wouldn't expect a big performance gain when using a bulk processor like above. I suppose you're starting that `InsertThread` as a goroutine, when the `BulkProcessor` itself is already a bunch of goroutines.

I've posted a few recipes on working with [bulk processor](https://github.com/olivere/elastic/blob/release-branch.v7/recipes/bulk_processor/main.go) and (if you need more control) the [Bulk API in general](https://github.com/olivere/elastic/blob/release-branch.v7/recipes/bulk_insert/bulk_insert.go) that you might find valuable.

**Comment by xiaochao** [comment]
the producer code:
![image](https://user-images.githubusercontent.com/1953662/114527783-f2e57800-9c7a-11eb-83c8-d38a498bf34f.png)
![image](https://user-images.githubusercontent.com/1953662/114527896-0f81b000-9c7b-11eb-9f68-11f4dd20f5b1.png)
