### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by nashasha1** [olivere/elastic#148]
It seems when insert lots of data at the same time. it will crash.
error info:

`oroutine 76 [running]:
runtime.panic(0x9cc620, 0xfbc893)
	/usr/src/go/src/pkg/runtime/panic.c:279 +0xf5
gopkg.in/olivere/elastic%2ev2.(*Client).PerformRequest(0x0, 0xa61140, 0x4, 0xc2082cee70, 0x6, 0xc20809fc50, 0x889a80, 0xc2082cee80, 0x0, 0x0, ...)
	/home/ubuntu/src/github.com/google/cadvisor/Godeps/_workspace/src/gopkg.in/olivere/elastic.v2/client.go:819 +0xd76
gopkg.in/olivere/elastic%2ev2.(*BulkService).Do(0xc208343ec0, 0xc208103600, 0x0, 0x0)
	/home/ubuntu/src/github.com/google/cadvisor/Godeps/_workspace/src/gopkg.in/olivere/elastic.v2/bulk.go:142 +0xa40
github.com/google/cadvisor/storage/es.(*ESStorage).WriteToElasticSearch(0xc20813c100, 0xc2080386c0, 0x3a, 0x48, 0x0, 0x0)`

**Comment by nashasha1** [comment]
Sorry. My bad. It is ok!~

**Comment by olivere** [comment]
So can we close this then?

**Comment by nashasha1** [comment]
Yes。 sorry again！
