### ISSUE TITLE
Question: Will this package support OpenSearch or Elasticsearch or both?

### ISSUE THREAD

**Issue by dylannz-sailthru** [olivere/elastic#1481]
For those that are unaware, there's been a bit of 'contention' around Elasticsearch's license lately which has lead to Amazon creating a fork of Elasticsearch 7.10 called OpenSearch:

https://aws.amazon.com/blogs/opensource/introducing-opensearch/

Given the code paths may diverge at some point, is the intention of this package to support Elasticsearch, OpenSearch, or both? Or will we cross that bridge when we come to it?

This is a great library that I've been using personally for a number of years without any issues whatsoever. Looking for a productive discussion about the future direction of this code. Please do let me know if there is a better venue for such a discussion, I am not trying to start a holy war.

Thanks :)

**Comment by olivere** [comment]
Hi Dylan! I replied to a similar question [here](https://github.com/olivere/elastic/issues/1466#issuecomment-788692439). Maybe that already answers your question?

> ... My personal view on this is that this library should benefit the community. To best serve the community, my goals for this library are 1) to be stable, 2) to limit the amount of breaking changes during minor versions, and 3) work on as many Elasticsearch versions and distros as possible.
> 
> My take on the future of this library is written down in #1240. I'd like to apologize for currently not being very active in working on this library. Day-time work related issues are more important to me right now. I see quite a number of very useful contributions in the form of PRs, but on the other hand I've not seen too many things that actively prevent people from using the library. Having said that, I really hope to pour in some days and work on the queue of PRs and issues that's already there, and even add some more stuff that I have on my list.
