### ISSUE TITLE
NewClient return error

### ISSUE THREAD

**Issue by Pluto-yubin** [olivere/elastic#1483]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[√ ] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
Connecting to es server successfully and when searching the document, it will return a correct value 

### Please describe the actual behavior
 When connecting to elasticsearch server, it will return a error, 
![image](https://user-images.githubusercontent.com/53851524/115407223-6dd20400-a222-11eb-923c-a73937a2c53d.png)
but after I set
![image](https://user-images.githubusercontent.com/53851524/115407622-c4d7d900-a222-11eb-83c8-6c21f2a47655.png)
to false,  I can connect to it, after that , when I want to search something, I get a 411 error when I try to search a document from es

### Any steps to reproduce the behavior?
I don't know, maybe it's the problem of environment, this server is deploy in the cloud server of my company, when I use local elasticsearch, everything is fine. But it's all right when using go-elasticsearch

**Comment by olivere** [comment]
Honestly, this is the first time I've ever seen HTTP Status 411 mentioned in a bug report. I even had to look it up :-) 

Not sure what's going on there. Can you run requests against the ES server with `curl` or Postman?

**Comment by Pluto-yubin** [comment]
> Honestly, this is the first time I've ever seen HTTP Status 411 mentioned in a bug report. I even had to look it up :-)
> 
> Not sure what's going on there. Can you run requests against the ES server with `curl` or Postman?

It's all right in Postman, like this
![image](https://user-images.githubusercontent.com/53851524/115502035-dd89d280-a2a6-11eb-940e-65a12c4e12e8.png)
but as you can see below
![image](https://user-images.githubusercontent.com/53851524/115502195-17f36f80-a2a7-11eb-9978-6c16c32925df.png)
it will return a 411 error
The most strange thing is when I connect to my local es server, it goes well

**Comment by olivere** [comment]
That 411 is due to a missing `Content-Length` in the HTTP request. That IIRC happens by default in the Go HTTP client because it uses [chunked transfer encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding) by default, which omits the `Content-Length`.

Do you have a proxy between the Go client and the ES instances that requires you to have a `Content-Length` in the HTTP header? Because ES doesn't require that, hence it works on your machine.

You might be able to work around this by creating a custom `http.Client` and passing it to Elastic via `SetHttpClient(...)`. The custom `http.Client` needs to set a HTTP header of `Transfer-Encoding: identity`, if I [read this correct](https://golang.org/pkg/net/http/#Request.Write).

**Comment by Pluto-yubin** [comment]
> That 411 is due to a missing `Content-Length` in the HTTP request. That IIRC happens by default in the Go HTTP client because it uses [chunked transfer encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding) by default, which omits the `Content-Length`.
> 
> Do you have a proxy between the Go client and the ES instances that requires you to have a `Content-Length` in the HTTP header? Because ES doesn't require that, hence it works on your machine.
> 
> You might be able to work around this by creating a custom `http.Client` and passing it to Elastic via `SetHttpClient(...)`. The custom `http.Client` needs to set a HTTP header of `Transfer-Encoding: identity`, if I [read this correct](https://golang.org/pkg/net/http/#Request.Write).

No, it doesn't work,  I  inherite the `http.Client` and overwrite the method like that
![image](https://user-images.githubusercontent.com/53851524/115690631-d12d7480-a38f-11eb-9c55-0199878314d4.png)

![image](https://user-images.githubusercontent.com/53851524/115690337-89a6e880-a38f-11eb-8c91-3aacb200d123.png)
but I still get a 411 error, what confused me is in postman, I don't need content-length
![image](https://user-images.githubusercontent.com/53851524/115690821-00dc7c80-a390-11eb-979d-f6c9d868fcf2.png)
It's a get request...
I don't know why in my golang code it will return a 411 error...

**Comment by olivere** [comment]
I'm confused about your `httpClient`. I don't think Elastic is using it, to be honest. [Here's how to use your own custom HTTP Transport with Elastic](https://github.com/olivere/elastic/wiki/HttpTransport).

**Comment by olivere** [comment]
From what I see from the screenshots, it doesn't seem to work even without Elastic. So does [something like this](https://play.golang.org/p/O9hQEIjUV-G) work at all?

```go
package main

import (
	"fmt"
	"log"
	"net/http"
	"net/http/httputil"
	"strings"
)

func main() {
	body := strings.NewReader(`{"query":{"match_all":{}}}`)
	req, _ := http.NewRequest("GET", "http://localhost:9200/_search?pretty=true", body)
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Transfer-Encoding", "identity")
	buf, _ := httputil.DumpRequestOut(req, true)
	fmt.Println(string(buf))
	res, err := http.DefaultClient.Do(req)
	if err != nil {
		log.Fatal(err)
	}
	defer res.Body.Close()
	buf, _ = httputil.DumpResponse(res, true)
	fmt.Println(string(buf))
}
```

This will successfully return here. If you can get this to work against your production cluster, we know what happens:

```sh
$ go run main.go
GET /_search?pretty=true HTTP/1.1
Host: localhost:9200
User-Agent: Go-http-client/1.1
Content-Length: 26
Content-Type: application/json
Accept-Encoding: gzip

{"query":{"match_all":{}}}

HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8

{
  "took" : 0,
  "timed_out" : false,
  "_shards" : {
    "total" : 0,
    "successful" : 0,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : 0.0,
    "hits" : [ ]
  }
}
```

**Comment by Pluto-yubin** [comment]
> From what I see from the screenshots, it doesn't seem to work even without Elastic. So does [something like this](https://play.golang.org/p/O9hQEIjUV-G) work at all?
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 	"log"
> 	"net/http"
> 	"net/http/httputil"
> 	"strings"
> )
> 
> func main() {
> 	body := strings.NewReader(`{"query":{"match_all":{}}}`)
> 	req, _ := http.NewRequest("GET", "http://localhost:9200/_search?pretty=true", body)
> 	req.Header.Set("Content-Type", "application/json")
> 	req.Header.Set("Transfer-Encoding", "identity")
> 	buf, _ := httputil.DumpRequestOut(req, true)
> 	fmt.Println(string(buf))
> 	res, err := http.DefaultClient.Do(req)
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 	defer res.Body.Close()
> 	buf, _ = httputil.DumpResponse(res, true)
> 	fmt.Println(string(buf))
> }
> ```
> 
> This will successfully return here. If you can get this to work against your production cluster, we know what happens:
> 
> ```shell
> $ go run main.go
> GET /_search?pretty=true HTTP/1.1
> Host: localhost:9200
> User-Agent: Go-http-client/1.1
> Content-Length: 26
> Content-Type: application/json
> Accept-Encoding: gzip
> 
> {"query":{"match_all":{}}}
> 
> HTTP/1.1 200 OK
> Content-Type: application/json; charset=UTF-8
> 
> {
>   "took" : 0,
>   "timed_out" : false,
>   "_shards" : {
>     "total" : 0,
>     "successful" : 0,
>     "skipped" : 0,
>     "failed" : 0
>   },
>   "hits" : {
>     "total" : {
>       "value" : 0,
>       "relation" : "eq"
>     },
>     "max_score" : 0.0,
>     "hits" : [ ]
>   }
> }
> ```

![image](https://user-images.githubusercontent.com/53851524/115708735-f2e42700-a3a2-11eb-93a1-8041e7723397.png)
it's still 411 error

**Comment by Pluto-yubin** [comment]
> I'm confused about your `httpClient`. I don't think Elastic is using it, to be honest. [Here's how to use your own custom HTTP Transport with Elastic](https://github.com/olivere/elastic/wiki/HttpTransport).

I saw the method like yours in https://developer20.com/add-header-to-every-request-in-go/
but this passage say like below
![image](https://user-images.githubusercontent.com/53851524/115708873-1c04b780-a3a3-11eb-9479-67e699d019d8.png)

**Comment by olivere** [comment]
> > From what I see from the screenshots, it doesn't seem to work even without Elastic. So does [something like this](https://play.golang.org/p/O9hQEIjUV-G) work at all?
> > ```go
> > package main
> > 
> > import (
> > 	"fmt"
> > 	"log"
> > 	"net/http"
> > 	"net/http/httputil"
> > 	"strings"
> > )
> > 
> > func main() {
> > 	body := strings.NewReader(`{"query":{"match_all":{}}}`)
> > 	req, _ := http.NewRequest("GET", "http://localhost:9200/_search?pretty=true", body)
> > 	req.Header.Set("Content-Type", "application/json")
> > 	req.Header.Set("Transfer-Encoding", "identity")
> > 	buf, _ := httputil.DumpRequestOut(req, true)
> > 	fmt.Println(string(buf))
> > 	res, err := http.DefaultClient.Do(req)
> > 	if err != nil {
> > 		log.Fatal(err)
> > 	}
> > 	defer res.Body.Close()
> > 	buf, _ = httputil.DumpResponse(res, true)
> > 	fmt.Println(string(buf))
> > }
> > ```
> > 
> > 
> > This will successfully return here. If you can get this to work against your production cluster, we know what happens:
> > ```shell
> > $ go run main.go
> > GET /_search?pretty=true HTTP/1.1
> > Host: localhost:9200
> > User-Agent: Go-http-client/1.1
> > Content-Length: 26
> > Content-Type: application/json
> > Accept-Encoding: gzip
> > 
> > {"query":{"match_all":{}}}
> > 
> > HTTP/1.1 200 OK
> > Content-Type: application/json; charset=UTF-8
> > 
> > {
> >   "took" : 0,
> >   "timed_out" : false,
> >   "_shards" : {
> >     "total" : 0,
> >     "successful" : 0,
> >     "skipped" : 0,
> >     "failed" : 0
> >   },
> >   "hits" : {
> >     "total" : {
> >       "value" : 0,
> >       "relation" : "eq"
> >     },
> >     "max_score" : 0.0,
> >     "hits" : [ ]
> >   }
> > }
> > ```
> 
> ![image](https://user-images.githubusercontent.com/53851524/115708735-f2e42700-a3a2-11eb-93a1-8041e7723397.png)
> it's still 411 error

So if this still fails, it's not due to Elastic, the library, but somehow related to your infrastructure. Find out what's wrong with your infrastructure first, then we can make it work in Elastic.

**Comment by Pluto-yubin** [comment]
OK，Thank you all the same, I will try to get in touch with the admin of es cluster to find out the problem

**Comment by Pluto-yubin** [comment]
![image](https://user-images.githubusercontent.com/53851524/116023635-18ad4c80-a67f-11eb-9616-fe0c926f19be.png)
That's the problem of IDE proxy
![image](https://user-images.githubusercontent.com/53851524/116023672-2c58b300-a67f-11eb-830a-1ad9bc91237a.png)

**Comment by ssardana96** [comment]
@olivere I'm also facing the same issue. I have a proxy in between
Due to Transfer-Encoding: chunked, I'm getting 500 from proxy

How can I disable this? I'm not able to create custom client. Can you please help here
Thanks in advance
