### ISSUE TITLE
data stream API

### ISSUE THREAD

**Issue by taylorzhangyx** [olivere/elastic#1484]
### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)

### Please describe the expected behavior
I'm pretty new to this library. But our team is heavily working with data streams.
Just would like to know if there is any plan to support the data stream APIs in this library.

https://www.elastic.co/guide/en/elasticsearch/reference/current/set-up-a-data-stream.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-data-stream.html

**Comment by olivere** [comment]
Hi there! I'm personally not familiar with Data Streams. But as long as there's a REST API Spec for Data Streams (and there is, e.g. [here](https://github.com/elastic/elasticsearch/blob/v7.12.0/x-pack/plugin/src/test/resources/rest-api-spec/api/indices.create_data_stream.json)), we can implement it just like any other API—PRs are welcome.

Data Stream seems also build on existing APIs, is that correct (e.g. ILM, Shrink, Rollover etc.)? I'm pretty sure we already support many of those APIs.

So next step would be to find all services that need to build.

**Comment by olivere** [comment]
Notice that the data stream is now returned in the Get Index Template API as described in #1550.

You can also create a data stream as part of the Put Index Template API: You are responsible to setup the request body though—the DSL won't help you with that (it's simply too dynamic).

Not sure what we're missing here. Let me know and I'll re-open.

**Comment by sdwa0** [comment]
@olivere Can we reopen this?
[#1550](https://github.com/olivere/elastic/pull/1550) seems to have only added the support for parsing data stream object in the response of index template APIs, which is nice but doesn't enable interacting with [Data stream APIs](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/data-stream-apis.html) directly. It would be great to add client code for those APIs too. I can file a PR with the changes.
