### ISSUE TITLE
Why is it slow

### ISSUE THREAD

**Issue by wanghousheng** [olivere/elastic#1485]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)

### Please describe the expected behavior

I just used two ways to search the same index data. The first way is elastic V7 search, and the second way is HTTP request search. The premise is that there are no search conditions in both ways. The first way is 3S, and the second way is 200ms

**Comment by olivere** [comment]
I have no idea. It's very much an educated guess. It could as well be just a cache being warmed up after the first request. Notice that this is just the repository of a Go driver for Elasticsearch, not the Elasticsearch repository. But if you can isolate the effect and are able to construct a reproducible test case, I'm eager to learn what I can do about it.

**Comment by nacholibre** [comment]
@olivere I have a similar issue. Two exactly the same queries - one is ran from curl and one is ran from the golang client. 

Curl query
```bash
~ time curl -X GET "http://localhost:9200/case/_search" -H 'Content-Type: application/json' -d '{"query":{"constant_score":{"filter":{"bool":{"filter":[{"bool":{}},{"geo_bounding_box":{"location":{"bottom_right":[14.0625,54.1624339680678],"top_left":[11.25,55.77657301866769]}}}]}}}},"size":10000,"sort":[{"_id":{"order":"asc"}}]}' &> /dev/null
curl -X GET "http://localhost:9200/case/_search" -H  -d  &> /dev/null  0.01s user 0.04s system 2% cpu 1.745 total
```
The curl query takes 1.745 seconds

golang query
```go
		start := time.Now()
		search := s.ES.Search().Index(s.CasesIndex).
			Query(
				elastic.NewConstantScoreQuery(
					elastic.NewBoolQuery().Filter(
						params.ToQuery(),
						tile.GetBBoxGeoQuery(),
					)),
			).
			Sort("_id", true).
			Size(esMaxFetchDocs)

		searchResult, err := search.Do(ctx)
		elapsed := time.Since(start)
		fmt.Printf("Search took %s\n", elapsed)

```
`Search took 2.269884083s`
this is 0.5 seconds of difference, and this is before the json is deserialized. This seems like a lot.

The client is created like so:
```go
	s.ES, err = elastic.NewClient(
		elastic.SetURL(strings.Split(s.addresses, ",")...),
		elastic.SetSniff(false),
		elastic.SetRetrier(newRetrier()),
	)

```

I'm testing on local, there is no network latency issue and I'm running the queries a lot of times so it's not related to any caching.

What could potentially cause this? This is just a simple http call, it shouldn't have any overhead really?

**Comment by nacholibre** [comment]
I figured out my problem. It was related to the JSON decoding at the query level. I had some documents with very long fields and the JSON decoding was taking .5 seconds itself. So I've configured 
`FetchSourceContext(elastic.NewFetchSourceContext(true).Include("field1", "field2")).` to my query so that only the needed fields are returned
