### ISSUE TITLE
I found a JSON serialization bug in the PutMapping().Index("**").BodyString()

### ISSUE THREAD

**Issue by GrumpyOmer** [olivere/elastic#1488]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)

### Please describe the expected behavior
I can use putMapping ().bodyString () to modify my index
### Please describe the actual behavior
A particularly weird bug occurs when I use putMapping ().bodyString ()... Json is OK, but if I put all the fields I want to change together, I'll get an Error: "Elastic: Error 400 (Bad Request):" Failed to parse content to map [type=parse_exception] ". But I found a problem for a long time after the JSON split into 2 parts to use, and are normal... . Does the length of JSON affect the result of serialization... This bug is really confusing to me... perhaps only to look at the source code to modify it

**Comment by olivere** [comment]
I'm not sure how to help here. Would be very helpful if you could post the request body you're sending to ES.

The fact that ES responds with a `400 Bad Request` typically means that it cannot read/parse the request. That is nothing that this library can fix—especially if you're sending a raw string. In that case you're responsible for posting valid JSON.

**Comment by GrumpyOmer** [comment]
now this is the error json: 
-------------------------------------------------------------------------------------
{
	  "properties": {
		"id": {
			"type": "long"
		},
		"tableName": {
			"type": "keyword"
		},
		"oid": {
			"type": "long"
		},
		"production": {
			"type": "keyword"
		},
		"subtype": {
			"type": "keyword"
		},
		"otype": {
			"type": "keyword"
		},
		"creator": {
			"type": "keyword"
		},
		"tableName": {
			"type": "keyword"
		},
		"create_time": {
			"type": "date"
		},
		"modifier": {
			"type": "keyword"
		},
		"modify_time": {
			"type": "date"
		},
		"info": {
			"type": "text",
			"analyzer": "optimizeIK",
			"search_analyzer": "optimizeIK"
		}
	}
}
-------------------------------------------------------------------------------------

But if I split their fields into two parts and request them separately, it's all successful
-------------------------------------------------------------------------------------
json 1: 
{
	  "properties": {
		"id": {
			"type": "long"
		},
		"tableName": {
			"type": "keyword"
		},
		"oid": {
			"type": "long"
		},
		"production": {
			"type": "keyword"
		},
		"subtype": {
			"type": "keyword"
		},
		"otype": {
			"type": "keyword"
		}
	}
}
-------------------------------------------------------------------------------------
json 2: 
{
	  "properties": {
		"creator": {
			"type": "keyword"
		},
		"tableName": {
			"type": "keyword"
		},
		"create_time": {
			"type": "date"
		},
		"modifier": {
			"type": "keyword"
		},
		"modify_time": {
			"type": "date"
		},
		"info": {
			"type": "text",
			"analyzer": "optimizeIK",
			"search_analyzer": "optimizeIK"
		}
	}
}
-------------------------------------------------------------------------------------

This is puzzling to me 😂

**Comment by olivere** [comment]
Just post it into your favourite editor of choice and... magic!

![image](https://user-images.githubusercontent.com/134848/117781785-467abf80-b241-11eb-9b5c-a83e01f8c943.png)

**Comment by GrumpyOmer** [comment]
Then I found out the same thing.... I think I should buy you a cup of coffee 😂😂  thank you !!!!
