### ISSUE TITLE
Reg. HealthCheck

### ISSUE THREAD

**Issue by vikramchhibber** [olivere/elastic#1489]
It seems that when we enable the health-check using “SetHealthCheck”, the olivere library maintains some state and regularly polls the health status of ES instances. Do we have a call to query this state? I need information whether there is connectivity with ES or none of them is reachable. Presently, I am using “olivere.NewCatHealthService()” to get the status and would like to avoid this call if the library itself maintains the state.

Thanks

### Which version of Elastic are you using?

[X] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Any steps to reproduce the behavior?

**Comment by olivere** [comment]
It's internal state. I'm hesitating about making it publically accessible because then people start to build their logic around it. I think you're absolutely right to use the Health Service API because that reflects the true state of the Elasticsearch cluster.
