### ISSUE TITLE
add docs this way more efficiently

### ISSUE THREAD

**Issue by foreversmart** [olivere/elastic#149]
I found the docs on https://godoc.org/gopkg.in/olivere/elastic.v2, but sadly there are huge numbers of apis need to view except the basic apis (index, update, search, delete and so on). 

This project's wiki pages help me again but do not solve all my problems when i want to implement a complex search query (because there are still only some basic apis)

I wish there are more docs about (the specific elasticsearch api implement by what type or function) rather than i look all the type may implement the api to check it's the right type.

**Comment by olivere** [comment]
Hi! You're right in that documentation for the APIs could be better. However, Elasticsearch has an API with over 600 REST endpoints (last time I counted), and probably more than a thousand parameters and options. As I do this library in my spare time, I simply don't have the time to document them all.

But don't worry. Here's what I found to be the best way to get used to Elasticsearch (and elastic): First, there's [The Definite Guide](https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html) which I recommend as a must read for anyone getting started with Elasticsearch. Read at least the "Getting Started" chapter. If you're ready to get into the details, there is the [API documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html). It is well written, comes with examples, and has many useful tips and tricks. Once you get the concepts and endpoints of Elasticsearch, using elastic becomes natural. The endpoints match up with the services, the parameters are (mostly) the same as they are in the documentation. And if you're still missing something (and God knows elastic has its rough edges), consult the tests. They serve not only as tests but as a "how to" for using elastic as well. Yes, it takes a little time. But sometimes there are no shortcuts.

What other ways of improving documentation do you have in mind?

**Comment by foreversmart** [comment]
yeah, I'm working at your way. maybe when i finished view all the apis. I'll contribute an api docs in my spare time.

thanks anyway~
