### ISSUE TITLE
elastic: Error 400 (Bad Request): failed to parse

### ISSUE THREAD

**Issue by div927** [olivere/elastic#1490]
elastic.v7 (for Elasticsearch 7.x)

```
package main

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"

	elastic "github.com/olivere/elastic"
)

type user struct {
	ID   int64  `json:"id" gorm:"primary_key"`
	Age  int64  `json:"age"`
	Name string `json:"name"`
}

func GetESClient() (*elastic.Client, error) {

	client, err := elastic.NewClient(elastic.SetURL("http://localhost:9200"),
		elastic.SetSniff(false),
		elastic.SetHealthcheck(false))

	fmt.Println("ES initialized...")

	return client, err

}

func main() {

	db, errDb := gorm.Open("mysql", "root:xyz@123@(127.0.0.1)/testdb?charset=utf8mb4&loc=Local")
	if errDb != nil {
		fmt.Println(errDb)
	} else {
		fmt.Println("------------------------------")
		fmt.Println("Connection Sucessful to MySQL")
		fmt.Println("------------------------------")
	}

	defer db.Close()
	db.LogMode(true)

	var users []user
	db.Find(&users)

	articleJSON, err := json.Marshal(users) // &users for string
	if err != nil {
		fmt.Errorf("Error while marshalling json: %s", err.Error())
		fmt.Println(err.Error())
		return
	}

	fmt.Println("###########################")
	fmt.Println(articleJSON)
	fmt.Println("###########################")

	ctx := context.Background()
	esclient, err := GetESClient()
	if err != nil {
		fmt.Println("Error initializing : ", err)
		panic("Client fail ")
	}


	js := string(articleJSON)
	fmt.Println("-----------_____________________-----------")
	fmt.Println(js)
	fmt.Println("-----------_____________________-----------")
	ind, err := esclient.Index().
		Index("users").
		Type("_doc").
		BodyJson(js).
		Do(ctx)

	if err != nil {
		panic(err)
	}

	fmt.Println("[Elastic][InsertProduct]Insertion Successful", ind)

}
```

I want read from my MySQL and write into Elasticsearch.

But the error I'm getting
panic: elastic: Error 400 (Bad Request): failed to parse [type=mapper_parsing_exception]

goroutine 1 [running]:
main.main()
        /Users/xyz/myproject/src/github.com/elasticsearch/test.go:90 +0xb49
exit status 2

**Comment by olivere** [comment]
HTTP status code 400 is almost always an issue with sending invalid JSON to Elasticsearch. Please inspect your code for that.

Another thing: You're using `"github.com/olivere/elastic"` but you **must** use a version, e.g. `"github.com/olivere/elastic/v7"` for ES 7.x.

There's also a [recipe](https://github.com/olivere/elastic/blob/release-branch.v7/recipes/bulk_insert/bulk_insert.go) for doing what you want (besides reading from MySQL).

**Comment by div927** [comment]
yeah I'm using version "github.com/olivere/elastic/v7"  but not able to write my mysql data into elasticsearch.

**Comment by olivere** [comment]
In your code, `js` is a `string`, not some serializable JSON object like e.g. a `map[string]interface{}` or anything that implements `json.Marshaler`. Simply index each `user` instance in a loop, or see the example recipe I mentioned.
