### ISSUE TITLE
elastic: all 1 nodes marked as dead; resurrecting them to prevent deadlock

### ISSUE THREAD

**Issue by gongzhxu** [olivere/elastic#1491]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the actual behavior
Large concurrent queries, appear at intervals
elastic: http://127.0.0.1 :9200 is dead，
dial tcp 127.0.0.1:9200: connect: connection reset by peer

Port 9200 has a lot of time_ wait

**Comment by olivere** [comment]
If you have a cluster with just one node in production, I think you should look at your infrastructure first. If you need to stick with 1 node, you probably should just disable sniffing and healthchecks.
