### ISSUE TITLE
Proxy in between (Transfer-Encoding: chunked)

### ISSUE THREAD

**Issue by ssardana96** [olivere/elastic#1492]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the actual behavior

@olivere I'm also facing the same issue https://github.com/olivere/elastic/issues/1483 . I have a proxy in between
Due to Transfer-Encoding: chunked, I'm getting 500 from proxy

How can I disable this? I'm not able to create custom client. Can you please help here
Thanks in advance

**Comment by ssardana96** [comment]
While client creation you should also have something called UnSetHeader()

**Comment by olivere** [comment]
It's valid HTTP according to the specification, and it's done so by the Go standard library. If you need to disable it, you need to get the standard library to use a different encoding. See [here](https://pkg.go.dev/net/http#Request.Write) for some hints (*). It's not the responsibility of this library to fix networking issues.

> (*) If Body is present, Content-Length is <= 0 and TransferEncoding hasn't been set to "identity", Write adds "Transfer-Encoding: chunked" to the header. Body is closed after it is sent.

So this should do the job (not tested):

```go
req.TransferEncoding = []string{"identity"}
```
