### ISSUE TITLE
Can give a default value when es return "null"

### ISSUE THREAD

**Issue by ryan961** [olivere/elastic#1498]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)

#### This is the aggregation：
```
     aggs := elastic.NewCompositeAggregation().Sources(
		elastic.NewCompositeAggregationTermsValuesSource("customerId").Field("customerId"),
		elastic.NewCompositeAggregationTermsValuesSource("platform").Field("platform"),
		elastic.NewCompositeAggregationTermsValuesSource("appVersion").Field("appVersion"),
	).
		SubAggregation("lastLoginIn", elastic.NewMaxAggregation().Field("actTime")).
		SubAggregation("lastLevel", elastic.NewMaxAggregation().Field("topLevel")).
		Size(10000)
```
#### This is the return result:
```
      {
          "Aggregations":{
              "doc_count":1,
              "key":{
                  "customerId":30342,
                  "platform":"ios",
                  "appVersion":"140"
              },
              "lastLevel":{
                  "value":null
              },
              "lastLoginIn":{
                  "value":"1.61984001E9"
              }
          },
          "Key":{
              "appVersion":"140",
              "customerId":30342,
              "platform":"ios"
          },
          "DocCount":1
      }
```

#### Get the value： 
```
       for _, bucket := range buckets {
                ......
                if last, ok := bucket.Max("lastLevel"); ok {
			lastLevel = *last.Value
		}
       }

```
It  failed to execute  `panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1344771]`  when I thought the execution was successful.

I have to change the code：
```
       for _, bucket := range buckets {
                ......
                if last, ok := bucket.Max("lastLevel"); ok {
			if last.Value != nil {
				lastLevel = *last.Value
			}
		}
       }
```
`null` is a very common data return for ES,  can you make a judgment  Before `json.Unmarshal`  in
```
func (a Aggregations) Max(name string) (*AggregationValueMetric, bool) {
	if raw, found := a[name]; found {
		agg := new(AggregationValueMetric)
		if raw == nil {
			return agg, true
		}
		if err := json.Unmarshal(raw, agg); err == nil {
			return agg, true
		}
	}
	return nil, false
}
```
It can ensure that the program continues to execute when `bucket.Max` retun  `true`.

**Comment by olivere** [comment]
That boolean in the 2nd return value indicates whether or not a `max` aggregation exists. It doesn't make any assumptions on the value it returns.

```go
func (a Aggregations) Max(name string) (*AggregationValueMetric, bool) { ... }
```

The `value` in `AggregationValueMetric` may be `nil` if ES returns a `null`. If we start to make hypothesis based on what people expect and not what Elasticsearch _actually_ returns, we're going down a slippery slope.

That `max` aggregation also has a [`missing` property](https://www.elastic.co/guide/en/elasticsearch/reference/7.13/search-aggregations-metrics-max-aggregation.html#_missing_value_10) which might be exactly what you want to always make ES return a non-`nil` value.

**Comment by Ryalu** [comment]
Alright, thank you! Very helpful.🎉

**Comment by ryan961** [comment]
> That boolean in the 2nd return value indicates whether or not a `max` aggregation exists. It doesn't make any assumptions on the value it returns.
> 
> ```go
> func (a Aggregations) Max(name string) (*AggregationValueMetric, bool) { ... }
> ```
> 
> The `value` in `AggregationValueMetric` may be `nil` if ES returns a `null`. If we start to make hypothesis based on what people expect and not what Elasticsearch _actually_ returns, we're going down a slippery slope.
> 
> That `max` aggregation also has a [`missing` property](https://www.elastic.co/guide/en/elasticsearch/reference/7.13/search-aggregations-metrics-max-aggregation.html#_missing_value_10) which might be exactly what you want to always make ES return a non-`nil` value.

Alright, thank you! Very helpful.🎉
