### ISSUE TITLE
Upsert got error

### ISSUE THREAD

**Issue by foreversmart** [olivere/elastic#150]
when i use client.Update().Index(MyIndex).Type(MyType).Id(MyId).Upsert(Mydata).Do

I got this error `&elastic.Error{Status:400, Message:"ActionRequestValidationException[Validation Failed: 1: script or doc is missing;]"}`

but i change to use DocAsUpsert(true).Doc(Mydata) everything is right, is there something i understand incorrect or bugs

**Comment by foreversmart** [comment]
DocAsUpsert(true).Doc(Mydata)  in your docs is may design for a partial document.

**Comment by olivere** [comment]
Hmm... as far as I can see, you cannot use `Upsert` standalone. You must [either provide a script or set a document](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html#upserts). Am I missing something?

**Comment by olivere** [comment]
Can you provide a test case that will work against ES but doesn't with elastic?

**Comment by foreversmart** [comment]
but, these two interfaces give me much confusion.

1.func (b *UpdateService) Upsert(doc interface{}) *UpdateService

2.func (b *UpdateService) Doc(doc interface{}) *UpdateService

the both interfaces pass doc interface{}.  must i pass the doc twice?

**Comment by olivere** [comment]
I'm not using the Upsert/Update API in my apps, so I'm not too familiar with it. But AFAICS the `Doc` is for [updating a partial document](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html#_updates_with_a_partial_document) while [Upsert](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html#upserts) will run a script when the document already exists.

I'm trying to implement the API in the same way the Java client does. If there's a semantic difference between the two, I'd really like to know.

**Comment by foreversmart** [comment]
thanks a lot!   I've review the elastic docs again carefully and you are right.
