### ISSUE TITLE
panic: no active connection found: no Elasticsearch node available

### ISSUE THREAD

**Issue by yinhuanyi** [olivere/elastic#1501]
### Which version of Elastic are you using?

elastic.v7 (for Elasticsearch 7.x)

### Please describe the expected behavior
panic: no active connection found: no Elasticsearch node available

**Comment by tanimutomo** [comment]
@yinhuanyi

I had same issue.
This issue can be helpful!

https://github.com/olivere/elastic/issues/312

**Comment by olivere** [comment]
Be sure to also read https://github.com/olivere/elastic/wiki/Connection-Problems.
