### ISSUE TITLE
tophits confuse

### ISSUE THREAD

**Issue by Belyenochi** [olivere/elastic#1504]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[☑️ ] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
I don't know how to write the same meaning dsl like this :

`POST /test/_search?search_type=count
{
    "aggs": {
        "group": {
            "terms": {
                "field": "country"
            },
            "aggs": {
                "group_docs": {
                    "top_hits": {
                        "size": 1,
                        "sort": [
                            {
                                "collected": {
                                    "order": "desc"
                                }
                            }
                        ]
                    }
                }
            }
        }
    }
}`

### Please describe the actual behavior
I have some documents indexed on Elasticsearch, looking like these samples:

{'country': 'France', 'collected': '2015-03-12', 'value': 20}
{'country': 'Canada', 'collected': '2015-03-12', 'value': 21}
{'country': 'Brazil', 'collected': '2015-03-12', 'value': 33}
{'country': 'France', 'collected': '2015-02-01', 'value': 10}
{'country': 'Canada', 'collected': '2015-02-01', 'value': 11}
{'country': 'Mexico', 'collected': '2015-02-01', 'value': 9}
...
I want to build a query that gets one result per country, getting only the ones with max(collected).

So, for the examples shown above, the results would be something like:

{'country': 'France', 'collected': '2015-03-12', 'value': 20}
{'country': 'Canada', 'collected': '2015-03-12', 'value': 21}
{'country': 'Brazil', 'collected': '2015-03-12', 'value': 33}
{'country': 'Mexico', 'collected': '2015-02-01', 'value': 9}

**Comment by olivere** [comment]
I'm sorry but I don't have the resources to help you with your code. Elasticsearch is a complex beast, and generating the correct query with the DSL can be quite an issue. If you want to use the DSL, the tests are your first source of help. For `InnerHits`, there's e.g. [these tests](https://github.com/olivere/elastic/blob/b7de00ddfd128672eac82ef8f6e938bcbb6c2cd4/search_test.go#L876-L1319) and the [`inner_hit_test.go` test file](https://github.com/olivere/elastic/blob/release-branch.v7/inner_hit_test.go).

EDIT: You're looking for `top_hits` aggregation. There's a [test here](https://github.com/olivere/elastic/blob/b7de00ddfd128672eac82ef8f6e938bcbb6c2cd4/search_aggs_metrics_top_hits_test.go) and an [integration test here](https://github.com/olivere/elastic/blob/fb742c189ed43878d94f3261f85dc55c1bc35fdf/search_aggs_test.go#L114) (and [here](https://github.com/olivere/elastic/blob/fb742c189ed43878d94f3261f85dc55c1bc35fdf/search_aggs_test.go#L1071-L1175)).

If the aggregations are missing some features, let me know.

EDIT: Finally, if everything is still too complex, you're free to send a [`RawString` query](https://github.com/olivere/elastic/blob/b7de00ddfd/search_queries_raw_string_test.go) to Elasticsearch by providing the query as e.g. a `string` or any JSON-serializable structure.
