### ISSUE TITLE
how can i translate this in code(elastic.v5)

### ISSUE THREAD

**Issue by canran** [olivere/elastic#1505]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[get ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

**how can i translate this in code(elastic.v5)**
```
{
  "size": 1,
  "query": {
    "bool": {
      "filter": [
        {
          "range": {
            "time_stamp": {
              "gt": "2021-05-29T21:58:06.000+0800",
              "lt": "2021-08-08T21:58:06.000+0800"
            }
          }
        }
      ]
    }
  },
  "aggs": {
    "by_pid": {
      "terms": {
        "field": "p_id",
        "size": 10000
      },
      "aggs": {
        "sum_drop_value": {
          "sum": {
            "field": "drop_value"
          }
        },
        "sum_drop_monitor_duration": {
          "sum": {
            "field": "drop_monitor_duration"
          }
        },
        "by_version": {
          "terms": {
            "field": "version",
            "size": 10000
          },
          "aggs": {
            "sum_drop_value": {
              "sum": {
                "field": "drop_value"
              }
            },
            "sum_drop_monitor_duration": {
              "sum": {
                "field": "drop_monitor_duration"
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by olivere** [comment]
I'm sorry but I don't have the capacity to help you with your programming tasks.

However, if you're looking for examples of how to use the DSL to build such a query, take a look at the `*_test.go` files. For aggregations, [`search_aggs_test.go`](https://github.com/olivere/elastic/blob/release-branch.v5/search_aggs_test.go) is a good example. For boolean query, [`search_queries_bool_test.go`](https://github.com/olivere/elastic/blob/release-branch.v5/search_queries_bool_test.go) is the way to go. If you want to send the query as-is, use [`search_queries_raw_string_test.go`](https://github.com/olivere/elastic/blob/release-branch.v5/search_queries_raw_string_test.go).
