### ISSUE TITLE
need to query on nested field with depth of 3

### ISSUE THREAD

**Issue by nojyarg** [olivere/elastic#1506]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
This is the query which works fine as a cURL:
{
 "query": {
   "nested": {
     "path": "watch_providers",
     "query": {
       "nested": {
         "path": "watch_providers.US",
         "query": {
           "nested": {
             "path": "watch_providers.US.buy",
             "query": {
               "bool": {
                 "must": [
                   { "match": { "watch_providers.US.buy.provider_name": "Amazon Video" } }
                 ]
               }
             }
           }
         }
       }
     }
   }
 }
}
'

here is the mapping for the relevant section:
      "watch_providers": {
        "type": "nested",
        "properties": {
          "US": {
            "type": "nested",
            "properties": {
              "buy": {
                "type": "nested",
                "properties": {
                  "logo_path": {
                    "type": "text"
                  },
                  "provider_name": {
                    "type": "text"
                  },
                  "display_priority": {
                    "type": "integer"
                  }
                }
              }

### Please describe the actual behavior
It works great, but i don't know how to construct the nested query with with a depth of 3 using your go client. Is there an example that shows multiple levels of nesting? is it maybe something like this?

bq := NewBoolQuery()
bq = bq.Must(NewMatchQuery("watch_providers.US.buy.provider_name", "Amazon Video"))
q := NewNestedQuery("watch_providers.US.buy", bq)
q1 := NewNestedQuery("watch_providers.US", q)
q2 := NewNestedQuery("watch_providers", q1)
src, err := q2.Source()

**Comment by nojyarg** [comment]
is it something like this?

bq := NewBoolQuery()
bq = bq.Must(NewMatchQuery("watch_providers.US.buy.provider_name", "Amazon Video"))
q := NewNestedQuery("watch_providers.US.buy", bq)
q1 := NewNestedQuery("watch_providers.US", q)
q2 := NewNestedQuery("watch_providers", q1)
src, err := q2.Source()

**Comment by olivere** [comment]
You can try yourself...

```go
package main

import (
	"encoding/json"
	"log"

	"github.com/olivere/elastic/v7"
)

func main() {
	log.SetFlags(0)

	bq := elastic.NewBoolQuery()
	bq = bq.Must(elastic.NewMatchQuery("watch_providers.US.buy.provider_name", "Amazon Video"))
	q := elastic.NewNestedQuery("watch_providers.US.buy", bq)
	q1 := elastic.NewNestedQuery("watch_providers.US", q)
	q2 := elastic.NewNestedQuery("watch_providers", q1)
	src, err := q2.Source()
	if err != nil {
		log.Fatal(err)
	}
	data, err := json.MarshalIndent(src, "", "  ")
	if err != nil {
		log.Fatalf("marshaling to JSON failed: %v", err)
	}
	got := string(data)
	log.Println(got)
}
```
