### ISSUE TITLE
BulkResponse.Errors not documented

### ISSUE THREAD

**Issue by fgblomqvist** [olivere/elastic#1509]
### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

It's unclear what `Errors` on a BulkResponse does. Is it just the same as `len(BulkResponse.Failed) > 0`?
Should be documented here: https://pkg.go.dev/github.com/olivere/elastic/v7#BulkResponse.

**Comment by olivere** [comment]
See the documentation over at [Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html#bulk-api-response-body). Here's an example of a [failed response body](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html#bulk-failures-ex). And `Failed` is [documented as such](https://github.com/olivere/elastic/blob/da2b168af2a62f07def937a91d45844089b5e0d5/bulk.go#L438-L439).
