### ISSUE TITLE
Wiki example is not pretty

### ISSUE THREAD

**Issue by yinhuanyi** [olivere/elastic#1511]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ✅] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
I lookout the wiki, and cannot find the detail example for search api. In some articles, I read something new about the usage of search api. Such as :  elastic.NewFetchSourceContext、SortBy

### Please describe the actual behavior
Where can I find the detail example of olivere/elastic？

**Comment by olivere** [comment]
The best source for examples of the DSL are the tests. Just peek into the hundreds of `*_test.go` files, and you'll eventually learn how to do it.

Especially helpful for search-related examples are [`search_test.go`](https://github.com/olivere/elastic/blob/release-branch.v7/search_test.go) and [`search_aggs_test.go`](https://github.com/olivere/elastic/blob/release-branch.v7/search_aggs_test.go). Here's [`fetch_source_context_test.go`](https://github.com/olivere/elastic/blob/release-branch.v7/fetch_source_context_test.go).

**Comment by yinhuanyi** [comment]
OK, Thank you for your reply!
