### ISSUE TITLE
Is it possible to provide more details to `reason` when requests fail? 

### ISSUE THREAD

**Issue by henryhsue** [olivere/elastic#1514]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

Is it possible to get more info in the `reason` provided by `ErrorDetails`? e.g. "All Shards Failed" is very obscure, but the trace level `reason` is much more detailed and useful. However, rather than enable trace level logs always, is it possible to get this level of detail when a search request fails? This is useful for running in production and debugging requests that have errors.

**Comment by olivere** [comment]
All the information passed back from Elasticsearch are part of the [`elastic.Error` type](https://github.com/olivere/elastic/blob/release-branch.v7/errors.go#L66-L102) (at least I hope they're complete). Plus, there are a lot of helper functions to extract specific details from an error, e.g. [`ErrorReason(err)`](https://github.com/olivere/elastic/blob/release-branch.v7/errors.go#L112-L124) or [`IsNotFound(err)`](https://github.com/olivere/elastic/blob/release-branch.v7/errors.go#L148-L153) and [friends](https://github.com/olivere/elastic/blob/release-branch.v7/errors.go#L142-L203).

What is not possible (and not a goal) is for the the library to extract additional information from an error besides what Elasticsearch returns. The client should be as dumb as possible IMHO.

I hope this answers your question.

**Comment by henryhsue** [comment]
Thanks @olivere, yes that answers my question. 

I believe `details.reason` is what I'm after within `elastic.Error`. Unfortunately, it sounds like Elastic isn't providing as much info within that `reason`.  e.g. "All Shards Failed" can be further explained _with_ tracing logs, by query syntax errors, maxClauseCount exceeded, and multitude of other issues...

**Comment by olivere** [comment]
The core of it is defined server-side in [`ElasticsearchException.java`](https://github.com/elastic/elasticsearch/blob/v7.13.4/server/src/main/java/org/elasticsearch/ElasticsearchException.java), and I don't think we're missing a field from it.

And it's rather detailed. If you look at e.g. `caused_by` and `root_cause` (which can be deeply recursive). See [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#common-options-error-options) for documentation on how to read these errors.
