### ISSUE TITLE
Runtime fields

### ISSUE THREAD

**Issue by justin-wilxite** [olivere/elastic#1527]
I am just wondering if it is supported to add runtime fields / runtime mappings to a search query:
https://www.elastic.co/guide/en/elasticsearch/reference/current/runtime-search-request.html

I couldn't find this mentioned anywhere in the documentation.
Thanks

### Which version of Elastic are you using?

[x ] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

**Comment by olivere** [comment]
Yes, I would love to see support for this anytime soon. Though I didn't start implementing it yet.
