### ISSUE TITLE
Muti Field group query

### ISSUE THREAD

**Issue by wang-xiaowu** [olivere/elastic#1532]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)

### Please describe the expected behavior
Implement field group query, the following is a DSL statement example
```
{
  "size": 0,
  "query": {
    "match": {
      "logtype.keyword": "acc"
    }
  },
  "aggs": {
    "group_by_module": {
      "terms": {
        "field": "module.keyword"
      },
      "aggs": {
        "group_by_method": {
          "terms": {
            "field": "method.keyword"
          },
          "aggs": {
            "group_by_url": {
              "terms": {
                "field": "url.keyword",
                "size": 500
              },
              "aggs": {
                "avg_res_time": {
                  "avg": {
                    "field": "responseTime"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```
### Please describe the actual behavior
I did not find the correct way to write the following aggregate query
Tried the following, but not correct
```
module := elastic.NewTermsAggregation().Field("module.keyword")
method := elastic.NewTermsAggregation().Field("method.keyword")
url := elastic.NewTermsAggregation().Field("url.keyword")
resTime := elastic.NewAvgAggregation().Field("responseTime")
url = url.SubAggregation("avg_res_time",resTime)
method = method.SubAggregation("group_by_url",url)
module = module.SubAggregation("group_by_method",method)
source, _ := module.Source()
marshal, _ := json.Marshal(source)
fmt.Println(string(marshal))
```

**Comment by wang-xiaowu** [comment]
Hope for your reply

**Comment by olivere** [comment]
Please look into the `*_test.go` files for hundreds of examples. For aggregations, [this is probably what you need](https://github.com/olivere/elastic/blob/release-branch.v7/search_aggs_test.go#L78-L210).

**Comment by wang-xiaowu** [comment]
> 请查看`*_test.go`文件以获取数百个示例。对于聚合，[这可能就是您所需要的](https://github.com/olivere/elastic/blob/release-branch.v7/search_aggs_test.go#L78-L210)。

I have seen, but do not know aggs nested in aggs -.-

**Comment by olivere** [comment]
But [here is a nested aggragation](https://github.com/olivere/elastic/blob/release-branch.v7/search_aggs_test.go#L100), and [here's how to use it in the response](https://github.com/olivere/elastic/blob/release-branch.v7/search_aggs_test.go#L772-L791).

**Comment by wang-xiaowu** [comment]
> But [here is a nested aggragation](https://github.com/olivere/elastic/blob/release-branch.v7/search_aggs_test.go#L100), and [here's how to use it in the response](https://github.com/olivere/elastic/blob/release-branch.v7/search_aggs_test.go#L772-L791).

All right, i'll see
thank u so much

**Comment by wang-xiaowu** [comment]
sorry
It doesn't feel like what I want

**Comment by wang-xiaowu** [comment]
Can you guide me please

**Comment by a943915349** [comment]
Can you look at the DSL example I posted, I don't see the corresponding method in the existing sample

**Comment by wang-xiaowu** [comment]
Can you look at the DSL example I posted, I don't see the corresponding method in the existing sample  @olivere

**Comment by wang-xiaowu** [comment]
> Can you look at the DSL example I posted, I don't see the corresponding method in the existing sample @olivere

I'm really sorry to bother you, but I'm in a hurry today

**Comment by olivere** [comment]
This should do the job:

```go
package main

import (
	"encoding/json"
	"fmt"
	"log"

	"github.com/olivere/elastic/v7"
)

func main() {
	b := elastic.NewSearchSource()
	b = b.Size(0)
	b = b.Query(elastic.NewMatchQuery("logtype.keyword", "acc"))

	avgResTime := elastic.NewAvgAggregation().Field("responseTime")
	groupByURL := elastic.NewTermsAggregation().Field("url.keyword").Size(500)
	groupByURL = groupByURL.SubAggregation("avg_res_time", avgResTime)
	groupByMethod := elastic.NewTermsAggregation().Field("method.keyword")
	groupByMethod = groupByMethod.SubAggregation("group_by_url", groupByURL)
	groupByModule := elastic.NewTermsAggregation().Field("module.keyword")
	groupByModule = groupByModule.SubAggregation("group_by_method", groupByMethod)
	b = b.Aggregation("group_by_module", groupByModule)

	src, err := b.Source()
	if err != nil {
		log.Fatal(err)
	}
	out, err := json.MarshalIndent(src, "", "  ")
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(string(out))
}
```

It's not that hard.

**Comment by wang-xiaowu** [comment]
> This should do the job:
> 
> ```go
> package main
> 
> import (
> 	"encoding/json"
> 	"fmt"
> 	"log"
> 
> 	"github.com/olivere/elastic/v7"
> )
> 
> func main() {
> 	b := elastic.NewSearchSource()
> 	b = b.Size(0)
> 	b = b.Query(elastic.NewMatchQuery("logtype.keyword", "acc"))
> 
> 	avgResTime := elastic.NewAvgAggregation().Field("responseTime")
> 	groupByURL := elastic.NewTermsAggregation().Field("url.keyword").Size(500)
> 	groupByURL = groupByURL.SubAggregation("avg_res_time", avgResTime)
> 	groupByMethod := elastic.NewTermsAggregation().Field("method.keyword")
> 	groupByMethod = groupByMethod.SubAggregation("group_by_url", groupByURL)
> 	groupByModule := elastic.NewTermsAggregation().Field("module.keyword")
> 	groupByModule = groupByModule.SubAggregation("group_by_method", groupByMethod)
> 	b = b.Aggregation("group_by_module", groupByModule)
> 
> 	src, err := b.Source()
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 	out, err := json.MarshalIndent(src, "", "  ")
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 	fmt.Println(string(out))
> }
> ```
> 
> It's not that hard.

thanks a lot,may be i was wrong,I thought this statement was wrong

![image](https://user-images.githubusercontent.com/44340137/132270819-a7be1fdd-e6b7-45de-9223-f21174a89f54.png)
