### ISSUE TITLE
Delete_By_Query with Max_Docs parameter

### ISSUE THREAD

**Issue by avi94** [olivere/elastic#1537]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)

### Please describe the expected behavior
I expected to be able to use **max_docs** parameter with the **delete_by_query**.

### Please describe the actual behavior
Cannot find if there is **max_docs** parameter option to use with  **delete_by_query**. I have searched for a while but couldn't find it in the library.

### Any steps to reproduce the behavior?
Here is a snippet of what I am doing:

`esResponseSalesRepMaterial, err := elastic.NewDeleteByQueryService(esClient).Index(salesRepMaterialsIndex).Slices(150).Query(boolQuery).Refresh("true").Do(context.Background())`

And what I want to be able to do here is, use max_docs with this.

A dummy query to show what I'm trying:

`POST /index_name/_delete_by_query?refresh=true&version&slices=100&max_docs=100000
{
  "query": {
    "bool": {
      "must": {
        "range": {
          "created_timestamp": {
            "from": null,
            "include_lower": true,
            "include_upper": false,
            "to": 1633344763
          }
        }
      }
    }
  }
}`

This works perfectly fine in Kibana, and I need to do the same in our backend code.

Thanks in advance!

**Comment by olivere** [comment]
Yep, that's missing. Thanks for reporting.

Should be a simple fix, will set it on the list for 7.0.30 (currently waiting for ES to fix an issue, hopefully in 7.15.1).

**Comment by avi94** [comment]
Thanks @olivere! Meanwhile, any alternatives?

**Comment by olivere** [comment]
You can always use `Client.PerformRequest` directly. Other than that... no.
