### ISSUE TITLE
logger with context ?

### ISSUE THREAD

**Issue by lichunqiang** [olivere/elastic#1541]
### Which version of Elastic are you using?

[ x ] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

Can Logger support Context ? Because it's usefully for tracing，add requestId etc for a request.

**Comment by olivere** [comment]
you can implement your own logger. Just implement the Logger interface as defined in https://github.com/olivere/elastic/blob/release-branch.v7/logger.go. Hope that helps.

**Comment by lichunqiang** [comment]
@olivere that does not meet the problem. (we have implement own logger with zap)

In our system, there is a "requestId" for per-request for logging, so we can combine multiple log for the same request.

if there is an error, `errorlog` will trace the error message, but we can not add custom fields to the log message (which get from Context).

**Comment by olivere** [comment]
Ah. I see. Let me have another look at it.

**Comment by olivere** [comment]
Yep. Passing the context as part of the logging should be fine. Just need to make it backwards compatible.

As for tracing, there's already support for [`opentracing`](https://github.com/olivere/elastic/tree/release-branch.v7/trace/opentracing) and [`opencensus`](https://github.com/olivere/elastic/tree/release-branch.v7/trace/opencensus), and logging is not the best way to do tracing.

**Comment by olivere** [comment]
https://github.com/olivere/elastic/pull/1542 should give you what you want. I will leave it around until 7.0.30 will be released. There's a few things I don't like about that PR, but yeah. Maybe I'll find a cleaner solution.

If https://github.com/olivere/elastic/pull/1542 will be merged, you only have to implement `LoggerWithContext` interface to get a `context.Context`. Notice that that context may be anything: It's not only for requests being performed by any of the APIs: It's also for requests from background tasks (e.g. sniffing, healthchecks, or bulk processor). So don't rely on the fact that the context passed is actually from you.

**Comment by lichunqiang** [comment]
@olivere thanks !

**Comment by EricDominguez1** [comment]
@olivere 
hello, this change is not going to upload?

**Comment by olivere** [comment]
Very probably not. This repository is effectively deprecated and dormant. Please switch to the official client.
