### ISSUE TITLE
question: PutMapping BodyJson

### ISSUE THREAD

**Issue by dyipon** [olivere/elastic#1543]
Hi,

I would like to clone/copy the whole index to another node. Bulk copy, analyzer copy is working fine, but im stuck at copying the mapping:
```
     sourcemapping, _ := sourceClient.GetMapping().Index(indexName).Do(context.Background())
       if err != nil {
             // Handle error
           log.Fatal(err)
        }
   
  _, err = destClient.PutMapping().Index(indexName).BodyJson(sourcemapping).Do(context.Background())

```

Got this error message: `Root mapping definition has unsupported parameters:  [test : {mappings={}}]`

I tried to find examples, and checked the https://github.com/olivere/elastic/blob/release-branch.v7/indices_put_mapping_test.go code too, but did not find the solution.

Anybody could help me?

**Comment by olivere** [comment]
For the actual cloning, there's a [Clone Index API](https://www.elastic.co/guide/en/elasticsearch/reference/7.15/indices-clone-index.html). Not sure if it's implemented in the client already, but that'd make sense. It already has the [Reindex API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html) though, which should help as well.

As for the mapping, you should be able to use [Get Mapping API](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-mapping.html) and then create the mapping in the new index [like so](https://github.com/olivere/elastic/blob/release-branch.v7/recipes/mapping/mapping.go).

If the indices are the same, [index templates](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-template.html) also work very well.

HTH

**Comment by dyipon** [comment]
thanks, Reindex API is easy as 1-2-3, I already made it work.
