### ISSUE TITLE
Sort and Search After on date nanoseconds field

### ISSUE THREAD

**Issue by Yiling-J** [olivere/elastic#1545]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
https://www.elastic.co/guide/en/elasticsearch/reference/current/date_nanos.html

if my filed value is `1420114230123456789`, the `SearchHit.Sort` result should be `[1420114230123456789]` too.
Even if this number already exceed json number limit.

### Please describe the actual behavior
 - raw response: `"sort":[1420114230123456789,0.11190013,1420114230123456789]`
 - `SearchHit.Sort`: `[1.4201142301234568e+18 0.11190013 1.4201142301234568e+18]`
 - `search_after` value: `"search_after":[1420114230123456800,0.11190013,1420114230123456800]` 

### Any steps to reproduce the behavior?
Just try `date_nanos` field with `sort` and `search_after`

**Comment by olivere** [comment]
If this is a JSON encoding/decoding issue, I don't know if we can do anything about it.

**Comment by Yiling-J** [comment]
Thanks. I think i can just using `NumberDecoder` and get values manually.
