### ISSUE TITLE
Prefix Query Not Encoding Case-Insensitive

### ISSUE THREAD

**Issue by crweatherly** [olivere/elastic#1546]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

```
NewPrefixQuery("foo", "bar").CaseInsensitive(true)
```
should yield:
```
{
  "prefix": {
    "foo": {
      "case_insensitive": true, "value": "bar"
    }
  }
}
```

### Please describe the actual behavior

```
NewPrefixQuery("foo", "bar").CaseInsensitive(true)
```
yields:
```
{
  "prefix": {
    "foo": "bar"
  }
}
```

`PrefixQuery.Source()` fails to check if the case-insensitive property has been set before defaulting to generating the short request form:
```
--- a/search_queries_prefix.go
+++ b/search_queries_prefix.go
@@ -52,7 +52,7 @@ func (q *PrefixQuery) Source() (interface{}, error) {
        query := make(map[string]interface{})
        source["prefix"] = query

-       if q.boost == nil && q.rewrite == "" && q.queryName == "" {
+       if q.boost == nil && q.rewrite == "" && q.caseInsensitive == nil && q.queryName == "" {
                query[q.name] = q.prefix
        } else {
                subQuery := make(map[string]interface{})
```

### Any steps to reproduce the behavior?

Set the `CaseInsensitive()` property of `PrefixQuery` and no other optional properties.

**Comment by olivere** [comment]
Thanks for reporting. Will fix it in the next release.

**Comment by martinrode** [comment]
NewWildcardQuery is missing "CaseInsensitive".  Maybe this can be added everywhere where Elastic allowes "case_insensitive" (since 7.10.0)?

**Comment by olivere** [comment]
@martinrode WildcardQuery [already has `CaseSensitive` in 7.0.29](https://github.com/olivere/elastic/blob/release-branch.v7/search_queries_wildcard_test.go#L70-L85). Will look for the other cases.
