### ISSUE TITLE
Greater than sign and less than sign can not be used in script

### ISSUE THREAD

**Issue by yxyyslf** [olivere/elastic#1548]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)

### Please describe the expected behavior

I put script "doc[field1].value + doc[field2].value > 0.5" in NewScriptInline function. 

### Please describe the actual behavior

Actually get "doc['field1'].value + doc['field2'].value \u003e 0.5" in real query

**Comment by olivere** [comment]
That's a valid encoding that the Go JSON encoder does by default. It replaces `>`, `<`, and `&` with their `\uXXXX` counterparts for security reasons.

The actual encoding shouldn't be an issue. It should work anyway. If it doesn't, please send me a unit test that I can execute to reproduce the issue.
