### ISSUE TITLE
Multi-Inner-Hits doesn't seems to be available in Collapse 

### ISSUE THREAD

**Issue by LGabilly** [olivere/elastic#1553]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

Inside a `collapse` I which to have multiple `inner_hits`. Like : [Collapse inner hits](https://www.elastic.co/guide/en/elasticsearch/reference/current/collapse-search-results.html)

### Please describe the actual behavior

It seems, there can only be one single `Inner_hits` field inside the `collapse field`

### Any steps to reproduce the behavior?

```
elastic.NewCollapseBuilder("user").
    Field("name.keyword").
    InnerHit(elastic.NewInnerHit().Name("one")).
    InnerHit(elastic.NewInnerHit().Name("two"))
```

**Comment by olivere** [comment]
Yes, looks like a missing feature in `CollapseBuilder` at least.
