### ISSUE TITLE
Getting mapping using the client throws error on ElasticSearch v8

### ISSUE THREAD

**Issue by deepjyoti30** [olivere/elastic#1555]
### Which version of Elastic are you using?

- [x] elastic.v7 (for Elasticsearch 7.x)
- [ ] elastic.v6 (for Elasticsearch 6.x)
- [ ] elastic.v5 (for Elasticsearch 5.x)
- [ ] elastic.v3 (for Elasticsearch 2.x)
- [ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

Mapping should be returned based on the index passed to the client.

### Please describe the actual behavior

An error is thrown. Elastic Search throws a `400 Bad Request` error.

```console
HTTP/1.1 400 Bad RequestContent-Type: application/jsonX-Elastic-Product: Elasticsearch{"error":"no handler found for uri [/.target/_mapping/_all] and method [GET]"}
```

### Any steps to reproduce the behavior?

Deploy an Elastic Version 8 image and try to get the mapping for any index.

---

As far as I can see from the calls, the mapping calls are being made to the `<target>/_mapping/_all`. However, as of Elastic v8, the `<target>/_mapping/_all` doesn't work and the `<target>/_mapping` endpoint is supposed to be used.

I tested locally and the `<target>/_mapping` endpoint works exactly similar to the `<target>/_mapping/_all` endpoint without the `_all` appended to the URI.

**Comment by olivere** [comment]
ES 8.x is not yet supported.
