### ISSUE TITLE
Does UpdateByQuery support direct DSL updates? I can't find the API 

### ISSUE THREAD

**Issue by along-KAL** [olivere/elastic#1556]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
Does UpdateByQuery support direct DSL updates? I can't find the API

**Comment by olivere** [comment]
Sure it does. Just have a [look at the tests](https://github.com/olivere/elastic/blob/release-branch.v7/update_by_query_test.go).

**Comment by along-KAL** [comment]
thanks
