### ISSUE TITLE
About the log4j vulnerability(https://github.com/advisories/GHSA-jfh8-c2jp-5v3q)

### ISSUE THREAD

**Issue by Naughty-Stone** [olivere/elastic#1558]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ *] elastic.v7 (for Elasticsearch 7.x)
[ *] elastic.v6 (for Elasticsearch 6.x)
[ *] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
Concerns about the log4j vulnerability

### Please describe the actual behavior
I saw the log4j configurations in this lib, will it be affected by the log4j vulnerability(https://github.com/advisories/GHSA-jfh8-c2jp-5v3q)?

elastic$ grep -rI 'log4j'
etc/jvm.options:# log4j 2
etc/jvm.options:-Dlog4j.shutdownHookEnabled=false
etc/jvm.options:-Dlog4j2.disable.jmx=true
etc/jvm.options:-Dlog4j.skipJansi=true

### Any steps to reproduce the behavior?
elastic$ grep -rI 'log4j'
etc/jvm.options:# log4j 2
etc/jvm.options:-Dlog4j.shutdownHookEnabled=false
etc/jvm.options:-Dlog4j2.disable.jmx=true
etc/jvm.options:-Dlog4j.skipJansi=true

**Comment by olivere** [comment]
Thanks for reporting. That directory hasn't been used for a long time, and I've removed it recently. We're using Docker images for the specific ES/ELK stack we're targeting. There's still an issue with e.g. version 5.x of the library, which supports an ES version no longer supported that won't get the log4j update.
