### ISSUE TITLE
by pass sorting in elastic search query

### ISSUE THREAD

**Issue by vikas17a** [olivere/elastic#156]
Hi,

I am trying to search a key value pair in elastic search index i always end up in error because of sorting  parameter passed in elastic search query. I want to avoid the sort function is there a way to avoid this sort feature in elastic search query

**Comment by olivere** [comment]
A term query provides a key/value lookup (given that keys are unique). E.g.

```go
package main

import (
	"log"
	"os"

	"gopkg.in/olivere/elastic.v2"
)

func main() {
	client, err := elastic.NewClient(elastic.SetTraceLog(log.New(os.Stdout, "", 0)))
	if err != nil {
		log.Fatal(err)
	}

	query := elastic.NewTermQuery("<key>", "<value>")
	res, err := client.Search("<index>").Query(&query).Do()
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("%d results", res.TotalHits())
}
```

That should be very fast for most queries. If you still need to optimize, you could use a [term filter](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/query-dsl-term-filter.html) and/or even use [scan](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-search-type.html) to disable scoring and sorting.

If that doesn't help, please send a complete sample that I can look into.

**Comment by vikas17a** [comment]
Thanks worked :)

On Tue, Nov 3, 2015 at 12:54 PM, Oliver Eilhard <notifications@github.com>
wrote:

> A term query provides a key/value lookup (given that keys are unique). E.g.
>
> package main
> import (
>     "log"
>     "os"
>
>     "gopkg.in/olivere/elastic.v2"
> )
> func main() {
>     client, err := elastic.NewClient(elastic.SetTraceLog(log.New(os.Stdout, "", 0)))
>     if err != nil {
>         log.Fatal(err)
>     }
>
>     query := elastic.NewTermQuery("<key>", "<value>")
>     res, err := client.Search("<index>").Query(&query).Do()
>     if err != nil {
>         log.Fatal(err)
>     }
>     log.Printf("%d results", res.TotalHits())
> }
>
> That should be very fast for most queries. If you still need to optimize,
> you could use a term filter
> <https://www.elastic.co/guide/en/elasticsearch/reference/1.7/query-dsl-term-filter.html>
> and/or even use scan
> <https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-search-type.html>
> to disable scoring and sorting.
>
> If that doesn't help, please send a complete sample that I can look into.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/olivere/elastic/issues/156#issuecomment-153277264>.
>



-- 
Regards,
Vikas Aggarwal
