### ISSUE TITLE
Loss of precision will occur when high-precision numbers are parsed here

### ISSUE THREAD

**Issue by zhanglp92** [olivere/elastic#1561]
https://github.com/olivere/elastic/blob/e037a96c4d3a384002c071cb999b0f32e35e2dd5/search.go#L773

Thanks look about issue.

Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior

Lossless data can be obtained through store.

Like source, it can support users to unmarshal

### Please describe the actual behavior

Data accuracy will be lost in `json.Unmarshal(body, map[string]interface{})`

### Any steps to reproduce the behavior?

eg: 

source-data: int64(-65302192449388541)
unmarshal-data: float64(-6.530219244938854e+16)
user-data: int64(float64(unmarshal-data)) = -65302192449388544

**Comment by olivere** [comment]
I guess that's inevitable. JSON by default only has a [numeric data type](https://en.wikipedia.org/wiki/JSON#Data_types) and e.g. doesn't have separate decimal and integer types. The only workaround I've seen more often than not is to serialize into a string and deserialize from there again.

It is out of scope for this library to come up with an alternative JSON encoder/decoder. However, you can configure your own, and if you can get `encoding/json` to work around your issue (e.g. some use [`UseNumber`](https://pkg.go.dev/encoding/json#Decoder.UseNumber)), you can configure your own decoder with [`SetDecoder(...)`](https://github.com/olivere/elastic/blob/release-branch.v7/client.go#L663-L674) and friends.

**Comment by zhanglp92** [comment]
I see, but i think this is not a friendly solution.

If the `Fields` can be defined as json.RawMessage type (Like `Source`), then users can parse and use by themselves

**Comment by olivere** [comment]
Did you have a look at the byte array that is `Fields`? I guess it's already too late to do the parsing then. Also, it'd be a breaking change. It would work fine for you, but would force all other users happily using `Fields` as-is to change their code.

**Comment by zhanglp92** [comment]
no no no. 
It is definitely not to modify the original fields (as a programmer, there is still some morality).
I am also thinking about this question, how can it be more friendly
