### ISSUE TITLE
How to parse the query string?

### ISSUE THREAD

**Issue by lucasbbb** [olivere/elastic#1563]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[*] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
For some reason, I need to replace a field in the query string to another field. 

q=name:"foo" -> q=name_alias:"foo"

The function elastic.NewQueryStringQuery(q) didn't parse the query string into split fields.

Is there any function can do this?

### Any steps to reproduce the behavior?

elastic.NewQueryStringQuery(`name:"foo"`)

**Comment by olivere** [comment]
This library is for interacting with Elasticsearch directly. If you need to modify the query string before sending it to Elasticsearch, you have to do so in your code.

As to the `NewQueryStringQuery` (and other questions regarding usage), feel free to browse the tests. [Here are the tests](https://github.com/olivere/elastic/blob/release-branch.v7/search_queries_query_string_test.go) for `NewQueryStringQuery`.
