### ISSUE TITLE
IntervalQueryRulePrefix Source is wrong. Needs "prefix" instead of "query"

### ISSUE THREAD

**Issue by martinrode** [olivere/elastic#1566]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

```
{
    "prefix": {
         "prefix": "horst"
    }
}
```

### Please describe the actual behavior

```
{
    "prefix": {
         "query": "horst"
    }
}
```
Results in:

[{\"root_cause\":null,\"type\":\"x_content_parse_exception\",\"reason\":\"[1:551] [prefix] unknown field [query]\"}]]

### Any steps to reproduce the behavior?

```
elastic.NewIntervalQueryRulePrefix("horst").Source()
````

**Comment by olivere** [comment]
Thanks for reporting. Will be fixed in the next release.
