### ISSUE TITLE
[Question]Is there any way to show the request body in debug mode?

### ISSUE THREAD

**Issue by Rorke76753** [olivere/elastic#1567]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[T] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
I've tried 
```
elastic.NewClient(
...,
elastic.SetTraceLog(log.New(bytes.NewBuffer([]byte{}),"es-trace",9200)),
)
```
but i could not find the log, the log files or console, where did it print at?

**Comment by olivere** [comment]
If you are doing ...

```go
elastic.SetTraceLog(log.New(bytes.NewBuffer([]byte{}),"es-trace",9200)),
```

... you are effectively capturing the output in the `bytes.NewBuffer([]byte{})` which you don't have a reference to. If you simply want to see the output on the screen, you can do ...

```go
elastic.SetTraceLog(log.New(os.Stdout,"",0)),
```

If you want to capture the output for later, you need to e.g. create a buffer and use it later.

```go
var buf bytes.Buffer
...
elastic.SetTraceLog(log.New(&buf,"",0)),
...
// Use buf here
```
