### ISSUE TITLE
[Question]Is there any way to just show the request body

### ISSUE THREAD

**Issue by Xwudao** [olivere/elastic#1568]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ - ] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

Because the response content is so big in my scene, it override the `request body` in terminal screen.

**Comment by olivere** [comment]
You mean, when enabling the trace log? I mean, there might be a way, but tbh: The trace log is for debugging. When debugging, you want to see everything happening on the wire, including the request and the response with all its details. Then you fix the issue, and disable trace logging again.

If you want to have some other kind of requirement for logging, you're probably better of using your own [HTTP transport](https://github.com/olivere/elastic/wiki/HttpTransport). You can output the HTTP request and response details with [`net/http/httputil.DumpRequest(Out)`](https://pkg.go.dev/net/http/httputil#DumpRequest) and [`net/http/httputil.DumpResponse`](https://pkg.go.dev/net/http/httputil#DumpResponse) and friends.
