### ISSUE TITLE
Nested query question

### ISSUE THREAD

**Issue by firstrow** [olivere/elastic#157]
Hello. How can I perform query line this:
``` go
query := elastic.NewTermsQuery("Tags", tags...).MinimumShouldMatch(MINIMUM_TAG_MATCH)
query2 :=  elastic.NewTermQuery("Active", true)
```

**Comment by olivere** [comment]
I'm not sure I understand. You pass the query to the `Search` service via the `Query` func. If you want to combine queries, you can do so by e.g. using a [BoolQuery](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/query-dsl-bool-query.html).

**Comment by olivere** [comment]
Or do you want a [Nested Query](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/query-dsl-nested-query.html)?

**Comment by firstrow** [comment]
Yes! I mean - how to combine queries?

**Comment by firstrow** [comment]
Like this example code:
query1 := elastic.NewTermsQuery("Tags", tags...).MinimumShouldMatch(MINIMUM_TAG_MATCH)
query2 :=  elastic.NewTermQuery("Active", true)
query := elactic.NewNestedQuery().Add(q1).Add(q)

**Comment by olivere** [comment]
The [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/index.html) is very good. Read the section about [queries](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/query-dsl.html), e.g. [`BoolQuery`](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/query-dsl-bool-query.html). Then look up the tests, e.g. [`search_queries_bool_test.go`](https://github.com/olivere/elastic/blob/release-branch.v2/search_queries_bool_test.go) if you're unsure about the exact syntax.

**Comment by firstrow** [comment]
Thanks for link. https://github.com/olivere/elastic/blob/release-branch.v2/search_queries_bool_test.go

**Comment by olivere** [comment]
Tests are your friend. :-)
