### ISSUE TITLE
how to handle error "elastic: uncommitted bulk response items" in bulk process

### ISSUE THREAD

**Issue by seanjoe** [olivere/elastic#1571]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[*] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
no error or how to handle the error

### Please describe the actual behavior
purge 100 items failed, err is "elastic: uncommitted bulk response items"

### Any steps to reproduce the behavior?
the request setting such as:
FlushInterval 10s
BulkActions 100
BulkSize -1

sometime it response the error as title mentioned, did I must handle the error and how to process the error ?
or maybe ignore it?

**Comment by olivere** [comment]
The error you're mentioning is [`ErrBulkItemRetry `](https://github.com/olivere/elastic/blob/b7de00ddfd128672eac82ef8f6e938bcbb6c2cd4/bulk_processor.go#L17-L19):

```go
// ErrBulkItemRetry is returned in BulkProcessor from a worker when
// a response item needs to be retried.
ErrBulkItemRetry = errors.New("elastic: uncommitted bulk response items")
```

It largely depends on your use case. Elastic is just a library to work with ES. It's up to you to use it wisely. If you can't lose data, you should probably retry. If you can lose data, you can ignore it. In general: If you need more control over the indexing process, use the Bulk Index API directly, not the Bulk Processor.

**Comment by seanjoe** [comment]
Yeah, thanks your patient answer!
