### ISSUE TITLE
How to build a query like this ? 

### ISSUE THREAD

**Issue by minr** [olivere/elastic#1573]
[ x ] elastic.v6 (for Elasticsearch 6.x)

```json
{
	"query": {
		"bool": {
			"must": [{
				"term": {
					"namex": "ok"
				}
			}, {
				"term": {
					"is_locked": "true"
				}
			}],
			"must_not": [{
				"term": {
					"uid": "1"
				}
			}]
		}
	}
}
```

But in Code...

```golang
boolQuery := elastic.NewBoolQuery()

	boolQuery.Must(elastic.NewTermQuery("name", "ok")).
		Must(elastic.NewTermQuery("locked", true)).
		MustNot(elastic.NewTermQuery("uid", 1))

	source, _ := boolQuery.Source()
	j, _ := json.Marshal(source)
	fmt.Println(strutil.Byte2string(j))
```

Results:

```json
{
	"bool": {
		"must": [{
			"term": {
				"name": "ok"
			}
		}, {
			"term": {
				"locked": true
			}
		}],
		"must_not": {
			"term": {
				"uid": 1
			}
		}
	}
}
```

so , my code not working!

**Comment by minr** [comment]
es return this:

```json
{
"error": {
"root_cause": [
{
"type": "parsing_exception",
"reason": "Unknown key for a START_OBJECT in [bool].",
"line": 1,
"col": 9
}
],
"type": "parsing_exception",
"reason": "Unknown key for a START_OBJECT in [bool].",
"line": 1,
"col": 9
},
"status": 400
}
```

**Comment by olivere** [comment]
Your code is building a Query, but you're sending that query directly, not through the Search API. Please learn about the [Search API here](https://www.elastic.co/guide/en/elasticsearch/reference/current/search.html) and the [Query DSL here](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html).

There is a myriad of examples in the tests and the recipes folder, e.g. [this snippet](https://github.com/olivere/elastic/blob/release-branch.v7/recipes/text_vs_keyword/main.go#L165-L184).
