### ISSUE TITLE
Support for _source endpoint to get only the source

### ISSUE THREAD

**Issue by mitar** [olivere/elastic#1579]
### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

I would like to query [`_source`](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-get.html#_source) endpoint, which is similar to `_get` endpoint, just that it returns source of the document only.

### Please describe the actual behavior

I do not see it supported anywhere in the code?

**Comment by olivere** [comment]
Yeah, it's a nice to have. But yeah, it's missing.

**Comment by protiumx** [comment]
hi @olivere !
is there any new on this or any way to add `_source` to the final URL?

**Comment by olivere** [comment]
@protiumx This library is deprecated for a number of reasons. For a more detailed history about this decision, [read this issue](https://github.com/olivere/elastic/issues/1533). The way to go is to use [the official Elasticsearch library](https://github.com/elastic/go-elasticsearch) offered by Elastic.
