### ISSUE TITLE
is there CountService a method to set Routing?

### ISSUE THREAD

**Issue by foreversmart** [olivere/elastic#158]
I found the v2 countService have not a method named Routing()
![image](https://cloud.githubusercontent.com/assets/8978295/10932054/5cfc2276-8308-11e5-853d-0d5883fb3838.png)

**Comment by olivere** [comment]
Yep. According to the [API spec](https://github.com/elastic/elasticsearch/blob/1.7/rest-api-spec/api/count.json), there are a lot of other properties as well. Will update.

**Comment by foreversmart** [comment]
can you update this property as soon as possible?  This property is very important for me now, thank you very much~

**Comment by olivere** [comment]
I'm on it. But remember: This is an open source project! I do it in my spare time.

**Comment by foreversmart** [comment]
yes, thanks a lot.

**Comment by olivere** [comment]
I just pushed v2.0.17.

**Comment by foreversmart** [comment]
you are awesome fast! thank you very very much~
