### ISSUE TITLE
Unable to use multiple clients of different version like v3 and v5 in same application

### ISSUE THREAD

**Issue by madhurpgarg** [olivere/elastic#1583]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ x ] elastic.v5 (for Elasticsearch 5.x)
[ x ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
I am using v5 client and v3 client together on same application since I have the use case where I have to send the data to the search clusters of different version. I'm expecting that it should work because I have kept a map of client object and using the specific version of client based on the request.
@olivere can you please shed some light on this as this is kind of urgent thing. Also, let me know if there is any work around to achieve this.

### Please describe the actual behavior
Data for cluster A(version 2.x) is getting updated but the which is supposed to go to Cluster B(version 5.x) is not getting updated, even there is no log which says about any failure. I am using bulk processor.

### Any steps to reproduce the behavior?
Just use two different version client objects (e.g. v3 and v5) and then send some data using v3 client and some data using v5.

**Comment by olivere** [comment]
Versions other than 6.x and 7.x are no longer supported. Furthermore, versions before 7.x do not support Go modules.

You can solve it by using a different approach. [Here's an example](https://github.com/olivere/esdiff/tree/master/elastic).
