### ISSUE TITLE
Incorect documentation for DeleteByQueryService.ProceedOnVersionConflict

### ISSUE THREAD

**Issue by milesich** [olivere/elastic#1586]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
> ProceedOnVersionConflict aborts the request on version conflicts.

It should say it will not abort on version conflicts.

### Please describe the actual behavior
In: `https://github.com/olivere/elastic/blob/release-branch.v7/delete_by_query.go#L195`

> ProceedOnVersionConflict aborts the request on version conflicts.

**Comment by olivere** [comment]
Yep. Thanks.
