### ISSUE TITLE
No way to configure deprecationlog

### ISSUE THREAD

**Issue by mitar** [olivere/elastic#1588]
### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

I would like to be able to configure `deprecationlog`. I would like to configure it so that it does not use error level logger but a warning level logger. Moreover, I would like to adapt it so that it prints a warning only once during lifetime of a program and not on every request (if warning is the same as already issued).

### Please describe the actual behavior

This is not possible, unless one uses `NewSimpleClient`.

**Comment by olivere** [comment]
You can do so by writing your own `http.RoundTripper` like mentioned [here](https://github.com/olivere/elastic/wiki/HttpTransport).

If you want, use the code [here](https://github.com/olivere/elastic/blob/release-branch.v7/setup_test.go#L328-L340) as a base for your implementation. However, I'm not willing to open up the code for deprecation logging because then I have to support it.

**Comment by mitar** [comment]
The problem is that `deprecationlog` is a private field. If it was exported, then sure, I could set it myself to something.

I am not sure how `http.RoundTripper` could help here, unless I would inspect headers of every response and remove deprecation warnings before passing them on, but that seems a bit overkill approach to this?

**Comment by olivere** [comment]
As I said, it is a private field as I want to make sure nobody uses it. If it were public, I had to support it.

Doing your own `http.RoundTripper` allows you to do the same as I did with deprecation warnings, alas it is _your_ code, not mine.

**Comment by mitar** [comment]
> Doing your own `http.RoundTripper` allows you to do the same as I did with deprecation warnings, alas it is your code, not mine.

I see. I didn't realize that current warnings are already implemented using `http.RoundTripper`.
