### ISSUE TITLE
Opinions on error messages returned

### ISSUE THREAD

**Issue by superman0987** [olivere/elastic#1592]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
Before I begin, thank you for this exceptional library. It really is the best ES client out there.

Coming to my query, I have noticed, that there is a particular way that this library sends errors back from ES.
Say I get this error back from a search query: 

> Error 404 (Not Found): all shards failed [type=search_phase_execution_exception]

The query used would be something like this:
```
{
  "pit": {
    "id": "somepitgeneratedbeforequerying"
  },
  "query": {
    "bool": {
      "must": [
        {some clauses}
      ],
      "must_not": [
        {some clauses}
      ]
    }
  },
  "size": 10000,
  "sort": [
    {
      "_score": {
        "order": "desc"
      }
    }
  ]
}
```

The error that I managed to replicate in Kibana is:
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "search_context_missing_exception",
        "reason" : "No search context found for id [3719708]"
      },
      {
        "type" : "search_context_missing_exception",
        "reason" : "No search context found for id [5195350]"
      },
      {
        "type" : "search_context_missing_exception",
        "reason" : "No search context found for id [4904017]"
      },
      {
        "type" : "search_context_missing_exception",
        "reason" : "No search context found for id [4904018]"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "materialsprod",
        "node" : "u2J1DipKRrqje2BYxgBkgg",
        "reason" : {
          "type" : "search_context_missing_exception",
          "reason" : "No search context found for id [3719708]"
        }
      },
      {
        "shard" : 0,
        "index" : "materialsprod2",
        "node" : "VGRx0LwmQfOhGyv3ii1xYw",
        "reason" : {
          "type" : "search_context_missing_exception",
          "reason" : "No search context found for id [5195350]"
        }
      },
      {
        "shard" : 1,
        "index" : "materialsprod",
        "node" : "J6rvHXRQRY2nKCdxmqB9ng",
        "reason" : {
          "type" : "search_context_missing_exception",
          "reason" : "No search context found for id [4904017]"
        }
      },
      {
        "shard" : 1,
        "index" : "materialsprod2",
        "node" : "J6rvHXRQRY2nKCdxmqB9ng",
        "reason" : {
          "type" : "search_context_missing_exception",
          "reason" : "No search context found for id [4904018]"
        }
      }
    ]
  },
  "status" : 404
}
```

### Please describe the actual behavior
So, I would expect the full error returned right? But I just get the "Error 404 (Not Found): all shards failed [type=search_phase_execution_exception]" back. 

My point being, I spent two days trying to figure out in production, what the issue really is. Finally from Kibana I was able to understand what my issue actually is. The PIT expired, so, this error is returned.

Would it be something you plan to do in the future, returning the whole error?
Because from the error returned by the library I would never really know what went wrong.

Thanks in advance!

**Comment by olivere** [comment]
That's unfortunate. I'm sorry.

If there is an error, you can get access to all details by type checking for [`*elastic.Error`](https://github.com/olivere/elastic/blob/release-branch.v7/errors.go#L66-L70).

Notice that there are also quite some [error helpers in `errors.go`](https://github.com/olivere/elastic/blob/release-branch.v7/errors.go#L112-L153).

**Comment by superman0987** [comment]
Hi @olivere  it's ok.

Will it be possible for you to show some snippet or way to do it, please?
>If there is an error, you can get access to all details by type checking for [*elastic.Error](https://github.com/olivere/elastic/blob/release-branch.v7/errors.go#L66-L70).

**Comment by superman0987** [comment]
I got a good one by you here [https://github.com/olivere/elastic/wiki/Errors](url)
Thanks.
