### ISSUE TITLE
SeqNoAndPrimaryTerm vs. SeqNoPrimaryTerm

### ISSUE THREAD

**Issue by mitar** [olivere/elastic#1593]
### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

There seems to be inconsistency how `SeqNoAndPrimaryTerm` is named between services. Sometimes is `SeqNoAndPrimaryTerm` (`SearchSource`) and sometimes is `SeqNoPrimaryTerm` (`SearchService`). I would expect them to be the same.

**Comment by olivere** [comment]
I would expect so as well. However, we're just mirroring what the server does. See [here](https://github.com/elastic/elasticsearch/blob/ed5fc8bdb343fa27a23ccb2b91d6bf6bd28cc999/server/src/main/java/org/elasticsearch/search/builder/SearchSourceBuilder.java#L83). The correct naming would be `seqNoAndPrimaryTerm` though.
