### ISSUE TITLE
searchResult.aggregations  be short of kibina excute result

### ISSUE THREAD

**Issue by jinjiang2009** [olivere/elastic#1594]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x) v7.0.22
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
SearchResult.aggregations  equal kibina's result

### Please describe the actual behavior
SearchResult.aggregations less 1 or 2 record. But sometime they are equal. I don't understand

### Any steps to reproduce the behavior?
When a lot of aggregations result return, it come out.

**Comment by olivere** [comment]
I'm not sure I understand. Can you please write a test to illustrate your issue?

**Comment by jinjiang2009** [comment]
1. The es query  in Kibana Developer Tools 50000 records; but the oivere/elastic client only return 49998 records. Maybe it's my fault, i close the question first. If i found later, i'll tell you more.
