### ISSUE TITLE
elastic OpenPointInTime have error: request body is required

### ISSUE THREAD

**Issue by wednesdaysunny** [olivere/elastic#1595]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)

the code is at pit_test.go, and the test function is TestPointInTimeOpenAndClose.

When I run test, it report request body is required

**Comment by olivere** [comment]
I'm not sure I understand. I just tried to run that test, and it succeeded.

```go
$ go test -v -run=PointInTimeOpenAndClose
=== RUN   TestPointInTimeOpenAndClose
--- PASS: TestPointInTimeOpenAndClose (0.76s)
PASS
ok  	github.com/olivere/elastic/v7	0.906s
```
