### ISSUE TITLE
Mocks for client.go

### ISSUE THREAD

**Issue by alaukiknpant** [olivere/elastic#1596]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ X] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

Are there any mocks available for client.go for unit testing?

### Please describe the actual behavior

There are no mocks that I see for client.go.

**Comment by olivere** [comment]
When I do mocking, I do so at a higher level like [described here](https://github.com/olivere/elastic/wiki/Testing).

If I want to do integration tests, it works quite nice with the [`dockertest` library](https://github.com/ory/dockertest).

**Comment by alaukiknpant** [comment]
Thank you!
