### ISSUE TITLE
Debug logging

### ISSUE THREAD

**Issue by superman0987** [olivere/elastic#1598]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
Just wanted to know if there is a way to enable debug logging in this client?

**Comment by olivere** [comment]
Yes. You probably want to enable trace logging. It's [described in the Wiki](https://github.com/olivere/elastic/wiki/Logging).

**Comment by superman0987** [comment]
Thank you @olivere! I was able to enable it and print them on the terminal. One more question, Will these be a way to route these logs to our elasticsearch deployment's Logs and Metrics?

**Comment by olivere** [comment]
You can capture the logs. It's just an `io.Writer` anyway. As for metrics/instrumentation, you can can use [tracing](https://github.com/olivere/elastic/wiki/Tracing).

**Comment by superman0987** [comment]
Thanks @olivere do you have any code snippets for the Tracing part? Like how to do it from an application.

**Comment by olivere** [comment]
It's no longer up-to-date, but the Wiki mentions this recipe: https://github.com/olivere/elastic/tree/release-branch.v6/recipes/tracing

Other than that, it's pretty simple. This library is basically a HTTP client, so all articles and blog posts about tracing and instrumentation regarding HTTP clients should apply. AFAICT the OpenTelemetry is the current go-to solution: https://opentelemetry.io

**Comment by superman0987** [comment]
Hi @olivere but I'm still a bit confused as to how to do tracing, on the logs that we get from elasticsearch via the SetInfoLog, SetTraceLog or SetErrorLog functions. 

For example,
`client, err := elastic.NewClient(
                elastic.SetErrorLog(log.New(os.Stdout, "ERROR: ", log.Ldate|log.Ltime|log.Lshortfile)),
                elastic.SetTraceLog(log.New(os.Stdout, "DEBUG: ", log.Ldate|log.Ltime|log.Lshortfile)),
		elastic.SetInfoLog(log.New(os.Stdout, "INFO: ", log.Ldate|log.Ltime|log.Lshortfile)),
		elastic.SetInfoLog(wrappedLogger),
		elastic.SetURL(elasticSearchURL),
		elastic.SetHttpClient(httpClient),
		elastic.SetSniff(false),
		elastic.SetHealthcheck(false)
)
`

In this code, how do I make sure telemetry happens?

**Comment by olivere** [comment]
Tracing and logging are two different things. What you're doing above is logging. Tracing is a way to monitor the execution of your application while it is running. E.g. how much time does your the application spend in searching, how is the throughput of your bulk indexing process etc.

I think the [docs on OpenTelemetry](https://opentelemetry.io/docs/) aren't that bad if you need an idea of how to do tracing. Here's a detailed [example for Go](https://opentelemetry.io/docs/instrumentation/go/getting-started/).

As for Elastic, it is typically done by [passing your own `http.Transport`](https://github.com/olivere/elastic/blob/release-branch.v6/recipes/tracing/tracing.go#L86) that is being watched by OpenTelemetry. I don't have code for OpenTelemetry in the library, but I'm sure someone has already done that. And even if you cannot find it, it's rather simple to implement yourself.

**Comment by superman0987** [comment]
Thanks @olivere will look into it
