### ISSUE TITLE
Error logging doesn't work

### ISSUE THREAD

**Issue by superman0987** [olivere/elastic#1599]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
Error logging should work.

### Please describe the actual behavior
Error logging doesn't work, even though Info and Trace logging work.

### Any steps to reproduce the behavior?

Here is the code snippet I use to create the client.

`client, err = elastic.NewClient(
		elastic.SetErrorLog(log.New(os.Stderr, "ERROR: ", log.Ldate|log.Ltime|log.Lshortfile)),
		// elastic.SetInfoLog(log.New(os.Stdout, "INFO: ", log.Ldate|log.Ltime|log.Lshortfile)),
		elastic.SetTraceLog(log.New(os.Stdout, "DEBUG: ", log.Ldate|log.Ltime|log.Lshortfile)),
		elastic.SetURL(elasticSearchURL),
		elastic.SetHttpClient(httpClient),
		elastic.SetSniff(false),
		elastic.SetHealthcheck(false))`

I am simulating an error and using the _count API to create a request and then get error. Following are the lines of debugging I get when i enable SetTraceLog

DEBUG: 2022/03/15 21:29:27 client.go:854: HTTP/2.0 400 Bad Request
Content-Type: application/json; charset=UTF-8
Date: Tue, 15 Mar 2022 15:59:27 GMT
X-Cloud-Request-Id: <some request id>
X-Elastic-Product: Elasticsearch
X-Found-Handling-Cluster: <cluster id>
X-Found-Handling-Instance: instance-0000000010

{"error":{"root_cause":[{"type":"too_complex_to_determinize_exception","reason":"too_complex_to_determinize_exception: Determinizing automaton with 63096 states and 63097 transitions w
ould require more than 10000 effort."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"mater
ials_with_meta_cache_uat","node":"im hiding the node id","reason":{"type":"query_shard_exception","reason":"failed to create query: Determinizing automaton with 63096 states and 63097
 transitions would require more than 10000 effort.","index_uuid":"hiding the index uuid","index":"materials_with_meta_cache_uat","caused_by":{"type":"too_complex_to_determinize_except
ion","reason":"too_complex_to_determinize_exception: Determinizing automaton with 63096 states and 63097 transitions would require more than 10000 effort."}}}],"caused_by":{"type":"too
_complex_to_determinize_exception","reason":"too_complex_to_determinize_exception: Determinizing automaton with 63096 states and 63097 transitions would require more than 10000 effort.
"}},"status":400}

So, meaning, the SetTraceLog works. Likewise, SetInfoLog works too, prints logs to the terminal.
But SetErrorLog doesn't work. I have tried logging it to os.Stderr, os.Stdout, both cases nothing logged when I simulate the error.

Is there anything I'm missing here?

Thanks in advance!

**Comment by superman0987** [comment]
@olivere any idea why this happens? Can you check if this is a known issue, please! Thanks!

**Comment by olivere** [comment]
You can check yourself, just look at the source code.

There are quite a few calls to the `errorf` function (which is the internal function to write to the error log) [in e.g. `PerformRequest`](https://github.com/olivere/elastic/blob/release-branch.v7/client.go#L1303-L1510). Maybe your request didn't cause it to write to the log. If that is true, we can discuss whether it should've written to the log or not. But it's not that nothing is ever written to the error log.

Don't get me wrong. It's hard and time consuming to answer these open questions. I'm still doing this in my spare time, you know.

**Comment by superman0987** [comment]
Yeah could be , I will be checking that.
> Maybe your request didn't cause it to write to the log

I understand, however if some issue arises, you are the only point of reference for me.
> I'm still doing this in my spare time, you know

**Comment by superman0987** [comment]
By the way I found the line where the issue happens: [this](https://github.com/olivere/elastic/blob/acdec24dbb5e881adc02a1c6ad6f9333eed8d7b3/client.go#L1484)

Here is where my code gets the errors. So meaning, there is error with status 400, and the error is something like shards failed or somethings, whatever it is, the point being, the library is not logging the error in the referenced block of code, right. That is why I didn't get the errors logged either. Is there any reason for not logging the error as error log (like you said, with the errorf function call)?  @olivere

**Comment by superman0987** [comment]
@olivere Can we please talk about this?
