### ISSUE TITLE
Implement Pipeline Aggregations

### ISSUE THREAD

**Issue by vinaykr** [olivere/elastic#160]
Hi,

Are there any plans to implement pipeline aggregations that are supported in elasticsearch 2.0?

Thanks for the great library!

**Comment by olivere** [comment]
Actually they are already: In gopkg.in/olivere/elastic.v3 (see release-branch.v3).

**Comment by vinaykr** [comment]
oh wow. Thanks a lot Olivere!

**Comment by olivere** [comment]
There might be some bugs as its not thoroughly tested. Let me know when you find them ;-)
