### ISSUE TITLE
Alias Exists or not

### ISSUE THREAD

**Issue by superman0987** [olivere/elastic#1603]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
Have some API that can be used to check if alias exists or not.

### Please describe the actual behavior
Could not find any such functions or methods.

Again, this is not an issue. Just a query. Is there any code written around this? Or is it not possible to find out if alias exists. No problem either way, just want to know before proceeding with my work.

**Comment by olivere** [comment]
There is `HasAlias` on the response of the Get Aliases API (see [example code here](https://github.com/olivere/elastic/blob/release-branch.v7/indices_get_aliases_test.go#L201-L204)). AFAIK there is no API to check if an alias exists directly, just [these Alias APIs](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/aliases.html).
