### ISSUE TITLE
source()  should add nil check 

### ISSUE THREAD

**Issue by Y-Matin** [olivere/elastic#1608]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

**Comment by olivere** [comment]
I'm sorry. This issue doesn't describe the problem in a way that I can investigate.
