### ISSUE TITLE
how to use NewGeoDistanceSort for search closest store for a specified location ?

### ISSUE THREAD

**Issue by willywartono14** [olivere/elastic#1609]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)

### Please describe the expected behavior

I want to get the data of all the nearest store

### Please describe the actual behavior

got error 
Error 400 (Bad Request): all shards failed [type=search_phase_execution_exception]

### Any steps to reproduce the behavior?

>  query := elastic.NewBoolQuery()
> 	sort := elastic.NewGeoDistanceSort("location").
> 		Point(106.4552, -6.3346).
> 		Order(true).
> 		Unit("km")
> 
> 	searchResult, err := elasticClient.Search().
> 		Index("indexname").
> 		Type("typename").
> 		Query(query).
> 		Size(5).
> 		SortBy(sort).
> 		Do(ctx)

- My Data looks like :
> _source" : {
>            "out_code" : "000",
>           "location" : {
>             "lon" : -6.2346,
>             "lat" : 106.5552
>           }
>         }

is there anything that i should add to that code ? 
i got the sample code from https://github.com/olivere/elastic/issues/351#issuecomment-245294717

**Comment by olivere** [comment]
I'm sorry I can't help with all questions about queries. The general approach that works is:

1. Read the tests. They typically have enough examples to illustrate how to achieve something.
2. When you know the output you want, go from the outside in, not from the inside out. That is, start with a small fraction of your query and build your way up from there.
3. Don't write everything in a single, huge line of DSL. Start small, then stick things together. Once you've achieved what you want, you can refactor. Make it work, then make it nice.

**Comment by willywartono14** [comment]
> query := elastic.NewBoolQuery()
> sort := elastic.NewGeoDistanceSort("location").
> Point(-6.24543, 106.63595).
> Order(true).
> Unit("km")
> 
> searchResult, err := elasticClient.Search().
> Index("indexname").
> Type("typename").
> Query(query).
> Size(5).
> SortBy(sort).
> Do(ctx)

Oh im sorry, Its Works, im only misplaced Latitude and Longitude value.
Thank you for your Response.
