### ISSUE TITLE
FetchSourceContext uses wrong fields for source filtering

### ISSUE THREAD

**Issue by R4CHI7** [olivere/elastic#161]
Hi!

The *FetchSourceContext* uses **includes** and **excludes** as fields in the source field. But, the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/search-request-source-filtering.html) says the fields are **include** and **exclude**, respectively.

Is this a valid issue? Or am I missing something here?

**Comment by olivere** [comment]
Hi! I'm using the Java source as reference, not the documentation. So it might be just okay as is, but I cannot check because I'm not at a laptop right now. Will check later.

Did you get an exception or unexpected results?

**Comment by R4CHI7** [comment]
Yep, I am getting this error:

*elastic: Error 400 (Bad Request): ElasticsearchParseException[unexpected token while parsing source settings]*

I changed the keys to **include** and **exclude** in my local fetch_source_context.go, and it works like a charm! :blush:

**Comment by olivere** [comment]
Can you post a test case please?

**Comment by R4CHI7** [comment]
Hi.

Not exactly a unit test. Just a short code I could write in a short period of time.

Use the data from [here](http://joelabrahamsson.com/elasticsearch-101/#searching) to populate.

I wrote the following code to illustrate the issue:

```
package main

import (
	"fmt"
	"gopkg.in/olivere/elastic.v2"
)

func main() {
	indexName := "movies"
	typeName := "movie"

	fields := []string{
		"title",
		"year",
		"genre",
	}

	fetchContext := new(elastic.FetchSourceContext)
	fetchContext.SetFetchSource(true)
	fetchContext.Include(fields...)

	client, err := elastic.NewClient()
	if err != nil {
		fmt.Println(err.Error())
	}

	multiGetService := client.MultiGet()
	item := new(elastic.MultiGetItem)
	item.Index(indexName).Type(typeName).Id("5").FetchSource(fetchContext)
	multiGetService.Add(item)

	res, err := multiGetService.Do()
	if err != nil {
		fmt.Println(err.Error())
	}
	fmt.Println(res)
}
```

I am getting the following output:

```
elastic: Error 400 (Bad Request): ElasticsearchParseException[unexpected token while parsing source settings]
<nil>
```

On the other hand, running the following curl command gives the correct output:

```
curl -XGET "http://localhost:9200/_mget" -d'
{"docs":[{"_id":"5","_index":"movies","_source":{"include":["title","year","genre"]},"_type":"movie"}]}'
```

I hope this illustrates the issue.

Thanks!

**Comment by olivere** [comment]
@R4CHI7 Just got the time to look into this.

Well, if you had used it like I hoped people do, everything would have worked fine ;-) The problem is that you created the `FetchSourceContext` yourself instead of using the proposed `NewFetchSourceContext` func:

```go
// Your code
fetchContext := new(elastic.FetchSourceContext)
fetchContext.SetFetchSource(true)
fetchContext.Include(fields...)

// Proposed way to use FetchSourceContext
fetchContext := elastic.NewFetchSourceContext(true)
fetchContext.Include(fields...)
```

Again, there's nothing wrong with doing it the way you did. `FetchSourceContext` is exported, so you could initialize yourself. And I could have prevented this situation, so it's my fault. I'm thinking about fixing this with a better solution in elastic.

**Comment by R4CHI7** [comment]
I think the issue is not with the way I initialized the object. The issue lies in the Source() method, which returns a map[string]interface{} in which the keys are returned as "includes" and "excludes".

Can you please check?

**Comment by olivere** [comment]
I wrote a little program to test, and it worked fine. You can test yourself.

```go
package main

import (
	"fmt"
	"log"
	"os"

	elastic "gopkg.in/olivere/elastic.v2"
)

func main() {
	client, err := elastic.NewClient(elastic.SetTraceLog(log.New(os.Stdout, "", 0)))
	if err != nil {
		panic(err)
	}

	indexName := "movies"
	typeName := "movie"

	fields := []string{
		"title",
		"year",
		"genre",
	}

	fetchContext := elastic.NewFetchSourceContext(true)
	//fetchContext.SetFetchSource(true)
	fetchContext = fetchContext.Include(fields...)
	//fetchContext.Exclude([]string{}...)

	multiGetService := client.MultiGet()
	item := new(elastic.MultiGetItem)
	item.Index(indexName).Type(typeName).Id("5").FetchSource(fetchContext)
	multiGetService.Add(item)

	res, err := multiGetService.Do()
	if err != nil {
		log.Print(err)
	}
	fmt.Println(res)
}
```

The [Java source](https://github.com/elastic/elasticsearch/blob/1.7/src/main/java/org/elasticsearch/search/fetch/source/FetchSourceParseElement.java#L72) accepts both `include` and `includes` as well as `exclude` and `excludes`.

**Comment by R4CHI7** [comment]
Oh! My bad! The issue was because of the null excludes! Should have used the *NewFetchSourceContext* method.

Thanks a ton! :blush:

**Comment by olivere** [comment]
You're welcome.
