### ISSUE TITLE
DeleteByQuery hangs for invalid query

### ISSUE THREAD

**Issue by pebbe** [olivere/elastic#162]
This program with a syntax error in the query hangs:
```go
package main

import (
    "gopkg.in/olivere/elastic.v3"
)

func main() {
    client, err := elastic.NewClient()
    if err != nil {
        panic(err)
    }

    _, err = client.DeleteByQuery(`{
            "query": {
                "filtered": {
                    "query": {
                        "match_all": { }
                    },
                    "filter": {
                        { "term": { "interval": -1 } }
                    }
                }
            }
        }`).
        Index("twitter20151101").
        Type("tweets").
        Do()

    if err != nil {
        panic(err)
    }
}
```

**Comment by pebbe** [comment]
Sometimes it hangs, sometimes it exists with the panic.

**Comment by olivere** [comment]
Sounds to me like an issue with Elasticsearch, not with the Go client. Which ES version are you using? Maybe you're suffering from one of the issues described here: https://www.elastic.co/blog/core-delete-by-query-is-a-plugin?!

**Comment by pebbe** [comment]
ES 2.0 with elastic version 3. No, I didn't have the plug-in.
Perhaps something to mention in the docs, that you should call `client.HasPlugin("delete-by-query")` first? And add the link you give to the docs also.

**Comment by pebbe** [comment]
Perhaps a better solution would be if DeleteByQuery returned an error if the plug-in is not installed.

**Comment by olivere** [comment]
@pebbe I see. Yes, documentation can always be better. I've written it up in the [CHANGELOG](https://github.com/olivere/elastic/blob/release-branch.v3/CHANGELOG-3.0.md#delete-by-query-api) for 3.0, but I understand that it's hard to find and the Wiki would have been a better place. Still struggling to find the time to enhance the Wiki.

However, I'm just a single developer and rephrasing all updates and docs written by the good guys at the Elastic documentation team is simply not possible. Therefore I rely on people reading the documentation for Elasticsearch (e.g. the [Breaking changes for 2.0](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-2.0.html)) and only then lean to elastic, trying to implement their solution in our favorite programming language.

Also notice the new [`SetRequiredPlugins`](https://github.com/olivere/elastic/blob/release-branch.v3/CHANGELOG-3.0.md#hasplugin-and-setrequiredplugins) configuration option in v3. It could be a useful option for your use case. It will check for the existence of a plugin at client creation time (btw you can achieve the same with a change to your [Elasticsearch configuration](https://www.elastic.co/guide/en/elasticsearch/plugins/2.0/_settings_related_to_plugins.html)):

```go
// Will raise an error if the "delete-by-query" plugin is NOT installed
client, err := elastic.NewClient(elastic.SetRequiredPlugins("delete-by-query"))
if err != nil {
  log.Fatal(err)
}
```

Your idea of returning an error if the `DeleteByQuery` plugin comes with a problem. If I do this with every usage of `DeleteByQuery`, elastic will end up sending an additional request to Elasticsearch for the "just in case" use case. I tend to not do that. I want to keep elastic a dumb (little) library whose sole purpose is to be a Go client for Elasticsearch. Elastic doesn't try to be smart.
