### ISSUE TITLE
Does this repository has a search after example?

### ISSUE THREAD

**Issue by wathenjiang** [olivere/elastic#1630]
# Does this repository has a search after example?

I was reluctant to ask questions here, but after trying googling I couldn't find the answer about how to use `search after` in [elastic](https://github.com/olivere/elastic).

And the docs is so confused, as the following:

```
// SearchAfter allows a different form of pagination by using a live cursor,
// using the results of the previous page to help the retrieval of the next.
//
// See https://www.elastic.co/guide/en/elasticsearch/reference/6.2/search-request-search-after.html
func (s *SearchService) SearchAfter(sortValues ...interface{}) *SearchService {
	s.searchSource = s.searchSource.SearchAfter(sortValues...)
	return s
}
```
The hyperlink is to elasticsearch docs, but not [elastic](https://github.com/olivere/elastic)'s docs.

**Comment by olivere** [comment]
There is an example in the tests here: https://github.com/olivere/elastic/blob/29ee98974cf1984dfecf53ef772d721fb97cb0b9/search_test.go#L1482

**Comment by wathenjiang** [comment]
Thank you a lot.

The `search after` will return `sort` field, then we will use `sort` field int the search after to execute the next search. 
How could I got `sort` field in [elastic](https://github.com/olivere/elastic)?

**Comment by wathenjiang** [comment]
The following way works for me, but is not elegant.

```
searchResult.Hits.Hits[len(searchResult.Hits.Hits)-1].Sort
```
But you'd better knew json result well in elasticsearch first.
