### ISSUE TITLE
how to express `GET alias_xxx/_alias?filter_path=index_name.aliases.alias_xxx` 

### ISSUE THREAD

**Issue by RaphaelL2e** [olivere/elastic#1632]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x ] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

GET alias_xxx/_alias?filter_path=index_name.aliases.alias_xxx

but may cant use olivere implement

### Please describe the actual behavior

i want  result this filter
```
{
  "indedx_name" : {
    "aliases" : {
      "alias_name" : {
        "filter" : {
          "bool" : {
            "filter" : [
              {
                
              }
            ]
          }
        }
      }
    }
  }
}
```

**Comment by olivere** [comment]
The API you need is `IndicesGetAliases`. Here's a [lot of code](https://github.com/olivere/elastic/blob/b7de00ddfd/indices_get_aliases_test.go) on how to work with that API. The `FilterPath` method is on the service [here](https://github.com/olivere/elastic/blob/b7de00ddfd128672eac82ef8f6e938bcbb6c2cd4/indices_get_aliases.go#L60-L64).

HTH.

**Comment by RaphaelL2e** [comment]
but i think IndicesGetAliases only return 
```
indexMap := make(map[string]struct {
		Aliases map[string]struct {
			IsWriteIndex bool `json:"is_write_index"`
		} `json:"aliases"`
	})
```
dont have my want filter body

**Comment by olivere** [comment]
That's what IndicesGetAliases returns IIRC. What API is that `GET alias_xxx/_alias` endpoint? Can you refer me to the documentation page on elastic.co?

**Comment by RaphaelL2e** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/7.17/indices-get-alias.html

**Comment by RaphaelL2e** [comment]
Maybe you confused 'indices_get_aliases' and 'indices_get_alias'

**Comment by olivere** [comment]
So the API is correct (the `indices_get_aliases.go` implements the endpoint you want). But you're missing part of the response?

**Comment by RaphaelL2e** [comment]
yes

**Comment by olivere** [comment]
Unfortunately, as the response is dynamic, all you can do is to use e.g. the `PerformRequest` method on the `Client` then and parse the body on your side.

**Comment by RaphaelL2e** [comment]
ok,thx
