### ISSUE TITLE
Is there a specific reason why this field is unexported?

### ISSUE THREAD

**Issue by itiulkanov** [olivere/elastic#1634]
Hello, I'm currently working on a task that requires some post processing after the request has been submitted to ES. The method is used in the after method, which receives the Bulk index request struct/ The doc field, which holds the values sent to the ES is unexported. I was wondering, how I can access the content of the ES request, besides the doc field? Is there an option to somehow access the doc value except using the reflect package? Any possibility to export the field in a future library update?   
https://github.com/olivere/elastic/blob/29ee98974cf1984dfecf53ef772d721fb97cb0b9/bulk_index_request.go#L29

**Comment by olivere** [comment]
The reason why it's not exported is that people start modifying it and expect the client to "magically" recognise the changes.

But I'm not sure I understand the use case. The `doc` is something that is passed into the bulk indexer by you, so you should be able to hold a reference to it. If you want more control over the bulk indexing process, you should probably use the Bulk API directly anyways.

**Comment by itiulkanov** [comment]
We have several ES clusters, and in case one of them fails to process the message, are willing to send the message to the DLQ, in the after method. Request returns the failed document, and I can even see all the values in the IDE, but I'm struggling to get the doc itself(

**Comment by olivere** [comment]
A tad of changes to [this recipe](https://github.com/olivere/elastic/blob/release-branch.v7/recipes/bulk_insert/bulk_insert.go) should give you the flexibility to do so (I hope).

**Comment by itiulkanov** [comment]
@olivere Just to make sure. Am I right, that currently is no way to somehow post-process the failed document sent to the index using the library if the cluster has failed for some reason or has been disconnected?
