### ISSUE TITLE
Why does elastic does only considers not an error HEAD && 404?

### ISSUE THREAD

**Issue by aanm** [olivere/elastic#164]
On this line:
https://github.com/olivere/elastic/blob/release-branch.v3/errors.go#L35
 
elastic is not considering the fact that a GET request can also return a 404. Is that considered an error? Why?

**Comment by olivere** [comment]
There's several use cases for that. E.g. when you check if a document exists via the `Exists` service, it is a vaild result for that service to return a 404 but that's not an error.

To find out the special cases, just uncomment the lines in the `errors.go` and run the tests via `go test`.

An alternative might have been to catch the specific kinds of "errors that are not errors" in the services.

**Comment by aanm** [comment]
@olivere I don't have anything against the `errors.go` itself. What I think it doesn't make sense is that the parameter used in `MaxRetries(int)` is used if a document doesn't exist. Shouldn't  `MaxRetries` only be used for TCP/IP errors? I was assuming, for example, when a server wasn't reachable for that request or if there was a communication error, `elastic` would retry to resend that request again.

**Comment by olivere** [comment]
Hmm... at second thought it makes sense for `PerformRequest` to only retry for HTTP status 500..599. Will have to think about it. That whole section of elastic is very ugly: No pluggable strategy (only round-robin), very stupid and simple exponential backoff etc.

**Comment by aanm** [comment]
I have a small piece of code that manually retries if something wasn't found in elasticsearch. I also have `MaxRetries` set to 10 so I was seeing way more requests than I was hopping for when something wasn't found.

**Comment by olivere** [comment]
Yep. Sounds like an error in elastic to me.

**Comment by olivere** [comment]
The official Python client [raises an error](https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/connection/http_requests.py#L76) for everything NOT in 200..299. The [official Ruby client](https://github.com/elastic/elasticsearch-ruby/blob/master/elasticsearch-transport/lib/elasticsearch/transport/transport/base.rb#L224) does log an error for HTTP status code > 300.

So I guess we'll have to do the same. I will probably find some time at the weekend for with a simple change, then it needs some testing.

**Comment by olivere** [comment]
... oh, and retrying only happens for "hard" errors: See [here](https://github.com/elastic/elasticsearch-ruby/blob/master/elasticsearch-transport/lib/elasticsearch/transport/transport/base.rb#L195).

**Comment by aanm** [comment]
@olivere Thanks!

**Comment by olivere** [comment]
Can you look into the [issue-164](https://github.com/olivere/elastic/tree/issue-164) branch and see if it fixes the retry issue?

Two significant changes there: First, `PerformRequest` now only retries when `HttpRequest.Do` returns an error. It only does so on HTTP protocol errors (see [documentation of `Do`](https://golang.org/pkg/net/http/#Client.Do)). Second, it refactors error handling for services that (correctly) accept 404 as a valid response and moves error handling into the service (away from `errors.go`).

Thanks.

**Comment by aanm** [comment]
@olivere yep. Now with https://github.com/olivere/elastic/tree/issue-164 I've the expected behavior. It was odd because on v2 elastic had a condition for 404 but not on this one.
Thanks for looking it up! :-)

**Comment by olivere** [comment]
@aanm I justed pushed version 3.0.4. A `go get -u gopkg.in/olivere/elastic.v3` should pick up the changes.

Thanks for reporting!
