### ISSUE TITLE
Too many dynamic script compilations within, max: [75/5m]

### ISSUE THREAD

**Issue by zenghao306** [olivere/elastic#1641]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
when i use v7.0.18 to update some record,this problem produced:
[script] Too many dynamic script compilations within, max: [75/5m]; please use indexed, or scripts with parameters instead; this limit can be changed by the [script.max_compilations_rate] setting
can you tell me how to solve this  problem?

**Comment by olivere** [comment]
This is typically due to a problematic script design. You can read about all of this in e.g. https://alexmarquardt.com/2020/10/21/elasticsearch-too-many-script-compilations/.
