### ISSUE TITLE
BulkProcessor ADD send on closed channel

### ISSUE THREAD

**Issue by cheaster062211** [olivere/elastic#1650]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[*] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

When using the bulkProcessor add function, under what circumstances will panic

**Comment by cheaster062211** [comment]
panic is send on closed channel What is the best posture to use bulkProcessor

**Comment by olivere** [comment]
There is a [working recipe here](https://github.com/olivere/elastic/blob/release-branch.v7/recipes/bulk_processor/main.go). Notice that you should move to the [official client](https://github.com/elastic/go-elasticsearch) ASAP.
