### ISSUE TITLE
Load balance between multiple master nodes

### ISSUE THREAD

**Issue by amirEBD** [olivere/elastic#1656]
### Which version of Elastic are you using?

elastic.v7 (for Elasticsearch 7.9)

### Please describe the expected behavior

As I give multiple master nodes to olivere client. what will happend? 
Will it balance the load between masters (coordinaitors) or just choose one of them at the very first connection and continue the rest of it?

**Comment by olivere** [comment]
By default, it will do round robin between the nodes that a) are identified during the Sniffing process (if enabled) or b) you specify at startup (if sniffing is disabled). You can read more about all these things in the [wiki](https://github.com/olivere/elastic/wiki).

In practice, you'd better leave load balancing up to DNS or Elasticsearch (by means of a dedicated coordinating node, I think).
