### ISSUE TITLE
TestClientWithBasicAuth fails

### ISSUE THREAD

**Issue by pebbe** [olivere/elastic#166]
I'm using Elasticsearch 2.0.0

I have installed shield. I have made a user `user` with password `secret`

I test with curl, this works:

```
$curl -XGET 'http://user:secret@127.0.0.1:9200/?pretty'
{
  "name" : "p209327",
  "cluster_name" : "kleiweg",
  "version" : {
    "number" : "2.0.0",
    "build_hash" : "de54438d6af8f9340d50c5c786151783ce7d6be5",
    "build_timestamp" : "2015-10-22T08:09:48Z",
    "build_snapshot" : false,
    "lucene_version" : "5.2.1"
  },
  "tagline" : "You Know, for Search"
}
```

But elastic fails:
```
$ go test -v -run TestClientWithBasicAuth gopkg.in/olivere/elastic.v3
=== RUN   TestClientWithBasicAuth
--- FAIL: TestClientWithBasicAuth (5.01s)
        client_test.go:124: no Elasticsearch node available
FAIL
exit status 1
FAIL    gopkg.in/olivere/elastic.v3     5.011s
```

**Comment by olivere** [comment]
Did you run the tests without any changes to it? Then the result is correct as the unit tests expect ES to be accessible without authentication. I'm afraid that you cannot run the tests with Shield enabled.

**Comment by olivere** [comment]
Oh, I see. You created a user/password for exactly the given test... :-)  Okay, will look into it...

**Comment by olivere** [comment]
@pebbe Thanks for reporting. I just pushed an update so that `go get -u gopkg.in/olivere/elastic.v3` should pick up the changes.

The problem was that while user requests successfully send HTTP basic auth, the administrative requests used with [sniffing](https://github.com/olivere/elastic/wiki/Sniffing) and [health checks](https://github.com/olivere/elastic/wiki/Healthcheck) didn't.

**Comment by olivere** [comment]
Backported to elastic.v2 as well (available in 2.0.18+).

**Comment by pebbe** [comment]
Thanks. It's working fine now.

**Comment by sndaergg** [comment]
how to connect elasticsearch(protected by shield) using gopkg.in/olivere/elastic.v3, any  example?

**Comment by pebbe** [comment]
@sndaergg see TestClientWithBasicAuth in client_test.go

**Comment by sndaergg** [comment]
my code as follow:
	es.client, err = elastic.NewClient(elastic.SetURL(url),
		elastic.SetBasicAuth("admin", "password"),
		elastic.SetMaxRetries(10))

but I got error:
no Elasticsearch node available
message from tcpdump: Response: Unauthorized
and I don't know why this error happened.

**Comment by olivere** [comment]
@sndaergg Can you please report the version of elastic you are using. It is somewhere in the first lines of `client.go`.

**Comment by sndaergg** [comment]
@olivere 
Version = "3.0.6"

tcpdump shows elastic will connect each node in cluster, but only one node export outside.
can I connect only one node in cluster? and How? Thanks!

**Comment by olivere** [comment]
@sndaergg Okay. 3.0.6 is the current version for ES 2.x.

If you only want to connect to one node of your cluster, you have to disable sniffing and set the URL manually. See the [Wiki](https://github.com/olivere/elastic/wiki/Configuration) for details. But it is almost always more beneficial to have clients use all nodes for load-balancing.

**Comment by sndaergg** [comment]
@olivere Ok, Thanks very much
