### ISSUE TITLE
Send GET body as POSTs

### ISSUE THREAD

**Issue by bbassingthwaite-va** [olivere/elastic#167]
Hey, I ran into an issue when using the multi get api. AppEngine doesn't allow sending a body on GET requests, which causes the multi get to fail. We made a change locally to the line https://github.com/olivere/elastic/blob/master/multi_get.go#L78 to `res, err := b.client.PerformRequest("POST", path, params, body)` from `res, err := b.client.PerformRequest("GET", path, params, body)`

In the official elasticsearch python library, they have a configuration `send_get_body_as='POST'` that allow you to configure how to send GET body's. Not sure if this is a configuration that could be added, or what you would suggest?

Maybe something like:
```go
client, err := elastic.NewClient(
  elastic.SendGetBodyAs("POST"),
)
```
?

**Comment by olivere** [comment]
Hi there. I've also seen this setting in (at least one of) the official clients. The [Rest API specification](https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/mget.json) allows both `GET` and `POST`. If official clients agree on this setting it'd make sense to add it to elastic as well.

I will have to check the official clients, look into the ES source, and find out which APIs would need to respect this setting. I hope I can get it done next weekend. If you like to help, have a go :-)

**Comment by olivere** [comment]
Seems like the official Python, Ruby, and Perl clients have `send_get_body_as`. So elastic will have it as well. Now I just need to find some time.

**Comment by bbassingthwaite-va** [comment]
I can put together a PR.

**Comment by olivere** [comment]
Thanks. BTW: You can probably fix this centrally in the PerformRequest function in client.go. Seems like a simple issue then.
