### ISSUE TITLE
issue between the elastic.v7 package and the easyjson

### ISSUE THREAD

**Issue by mamtaRaiTech** [olivere/elastic#1689]
The error message you're encountering indicates a compatibility issue between the elastic.v7 package and the easyjson dependency in your Go project. Specifically, the error:

bash
Copy code
/root/.go/pkg/mod/github.com/olivere/elastic/v7@v7.0.32/bulk_create_request_easyjson.go:31:13: in.UnsafeFieldName undefined (type *jlexer.Lexer has no field or method UnsafeFieldName)
suggests that the jlexer.Lexer type, used by easyjson, does not have the UnsafeFieldName method expected by the elastic.v7 package.

Recommendations:

Verify Dependency Versions:

Ensure that you're using compatible versions of elastic.v7 and easyjson. The elastic.v7 package has been deprecated in favor of the official Elasticsearch client for Go, go-elasticsearch. 
GITHUB
Consider updating to the latest versions of both dependencies to benefit from bug fixes and compatibility improvements.
Update go-elasticsearch:

The official Elasticsearch client for Go is go-elasticsearch. 
GO.DEV

This client is actively maintained and offers better support and compatibility with Elasticsearch.

To switch to go-elasticsearch, update your go.mod file:

go
Copy code
require (
  github.com/elastic/go-elasticsearch v8.0.0
)
Then, run go get to fetch the new dependency.

Refactor Code:

After updating to go-elasticsearch, refactor your code to use the new client's API.
The go-elasticsearch client provides a more straightforward and efficient way to interact with Elasticsearch.
Consult Documentation:

Review the official documentation for go-elasticsearch to understand its usage and features. 
OLIVERE
By updating to the official go-elasticsearch client and ensuring compatibility between your dependencies, you should be able to resolve the UnsafeFieldName error and improve the stability and maintainability of your project.

**Comment by olivere** [comment]
Yes. Please switch to the official client. This Elasticsearch client is no longer maintained.
