### ISSUE TITLE
Is NewFilteredQuery not supported in v3 ?

### ISSUE THREAD

**Issue by shwetaskatdare** [olivere/elastic#171]
Hi, I am using v3 of elastic client and trying to use filtered query. I don't seem to find it in v3. I've checked the documentation. Could someone point me in the right direction ?

**Comment by olivere** [comment]
Hi there. FilteredQuery is deprecated as of ES 2.0. You can use a BoolQuery instead. IIRC I laid out the details in CHANGELOG.md in the v3 branch. Can you have a look? (I'm on my iPhone with a shaky connection, sorry.)

**Comment by olivere** [comment]
Here's the [deprecation info of `FilteredQuery`](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_query_dsl_changes.html#_literal_filtered_literal_query_and_literal_query_literal_filter_deprecated) for 2.0 and an example of how to change things.

Notice that you can still use `FilteredQuery` in 2.0. So if your project is littered with `FilteredQuery` you can just copy the `FilteredQuery` implementation (see [`search_queries_filtered.go`](https://github.com/olivere/elastic/blob/release-branch.v2/search_queries_filtered.go)) from elastic.v2 and use it in v3. But as it'll be removed and v3 is already a major upgrade, I decided to remove it as well.

HTH
