### ISSUE TITLE
BulkService usage question?

### ISSUE THREAD

**Issue by jgoodall** [olivere/elastic#173]
Does anyone have a pattern for using the bulk indexer on unbounded streams? I have tried setting up a goroutine for doing the `Add()` as new messages come in on a channel and a separate goroutine to do the `Do()` when the `NumberOfActions()` is greater than some number, but I think what is happening is that adding new requests (with `Add()`) at the same time as the sending of the request (with `Do()`) causes a lot of the messages to get lost.

Should the [BulkService.requests](https://github.com/olivere/elastic/blob/master/bulk.go#L22) have a Mutex on it, or is there a successful pattern for periodically sending updates?

**Comment by olivere** [comment]
I usually set up a pool of workers that perform bulk requests to Elasticsearch. The pool is limited in size to ensure that ES doesn't get overloaded. It also does automatic retries if ES fails. However, I never separated the `Add` and the `Do` method in separate goroutines. Here's [a very simple version of it](https://gist.github.com/olivere/a6dc27ae961736721d2c). It's far from being perfect, of course.

In my use cases, the apps could generate documents much faster than ES could index. So the bottleneck was always ES, not my app. Hence there was no need to optimize for throughput on the application side. But YMMY.

**Comment by olivere** [comment]
I'm not sure what the condition for closing this issue is? Would you close the issue if your question has been answered or the issue has been resolved? Thanks.

**Comment by jgoodall** [comment]
Yes, this was very helpful. The problem I was having persisted though - namely if the bulk index size is, say 100, and you have 201 documents, there will be two bulk requests sent, but the last document will not get sent, because the 'queue' is not full. So I created a separate goroutine to periodically check if some time had elapsed before the last bulk send and send anything remaining. 

I am including some code here that uses the code from the gist to create the pool of workers - if this seems like a bad idea or there is a better way, maybe reopen the issue?

```go

func (es *Publisher) Open() (err error) {
  es.client, _ = elastic.NewClient(...)
  es.pool, _ = NewPool(es.numWorkers)
	es.responseCh = make(chan error)
	es.service = es.client.Bulk().Index(es.Index)
  // Check time to see if a while has gone past and commit to Pool if so.
  go func(es *Publisher) {
    for {
      if !es.lastSend.IsZero() && time.Since(es.lastSend) >= es.maxDuration {
        if es.service.NumberOfActions() > 0 {
          es.pool.Commit(es.service, es.responseCh)
          _ := <-es.responseCh
        }
      }
      time.Sleep(time.Second * 15)
    }
  }(es)
}

func (es *Publisher) Publish(in <-chan *SomeStruct) {
	for {
		msg := <-in
		es.service.Add(elastic.NewBulkIndexRequest().Id(msg.Uuid).Type(msg.Type).Doc(msg.Content))
		if es.service.NumberOfActions() >= es.maxDocs {
			es.lastSend = time.Now()
			es.pool.send(es.service, es.responseCh)
			_ := <-es.responseCh
		}
	}
}
```

**Comment by sundarv85** [comment]
@jgoodall Is your es.publisher package available for general use. I would like to use it, instead of reinventing the wheel.

**Comment by olivere** [comment]
@jgoodall @sundarv85 It seems like you guys need something like the [BulkProcessor](https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/java-docs-bulk-processor.html) from the Java API, is that right?

**Comment by sundarv85** [comment]
@olivere Yes, that will be perfect.

**Comment by olivere** [comment]
See #190 for work on a BulkProcessor.

**Comment by jgoodall** [comment]
Mine is pretty much the same as what @olivere posted in his gist initially.
