### ISSUE TITLE
and query

### ISSUE THREAD

**Issue by krzysztofantczak** [olivere/elastic#175]
Hi,

Since "And Query" is deprecated, how can i fetch documents where: foo == "bar" AND baz == "pop" using elastic.v3?

**Comment by olivere** [comment]
Use a [`BoolQuery`](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html) as described [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_query_dsl_changes.html#_literal_or_literal_and_literal_and_literal_now_implemented_via_literal_bool_literal).

**Comment by krzysztofantczak** [comment]
So, i shouldn't use Your library?

**Comment by olivere** [comment]
Why not? It supports all kinds of queries including BoolQuery. See the test files for example code.
