### ISSUE TITLE
Sort not working with scan/scroll

### ISSUE THREAD

**Issue by vsiv** [olivere/elastic#181]
Hi @olivere - Not sure if I am not using it correctly but with sort/scan and either a sorter or a sort field, I am getting empty results but without the sort, it works fine. FYI - the values are all integer 0's for now....

Any thoughts?

Thanks.
PS. using this way-
```
elastic.NewScanService(client).Indices(indices...).Types(iTypes...).Query(query).SortBy(sorters...)
```

**Comment by olivere** [comment]
@vishalshah-org Hmm... that seems strange. Using [scan and scroll](https://www.elastic.co/guide/en/elasticsearch/guide/current/scan-scroll.html) has huge performance benefits; iterating through large resultsets will be much faster if sorting is disabled. The `ScanService` tries to use this knowledge to enable `search_type=scan` automatically when there is no sort order specified. The Python client has the same behavior IIRC. Besides that, there shouldn't be any difference.

But of course there could be a bug somewhere. Can you [enable tracing](https://github.com/olivere/elastic/wiki/Logging) to see what's happening on the wire?

BTW: [ES 2.1 changes this behavior and deprecates `search_type=scan`](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_21_search_changes.html#_literal_search_type_scan_literal_deprecated). Are you on 1.x or 2.x?

**Comment by olivere** [comment]
@vishalshah-org Any updates on this?

**Comment by vishalshah-org** [comment]
@olivere Hi, sorry for the late reply. I am on 1.x. WIll post with tracing enabled.
Good to know about the performance benefits. I am trying to get all objects using scan/scroll because I dont know upfront how many exist - to set the right from-size. But there is the option of running a count query and then setting the right from/size. I am dealing with 100's of objects max, so a non scan/scroll query should suffice.

Will update soon. Currently on the road. Thanks.

**Comment by olivere** [comment]
@vishalshah-org Didn't mean to push you. Take your time. But sometimes people just forget about their issues.

Do **NOT** use from/size for pagination. Beware that 2.1 introduces a [limit on from/size](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/breaking_21_search_changes.html#_from_size_limits). They simply don't want you to paginate with from/size, and they're right.

Also: In [scroll-and-scan](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/search-request-scroll.html#scroll-scan) you can set a `size` parameter. However, it specifies how many results to return **per shard**.

**Comment by leokongwq** [comment]
Hi @olivere ：I am first used elastic，after i did "go get gopkg.in/olivere/elastic.v3" in cmd line, i did as example show, i meet the follow error。 i confused。

import cycle not allowed
package gopkg.in/olivere/elastic.v3
	imports gopkg.in/olivere/elastic.v3

Any thoughts?

thandks!

**Comment by olivere** [comment]
Whoops. Will check as soon as I'm back home...

**Comment by olivere** [comment]
@leokongwq Fixed it. Sorry.

**Comment by leokongwq** [comment]
Hi @olivere, It works, thanks !

**Comment by olivere** [comment]
@vishalshah-org Any news on this issue?

**Comment by vishalshah-org** [comment]
@olivere sorry for the delayed response. I turned on trace debugging. I don't see anything interesting in the trace logs. Just a bunch of 200 OKs.

Here are couple trace log [files](https://www.dropbox.com/s/ulhlvi9qg4do2wj/elastic.zip?dl=0). `elastic1.log` has the sorter enabled and the results not returned. `elastic.log` has the sorter disabled and all the results are correctly returned. That's the only code change i am making, turning off the sorter.

If I notice anything else, I will update this thread.

thanks!
V

**Comment by vishalshah-org** [comment]
@olivere thoughts on this issue? keep it open for now?
thanks.

**Comment by olivere** [comment]
@vishalshah-org Yes, keep it open. Sorry, I didn't have the time to look into it in detail.

BTW sorting with scanning is not such a good idea if the number of results is large. It's basically like searching with pagination, which [got limits in 2.1](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_21_search_changes.html).

In 2.x, `search_type=scroll` is the recommended approach AFAIK. Did you try [Scroll](https://www.elastic.co/guide/en/elasticsearch/reference/2.2/search-request-scroll.html), too? Here's the [code for `ScrollService`](https://github.com/olivere/elastic/blob/release-branch.v3/scroll.go) and some [tests](https://github.com/olivere/elastic/blob/release-branch.v3/scroll_test.go). However, sorting is very resource intensitive, so if you can circumvent it, that's very much recommended--[see notes here](https://www.elastic.co/guide/en/elasticsearch/reference/2.2/search-request-scroll.html).

Also, I think about implementing an Iterator-style cursor which is safe for data races, as some users experience that ES can provide data faster that Go can deserialize it (see #208).

**Comment by olivere** [comment]
@vishalshah-org I just added a [test for Scan with sort](https://github.com/olivere/elastic/blob/release-branch.v2/scan_test.go#L503). That works fine. Can you check the difference between your code and the test?

**Comment by vishalshah-org** [comment]
@olivere i have a query associated with the scan and sort. Could that cause the issue?

**Comment by olivere** [comment]
Did you figure this one out, e.g. by a test case?

**Comment by vsiv** [comment]
I did not, let me see if I can this week.. thx

**Comment by vsiv** [comment]
Hi @olivere - just read in the docs this -

> The scan search type disables sorting in order to allow very efficient scrolling through large result sets.
Source: https://www.elastic.co/guide/en/elasticsearch/reference/1.7/search-request-search-type.html

That explains this issue. I did not know this. so sorry! 
closing 🎉

**Comment by vsiv** [comment]
On second thought, I will let u close it 😄

**Comment by olivere** [comment]
Okay. I'm closing this as it's hard to tell what the problem was by reading through every comment. Just create a new issue if the problem reoccurs somehow.
