### ISSUE TITLE
Unable to use this package with cached godeps

### ISSUE THREAD

**Issue by bradgearon** [olivere/elastic#183]
Trying to use this in a project that has cached godeps and the uritemplates package causes build issues since its looking for godeps/_workspace/src/* instead of the gopath

**Comment by olivere** [comment]
@bradgearon Hi. I'm not familiar with godeps so I don't know what going on really. I will try out myself, but TBH I'm pretty amazed that you're the first one with this issue. Which import path are you using: gopkg.in/olivere/elastic.v2, gopkg.in/olivere/elastic.v3, or github.com/olivere/elastic? You shouldn't use the last one.

**Comment by olivere** [comment]
@bradgearon Any news on this?

**Comment by bradgearon** [comment]
I'm using v2. Thanks so much!

**Comment by olivere** [comment]
@bradgearon Does this mean you issue is solved now?

**Comment by olivere** [comment]
I found a wrong import path on 3.0.14 that lead to inclusion of `github.com/olivere/elastic`. You might want to update to 3.0.15 (`go get -u gopkg.in/olivere/elastic.v3`) to fix the issue. Elastic currently does not have any external dependencies.
