### ISSUE TITLE
Replace PreOffset and PostOffset with Offset in v3

### ISSUE THREAD

**Issue by kbirk** [olivere/elastic#186]
It seems that the pre_offset and post_offset parameters in the Histogram and DateHistogram aggregations were deprecated in 1.5 and removed in 2.x. 

https://www.elastic.co/guide/en/elasticsearch/reference/2.x/search-aggregations-bucket-datehistogram-aggregation.html#_offset

Please replace the PreOffset and PostOffset methods with Offset.

**Comment by olivere** [comment]
@kbirk Thanks for reporting. It's hard to keep everything in sync. Just [pushed 3.0.14](https://github.com/olivere/elastic/commit/33747b6d450839d8186edd535f36ae1c90e75730) and updated to be in line with [DateHistogramBuilder.java](https://github.com/elastic/elasticsearch/blob/2.1/core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramBuilder.java#L33) in 2.1.
