### ISSUE TITLE
no Elasticsearch node available

### ISSUE THREAD

**Issue by sundarv85** [olivere/elastic#187]
Hello,

I’m facing connection problem with **2.1.1 Elasticsearch**. I went through your [wiki](https://github.com/olivere/elastic/wiki/Connection-Problems) and here is my output

```
$ curl -s -XGET 'http://127.0.0.1:9200/_nodes/http?pretty=1'
{
  "cluster_name" : "elasticsearch",
  "nodes" : {
    "PaUe2I24Q3m4m_p_mneBqg" : {
      "name" : "gen Harada",
      "transport_address" : "127.0.0.1:9300",
      "host" : "127.0.0.1",
      "ip" : "127.0.0.1",
      "version" : "2.1.1",
      "build" : "40e2c53",
      "http_address" : "127.0.0.1:9200",
      "http" : {
        "bound_address" : [ "127.0.0.1:9200", "[fe80::1]:9200", "[::1]:9200" ],
        "publish_address" : "127.0.0.1:9200",
        "max_content_length_in_bytes" : 104857600
      }
    }
  }
}
```

But when I run from go program

```
$ go run searchservice.go
panic: no Elasticsearch node available
```

Any idea where to debug?

**Comment by olivere** [comment]
Is that really 127001, not 127.0.0.1? Can you show me the Go code where you're connecting to ES?

**Comment by olivere** [comment]
@sundarv85 Interesting. I was reading this on my iPhone over christmas, and it displayed 127.0.0.1 as 127001. So: Sorry for that :-)

When using elastic to connect to Elasticsearch 2.x, you should definitely use the following import path:  `"gopkg.in/olivere/elastic.v3"`. Do you use that?

**Comment by olivere** [comment]
@sundarv85 I updated the [wiki page on connection problems](https://github.com/olivere/elastic/wiki/Connection-Problems) to include instructions on chosing the correct version of Elastic. You might want to read it again... maybe it solves your problem?

**Comment by sundarv85** [comment]
@olivere Ah yes, that was the issue. I had used incorrect path. My bad. Thanks for updating the wiki. Now it works.
