### ISSUE TITLE
Pretty Print for Requests

### ISSUE THREAD

**Issue by sundarv85** [olivere/elastic#188]
Hello,

I have enabled `elastic.SetTraceLog(log.New(os.Stdout, "", log.LstdFlags))` and have set the Pretty as true

```
	searchResult, err := client.Search().
		Index("twitter"). // search in index "twitter"
		Query(termQuery). // specify the query
		From(0).Size(10). // take documents 0-9
		Pretty(true).     // pretty print request and response JSON
		Do()    
```

This prints the response in the pretty format. However the request is not pretty. I’m using `"gopkg.in/olivere/elastic.v3"`

**Comment by olivere** [comment]
@sundarv85 You're right. Using `Pretty(true)` simply makes Elastic pass [`pretty=true` as a URL query parameter](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#_pretty_results) to Elasticsearch. So in the end, Elasticsearch will pretty print the response and I simply output the pretty-printed response. Elastic doesn't do anything to pretty print anything, neither request nor response. So it first of all is a documentation issue.

I will have to dig into [`net/http/httputil`](https://golang.org/pkg/net/http/httputil/) to see if there's anything I can do to get the HTTP request pretty printed.

**Comment by olivere** [comment]
I think I'll not be doing pretty-printing for the request side.
