### ISSUE TITLE
Clone Connection

### ISSUE THREAD

**Issue by sundarv85** [olivere/elastic#189]
Hello,

When writing a server, for every request how should the connection be setup with ElasticSearch. Is creating `elastic.NewClient` for every request in a middleware, the recommended approach.

For e.g. in `mgo`, there  is a `Clone()` call, which clones the connection. This can be used in the middleware. Is there something like that.

Thanks

**Comment by olivere** [comment]
@sundarv85 Hi! You typically create one `Client` and use it in throughout your application. A `Client` is not like a database session. The `Client` has two purposes: First, to make [Services](https://github.com/olivere/elastic/wiki/Services) available. Second, to monitor your cluster and e.g. gracefully handle situations where one node goes down or another gets added to the cluster. For the latter, we need more than session-like behavior. Internally, a `Client` starts goroutines to monitor these changes. Details are described in the Wiki under [Sniffing](https://github.com/olivere/elastic/wiki/Sniffing) and [Healthchecks](https://github.com/olivere/elastic/wiki/Healthcheck).

If you work in a sandbox like e.g. AppEngine, you can create a new `Client` on every request without too much overhead--and without the goroutines and the monitoring aspect. See [here](https://github.com/olivere/elastic/wiki/App%20Engine) for an example.

I hope this answers your question?!

**Comment by sundarv85** [comment]
@olivere Thanks for the quick reply! Now I understand better. In mgo session, if we use the same session across go-routines, then they are kind of blocked. It is recommended to clone and use these cloned sessions.

From your description of Sniffing/HealthChecks, I assume the following to be true:

1. One client can be used by multiple go-routines without any issue
2. If one communication fails, the rest of the client calls are still unaffected and are handled internally.

If my assumptions are incorrect, please reopen the issue. I’m closing the issue.

**Comment by olivere** [comment]
@sundarv85 Correct. Use one Client across all your goroutines. Elastic must not have any race conditions when doing so. If it does, that's an error. Elastic also does its best to never fail as nodes come and go. There's a small test suite for that in the [cluster-test](https://github.com/olivere/elastic/tree/release-branch.v3/cluster-test) folder.
