### ISSUE TITLE
Complicated Query Examples

### ISSUE THREAD

**Issue by sundarv85** [olivere/elastic#194]
Hello,

I’m trying to wrap my head on how to write such the below two querires as below using elastic. It would be helpful if you could write up such examples in the Wiki as well. Thanks in advance.

```
GET /industry/music/_search
{
  "query": {
    "filtered": {
      "filter": {
        "term": {
          "kind": "rock"
        }
      },
      "query": {
        "has_child": {
          "type": "song",
          "score_mode": "sum",
          "query": {
            "filtered": {
              "query": {
                "match_all": {}
              },
              "filter": {
                "bool": {
                  "must": [
                    {
                      "term": {
                        "singer": "Michael"
                      }
                    },
                    {
                      "term": {
                        "group": "no"
                      }
                    }
                  ]
                },
                "range": {
                  "date": {
                    "gte": "1995",
                    "lt": "2000"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

Aggregate Example

```
GET /industry/music/_search?search_type=count
{
  "query": {
    "filtered": {
      "filter": {
        "term": {
          "kind": "rock"
        }
      }
    }
  },
  "aggs": {
    "events": {
      "children": {
        "type": "song"
      },
      "aggs": {
        "filtered": {
          "filter": {
            "range": {
              "date": {
                "gte": "1995",
                "lt": "2000"
              }
            }
          },
          "aggs": {
            "browser": {
              "terms": {
                "field": "singer",
                "size": 15
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by olivere** [comment]
@sundarv85 Yeah. Documentation could be better. Here are some tips that might help. First, read the tests. They serve as example code. Second, once you got the JSON right, build it from the inside out. Third, once you think you got it right and it still fails, enable the trace log and/or use the `_.Source()` func and serialize to JSON. It should give you an idea what's wrong.

Regarding your  query, notice that ES has deprecated filtered query as of 2.0 (and it's not in elastic.v3). You should use a bool query instead, as [described here](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_query_dsl_changes.html#_literal_filtered_literal_query_and_literal_query_literal_filter_deprecated).

HTH

**Comment by olivere** [comment]
I've set up some documentation regarding the [QueryDSL](https://github.com/olivere/elastic/wiki/QueryDSL).
