### ISSUE TITLE
AndFilter replacement in v3

### ISSUE THREAD

**Issue by baxterbln** [olivere/elastic#195]
Hey,

can you give me a example of a replacement for the AndFilter/OrFilter? I found nothing in the docs;-)

termQuery := elastic.NewQueryStringQuery(search).DefaultField("_all")
orFilterFurnish := elastic.NewOrFilter()
andFilter := elastic.NewAndFilter()

if store.GetFilters("Filterfurnished", w, request) == "furnished" {
			orFilterFurnish := orFilterFurnish.Add(elastic.NewTermFilter("furnish", "Completely furnished"))
			orFilterFurnish = orFilterFurnish.Add(elastic.NewTermFilter("furnish", "Partially furnished"))
			andFilter = andFilter.Add(orFilterFurnish)
		}
		
andFilter = andFilter.Add(elastic.NewRangeFilter("prices.price").From(convert2int(store.GetFilters("FilterPriceFrom", w, request))).To(FilterPriceTo))

Thanks
Baxter

**Comment by olivere** [comment]
Sorry, on the road now.

I think they were deprecated and replaced by Bool query in 2.0. Can you find a reference in the breaking changes (https://www.elastic.co/guide/en/elasticsearch/reference/2.1/breaking_20_query_dsl_changes.html) or the CHANGELOG.md in release-branch.v3?

**Comment by olivere** [comment]
@baxterbln Hey! While they are not strictly deprecated, you are discouraged to use them as they "may be removed in the future" (see [here](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/breaking_20_query_dsl_changes.html#_literal_or_literal_and_literal_and_literal_now_implemented_via_literal_bool_literal)).

What you need to do is to create a `BoolQuery` and work with `must`, `must_not`, `should`, `should_not` and `filter`. In my apps this made queries much simpler in Elasticsearch 2.0. You can find [a simple example](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/breaking_20_query_dsl_changes.html#_literal_or_literal_and_literal_and_literal_now_implemented_via_literal_bool_literal) in the test for `BoolQuery`.

Feel free to comment if that doesn't solve your question.

**Comment by baxterbln** [comment]
Thanks for your Help, this example work for me:

termFilter := elastic.NewBoolQuery()
filter := elastic.NewBoolQuery().Must(elastic.NewTermQuery("active", 1))
filter = filter.Should(elastic.NewTermQuery("types.raw", "App"))
filter = filter.Should(elastic.NewTermQuery("types.raw", "Ho"))
filter = filter.Should(elastic.NewTermQuery("types.raw", "Pe"))
filter = filter.Should(elastic.NewTermQuery("types.raw", "St"))
termFilter = termFilter.Filter(filter)
