### ISSUE TITLE
range query instead of gte, it uses include_lower, upper, to

### ISSUE THREAD

**Issue by sundarv85** [olivere/elastic#196]
Hello,

When I use the code
```
	dateFilter := NewBoolQuery()
	dateFilter = dateFilter.Filter(NewRangeQuery("ts").Gte("now-24h/d"))
	dateFilter = dateFilter.Filter(NewRangeQuery("ts").Gte("now-24h"))
```

I was only expecting the `gte` keyword to be used. But I see
```
                         "from": "now-24h/d",
                        "include_lower": true,
                        "include_upper": true,
                        "to": null 
```

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-range-query.html also explains only about `gte`. Is there a reason why you convert to these values. Also, I was trying to find in ES Reference of range query. Is this mentioned somewhere in docs. 

Full Query below:

```
{
  "bool": {
    "_name": "Test",
    "filter": {
      "bool": {
        "filter": [
          {
            "term": {
              "singer": "Michael"
            }
          },
          {
            "term": {
              "kind": "rock"
            }
          }
        ]
      }
    },
    "must": {
      "has_child": {
        "inner_hits": {
          "fields": "ts",
          "name": "ts",
          "size": 1,
          "sort": [
            {
              "ts": {
                "order": "desc"
              }
            }
          ]
        },
        "query": {
          "bool": {
            "filter": {
              "bool": {
                "filter": [
                  {
                    "range": {
                      "ts": {
                        "from": "now-24h/d",
                        "include_lower": true,
                        "include_upper": true,
                        "to": null
                      }
                    }
                  },
                  {
                    "range": {
                      "ts": {
                        "from": "now-24h",
                        "include_lower": true,
                        "include_upper": true,
                        "to": null
                      }
                    }
                  }
                ]
              }
            },
            "must": {
              "match_all": {}
            }
          }
        },
        "score_type": "sum",
        "type": "music"
      }
    }
  }
}
```

**Comment by olivere** [comment]
AFAICS the behavior is semantically correct, isn't it?

The Java API of Elasticsearch does the same: The `gte`, `lte` etc. keywords are just shortcuts you can use in the JSON interface. Internally, all these queries [get](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/index/query/RangeQueryBuilder.java#L233) [translated](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/index/query/RangeQueryBuilder.java#L123) [to](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/index/query/RangeQueryBuilder.java#L123) `from`, `to`, `include_lower` and `include_upper` in [`RangeQueryBuilder.doXContent(...)`](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/index/query/RangeQueryBuilder.java#L233).

**Comment by vdamery** [comment]
@olivere I'm migrating an application from Scala (Elastic4s) to Golang (Olivere) and I've experienced the same behaviour. 

I've look back into the official documentation and find this :
https://www.elastic.co/guide/en/elasticsearch/reference/0.90/query-dsl-range-query.html

> Deprecated in 0.90.4.
> The from, to, include_lower and include_upper parameters have been deprecated in favour of gt,gte,lt,lte

Is this problematic to use olivere's rangeQuery or it is better to implement our own with gt,gte,... ?

**Comment by renier** [comment]
@olivere What if I want to control `include_upper` and `include_before`? Is there a way to do that via the library?

[edit] I [see](https://pkg.go.dev/github.com/olivere/elastic/v7#RangeQuery) it.

**Comment by rharsh-arkin** [comment]
@renier @olivere  
Can any one of you please explain how to control include_upper and include_lower in java?
I am using java API client and I could not seem to find those APIs while building RangeQuery.
Thanks in advance.

**Comment by olivere** [comment]
@rharsh-arkin If you're using the Java client, why do you ask such things in the issues section of a (deprecated) Go project?

Isn't [the official Java client](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/index.html) the best site for your question?
