### ISSUE TITLE
Children Aggregation

### ISSUE THREAD

**Issue by sundarv85** [olivere/elastic#199]
In the Children Aggregation, only the 
```
"type":"music"
```
is written. From `search_aggs_bucket_children.go`
```
func (a *ChildrenAggregation) Source() (interface{}, error) {
	// Example:
	//	{
	//    "aggs" : {
	//      "to-answers" : {
	//        "type" : "answer"
	//      }
	//    }
	//	}
	// This method returns only the { "type" : ... } part.

	source := make(map[string]interface{})
	source["type"] = a.typ
```

From https://www.elastic.co/guide/en/elasticsearch/reference/2.1/search-aggregations-bucket-children-aggregation.html, I assume that it should be

```
          "children": {
            "type" : "answer" 
          },
```

I made the below change and then it works for me

```
	t := make(map[string]interface{})
	t["type"] = a.typ
	source := make(map[string]interface{})
	source["children"] = t
```

Is my understanding correct or am I missing something.

**Comment by olivere** [comment]
@sundarv85 Yep. That looks like a bug to me. Thanks for reporting! A new version for v2 and v3 will be available soon.
