### ISSUE TITLE
Search examples

### ISSUE THREAD

**Issue by mpmlj** [olivere/elastic#200]
Hi,

Could you please provide an example for a use-case similar to Facebook's top search?
I.e.:
1. Multi-match search, i.e. success if any of the fields match ("name", "organization", etc.)
2. Every match is a wildcard, i.e. I'm ok if just a part of each field matched. Any part.
3. Sorted the results by best match.

Thank you
D.

P.S.
In general, it will be great to have complex search examples, i.e. different conditions/filters/etc.

**Comment by sundarv85** [comment]
@mpmlj Refer [issue 194](https://github.com/olivere/elastic/issues/194). That might give you a starting point.

**Comment by mpmlj** [comment]
@sundarv85 

Hi, Thank you for the links (i've used example from one of it to optimize my own code). 
Still, I had no problem assembling a request with:
1. A search by wildcard against a _single_ field
2. or a non-wildcard NewMultiMatchQuery to several fields ("displayName", "organization")

My problem: combining wildcard + multimatch.

I would greatly appreciate your insight here!

D.

P.S.
Attaching my code below, hope it helps!

``` Go
...
	query := elastic.NewWildcardQuery("displayName", "*" + q + "*")

	search := es.DB.Search().
	Index("fb").
	Type("user").
	Query(query).
	Sort("displayName", true).
	From(0).Size(10)

	res, err := search.Do()
	if err != nil {
		log.Error("Error running ES search", err.Error())
		return resp, err
	}

	if res == nil || res.TotalHits() == 0 {
		resp.Hits = 0
		return resp, nil
	}

	for _, hit := range res.Hits.Hits {
		user := new(UserQuickSearchRecord)
		if err := json.Unmarshal(*hit.Source, user); err != nil {
			log.Error("Cannot unmarshal ES hit object", err.Error())
			return resp, err
		}
		resp.Items = append(resp.Items, user)
	}
...
```

**Comment by sundarv85** [comment]
@mpmlj 

AFAIK you cannot use wildcard with multi-match. You have to construct a `should` claus with `bool`

For e.g. from [stackoverflow link](http://stackoverflow.com/questions/16933800/elasticsearch-how-to-use-multi-match-with-wildcard)
```
GET _search {
    "query": {
        "bool": {
            "must": [
                {
                    "range": {
                        "theDate": {
                            "gte": "2014-01-01",
                            "lte": "2014-12-31"
                        }
                    }
                },
                {
                    "match" : {
                        "Country": "USA"
                    }
                }
            ],
            "should": [
                {
                    "wildcard" : { "Id_A" : "0*" }
                },
                {
                    "wildcard" : { "Id_B" : "0*" }
                }
            ],"minimum_number_should_match": 1
        }
    }
}
```

**Comment by olivere** [comment]
@mpmlj Thanks for your question. Is it related to being able to find the correct syntax in Go/Elastic? Or are you asking a general question on how to achieve a specific search in Elasticsearch? For the latter, it's probably better to ask your question on the [Elastic discussion forums](https://discuss.elastic.co/c/elasticsearch), then apply the response to Go/Elastic.

**Comment by mpmlj** [comment]
@olivere 
Former. I had a gut feeling that (and as per @sundarv85 's suggestion above) I'll need to construct a search somehow, but did not know to do this using "elastic".

**Comment by olivere** [comment]
@mpmlj If you want to look at constructing queries with Elastic, you probably want to look into the tests. There are probably dozens of examples of building up queries. E.g. if you're looking into working with search results, [search_test.go](https://github.com/olivere/elastic/blob/release-branch.v3/search_test.go) is a good example. For multi match, the tests in [search_queries_multi_match_test.go](https://github.com/olivere/elastic/blob/release-branch.v3/search_queries_multi_match_test.go) might be helpful, or [search_queries_wildcard_test.go](https://github.com/olivere/elastic/blob/release-branch.v3/search_queries_wildcard_test.go) for wildcard queries.

My general approach to mapping the REST query to Go code is to build the Go code from the inside out, i.e. construct the innermost query/filter component first, then build up from there.

HTH

**Comment by mpmlj** [comment]
@olivere @sundarv85 
Thank you, guys!
