### ISSUE TITLE
SetTraceLog inside test

### ISSUE THREAD

**Issue by zippoxer** [olivere/elastic#201]
I'm trying to debug requests and responses from my tests:

```
func TestBar(t *testing.T) {
  // connect to elastic
  elastic.SetTraceLog(log.New(os.Stdout, "", 0))
  // perform a search with elastic
}
```

However, I get no output from `elastic` at all. What am I doing wrong?

**Comment by sundarv85** [comment]
@zippoxer It seems a bit confusing, but the logging works when I pass it into the NewClient() options

```
	client, err = elastic.NewClient(
		elastic.SetHealthcheckInterval(10*time.Second),
		elastic.SetMaxRetries(5))
	   elastic.SetTraceLog(l.New(os.Stdout, "", l.LstdFlags)))
```
Refer [this wiki page](https://github.com/olivere/elastic/wiki/Logging)

**Comment by zippoxer** [comment]
Oh, I didn't notice it's a client option. Sorry for the confusion and thanks a lot :)

**Comment by sundarv85** [comment]
@olivere Is there a reason why SetTraceLog is not returning a `ClientOptionFunc `. I see that 

`type ClientOptionFunc func(*Client) error`

Could we change SetTraceLog also to ClientOptionFunc

**Comment by olivere** [comment]
@sundarv85 You mean `SetTraceLog` etc. should change signature from

```go
func SetTraceLog(logger *log.Logger) func(*Client) error {
```

to

```go
func SetTraceLog(logger *log.Logger) ClientOptionFunc { ... }
```

?

No, there's no reason not to change that. ;-)  Can you open a new issue for that? Thanks a lot for reporting.

**Comment by sundarv85** [comment]
Yep, that is it. Have opened #202
