### ISSUE TITLE
NewSimpleClient

### ISSUE THREAD

**Issue by olivere** [olivere/elastic#205]
The idea is  to create a simple "throwaway" client that can be used for only one request. You might need this in restricted environments like AppEngine.

**Comment by gm42** [comment]
Oh, this is very much in line with what I was going to ask! Basically we are experiencing issues with the embedded sniffer/healthcheck/connection pool/balancer that there is currently in the client. As an example of what I am talking about, feel free to give a look to the [massive removals here](https://github.com/olivere/elastic/compare/release-branch.v3...bookerzzz:release-branch.v3).

Problem is that when using a load balancer, you don't want any special logic to hide problems or even retries. You can think of this as the mysql library that does little retries (https://golang.org/src/database/sql/sql.go#L845 only 2 at the moment) and tries to stay responsive and "flat" as much as possible.

Is it possible - with the current v3/master - to configure a client to behave like explained above? If not then a `NewSimpleClient` would be very welcome :smiley:

**Comment by olivere** [comment]
@gm42 Well, the idea stems from having a discussion with users that use e.g. AppEngine and cannot create a shared client for their application. They basically need a simple throwaway client that is cheap to create, doesn't start any goroutines etc. This is what I described in [AppEngine](https://github.com/olivere/elastic/wiki/App%20Engine) in the wiki.

What `NewSimpleClient` does is simply create a client with the correct options for that use case: No healthchecks, no retries, no sniffing, no load balancing etc. It's simply a small wrapper that calls `NewClient` and does "the right thing".

Regarding the question wrt hiding problems: Elastic basically does what the official clients do. If you don't want to hide any problems, you can specify options to e.g. have no retries or disable sniffing or load-balancing. What is the reason for the removals other than making Elastic simpler and moving responsibilities for load-balancing, sniffing etc. to the caller?

**Comment by gm42** [comment]
@olivere yes, then we are talking about the same thing. No other reason than what you specified, e.g. `making Elastic simpler and moving responsibilities for load-balancing, sniffing etc. to the caller`. So if this were possible by configuring the existing client (or using a `NewSimpleClient` wrapper), that would suffice for us and I could use it already.

I've looked up the options you use in that AppEngine wiki page and I think that could be the right set.

**Comment by olivere** [comment]
@gm42  I have implemented `NewSimpleClient` and released 3.0.19. Could you give it a try and see if it works for you?

**Comment by olivere** [comment]
Updated [Client documentation](https://github.com/olivere/elastic/wiki/Client).

**Comment by gm42** [comment]
@olivere sure, thanks! We are going to test it :)

**Comment by olivere** [comment]
@gm42 Any news on this?

**Comment by gm42** [comment]
@olivere it seems to work fine, thanks!

**Comment by olivere** [comment]
@gm42 Okay. Closing then. Feel free to reopen or create a new issue when something fails.
