### ISSUE TITLE
No way to add new type mapping to existing index

### ISSUE THREAD

**Issue by khuderm** [olivere/elastic#209]
I can't seem to find any documentation or code for adding new type mappings to an existing index.

**Comment by olivere** [comment]
You mean, like the Put Mapping API: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html? It should be supported by both v2 and v3.

**Comment by khuderm** [comment]
I found it now. Sorry about the dumb question lol
