### ISSUE TITLE
sort by script

### ISSUE THREAD

**Issue by nizsheanez** [olivere/elastic#21]
Hello, is it possible now to sort by script?
Like this:
```
"_script" : {
   "script": "...",
  "lang": "groovy",
  "type": "number",
  "order": "desc"
}
```
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-request-sort.html#_script_based_sorting

**Comment by olivere** [comment]
I don't think so. Yet. :-)    I'll see if I find the time to implement the changes to sorting in the next days.

**Comment by nizsheanez** [comment]
Thanks.
Actually this task is not in priority for me now.
So if you will have time please take a look at https://github.com/olivere/elastic/pull/20 firstly

**Comment by olivere** [comment]
All sorters of Elasticsearch 1.4 should be implemented by [this commit](https://github.com/olivere/elastic/commit/57a2a9e0840854e6b00791f074d9f9f803d67ab3).
