### ISSUE TITLE
SetURL not working

### ISSUE THREAD

**Issue by petard** [olivere/elastic#210]
I need to setup a simple script to pull some data from ES but fail already on the connection:

```
func main() {

	client, err := elastic.NewClient(elastic.SetURL("http://122.15.2.61:31344"))
	if err != nil {
		println(err.Error())
		return
	}
```

I'm getting `no Elasticsearch node available` even though `curl -XGET -v "http://122.15.8.82:31344/_search"` works perfectly fine. I'm connecting to a remote ES host within a VPN.

Any ideas?

**Comment by olivere** [comment]
Hi! Did you check the [connection problems](https://github.com/olivere/elastic/wiki/Connection-Problems) section in the Wiki? I suspect the sniffing process isn't working, but you could disable that.

**Comment by olivere** [comment]
@petard Any news on this issue?

**Comment by petard** [comment]
@olivere i've disabled sniffing in the client initializer and it fixed the problem. thx!
