### ISSUE TITLE
release-branch.v3 elastic.RangeQuery syntax broken on ES 2.x

### ISSUE THREAD

**Issue by adamalix** [olivere/elastic#211]
Currently, [release-branch.v3](https://github.com/olivere/elastic/tree/release-branch.v3) uses the old range query syntax.  See the new [Range Query DSL Syntax here](https://www.elastic.co/guide/en/elasticsearch/reference/2.x/query-dsl-range-query.html#query-dsl-range-query).

We should replace:
- `RangeQuery.From()` with `RangeQuery.Gte()`
- `RangeQuery.To()` with `RangeQuery.Lte()`

Remove:
- `RangeQuery.IncludeLower()`
- `RangeQuery.IncludeUpper()`

Add:
- `RangeQuery.Lt()`
- `RangeQuery.Gt()`

**Comment by olivere** [comment]
@adamalix Thanks a lot for your support. I'm rather busy at the moment, so it may take a few days.

I try not to remove existing code though (unless it's really unsupported) as that might break clients.

**Comment by olivere** [comment]
@adamalix RangeQuery should resemble the API of the Java client (see [RangeQuery](https://github.com/elastic/elasticsearch/blob/2.x/core/src/main/java/org/elasticsearch/index/query/RangeQueryBuilder.java)).

Elastic documentation is good. I try to take the Java API as reference though :-)

**Comment by adamalix** [comment]
@olivere cool. will fix up PR to reflect.

**Comment by olivere** [comment]
@adamalix Thanks a lot. I promise I'll look into it as soon as I find some time.

**Comment by olivere** [comment]
See discussion on [PR-214](https://github.com/olivere/elastic/pull/214).
