### ISSUE TITLE
SetURL issues on Docker

### ISSUE THREAD

**Issue by EwanValentine** [olivere/elastic#213]
I'm trying to connect to an Elasticsearch container in a Docker set-up:

```
client, err := elastic.NewClient(elastic.SetSniff(false), elastic.SetURL("http://"+os.Getenv("ELASTICSEARCH_9200_TCP_ADDR")+":9200"))
	if err != nil {
		panic(err)
	}
```

This uses the docker-compose environment variables to resolve the host and it does find the correct ip address, so I'm not sure why it's not connecting properly? I've tried connecting via the docker-compose generated hostname also which works for my other mongodb container for instance.

**Comment by olivere** [comment]
@EwanValentine Hi there. I couldn't reproduce the issue. But as this question comes up once in a while, I've set up an example that illustrates [how to use Elastic with Docker / Docker Compose](https://github.com/olivere/elastic-with-docker). Maybe this will help you find the problem in your environment.

If this doesn't help, feel free to ask again, and I'm happy to reopen the issue and we'll eventually find a way.

**Comment by EwanValentine** [comment]
Perfect, thank you!
