### ISSUE TITLE
Custom Logger

### ISSUE THREAD

**Issue by kri5** [olivere/elastic#217]
Is there any reason to enforce the use of a log.Logger?

As it is not an interface, it does not allow to log with a custom logger implementing the same methods, such as logrus/glog/others...

Why not exposing a logger interface that anyone could implement?

Bests.

**Comment by olivere** [comment]
@kri5 It's basically there because that's what the standard library provides. If you find a good interface for logging that is a) compatible with all the other logging libraries out there and b) doesn't break compatibility, I'd be willing to look into your PR :-)

**Comment by olivere** [comment]
Let me know if you're missing something.
