### ISSUE TITLE
Export method on BulkService to give access to individual BulkableRequests by index

### ISSUE THREAD

**Issue by kbirk** [olivere/elastic#219]
I have an application that uses the BulkService for large ingestion jobs. Bulk payloads are typically within the 5-10MB range and include tens of thousands of actions (BulkIndexRequest). User error frequently occurs, resulting in vague error messages returned by elasticsearch.

In the case of an error the BulkResponse object provides me access into the individual BulkResponseItems to determine which exact documents resulted in error.

The BulkableRequest interface provides the String method, which I can use to see the actual JSON that the action translates to.

However there is no exported method or attribute to let me search for that action in the original BulkService object. I have to create a separate slice for reference.

Would you be willing to export a method on the BulkService for returning a BulkableRequest by index?

**Comment by olivere** [comment]
That doesn't seem to be too invasive and won't break existing code. Would you provide a PR?

**Comment by olivere** [comment]
You noticed that there's a [`ById`](https://github.com/olivere/elastic/blob/release-branch.v3/bulk.go#L267) func on the response structure, yes? That'd help you lookup the outcome of a specific document from the request side. But you want direct access to the requests on the input side?

Also: There's an experimental [BulkProcessor](https://github.com/olivere/elastic/wiki/BulkProcessor) that you might try for ingesting bulk data. It's not broadly used yet, so there might be dragons.

**Comment by kbirk** [comment]
The issue is that the Error.Type and Error.Reason strings in most cased aren't descriptive enough, and I find myself needing to look back at the actual corresponding bulk action.

For example, yesterday I was running a 50GB ingest (~120M documents), and an hour in I got the following error:

> mapper_parsing_exception: failed to parse [randomAttribute]

Only when I could see exactly what the bulk action JSON was, was I able to fix it.

My current solution is as follows:

On my local repo i've added a simple 'Actions' method to return the slice of actions.
`
func (s *BulkService) Actions() []BulkableRequest {
	return s.requests[0:]
}
`

To find the corresponding JSON:
`
// errors to return
errs := make([]error, 0)
// store actions before sending the bulk request, since it is reset after
actions := bulk.Actions()
// send response
res, err := bulk.Do()
if err != nil {
    errs = append(errs, err)
    return errs
}
// check for errors
if res.Errors {
    for index, items := range res.Items {
        action, ok := items["index"]
        if ok {
            if action.Error != nil {
                errs = append(errs, fmt.Errorf("%s: %s: %s", 
                    action.Error.Type, 
                    action.Error.Reason, 
                    actions[index].String()))
            }
        }
    }
}
return errs
`

As you can see it is a bit cumbersome because of how the BulkService resets implicitly after Do(). Also since I rely on the absolute index of the action, I have to bypass the Failed() method and iterate over the responses manually.

**Comment by olivere** [comment]
I'm not sure I understand your issues.

First of all, the error details and error message are what is returned by Elasticsearch. There is nothing I can do in the client to get more precise error messages.

Second, BulkService resets the input requests because otherwise all implementors had to do this manually. This is error prone and so Elastic does exactly what official clients do, e.g. [elasticsearch-py](https://github.com/elastic/elasticsearch-py/blob/8342e0efb1e38c06fa975c7442ad897b764c3bd2/elasticsearch/helpers/__init__.py#L64).

Having worked with some bulk implementations, the general approach I see is to pass a unique id into the `BulkIndexRequest` and then, when an error occurs, use that id to lookup the document that caused the problem in the first place.

**Comment by kbirk** [comment]
Poor wording on my part.

I understand that the errors are forwarded directly from elasticsearch and agree it makes sense for the BulkService to reset upon sending the request.

I was trying to do the general approach you suggested:
    1) I have a BulkService object (bulk) filled with BulkIndexRequests, all with unique IDs
    2) I have a BulkResponse object (res) returned from a call to `bulk.Do()`
    3) I use `res.Failed()` to get all the BulkResponseItems that resulted in error
    4) I want to use the item Id to get the corresponding BulkIndexRequest so that I can inspect the JSON via .String().

I opened an issue to see if a method could be exposed on the BulkService or BulkRequest for getting access to the BulkIndexRequest objects.

Looking at this again, it makes more sense for me to simply persist a map of the BulkIndexRequests, and use that to access them by id:

```go
reqs := make(map[string]*BulkIndexRequest)
for {
    // ... add to reqs
}

bulk := client.Bulk().Index(index).Type(typ)
for _, req := range reqs {
    bulk.Add(req)
}

res, err := bulk.Do()
if err != nil {
    return []error{err}
}

errs := make([]error, 0)
if res.Errors {
    for _, item := range res.Failed() {
        err := fmt.Errorf("%s: %s: %s", 
            item.Error.Type, 
            item.Error.Reason, 
            reqs[item.Id].String())
        errs = append(errs, err)
    }
}
return errs
```

I apologize for wasting your time.
