### ISSUE TITLE
Cannot search for multiple words in an elasticsearch object

### ISSUE THREAD

**Issue by Xe** [olivere/elastic#220]
```go
package main

type Opts struct {
    String string  `short:"s" long:"string" description:"String to search for" required:"true"`
    Rate   float64 `short:"r" long:"rate" description:"Maximum rate before going critical" required:"true"`
}

var opts *Opts

func main() {
    opts = &Opts{}
    _, err := flags.Parse(opts)
    if err != nil {
        log.Fatal(err)
    }

    index := "syslog-2016-02-04"

    // Look for all of the relevant elasticsearch documents
    termQuery := elastic.NewTermQuery("message", opts.String)
    res, err := client.Search().
        Index(idx).
        Query(&termQuery).
        Size(50).
        Type("events").
        Do()
    if err != nil {
        log.Fatal("Could not fetch from Elasticsearch: %#v", err)
    }

    if len(res.Hits.Hits) == 0 {
        log.Fatal("No results")
    }

    for count, hit := range res.Hits.Hits {
        log.Printf("%s", *hit.Source)
    }
}
```

When I run this program such as:

```console
$ ./foo --string "found preference" -r 0
```

I expect it to match any document in the syslog index with the string `"found preference"` in it. However this does match if I change the input string to `"preference"`. How can I search for multiple words?

**Comment by olivere** [comment]
@Xe Hi there. Well, this is more of an Elasticsearch issue, but let me explain nevertheless.

ES is not a database. ES and the underlying Lucene technology deals more with human language which is somewhat subtle and ambiguous, and very often not about exact matches. ES will happily find near matches, documents that sound like those your original query, or words similar to those specified in your query. It will apply a score to the documents and return them in order. E.g. if `"found preference"` is an exact match with a perfect score of 1.0, what score would `"preference"` get, and will it be the same or different than a search for "`found"`? And what about "`find"`: It's the same word as `"found"`, only in present tense, so should it get the same score? ES/Lucene can handle these things.
 
So if you have specific requirements on how things should work, you must help ES to correctly deal with it. The key here is to provide a so-called mapping for your index. Such a mapping describes the fields of your documents, how to analyze and tokenize them, and how to index and search them.

That's such a broad topic that it will not fit into a GitHub issue. But don't worry: Core members of Elasticsearch have written a free book that has all the details: [Elasticsearch - The Definite Guide](https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html). Go check it out, then take a look at the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html), then apply your knowledge to Elastic (read the tests to illustrate how to make Go code out of the JSON structures). I'm sorry: There is no shortcut :-)

HTH.
