### ISSUE TITLE
Logging and instrumentation

### ISSUE THREAD

**Issue by olivere** [olivere/elastic#221]
The general approach to integrating logging into a library in Go is to "just don't": Return errors and leave logging up to the implementer. But Elastic already does logging (and is way too chatty anyway) so we have to deal with it.

A quick grep over what kind of information Elastic is logging shows up that most of it is just informative: Response times, outcome, node health etc. Most of this is telemetry, not logging (or actionable feedback). So in the long run, I'd love to make Elastic silent and only return errors and leave it up to the implementer to deal with it. In addition to that, reporting response times etc. will probably need an interface into a metrics/instrumentation library, e.g. [kit/metrics](https://godoc.org/github.com/go-kit/kit/metrics).

This issue is reserved for thoughts and discussion on the separation of logging and telemetry in Elastic.

**Comment by vsiv** [comment]
Would be interesting if clients can pass a logger that the library can use for info/warns/errors. Developers can then decide whether they want to access logs and what to do with them.

**Comment by olivere** [comment]
You can pass an instance that implements the `Logger` interface when creating a new client. It is described in the Wiki under [Logging](https://github.com/olivere/elastic/wiki/Logging). But it doesn't differentiate between info/warning/error.

**Comment by vsiv** [comment]
Yes, I meant if the logger was aware of levels, that would be interesting and helpful to log for lib users. Happy to see this issue tracked. Thanks.

**Comment by olivere** [comment]
In my apps I try to stay away from log levels, but it's a matter of personal taste.

Out of the blue, I feel like we could create a `LeveledLogger` interface with funcs for the various levels, or a single func that accepts the log level as the first argument. Right now, elastic only uses a trace log (which is used for debugging only), an info log, and an error log. So we could do something like this:

```go
type LeveledLogger interface {
  Errorf(format string, v ...interface{})
  Infof(format string, v ...interface{})
  Tracef(format string, v ...interface{})
}
```

One could set activate the leveled logger via `elastic.SetLeveledLogger(...)` on startup.

What I don't like is that we now have two interfaces for logging.

**Comment by vsiv** [comment]
I too am not too stoked about the 2 logging interfaces. A similar option but more domain centric is something like what [ozzo-routing](https://github.com/go-ozzo/ozzo-routing) does... a logger for domain specific task. In elastic it could be network related error or an elastic error and we can treat them differently as opposed to classifying everything in standard log levels (unless its lib level tracing for debugging I suppose)

This might make it easier to troubleshoot as well.

```
router.Use(
        access.Logger(log.Printf),
        fault.Recovery(customLoggerFn),
    )
```

**Comment by olivere** [comment]
@vsiv You should have a way to intercept HTTP failures via `Retrier` now (see [a855324](https://github.com/olivere/elastic/commit/a85532499f01f2c7eccb34ec7c850d2c01134319) for implementation). I'm about to document the `Retrier` in the wiki later.

Let me know if this doesn't solve your use case.

**Comment by vsiv** [comment]
👍 will check it out!
