### ISSUE TITLE
SearchService Source to JSON

### ISSUE THREAD

**Issue by o-r-r** [olivere/elastic#222]
From what I see , it's not possible to get the source of a search request, for debugging and logging. I think it would be helpful to add this:
```
func (s *SearchService) SourceJSON() (string,error) {
	str, err :=s.searchSource.Source()
	if err!=nil {
		return "",err
	}
	res,err :=json.Marshal(str)
	if err!=nil {
		return "",err
	}
	return string(res),nil
}
```
What do you think?

**Comment by olivere** [comment]
Please use the Source() function of SearchSource, or basically any other type in Elastic that renders JSON in the end. Then use that in your own application if you need to debug it. Or enable the trace log in the Client.

**Comment by o-r-r** [comment]
Looks like Source(source interface{}) set the request body manually no? I couldn't find any Source() function. This is for elastic.v3

**Comment by olivere** [comment]
[Source is here](https://github.com/olivere/elastic/blob/release-branch.v3/search_source.go#L297).

**Comment by o-r-r** [comment]
Sorry, maybe I wasn't clear. The thing is I am creating a SearchService using the package's factory methods, its inner struct searSource is not exported and looks like there is no getter for it. am I wrong?

**Comment by olivere** [comment]
I'm sorry. Can you explain the problem you have and how I might help in resolving it?

If you're interested in debug output, you could enable that in the trace log. If you want to debug individual search request, build up a `SearchSource` and use its `Source()` func to serialize into JSON (before setting it via [`SearchService.SearchSource(...)`](https://github.com/olivere/elastic/blob/release-branch.v3/search.go#L20).

All funcs in `SearchService` simply forward to `SearchSource` anyway, so a `searchSource` is created in the background for every non-trivial search.

AFAICS your `func (s *SearchService) SourceJSON() (string,error) { ... }` is just a shortcut for creating `SearchSource` and using its `Source` method.

Am I missing something?

**Comment by o-r-r** [comment]
OK, I guess that can be done. But it looks like it's much less comfortable and doesn't match the examples in the documentations... I'm constructing a SearchService in this simple manner:
```
searchService := elastic.Search().
	Index(index).   
	Query(query).  
	Aggregation(aggsName,aggregation).
	Sort("user", true).
	From(0).Size(10).  
	Pretty(true).  
	SearchType("count")
```
Now, it would seem logical that this searchService will have some kind of a function to access it's source, at least for debugging. If I understand what you are suggesting, I need to create the SearchSource, get its inner serializable Source struct and then go on to creating the SearchService with that Source? Like I said, now I understand that's the way to do it, but I don't think it's comfortable.

**Comment by olivere** [comment]
To be honest, I think I could probably litter Elastic with a lot of functions that help with getting insights into what's going on under the cover. But is that the purpose of Elastic, or any library? There's a nice quote by Antoine Saint-Exupéry coming to my mind that I like a lot, and I think fits in the context of programming libraries as well: "Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away." Of course, not saying that Elastic is perfect ;-)

If you want to see what's being sent on the wire, there's still the trace log.

**Comment by o-r-r** [comment]
Nice quote... OK I will try using the logger for debugging. Thanks for the great support
