### ISSUE TITLE
Not getting any response from search

### ISSUE THREAD

**Issue by EwanValentine** [olivere/elastic#223]
Hi there,

Me again, apologies if this is something obvious. 

```go
// Search with a term query
termQuery := elastic.NewTermQuery("name", "test")

searchResult, err := search.client.Search().
	Index("artist").      // search in index
	Query(termQuery).  // specify the query
	Sort("name", true). // sort by type field, ascending
	From(0).Size(100). // take documents 0-9
	Pretty(true).      // pretty print request and response JSON
	Do() 

fmt.Println(searchResult)
```

fmt.Println prints `&{66  0xc8201d2480 map[] map[] false <nil>}`. But when I run `http://localhost:9200/artist/_search?q=name:test` it returns an entry. 

Thanks in advance!

**Comment by olivere** [comment]
Hi!

It really depends on the mapping of the `artist` index. AFAIK if you run `http://localhost:9200/artist/_search?q=name:test`, you're running a [`QueryStringQuery`](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html) against the index, not a [`TermQuery`](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html). The former is a full text query which also finds documents that look like a match while the latter looks for **exact** matches. Remember: ES is not a database, and not all queries are the same.

Can you please post the output of `curl 'localhost:9200/artist/_mapping?pretty'`?

**Comment by EwanValentine** [comment]
Ahaa, I think I know what you mean.

The output is:
```
{
  "artist" : {
    "mappings" : {
      "name" : {
        "properties" : {
          "avatar" : {
            "type" : "string"
          },
          "bg_img" : {
            "type" : "string"
          },
          "followers" : {
            "type" : "long"
          },
          "genre" : {
            "type" : "string"
          },
          "id" : {
            "type" : "string"
          },
          "location" : {
            "type" : "string"
          },
          "name" : {
            "type" : "string"
          }
        }
      }
    }
  }
}
```

**Comment by olivere** [comment]
Maybe reading this in [The Definite Guide](https://www.elastic.co/guide/en/elasticsearch/guide/current/languages.html) will help you understand a bit more about all of this. The book is really helpful, highly recommended.

**Comment by olivere** [comment]
This section of the mapping e.g. illustrates that your index has a field called `name` of type `string` (see [string type](https://www.elastic.co/guide/en/elasticsearch/reference/current/string.html)). All the other properties of the field have default values. This means that the field is analyzed, and uses the [standard analyzer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-standard-analyzer.html) by default. The default analyzer e.g. splits on whitespace etc. If you want exact matches, you have to disable analysis on the field.

Run this to see what the default analyzer on the "name" field is doing with input: `curl -XGET 'localhost:9200/artist/_analyze?pretty' -d '{"name" : "test"}'`. Read more about testing analyzers [here](https://www.elastic.co/guide/en/elasticsearch/reference/2.2/indices-analyze.html).

**Comment by olivere** [comment]
This section of TDG [exactly describes your problem](https://www.elastic.co/guide/en/elasticsearch/guide/current/_finding_exact_values.html).

**Comment by EwanValentine** [comment]
I'm getting...

```
{
  "error" : {
    "root_cause" : [ {
      "type" : "illegal_argument_exception",
      "reason" : "Unknown parameter [name] in request body or parameter is of the wrong type[VALUE_STRING] "
    } ],
    "type" : "illegal_argument_exception",
    "reason" : "Unknown parameter [name] in request body or parameter is of the wrong type[VALUE_STRING] "
  },
  "status" : 400
}
```

when I run `curl -XGET 'localhost:9200/artist/_analyze?pretty' -d '{"name" : "test"}'`

**Comment by olivere** [comment]
Syntax was wrong. [Read it up here](https://www.elastic.co/guide/en/elasticsearch/reference/2.2/indices-analyze.html), but I think the documentation is a bit misleading here:

```
# Create the artist index
$ curl -XPOST 'localhost:9200/artist'
# Test analyzer
$ curl -XGET 'localhost:9200/artist/_analyze?pretty&analyzer=standard' -d 'this is a test'
{
  "tokens" : [ {
    "token" : "this",
    "start_offset" : 0,
    "end_offset" : 4,
    "type" : "<ALPHANUM>",
    "position" : 1
  }, {
    "token" : "is",
    "start_offset" : 5,
    "end_offset" : 7,
    "type" : "<ALPHANUM>",
    "position" : 2
  }, {
    "token" : "a",
    "start_offset" : 8,
    "end_offset" : 9,
    "type" : "<ALPHANUM>",
    "position" : 3
  }, {
    "token" : "test",
    "start_offset" : 10,
    "end_offset" : 14,
    "type" : "<ALPHANUM>",
    "position" : 4
  } ]
}
```

Not sure about the syntax. Please try to figure out with ES documentation, sorry.

**Comment by olivere** [comment]
Ah. I was using it against 1.7.5. Documentation for 2.2 is good.

**Comment by EwanValentine** [comment]
I switched my query type to `NewCommonTermsQuery(field, term)` and it worked perfectly! 

Thanks for all your help/advice :)
