### ISSUE TITLE
Result window is too large

### ISSUE THREAD

**Issue by alehano** [olivere/elastic#224]
Sometimes I get this error:
```
[2016-02-09 16:03:20,670][INFO ][rest.suppressed          ] /products/product/_search Params: {index=products, type=product}
Failed to execute phase [query], all shards failed; shardFailures {[5r3CP6p5TkyYPqqS8Heu-A][products][0]: RemoteTransportException[[Free Spirit][172.17.0.2:9300][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Result window is too large, from + size must be less than or equal to: [10000] but was [10080]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter.]; }
```

But I set From to 0 and Size to 6. 

My code: 

```go
	searchResult, err := es.client().Search().
		Index(indexES).
		Type(typeProductES).
		Query(q).
		MinScore(minScore).
		SortBy(elastic.NewFieldSort("_score").Desc()).
		From(options.Skip).Size(options.Limit).
		Do()

```

**Comment by olivere** [comment]
Hi! Can you reproduce the problem? If so, can you enable the trace log and post its output?

ES has imposed a limit of 10.000 documents as a breaking change in 2.1, but you could change that (although you shouldn't;-)). See: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html

**Comment by alehano** [comment]
Yeah, but why if I set size to just 6 I have this error?

**Comment by alehano** [comment]
I can't reproduce error, it happens occasionally. Usually all ok. I used ES 2.1.1, maybe it was a bug. Updated to 2.2.0

**Comment by olivere** [comment]
@alehano Maybe you should enable the trace log for a while in a typical session where this happens. Watch out however, the trace log can produce huge files!
