### ISSUE TITLE
startupHealthcheck doesn't respect SetHttpClient()

### ISSUE THREAD

**Issue by nickw444** [olivere/elastic#225]
When using `newClient` and providing a custom HTTP client, the connection initiated within `startupHealthcheck` doesn't use the provided HTTP client, instead, a new `http.Client` is instantiated, thus any provided HTTP connection configuration is neglected.

Offending line appears within `client.go:946`

```
...
start := time.Now()
for {
	cl := &http.Client{Timeout: timeout}
	for _, url := range urls {
...
```

The current use case for this is to provide a self provided CA root cert, which is provided to our `http.Client`. Since the health check does not use this http client, it will fail.

**Comment by olivere** [comment]
@nickw444 Ah, I see. Sounds like a bug to me. Thanks for reporting. Will take me a few days however; currently on a business trip.
