### ISSUE TITLE
Critical/Stange scenario while using filters in query, in V3

### ISSUE THREAD

**Issue by abhiesa** [olivere/elastic#227]
Hi Olivere,

I am experiencing a abnormal query while applying a filter on the query. There is one scenario in which filter is working fine, and in another, after filter, query is misbehaving.

**Good Scenario**
I have a lucene query and a filter:
```json
filter:  (category:"Computer Accessories")
searchQuery  : {"bool":{"must":{"term":{"cats":"1193"}}}}
```
*Now, I executed following code*
```go
filterQuery := elastic.NewQueryStringQuery(filter)
searchQuery = searchQuery.Filter(filterQuery)
```

Result is fine... and everything is working correctly.

```json
 {
  "bool":{
    "filter":{
      "query_string":{
        "query":"(category:\"Computer Accessories\") "
      }
    },
    "must": {
     "term":{
       "cats":"1193"
      }
   }
  }
}
```

**Bad Scenario**

Now, I have another lucene query and a filter:

filter:  (category:"Computer Accessories")

searchQuery  : {"function_score":{"query":{"bool":{"must":{"multi_match":{"fields":["A^5","B^3","C^3.","D^2","E","F","G","H","I"],"query":"LED","tie_breaker":0,"type":"best_fields"}}}},"script_score":{"script":"_score * ((1/doc['rank'].value)*20)"}}}

*Now, If I executes following code, again*

```go
filterQuery := elastic.NewQueryStringQuery(filter)
searchQuery = searchQuery.Filter(filterQuery)
```

Result is very very weird, and misbehaving

```json
{
  "function_score":{
    "filter":{
     "query_string":{
       "query":"(category:\"Computer Accessories\") "
      }
   },
  "script_score":{
     "script":"_score * ((1/doc['rank'].value)*20)"
    }
  }
}
```

Could you please advice me, is this intentional or i am doing something very wrong, here.

*Warm Regards,* 
**Abhishek Pandey**

**Comment by abhiesa** [comment]
Sorry My Bad.

What I was doing in wrong scenario:  
query, boost and filter and what i suppose to do is query filer and boost.

Changed the order and query is running as a charm. :)

**Comment by olivere** [comment]
Hi! Can you please post the full Go code that creates the query? It's not obvious to me how you created the search query, especially the must/multi_match.

**Comment by abhiesa** [comment]
I have closed the defect.
Thanks for replying back.

It was my bad. just doing Elastic search and go from last 3 months, and ignored a simple order of execution.
With the change of execution, it is working fine correctly, or it seems to be.

Let me test it a bit more. Meantime, in github i have updated the comment.
