### ISSUE TITLE
Analyzer support.

### ISSUE THREAD

**Issue by gdrte** [olivere/elastic#230]
I am wandering for the Analyzer support(https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-analyzers.html)  in  elastic.v3. I didn't found any api related. If I am mistaken, can you please point me to some example?

Thanks in advance.

**Comment by olivere** [comment]
Elastic is a client to the REST API of Elasticsearch. Which API endpoint are you missing?

**Comment by gdrte** [comment]
Apologies, I found the api. I was just looking to create an index with analyzer.
