### ISSUE TITLE
BulkService "After" function requests parameter is empty

### ISSUE THREAD

**Issue by dimfeld** [olivere/elastic#231]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[X] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)

### Please describe the expected behavior
BulkService `After` requests parameter contains the requests that were sent.

### Please describe the actual behavior
The requests parameter is a zero-length slice.

Here are some simple logs I added in my code to illustrate the problem:
```
I0224 23:21:14.877035   29669 esindexer.go:77] requests contains 0 items
I0224 23:21:14.877098   29669 esindexer.go:78] response.Items contains 2000 items
```

### Any steps to reproduce the behavior?
Run a bulk request with an After step. Note that requests is empty.

I think this is because the end of `BulkService.Do` calls `reset` which resets the requests array, but `bulkWorker.commit` still references `w.service.requests` when calling `afterFn`. Since `Do()`and `reset` create a new list for `requests` instead of modifying it, this is probably as simple as saving a copy of `w.service.requests` before calling `Do()` and then using that saved copy in the call to `afterFn`. I'm not completely sure though. What do you think?

**Comment by olivere** [comment]
Hi there! Sorry for the late reply. Looks like an error.

It's correct that the Bulk service resets the given requests slice. The official clients do the same. But of course, it shouldn't be reset before calling `After`.

TBH I don't quite like the `BulkProcessor` API as it is now. The error case with the `After` and `Before` callbacks are cumbersome and resemble the Java approach; they're not very Go-like. The `After` callback e.g. desperately needs a pointer to its `BulkProcessor` to be able to re-add failed documents. BulkProcessor is nice for fire-and-forget bulk indexing though.

Having said all that: Yes, it's a bug and I will fix it. However, expect some more changes to the Bulk Procesor.

**Comment by dimfeld** [comment]
Yeah, I can see where you're coming from. I built my `After` function around an object that has a reference to the client, which works out well, but having the client included in the function call would be even better. I'm using glide for vendoring so will be able to adapt to any API changes on my own time :) Thanks for building this; aside from this minor hiccup it's working great!

**Comment by olivere** [comment]
Fixed in v2 by [this commit](https://github.com/olivere/elastic/commit/2c5a3105cd1054dbd60d0f402c6218031a652362) and in v3 by [this](https://github.com/olivere/elastic/commit/ea60f14deda82f645e0221894b3a9af6b0c76819). See also #238.

**Comment by dimfeld** [comment]
Thanks @olivere and @idubinskiy!
