### ISSUE TITLE
net/context support

### ISSUE THREAD

**Issue by rs** [olivere/elastic#239]
Services could expose a `DoC(ctx context.Context)` method in addition to their `Do` command. When a context is passed, the underlaying HTTP request would handle the context's cancellation by using [ctxhttp](https://godoc.org/golang.org/x/net/context/ctxhttp).

**Comment by olivere** [comment]
Yes, that seems like a very good idea. Maybe we should wait a bit until the dust settles about `context.Context` being added to `net/http` in 1.7 (maybe). I'm not up to date, but I remember there was a discussion about that recently.

**Comment by rs** [comment]
I see no sign of `net/context` being integrated into 1.7 unfortunately :/

**Comment by olivere** [comment]
It is discussed in [various](https://github.com/golang/go/issues/12438#issuecomment-161745446) [places](https://www.reddit.com/r/golang/comments/46bd5h/ama_we_are_the_go_contributors_ask_us_anything/d03vgkn) by people from the core team. But you're right: Nothing is set in stone at this point in time.

**Comment by olivere** [comment]
Just two quick remarks:

1. I expect you want to use it for cancelable requests, correct? Depending on the implementation, that's quite some work as we have many endpoints. So I think I should focus on the ones that would benefit the most. Which are the endpoints you have in mind? Search, I suppose. Anything else?

2. If you want search timeouts, there's already a way. ES supports a [timeout](https://www.elastic.co/guide/en/elasticsearch/reference/2.2/search-request-body.html#_parameters_5) parameter that is exposed e.g. in the [Search service](https://github.com/olivere/elastic/blob/release-branch.v3/search.go#L79) and in [Search source](https://github.com/olivere/elastic/blob/release-branch.v3/search_source.go#L105). Maybe that'll already work for you.

**Comment by rs** [comment]
I'm using you lib in this project: https://github.com/rs/rest-layer-es

I already implemented timeout respecting context's deadline: https://github.com/rs/rest-layer-es/blob/master/util.go#L80

Now I'd like to respect cancellation as you mentioned in you point 1. The most obvious endpoints are `Search`, `Get` and `MultiGet`. `Bulk` would be my next, then `Scroll` and finally `Update` and `Delete`.

**Comment by olivere** [comment]
I implemented the basics in `Client` and for the Search service in the [ctxhttp branch](https://github.com/olivere/elastic/tree/ctxhttp). Will you have a look?

**Comment by rs** [comment]
Looks great :)

**Comment by olivere** [comment]
Update: [Proposal to add net/context to stdlib](https://github.com/golang/go/issues/14660).

**Comment by olivere** [comment]
It's been a looong time, but finally, in 3.0.48 you can use `context.Context` will all services in Elastic (see [73e440](https://github.com/olivere/elastic/commit/73e440e0b18e72fc0ee22b002d67947c61498a39). Simply use `<Service>.DoC(context.Context)` instead of `<Service>.Do()` to pass a context.

I will publish 3.0.48 soon. It is for Elasticsearch 2.x only.

**Comment by rs** [comment]
Awesome! Are you going to add it to .v3?

**Comment by olivere** [comment]
Yes. It will be for `elastic.v3` only. I will only backport to `elastic.v2` if it's really necessary. I'm unsure what to do about it in `elastic.v5`. Time will tell. ;-)
