### ISSUE TITLE
BulkUpdateRequest puts upsert on the wrong line

### ISSUE THREAD

**Issue by fcheslack** [olivere/elastic#240]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[x] elastic.v3 (for Elasticsearch 2.x)

### Please describe the expected behavior
According to https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html#bulk-update the upsert belongs with the payload data on the second line of the bulk update request.

### Please describe the actual behavior
The upsert is included in the first line of the bulk update request.

### Any steps to reproduce the behavior?
Seems straightforward in the code, intentionally being put on the first line, such that it happens with any BulkUpdateRequest with an upsert. I'm filing an issue instead of a pull request because of the decent chance I don't properly understand the bulk api. Simply moving the upsert from the command map to the source map in bulk_update_request.go seems eliminates the errors I was getting.

**Comment by olivere** [comment]
I'm sorry but I don't think I understand. Can you post actual code so that I can reproduce the problem?

**Comment by fcheslack** [comment]
Sorry about that

`
params := map[string]interface{}{
	"itemID": itemGID,
}
upsert := map[string]interface{}{
	"items": []string{itemGID},
}
r := elastic.NewBulkUpdateRequest().
	Index(indexName).
	Type("item").
	Id(itemID).
	Script(elastic.NewScriptFile("appendItemID").Params(params)).
	Upsert(upsert)
`

produces 
`
{"update":{"_id":"<XXXX>","_index":"indexName","_type":"item", "upsert":{"items":["<ZZZZ>"]}}}
{"script":{"file":"appendItemID","params":{"newItemID":"<ZZZZ>"}}}
`

but I think it should produce
`
{"update":{"_id":"<XXXX>","_index":"indexName","_type":"item"}}
{"script":{"file":"appendItemID","params":{"newItemID":"<ZZZZ>"}},"upsert":{"items":["<ZZZZ>"]}}
`

**Comment by fcheslack** [comment]
Sorry about that

	params := map[string]interface{}{
		"itemID": itemGID,
	}
	upsert := map[string]interface{}{
		"items": []string{itemGID},
	}
	r := elastic.NewBulkUpdateRequest().
		Index(indexName).
		Type("item").
		Id(itemID).
		Script(elastic.NewScriptFile("appendItemID").Params(params)).
		Upsert(upsert)

produces 

	{"update":{"_id":"<XXXX>","_index":"indexName","_type":"item", "upsert":{"items":["<ZZZZ>"]}}}
	{"script":{"file":"appendItemID","params":{"newItemID":"<ZZZZ>"}}}


but I think it should produce

	{"update":{"_id":"<XXXX>","_index":"indexName","_type":"item"}}
	{"script":{"file":"appendItemID","params":{"newItemID":"<ZZZZ>"}},"upsert":{"items":["<ZZZZ>"]}}

**Comment by olivere** [comment]
Thanks, that helped. And at first sight: It looks like a bug. Will look into it.

**Comment by fcheslack** [comment]
Thanks for the quick answer.
This is what I think it should be doing:
https://github.com/fcheslack/elastic/commit/c6593b60f93df15a5c51c2f5a4ff08613a9ba5f8

**Comment by olivere** [comment]
Yes, I agree. I always look at the Java code as the (good) documentation tends to be rather high level. But it seems like what you've proposed is the right solution. However, it's late here, and I will look into it later this week. Sorry.

**Comment by fcheslack** [comment]
Not a problem at all. Your responsiveness is already stunning to me, and I'm deeply impressed by the progress you've made on this library since the first time I looked into it.

I appreciate your efforts tremendously. Thank you.
