### ISSUE TITLE
Support for Fuzziness in Completion Suggester

### ISSUE THREAD

**Issue by vsiv** [olivere/elastic#246]
### Which version of Elastic are you using?
[x] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
Missing fuzzy queries support for completion suggestor - https://www.elastic.co/guide/en/elasticsearch/reference/1.7/search-suggesters-completion.html#fuzzy

@olivere is it possible to add it, it should be a quick add, can submit a pull request. Its a must have for us. Thanks.

**Comment by olivere** [comment]
@vsiv Anything missing in [FuzzyCompletionSuggester](https://github.com/olivere/elastic/blob/release-branch.v2/suggester_completion_fuzzy.go)?

**Comment by vsiv** [comment]
ooh, I completely missed that. That should do it. I thought it would have been a property of CompletionSuggester. Closing the issue. Thanks!
