### ISSUE TITLE
Expose JSON Elastic Query String

### ISSUE THREAD

**Issue by kylebrandt** [olivere/elastic#25]
I would like to be bale to present the elastic query that is generated to my program (which debug doesn't really let me do). Could searchSource be exported (or a method to access it?).

**Comment by olivere** [comment]
PR #20 asked for the same, so I'll probably add something like that soon.

I used `Pretty(true).Debug(true)` in my code, but that's not perfect. I'm thinking of adding a `log.Logger` to the client.

**Comment by olivere** [comment]
As a workaround, you can always serialize the SearchSource with something like this:

```go
ss := NewSearchSource().
// set ss fields
data, _ := json.MarshalIndent(ss.Source(), "", "  ")
log.Printf("%s\n", string(data))
```

**Comment by olivere** [comment]
Does [this commit](https://github.com/olivere/elastic/commit/9d576a11aa5aadb59b33cd5550f3eb5daed55706) solve your issue? If not, re-open.

**Comment by kylebrandt** [comment]
@olivere Can I access the source of a query generate by the normal API? So basically I'd like to:

```
query_string := s.GetSource()
s.Do()
...
```

So I'm not looking to build a raw query at the moment, but rather get the raw query from the search service when it has been generated via code.

**Comment by kylebrandt** [comment]
FYI I don't think I can reopen this

**Comment by olivere** [comment]
I hesitate from adding a getter to the (otherwise setter-only) SearchService. So I did it the other way round: You create the search query via `SearchSource` (a builder, basically), then pass it to `SearchService`. Like so:

```go
// Create your search request
ss := elastic.NewSearchSource().Query(elastic.NewMatchAllQuery()).From(0).Size(10)
data, _ := json.Marshal(ss.Source())
fmt.Printf("%s", string(data))
...
// Use ss in search
res, err := client.Search().SearchSource(ss).Do()
...
```

Does that make sense to you?

See also the discussion in #20.

**Comment by olivere** [comment]
Re: Re-open... interesting, but [true](http://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github). Anyway, got it on my radar.

**Comment by kylebrandt** [comment]
Okay this works. Make things a little bit more messy on my end, but I
understand you argument as given in #20. Thanks!
