### ISSUE TITLE
Sniffing Fails on Complex Hostnames

### ISSUE THREAD

**Issue by tebriel** [olivere/elastic#251]
### Which version of Elastic are you using?

- [ ] elastic.v2 (for Elasticsearch 1.x)
- [x] elastic.v3 (for Elasticsearch 2.x)

Using elasticsearch 2.2.1

### Please describe the expected behavior

It should be able to split and pick the hostname or the IP address (unsure which is the proper to choose) from the http_address section.

### Please describe the actual behavior

It grabs the entire http_address and attempts to connect to it:

> 2016/03/25 15:40:33 elastic: http://myelk.local/10.1.0.24:9200 joined the cluster
> F0325 15:40:34.133720   30624 company_volume.go:57] Couldn't connect to ES: no Elasticsearch node available

### Any steps to reproduce the behavior?

When sniffing the connection to determine what the http address is, the client takes into account the condition where inet is present in the http_address, but not when there is a hostname + ip address.

Here's an example from http://myelk.local:9200/_nodes/Hathor/http?pretty=1

```
{
  "cluster_name" : "myelk",
  "nodes" : {
    "CIH2quEoTpqkR_UV4wI3oQ" : {
      "name" : "Hathor",
      "transport_address" : "10.1.0.24:9300",
      "host" : "10.1.0.24",
      "ip" : "10.1.0.24",
      "version" : "2.2.1",
      "build" : "d045fc2",
      "http_address" : "myelk.local/10.1.0.24:9200",
      "attributes" : {
        "master" : "true"
      },
      "http" : {
        "bound_address" : [ "[::]:9200" ],
        "publish_address" : "10.1.0.24:9200",
        "max_content_length_in_bytes" : 524288000
      }
    }
```

Elasticsearch-py [handles this](https://github.com/elastic/elasticsearch-py/blob/6e94bf76adbbbb2fe5b927a3933ed535cd738387/elasticsearch/transport.py#L221-L238) by splitting the url on `/`, which is probably what is needed.

The [offending code](https://github.com/olivere/elastic/blob/8ab36d032a9eaeb3127c4f56e6e5bec665959a32/client.go#L795-L828) doesn't seem to take the `/` into account.

To accomplish this configuration in Elasticsearch, I have this set: `-Des.network.bind_host="0.0.0.0" -Des.network.publish_host=myelk.local` (it runs in docker so it has a different bind_host than publish_host, as publish_host is the docker_host).

**Comment by olivere** [comment]
Thanks for reporting. Will look into it and strive to do the same as the official clients.

**Comment by tebriel** [comment]
@olivere thanks! Love the client.

**Comment by olivere** [comment]
@tebriel Just released a new client. I hopefully fixed it correctly. Can you please try again?

**Comment by tebriel** [comment]
@olivere I'll try to do it today, if not I'll do it on Monday. Wow thanks for the fast turnaround!

**Comment by tebriel** [comment]
Confirmed working. Thank you! Sorry for the slow turnaround!



On Mar 25, 2016, at 5:10 PM, Oliver Eilhard <notifications@github.com<mailto:notifications@github.com>> wrote:


@tebriel<https://github.com/tebriel> Just released a new client. I hopefully fixed it correctly. Can you please try again?
