### ISSUE TITLE
Bulk Processor: Change in EstimatedSizeInBytes calculation causes immense slowdown

### ISSUE THREAD

**Issue by dimfeld** [olivere/elastic#252]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[X] elastic.v2 (for Elasticsearch 1.x)
[X ] elastic.v3 (for Elasticsearch 2.x)

### Please describe the expected behavior
Performance should about the same as before commit 56384553f13a5157c520f4ad78dd303ac8950030.

### Please describe the actual behavior
Bulk index performance is about 400x slower in my usage.

### Any steps to reproduce the behavior?
 
I'm using 8 workers with a BulkActions setting of 2000. The documents themselves are on the small side, with approximate 8 fields each. I'm also running with GOGC=500 which helps a lot with reducing percentage of time in GC here.

Since commitRequired is called every time a new request comes in, the commit referenced above effectively changes the algorithmic complexity from O(n), performing 1 size calculation on each request object, to O(n^2), recalculating for all queued requests each time a new request comes in. I narrowed it down to this particular commit, and in my usage case I see the performance approximately 400x slower, from 20000-30000 documents indexed per second down to 60-70.

**Comment by dimfeld** [comment]
Looks related to #250?

**Comment by olivere** [comment]
Yes. There was a change there recently. Seems like a regression. I will look into it tomorrow.
