### ISSUE TITLE
The example repository for Docker/OSX is out of date with newer versions

### ISSUE THREAD

**Issue by EwanValentine** [olivere/elastic#256]
You're using... 
```
os.Getenv("ELASTICSEARCH_PORT_9200_TCP_ADDR"),
os.Getenv("ELASTICSEARCH_PORT_9200_TCP_PORT")
``` 

to find the port and host address. As of Docker 1.10 or 1.9, you should use `elastic.SetURL("elasticsearch:9200")` I believe. 

If your docker service is named as followed... 
```
elasticsearch:
  // etc
```

I've just stumbled across this issue, if I can figure out how to get it working without using environment variables, I'll update this issue. Thanks!

**Comment by olivere** [comment]
I think Docker Compose v2 format sets up a network like this: https://docs.docker.com/compose/networking. If you could check that and provide a PR, I'd be happy to merge that.

**Comment by olivere** [comment]
I've just updated the [elastic-with-docker repository](https://github.com/olivere/elastic-with-docker) to use the latest version of Docker / Docker Compose.

Please file an issue at that repository next time. It keeps things together. Thanks for reporting.

**Comment by EwanValentine** [comment]
Thanks! Great work! And will do.
