### ISSUE TITLE
Can't create a new client when using custom domain name

### ISSUE THREAD

**Issue by FrenchBen** [olivere/elastic#259]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

- [ ] elastic.v2 (for Elasticsearch 1.x)
- [x] elastic.v3 (for Elasticsearch 2.x)

### Please describe the expected behavior
When creating a new client, I should be able to pass my custom domain/port to it and get a successful connection.
```
logElastic := "http://elasticsearch:9200"
client, err := elastic.NewClient(elastic.SetURL(logElastic))
logrus.Infof("New client: %v - url: %v", client, logElastic)
if err != nil {
  logrus.Fatal(err)
}
```

### Please describe the actual behavior
The client returns nil :(

### Any steps to reproduce the behavior?
* Create a new elasticsearch instance with a custom domain of `http://elasticsearch:9200`
* Create a new client with the above url and see that it fails with:
```
INFO[0005] New client: <nil> - url: http://elasticsearch:9200
FATA[0005] no Elasticsearch node available
make: *** [cli-dev] Error 1
```
* Create a curl request for the same url and see it work:
```
curl -i http://elasticsearch:9200
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Content-Length: 313

{
  "name" : "Dusk",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.3.0",
    "build_hash" : "8371be8d5fe5df7fb9c0516c474d77b9feddd888",
    "build_timestamp" : "2016-03-29T07:54:48Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.0"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by olivere** [comment]
Odd... I do that all the time, so maybe it's a regression.

But it looks like the URL is not the source of the problem.

Are you [using Docker](https://github.com/olivere/elastic/wiki/Docker)? Does the Wiki section on [connection problems](https://github.com/olivere/elastic/wiki/Connection-Problems#how-to-figure-out-connection-problems) help? Can you temporarily disable sniffing to see if that makes a difference  (see [here](https://github.com/olivere/elastic/wiki/Sniffing))?

**Comment by FrenchBen** [comment]
I am indeed using this stack on Docker - Thanks for the different links for help, I'll see if I can get it sorted it out.

**Comment by FrenchBen** [comment]
A bit more info - I used your docker-compose setup, which uses the new network stuff. 
Doing so, I can get my app to connect. Using the old stuff, when I do:
```
ips, err := net.LookupIP("elasticsearch")
```
I get the following error:
```
FATA[0010] lookup elasticsearch on 192.168.99.100:53: no such host
```

Long story short it seems to be an issue within the container networking, not the actual lib. Thanks for helping me troubleshoot this.

**Comment by olivere** [comment]
If you enable sniffing (the default), the URL you specify is merely the starting point of a lookup process. It uses your URL to do a cluster_info API calls to get all nodes of the cluster. Then it uses all the found nodes to run requests. If the nodes returned by the cluster info API are not accessible, you've got a problem. So you need to ensure that the nodes in your cluster are available to the outside, as written in the [Docker](https://github.com/olivere/elastic/wiki/Docker) wiki entry.

**Comment by FrenchBen** [comment]
In case you were wondering I managed to get this resolved, thanks to your https://github.com/olivere/elastic-with-docker repo.
I was still using `golang:1.5-alpine` as the base image, switching that over to `golang:1.6-alpine` made everything work like magic!

Thanks for the tip.
