### ISSUE TITLE
Unchecked json.Unmarshal results in Blank Keys

### ISSUE THREAD

**Issue by kylebrandt** [olivere/elastic#26]
In elastic it is possible to have keys that are not strings. So for example, in:

```
func (a *AggregationBucketKeyItem) UnmarshalJSON(data []byte) error {
	var aggs map[string]json.RawMessage
	if err := json.Unmarshal(data, &aggs); err != nil {
		return err
	}
	a.Aggregations = aggs

	json.Unmarshal(aggs["key"], &a.Key)
	json.Unmarshal(aggs["doc_count"], &a.DocCount)
	return nil
}
```

We get an empty key result because the Unmarhsal fails, and since the code isn't checking for errors in unmarshmaling this is a silent error.

**Comment by olivere** [comment]
Can you send me your query and the results? Set `Pretty(true).Debug(true)` in the `SearchService` and paste the output (like [here](https://github.com/olivere/elastic/blob/refactor-suggesters/search_aggs_test.go#L127))?

**Comment by kylebrandt** [comment]
Head of Response, note the Keys are Ints of some sort (not quoted). 

Query:
```
{"aggregations":{"g_TargetUserName":{"aggregations":{"g_eventlog_id":{"aggregations":{"ts":{"date_histogram":{"field":"@timestamp","interval":"1m"}}},"terms":{"field":"TargetUserName"}}},"terms":{"field":"eventlog_id"}}},"query":{"range":{"@timestamp":{"from":"2015-01-08T15:54:50.750119001Z","include_lower":true,"include_upper":true,"to":"2015-01-08T16:04:50.750119001Z"}}}}
```

```
  "aggregations" : {
    "g_TargetUserName" : {
      "doc_count_error_upper_bound" : 2,
      "sum_other_doc_count" : 2487,
      "buckets" : [ {
        "key" : 5447,
        "doc_count" : 2448,
        "g_eventlog_id" : {
          "doc_count_error_upper_bound" : 0,
          "sum_other_doc_count" : 0,
          "buckets" : [ ]
        }
      }, {
        "key" : 16,
        "doc_count" : 984,
        "g_eventlog_id" : {
          "doc_count_error_upper_bound" : 0,
          "sum_other_doc_count" : 0,
          "buckets" : [ ]
        }
      }, {
        "key" : 4624,
        "doc_count" : 829,
        "g_eventlog_id" : {
          "doc_count_error_upper_bound" : 0,
          "sum_other_doc_count" : 141,
          "buckets" : [ {
            "key" : "system",
            "doc_count" : 194,
            "ts" : {
              "buckets" : [ {
                "key_as_string" : "2015-01-08T15:54:00.000Z",
```

**Comment by olivere** [comment]
Can you update and try again? Should be fixed with [this commit](https://github.com/olivere/elastic/commit/5609eefb668b1ed0f7bd00ec58e9cf9e7bc0f7ea). Reopen if necessary.

**Comment by kylebrandt** [comment]
I don't think this is going to be correct, since the key can be a number or a string (possibly other things)...

**Comment by olivere** [comment]
And in the tests, the key is indeed a string for e.g. the "users" aggregation.

**Comment by kylebrandt** [comment]
So probably an interface, and then the user has to type switch I imagine? I had another idea but can't remember now...

**Comment by olivere** [comment]
We could to that as well. And you're right in that it's better because Keys can of any type, not only strings and numbers.

However, remember that you'll then get a `float64` when decoding the "Key" in your example. A type switch is not enough.

**Comment by olivere** [comment]
Maybe we could have the best of both worlds with this.

```go
type AggregationBucketKeyItem struct {
	Aggregations

	Key       interface{}
	KeyNumber json.Number
	DocCount  int64
}
```

You could use `Key` to get to the `interface{}` while still having `KeyNumber` can be used for convenience.

```go
if bucket.Key != float64(0) {
	t.Errorf("expected %v; got: %v", float64(0), bucket.Key)
}
if got, err := bucket.KeyNumber.Int64(); err != nil {
	t.Errorf("expected %d; got: %v", 0, bucket.Key)
} else if got != 0 {
	t.Errorf("expected %d; got: %d", 0, got)
}
if bucket.KeyNumber != "0" {
	t.Errorf("expected %q; got: %q", "0", bucket.KeyNumber)
}
```

**Comment by olivere** [comment]
See [this test](https://github.com/olivere/elastic/blob/bd9d7262e855668e96299b6acc09c77f3c37fedb/search_aggs_test.go#L1747) for example usage.

Hope this is going to fix it.

Thanks for reporting.
