### ISSUE TITLE
BUG[NewTimer leaks]

### ISSUE THREAD

**Issue by wolfkdy** [olivere/elastic#260]
the problem exists for all versions of elastic clients, both 1.x and 2.x

### Steps to reproduce the behavior:
write a dead-loop to create stack-local es-clients and let them alone(let the gc deal with them), by opening the pprof port,  you will see
 3625.5  95.6%  95.6%   3783.4  99.8% time.NewTicker
something like above

### Why it happens?
According to go's official document and code comments, the Ticker object can not be collected by gc unless the Stop method is called. Unfortunately, code in both 1.x and 2.x did not call Stop anywhere.
see client.go:sniffer(), client.go:healthchecker()

**Comment by olivere** [comment]
@wolfkdy Thanks for reporting. Yes, that's wrong. I will fix it when I find some time, hopefully next weekend.

**Comment by olivere** [comment]
@wolfkdy Would you please review the changes in the above commit?

**Comment by wolfkdy** [comment]
I review it carefully and think it enough to fix the bug.
Btw, will you merge the patch into earlier versions ?

**Comment by olivere** [comment]
I will merge into v2 as well. When you then go get gopkg.in/olivere/elastic.v2 (or v3) again, then the fix is in.

**Comment by olivere** [comment]
Merged into v3 in [this commit](https://github.com/olivere/elastic/commit/86568dfd7c3b4c4aa0510c43afeecfb8af82580d). v2 should follow up shortly.
