### ISSUE TITLE
Inconsistent integer type for document version

### ISSUE THREAD

**Issue by atombender** [olivere/elastic#263]
Some fields use `int64`, some `int`. For example `BulkResponseItem` uses `int`, whereas `GetResult` uses `int64`. This is minor, but annoying.

**Comment by olivere** [comment]
@atombender Yes. I tried to fix it in the release 2 to 3, but unfortunately I missed some fields. We get another chance at the 3 to 5 migration. I don't want to introduce breaking changes in minor releases.

**Comment by atombender** [comment]
Great, thanks!

**Comment by olivere** [comment]
Missed it in the 5.0 release. Sorry.

**Comment by olivere** [comment]
I checked a few and it looks like they match the Java type in Elasticsearch (some are `long`, some are `int` in the Java source). Sometimes it's even worse, e.g. TTL in the response always seems to be `long` whereas in some APIs you can specify it as a `long` or a `string` (as in `"1d"`).

Anyway, I feel more confident in using the corresponding Go types in Elastic although I agree it's annoying.

**Comment by olivere** [comment]
Forgot to say that I'll change `Version` in `BulkResponseItem` to `int64`.
