### ISSUE TITLE
Ignore unavailable for search

### ISSUE THREAD

**Issue by bradylove** [olivere/elastic#265]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[x] elastic.v3 (for Elasticsearch 2.x)

We are looking to use elastic and as we were starting to use it we noticed there is no support for passing in custom query parameters for the search request (https://github.com/olivere/elastic/blob/release-branch.v3/search.go#L279) where we would like to send the `ignore_unavailable` query parameter (https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-index.html). Is there any way we could get support for this?

**Comment by olivere** [comment]
@bradylove Interesting. When I implemented the Search API, `ignore_unavailable` wasn't a parameter you could use for a search request. It was available [for other APIs](https://github.com/olivere/elastic/search?utf8=%E2%9C%93&q=ignore_unavailable), e.g. `IndexExists` or `IndexClose`.

Now, [`ignore_unavailable` is available](https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/search.json#L53).

So thanks for reporting: I will add it ASAP, probably over the weekend.

**Comment by olivere** [comment]
The properties are available in the next release of elastic.v3, which will be available later this weekend. Simple `go get -u gopkg.in/olivere/elastic.v3` again, and you should be set.

See [this commit](https://github.com/olivere/elastic/commit/a7a712ea29db9dd5d30b5a16f9f5f80212a541d3) for details.

**Comment by MasslessParticle** [comment]
Thank you @olivere
