### ISSUE TITLE
How to delete multiple documents? (bulk)

### ISSUE THREAD

**Issue by gm42** [olivere/elastic#266]
I have a question about bulk delete request. Ideally I would use this to submit deletion of multiple documents, but does it actually support it? Reading its source or the test source doesn't help either.

Could you please provide an example about how to perform multiple deletes with it?

### Which version of Elastic are you using?

[x] elastic.v3 (for Elasticsearch 2.x)

**Comment by olivere** [comment]
Hi there!

Does [this test](https://github.com/olivere/elastic/blob/fb3d0946b0bb6c7580bbd1a6cb9ba688469f20e4/bulk_test.go#L12-L35) answer your question?

**Comment by gm42** [comment]
Yes! Thanks, I hadn't noticed before
