### ISSUE TITLE
Bugs found in generate Source for SortInfo

### ISSUE THREAD

**Issue by brucez-isell** [olivere/elastic#267]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ *] elastic.v3 (for Elasticsearch 2.x)

### Please describe the expected behavior
when generate "nested_filter" in sort the It should looks like:
"nested_filter":{"term":{"myfield":"myvalue"}}.

### Please describe the actual behavior
when generate "nested_filter" in sort, the internal filter can't be generated correctly. It looks like:
"nested_filter":{}.

### Any steps to reproduce the behavior?
1. Create a index type with nested array field. the nested object should have 2 or more fields.
Such as type "family"

{
"sername": {
     "type":"string"
},
"children": {
  "type":"nested",
  "properties": {
      "gender":{
           "type":"string"
      },
      "name":{
           "type":"string"
      }
  }
}
}

2. Start a matchAll query and sort by one of the nested field and set the nested filter on another field.

"sort":[
    {
        "children.name":{
             "nested_path":"children",
             "nested_filter": {
                  "term":{"children.gender":"female"}
             }
         }
    }   
]

When use SortInfo.NestedFilter to set it you will find the error.

### My code change: in sort.go
in func (info SortInfo) Source() (interface{}, error)
the original code is:

    if info.NestedFilter != nil {
		prop["nested_filter"] = info.NestedFilter
	}

I changed to:

    if info.NestedFilter != nil {
		src, err := info.NestedFilter.Source()
		if err != nil {
			return nil, err
		}
		prop["nested_filter"] = src
	}

and it works.

**Comment by olivere** [comment]
Yes. That's a bug. Will fix it ASAP. Thank you!

**Comment by olivere** [comment]
3.0.32 has been released.
