### ISSUE TITLE
Unit testing Query objects

### ISSUE THREAD

**Issue by xtreme-aaron-jarecki** [olivere/elastic#268]
We're using elastic.v2 and trying to write tests that confirm our code is generating queries correctly.

We've got lower level methods that builds and returns a FilteredQuery, which in turn gets added to a SearchService, which is what we'd like to test.

What's frustrating us is that the objects in this chain store a SearchSource, which can easily be examined to determine correctness, but it is stored in a private attribute just out of reach.

Is there a correct way to determine how a query is structured without actually running it and looking at the results set?

**Comment by olivere** [comment]
What I'm currently doing in the unit tests is to compare the generated output of the queries [like this](https://github.com/olivere/elastic/blob/release-branch.v3/search_queries_bool_test.go#L29-L33).

You are guaranteed that every Query and e.g. SearchSource always have a [`Source` function](https://github.com/olivere/elastic/blob/release-branch.v3/search_source.go#L297), which returns the output to be serialized to JSON and an error (in elastic.v2 it was only JSON, without the error).

Does this help?

**Comment by olivere** [comment]
If you need to investigate the `searchSource` variable used by the `SearchService`, you could restructure your code to build a `SearchSource` first, then use [`SearchService.SearchSource`](https://github.com/olivere/elastic/blob/release-branch.v3/search.go#L42-L49) to set it (which should override all the things set in `SearchService`. You could then test `SearchSource` using the method described in the previous comment.

A workaround, yes. But I refrain from opening up internal variables. IIRC Elasticsearch once had the `SearchService` stuff in the search service, then extracted it into something similar to `SearchSource`. I'd be in trouble if they do something similar again.

**Comment by olivere** [comment]
Can we close this?
