### ISSUE TITLE
Reverse nested aggregations?

### ISSUE THREAD

**Issue by nsf** [olivere/elastic#269]
Hi. Reverse nested aggregations marked as an implemented feature. But I don't see a way to create them in the API.

https://www.elastic.co/guide/en/elasticsearch/reference/1.7/search-aggregations-bucket-reverse-nested-aggregation.html

Of course I can implement myself via Aggregation interface. But shouldn't there be `elastic.NewReverseNestedAggregation()`?

In it's simplest form it has an empty property and sub-aggs:
```js
"comment_to_issue": {
  "reverse_nested": {}, ￼
  "aggs": {
    "top_tags_per_comment": {
      "terms": {
        "field": "tags"
      }
    }
  }
}
```

But it also supports "path" option in a similar way "nested" does.

**Comment by olivere** [comment]
@nsf You're right. The creation part is missing. The only test I see is [handling the result](https://github.com/olivere/elastic/blob/fb3d0946b0bb6c7580bbd1a6cb9ba688469f20e4/search_aggs_test.go#L1830-L1853).

I will look it up in the Java source and see what other options `ReverseNested` might have, and then add it.

Thanks for reporting. And sorry for the misleading information in the README. It's hard to keep on top of the ES API; it has a big surface.

**Comment by olivere** [comment]
In 3.0.33 and 2.0.40, there's a `ReverseNestedAggregation` now. That should do the trick. Sorry it took me so long.

**Comment by nsf** [comment]
Thanks.
