### ISSUE TITLE
Problem sourcing a sorter of type NewGeoDistanceQuery

### ISSUE THREAD

**Issue by ssola** [olivere/elastic#271]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[x] elastic.v3 (for Elasticsearch 2.x)

### Please describe the expected behavior

I have an instance with Elasticsearch 2.x installed. I was able to index some data with some coordinates on it. For instance, a document looks like this:

```json
{
   "name": "Test",
   "location": {
      "lat": 30.003,
      "lon": 20.00
   }
}
```

I was able to index and search those items like this:

```go
    q := elastic.NewMatchAllQuery()
    geoQ := elastic.NewGeoDistanceQuery("location")
    qLat, _ := strconv.ParseFloat(lat, 64)
    qLon, _ := strconv.ParseFloat(lon, 64)

    geoQ.Lat(qLat)
    geoQ.Lon(qLon)
    geoQ.Distance("15km")

r, err := client.Search().Index("areas").Type("area").Query(q).PostFilter(geoQ).SortBy(sorter).From(0).Size(1).Pretty(true).Do()
```

At the end I have a result. But the problem is sorting. Basically I am trying to sort from the closest one to the farthest like this:

```go
 sorter := elastic.NewGeoDistanceSort("location")
    sorter.Point(qLat, qLon)
    sorter.Asc()
```

The problem is with the output of this query, it looks like this:

```json
{"from":0,"post_filter":{"geo_distance":{"distance":"15km","location":{"lat":51.4805,"lon":-0.09828}}},"query":{"match_all":{}},"size":1,"sort":[{"_geo_distance":{"location":[]}}]}
```

Everything related to location inside the _geo_distance object is empty.

### Please describe the actual behavior

Currently adding a new NewGeoDistanceSort sorter into the SortBy at the end the request to elasticsearch seems incorrect.

All the fields I included on that object are not visible after sourcing that Sorter. I tried printing directly on command line the sorter but it's almost empty. Only the FileName is visible.

I suspect it's just getting the default values creating the GeoDistanceSort struct. Somehow, sourcing that struct isn't adding the proper values.

### Any steps to reproduce the behavior?

- Add some items into an index with some location data
- Try to create a query like the one I provided above those lines
- You should see the missing data on the _geo_distance json object

**Comment by olivere** [comment]
Can you try the following instead?

```
sorter := elastic.NewGeoDistanceSort("location")
sorter = sorter.Point(qLat, qLon)
sorter = sorter.Asc()
```

or 

```
sorter := elastic.NewGeoDistanceSort("location").Point(qLat, qLon).Asc()
```

The `GeoDistanceSort` type is a value object, so it returns a copy of the previous value, which you swallowed in your code.

**Comment by ssola** [comment]
Yes that works. Thanks!.

I am not sure why I didn't tried that, I saw each func returns the objet itself.

By the way, I would like to collaborate maybe writing some extra documentation in the wiki, like this Geo queries. I think it can be useful for other people to see more examples.

**Comment by olivere** [comment]
Contributions are always welcome, as well as brave testers ;-)
