### ISSUE TITLE
Branch for Elasticsearch ver. 5?

### ISSUE THREAD

**Issue by kf6nux** [olivere/elastic#272]
Elasticsearch version 5 now in alpha.

Should we open a development branch?

**Comment by olivere** [comment]
There will be a `release-branch.v5`. I didn't test ES 5 alpha yet, but it could be that v3 "just works" (tm). I see v5 more as a chance to do breaking changes.

However, I'm on vacation for the next 2 weeks, so don't expect anything in the very near future.

**Comment by olivere** [comment]
There's a [release-branch.v5](https://github.com/olivere/elastic/tree/release-branch.v5) now which anyone interested can follow.

But we've still got a long way to go until 5.0 is stable.
