### ISSUE TITLE
Add Support for regexp Query

### ISSUE THREAD

**Issue by kylebrandt** [olivere/elastic#28]
Let me know if I'm getting annoying and I can try to get caught up on the library to contribute :-/ But now I'm also looking for the rexep Query.

The regexp filter is working as expected - thanks a lot for that

**Comment by olivere** [comment]
No worries. I want it to be feature-complete... although I'm pretty sure I won't get to that point anytime soon. :-)

However, if you want to try, adding filters and queries is a trivial task (to be honest). Copy an existing one and change it accordingly, then send me a PR. The hard thing is to make it compatible with all the features that ES has, which is much much more than you see in the official documentation. So you have to work with the Java source code and see how things are implemented there.
