### ISSUE TITLE
How to provide a TYPE QUERY to v2 Reindexer?

### ISSUE THREAD

**Issue by rrfeng** [olivere/elastic#280]
I am using elastic.v2 (for Elasticsearch 1.x), and want to reindex a old_index to new_index, but new_index should only contains the `_type: course` documents from old_index.

I found a TypeQuery in v3, but there is not in v2.
so what should I do? If no query provided, the old_index contains billions documents, I don't want to scan all of them.

**Comment by olivere** [comment]
Sorry, I'm on vacation this week. So very short...

You could use a TypeFilter in v2. You should also take a look at Reindexer. Read the tests for usage information.

**Comment by rrfeng** [comment]
thks，I use TermQuery：_type to make it。
