### ISSUE TITLE
Named range filters aggregation

### ISSUE THREAD

**Issue by jamiecuthill** [olivere/elastic#283]
### Which version of Elastic are you using?
elastic.v3 (for Elasticsearch 2.x)

### Please describe the expected behavior
I should be able to name my range filters as per the example in the code comment (search_aggs_bucket_filters.go:48-61)

I want to give keys to the range filters I add to a filters aggregation, for example:
```go
Aggregation("someagg", elastic.NewFiltersAggregation().
			Filters(
				elastic.NewRangeQuery("created").From("now-12M/w").To("now/w"),
				elastic.NewRangeQuery("created").From("now-12M-1w/w").To("now-1w/w"),
			)
)

```
Which marshals to a slice of filters but I need to give an index key to these ranges such as:

```json
"someagg": {
                "filters": {
                    "filters": {
                        "current": {
                            "range": { "created": { "from": "now-12M/w", "to": "now/w" } }
                        },
                        "prev": {
                            "range": { "created": { "from": "now-12M-1w/w", "to": "now-1w/w" } }
                        }
                    }
                }
}

```

### Please describe the actual behavior
The filter is marshalled as

```json
"someagg": {
                "filters": {
                    "filters": [
                         {
                            "range": { "created": { "from": "now-12M/w", "to": "now/w" } }
                        },
                        {
                            "range": { "created": { "from": "now-12M-1w/w", "to": "now-1w/w" } }
                        }
                    ]
                }
}

```

**Comment by olivere** [comment]
You're correct. The Java API provides the same options and splits the filters into `keyedFilters` and `nonKeyedFilters` (see [here](https://github.com/elastic/elasticsearch/blob/2.x/core/src/main/java/org/elasticsearch/search/aggregations/bucket/filters/FiltersAggregationBuilder.java#L36)). It changed again [in master](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/search/aggregations/bucket/filters/FiltersAggregatorBuilder.java#L46). I will try to find a way to do something similar in Elastic.

**Comment by olivere** [comment]
I'm in the process of releasing 3.0.37 that contains the ability to use named filters. See [d157b77](https://github.com/olivere/elastic/commit/d157b778b286d54ad6a84dd5872fe97e35906042) for changes and usage examples.

**Comment by jamiecuthill** [comment]
Excellent, thanks @olivere

**Comment by paulocezar** [comment]
can we get this behaviour on elastic.v2 as well?

**Comment by olivere** [comment]
v2.0.47 has just been pushed. That release contains a backport of the named/unnamed filters aggregations from v3. See [3f06295](https://github.com/olivere/elastic/commit/3f0629529e5f0ac67d7a16566e478aa7ec6102aa).
