### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by abonec** [olivere/elastic#284]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[x] elastic.v3 (for Elasticsearch 2.x)
### Please describe the expected behavior

Query Should send to the Node
### Please describe the actual behavior

panic: runtime error: invalid memory address or nil pointer dereference
...
panic(0x9d0400, 0xc82000a260)
    /usr/local/go/src/runtime/panic.go:481 +0x3e6
gopkg.in/olivere/elastic%2ev3.(_Client).PerformRequest(0x0, 0xaa5dc0, 0x4, 0xc8201de400, 0x11, 0xc8201dc600, 0x8c3b20, 0xc8201dc630, 0x0, 0x0, ...)
    /home/abonec/sandbox/go/src/gopkg.in/olivere/elastic.v3/client.go:1042 +0x120d
gopkg.in/olivere/elastic%2ev3.(_SearchService).Do(0xc82021e160, 0xc820121d90, 0x0, 0x0)
    /home/abonec/sandbox/go/src/gopkg.in/olivere/elastic.v3/search.go:343 +0x1a1
main.Database.GetEta(0x0)
    /home/abonec/sandbox/go/src/github.com/abonec/eta_service_go/database.go:38 +0x741
main.main()
    /home/abonec/sandbox/go/src/github.com/abonec/eta_service_go/server.go:22 +0xe7
exit status 2
### Any steps to reproduce the behavior?

Clone and run this project https://github.com/abonec/eta_service_go
This line of code send the request https://github.com/abonec/eta_service_go/blob/37eee938eb1185dacb6424c4276afe2bc5eb0f3f/database.go#L33-38

I newbie in go and I think this can be fairly simple explanation but I can't undersand why compiler panic on    c.mu.RLock() and why mutex is null. And where mutex should actually be initialized. In NewClient function is nothing.

**Comment by olivere** [comment]
If you're using pointer receivers, everything should work as expected:

```go
package main

import (
	"encoding/json"
	"fmt"

	"gopkg.in/olivere/elastic.v3"
)

type Database struct {
	source *elastic.Client
}

func (v *Database) Init() {
	client, err := elastic.NewClient()
	if err != nil {
		panic(err)
	}
	v.source = client
}

func PrintQuery(query elastic.Query) {
	src, err := query.Source()
	if err != nil {
		panic(err)
	}
	data, err := json.Marshal(src)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(data))
}

func (v *Database) GetEta() {
	query := elastic.NewBoolQuery()
	query = query.Must(elastic.NewTermQuery("vacant", true))
	distance := elastic.NewGeoDistanceQuery("location").Distance("40 km").Point(55.662987, 37.656230)
	query = query.Filter(distance)
	PrintQuery(query)
	_, err := v.source.Search().Index("cabs").Type("cab").Query(query).Do()
	if err != nil {
		panic(err)
	}
}

func InitDatabase() *Database {
	database := &Database{}
	database.Init()
	return database
}
```

Maybe the [Go FAQ](https://golang.org/doc/faq#methods_on_values_or_pointers) helps you understand.

Let me know if I can help, otherwise close the issue.

**Comment by abonec** [comment]
Oh. It's my stupid fault) Sorry. Thx for help, forking fine.

**Comment by Mornor** [comment]
@olivere I got exactly the same issue but can't figure out what is my issue there. 
```
client, err := elastic.NewClient(elastic.SetURL("Elastic_Host"))
if err != nil {
    fmt.Println("Error when connecting Elasticsearch host"); 	
}
```

Which result by: 

> Error when connecting Elasticsearch host
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x81f43]

I know for a fact that the Elasticsearch_host exists. 

Could you may be help me to find the issue here?
Many thanks!

**Comment by olivere** [comment]
@Mornor A segmentation fault is very strange here...

The URL should be something like `http://localhost:9200`, not `"Elastic_Host"`.

What's the output of 

```
ping Elastic_Host
```

in the terminal?

**Comment by Mornor** [comment]
@olivere The host is something `host.blabla.io` (Without http://)
The result from the ping indicate is a success.

**Comment by olivere** [comment]
Can you please post a complete, runnable Go source code.

**Comment by Mornor** [comment]
Sure

package main

import "fmt"
import "flag"
import "os"
import "time"
import "golang.org/x/net/context"
import elastic "gopkg.in/olivere/elastic.v5"
import blackfriday "github.com/russross/blackfriday"

func main() {

	// Define the command line arguments
	subjectPtr 	:= flag.String("s", "default_subject", "describes the event")
	tagPtr 		:= flag.String("t", "default_tag", "tag of the event")
	markdownPtr	:= flag.String("m", "default_markdown", "markdown of the event") 

	// Parse the received flags
	flag.Parse()

	user := os.Getenv("LOGNAME")
    hostname, err := os.Hostname()
    if err != nil {
       panic(err)
    }
    sendEvent(user, hostname, *subjectPtr, blackfriday.MarkdownBasic([]byte(*markdownPtr)), *tagPtr, time.Now())
}

func sendEvent(user string, host string, subject string, desc []byte, tags string, timestamp time.Time) {

	// Config (where to send args)
	var index string = "events"
	var nodes [2]string
	nodes[0] = "host1.blabla.io"
	nodes[1] = "host2.blabla.io"

	// Define an event
	type Event struct {
    	user 		string
    	host 		string
    	title 		string
    	desc 		[]byte
    	tags 		string
    	timestamp 	time.Time
	}

	// Define an elastic client 
	client, err := elastic.NewClient(elastic.SetURL(nodes[0]))
	if err != nil {
    		fmt.Println("Error when connecting Elasticsearch host"); 	
	}

       // etc ... 
}

**Comment by olivere** [comment]
I changed the URL to `http://localhost:9200` and did some formatting. That worked okay.

```sh
$ go run conn.go
2016/11/15 16:47:30 Connected
```

```
package main

import (
	"flag"
	"log"
	"os"
	"time"

	blackfriday "github.com/russross/blackfriday"
	elastic "gopkg.in/olivere/elastic.v5"
)

func main() {

	// Define the command line arguments
	subjectPtr := flag.String("s", "default_subject", "describes the event")
	tagPtr := flag.String("t", "default_tag", "tag of the event")
	markdownPtr := flag.String("m", "default_markdown", "markdown of the event")

	// Parse the received flags
	flag.Parse()

	user := os.Getenv("LOGNAME")
	hostname, err := os.Hostname()
	if err != nil {
		panic(err)
	}
	sendEvent(user, hostname, *subjectPtr, blackfriday.MarkdownBasic([]byte(*markdownPtr)), *tagPtr, time.Now())
}

func sendEvent(user string, host string, subject string, desc []byte, tags string, timestamp time.Time) {

	// Config (where to send args)
	var index string = "events"
	var nodes [2]string
	nodes[0] = "http://localhost:9200"
	nodes[1] = "host2.blabla.io"

	// Define an event
	type Event struct {
		user      string
		host      string
		title     string
		desc      []byte
		tags      string
		timestamp time.Time
	}

	// Define an elastic client
	client, err := elastic.NewClient(elastic.SetURL(nodes[0]), elastic.SetSniff(false))
	if err != nil {
		log.Fatalf("Error when connecting Elasticsearch host: %v", err)
	}
	log.Println("Connected")

	_ = client
	_ = index

}
```

**Comment by Mornor** [comment]
@olivere Indeed, by doing it with locally it works. 

I guess it is an issue with the Elasticsearch instance. 
Sorry to have bother you with that :( 

Many thanks for your precious help!

**Comment by olivere** [comment]
No. Indeed there's something wrong with normalization.  Looking into it... thanks

**Comment by olivere** [comment]
Wait, what?!

```go
package main

import (
	"fmt"
	"log"
	"net/url"
)

func main() {
	urls := "localhost:9200"
	u, err := url.Parse(urls)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("Scheme = %q\n", u.Scheme)
	// Prints: localhost
}
```

Oh man...

**Comment by olivere** [comment]
You have to specify a protocol in order to make it work. Using `"localhost:9200"` will return a Scheme of `"localhost"` with `url.Parse(...)`.

**Comment by wings-xue** [comment]
how to close the client if write by pointer?
such as 	defer client.Stop()

**Comment by olivere** [comment]
I don’t understand. To stop a client, call client.Stop(), as you said.
