### ISSUE TITLE
Search with raw JSON request body

### ISSUE THREAD

**Issue by jamesrose** [olivere/elastic#286]
### Which version of Elastic are you using?

[X] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)

### Please describe the expected behaviour

I would like to execute a query with the raw request body:

`{
    "query": {
        "bool" : {
            "must" : {
                "query_string" : {
                    "query" : "some query string here"
                }
            },
            "filter" : {
                "term" : { "user" : "kimchy" }
            }
        }
    }
}`

Is this possible with this package?

**Comment by olivere** [comment]
Yes, you can. There are several options.

1. Use the [`Source`](https://github.com/olivere/elastic/blob/release-branch.v2/search.go#L54-L59) func of `SearchService`. Simply pass a string.
2. Use the [`PerformRequest`](https://github.com/olivere/elastic/blob/release-branch.v2/client.go#L985) func of `Client` and pass any HTTP method, URL, query params, and body to it. The body can be a string, an `io.Reader`, or an `interface{}` (the latter will be serialized into JSON).

HTH.

**Comment by jamesrose** [comment]
@olivere Fantastic. Thank you!

**Comment by akotlar** [comment]
Could you please provide an example. Having trouble with this. Goal is to use with a Scan or Scroll function. I need to be able to search any valid string which is passed by the client.

I've tried using SearchService, does not help in case of Scan or Scroll. I don't understand how to use PerformRequest with Scan queries (or Scroll queries). 

In short, I think this is an excellent library. At the same time, it makes very difficult the most basic use case, which is search raw JSON. I expect to be able to pass an arbitrary valid string, or at least a map[string]interface{} representing that JSON, and search that. I suspect I am missing something, but have spent a day, and found the library very frustrating to use for this purpose. Any help would be appreciated.

```go 
    searchSource := elastic.NewSearchService(client)
    searchSource.Source(*queryString)

    // no way to use in client.Scan, because source property is not exported
```

**Comment by olivere** [comment]
Out of my mind, `RawStringQuery` should do the job for passing queries as strings:

```go
s := `{ "bool" : { "must" : { "query_string" : { "query" : "some query string here" } }, "filter" : { "term" : { "user" : "kimchy" } } } }`
res, err := client.Search().Query(elastic.NewRawStringQuery(s)).Do()
if err != nil { ... }
// res is your search result
```

The `Source` function in `SearchService` should also work. It allows you to specify the body of the HTTP request to be sent to ES. You can pass a `string`, an `io.Reader` or anything that can be serialized into JSON. It's as simple as that:

```go
s := `{"query": { "bool" : { "must" : { "query_string" : { "query" : "some query string here" } }, "filter" : { "term" : { "user" : "kimchy" } } } } }`
res, err := client.Search().Source(s).Do()
if err != nil { ... }
// res is your search result
```

Again, untested. See the tests if you're unsure about the syntax.

If you only need to send a string, you probably don't need Elastic (besides the load-balancing). Simply send a HTTP request to Elasticsearch.

**Comment by akotlar** [comment]
Unfortunately, this does not work with anything that specifies properties other than query. Such as sort, etc. Those will _always_ return a 400 request failure, even with perfectly valid JSON. Testing this is trivial, just pass a valid query with a sort key.

I think the solution you have in SearchService isn't terribly elegant if we want to use it across all services:

```
// Perform request
	var body interface{}
	if s.source != nil {
		body = s.source
	} else {
		src, err := s.searchSource.Source()
		if err != nil {
			return nil, err
		}
		body = src
	}
	res, err := s.client.PerformRequestC(ctx, "POST", path, params, body)
```

This can be more succinctly expressed if you allow SearchSource to take the source directly from map[string]interface{} or JSON string.

Then we could avoid this special condition for SearchService (and every other service that relies on SearchSource.Source() to generate the body, which is probably all search services), as you use above.

What do you think? If you like, I can submit a pull request.

**Comment by olivere** [comment]
The API is: Either you configure your request via the setters in `SearchService` or you set everything via `Source`. If you use the latter, you're on your own. Elastic won't merge `Source` and `SearchSource` for you.

If you want to pass a query as a raw string and still use things like sorting, then `RawStringQuery` is for you.

**Comment by akotlar** [comment]
RawStringQuery does not work with sort, try it please. I get an exception every time, with valid queries.

**Comment by akotlar** [comment]
Namely, the use case of RawStringQuery with client.Scan().Query(elastic.NewRawStringQuery(queryString) ) does nothing but return a 400 request error with **perfectly valid JSON body**. It works fine if all that you pass is '{query: ...}`

Presumably this is because ScanService Query() function does not expect anything other that the query portion of the request

```
// Query sets the query to perform, e.g. MatchAllQuery.
func (s *ScanService) Query(query Query) *ScanService {
	s.searchSource = s.searchSource.Query(query)
	return s
}
```

**Comment by akotlar** [comment]
Also, you CANNOT set everything using a raw string (or interface) using Source for Scan or Scroll service, because SearchSource does not accept a string. It requires you to manually fill the structure, which is a bit of a pain. And SearchService, which DOES allow you to do this, does not export the source property (which is a SearchSource). What I propose is globally allowing people to set the body of the request. This would make the ```if s.source != nil ... ``` unnecessary.

Clearly you've noted the need for this, because you've made a workaround in search.go, which I mentioned in an earlier comment, and reference here

**Comment by olivere** [comment]
Yes. That's how it works. `RawStringQuery` is a query, not the message body. As such, you use it like you'd do with any query:

```go
package main

import (
	"fmt"

	"gopkg.in/olivere/elastic.v3"
)

func main() {
	client, err := elastic.NewClient()
	if err != nil {
		panic(err)
	}

	s := `{"match_all":{}}`
	res, err := client.Search().
		Index("store2").
		Query(elastic.RawStringQuery(s)).
		Sort("price", true).
		Do()
	if err != nil {
		panic(err)
	}

	fmt.Printf("%d results\n", res.TotalHits)
}
```

If you want to pass raw JSON and send it as the body for your request, this does the job:

```go
package main

import (
	"fmt"

	"gopkg.in/olivere/elastic.v3"
)

func main() {
	client, err := elastic.NewClient()
	if err != nil {
		panic(err)
	}

	s := `{"query":{"match_all":{}},"sort":[{"price":{"order":"asc"}}]}`
	res, err := client.Search().
		Index("store2").
		Source(s).
		Do()
	if err != nil {
		panic(err)
	}

	fmt.Printf("%d results\n", res.TotalHits)
}
```

**Comment by akotlar** [comment]
Try this with Scan or Scroll!

**Comment by olivere** [comment]
Please open a new issue for this. I don't want to continue to spam the original author...
