### ISSUE TITLE
how to install this pkg offline?

### ISSUE THREAD

**Issue by morning-color** [olivere/elastic#287]
I am working on a cluster, which can't be linked to the internet directly. So I want to know how to install this pkg using its source code on LINUX. 
Many Thanks!

**Comment by olivere** [comment]
What do you mean by "install"? You typically use `go get gopkg.in/olivere/elastic.v2` (or v3) or use some kind of vendoring tool, as described in the README and the Wiki. If you cannot do that for one reason or another, simply `git clone` this repository.

HTH.

**Comment by morning-color** [comment]
Sorry, I am a freshman in Go & es. I've git clone the source code, but i don't know how to build or install it. Could you give me the details of the steps to install or build the source code of elastic pkg.
I know this question seems stupid, but many thanks!

**Comment by morning-color** [comment]
I've konwn how to install it, THX!!!

**Comment by olivere** [comment]
I'm sorry, but your question is more about general development with Go. Please get yourself accustomed to Go development in general, e.g. by reading [How to Write Go Code](https://golang.org/doc/code.html) or by reading [a good book about Go development](https://github.com/dariubs/GoBooks) first. I'm afraid, there is no shortcut.
