### ISSUE TITLE
Errors in bulk request are not objects; they are strings.

### ISSUE THREAD

**Issue by ian-axelrod** [olivere/elastic#288]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[X] elastic.v3 (for Elasticsearch 2.x)

### Please describe the expected behavior
All errors in the response to a <es host>/_bulk request should unmarshal cleanly.

### Please describe the actual behavior
Errors in the response fail unmarshaling with the error ```Cannot unmarshal object into go value of type string```.

### Any steps to reproduce the behavior?
Execute a bulk request that results in an error. For example,

```
{
   "took": 3,
   "errors": true, 
   "items": [
      {  "create": {
            "_index":   "website",
            "_type":    "blog",
            "_id":      "123",
            "status":   409, 
            "error":    "DocumentAlreadyExistsException 
                        [[website][4] [blog][123]:
                        document already exists]"
      }},
      ...
   ]
}
```

**Comment by olivere** [comment]
Hmm... thanks for reporting. Did they change the `error` field? I have a [test for this](https://github.com/olivere/elastic/blob/release-branch.v3/bulk_test.go#L364-L406).

**Comment by ian-axelrod** [comment]
Let me look through their change history and find out for you.

**Comment by olivere** [comment]
In the 2.x branch they [generate an object](https://github.com/elastic/elasticsearch/blob/2.x/core/src/main/java/org/elasticsearch/rest/action/bulk/RestBulkAction.java#L109-L111). Which version are you using exactly?

**Comment by ian-axelrod** [comment]
It doesn't appear so. The issue is that your test already assumes a response format. It doesn't test that the response is actually going to be in that format.

**Comment by olivere** [comment]
Yes. I have a lot of tests, but I don't have integration tests for everything.

**Comment by ian-axelrod** [comment]
I use version 2.2.0. Yeah it appears that in the code they generate an object, but the documentation and my log shows a regular message. Weird... going investigate more.

**Comment by ian-axelrod** [comment]
Ugh. The only way I can get this error to replicate is through a build on circleci, and now circleci is completely borked. It doesn't help that it only gives me 30 minutes before expiring the ssh session. I'll give you an update when circleci is stable enough to let me log the elasticsearch bulk action responses. What I can tell you at the moment from my debugging is that the error occurs at https://github.com/olivere/elastic/blob/release-branch.v3/bulk.go#L202. Of course, UnmarshalTypeError has very little information.

**Comment by olivere** [comment]
Well... :-)   The error is due to [this line](https://github.com/olivere/elastic/blob/release-branch.v3/bulk.go#L267). You somehow managed to get ES to return a string while I can only see ES return a structured error.

Can you update to 2.3.2, or does that make things even worse?

**Comment by olivere** [comment]
Hmm... 1.x had [an error message](https://github.com/elastic/elasticsearch/blob/1.7/src/main/java/org/elasticsearch/rest/action/bulk/RestBulkAction.java#L110) ...

**Comment by ian-axelrod** [comment]
We are definitely on 2.2. I do know that. I'm running my circleci build now with trace logging enabled. We should know soon.

**Comment by olivere** [comment]
Did you find the root cause of this?

**Comment by ian-axelrod** [comment]
Sorry for the sudden inactivity. No, I did not figure out the cause of this. I fixed a bug in existing code that was causing elasticsearch to raise the 400 error for one of the bulk request items. I tried to reproduce the issue many times before applying my fix, but I could not get it to reproduce. I also could not get to the logs because they had been redirected to nohup.out, which was empty. CircleCI would not let me view (or even download) the full log when I configured your client with a trace logger because there were too many requests; the log size was limited to 4 MB. I gave up after that and applied my fix.

I'll close this for now. Perhaps someone will also encounter the same problem, find this issue, and provide you with sufficient information to fix it. Cheers!

**Comment by olivere** [comment]
Okay. Thanks for trying.
