### ISSUE TITLE
RangeFilter support new format

### ISSUE THREAD

**Issue by nizsheanez** [olivere/elastic#29]
In ES documentation:
`The from, to, include_lower and include_upper parameters have been deprecated in favour of gt,gte,lt,lte.`
http://www.elasticsearch.org/guide/en/elasticsearch/reference/0.90/query-dsl-numeric-range-filter.html

In current documentation it's already `from, to, include_lower and include_upper` already not exists:
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-range-filter.html

need to add this possibility? or it's already exists somewhere?

**Comment by olivere** [comment]
Will update later when I have the time.

**Comment by olivere** [comment]
The code hasn't changed yet in the Java client (see [here](https://github.com/elasticsearch/elasticsearch/blob/master/src/main/java/org/elasticsearch/index/query/RangeFilterBuilder.java#L384)). So the old syntax seems to be still supported. As the Java client is my reference implementation, I won't change until they do.

**Comment by nizsheanez** [comment]
got it, will create ticket in ES repo https://github.com/elasticsearch/elasticsearch/issues/9266
