### ISSUE TITLE
Fix range query boost parameter placement

### ISSUE THREAD

**Issue by marcybuccellato** [olivere/elastic#290]
### Which version of Elastic are you using?

[x] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)

### Please describe the expected behavior
`RangeQuery...Boost(<num>)` should produce:
```
{
	"range": {
		"publish_from": {
			...,
			"boost": < num >
		}
	}
}
```
according to the docs (and testing): https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-range-query.html

### Please describe the actual behavior
`RangeQuery...Boost(<num>)` is producing:
```
{
	"range": {
		"boost": < num > ,
		"publish_from": {
			...
		}
	}
}
```

### Any steps to reproduce the behavior?
Create a new `RangeQuery` instance with boost parameter specified and print the output - try in elasticsearch.

### Fix
Move the `boost` parameter within `params` rather than `rangeQ`.
https://github.com/olivere/elastic/blob/release-branch.v3/search_queries_range.go#L137

**Comment by olivere** [comment]
Thanks for your contribution. I just updated v3, will backport to v2 and then release an updated version of both on gopkg.in.
