### ISSUE TITLE
Use a configured decoder in multi_get.go and get.go

### ISSUE THREAD

**Issue by four2five** [olivere/elastic#293]
## Which version of Elastic are you using?

[x] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)

### Please describe the expected behavior
Olivere should return int64 values formatted as int64 values

### Please describe the actual behavior
Values stored in elasticsearch as a long, say 1464728444255,
are Unmarshalled into what looks like a float, 1.464728444255e+12

As a suggestion for a fix, olivere should accept and use a custom decoder. It looks like this is meant to be possible via the SetDecoder() function here: 
https://github.com/olivere/elastic/blob/release-branch.v2/client.go

However, olivere uses the Go's default json.Unmarshall and not a configured decoder (b.client.decoder) in multi_get.go function:
func (b *MultiGetService) Do() (*MultiGetResult, error)

### Any steps to reproduce the behavior?
I've distilled the core issue into some example Go code:
https://play.golang.org/p/yOs-XWoU1k

**Comment by olivere** [comment]
I think I cannot change the default behavior without (potentially) breaking existing clients.

However, you're right in that the services should use the [configured decoder](https://github.com/olivere/elastic/wiki/Decoder) everywhere. I will check that.

**Comment by olivere** [comment]
All services now use the decoder configured in the client.

**Comment by four2five** [comment]
Thank you for taking a look at this and for fixing it so quickly.

**Comment by olivere** [comment]
You're welcome.
