### ISSUE TITLE
Request signing for AWS ES cluster

### ISSUE THREAD

**Issue by vgarg** [olivere/elastic#295]
Is it possible to use this client to talk to an IAM protected AWS ES cluster? Specifically is it possible to inject the AWS V4 request signing into this SDK?

Vivek

**Comment by olivere** [comment]
I'm not familiar with AWS request signing. But if all you want is injecting data into the request, you could configure your own [http.Transport](https://github.com/olivere/elastic/wiki/HttpTransport). Does that help?

**Comment by vgarg** [comment]
@olivere thanks. That should help. I will give that a try.

**Comment by olivere** [comment]
You're welcome. Will close for now but re-open if it didn't help.
