### ISSUE TITLE
Add Multiple Term values under one term name

### ISSUE THREAD

**Issue by pxaviad** [olivere/elastic#296]
### Which version of Elastic are you using?

[ ] elastic.v3 (for Elasticsearch 2.x)

I'm trying to get data from elastic with a ```BoolQuery``` and a ```Must``` term:
```
boolQuery = boolQuery.Must(elastic.NewTermQuery("some_field", "value1"))
```
This works fine for this ```value1``` but I want that some_field will be one of an array of values. For instance - I want to get back in the result set some_field with value of ```value1``` or ```value2``` or ```value3```.

I tried doing this in several manners, this was my last hope:

```
boolQuery = boolQuery.Must(elastic.NewTermQuery("some_field", []string{"value1", "value2", "value3}))
```

But that doesn't seem to work.
What am I doing wrong?

btw: If it is relevant in any way. this is how I'm running the query:
```
searchResult, err := esClient.Search().Index(indices...).Query(boolQuery).Pretty(true).Do()
```

**Comment by olivere** [comment]
I'm not sure if there is a problem with elastic or if it's a problem with understanding... Maybe [this blog post](https://www.elastic.co/blog/lost-in-translation-boolean-operations-and-filters-in-the-bool-query) does already help?! Otherwise, let me know.

**Comment by olivere** [comment]
Otherwise, [Terms Query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-terms-query.html) should be an option (notice the `s` at the end: Terms instead of Term). Reopen if that still doesn't help.

**Comment by pxaviad** [comment]
Thanks. That what did the trick. I did not noticed the s.
