### ISSUE TITLE
reserved characters

### ISSUE THREAD

**Issue by thekostya** [olivere/elastic#30]
I get elastic error when i use reserved characters in my query. Do you have "escape" function for elastic reserved caracters.

+ - && || ! ( ) { } [ ] ^ " ~ * ? : \ /

http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_reserved_characters

**Comment by olivere** [comment]
Can you send a failing test? 

I'm using [uritemplates](https://github.com/olivere/elastic/tree/master/uritemplates) but might have missed a case ([original](https://github.com/jtacoma/uritemplates)).

**Comment by thekostya** [comment]
Here is log from my tests. 

Line 112:
  Expected: nil
  Actual:   'elastic: Error 400: SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[ekch3YLHTES-Ag3N9HH3Zw][marketplace-2014-12-28][0]: SearchParseException[[marketplace-2014-12-28][0]: from[0],size[-1]: Parse Failure [Failed to parse source [{"from":0,"highlight":{"fields":{"about":{}},"post_tags":["\u003c/em\u003e"],"pre_tags":["\u003cem\u003e"]},"query":{"bool":{"minimum_should_match":"1","must":[{"query_string":{"fields":["education","software","location","about","name"],"query":"What~3 say~3 about~3 me…~3 I~3 don't~3 now:)~3"}},{"match":{"status.activity":{"query":"ACTIVE"}}}]}},"size":10}]]]; nested: QueryParsingException[[marketplace-2014-12-28] Failed to parse query [What~3 say~3 about~3 me…~3 I~3 don't~3 now:)~3]]; nested: ParseException[Cannot parse 'What~3 say~3 about~3 me…~3 I~3 don't~3 now:)~3': Encountered " ")" ") "" at line 1, column 43.


post_tags has escaped <em>  </em> 
But "query":"What~3 say~3 about~3 me…~3 I~3 don't~3 now:)~3"  has unescaped bracket in smile :)

**Comment by olivere** [comment]
I added a helper function (see [here](https://github.com/olivere/elastic/blob/e61a4b499f62a013098b66cdbecec2e9a79900c3/search_queries_query_string.go#L19)).

However, it's not a silver bullet. There's no way of telling if e.g. a `~3` suffix should be escaped as `\~3` (part of a keyword) or if the user wants to boost some keyword (part of the `query_string DSL`).

BTW: The Java client does not seem to have any escape function for `query_string` either (at least I couldn't find any). So they keep it up to the implementer to properly escape.

**Comment by olivere** [comment]
Related: If you're accepting raw user input, you might be better off using [simple_query_string_query](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html). It never throws.

**Comment by thekostya** [comment]
Thanks a lot. I think helper function is enough. When i construct the query i know which string have to be escaped.
