### ISSUE TITLE
Add AWS signing

### ISSUE THREAD

**Issue by olivere** [olivere/elastic#301]
See e.g. https://github.com/tj/go-elastic and/or https://github.com/smartystreets/go-aws-auth.

**Comment by felipejfc** [comment]
see #302

**Comment by olivere** [comment]
Thanks for your contribution. That looks interesting but is too invasive.

I'm not familiar with AWS signing, so if you have the time and resources: Could you experiment in preparing the request by passing a custom `http.Transport` as described [in the Wiki](https://github.com/olivere/elastic/wiki/HttpTransport)? That way you should be able to remove all the `if IsAWSRequest(...) { ... }` statements from the PR in #302, no?

**Comment by felipejfc** [comment]
@olivere You are rightm I think you'll like this one better: #303

**Comment by olivere** [comment]
@felipejfc Thanks. Much easier now, isn't it?

However, I'm wondering if there is a Go library out there that already is a "middleware" to the `net/http` that does all this signing for us. Do you know any?

I mean: It looks easy at first sight. But I refrain from putting this into Elastic as I might end up maintaining and supporting a 2nd library hidden inside Elastic: Just for signing AWS requests. So I'm left with these options I guess:

1. I will create a new repository as a sort of contrib, e.g. elastic-aws.
2. Someone from the community will create an elastic-aws repository and I will link to it here.
3. Elastic will use a supported and maintained package for AWS signing, and put it into a sub-package `aws`, then document it in the Wiki.

**Comment by olivere** [comment]
Request signing should be possible with the official Go SDK at [aws/aws-sdk-go](https://github.com/aws/aws-sdk-go/) when they [merge this](https://github.com/aws/aws-sdk-go/issues/555).

On the other hand, [smartystreets/go-aws-auth](https://github.com/smartystreets/go-aws-auth) is an option as well.

**Comment by sha1sum** [comment]
@olivere @felipejfc In anticipation of the merging of [the PR for making signing generic requests easier](https://github.com/aws/aws-sdk-go/pull/698) via the AWS SDK, I've [created a wrapper for `*http.Client`](https://github.com/sha1sum/aws_signing_client) that will use the new signing from the PR to ensure that all outgoing requests are signed before sending. I've noticed that you can set an `*http.Client` into Elastic that will be used for requests. Hopefully this will help.

I've not yet implemented this via Elastic yet (just finished), but I am about to do so. Feel free to contribute as well, if you think anything can be added.

**Comment by olivere** [comment]
@sha1sum Thanks. Having a separate package which does the AWS signing via `http.Client/http.Transport` is my favorite option (so I could be kept this out of core). [Here's a simple description](https://github.com/olivere/elastic/wiki/HttpTransport) of how to use a custom `http.Client/http.Transport`.

If you've got a repository ready for integration, I will link to it from the Wiki.

**Comment by sha1sum** [comment]
@olivere I will integrate it with Elastic on my end to make sure it actually works, and then we should probably wait for the AWS SDK PR to be merged in before publishing. The package is under test, but there are no integration tests, so I want to make sure it _actually_ works so I don't cause you any headaches :)

**Comment by sha1sum** [comment]
@olivere I have [created a wiki page](https://github.com/olivere/elastic/wiki/Using-with-AWS-Elasticsearch-Service) and linked it on the home page for the wiki.

**Comment by olivere** [comment]
Wonderful. I ❤️ Open Source. Thanks for being a contributor.
