### ISSUE TITLE
Support source filtering for scroll queries

### ISSUE THREAD

**Issue by vsiv** [olivere/elastic#304]
I have a need to for just retrieving ids via scroll queries, but the `ScrollService` does not support source filtering like the `SearchService` does. Would be a big help. And I think its quite useful, since you are scrolling generally through lots of docs, source filtering can help u optimize a bit via includes/excludes fields, etc.

Thanks.

**Comment by olivere** [comment]
Hmm... with `ScrollService` you can [specify a `Query`](https://github.com/olivere/elastic/blob/release-branch.v3/scroll.go#L65) and with `ScanService` you can [specify a `SearchSource`](https://github.com/olivere/elastic/blob/release-branch.v3/scan.go#L91).

Can't you use a `TermsQuery`with one of those?

**Comment by olivere** [comment]
I'm sorry... you're talking about source filtering, and I misread it as just "filtering" (in terms of querying). My bad.

Can you switch to `ScanService`, or is that too much work? It basically does the same as `Scroll`, but returns results one-by-one (loading data as required).

I don't like the situation around `Scroll` and `Search`, and one of my issues for 5.0 is to provide a unique iterator-style approach that deprecated both of these services. Unfortunately, I didn't find the time yet.

BTW: There's [interesting things happening](https://github.com/elastic/elasticsearch/pull/18237) around scrolls in 5.0.

**Comment by vsiv** [comment]
Yes, I can switch to `ScanService`. Should not be a big issue.

PS. thanks for the link, love the parallel reads support, i am assuming most requests around this is for ES-hadoop mappers.

**Comment by olivere** [comment]
Probably :-)

I will close this issue. If you have problems with the switch, just post a new issue.

**Comment by vsiv** [comment]
👍
