### ISSUE TITLE
Go through 5.0 breaking changes

### ISSUE THREAD

**Issue by olivere** [olivere/elastic#307]
https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking-changes-5.0.html

**Comment by olivere** [comment]
Current draft of [CHANGELOG-5.0.md](https://github.com/olivere/elastic/blob/release-branch.v5/CHANGELOG-5.0.md).

**Comment by chenziliang** [comment]
Hi,

May i ask if elastic golang lib supposed to work with current ES 5.0 alpha release ?

**Comment by olivere** [comment]
Yes it is. See release-branch.v5. Works for beta1, no test errors, but also not finished yet.

**Comment by chenziliang** [comment]
Great! Thanks Olivere for the quick response.

**Comment by oryband** [comment]
UPDATE: ES 5 is GA (production) as of yesterday

**Comment by olivere** [comment]
@oryband Ran all tests of elastic.v5 on ES 5.0 GA yesterday, and it's green. Also tagged it as 5.0.0, so you can use `import "gopkg.in/olivere/elastic.v5"`.

However, I'm not quite finished with all changes and implementing new APIs. So expect some breaking changes before elastic.v5 is considered ready for prime time.

**Comment by atombender** [comment]
ES 5.0 no longer has the consistency parameter (`client.Index().Consistency("quorum")` will fail with a 400 error). It seems to have [been replaced with](https://github.com/elastic/elasticsearch/issues/18985) a parameter `wait_for_active_shards`.

**Comment by olivere** [comment]
@atombender I just pushed 5.0.1 which changes these settings in a lot of APIs: Bulk, Index, Delete, Delete-by-Query, Reindex, Update, and Update-by-Query.

Notice that `wait_for_active_shards` is not quite the same as `consistency`. The latter e.g. has `"quorum"` as a valid setting while the former only seems to accept `"all"` or positive numeric values.

Expect more problems like these: ES 5.0 changed the way they handle "unknown" or "unsupported" parameters. While ES < 5.0 silently dropped these, ES >= 5.0 will now bail.

**Comment by atombender** [comment]
Thanks, @olivere, will update.

I know the new parameter isn't exactly the same; it's a bit weird that they removed `quorum`, since the client can't know what a quorum is without reading how many shards there are for a given index.

On the other hand, the new, stricter handling is a good thing.

**Comment by oryband** [comment]
@olivere thank you very much. Awesome support for this plugin.
