### ISSUE TITLE
Not obvious behaviour of sorting

### ISSUE THREAD

**Issue by nizsheanez** [olivere/elastic#31]
Now you can use or `SortBy` or `Sort/SortWithInfo`, but not together. 
I did something like:
```
engineRequest = engineRequest.Sort("field1", false)
engineRequest.SortBy(elastic.NewScriptSort(DEFAULT_SCORING, "number").Lang("groovy"))
engineRequest = engineRequest.Sort("field2", false)
```

in result i have only order by script. I think it's strange behaviour, i expected that i will have sorts by `field1`, `script`,  `field2`. 

it happening because of code: 
```
if len(s.sorters) > 0 {
		sortarr := make([]interface{}, 0)
		for _, sorter := range s.sorters {
			sortarr = append(sortarr, sorter.Source())
		}
		source["sort"] = sortarr
	} else if len(s.sorts) > 0 {
		sortarr := make([]interface{}, 0)
		for _, sort := range s.sorts {
			sortarr = append(sortarr, sort.Source())
		}
		source["sort"] = sortarr
	}
```

i understand that i can avoid it by using `elastic.NewFieldSort("field1").Desc()`, but then need to mark `Sort` and `SortWithInfo` as deprecated?

**Comment by olivere** [comment]
SortWithInfo should be avoided, really. The same can be achieved with the other Sorters, and they are more up-to-date to the ES reference implementation (the Java client). But I keep supporting it unless it really becomes a hassle.

**Comment by nizsheanez** [comment]
maybe:
```
if len(s.sorts) > 0 && len(s.sorters) > 0 {
   panic(..)
}
```
?

**Comment by olivere** [comment]
It's already solved, isn't it? Just fetch master.

**Comment by nizsheanez** [comment]
ah, i didn't see

**Comment by danbrakeley** [comment]
Any particular reason why this was undone in 190f272208dac97580821322db02f4c3e63f2042?

**Comment by olivere** [comment]
I'm sorry, it looks like something went wrong here. I will check as soon as I find time.

**Comment by olivere** [comment]
@danbrakeley I hope this changes fix the behavior. Interesting that nobody got hit by this for more than a year. Thank you.
