### ISSUE TITLE
SearchHit result Fields is nil

### ISSUE THREAD

**Issue by hurkgu** [olivere/elastic#310]
when  i use elastic.SearchHit.Fields to get fields ,i find the result is nil, but source has value
such as:
`res, err := client.Search(index).Query(query).From(0).Size(size).Do()
 
for _, hit := range res.Hits.Hits {
    if val,ok:=hit.Fields["key"];ok{
        println(val)
   }
 }`

@olivere

**Comment by olivere** [comment]
By default, `fields` are [not stored](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-fields.html). Can you return output of the `curl`-equivalent query in the console?

```
$ curl -is 'localhost:9200/index/_search?pretty' -d '{...your-query...}'
```

**Comment by hurkgu** [comment]
@olivere 
ths

**Comment by olivere** [comment]
Does this answer your question? Can we close the issue?
