### ISSUE TITLE
UnmarshalJSON of AggregationValueMetric should return error if required fields are missing

### ISSUE THREAD

**Issue by Jack47** [olivere/elastic#311]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[X] elastic.v3 (for Elasticsearch 2.x)

### Please describe the expected behavior
UnmarshalJSON of struct `AggrationValueMetric`, `AggregationPercentilesMetric` should return error if the required fields are missing

### Please describe the actual behavior
UnmarshalJSON of struct `AggrationValueMetric` will success even if the `value` field is missing.

PS: I'm using the `SearchService.Source()` to set the request body manually, I need to parse the response's `SearchResult` manually, so I use `UnmarshalJSON` to guess the returned aggregation type and encountered this problem.

**Comment by olivere** [comment]
Can you provide a complete example, or even a test, so that I can reproduce the problem?

**Comment by Jack47** [comment]
```go
import (
        elastic "gopkg.in/olivere/elastic.v3"
)
func TestUnmarshal(t *testing.T) {
	str := `{
  "1": {
    "value": 8.75
  },
  "2": {
    "value": 47.35
  }
}`
	agg := new(elastic.AggregationPercentilesMetric)
	err := json.Unmarshal([]byte(str), &agg)
	if err == nil {
		t.Fatal("Unmarshal should failed, missing Values field.")
	}
}
```

**Comment by olivere** [comment]
Hmm... maybe I'm missing something... but I'm struggling to see why `elastic.AggregationPercentilesMetric` should accept a `value` field. It should only consume `values`, as [described here](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/search-aggregations-metrics-percentile-aggregation.html).

Maybe you're unmarshaling into the wrong kind of aggregation. Are you looking for [`elastic.AggregationValueMetric`](https://github.com/olivere/elastic/blob/release-branch.v3/search_aggs.go#L615) instead?!

Can you post the query you send to ES?

**Comment by olivere** [comment]
Did the above solve the issue? If yes, please close. Otherwise I'll do it in a few days.

**Comment by Jack47** [comment]
Sorry for the delayed response.  As you said that `elastic.AggregationPercentilesMetric ` should only consume `values`, but if it is made to consume `value`, it doesn't fail, this is the problem. I prefer it to fail when consume unexpected values.

**Comment by olivere** [comment]
Why? Just because, or is there a reason I don't see?

These Aggregation should be internal really.

**Comment by Jack47** [comment]
I'm using elastic query DSL directly, it will save me from calling various elastic go client interface. I use the `SearchService.Source()` to set the DSL I received, the DSL is guaranteed to use Value or Percentile aggregation. I need to parse the response's `SearchResult` manually, so I use `UnmarshalJSON` to guess the returned aggregation type is whether `AggregationPercentilesMetric`  or `AggregationValueMetric`. Is there a better way to do this ?

**Comment by olivere** [comment]
Oh, I think I understand now. Sorry. So you want to use the integrated Aggregation... structs for parsing in your own app.

Hmm... I think the reason that I'm so forgiving with errors in aggregations is that ES changed quite a lot when I implemented them. Aggregation structs should have been internal from the start, but that makes it impossible to pass it around in your app.

While ES has a nice REST API spec, it is only for the query side. They do not have a spec for the return values. ES documentation is good but pretty high-level and tends to [only gives examples](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-aggregations-metrics-percentile-aggregation.html) which is quite different to [what I'd expect](https://www.postgresql.org/docs/9.5/static/sql-createtable.html).

Another problem with the hierarchical structure of aggregations is that you basically have no information in `UnmarshalJSON` about where the problem actually occured in your query. You can only return an error without giving the user any context. Of course this is a problem with my particular implementation; I just want to frame the problems here.

So this led me to be more pragmatic and simply do a best-effort approach. I prefer to only fail when the returned struct is not deserializable at all.

If you want to make sure a query fails you can simply copy-and-paste the code from Elastic in your application and implement the error handling, no?

**Comment by olivere** [comment]
Serious question: Why do you need to parse the `SearchResult` manually? I see this quite a lot recently, and I think it's not a good design decision because it makes your code fragile because of (internal) changes in Elastic.

**Comment by Jack47** [comment]
You asked a good question. In my implementation,  the client sends raw elastic search query DSL to server, server use elastic go client to execute them, parse the `SearchResult` manually and ship the  result to the client. In this way I can avoid to write tons of search APIs with Elastic interface. But on the other hand, this implementation is fragile, the server doesn't know any thing about the DSL. That is the first implementation, now I'm clear about all the search queries client need, so I'm thinking about simply abstract several APIs and use elastic interfaces to interact with elastic search.
