### ISSUE TITLE
Aggregations retrieve wrong float precision

### ISSUE THREAD

**Issue by jjamaral** [olivere/elastic#313]
Hi!

I'm using global aggregations and i'm getting a minor issue.
I have some float fields in Elastic, that are being saved with precision = 2.
Example: **1000.12**
But when I'm using aggregations with this library, im getting: **1000.1199951171875**

Do you know why? 

I have multiple aggregations, so there it go an example:
```
global := elastic.NewGlobalAggregation()
aggExample := elastic.NewTermsAggregation().Field("aggExample").Size(0)
global.SubAggregation("aggExample", aggExample)

var values []interface{}
options , _ := agg.Aggregations.Terms("aggExample")

for _, hits := range options.Buckets {
	fmt.Println(hits.Key)
	fmt.Println(hits.KeyNumber)
	values = append(values, hits.Key)
}
```

And when printing the value, already it's 1000.1199951171875.

If you have some solution please share.
Thanks

### Which version of Elastic are you using?
elastic.v3 (for Elasticsearch 2.x)

### Please describe the expected behavior
Returned aggregation value it's like in Elastic (precision 2)

### Please describe the actual behavior
Returned aggregation value with wrong precision.

### Any steps to reproduce the behavior?
Just check the code above.

**Comment by olivere** [comment]
Maybe because of [this](https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html)? :-)

**Comment by olivere** [comment]
```
$ js
js> 0.1 + 0.2
0.30000000000000004
```

[Wat](https://www.destroyallsoftware.com/talks/wat)

**Comment by jjamaral** [comment]
Hi @olivere thank you for your comments, but do you have any tip how to solve this issue?

**Comment by olivere** [comment]
Well. Go has to serialize all numeric data into `float64`as JavaScript doesn't come with an integer or decimal type. It really depends how important your data. If it's monetary data, you should really take care and watch your options!

If it's not that important you have several options, e.g.:

* Multiply by 100 (or whatever you need) and translate to integers, then divide by 100 after reading.
* Translate the decimal into a string, then parse again when reading.
* Simply do `math.Round()` when reading.

**Comment by olivere** [comment]
See also: [JavaScript type system](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures) and [JSON data types](https://en.wikipedia.org/wiki/JSON#Data_types.2C_syntax_and_example).

**Comment by jjamaral** [comment]
I'm just trying with Script method.

```
scr := elastic.NewScriptInline("Float.parseFloat(doc['field'].value)")
aggExample := elastic.NewTermsAggregation().Field("aggExample").Size(0).Script(scr)
```

But no success yet :(

**Comment by olivere** [comment]
Can't you simply do it while indexing? In your Go program?

**Comment by jjamaral** [comment]
The problem is in aggregation return.
Value is correctly indexed: 1000.12
When I search in Elastic, the value is still good: 1000.12
But when returning on aggregation is: 1000.1199951171875

**Comment by jjamaral** [comment]
FYI, just solved the issue by updating the field type from **_float_** to **_double_**.

**Comment by prasadsidda** [comment]
I'm using elasticsearch 6.1.1. I also have the same with aggregation. but i tried with both float and double field type but no Luck.

Please help me....

**Comment by olivere** [comment]
@prasadsidda I'm sorry but there is no way of solving this problem in the library. If Elasticsearch does return e.g. a value of `1000.1199951171875`, how can the library pretend it's `1000.12`. It's a problem all floating-point number types have, and Go deserializes numeric values as `float64` by default. We don't have fixed-point number types yet.

Maybe you can solve it in Elasticsearch by using [`scaled_float`](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/number.html) as the underlying data type. I haven't worked with these scaled types yet.

**Comment by cnarvaa** [comment]
My team had the same problem today. Our workaround was casting the value to double `(double)Math.round(_value * 1000) / 1000` with painless.

It's anyway to update the rage aggregation documentation?. This way other users will be aware of this behavior.
