### ISSUE TITLE
Multi Term Vectors needs filter params?

### ISSUE THREAD

**Issue by saxsir** [olivere/elastic#315]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[x] elastic.v3 (for Elasticsearch 2.x)
### Please describe the expected behavior

Multi Term Vectors API might be possible to use `filter` params.

https://www.elastic.co/guide/en/elasticsearch/reference/2.3/docs-multi-termvectors.html

> See the termvectors API for a description of possible parameters.

It's not implemented yet. I want to contribute if it is needed.

However, there're not specs in https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/mtermvectors.json

**Comment by olivere** [comment]
If they're not in the REST spec, they're probably not officially supported. However, I cannot see a filter field/param on the docs page either. The Java source code is the ultimate source of truth.

**Comment by saxsir** [comment]
Thanks for your reply.

> The Java source code is the ultimate source of truth.

ok, i got it. thanks.

**Comment by saxsir** [comment]
Sorry, reopened this issue because I found that The Java source code implemented filter params on mtermvectors.

https://github.com/elastic/elasticsearch/issues/12311
https://github.com/elastic/elasticsearch/pull/12312

I will contribute to add filter on multi term vectors API implementation.

**Comment by olivere** [comment]
@saxsir Can you file an issue at their site trying to find out if a) the `filter` param is officially supported and if so, b) where documentation can be found and c) if it's missing in the REST API spec?

**Comment by saxsir** [comment]
@olivere Thank you for your reply.

a), b)
In [this page](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/docs-multi-termvectors.html), there is written the description below.

`See the termvectors API for a description of possible parameters.`

So mtermvectors API should possible to use params that same as termvectors API.
I think this is an official documentation.

c)
I'm not sure.

Also in the [termvectors spec file](https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/termvectors.json), there is not spec that supported filter params.

But The Java library supported it, and also this `olivere/elastic` golang client library [supported it](https://github.com/olivere/elastic/blob/release-branch.v3/termvectors_test.go#L129) .

So I have a question, where did you find the documentation that termvectors API support filter params (because there is not spec file, I think..)?

**Comment by saxsir** [comment]
> there's no filter in the REST specification

No, no specification but it's implemented. I asked them about it while ago.
https://github.com/elastic/elasticsearch/issues/19243

> If filter is in the Java API and not explicitly deprecated in their breaking changes, I tend to include it.

OK, thanks a lot. I will contribute it in few days.

**Comment by olivere** [comment]
I took another look at this today. I think Term Vectors API and Multi-Term Vectors API needs to be refactored, then we can add this. Many of the parameters are passed in the query string. Although this works for simple types, it's really not working well (or is at least bad style) for structures like the filter settings. The docs for [Term Vectors API](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/docs-termvectors.html) and [Multi-Term Vectors API](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/docs-termvectors.html) illustrate how we should really use the API, i.e. pass parameters in the body of the request.

Furthermore, the parameters should be extracted from `TermvectorsService` into a `TermvectorsRequest` and then be reused both in `TermvectorsService` and in `MultiTermvectorsService`.

I will do all of this eventually. It's a matter of time. Please bear with me.

**Comment by olivere** [comment]
Closing it for it is too old. Elastic v6 supports the filter in the Term Vectors API.
