### ISSUE TITLE
Querying with JSON string?

### ISSUE THREAD

**Issue by seenickcode** [olivere/elastic#321]
Is there a way to query with a JSON string at all rather than using the DSL? i.e.

    q := `{
      "query" : {
          "wildcard" : { "title" : "spiel*" }
      }
    }`
    results, err := myclient.Search("myindex", "thing", nil, q)

**Comment by olivere** [comment]
You have two way to do that. Either you use [`Source`](https://github.com/olivere/elastic/blob/release-branch.v3/search.go#L51) in the `SearchService` to specify the body, or you use [`PerformRequest`](https://github.com/olivere/elastic/blob/release-branch.v3/client.go#L1033) to send arbitrary data to ES.

**Comment by seenickcode** [comment]
Works.  Thank you!
