### ISSUE TITLE
SearchService does not set preference in Do

### ISSUE THREAD

**Issue by sidazhang** [olivere/elastic#323]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

SearchService (in search.go) should set the `preference` params

### Please describe the actual behavior

This code below is in `Do()` however it doesn't set the preference string.

```
	// Parameters
	params := make(url.Values)
	if s.pretty {
		params.Set("pretty", fmt.Sprintf("%v", s.pretty))
	}
	if s.searchType != "" {
		params.Set("search_type", s.searchType)
	}
	if s.routing != "" {
		params.Set("routing", s.routing)
	}
	if s.ignoreUnavailable != nil {
		params.Set("ignore_unavailable", fmt.Sprintf("%v", *s.ignoreUnavailable))
	}
	if s.allowNoIndices != nil {
		params.Set("allow_no_indices", fmt.Sprintf("%v", *s.allowNoIndices))
	}
	if s.expandWildcards != "" {
		params.Set("expand_wildcards", s.expandWildcards)
	}
```

Although we are able to set it:

```
type SearchService struct {
	client            *Client
	searchSource      *SearchSource
	source            interface{}
	pretty            bool
	searchType        string
	indices           []string
	queryHint         string
	routing           string
	preference        string <------------------
	types             []string
	ignoreUnavailable *bool
	allowNoIndices    *bool
	expandWildcards   string
}
```

I am expected to see something like this in `Do()`

```
	if s.preferemce != "" {
		params.Set("_preference", s.preference)
	}

```

### Any steps to reproduce the behavior?

See above

**Comment by olivere** [comment]
Yep. That looks like a bug. I'll fix this in the next release.

**Comment by olivere** [comment]
Wait a second. Isn't is already there?

https://github.com/olivere/elastic/blob/release-branch.v2/search.go#L357

**Comment by olivere** [comment]
Double-checked. It's already there. Update your client.
