### ISSUE TITLE
How to support https and base Auth

### ISSUE THREAD

**Issue by swan-go** [olivere/elastic#324]
as title 

By command as below:
$ curl --user  es001:pwd001 -XGET 'https://support.xxxxxx.com/dev/elasticsearch'

**Comment by olivere** [comment]
To use HTTP Basic Auth, use the SetBasicAuth configuration option. It's described here: https://github.com/olivere/elastic/wiki/Configuration

**Comment by swan-go** [comment]
**from example code, may be it doesn't support https?**  

`Here's a full example of configuring a new client:

// Obtain a client for an Elasticsearch cluster of two nodes,
// running on 10.0.1.1 and 10.0.1.2. Do not run the sniffer.
// Set the healthcheck interval to 10s. When requests fail,
// retry 5 times. Print error messages to os.Stderr and informational
// messages to os.Stdout.
client, err := elastic.NewClient(
  elastic.SetURL("http://10.0.1.1:9200", "http://10.0.1.2:9200"),
  elastic.SetSniff(false),
  elastic.SetHealthcheckInterval(10*time.Second),
  elastic.SetMaxRetries(5),
  elastic.SetErrorLog(log.New(os.Stderr, "ELASTIC ", log.LstdFlags)),
  elastic.SetInfoLog(log.New(os.Stdout, "", log.LstdFlags)))`

**If it support https,** , example  code like as below:
`Here's a full example of configuring a new client:

// Obtain a client for an Elasticsearch cluster of two nodes,
// running on 10.0.1.1 and 10.0.1.2. Do not run the sniffer.
// Set the healthcheck interval to 10s. When requests fail,
// retry 5 times. Print error messages to os.Stderr and informational
// messages to os.Stdout.
client, err := elastic.NewClient(
  elastic.SetURL("https://10.0.1.1:9200", "https://10.0.1.2:9200"),
  elastic.SetSniff(false),
  elastic.SetHealthcheckInterval(10*time.Second),
  elastic.SetMaxRetries(5),
  elastic.SetErrorLog(log.New(os.Stderr, "ELASTIC ", log.LstdFlags)),
  elastic.SetInfoLog(log.New(os.Stdout, "", log.LstdFlags)))`

**Comment by swan-go** [comment]
Because in front of the elasticsearch, nginx do reverse proxy (based on https)

**Comment by swan-go** [comment]
I have been test it, it support https is ok. :)
