### ISSUE TITLE
Initialize urls for client should be http by default even without explicit "http://" prefix

### ISSUE THREAD

**Issue by huydx** [olivere/elastic#325]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v2 (for Elasticsearch 1.x)
[x] elastic.v3 (for Elasticsearch 2.x)

### Please describe the expected behavior
When setup new client with customized URL, using `SetURL` function, set url expected to use "http" or "https". However IMHO any url without protocol should be considered as using `http` by default. Which mean that [canonicalize function](https://github.com/olivere/elastic/blob/release-branch.v3/canonicalize.go#L17) should return correct result even without protocol.
Moreover, client has `DefaultScheme` as http, which mean that above behavior should be supported by default

My proposal:
- Proposal 1: canonicalize function will automatically add prefix with `DefaultScheme`
- Proposal 2: make it panic when passed URL is malformed

### Please describe the actual behavior
Currently, any passed url without protocol will "silently" return blank urls list, which make it really weird behavior.

### Any steps to reproduce the behavior?

```
elastic.NewClient(
		elastic.SetURL("foo.bar:host"),
		elastic.SetMaxRetries(10),
	)
```
Above code will lead to fail at healthcheck, because canonicalize returns an empty urls list?!

**Comment by olivere** [comment]
We could support this. Last time I checked, the official clients didn't support this however. I will check them again and come back to you later.

**Comment by huydx** [comment]
As i see in [python official client](https://github.com/elastic/elasticsearch-py/blob/fb8b55284ac0d57405e9f1bd19f41fb766535db0/elasticsearch/client/__init__.py), with or without protocol seems both fine

**Comment by olivere** [comment]
In the next release, we use `http` by default if the URL scheme is missing.

**Comment by huydx** [comment]
@olivere thanks!
