### ISSUE TITLE
Add custom headers when make calls to Elasticsearch

### ISSUE THREAD

**Issue by SmartSara** [olivere/elastic#326]
### version of Elastic I am using
elastic.v3 (for Elasticsearch 2.x)

### Please describe the expected behavior
Cannot add custom headers when perform the request to Elasticsearch.

I have a Elasticsearch cluster which is load balanced by an HAProxy, and I want to add the header like "requestID" when I make a request to Elasticsearch, then I can capture headers from logs of HAProxy. So that I can trace each request based on "requestID".

### Please describe the actual behavior
It seems each request was sent via PerformRequest function, but there is no where I can add custom headers.
Is this feature supported for now? If not, would you consider to implement this feature?

**Comment by olivere** [comment]
Could you use your own HTTP transport? See here: https://github.com/olivere/elastic/wiki/HttpTransport

**Comment by SmartSara** [comment]
@olivere oh this seems another way to do so... Okay, I will try it then, thanks.

**Comment by olivere** [comment]
Feel free to comment to re-open the issue.
