### ISSUE TITLE
It support to post json by elastic.client?

### ISSUE THREAD

**Issue by swan-go** [olivere/elastic#327]
It support to post json to search and aggregations.  

> `{

    "query": {
        "filtered": {
            "filter": {
                "bool": {
                    "must": [
                        {
                            "range": {
                                "@timestamp": {
                                    "gt": "2015-01-01T00:00:00Z",
                                    "lt": "2016-07-16T00:00:00Z"
                                }
                            }
                        }, 
                        {
                            "term": {
                                "process_channel": "ccata"
                            }
                        }, 
                        {
                            "term": {
                                "process_result": "Success"
                            }
                        }
                    ]
                }
            }
        }
    },
    "aggs": {
      "process_duration_per_hour": {
         "date_histogram": {
            "field": "@timestamp",
            "interval": "minute",
            "format":"HH:mm:ss"
         },
         "aggs": {
            "avg_process_duration": {
               "avg": {
                  "field": "process_duration"
               }
            }
         }
      }
   }
}`

**Comment by olivere** [comment]
I'm not sure I understand you correctly. But if the question is if there are ways to send raw JSON queries/data to ES, then: Yes, you have at least two ways to do so. You either use `Source` in the `SearchService` to specify the body, or you invoke `PerformRequest` on the `Client` to send arbitrary data to ES.
