### ISSUE TITLE
how to use two contextQuery

### ISSUE THREAD

**Issue by zhaochenxiao90** [olivere/elastic#329]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v3 (for Elasticsearch [2.x)]

### Please describe the expected behavior
I have a suggester index.it contains two context. it  shows : 

localhost:9200/suggester/suggest/_mapping -d '{
    "suggest": {
        "properties": {
            "name": {
                "type": "string"
            },
            "suggest": {
                "type": "completion",
                "analyzer": "simple",
                "search_analyzer": "simple",
                "payloads": true,
                "context": {
                    "app": {
                        "type": "category",
                        "default": 1
                    },
                    "add_app": {
                        "type": "category",
                        "default": 2
                    }
                }
            }
        }
    }
}'

while,in my project,I want to suggest it by contextQuery.the code is :

suggest_build:=elastic.NewCompletionSuggester("suggest")
suggest_build.Field("suggest")
suggest_build.Size(20)
suggest_build.ContextQueries(elastic.NewSuggesterCategoryQuery("app","1"))
suggest_build.ContextQueries(elastic.NewSuggesterCategoryQuery("add_app","2"))

but,this code build a json to es is :

"context":[{"app":"1"},{"add_app":2}]

this is wrong,the correct format is:

"context":{"app":"1","add_app":"2"}

this is why?I don't know how to deal with it.

**Comment by olivere** [comment]
According to Elasticsearch master branch, you are correct: It's a map ([see here](https://github.com/elastic/elasticsearch/blob/cdb36a2b0c106cd00a362e6b3528754557c3271a/core/src/main/java/org/elasticsearch/search/suggest/completion/context/CategoryQueryContext.java#L123)). I can't seem to find the `toXContent` that serializes the `"context"` in 2.3 though.

The code in Elastic that does it wrong is [here](https://github.com/olivere/elastic/blob/release-branch.v3/suggester_completion.go#L109). I will need to see if this is wrong/deprecated sometimes during 2.x. And if so, I will fix it on the next release.

**Comment by zhaochenxiao90** [comment]
case 1:
		src, err := q.contextQueries[0].Source()
		if err != nil {
			return nil, err
		}
		suggester["context"] = src
	default:
		//ctxq := make([]interface{}, 0)
		ctxq := map[string]interface{}{}
		for _, query := range q.contextQueries {
			src, err := query.Source()
			if err != nil {
				return nil, err
			}
			//ctxq = append(ctxq, src)

			for k, v :=range src.(map[string]interface{}) {
				ctxq[k] = v
			}

		}
		suggester["context"] = ctxq
	}

this is correct,you can look

**Comment by olivere** [comment]
I'm about to release v3.0.45 and v2.0.52 which should fix this issue. Please comment here if that doesn't solve your problem. Thanks for contributing to Elastic.
