### ISSUE TITLE
problem with from and size

### ISSUE THREAD

**Issue by jxstanford** [olivere/elastic#333]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ X ] elastic.v3 (for Elasticsearch 2.x)

### Please describe the expected behavior
When From = 0 and limit = 3, I would expect 13records returned

### Please describe the actual behavior
I have 8 records in my test index, and all 8 are returned

### Any steps to reproduce the behavior?
```
body := "{\"query\":{\"match_all\":{}}}"
sr, err := s.db.Search(indices).Source(body).
	From(0).Size(3).
	ExpandWildcards("open").AllowNoIndices(false).Do()
```

Any guidance appreciated!

**Comment by olivere** [comment]
When you're passing the body as a string, you opt out of the DSL. You either construct the body yourself or you choose the DSL to do that for you. You can't mix both.

So either:

```go
sr, err := s.db.Search(indices).Source(elastic.NewMatchAllQuery()).From(0).Size(3).Do()
```

or

```go
sr, err := s.db.Search(indices).Source(`{"query":{"match_all":{}},"from":0,"size".3"}`).Do()
```
