### ISSUE TITLE
Bulk Processor refresh

### ISSUE THREAD

**Issue by kristen1980** [olivere/elastic#335]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ x] elastic.v3 (for Elasticsearch 2.x)

### Any steps to reproduce the behavior?

Thank you for this excellent library! I noticed in the Bulk Requests there is a way to refresh the index when the bulk action is finished. However, this behavior does not exist in the Bulk Processor. Is that on purpose? (Right now I am manually refreshing the index after I close the Bulk Processor...I could put it in an After function but would seem nice to have a method for BulkProcessorService).

Thanks again!

thanks!

**Comment by olivere** [comment]
Thanks for the kind words. I've used so many OSS projects in my life as a developer that it's a pleasure to give something back.

Regarding your question: You're correct, there's no way in `BulkProcessor` to refresh manually. However, refreshing is expensive in terms of I/O and should be avoided unless absolutely necessary (especially when bulk indexing). BTW: Refresh will get optimized in ES 5.0: [This blog post](https://www.elastic.co/blog/refreshing_news) gives a nice overview.

If you still want to refresh, enabling `Refresh` in one of the `BulkableRequest` instances you add to bulk processor should do the trick. All 3 bulk request types (`BulkDeleteRequest`, `BulkIndexRequest` and `BulkUpdateRequest`) have an option to enable `Refresh`.

Finally, closing the `BulkProcessor` should ensure that all requests are committed before it returns. Or did it fail for you?

**Comment by kristen1980** [comment]
Finally, closing the BulkProcessor should ensure that all requests are committed before it returns. Or did it fail for you?

It closes and commits fine.

**Comment by kristen1980** [comment]
I also tried doing the refresh via your suggested BulkUpdateRequest but it seemed to take a long time to refresh. I'll just refresh it manually when I am done. thx!
