### ISSUE TITLE
Should I maintain a connection pool?

### ISSUE THREAD

**Issue by jinleileiking** [olivere/elastic#338]
I didnot check the source code.

When I call `NewClient` does it mean setup up  a new tcp connection?

should I keep the persistent connection And reuse it ?

**Comment by olivere** [comment]
No need for your own pool. Go's stdlib keeps a pool of HTTP connections for you automatically.

**Comment by joshua0x** [comment]
can i control max conns ?

**Comment by olivere** [comment]
You can pass in your own http.Client/http.Transport and can control anything that is available from within the standard library.
