### ISSUE TITLE
PingService: ping cluster or default client's URLs

### ISSUE THREAD

**Issue by VojtechVitek** [olivere/elastic#340]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[x] elastic.v3 (for Elasticsearch 2.x)

### Please describe the expected behavior

PingService should be able to pick up `client`'s URL when invoked with `elastic.NewPingService(client).Do()`. Ideally, the PingService would try to ping at least one node in the cluster.

### Please describe the actual behavior

PingService tries to ping "localhost:9200" when no URL was given. See below example:

### Any steps to reproduce the behavior?

```go
client, err := elastic.NewClient(elastic.SetURL("http://node1.example.com:9200", "http://node1.example.com:9200"))
if err != nil {
		return err
}

elastic.NewPingService(client).Do() // pings localhost:9200 instead of above example.com URLs
```

The above example has very unexpected behavior.

Cluster ping would be awesome -- any plans to implement it?

**Comment by VojtechVitek** [comment]
Closing. I discovered ClusterHealthService.

**Comment by olivere** [comment]
Yeah. Ping is special to some extent. I tried to describe in [the Wiki](https://github.com/olivere/elastic/wiki/Ping).

**Comment by VojtechVitek** [comment]
@olivere this would be super useful in the godoc too.

It was quite difficult to find out how to run basic health check on my cluster. I discovered it accidentally while reading the code (client.go, connection.go and ping.go) itself. :)
