### ISSUE TITLE
Question: How to use scroll parameter in SearchService?

### ISSUE THREAD

**Issue by joyt** [olivere/elastic#341]
Hi there, I'm trying to execute a _search call but I couldn't figure out how to set the [scroll query parameter](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html) e.g. (http://elasticsearch:9200/entitites/entities/_search?scroll=1m) in my code:
```go
resp, err := client.Search("entities").
Type("entities").
Query(query).
Sort("field", true).
Size(100).
Do()
```
I couldn't find an example of the correct way to execute this, but I assume `ScrollService` is for after you already have a scrollId? Any help would be appreciated, thanks!

**Comment by olivere** [comment]
Hi, sorry for the delay.

If all you want to do is scroll through the documents specified via a search query, you have [`ScanService`](https://github.com/olivere/elastic/blob/release-branch.v3/scan.go) and [`ScrollService`](https://github.com/olivere/elastic/blob/release-branch.v3/scroll.go). Both abstract the scrolling away for you and you get a cursor-like experience. See [this test](https://github.com/olivere/elastic/blob/release-branch.v3/scan_test.go#L41-L85) for an example.

Two warnings though: First, you should use `ScanService` for Elastic v2 and v3. The differences are subtle, you can find several discussions about that in GitHub issues.  Second, I will replace/merge both with a new mechanism in Elastic v5 (for ES 5.0) and will backport it when it's ready. So you might need to adopt the "new" approach in a few weeks. Don't worry, it won't be too different, but it'll be safe for concurrent use (which `ScanService` isn't).

HTH.

**Comment by olivere** [comment]
BTW: `ScrollService` has been refactored in 3.0.48. See [this example in the Wiki](https://github.com/olivere/elastic/wiki/ScrollParallel) to illustrate scrolling in parallel.
