### ISSUE TITLE
Documentation improvements for BulkProcessor example

### ISSUE THREAD

**Issue by uynap** [olivere/elastic#343]
Hi,

When I went through the documents of BulkProcessor, I found the example can be more clear. 
In the link below, an instance of Tweet is created but never used.
https://github.com/olivere/elastic/wiki/BulkProcessor#indexing

It's better to change it from
`r := elastic.NewBulkIndexRequest().Index("twitter").Type("tweet").Id("12345")`
to
`r := elastic.NewBulkIndexRequest().Index("twitter").Type("tweet").Id("12345").Doc(t)`.

Regards,
 -
Pan Yu

**Comment by olivere** [comment]
Hey. Thanks for reporting. I fixed it.
