### ISSUE TITLE
Multiple CompletionSuggesters?

### ISSUE THREAD

**Issue by jgoodall** [olivere/elastic#345]
elastic.v3 (for Elasticsearch 2.x)

I have a suggester set up and working for a single field:

```
const suggestorName = "typeahead"
var suggestor = elastic.NewCompletionSuggester(suggestorName)
field := "source_ip_suggest"
text := "10"
res, err := Client.Suggest(indices).Suggester(suggestor.Field(field).Text(text)).Do()
```

I can't figure out a way to use multiple suggesters - is that supported? I have two fields, `source_ip` and `dest_ip` and I would like to get a combined list of completions across the fields.

I realize I can do this at index time by adding both source and dest IPs to the same completion field, but then I would be storing the same data twice.

I can do so using `curl` and the elasticsearch http api like so:

```
curl -XPOST "http://localhost:9200/<index>/_search" -d'
{
   "size": 0,
   "suggest": {
      "text": "10",
      "dip-suggest": {
         "completion": {
            "field": "dest_ip_suggest"
         }
      },
      "sip-suggest": {
         "completion": {
            "field": "source_ip_suggest"
         }
      }
   }
}'
```

**Comment by olivere** [comment]
Oh, a long time since I touched suggester code ;-)

[This test](https://github.com/olivere/elastic/blob/release-branch.v3/suggest_test.go#L66-L79) illustrates that you can add multiple suggesters. Is that what you're looking for?

HTH

**Comment by jgoodall** [comment]
Yes, that works! I had not realized from the documentation that you could add multiple suggesters.
