### ISSUE TITLE
Possible problem with UpdateService with partial doc

### ISSUE THREAD

**Issue by jgoodall** [olivere/elastic#347]
Using elastic.v3, trying to update a field in an existing document using the UpdateService and I get unexpected results. 

If I do the following the field (`handled`) is updated properly: 

```
curl -XPOST "http://localhost:9200/<index>/<type>/<id>/_update" -d'
{
   "doc": {
      "handled": true
   }
}'
```

If I do this in my code with a new object (`doc`) with only the `handled` field set:

```
	res, err := Client.Update().
		Index(index).
		Type(docType).
		Id(id).
		Doc(doc).
		Refresh(true).
		Do()
```

I do not get an error, but `Created` is false in the response. If instead of passing `Doc` the new struct with the updated values, I pass it json (`[]byte`), I get an error:

```
elastic: Error 500 (Internal Server Error): Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes [type=not_x_content_exception]
```

Same thing if I pass it a json string. What exactly is supposed to be in `Doc` argument? Or am I just doing it wrong?

**Comment by olivere** [comment]
Do the tests in `update_test.go` help, especially [this one](https://github.com/olivere/elastic/blob/release-branch.v3/update_test.go#L167-L198)?

**Comment by olivere** [comment]
Did this help? Can I close the issue?

**Comment by jgoodall** [comment]
I wont have a chance to look until next week, but I can reopen if it I still have questions. Thanks for pointing at the test, that syntax was not immediately obvious from the documentation.

**Comment by olivere** [comment]
Sure. It should be in line with the syntax described in the [Update API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html). If it's not, let me know and we see what we can do about it.
