### ISSUE TITLE
How to set mapping? Need to specify "index": "not_analyzed" for a field

### ISSUE THREAD

**Issue by mkhetan** [olivere/elastic#348]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ x] elastic.v3 (for Elasticsearch 2.x)

### Please describe the expected behavior

Sort is not working for a field. It seems we need to make that field "not_analyzed".

### Please describe the actual behavior

Can't find a way to specify mapping where i can specify this for this field:

"index": "not_analyzed"

When to specify mapping? Before or while creating Index? Should I use PutMapping() function?

### Any steps to reproduce the behavior?

This is not an issue but a query on how to use mapping with Olivere elastic client.
Hope this is the right place to ask this.

Thanks,
mayank

**Comment by olivere** [comment]
Elastic doesn't have an API to specify a mapping in Go code. You simply pass it a string when creating an index. There's an example in the wiki: [How to create an index](https://github.com/olivere/elastic/wiki/CreateIndex). If that doesn't help, read the tests; there are quite a few of them.

HTH.

**Comment by mkhetan** [comment]
Hi,

This is exactly I was looking for. Thanks a bunch!

regards,
mayank
