### ISSUE TITLE
Running Elastic with query string

### ISSUE THREAD

**Issue by sofo23** [olivere/elastic#349]
Hi,
I am using Elastic 3. Given a query string like this (in Sense):

GET employee/info/_search
{
    "query":{
        "bool": {
            "should": [
               {"match": {"name": "Rodri"}},
                {"match": {"name": "Massadra"}}
            ]
        }
    }
}

How should I use Elastic to run this query and got the result? I have a set of queries already available as string (query DSL format). I don't have to write them again. You can find also  this question on [StackOverflow](http://stackoverflow.com/questions/39309862/querying-elasticsearch-from-golang). 
 Thank for your help.

**Comment by olivere** [comment]
Please have a look at the Wiki and the test files (e.g. [search_queries_bool_test.go](https://github.com/olivere/elastic/blob/release-branch.v3/search_queries_bool_test.go)). They illustrate all aspects of using Elastic.

HTH

**Comment by sofo23** [comment]
Thank you for your reply.

Regards
David

2016-09-04 11:01 GMT+02:00 Oliver Eilhard <notifications@github.com>:
