### ISSUE TITLE
How to construct filter query?

### ISSUE THREAD

**Issue by mlen108** [olivere/elastic#35]
Hi there,

Thanks for a great library :-)

I'm having a bit of trouble to construct a Search API query, in Query DSN this looks like (truncated for readability):
```json
{
    "filter": {
        "term": {
           "Status": "3"
       }
    },
   "query": {
      "match": {
          "MyField": {
              "query": "something",
              "minimum_should_match": "75%"
          }
      }
   }
}
```

I have constructed this query using `elastic` but I can't figure out how to make the `filter` to work.
```go
q := elastic.NewMatchQuery("MyField", my_query).MinimumShouldMatch("75%")
t := elastic.NewQueryFilter(elastic.NewTermFilter("Status", "3"))
sres, _ := dbc.Search().
    Index("MyIndex").Type("MyType").
    Query(&q).Do()
```

I don't see `Filter` method but there's `PostFilter` (too slow in my case).

Perhaps I should somehow pass `t` to `q` and then to `Query` method?

Would appreciate some hints.

**Comment by olivere** [comment]
Hi,

maybe you're looking for the [post_filter](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-request-post-filter.html#search-request-post-filter)?

There's an example in the [test for search source](https://github.com/olivere/elastic/blob/master/search_source_test.go#L109).

**Comment by mlen108** [comment]
Yes! Funny enough, I used `PostFilter` but somehow didn't debug the query and I thought this library maps ES' methods 1:1, so I was still looking for `Filter`...

Thanks!
