### ISSUE TITLE
Source() function for SearchService

### ISSUE THREAD

**Issue by sundarv85** [olivere/elastic#350]
For debugging purposes, When I want to print the aggregate object, what I do is:

```
                a, _ := eventAggs.Source()
                PrintJSON(a) //PrintJSON is my helper function to print it
```

I use the `Source()` function, to get the source. Would it be possible, to do the same for the SearchService too?

```
    search := es.Client.Search().
        Index(masterIndex).
        Query(query).
        Size(0).
            Aggregation(aggName, agg)

       a, _ := search.Source()
       PrintJSON(a)
```

Since the search does not have a `Source()`, the above does not work.

**Comment by olivere** [comment]
Sure, that seems to be helpful. I'm unsure if `PrintJSON` would be a function on the struct, or if we'd follow a pattern like [`httputil.DumpRequest`](https://golang.org/pkg/net/http/httputil/#DumpRequest)--which would live in a separate package.

**Comment by sundarv85** [comment]
`PrintJSON` is my helper function that lives in a separate package. So we do not need it as part of elastic.v3. It can like separately like `httputil.DumpRequest`

**Comment by olivere** [comment]
Maybe we can add it to some kind of elastic-contrib. Is it online somewhere? On the other hand: What does it do exactly? Would it be better to be able to deserialize a response to JSON?

**Comment by sundarv85** [comment]
This is the function

```
func PrintJSON(x interface{}) {
	d, err := json.MarshalIndent(x, "", "  ")
	if err != nil {
		fmt.Errorf("PrintJSON failed with error: %s\n", err)
		return
	}
	os.Stdout.Write(d)
	os.Stdout.Write([]byte("\n"))
	return
}
```

It only deserializes a structure, not a http response.

**Comment by olivere** [comment]
Well, that's pretty straightforward and not required as part of Elastic. I thought you did something more complex.

BTW: The last response body is available [here](https://github.com/olivere/elastic/blob/release-branch.v3/response.go#L21) and returned by [PerformRequestC](https://github.com/olivere/elastic/blob/release-branch.v3/client.go#L1057). But it's only exposed via the `Decoder` interface, so you could access it by [implementing and specifying a custom decoder](https://github.com/olivere/elastic/wiki/Decoder).

**Comment by sundarv85** [comment]
Did you get a chance to take a look into this. Note that I'm trying to print the request.

**Comment by olivere** [comment]
To clarify: What you're really looking for is for any service to print out the request that will be sent down to ES?

(What I typically do in this case is to enable the trace log.)

**Comment by sundarv85** [comment]
yes, that is correct. The problem with enabling the trace log is, the pretty printing cannot be enabled for requests. There was an previous issue on this #188 

The aggregate for e.g. has the Source() function. However, the complete request does not have the source.

**Comment by olivere** [comment]
Okay.

Problem is: I don't see a nice way to do this.

The services are builders. Its functions are typically setters that return the builder so calls can be chained. E.g. the `Source()` function is already there to enable callers to manually set the request body. So `Source()` is not the way to go.

On the one hand I see the benefit of this. On the other I don't see it as a core functionality required for core. The problem of not being able to pretty-print a request is a generic problem with HTTP requests, not something that's specific to Elastic. Go has `net/http/httputil.DumpRequestOut` that is being used with the trace log.

We could probably add an `Encoder` as a counterpart for [`Decoder`](https://github.com/olivere/elastic/wiki/Decoder), but I'm not sure it's worth it. That would give you at least a chance to intercept on the encoding step.

Ideas?

**Comment by sundarv85** [comment]
`Encoder` seems to be something that we can give a try.

**Comment by NeoCN** [comment]
@olivere maybe add SetRequestLogger and SetResponseLogger can help debug ? When SetTraceLog, developers can not control the output format.
```
type RequestLogger func(req *http.Request)
type ResponseLogger func(resp *http.Response) 
```
sometimes we just want to log es request and response, without other trace logs

**Comment by olivere** [comment]
@NeoCN If you want deep information about request/response, [use a `http.Transport`](https://github.com/olivere/elastic/wiki/HttpTransport).

**Comment by olivere** [comment]
With 5.0.51, you have access to `SearchRequest.Body`. I hope this solved the issue.

**Comment by olivere** [comment]
@larrycinnabar What's wrong with building your own [`SearchSource`](https://github.com/olivere/elastic/blob/release-branch.v6/search_source_test.go), cache that, then pass it into search service via [`SearchService.SearchSource(...)`](https://github.com/olivere/elastic/blob/release-branch.v6/search.go#L45-L52)?
