### ISSUE TITLE
Geo Distance Query

### ISSUE THREAD

**Issue by Noeru14** [olivere/elastic#351]
Hi!

### Which version of Elastic are you using?
[ ] elastic.v3 (for Elasticsearch 2.x)

I created an index "findmystore" and two types "file" (that doesn't matter) and "store".
"store" is composed of a location (struct with a lat and a lon), an address, a postal and a city. For example, I get this as a description when I look at one element of type "store" : 

```
"_source": {
    "location": {
        "lat": 50.6341605,
        "lon": 3.0656515
    },
    "address": "40 rue Des Tanneurs",
    "postal": 59000,
    "city": "LILLE"
},
```

I'm using currently using the following code to make the query and execute it : 

```
distanceQuery := elastic.NewGeoDistanceQuery("store.location")
distanceQuery = distanceQuery.Lat(48.81433999999999)
distanceQuery = distanceQuery.Lon(2.3204906)
distanceQuery = distanceQuery.Distance("5km")

boolQuery := elastic.NewBoolQuery()
boolQuery = boolQuery.Must(elastic.NewMatchAllQuery())
boolQuery = boolQuery.Filter(distanceQuery)

searchResult, err := client.Search().Index("findmyfpstore").Type("store").Query(boolQuery).Do()
```

As store seems to be already specified in the first line of the code, I tried removing it in either the first or the last line but it doesn't seem to change much as I keep getting this error : elastic: Error 400 (Bad Request): all shards failed [type=search_phase_execution_exception]
I also tried to get the source of the boolQuery and execute it on elasticsearch head but it returns me the same error.

Thanks in advance!

**Comment by olivere** [comment]
Can you please enable the trace log and send me the output of your request and response. See [here](https://github.com/olivere/elastic/wiki/Logging) on how to enable the trace log.

**Comment by Noeru14** [comment]
Thanks for your reactivity

I'm looking to enable and get the trace log.

While I'm doing this, I have more information from elasticsearch head, maybe it can help as it is the same error I get on the console when I execute my script : 

```
{
    "error": {
        "root_cause": [
            {
                "type": "search_parse_exception",
                "reason": "failed to parse search source. unknown search element [bool]",
                "line": 1,
                "col": 9
            }
        ],
        "type": "search_phase_execution_exception",
        "reason": "all shards failed",
        "phase": "query",
        "grouped": true,
        "failed_shards": [
            {
                "shard": 0,
                "index": "findmyfpstore",
                "node": "1d-Qdj0WQla_w6ZpvkhShQ",
                "reason": {
                    "type": "search_parse_exception",
                    "reason": "failed to parse search source. unknown search element [bool]",
                    "line": 1,
                    "col": 9
                }
            }
        ]
    },
    "status": 400

}
```

**Comment by olivere** [comment]
Yes. Seems like your query is malformed. It's the same issue as [this](https://github.com/elastic/elasticsearch/issues/14811). I need to look at your code to find out what's wrong. The code sample you submitted above looks okay.

**Comment by Noeru14** [comment]
The whole code looks like that, there are not much things happening aside from connecting to ElasticSearch and printing the results:  

```
package main

import (
	elastic "gopkg.in/olivere/elastic.v3"
	"encoding/json"
	"fmt"
)

type Location struct {
	Lat			float64 	`json:"lat"`
	Lon			float64		`json:"lon"`
}

type Store struct {
	Loc			Location	`json:"location"`
	Address		string		`json:"address"`
	Postal		int			`json:"postal"`
	City		string		`json:"city"`
}

type Coord struct {
	RequestId	int			`json:"request_id"`
	Lat			float64		`json:"lat"`
	Lon			float64		`json:"lon"`
}

func main() {
	client, err := elastic.NewClient()
	CheckErr(err)

	distanceQuery := elastic.NewGeoDistanceQuery("store.location")
	distanceQuery = distanceQuery.Lat(48.81433999999999)
	distanceQuery = distanceQuery.Lon(2.3204906)
	distanceQuery = distanceQuery.Distance("10km")

	boolQuery := elastic.NewBoolQuery()
	boolQuery = boolQuery.Must(elastic.NewMatchAllQuery())
	boolQuery = boolQuery.Filter(distanceQuery)

	src, err := boolQuery.Source()
	CheckErr(err)
	
	data, err := json.Marshal(src)
	CheckErr(err)
	
	got := string(data)
	
	fmt.Println(got)
	
	searchResult, err := client.Search().Index("findmyfpstore").Type("store").Query(boolQuery).Do()
	CheckErr(err)

	if searchResult.Hits.TotalHits > 0 {
		fmt.Printf("Found a total of %d stores\n", searchResult.Hits.TotalHits)

		for _, hit := range searchResult.Hits.Hits {
			var s Store
			err := json.Unmarshal(*hit.Source, &s)
			if err != nil {
				// deserialization failed
			}

			fmt.Printf("Store from - Address : " + s.Address + " ; City : " + s.City)
		}
	} else {
		fmt.Print("Found no stores\n")
	}
}

func CheckErr(err error) {
	if err != nil {
		fmt.Println(err)
	}
}
```

**Comment by Noeru14** [comment]
I get this after enabling the trace log :

```
ELASTIC 2016/09/07 12:50:56 POST /findmyfpstore/store/_search HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/3.0.50 (linux-amd64)
Transfer-Encoding: chunked
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip

1
{
94
"query":{"bool":{"filter":{"geo_distance":{"distance":"10km","store.location":{"lat":48.81433999999999,"lon":2.3204906}}},"must":{"match_all":{}}}}}
0


elastic: Error 400 (Bad Request): all shards failed [type=search_phase_execution_exception]
```

**Comment by olivere** [comment]
This one works fine: https://gist.github.com/olivere/2804a338bd743ac09942180000c6b325

Watch out! It will delete your index and recreate it with a mapping on every execution!

**Comment by Noeru14** [comment]
Thanks for your solution.
I used to make a search query in an older version to retrieve all the existing stores but it doesn't seem to work very well with the mapping (I corrected the mapping a bit as there was 2 address properties) : 
	searchResult, err := client.Search().
		Index(indexName).
		Type(storeType).
		Do()
	CheckErr(err)

It returns an error 503 : 
POST /findmyfpstore/store/_search HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/3.0.50 (linux-amd64)
Transfer-Encoding: chunked
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip

1
{
1
}
0


elastic: Error 503 (Service Unavailable): all shards failed [type=search_phase_execution_exception]
panic: runtime error: invalid memory address or nil pointer dereference

I switched the number of shards to 5 and it seems to work better, I'm continuing to test!

**Comment by olivere** [comment]
The code above does not execute any search query. The `Query` part is
simply missing.

**Comment by Noeru14** [comment]
Thanks for your replies, I think it's working well! One more question, why do you delete the index and recreate it on every execution ? Is this necessary ?

**Comment by olivere** [comment]
No. Of course it's not. But that makes the example idempotent: It does
behave exactly the same every time you call it.

**Comment by Noeru14** [comment]
I understand, thanks again!
I finally found the combination of funcs I needed to find the closest store for a specified location, I'll leave this here in case it might help someone: 

```
	geoDistanceSorter := elastic.NewGeoDistanceSort("location").
		Point(48.81433999999999, 2.3204906).
		Unit("km").
		GeoDistance("plane").
		Asc()
	
	matchAllQuery := elastic.NewMatchAllQuery()
	searchResult, err := client.Search().
		Index(indexName).
		Type(typeName).
		Query(matchAllQuery).
		Size(1).
		SortBy(geoDistanceSorter).
		Do()
```

**Comment by olivere** [comment]
Closing the issue then.
