### ISSUE TITLE
Add `request_cache` to search

### ISSUE THREAD

**Issue by olivere** [olivere/elastic#353]
ES 2.x added `request_cache` to REST API spec for Search API.

**Comment by timeemit** [comment]
Hey @olivere -- Just tried to use this feature and am seeing 

```
SearchParseException[failed to parse search source [{"request_cache":false}]]; nested: SearchParseException[failed to parse search source. unknown search element [request_cache]]
```

The [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html) explains that
> the request_cache must be passed as query-string parameters. The rest of the search request should be passed within the body itself.
