### ISSUE TITLE
Scroll with Sort?

### ISSUE THREAD

**Issue by mkhetan** [olivere/elastic#354]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ x] elastic.v3 (for Elasticsearch 2.x)

### Please describe the expected behavior

My current mechanism is as follows:

            searchResult, err := client.Search().
                Index(group).
                Type(itype).
                Query(q).
                Sort("prefix", true).
                From(start).Size(size).
                Pretty(true).
                Do()

But, i was not able to display more than 10000 results. I could change index.max_result_window . But, elasticsearch documentation recommends the use of scroll instead of increasing this limit.

I was able to use your Scroll API in this manner:

        searchResult, err := client.Scroll(group).Type(itype).Query(q).
            Size(1000).
            ScrollId(scrollId).
            Do()

But, then, I could not use "Sort".

### Please describe the actual behavior

Is there a way I can use Sort along with Scroll?

Or should i use a completely different way to achieve my application. I need to have a query and my result sorted in an order based on a parameter "prefix" in my database.

**Comment by olivere** [comment]
Please update your version of elastic.v3. There has been updates to the [`Scroll`](https://github.com/olivere/elastic/blob/release-branch.v3/scroll.go) service recently. The [tests](https://github.com/olivere/elastic/blob/release-branch.v3/scroll_test.go) typically help you as well.

Here's [an example](https://github.com/olivere/elastic/wiki/ScrollParallel) of how to use if efficiently. See also the warning about sorting in the last section. If you have a large index and you want good performance, you shouldn't sort.

Please re-open if this doesn't answer your question.

**Comment by mkhetan** [comment]
Cool! Thanks for a quick response. I should have kept the package unto
date. This is exactly we were looking for it. It seems to be working. Will
take care of performance.

Regards,
mayank
