### ISSUE TITLE
geo_distance aggregation: Different results for different syntax

### ISSUE THREAD

**Issue by tarun91vas** [olivere/elastic#358]
#### Versions
1. elastic version: elastic.v2
2. ES version : 2.1.1

### Expected behavior
I am moving a search application to golang where I am using geo_distance aggregation. Previous language was php where query used for geo_distance aggregation was 
```
"distance": {
      "geo_distance": {
        "field": "location",
        "origin": {
          "lat": 12.97401,
          "lon": 77.612357
        },
        "unit": "km",
        "ranges": [
          {
            "from": 0,
            "to": 2
          },
          {
            "from": 0,
            "to": 5
          }
        ]
      }
    }
```
which gave expected response as below
```
"distance": {
      "buckets": [
        {
          "key": "*-2.0",
          "from": 0,
          "from_as_string": "0.0",
          "to": 2,
          "to_as_string": "2.0",
          "doc_count": 99
        },
        {
          "key": "*-5.0",
          "from": 0,
          "from_as_string": "0.0",
          "to": 5,
          "to_as_string": "5.0",
          "doc_count": 383
        }
      ]
    }
```

I created geo_distance aggregation using `olivere.v2`  which generated below query source
```
"distance": {
      "geo_distance": {
        "field": "location",
        "origin": "12.97401,77.612357",
        "ranges": [
          {
            "from": 0,
            "to": 2
          },
          {
            "from": 0,
            "to": 5
          }
        ]
      }
    }
```
but the actual output given below is not expected one
```
"distance": {
      "buckets": [
        {
          "key": "*-2.0",
          "from": 0,
          "from_as_string": "0.0",
          "to": 2,
          "to_as_string": "2.0",
          "doc_count": 0
        },
        {
          "key": "*-5.0",
          "from": 0,
          "from_as_string": "0.0",
          "to": 5,
          "to_as_string": "5.0",
          "doc_count": 0
        }
      ]
    }
```
The doc count received is different in both the cases. Same data source is used for both the queries and es query on which aggregation is calculated is also same.

Can you help me on this ? Although official elasticsearch  documentation says both queries are right for geo_point field type.

**Comment by olivere** [comment]
Hmm... first thing I see that differs is that the `"unit":"2km"` is missing in the 2nd query. But it's hard to tell what's wrong without having anything to reproduce the problem. Can you perhaps create a small test, including data, that illustrates the problem?

With regards to ES, please always look into the `*_test.go` files in elastic. There are lots of tests, and some of them might actually do exactly what you are looking for.

**Comment by olivere** [comment]
Any news on this?

**Comment by tarun91vas** [comment]
@olivere Yes...what you said is right, the unit which it takes by default is "meters", as mentioned [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-geodistance-aggregation.html).

The query source below fixed it.
```
"distance": {
			"geo_distance": {
				"field": "location",
				"unit": "km",
				"origin": "12.932375,77.623637",
				"ranges": [{
					"from": 0,
					"to": 2
				}, {
					"from": 0,
					"to": 5
				}]
			}
		}
```
Thanks!

**Comment by olivere** [comment]
Perfect. Then I'll close this.
