### ISSUE TITLE
Sample Programs written with olivere/elastic v3

### ISSUE THREAD

**Issue by dinilv** [olivere/elastic#360]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)

### Please describe the expected behavior
Hi,
Is any sample programs/projects which is using this package to interact with ES? Am a newbie to both Go & ES . Any lead would be helpful :-)

**Comment by olivere** [comment]
Best advice is to read the Wiki and the tests in the project. There's tons of tests.

Next, you might look up [packages that import elastic](https://godoc.org/gopkg.in/olivere/elastic.v3?importers) via [godoc.org](https://godoc.org/).

**Comment by dinilv** [comment]
Thanks olivere for ur quick response... I would like know, is it good practice to pool the elastic connections and is it possible through this package ?

**Comment by olivere** [comment]
You typically create one `*elastic.Client` per application and share it across your Goroutines. It's thread-safe. Pooling of HTTP connections is done by `net/http`.

**Comment by dinilv** [comment]
Thanks Again Olivere for both tips 👍 👍
