### ISSUE TITLE
no ElasticSearch node available when executing as a daemon

### ISSUE THREAD

**Issue by Noeru14** [olivere/elastic#361]
Hi!

### Which version of Elastic are you using?
elastic.v3 (for Elasticsearch 2.4)

### Please describe the actual behavior
If I execute the program after building it, it finds the ElasticSearch node without any problem. However, if I try to run the same program as a daemon, it returns the following error "no ElasticSearch node available". The ElasticSearch node also runs on the same server as a daemon. There is only a single node in the cluster.

I use the following line of codes to create a client that connects to ES :
```
		client, err = elastic.NewClient(
			elastic.SetSniff(false),
			elastic.SetURL("http://127.0.0.1:3306"),
		)
```

I tried to use this URL instead "http://localhost:3306" but it doesn't seem to work better.

Thanks in advance!

**Comment by olivere** [comment]
3306 is typically the MySQL endpoint. Are you sure you don't want 9200?

**Comment by Noeru14** [comment]
Thanks for your fast reply, it works now. I had to use the 3306 port for a test with multiple nodes as I had a communication problem with the port 9200. Thanks again!
