### ISSUE TITLE
Function score query's filter ignored

### ISSUE THREAD

**Issue by gm42** [olivere/elastic#364]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[x] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
When using a function score query's filter, one would expect such filter to be used.

```
	fsq := elastic.NewFunctionScoreQuery()
	s := elastic.NewScript(`some script here`)
	s.Lang("expression")
	someScoreFunc := elastic.NewScriptFunction(s)

	fsq.AddScoreFunc(someScoreFunc)

	fsq.BoostMode("replace")

	fsq.Filter(someFilterHere) // <-- notice this

	fsq.Query(elastic.NewBoolQuery())

	searchSource := elastic.NewSearchSource().Query(fsq)
```

### Please describe the actual behavior
It does not appear in source:
```json
"query": {
        "function_score": {
            "boost_mode": "replace",
            "query": {
                "bool": {}
            },
            "script_score": {
                "script": {
                    "inline": "some script here",
                    "lang": "expression"
                }
            }
        }
    }
```

If I move the `.Filter` to the query used in the function score query, then I see filters there but I am not sure this is correct.

**Comment by olivere** [comment]
Hmm... I'm pretty sure there was a time where you could either specify a filter or a query, but not both. Cannot find the reference in the Elasticsearch code though.

Anyway, it's the responsibility of the caller to use Elasticsearch correctly. So I will remove this check in the next release.

**Comment by olivere** [comment]
In 2.4, [`FunctionScoreQueryBuilder`](https://github.com/elastic/elasticsearch/blob/2.4/core/src/main/java/org/elasticsearch/index/query/functionscore/FunctionScoreQueryBuilder.java) only allows to specify a Query, not a filter.

**Comment by gm42** [comment]
@olivere I am running `v2.3.5` and it accepts the filter (it was enough to remove the `.Query` assignment in example of OP).

Thanks for the reference, so I guess in v2.4 it just merges those two (queries and filters)?

**Comment by olivere** [comment]
2.0 [merged queries and filters](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_query_dsl_changes.html#_queries_and_filters_merged), so I guess it was a relict from code in 1.x. I went back all the way to 2.0 and FSQ doesn't have a filter in any 2.x release.

I cannot find a reference to a `filter` in the [2.3 branch](https://github.com/elastic/elasticsearch/blob/2.3/core/src/main/java/org/elasticsearch/index/query/functionscore/FunctionScoreQueryBuilder.java) as well. The functions have filters, but not the FSQ.

**Comment by gm42** [comment]
@olivere ok so even if it's being sent as this:
```
{
    "query": {
        "function_score": {
            "boost_mode": "replace",
            "filter": {
                "bool": {
                    "filter": [
                        {
                            "term": {
                                "foo": 378328743
                            }
                        }
                    ]
                }
            },
            "script_score": {
                "script": {
                    "inline": "something here",
                    "lang": "expression"
                }
            }
        }
    },
    "size": 0
}
```

It has no effect on the actual results?

**Comment by olivere** [comment]
I don't think so. I think the correct way would be to replace `"filter"` with `"query"`. You could easily test that with your data, couldn't you?

Maybe ES has a fallback that uses `filter` when `query` is missing, but I don't know. ES 2.x is rather forgiving: I recently found that it even applied a query even when you specified it as `{"query":{"query":{"match_all":{}}}}`. ES 5.x bailed when you do that.

**Comment by gm42** [comment]
@olivere yeah I confirm that `"filter"` is equivalent to `"query"`: it is being accepted as synonymous and it is effective. The client library should probably go with `query` since that's what is documented right now: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html

Funny note about that syntax laxness, I hope they can backport some strictness to 2.x as I do not plan to upgrade for now!

I am now diving into the use of filter for the specific functions (that is something I need to use too); as per this issue, shall you close it when there is a change in the release branch?

**Comment by olivere** [comment]
I've already prepared a change that removes the use of `Filter` for FQS in the next update. So I'll close this.

Good luck with FSQ. It's an interesting query but it was a lot of work implementing that and working through the Java code. There might still be dragons.

**Comment by gm42** [comment]
@olivere ok, thanks! I think you implemented it pretty correctly for my use-case, but I'll keep eyes open.
