### ISSUE TITLE
The type for Max/Min aggregation's Value

### ISSUE THREAD

**Issue by mlen108** [olivere/elastic#37]
Hi again :)

Is there any reason that the `Value` field on `AggregationValueMetric` is of type `float64` ? ([see here](https://github.com/olivere/elastic/blob/bd9d7262e855668e96299b6acc09c77f3c37fedb/search_aggs.go#L367 ))

I'm using date histogram aggregation with max aggregation (on field which is of type `time.Time`).

So the results returned from pure ES are:
```json
...
"key_as_string": "2015",
"key": 1420070400000,
"doc_count": 9256,
"latest": {
    "value": 1423589933165
},
...
```

but in `elastic` I'm getting `1.422469422e+12` for the `latest` value... Obviously the original int(64?) is cast to float64.

ES docs does not specify type for Min/Max, it only mentions "...returns the maximum value among the numeric values extracted from the aggregated documents..."

Ideally, I'd prefer if it returns the type same as original value's type.

Thanks, Maciek

**Comment by olivere** [comment]
I see. Maybe we should go for `interface{}` and provide a `json.Number` helper as I already did with the `AggregationBucketKeyItem`in [this commit](https://github.com/olivere/elastic/commit/bd9d7262e855668e96299b6acc09c77f3c37fedb).

**Comment by mlen108** [comment]
Yes, indeed. Something like above would be perfect. I can PR this if you're happy.

**Comment by olivere** [comment]
Sure. Go ahead if you've got the time. Looking forward to it :-)

**Comment by mlen108** [comment]
The current `float64` type is okay. It's not worth (or makes sense) to change it. Here's why:

1) ES will support `format` for numeric metric aggregations! - similar to date/histogram's for example. This new functionality [was recently merged into its master](https://github.com/elasticsearch/elasticsearch/pull/9032).
2) To my understanding ES always returns `float64` (or `double` in Java world ;-) for numeric aggs' values.

My initial results fooled me:
```json
"latest": {
    "value": 1423589933165
}
```

The client-side server I use for debugging returns this and I thought the value's `int` but it's not - it's float, always float.


So my rather dirty solution to get `time` object from the max value is something like:
```go
...
for _, x := range data.Buckets {
    latest, _ := x.Max("latest")
    timestamp := int64(*latest.Value) / 1000
    newTime := time.Unix(timestamp, 0)
...
```

I'm closing this as nothing to be fixed here. Reopen if you think opposite.

**Comment by olivere** [comment]
Okay. Now that you say this, I remember looking into the ES source for the aggregations, and it was `double` everywhere. I thought this might have changed (ES is moving very fast).

I also remember Go deserializing numeric data as `float64`, by default, unless you tell it not to with [`UseNumber`](http://golang.org/pkg/encoding/json/#Decoder.UseNumber).

Anyway, I will create a new issue for supporting the `format` parameter you referenced.

Thanks for investigating.
