### ISSUE TITLE
Mappings

### ISSUE THREAD

**Issue by BafFlynN** [olivere/elastic#371]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[x ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
when I set a mapping it should stay. 

### Please describe the actual behavior
I am not sure if it is a local elasticsearch setting or this module. 
But I created a mapping with a field type "date" format : "epoch_second" then set time.Time.Unix() to that field. Then after submission elastic search changes it to type long.

**Comment by olivere** [comment]
Can you please post the complete mapping so that I can reproduce? Thanks.

**Comment by olivere** [comment]
Friendly ping.

**Comment by BafFlynN** [comment]
https://gist.github.com/BafFlynN/1acd6b76756cf782507c4518be3becf8
@olivere  sorry about that delay.

**Comment by olivere** [comment]
I don't see a problem anywhere. [Here's a test program](https://gist.github.com/olivere/d49cae8646122d163103e4c12cc2d66a).

There was a missing comma in your mapping in [line 18](https://gist.github.com/BafFlynN/1acd6b76756cf782507c4518be3becf8#file-mapping-L18) though.

Can you check again.

**Comment by BafFlynN** [comment]
I actually found the issue being new to ES I messed up my mapping. I was pushing a mapping with an index name in the mapping to a url with the index name in it. I was ending up with two mappings. Sorry that was my misunderstanding of how the mappings in ES worked.
