### ISSUE TITLE
A more standard way of passing configuration options to NewClient

### ISSUE THREAD

**Issue by khalilovcmd** [olivere/elastic#374]
### Which version of Elastic are you using?

- [x] elastic.v3 (for Elasticsearch 2.x)

### Please describe the expected behavior

First, great library, and well maintained. Thank you for the effort.
This is not exactly an issue, but rather a question and probably an enhancement. 

Why did you use the `func` `SetXXX` pattern to initialise the configuration for creating a new elastic search client?

```go
client, err := elastic.NewClient(
 elastic.SetURL("http://127.0.0.1:9200", "http://127.0.0.1:9201"),
 elastic.SetMaxRetries(10),
 elastic.SetBasicAuth("user", "secret"))
```

Why can't it be something more standard declaring an `options` struct pointer, and passing it to the `NewClient` method?

```go
client, err := elastic.NewClient(
&elastic.Options{
Urls: []string{"http://127.0.0.1:9200"}, 
MaxRetries: 10, })
```

**Comment by olivere** [comment]
It is done so by purpose. I was influenced by [this insights from Dave Cheney](http://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis). Maybe you like that, too.

**Comment by khalilovcmd** [comment]
Thanks @olivere , I will check it out 😺
