### ISSUE TITLE
Add note to README on switching from elastigo

### ISSUE THREAD

**Issue by shawnps** [olivere/elastic#378]
Hi, https://github.com/mattbaird/elastigo was a popular library for connecting to ES from golang but is no longer maintained. It would be really useful if there was something in the README about how to make a transition from that library to this one. I know documentation isn't the most fun thing to do, and I'm happy to help if I can, but I may have some questions/feedback.

**Comment by olivere** [comment]
Oh. I didn't know. Is it officially deprecated?!

Matt has my respect for maintaining elastigo and I have is no problems whatsoever with it. Alternatives are good for everyone. However, unless it is officially deprecated I like to stay neutral and don't want to push anyone to choose Elastic for elastigo.

But you could of course write a blog post on your journey from one library to another. It might be interesting to other people in the same situation. Sharing it e.g. on the Gophers Slack channel would probably help.

Feel free to ask anything. Find my email address in my GitHub profile.
