### ISSUE TITLE
Getting Compiler Error not enough arguments in call to elastic.NewUpdateByQueryService

### ISSUE THREAD

**Issue by dinilv** [olivere/elastic#379]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.
### Which version of Elastic are you using?

[ ] elastic.v3 (for Elasticsearch 2.x)
### Please describe the expected behavior

I am trying to use elastic client for updating multiple indices filtered by query.
### Please describe the actual behavior

"moadTrack" --> its partial doc

moadTrack.ResponseStatus = "Served"

query := elastic.NewTermQuery("RequestID", moadTrack.RequestID)

elastic.NewUpdateByQueryService().Index().Index("tracking").Type("request_log").Query(query).DoC(moadTrack).Do()

while compiling the above code gives an error ; 

"Compiler Error not enough arguments in call to elastic.NewUpdateByQueryService"
### Any steps to reproduce the behavior?

How to use the "NewUpdateByQueryService" ?

**Comment by olivere** [comment]
There are several usage examples in the tests. Does [`update_by_query_test.go`](https://github.com/olivere/elastic/blob/release-branch.v3/update_by_query_test.go) help?

**Comment by olivere** [comment]
The compiler error comes because you didn't pass the client to `NewUpdateByQueryService(client)`. See [here](https://github.com/olivere/elastic/blob/1368b91516f39100baf5e23a02ae9f090c0d90e2/update_by_query.go#L72). Use the tests as a reference on how to work with the `UpdateByQuery` service.
