### ISSUE TITLE
Bound address isn't always []string

### ISSUE THREAD

**Issue by sfroment** [olivere/elastic#380]
Hello,

- [ ] elastic.v2 (for Elasticsearch 1.x)
- [x] elastic.v3 (for Elasticsearch 2.x)
- [ ] elastic.v5 (for Elasticsearch 5.x)

I try to init a new client elastic.NewClient(elastic.SetURL("http://elasticsearch"))
but I was getting this error "No Elasticsearch node available".
I'm using kubernetes and I use this docker image quay.io/pires/docker-elasticsearch-kubernetes:1.7.1-4 .
I've fixed this by replacing at this line https://github.com/olivere/elastic/blob/release-branch.v3/nodes_info.go#L303
[]string by string

The return of  http://elasticsearch/_nodes/http?pretty : 
```json
{
  "cluster_name" : "myesdb",
  "nodes" : {
    "r0rb3JFFQt-oclmaV_hOhQ" : {
      "name" : "Big Bertha",
      "transport_address" : "inet[/172.17.0.4:9300]",
      "host" : "elasticsearch-x4xty",
      "ip" : "172.17.0.4",
      "version" : "1.7.1",
      "build" : "b88f43f",
      "http_address" : "inet[/172.17.0.4:9200]",
      "attributes" : {
        "master" : "true"
      },
      "http" : {
        "bound_address" : "inet[/0:0:0:0:0:0:0:0:9200]",
        "publish_address" : "inet[/172.17.0.4:9200]",
        "max_content_length_in_bytes" : 104857600
      }
    }
  }
}
```
Thanks !

**Comment by olivere** [comment]
You seem to be using Elastic v3 with Elasticsearch 1.x. That's not a valid combination. You need to use Elastic v2 with Elasticsearch 1.x. See the [README](https://github.com/olivere/elastic/blob/release-branch.v3/README.md#releases).

**Comment by sfroment** [comment]
I'm using Elasticsearch v2.4.1 as you can see in the FROM of the dockerfile https://github.com/pires/docker-elasticsearch/blob/master/Dockerfile#L7 .

**Comment by olivere** [comment]
Well, according to the node info output, you are using 1.7.1:

```
{
  "cluster_name" : "myesdb",
  "nodes" : {
    "r0rb3JFFQt-oclmaV_hOhQ" : {
      "name" : "Big Bertha",
      "transport_address" : "inet[/172.17.0.4:9300]",
      "host" : "elasticsearch-x4xty",
      "ip" : "172.17.0.4",
      "version" : "1.7.1",                                      <-- SEE HERE
      "build" : "b88f43f",
      "http_address" : "inet[/172.17.0.4:9200]",
      "attributes" : {
        "master" : "true"
      },
      "http" : {
        "bound_address" : "inet[/0:0:0:0:0:0:0:0:9200]",
        "publish_address" : "inet[/172.17.0.4:9200]",
        "max_content_length_in_bytes" : 104857600
      }
    }
  }
}
```
