### ISSUE TITLE
Add Indices Recovery API

### ISSUE THREAD

**Issue by olivere** [olivere/elastic#384]
[Documentation](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/indices-recovery.html) -- maybe backport to v3.

**Comment by eticzon** [comment]
@olivere I'm happy to pick this up and backport it to v3 if you still think it's worth doing?

**Comment by olivere** [comment]
@eticzon It's low priority, but it would close some gaps. Thanks again.

**Comment by bah2830** [comment]
This addition would be greatly appreciated if you have the time. We can workaround for now making a standard request to elastic but would be nice to have it implemented cleanly.
