### ISSUE TITLE
Bulk ingest failing with BasicAuth

### ISSUE THREAD

**Issue by blacktop** [olivere/elastic#385]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[x] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior

To index the data

### Please describe the actual behavior

No data is indexed

### Any steps to reproduce the behavior?

https://github.com/blacktop/docker-es-demo-data/blob/master/5.0/main.go

```bash
$ docker run -d --name elastic -p 9200:9200 blacktop/elasticsearch:x-pack
$ docker run -d --name kibana --link elastic:elasticsearch -p 5601:5601 blacktop/kibana:x-pack
$ docker run --rm --link elastic:elasticsearch -e ES_USERNAME=elastic -e ES_PASSWORD=changeme blacktop/es-data
```

**Comment by olivere** [comment]
Okay. Thanks for the test, I'll have a look.

Your ELK-based repositories look very good and clean BTW. Good work!

**Comment by olivere** [comment]
I tested your images. My error is:

```
$ docker run --rm --link elastic:elasticsearch -e ES_USERNAME=elastic -e ES_PASSWORD=changeme blacktop/es-data
Unable to find image 'blacktop/es-data:latest' locally
latest: Pulling from blacktop/es-data
07c6396da268: Already exists
1916566e3ae6: Pull complete
8023fc032b62: Pull complete
a742d81b54da: Pull complete
1b6b4cd2ac01: Pull complete
Digest: sha256:bc12cd42e5fea12dbf05e0cf58b6e8a23c4e46f976d4df458cfbc4196aad1308
Status: Downloaded newer image for blacktop/es-data:latest
Using username: elastic and password: changeme
Creating index: nginx_json_elastic_stack_example
time="2016-11-06T13:50:58Z" level=fatal msg="Head http://elasticsearch:9200/nginx_json_elastic_stack_example: dial tcp 192.168.101.15:9200: i/o timeout"
```

So it seems that the index existence check fails (because it's a HEAD request). Is that the same error that you get, or is it different?

**Comment by blacktop** [comment]
Coming from a dev like you that means a lot.  Thank you very much!

**Comment by blacktop** [comment]
So when I run it I get the following:

```bash
~ ❯❯❯ docker run --rm --link elastic:elasticsearch -e ES_USERNAME=elastic -e ES_PASSWORD=changeme blacktop/es-data
Using username: elastic and password: changeme
Creating index: nginx_json_elastic_stack_example
Unzip archive  /nginx_data
Adding template: nginx_json_elastic_stack_example
Adding ingest pipeline: nginx-pipeline
This Bulk Requests is 16 MB.
Import directory  /nginx_data/nginx-dashboard/index-pattern
Import index to /.kibana/index-pattern/nginx_json_elastic_stack_example from /nginx_data/nginx-dashboard/index-pattern/nginx_json_elastic_stack_example.json
Import directory  /nginx_data/nginx-dashboard/dashboard
Import dashboard  /nginx_data/nginx-dashboard/dashboard/Sample-Dashboard-for-Nginx-(JSON)-Logs.json
Import vizualization  /nginx_data/nginx-dashboard/visualization/Nginx-Dashboard-json.json
Import vizualization  /nginx_data/nginx-dashboard/visualization/Traffic-vs.-Location-json.json
Import vizualization  /nginx_data/nginx-dashboard/visualization/Unique-Visits-json.json
Import vizualization  /nginx_data/nginx-dashboard/visualization/Total-Requests-by-City-json.json
Import vizualization  /nginx_data/nginx-dashboard/visualization/Traffic-by-Country-ampersand-OS.json
Import vizualization  /nginx_data/nginx-dashboard/visualization/Total-Requests-json.json
Import vizualization  /nginx_data/nginx-dashboard/visualization/Bytes-vs.-Time-json.json
Import vizualization  /nginx_data/nginx-dashboard/visualization/Non-200-Response-Code-vs.-Time-json.json
```
However, it seems that nothing was indexed into the newly created `nginx_json_elastic_stack_example` index as can be seen here:
```bash
~ ❯❯❯ http -a elastic:changeme :9200/nginx_json_elastic_stack_example
HTTP/1.1 200 OK
content-encoding: gzip
content-type: application/json; charset=UTF-8
transfer-encoding: chunked

{
    "nginx_json_elastic_stack_example": {
        "aliases": {},
        "mappings": {},
        "settings": {
            "index": {
                "creation_date": "1478470490972",
                "number_of_replicas": "1",
                "number_of_shards": "5",
                "provided_name": "nginx_json_elastic_stack_example",
                "uuid": "0v66zHRGTpS3aryseCPbSQ",
                "version": {
                    "created": "5000099"
                }
            }
        }
    }
}
```

**Comment by blacktop** [comment]
Now to contrast that with an attempt without BasicAuth
```bash
$ docker run -d --name elastic -p 9200:9200 blacktop/elasticsearch:geoip
$ docker run -d --name kibana --link elastic:elasticsearch -p 5601:5601 blacktop/kibana
$ docker run --rm --link elastic:elasticsearch blacktop/es-data
~ ❯❯❯ http :9200/nginx_json_elastic_stack_example/_count
HTTP/1.1 200 OK
content-encoding: gzip
content-type: application/json; charset=UTF-8
transfer-encoding: chunked

{
    "_shards": {
        "failed": 0,
        "successful": 5,
        "total": 5
    },
    "count": 51462
}
```

**Comment by blacktop** [comment]
@olivere I know that the new Elasticsearch is very strict with it's bootstrap checks and you might not have the memory map areas high enough?  What does the elasticsearch logs say?

`docker logs elastic`

**Comment by olivere** [comment]
Yes. ES 5 is very strict with the bootstrap checks (and rightfully so), but I've used your Docker images. So that should do it, no?

What's interesting is that data isn't imported with auth enabled, yet I don't see any errors. Whenever I see this behavior, I head over to inspect the ES log files? Is there anything interesting in it?

In the end, all services should execute `PerformRequest`,  and that adds the `Authorization` header [here](https://github.com/olivere/elastic/blob/release-branch.v5/client.go#L919-L921). So I'm not yet convinced that we're looking for the real problem.

Anyway, I'll find some time tomorrow and try to figure out what's going on. I have data, images, and a test program. I should be able to figure it out...

**Comment by blacktop** [comment]
Haha it was a dumb mistake on my part, I apologize for wasting your time with this. 

So I added basicAuth checks to all my calls to **your** library **EXCEPT** the hand rolled putPipeline function I wrote that was just using a `"net/http"` Request.

I added in your new `client.IngestPutPipeline` and it worked because it had the basicAuth. 😞 

Please keep up the great work on this project!!

I am still a little curious why you were seeing the `"Head http://elasticsearch:9200/nginx_json_elastic_stack_example: dial tcp 192.168.101.15:9200: i/o timeout"` though?

**Comment by olivere** [comment]
Good to hear!

Re the Docker issues: Docker is sometimes part of the problem, isn't it? ;-) For Elastic tests, I run ES with [`./run-es-5.0.0.sh`](https://github.com/olivere/elastic/blob/release-branch.v5/run-es-5.0.0.sh)--and it works fine. However, it took me roughly 20 steps of trial & error to get Travis CI to run my tests--and it required e.g. the [sysctl settings](https://github.com/olivere/elastic/blob/release-branch.v5/.travis.yml).

Containers are a great idea. And Docker was a giant step forward. But I think it's still not quite there yet. Sometimes I think a mixture of FreeBSD Jails and Docker would've been a better approach. It'd be much more approachable if a container e.g. could be just another directory I could cd into. Anyway... I personally still prefer local development, but use Docker images for deployment.

BTW: Is this issue done for you? Can we close it?

**Comment by blacktop** [comment]
yes, thank you @olivere
