### ISSUE TITLE
is it the right way use NewRangeQuery ?

### ISSUE THREAD

**Issue by jacobluo** [olivere/elastic#386]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v3 (for Elasticsearch 2.x)

	query := elastic.NewBoolQuery()
	if keys != nil {
		for _, key := range keys {
			if key != ""{
				query = query.Must(elastic.NewMatchQuery("message", key))
			}
		}
	}
	query = query.Must(elastic.NewRangeQuery("@timestamp").Gte(start_time.Unix()).Lte(end_time.Unix()))
	search := client.Search(index).Index(index)
	search = search.Query(query)
	searchResult, err := search.Do()
	

### Please describe the actual behavior

no results

**Comment by jacobluo** [comment]
done

**Comment by kgrvamsi** [comment]
@jacobluo was trying to understand the query here if the result for start_date and end_date really worked in 3.x or did it fixed this query for 5.x and how are you handling the index return rows if the data is beyond 10000? increase the index result value to a higher number?
