### ISSUE TITLE
v5 connect panic: no Elasticsearch node available

### ISSUE THREAD

**Issue by zplzpl** [olivere/elastic#387]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?
[ ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
panic: no Elasticsearch node available

### Please describe the actual behavior
```

	// Create a client
	client, err := elastic.NewClient(elastic.SetURL("http://192.168.33.10:9200"))
	if err != nil {
		panic(err)
	}

```

```
curl -s -XGET 'http://192.168.33.10:9200/_nodes/http?pretty=1'
{
  "_nodes" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "cluster_name" : "es-search",
  "nodes" : {
    "qoa_gnFlTtSPjUiQWH_I9g" : {
      "name" : "node-1",
      "transport_address" : "10.0.2.15:9300",
      "host" : "10.0.2.15",
      "ip" : "10.0.2.15",
      "version" : "5.0.0",
      "build_hash" : "253032b",
      "roles" : [
        "master",
        "data",
        "ingest"
      ],
      "http" : {
        "bound_address" : [
          "[::]:9200"
        ],
        "publish_address" : "10.0.2.15:9200",
        "max_content_length_in_bytes" : 104857600
      }
    }
  }
}
```

### Any steps to reproduce the behavior?
Run the code above

**Comment by olivere** [comment]
One word: [Sniffing](https://github.com/olivere/elastic/wiki/Sniffing). The client will try to find other nodes in the cluster by default (as all official Elasticsearch clients do). It will do so by finding the `publish_address` in the response you sent. Can you ping `10.0.2.15:9200` from your node?

Either disable sniffing (`elastic.SetSniff(false)`) or make sure all ES nodes return an address that is accessible by your application.

**Comment by kuma-guy** [comment]
I followed [Connection-Problems](https://github.com/olivere/elastic/wiki/Connection-Problems) on Wiki, but still get "no Elasticsearch node available"

### Which version of Elastic are you using?

- [x]  elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior

panic: no Elasticsearch node available

### Please describe the actual behavior

```
// Create a client
i.ElasticClient, err = elastic.NewClient(elastic.SetSniff(false), elastic.SetURL("http://127.0.0.1:9200"))
if err != nil {
    // Handle error
    panic(err)
}
```

```
curl -s -XGET 'http://127.0.0.1:9200/_nodes/http?pretty=1'
{
  "_nodes" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "cluster_name" : "elasticsearch_kumaguy",
  "nodes" : {
    "FBkUSwVqSNG0lIFnBcVAww" : {
      "name" : "FBkUSwV",
      "transport_address" : "127.0.0.1:9300",
      "host" : "127.0.0.1",
      "ip" : "127.0.0.1",
      "version" : "5.2.2",
      "build_hash" : "f9d9b74",
      "roles" : [
        "master",
        "data",
        "ingest"
      ],
      "http" : {
        "bound_address" : [
          "[fe80::1]:9200",
          "[::1]:9200",
          "127.0.0.1:9200"
        ],
        "publish_address" : "127.0.0.1:9200",
        "max_content_length_in_bytes" : 104857600
      }
    }
  }
}
```

```
{
  "name" : "FBkUSwV",
  "cluster_name" : "elasticsearch_kumaguy",
  "cluster_uuid" : "1tc7ObqOTIKg0LbYauf2pw",
  "version" : {
    "number" : "5.2.2",
    "build_hash" : "f9d9b74",
    "build_date" : "2017-02-24T17:26:45.835Z",
    "build_snapshot" : false,
    "lucene_version" : "6.4.1"
  },
  "tagline" : "You Know, for Search"
}
```

### Any steps to reproduce the behavior?

Run the code above

**Comment by olivere** [comment]
Works fine here.

I set up an example here a few months ago: https://gist.github.com/olivere/d49cae8646122d163103e4c12cc2d66a. That works fine here.

You need to make sure that the server (the part which runs the Elastic code) can connect to 127.0.0.1:9200. That's all that's required.

**Comment by olivere** [comment]
I also added a [simple connect example](https://github.com/olivere/elastic/blob/release-branch.v5/recipes/connect/connect.go).

```
$ ./connect -h
Usage of ./connect:
  -sniff
    	Enable or disable sniffing (default true)
  -url string
    	Elasticsearch URL (default "http://localhost:9200")

$ ./connect -sniff=true
Connection succeeded

$ ./connect -sniff=false
Connection succeeded
```

**Comment by kuma-guy** [comment]
Thanks for quick response.

I tested your example and simple connect.
Both totally works fine here too...

Do I need something if it works on top of Google App Engine?

**Comment by olivere** [comment]
@kuma-guy There's [a wiki page for that](https://github.com/olivere/elastic/wiki/App%20Engine).

**Comment by kuma-guy** [comment]
@olivere  it works!  sorry for taking your time and thanks for your help!

**Comment by 478682649** [comment]
elastic.SetSniff(false)

**Comment by olivere** [comment]
@478682649 Thinking of making this the official slogan of the library: "elastic.SetSniff(false) is a Go library for Elasticsearch" ;-)

**Comment by ZChristine** [comment]
I try to use the following command to have a quick start of carley
cayley.exe http -a ./data/disease_crawled_6212.nq -d elastic http://10.190.188.45:9200
but it return a error of "health check timeout: no Elasticsearch node available" @olivere

**Comment by olivere** [comment]
@ZChristine You can disable health checks alongside with sniffing. Something like this:

```
client, err := elastic.NewClient(...,
   elastic.SetSniff(false),
   elastic.SetHealthcheck(false),
   ...
)
```

If you want to know how to configure Elasticsearch in a way that you don't need to do this, see https://github.com/olivere/elastic-with-docker.

**Comment by olivere** [comment]
@ZChristine Maybe this is an issue for Cayley, as they [don't seem to support passing parameters into Elastic](https://github.com/cayleygraph/cayley/blob/009b1f61d2adabed4b6fed0506fdb0fe485658fa/graph/nosql/elastic/elastic.go#L35).

I wonder if they could use the [`github.com/olivere/elastic/config`](https://github.com/olivere/elastic/tree/release-branch.v6/config) package to make Elastic automatically pick up connection parameters from the URL. It's up to the authors of Cayley though.

**Comment by olivere** [comment]
Elasticsearch Bulk API is pretty fast. It depends on various factors though, e.g. the size of the documents or the I/O of the cluster. You should really talk to the authors of Cayley for those things.

BTW I opened https://github.com/cayleygraph/cayley/issues/730 to address the original issue you mentioned.

**Comment by ZChristine** [comment]
thanks so much

**Comment by li-keli** [comment]
I have the same problem, I added `elastic.SetSniff(false)` solved this problem
thanks so much
