### ISSUE TITLE
use of multiple values in "NewTermsQuery"

### ISSUE THREAD

**Issue by wouafff** [olivere/elastic#392]
Elasticsearch 1.7

Hi,
in fact I need to make a NewTermsQuery on a specific field.
But the thing is I don't know in advance how many values I need to inject into the query.
So for that I try to give it an array:
bq = bq.Must(elastic.NewTermsQuery("address.PollingStation",temp_array))

but when I inject an array as a value -> [value1 value2] , it will append it in an array as well so Elastic can't execute the request -> [[value1 value2]]

The behavior is quite normal with the code I wrote, but do you have an idea how to do that without modifying the behavior of NewTermsQuery()?

Thanks you!!!

**Comment by olivere** [comment]
An array is okay. Maybe you are looking for the [`...` operator](https://golang.org/ref/spec#Passing_arguments_to_..._parameters):

```go
terms := []string{"term-1", "term-2"}
q := elastic.NewTermsQuery("address.PollingStation", terms...)
```

Please close if this solves your issue.

**Comment by wouafff** [comment]
I had to adapt my array to be accepted by the method:
`
var interfaceSlice []interface{} = make([]interface{}, len(dataSlice))
for i, d := range dataSlice {
     interfaceSlice[i] = d
}
bq = bq.Must(elastic.NewTermsQuery("address.PollingStation", interfaceSlice...))`

but it works!!!
thanks a lot Oliver!
