### ISSUE TITLE
Setting pipeline for BulkProcessor

### ISSUE THREAD

**Issue by mahmoudhossam** [olivere/elastic#393]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[*] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
`BulkProcessor` should have a `pipeline` attribute or method that lets you specify a pipeline to use with the bulk request.

### Please describe the actual behavior
Currently, pipeline is only defined in the `BulkService` and it's marked as private in the `BulkProcessor`

**Comment by olivere** [comment]
I will look into it. Thanks for reporting.

**Comment by olivere** [comment]
Looks like we need a `pipeline` in [`bulk_index_request.go`](https://github.com/olivere/elastic/blob/release-branch.v5/bulk_index_request.go). However, I don't see any reference to a pipeline in the Java code of a BulkUpdateRequest. Does that make sense?

**Comment by olivere** [comment]
You can use 5.0.6 which has Pipeline, RetryOnConflict and TTL added to the BulkIndexRequest.

**Comment by mahmoudhossam** [comment]
@olivere thank you for working on this, but I was referring to [BulkProcessor](https://github.com/olivere/elastic/blob/release-branch.v5/bulk_processor.go#L221), not `BulkIndexRequest`

**Comment by olivere** [comment]
@mahmoudhossam Yes, but the BulkProcessor works by [adding BulkableRequests to it](https://github.com/olivere/elastic/blob/release-branch.v5/bulk_processor.go#L358). And `BulkIndexRequest` is a "bulkable request".

**Comment by mahmoudhossam** [comment]
@olivere Got it, thank you very much!
