### ISSUE TITLE
how to get errored records from bulk index

### ISSUE THREAD

**Issue by kmulvey** [olivere/elastic#394]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[x ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
This is just a question not a bug. When doing a bulk index how do you know which records failed? I.e. is it possible to get the records out of bulkResponse.Failed() ? Also, ifs there a way to force failure for testing?

**Comment by olivere** [comment]
Elasticsearch returns errors that failed in [an array](https://github.com/olivere/elastic/blob/release-branch.v5/bulk_test.go#L365). The `BulkResponse.Errors` flag indicates whether any errors happened at all. The `BulkResponse.Failed()` will return all items that had an error. You can use the `Id` property to get a back-reference to the original document, retry or do whatever is appropriate for your application.

You should probably not test Elasticsearch and its bulk operation capabilities but the service that uses it. You could e.g. do that by defining an interface and provide two implementations: One for a live environment and one (mocked) implementation that provides callbacks for your testing code.
