### ISSUE TITLE
Pipeline function not found on type NewBulkIndexRequest

### ISSUE THREAD

**Issue by cdstelly** [olivere/elastic#396]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[x] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
Upon setting '[Pipeline](https://godoc.org/gopkg.in/olivere/elastic.v5#BulkIndexRequest.Pipeline)' on an instance of [BulkIndexRequest](https://godoc.org/gopkg.in/olivere/elastic.v5#BulkIndexRequest), the request will go through the ingest pipeline.

### Please describe the actual behavior
Upon setting '[Pipeline](https://godoc.org/gopkg.in/olivere/elastic.v5#BulkIndexRequest.Pipeline)' on an instance of [BulkIndexRequest](https://godoc.org/gopkg.in/olivere/elastic.v5#BulkIndexRequest) (via NewBulkIndexRequest()), the program fails to compile with the error: 
`src/consumer/consumer.go:243: elastic.NewBulkIndexRequest().Pipeline undefined (type *elastic.BulkIndexRequest has no field or method Pipeline)
`
Creating a BulkIndexRequest without calling NewBulkIndexRequest results in the same behavior. 

### Any steps to reproduce the behavior?
Yep, this code compiles:
```
resultIndex := elastic.NewBulkIndexRequest().
		Index("scarf").
		Type("file").
		Id(strconv.Itoa(int(fi.Id))).
		Doc(fi)
```

This code doesn't
```
resultIndex := elastic.NewBulkIndexRequest().
		Index("scarf").
		Type("file").
		Id(strconv.Itoa(int(fi.Id))).
		Pipeline("attachment").
		Doc(fi)
// or
resultIndex := elastic.NewBulkIndexRequest().
		Index("scarf").
		Type("file").
		Id(strconv.Itoa(int(fi.Id))).
		Doc(fi)
resultIndex.Pipeline("attachment")
```

**Comment by cdstelly** [comment]
[thanks for your time, my apologies if i'm missing something obvious...]

**Comment by olivere** [comment]
I just [added these yesterday](https://github.com/olivere/elastic/commit/6818747c91f036a8ec4115a0d66d67713e084510). Can you update to 5.0.6 and try again?

Please close if it works.

**Comment by cdstelly** [comment]
Talk about timing.. working now! Thanks, was using last week's build.
