### ISSUE TITLE
PerformRequest should return a response if one is available

### ISSUE THREAD

**Issue by baliame** [olivere/elastic#397]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
We are operating an API endpoint that is effectively a proxy to Elasticsearch. For this endpoint only, we want to return responses as if they were coming from Elasticsearch. The library, however, doesn't pass back the response if a non-2xx (and non-404) response is received. I don't see why PerformRequest shouldn't return both a response and an error in this case.

### Please describe the actual behavior
PerformRequest returns either a response *or* an error, not both.

### Any steps to reproduce the behavior?
Call PerformRequest with a search request which results in a 400 from Elasticsearch. Only an error is returned, even though a response is available.

**Comment by olivere** [comment]
That would be feasible. But it's up to you, the caller, to check for a valid response: It might be nil. I add that to the documentation of PerformRequest.

**Comment by olivere** [comment]
... to work around that with the current code, you could pass a list of errors to ignore to `PerformRequest`. In that case, it'll still return a response (and no error).

**Comment by olivere** [comment]
Try [2.0.55](https://github.com/olivere/elastic/commit/45693ebb296a40a56e30a6d9173bfd96ca6bb48f). I will port this change to `PerformRequest` to v3 and v5 as well.

**Comment by baliame** [comment]
Thanks!

**Comment by baliame** [comment]
Yep - the function returns a response and an error correctly as expected. Thanks again!
