### ISSUE TITLE
Has Child/Has Parent Query: Score incompatible api change

### ISSUE THREAD

**Issue by JadenTeng** [olivere/elastic#399]
### Which version of Elastic are you using?

elastic.v5 (for Elasticsearch 5.x)

Hi @olivere 
thanks for your great library. that help me a lot with my work with golang.

This is a bug I miss.

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-has-child-query.html#_scoring_capabilities
https://github.com/olivere/elastic/blob/release-branch.v5/search_queries_has_child.go#L16

The has child only support `score_mode` not `score_type`.

I think it has problem with `has parent query`(I don't have a try).

#### 2.4:

https://www.elastic.co/guide/en/elasticsearch/reference/2.4/query-dsl-has-parent-query.html#_scoring_capabilities_2

#### current

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-has-parent-query.html#_scoring_capabilities_2

**Comment by olivere** [comment]
Thanks. I'll have a look at it in the next update.

**Comment by olivere** [comment]
Just a short notice to self:

You can use use `score` (bool) as well as `score_mode` in 5.0 (see [`HasParentQueryBuilder`](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/index/query/HasParentQueryBuilder.java#L252-L263)).

[`HasChildQueryBuilder` only has `score_mode`](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/index/query/HasChildQueryBuilder.java).

I'll fix that ASAP.
