### ISSUE TITLE
Enabling no-op with bulk updates

### ISSUE THREAD

**Issue by gm42** [olivere/elastic#401]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[x] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
I am using `BulkIndexRequest` and would like to explicitly set `DetectNoop` to `true`.

### Please describe the actual behavior

There does not seem to be such method available.

Similarly to https://github.com/elastic/elasticsearch/issues/10881, I assume the feature is available in Elasticsearch 2.x but there is no client option to enable it?

**Comment by olivere** [comment]
Yep. That's missing. I'll add it in the next release. Thanks for reporting.

**Comment by gm42** [comment]
@olivere many thanks. As far as I understood by default it's not enabled, hence I was looking around for it.

**Comment by gm42** [comment]
I made a (temptative) PR, however I notice that Elasticsearch maybe supports this only with **update** requests, I am not sure about **index** requests as per my initial post.

**Comment by gm42** [comment]
So, I dug a bit into this. The `detect_noop` is enabled by default for **update** bulk requests (making PR #403 somewhat of a whistle&bell). For **index** bulk requests, as I was asking originally, it's a different situation, see https://github.com/elastic/elasticsearch/issues/12969

Basically from the documentation update they did there (https://github.com/nik9000/elasticsearch/blob/master/docs/reference/docs/index_.asciidoc#noop-updates), it's clear that index API has no option for this :cry:

**Comment by olivere** [comment]
DetectNoop is available in 3.0.59 and 5.0.12.
