### ISSUE TITLE
No create support for bulk requests?

### ISSUE THREAD

**Issue by gm42** [olivere/elastic#402]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[x] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
According to https://www.elastic.co/guide/en/elasticsearch/reference/2.4/docs-bulk.html it is possible to send bulk `create` requests. I assume such requests would correspond to a `PUT` (because in the code for bulk service I have seen only `POST` so far).

### Please describe the actual behavior
Possibility to specify bulk `PUT` requests that replace documents instead of merging.

This is important for example for array fields, because a simple `POST` would add elements to the array and not replace them.

**Comment by olivere** [comment]
I support you're looking for [`OpType("create")`](https://github.com/olivere/elastic/blob/release-branch.v5/bulk_index_request_test.go#L27-L34)?! If that's not what you're looking for, ping again and I'll re-open.

**Comment by gm42** [comment]
Oh! Sorry, totally missed that. Thanks again!

**Comment by gm42** [comment]
@olivere what I would like is:
* index `n` documents in bulk
* if some document exists, replace it (**not** merge as normally an index request would do)
* if it does not exist, create it

Unfortunately `op_type=create` doesn't do this; do you know if it's possible to achieve this currently? By reading the Elasticsearch documentation it seems it's possible for individual PUTs hence I was assuming the same for bulk indexing.

**Comment by olivere** [comment]
Hmm... I'm on the road, so out of my mind: Isn't that possible with Update and doc_as_upsert=true?

**Comment by gm42** [comment]
@olivere yeah I have just tested that approach (update with doc_as_upsert), unfortunately in this mode of operation if a document already exists its array fields get "merged" and not replaced. So imagine before the call:
```
{
  "field1": [0,1,2,3]
}
```

After the call with `[0,1,2]` it would become:
```
{
  "field1": [0,1,2,3,0,1,2]
}
```

When I'd rather have the field replaced (which happens with an individual `PUT`. I guess the only alternative would be to use in the update request a script to remove the field before setting it, but this is very bad for my use case because I would completely loose the noop detection.
