### ISSUE TITLE
Custom JSON tag for Elasticsearch

### ISSUE THREAD

**Issue by sundarv85** [olivere/elastic#404]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v3 (for Elasticsearch 2.x)

### Please describe the expected behavior

Our data, while coming over network, we prefer to have short json names to save bandwidth. However, when we want to write into ElasticSearch, we would like to give a more readable name. Currently we have two structures and are copying one to another and the only difference between these two are the json tag.

It would be good, if we can have a custom tag possibility, such as "ejson", which will be used if present. 

Your thoughts?

**Comment by olivere** [comment]
I'm not familiar with ejson. I also try to stick to stdlib as much as possible. Did you try to enable gzip?

**Comment by olivere** [comment]
BTW: There's some nice libraries to help copying similar structs, e.g. [jinzhu/copier](https://github.com/jinzhu/copier) and [mitchellh/copystructure](https://github.com/mitchellh/copystructure).

**Comment by sundarv85** [comment]
Thanks. let me check the libraries. BTW, the `ejson` was an example that I suggested for a custom tag possibility. For e.g. when we get the json from network, we have it as

```
type Data struct {
   ResTime int `json:"rt"`
   ResSize int `json:"rz"`
}
```

But, when we want to write into elasticsearch, we prefer

```
type Data2 struct { // Instead of Data, I use Data2
   ResTime int `json:"resTime"`
   ResSize int `json:"resSize"`
}

```
Note the different in both the json tags. Hence, I end up, naming the second one as `Data2`. Instead, it would be good if we can do something like

```
type Data struct {
   ResTime int `json:"rt" ejson:"resTime"`
   ResSize int `json:"rz" ejson:"resSize"`
}
```

Then I do not need to copy anything and just use `Data` as it is

**Comment by olivere** [comment]
I see what you're looking for. But I'm afraid that's out of scope for the core Elastic library. I would tackle that either by using the reflect package and generate the structs on the fly, or using go generate to generate the structures at compile time.

**Comment by olivere** [comment]
@sundarv85 This language change in Go 1.8 might or might not be interesting to you: https://beta.golang.org/doc/go1.8#language

**Comment by sundarv85** [comment]
@olivere Wow.. really awesome.. This is exactly what I wanted.. This is a valid problem in real world :)

Thanks for sharing it.
