### ISSUE TITLE
Can't connect to Elastic

### ISSUE THREAD

**Issue by zet4** [olivere/elastic#405]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ x ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
Client connects and works as intended

### Please describe the actual behavior
Client errors and returns `no Elasticsearch node available`

### Any steps to reproduce the behavior?
1) Run sebp/elk:latest docker container
2) Have a config with elastic pool list ( in my case it's ["http://192.168.99.100:9200"] in json file )
3) Try to connect with code below
```go
	log.Println(config.ElasticPool)
	elasticClient, err = elastic.NewClient(elastic.SetURL(config.ElasticPool[0]))
	if err != nil {
		log.Fatalln("Error creating elastic client: ", err.Error())
	}
```

I've tried numerous times to curl root of that address (http://192.168.99.100:9200) and I always get
```
$ curl http://192.168.99.100:9200
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   327  100   327    0     0  20437      0 --:--:-- --:--:-- --:--:-- 20437
{
  "name" : "HkRAP0f",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "qD5LuTUaQqG-GS9qTvdTOg",
  "version" : {
    "number" : "5.0.1",
    "build_hash" : "080bb47",
    "build_date" : "2016-11-11T22:08:49.812Z",
    "build_snapshot" : false,
    "lucene_version" : "6.2.1"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by CodeJuan** [comment]
Me too...
`elastic.v5`

**Comment by olivere** [comment]
The [wiki](https://github.com/olivere/elastic/wiki) has a whole page [dedicated to solving connection problems](https://github.com/olivere/elastic/wiki/Connection-Problems). If you still can't solve it, feel free to come back and I'll reopen the issue.
