### ISSUE TITLE
Two type in mapping provided but one is update in elastic

### ISSUE THREAD

**Issue by kamorahul** [olivere/elastic#406]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[X] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
add mapping for two types together

### Please describe the actual behavior
Only conversation mapping added

### Any steps to reproduce the behavior?
       mappingConversation := {
		     "conversation":{
			    "properties":{
			       	"conversation_id":{
				      	"type":"string"
			      	},
			       	"subject":{
			     	"type" : "string"
		     		}
		     	}
	    	},
	     	"message":{
		      	"_parent" :{
		     	"type" : "conversation"
		     	},
		     	"properties":{
			  	"message_text":{
				   	"type":"string"
			     	},
				    "message_id":{
				    	"type":"string"
			     	},
			      	"conversation_id":{
				      	"type":"string"
				     }
			    }
		     }
	    }

Only conversation is added to mapping 

     putresp1, err :=      client.PutMapping().Index("search").BodyString(mappingConversation).Do(context.TODO())
	    if putresp1 != nil {

		fmt.Println(putresp1.Acknowledged)
	}

**Comment by olivere** [comment]
I'm pretty confident this has nothing to do with Elastic but with your mapping. Did you check the Elasticsearch log for errors? Can you provide a complete example? The `mappingConversation := { ... }` isn't even valid Go code, so I don't know what you're really sending to ES.

**Comment by olivere** [comment]
Please take a look at the [Put Mapping API](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html). It always requires at least a root element called `"mapping"`.
