### ISSUE TITLE
how to connect with a elasticsearch cluster which use nginx to do the reverse proxy

### ISSUE THREAD

**Issue by lixl1019** [olivere/elastic#409]
elastic.v3 (for Elasticsearch 2.3/2.4)

In order to  load balance, I use nginx to do the reverse proxy. It provides an agent address.Through the curl command I can random access to the nodes in the cluster with the agent address,but how to connect  the cluster thorough the agent address  use  elastic.v3 client for load balance?
waiting for your reply
thank you

**Comment by olivere** [comment]
I'd use something like this:

```go
client, err := elastic.NewClient(elastic.SetURL("<endpoint-of-nginx-lb>"), elastic.SetSniff(false))
if err != nil {
    // Handle error
}
```

Let me know if this doesn't work.

**Comment by lixl1019** [comment]
it works, thank you
