### ISSUE TITLE
How to pass in raw JSON when making a search

### ISSUE THREAD

**Issue by magicalbanana** [olivere/elastic#410]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

- [ ] elastic.v2 (for Elasticsearch 1.x)
- [ ] elastic.v3 (for Elasticsearch 2.x)
- [x] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior

Pass in raw JSON when searching

### Please describe the actual behavior

Pass in raw JSON when searching

### Any steps to reproduce the behavior?

How do I pass in just a raw JSON when making a search?

**Comment by olivere** [comment]
If you don't want to use the DSL, you have these options:

1. Use [`client.PerformRequest(...)`](https://github.com/olivere/elastic/blob/release-branch.v5/client.go#L1053) directly,
2. Use a [`RawStringQuery`](https://github.com/olivere/elastic/blob/release-branch.v5/search_queries_raw_string.go) if you only want to provide raw data for the query part, or
3. don't use Elastic at all and use `net/http`, plain and simple.
