### ISSUE TITLE
Scroll command 

### ISSUE THREAD

**Issue by dhbarman** [olivere/elastic#413]
The following query returns an error for ElasticSearch 5.x:

searchResult, err = client.Scroll(group).Type(itype).Query(q).Sort("field1", true). Size(size).
                        ScrollId(scrollId).
                        Do(context.TODO())

             
Error 400 (Bad Request): all shards failed [type=search_phase_execution_exception]

But the same query works for ElasticSearch 2.x:

searchResult, err = client.Scroll(group).Type(itype).Query(q).Sort("field1", true). Size(size).
                        ScrollId(scrollId).
                        Do()

The above query returns correct results in sorted order. 

Has anything changed in 5.x as far as the go client is concerned ?

**Comment by olivere** [comment]
Yes, the Scroll service has been rewritten. Your request looks good though, but I can only test a complete, reproducible example. Also, the ES log file will contain further details. Maybe it's simple to fix.

The [`scroll_test.go`](https://github.com/olivere/elastic/blob/release-branch.v5/scroll_test.go) file illustrates how to do scrolling. And you can now even [scroll in parallel](https://github.com/olivere/elastic/blob/release-branch.v5/recipes/sliced_scroll.go).

**Comment by dhbarman** [comment]
Is it necessary to enable fielddata on the field using mapping ?

**Comment by olivere** [comment]
If you e.g. want to sort on that field: Yes. Read the docs: https://www.elastic.co/guide/en/elasticsearch/reference/current/fielddata.html

**Comment by olivere** [comment]
I'll close this for now. If question is not answered yet, feel free to respond and I'll reopen again.
