### ISSUE TITLE
Bulk Indexing could use an example

### ISSUE THREAD

**Issue by Redundancy** [olivere/elastic#414]
Doing faster inserts using client.Bulk() on v5 could use better documentation, partially because it's difficult to see how to compose the calls in such a way that you end up with the required objects and interfaces.

**Comment by olivere** [comment]
Sure. If I have some time, I will put up an example. I recently created a `recipes` directory that's a good place for such things. Feel free to contribute.

**Comment by Redundancy** [comment]
I would contribute it, but I haven't gotten it working yet.

I'm assuming that you start with client.Bulk() and then Add() elastic.NewBulkIndexRequest() then call Do() every few iterations, but I don't understand how the BulkIndexRequest relates to the BodyJson() call that I was making from one of the examples on individual index calls.

**Comment by olivere** [comment]
I hacked together a [simple recipe for bulk insert](https://github.com/olivere/elastic/blob/release-branch.v5/recipes/bulk_insert.go). Maybe that helps.

**Comment by Redundancy** [comment]
Thanks! Very helpful
