### ISSUE TITLE
how to get search result full raw json?

### ISSUE THREAD

**Issue by zplzpl** [olivere/elastic#417]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior

searchResult,err:= client().search().....Do(...)

searchResult.RawJson()  // get full result raw json

### Please describe the actual behavior

Did not find this method

### Any steps to reproduce the behavior?

`
	// Search with a term query
	termQuery := elastic.NewTermQuery("user", "olivere")
	searchResult, err := client.Search().
		Index("twitter").        // search in index "twitter"
		Query(termQuery).        // specify the query
		Sort("user", true).      // sort by "user" field, ascending
		From(0).Size(10).        // take documents 0-9
		Pretty(true).            // pretty print request and response JSON
		Do(context.Background()) // execute
	if err != nil {
		// Handle error
		panic(err)
	}
`

**Comment by olivere** [comment]
Why'd you want to do that? The whole idea of Elastic is to provide a DSL to not make it necessary to work with the raw response.

A workaround is to use `client.PerformRequest(...)` directly.

**Comment by zplzpl** [comment]
I provide a search of the RPC service. I want to return directly to the raw json.

**Comment by olivere** [comment]
Then did you look at [`PerformRequest(...)`](https://github.com/olivere/elastic/blob/release-branch.v5/client.go#L1053)? It's as low level as it gets. It returns a HTTP response-like structure, including the body (which you can read). [Here's an example.](https://github.com/olivere/elastic/blob/release-branch.v5/client_test.go#L685-L705)

**Comment by songlong** [comment]
If I can print raw request data,  It will help to solve the wrong problem.
when I get the raw request body,  at least, I can found which keyword error?

**Comment by olivere** [comment]
@songlong What is your question then? In what way is [`PerformRequest`](https://github.com/olivere/elastic/blob/release-branch.v5/client.go#L1133) insufficient?

**Comment by songlong** [comment]
function performRequest is good. 
I want to know request body in some condition especially I need to debug my code.
But I found not find request body when I use Mutlitsearch objects.

**Comment by olivere** [comment]
@songlong Can you explain or post an example of what you mean by "Multisearch objects" and how they cannot be executed by `PerformRequest`?

**Comment by songlong** [comment]
for example:
	sreq := elastic.NewSearchSource().Query(q).Sort("ts", s.Sortable).Size(0).FetchSourceContext(fsc)
	sreq = sreq.Aggregation("top", topTagsAgg)
	srequest := elastic.NewSearchRequest().Index(indices...).Type(typ).Source(sreq)

in here,
       as i know, it canprint search source,
       but can print srequest content when include aggregation?

**Comment by olivere** [comment]
Aha, I see. Would it help to export [`body()`](https://github.com/olivere/elastic/blob/release-branch.v5/search_request.go#L200-L202)?

**Comment by songlong** [comment]
yeah
how to export?

**Comment by olivere** [comment]
I would need to export it. Will do so in the next version of elastic.v5 (and backport to v6). Watch #548.

**Comment by songlong** [comment]
expectation， haha

**Comment by sumit-nference** [comment]
Hi all,
I have a search request something like this:
```searchResult, err := client.Search().
    Index("twitter").   // search in index "twitter"
    Query(termQuery).   // specify the query
    Sort("user", true). // sort by "user" field, ascending
    From(0).Size(10).   // take documents 0-9
    Pretty(true).       // pretty print request and response JSON
    Do(ctx)```
Can you please help me find out, how in this case can I print raw json?

**Comment by olivere** [comment]
@sumit-nference You cannot natively. What's you use case?

**Comment by sumit-nference** [comment]
@olivere , my Usecase is in my elastic search i have data, and based on queries match -> with date=" "& name = " " & place = " " I want to fetch each and every entire json key value pair for each hit.

I was able to form a query and perform search, as mentioned above:
```
searchResult, err := client.Search().
    Index("twitter").   // search in index "twitter"
    Query(termQuery).   // specify the query
    Sort("user", true). // sort by "user" field, ascending
    From(0).Size(10).   // take documents 0-9
    Pretty(true).       // pretty print request and response JSON
    Do(ctx)
```
But now I want the search result.

**Comment by olivere** [comment]
I'm not sure I understand. I mean: Why do you want the raw JSON request? If you want to log it, you can use the trace log. If you want to modify it, use the builder to modify it. If you want tracing, you can provide your own `*http.Client` / `*http.Transport`.

There is no orthogonality in the library in terms of query building and executing the requests. However, you can build your own JSON and pass it into `client.PerformRequest(...)`.

**Comment by sumit-nference** [comment]
Consider this example:

Indexname = twitter

I manage to create a function call like below, but don't know how body needs to be passed.

```
p1 := elastic.PerformRequestOptions{"GET", "http://localhost:9200/twitter/_search", url.Values{}}
client.PerformRequest(ctx, p1)
```
For reference, I need a query like this :
```
GET twitter/_search?pretty
{
  "query": {
        "match": {
            "place": "Paris"
        }
    }
}
```
Can you please help me in making a right function call to get the result (data)

**Comment by olivere** [comment]
You use something like this:

```
q := elastic.NewMatchQuery("place", "Paris")

searchResult, err := client.Search().
    Index("twitter").   // search in index "twitter"
    Query(q).           // specify the query
    Sort("user", true). // sort by "user" field, ascending
    From(0).Size(10).   // take documents 0-9
    Pretty(true).       // pretty print request and response JSON
    Do(ctx)
```

Please take a look into the dozens of test files in the repository, e.g. [`search_queries_match_test.go`](https://github.com/olivere/elastic/blob/release-branch.v7/search_queries_match_test.go). Consider the tests part of the documentation.

**Comment by olivere** [comment]
@sumit-nference Also refer to the Wiki. It has a [page on the QueryDSL](https://github.com/olivere/elastic/wiki/QueryDSL), including a larger example of a `Finder`.

**Comment by sumit-nference** [comment]
@olivere Thanks for sharing.
The real problem is I don't have a definite templating of elastic to use any of these examples.
like in the Finder example, there is a struct defined for Film, Finder. I can't do the same in my case.

Hence, there can be different key value pairs in ES for each hit.

As all the results after query might have different sets of key:value pairs, I want to get the entire json result.

**Comment by olivere** [comment]
If you're working on a completely unknown structure—both at request as well as response time—you can only use `client.PerformRequest`. It will return a [`*elastic.Response` with a `Body`](https://github.com/olivere/elastic/blob/release-branch.v7/response.go#L28).

But if the only thing you use from this library is `PerformRequest`, you'd probably be better off using a plain-old `*http.Client`. In that case, Elastic isn't much more than a bit of error handling and load-balancing.

**Comment by sumit-nference** [comment]
Sounds great Oliver. Will go for http
Thanks
