### ISSUE TITLE
support _search/template ?

### ISSUE THREAD

**Issue by zplzpl** [olivere/elastic#418]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior

index/type/_search/template

### Please describe the actual behavior

search buildUrl not found template mode

### Any steps to reproduce the behavior?

search().do()

**Comment by olivere** [comment]
That's [still missing](https://github.com/olivere/elastic/blob/b272fab42387a42585235d56f8c6b53b13ddfb7d/client.go#L1281). Feel free to contribute.

**Comment by olivere** [comment]
Notice however that you can manage search templates already, i.e. [GetTemplate](https://github.com/olivere/elastic/blob/release-branch.v5/get_template.go), [PutTemplate](https://github.com/olivere/elastic/blob/release-branch.v5/put_template.go), and [DeleteTemplate](https://github.com/olivere/elastic/blob/release-branch.v5/delete_template.go).

**Comment by zplzpl** [comment]
`

    res,err:=es.Search().
    Index(string(request.SearchIndex())).
    Type(string(request.SearchType())).
    Template(string(request.SearchTemplate())).
    Source(string(request.SearchBody())).
    Do(ctx)
`


I added a template method

**Comment by olivere** [comment]
As I said, the SearchTemplate API is not yet implemented. It's different from the Search API. You can find the REST API specification [here](https://github.com/elastic/elasticsearch/blob/v5.1.1/rest-api-spec/src/main/resources/rest-api-spec/api/search_template.json).
