### ISSUE TITLE
support change notifications

### ISSUE THREAD

**Issue by dhbarman** [olivere/elastic#419]
[ ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior

Is there a way to set watch-notifications so that an ES client may know when an index or document changes ? 

If no, is there a plan to add such a support ? Etcd supports a similar functionality.

**Comment by olivere** [comment]
Elastic is simply a REST API for Elasticsearch for the Go programming language. It's not a product but a library to work with Elasticsearch. So I'm afraid you probably have to ask the people at Elastic for such features. Maybe [Alerting/Watcher](https://www.elastic.co/products/x-pack/alerting) is what you're looking for.

**Comment by kmulvey** [comment]
@dhbarman via commercial plugin X-Pack  

https://www.elastic.co/guide/en/x-pack/current/xpack-alerting.html
