### ISSUE TITLE
Panic on bulk update requests

### ISSUE THREAD

**Issue by tkpdgun** [olivere/elastic#420]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[x] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)

Go Version: 1.7.4

### Please describe the expected behavior
suppressing error

### Please describe the actual behavior
error message:
```
panic: value method elastic.BulkUpdateRequest.Source called using nil *BulkUpdateRequest pointer

goroutine 362 [running]:
panic(0xb428c0, 0xc420b65290)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
gopkg.in/olivere/elastic%2ev3.(*BulkUpdateRequest).Source(0x0, 0xc42085fa0a, 0x0, 0x0, 0x0, 0x0)
        <autogenerated>:1606 +0x124
gopkg.in/olivere/elastic%2ev3.(*BulkService).bodyAsString(0xc423bec380, 0x7fd112e68000, 0x0, 0x417055, 0x413f6a)
        /mnt2/dpkg-build/ads-build/src/gopkg.in/olivere/elastic.v3/bulk.go:139 +0x8f
gopkg.in/olivere/elastic%2ev3.(*BulkService).DoC(0xc423bec380, 0x0, 0x0, 0xc42498bc70, 0xc4203bb6a0, 0x59c0f8)
        /mnt2/dpkg-build/ads-build/src/gopkg.in/olivere/elastic.v3/bulk.go:169 +0xee
gopkg.in/olivere/elastic%2ev3.(*BulkService).Do(0xc423bec380, 0xca7ae8, 0xc42498bc70, 0x0)
        /mnt2/dpkg-build/ads-build/src/gopkg.in/olivere/elastic.v3/bulk.go:156 +0x3d
...
```
using the latest commit

### Any steps to reproduce the behavior?
Sorry, I have no clue about it.
I've add validation `req != nil`. still got the same error though it's occasionally happen (about one in every million call)

**Comment by olivere** [comment]
Bulk only uses the requests that you pass into it via [`Add`](https://github.com/olivere/elastic/blob/release-branch.v3/bulk.go#L94-L101)? Are you sure you do not pass a `nil` request to `Add` somehow?

**Comment by olivere** [comment]
Maybe you have some sort of concurrency issue here, where you re-use a `*BulkUpdateRequest` in your code? Testing with the [race detector](https://golang.org/doc/articles/race_detector.html) enabled could help you find such issues.

**Comment by tkpdgun** [comment]
I add validation right before calling `req.Source()` on bulk.go file seems not help. About race condition, I use mutex, define variable locally, avoid go-routine (inside & caller function itself) and also testing `Copy()` of s.requests into a local slice before bodyAsString iteration.

Okay, I'll take a look on it.
Thank You.

**Comment by olivere** [comment]
I don't think `req.Source()` is not the problem. I think you add a `nil` request via `Add(...)`. Please try to figure out if you add a `nil` there in your code.

```
var batch []elastic.BulkableRequest
for <some-condition> {
  req := <create-some-bulk-request>
  if req == nil {
    // I think the request might be nil here in your code, so check for this!
    panic("request is nil")
  }
  batch = append(batch ,req)
}
bulk = bulk.Add(batch...)
```
