### ISSUE TITLE
op_type in Reindex

### ISSUE THREAD

**Issue by keepschanging** [olivere/elastic#424]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?
[*] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
Need to reindex from index "a" to index "b" with update and create options.
Not able to include the op_type field in reindex as per elasticsearch docs.

What way can we use to implement the above behaviour ?

**Comment by olivere** [comment]
Can you clarify? `OpType` already exists (see [the tests](https://github.com/olivere/elastic/blob/release-branch.v5/reindex_test.go#L86-L103)), but maybe I've been missing something?!

**Comment by keepschanging** [comment]
oh damn! I was trying to apply it on the service rather than the destination. Sorry for the trouble!
