### ISSUE TITLE
Switch to "context" from stdlib when 1.8 comes out

### ISSUE THREAD

**Issue by olivere** [olivere/elastic#425]
We want to switch from `"golang.org/x/net/context"` to `"context"` when 1.8 is ready.

**Comment by eticzon** [comment]
Hi @olivere! Thanks for this awesome lib! I'd like to get involved, if that's OK. 😄  Would you mind if I start with this "admin"-y task first?

**Comment by olivere** [comment]
I'd appreciate support if you're ready to spend some of your time. I agree changing `golang.org/x/net/context` to `context` should be pretty straightforward. So if you want, feel free to create a PR. Please do so for v5 first.

**Comment by eticzon** [comment]
Thanks @olivere! Much appreciated! PR's up as well when you've got time to review.

**Comment by olivere** [comment]
@eticzon I haven't looked into this recently. But can we also switch away from `golang.org/x/net/context/ctxhttp` now that we have `WithContext(...)` in stdlib?

**Comment by eticzon** [comment]
Good point @olivere. I'll change the calls to `ctxhttp` then and replace them `WithContext(...)` alternatives.

**Comment by olivere** [comment]
Thanks so much for working on this. It's been tagged as 5.0.36 now.
