### ISSUE TITLE
NewClient without a connection to ES

### ISSUE THREAD

**Issue by pranas** [olivere/elastic#426]
First of all, thanks for a great project!

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[X] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior

I'd like to have a way to start elastic without a connection to ES. We need our code to start even if ES is down (and preferably re-connect when it comes back online again). Ideally, we would like to get errors when we perform operations on ES but not when initialising the client. It seems like a valid use case. Is there a way to achieve this already?

### Please describe the actual behavior

``NewClient`` returns nil and error if ES is unavailable.

### Any steps to reproduce the behavior?

Execute ``client, err := elastic.NewClient()`` when ES is down.

**Comment by olivere** [comment]
The default behavior of the Client is to try everything to create and hold connections to the Elasticsearch cluster. This is how the official clients work as well. So the `NewClient` starts a process sniffing the cluster, and if it fails, it will complain.

So you have two options if you don't want this behavior: First, disable sniffing with the option `NewClient(..., elastic.SetSniff(false))` (see the [wiki](https://github.com/olivere/elastic/wiki/Sniffing)). Second, use the [`NewSimpleClient(...)`](https://github.com/olivere/elastic/blob/release-branch.v5/client.go#L277) option to get a "throwaway" client that is only available on a per-request basis.
