### ISSUE TITLE
FieldStats response missing aggregatable / searchable fields

### ISSUE THREAD

**Issue by jgoodall** [olivere/elastic#433]
elastic.v5 (for Elasticsearch 5.1.1)

### Please describe the expected behavior

The [Elasticseach Field Stats API](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-field-stats.html) lists two fields, `is_aggregatable` and `is_searchable` that are not present in the [FieldStats](https://godoc.org/gopkg.in/olivere/elastic.v5#FieldStats) response.

### Please describe the actual behavior

The fields `is_aggregatable` and `is_searchable` are not present in the [FieldStats](https://godoc.org/gopkg.in/olivere/elastic.v5#FieldStats) response from [`FieldStatsService`](https://godoc.org/gopkg.in/olivere/elastic.v5#FieldStatsService).

Is it possible to add these fields to `FieldStats` response?

**Comment by olivere** [comment]
Yep. I fixed this and released 5.0.18 just now. The `type` field was also missing.
