### ISSUE TITLE
support for response-filtering ?

### ISSUE THREAD

**Issue by cyrilleverrier** [olivere/elastic#434]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[X ] elastic.v3 (for Elasticsearch 2.x)
[X ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior

elastic.v5 and elastic.v3 supports all the features defined in the Elasticsearch HTTP API

### Please describe the actual behavior

It is not possible to add a [response-filtering](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#common-options-response-filtering) to the query.

**Comment by cyrilleverrier** [comment]
I browsed your code and it should be fairly easy to append the `filter_path` URL param in `search.go` file

**Comment by olivere** [comment]
Thanks for reporting. It's next to impossible to implement all features defined in the ES API. But I try my best.

Yes, it'd be easy for searching which is probably the 99% use case of `filter_path`. But as it's a common API setting, so we probably need to implement it for every request. I'll see if that's possible without too many problems.

**Comment by cyrilleverrier** [comment]
Thanks @olivere .

I am using elasticearch with libbeat to aggregate metrics.
By using `filter_path`, I can reduce the size of the HTTP response body by filtering the results of sub-aggregations

**Comment by olivere** [comment]
I added source filtering to the Search API for v3 and v5 in v3.0.65 and v5.0.21 respectively.
