### ISSUE TITLE
Get raw response

### ISSUE THREAD

**Issue by MaxJust** [olivere/elastic#436]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[*] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior

I want to get a raw response from elasticsearch without json decode, is it possible?
Here My code:

mq := elastic.NewMultiMatchQuery(request.Keyword, "title").MinimumShouldMatch("100%")
svc := elastic_repo.Client.
		Scroll(elastic_repo.GetIndexByCurrency(request.Currency)).
		Query(mq).
		Size(SCROLL_SIZE)

res, err := svc.Do(context.TODO())   //// And here I need a raw response (not decoded):

Please tell how I can Do IT?

**Comment by olivere** [comment]
The purpose of elastic's services is exactly to _not_ having to deal with raw response. If you want raw responses, you could use a simple load-balancing HTTP client.

If you still want low-level access, you can use [`PerformRequest(...)`](https://github.com/olivere/elastic/blob/release-branch.v5/client.go#L1073-L1204) in the client directly.

Notice though that by using the low-level functions, you won't get the benefits of the services. E.g. the Scroll service will automatically manage pagination for you. You have to manage that yourself if you switch away from the services.
