### ISSUE TITLE
can't use function_score query with filter

### ISSUE THREAD

**Issue by mosasiru** [olivere/elastic#439]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[x] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior

I want to use function_score query with just filter query like this.
https://www.elastic.co/guide/en/elasticsearch/guide/current/function-score-filters.html

```
GET /_search
{
  "query": {
    "function_score": {
      "filter": { 
        "term": { "city": "Barcelona" }
      },
      "functions": [ 
        {
          "filter": { "term": { "features": "wifi" }}, 
          "weight": 1
        },
        {
          "filter": { "term": { "features": "garden" }}, 
          "weight": 1
        },
        {
          "filter": { "term": { "features": "pool" }}, 
          "weight": 2 
        }
      ],
      "score_mode": "sum", 
    }
  }
}
```

### Please describe the actual behavior

But elastic.v3 `FunctionScoreQuery` seems filter query is not acceptable.

**Comment by olivere** [comment]
Fixed in v3.0.64.
