### ISSUE TITLE
Make RetryWait an option

### ISSUE THREAD

**Issue by gittycat** [olivere/elastic#440]
The client.go code has the retryWait period hardcoded.
There's already a TODO above the code to make it configurable.
```
// We wait between retries, using simple exponential back-off.
// TODO: Make this configurable, including the jitter.
retryWaitMsec := int64(100 + (rand.Intn(20) - 10))
```

This would be specially useful in a Docker environment where the Elasticsearch container might recover automatically in a few seconds.

**Comment by olivere** [comment]
Theres a [`retrier`](https://github.com/olivere/elastic/tree/retrier) branch tracked by #298. It implements a configurable retry/backoff mechanism. But I'm not yet happy with the configuration of the retrier. Maybe you can validate the approach.

**Comment by olivere** [comment]
@gittycat You should have a way to intercept HTTP failures via `Retrier` now (see [a855324](https://github.com/olivere/elastic/commit/a85532499f01f2c7eccb34ec7c850d2c01134319) for implementation). I'm about to document the `Retrier` in the wiki later.
