### ISSUE TITLE
BoolQuery example 

### ISSUE THREAD

**Issue by ellisonleao** [olivere/elastic#441]
### Which version of Elastic are you using?

[x] elastic.v2 (for Elasticsearch 1.x, using Elasticsearch 1.7.5)
 
Hey guys i was trying to move a bool query body request into elastic go code. This is the following body

```js
                query: {
                    bool: {
                        should: [
                            {
                                match: {
                                    name: {
                                        query: textQuery,
                                        boost: 4
                                    }
                                }
                            },{
                                match: {
                                    name: {
                                        query : textQuery,
                                        boost : 1,
                                        fuzziness: 1,
                                    }
                                }
                            }
                        ]
                    }
                }
```

Right now the code is: 

```go
        var esItem someStruct
	query := elastic.NewBoolQuery()

	matchQuery := elastic.NewMatchQuery("name", "somename")
	matchQuery.Boost(4)

	matchQuery2 := elastic.NewMatchQuery("name", "somename")
	matchQuery2.Boost(1)
         
        // What should be the Fuzziness value? 
	matchQuery2.Fuzziness("")

	res, err := es.Search("doc").Index("myindex").Query(query).Do()

	if err != nil {
		panic(err)
	}

	for _, item := range res.Each(reflect.TypeOf(esItem)) {
		esItem = item.(someStruct)
		results = append(results, esItem)
	}

	for _, j := range results {
                   // print values
	}
}

```

The problem is that MatchQuery Fuzziness expects a string type and on the body match request the fuzziness is an `int`. What am i doing wrong? Sorry to open an issue, but i could not find any examples on the docs.

**Comment by olivere** [comment]
Fuzziness allows many different expressions. See [the docs](https://www.elastic.co/guide/en/elasticsearch/reference/5.1/common-options.html#fuzziness) for some examples. This was even true [in 1.7](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/common-options.html#fuzziness).

If you want to use `1` (the number), simply pass `"1"` (the string). But you are correct in that I could change the fuzziness parameter type from `string` to `interface{}`.

**Comment by ellisonleao** [comment]
Hey @olivere , thanks for the reply.

Yeah, i've tried `"1"` as value, but the results are not getting the same as the raw query itself. Is there any way i can pass the raw body request and not use the DSL on 1.7? I saw v5 branch has a `RawQueryString` type? Should i use `client.PerformRequest` directly on 1.7?

**Comment by olivere** [comment]
@ellisonleao If the results aren't the same, I'm pretty sure something else is wrong/different. It should return the same as if your passing 1 (the numeric value). Please try first by testing with e.g. curl on the command line.

You can use `PerformRequest` if you want. But elastic was written to _not_ be required to work with raw HTTP requests and responses.

`RawStringQuery` should be straightforward to backport to elastic.v2. Feel free to contribute.

**Comment by ellisonleao** [comment]
I see, 

One thing i've noticed is that the generated source is getting empty when i create that query.

```go
	query := elastic.NewBoolQuery()
	q1 := elastic.NewMatchQuery("name", "twit")
	q1.Boost(4)

	q2 := elastic.NewMatchQuery("name", "twit")
	q2.Boost(1)
	q2.Fuzziness("1")

	query.Should(q1, q2)

	source := query.Source()
	data, _ := json.Marshal(source)
	fmt.Println("DATA", string(data))

        // DATA {"bool":{}}
```

Is this a bug?

**Comment by olivere** [comment]
In elastic.v2, a new query/object is returned when you set a property. So you need to chain them:

```
q2 := elastic.NewMatchQuery(...)
q2 = q2.Boost(1)
```

instead of

```
q2 := elastic.NewMatchQuery(...)
q2.Boost(1)
```

**Comment by ellisonleao** [comment]
Nice, that was the issue. I think we can close this. I will open a PR later for the `RawStringQuery` backport if that is okay
