### ISSUE TITLE
Logging vs Channels

### ISSUE THREAD

**Issue by jgoodall** [olivere/elastic#443]
Using elastic.v5 (for Elasticsearch 5.x)

This is a feature request for being able to get an Error Channel or set an Error Callback function.

I see that there is a way to pass Error/ Info / Trace logger to a client, but a more flexible approach would be a Error / Info /Trace notifier - a channel that a client can listen to as well as respond to. The current approach probably works fine for many use cases, but having a channel would be useful for structured logging. While it is possible to pass a custom logger I don't see a way to implement structured logging where the fields of the log are populated dynamically using something like [logrus](https://github.com/Sirupsen/logrus).

Thanks.

**Comment by olivere** [comment]
Thanks for your support.

To be honest, I'm still looking into a good way of passing errors and tracing information to the client. E.g. I share Peter's view when it comes to [logging vs instrumentation](https://peter.bourgon.org/blog/2016/02/07/logging-v-instrumentation.html). But libraries like elastic are different to applications in that IMHO they should not bind to a specific logging system like logrus. Instead, they should enable a mechanism to pass "actionable" information to the application in a structured way. Elastic is way to chatty in this regard. I'm still not sure how to correctly implement instrumentation though (see #221 for some context and history).

I also think that using a channel for passing log data is not the right way to go for a library. If you want to use a channel, you can wrap the existing logging mechanism in your application. Wrapping could be done by something like this:

```
// elasticLogger wraps log messages from Elastic and redirects them to logger.
type elasticLogger struct {
        log.Logger
}

// Print wraps a logging message from elastic and redirects it into e.g. Go-kit's logger.
func (l elasticLogger) Printf(format string, v ...interface{}) {
        l.Logger.Log("component", "elastic", "level", "error", "msg", fmt.Sprintf(format, v...))
        // Or use a channel here, if that's what you want to do...
}

...

client, err := elastic.NewClient(
    "http://127.0.0.1:9200",
    elastic.SetErrorLog(elasticLogger{kitlogger}))
...
```

There's an example of a custom logger in [this test](https://github.com/olivere/elastic/blob/release-branch.v5/client_test.go#L821-L862).

If you have a good example of a library implementing logging and instrumentation the way you think it should work, let me know.

**Comment by jgoodall** [comment]
@olivere - yes, that is how I am wrapping it now. It works, but I dont see a way to add dynamic information (e.g. the address or the version of the server) that is not known at compile-time. Am I missing something?

If not a channel, then a callback when there are errors? Similar to `SetSnifferCallback`? 

Yes, Elasticsearch is ridiculously chatty - but I am more interested in catching errors than tracing information. Yes, I would like to log the errors in the same structured way I do in other parts of the application, but I would also like the option to parse them and do something about them.

Though not quite the same, an example is the [`NotifyClose`](https://godoc.org/github.com/streadway/amqp#Channel.NotifyClose) method in the `amqp` package. The application can listen to the channel, log the error, and try to reconnect.

Does that make sense?

**Comment by olivere** [comment]
@jgoodall I think I see what you're after.

If you're interested in being notified of errors, I think it might help to wait for the `Retrier` that is in the works now. Although I didn't think of it in terms of error handling/reporting it might be a good fit.

Some background: All requests somehow end up calling `PerformRequest` on the client. Right now, `PerformRequest` does only simple retrying. The `Retrier` interface would give users a chance to intercept into this process. It serves many different purposes. First, it gives users a chance to use a backoff algorithm that best suits their needs (exponential backoff, simple, or no backoff). Second, it gives users a chance to decide whether to retry at all. Third, it receives the error that elastic got and can decide what to do in that case, or even return a different kind of error for elastic to continue.

And fourth might be your use case... Suppose I'd also pass the failed `http.Response` and the error to your custom `Retrier` implementation: Then you could probably use it for structured logging. Would that serve your needs?

**Comment by jgoodall** [comment]
@olivere - yes, I think that sounds good. When do you expect it to be released?

**Comment by olivere** [comment]
You should have a way to intercept HTTP failures via `Retrier` now (see [a855324](https://github.com/olivere/elastic/commit/a85532499f01f2c7eccb34ec7c850d2c01134319) for implementation). I'm about to document the `Retrier` in the wiki later.

Let me know if this works for you.

**Comment by jgoodall** [comment]
I would like to add a `Context` from my bulk indexer, but `BulkProcessorService` has a `Do` method with no `Context`. Maybe there is another way to do this, but would like to add things like the worker id. Can that be done currently?

**Comment by olivere** [comment]
Sure. Please create a new issue for it and I'll work on it eventually.

**Comment by jgoodall** [comment]
Will do - also `BulkProcessorService` has its own internal retry method, so it seems like things are getting retried twice currently, and I dont see a way to turn off the retry in the `BulkProcessorService` despite the documentation that says "BulkProcessorService also does retry **by default**, using an exponential backoff algorithm."

Should the bulkprocessor use the same custom retrier?

**Comment by olivere** [comment]
Yes. I should remove the `gokpg.in/olivere/elastic.vx/backoff` directory and move everything to use the same backoff/retry mechanism. Can you create a 2nd issue for that please?
