### ISSUE TITLE
Not enough arguments in call to 

### ISSUE THREAD

**Issue by sschimmel** [olivere/elastic#444]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[X] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
Expected is that the code compiles.

### Please describe the actual behavior
On `go build` the following compilation error is thrown: `not enough arguments in call to esClient.Search().Index("charging").Query(rangeQuery).Aggregation("daily", dailyAgg).Sort("Recorded", false).From(0).Size(1).Pretty(true).Do`

### Any steps to reproduce the behavior?
The following code is based on the example found in the [getting started chapter of the v5 tag]( https://github.com/olivere/elastic/tree/v5.0.18).

This is the code snippet I wrote. The `esClient` is a `elastic.NewClient()`.

Running go build on this will produce the error.

`import "gopkg.in/olivere/elastic.v5"`

```go
rangeQuery := elastic.NewRangeQuery("Recorded")
	rangeQuery.Gte(gte.String())
	rangeQuery.Lt(lt.String())
	rangeQuery.TimeZone("Europe/Amsterdam")
	rangeQuery.Format("MM-YYYY")

	dailyTotalImportStats := elastic.NewStatsAggregation().Field("TotalImport")

	dailyAgg := elastic.NewDateHistogramAggregation()
	dailyAgg.Field("Recorded")
	dailyAgg.Interval("day")
	dailyAgg.TimeZone("Europe/Amsterdam")
	dailyAgg.SubAggregation("statistics", dailyTotalImportStats)


	search, err := esClient.Search().
		Index("charging").
		Query(rangeQuery).
		Aggregation("daily", dailyAgg).
		Sort("Recorded", false).
		From(0).
		Size(0).
		Pretty(true).
		Do()

	if err != nil {
		fmt.Println(err)
	}

```

**Comment by olivere** [comment]
Thanks for reporting: The example code in the README is missing a `context.Context` that needs to be passed into the `Do(...)` call. This is mandatory as of elastic.v5 and I didn't modify the README and the project homepage. The reason for that is the under its covers, Elastic uses the [`ctxhttp`](https://godoc.org/golang.org/x/net/context/ctxhttp) package for cancelable HTTP requests.

**Comment by olivere** [comment]
GitHub pages and README are fixed. Thanks.
