### ISSUE TITLE
Remove the SetMaxRetries option

### ISSUE THREAD

**Issue by olivere** [olivere/elastic#448]
You can achieve the same via a custom [`Retrier`](https://github.com/olivere/elastic/wiki/Retrier-and-Backoff).

**Comment by eticzon** [comment]
@olivere, I can have a look at this if you want.

**Comment by olivere** [comment]
@eticzon Thanks. I think we should delay this (breaking) change until 6.0. If you want to tackle something hard, #415 is a good one. I currently don't have the time to do that. If you're looking for something much more straightforward, #297 is a long standing issue.

**Comment by olivere** [comment]
It doesn't make sense to remove this. If you need a complex/custom retrier, you can use `SetRetrier`, e.g.:

```
client, err := elastic.NewClient(
	elastic.SetHttpClient(httpClient),
	elastic.SetRetrier(elastic.NewBackoffRetrier(elastic.NewSimpleBackoff(100, 200, 300, 400, 500))), // 5 retries with fixed delay of 100ms, 200ms, 300ms, 400ms, and 500ms
	elastic.SetHealthcheck(false),
)
```

Otherwise, the `SetMaxRetries(n)` helper is a good companian if you want simple retries.
