### ISSUE TITLE
Add Http Basic Auth support to requests

### ISSUE THREAD

**Issue by foeken** [olivere/elastic#45]
We are using the newly released shield plugin for ES. This requires us to set the authentication header.

I'd like to add that to the client, would you prefer this as a Request mutator just like `SetBodyJson` in https://github.com/olivere/elastic/blob/023773e3454ae460b40687dbf893821c371a033f/request.go or as a Client setting that is automatically added to each request. Since each request *might* require different authorisation a per request setting would not be the worst thing here...

Any thoughts?

**Comment by olivere** [comment]
Interesting. I didn't have a user asking for this :-)

Just for reference, the Shield documentation describes the authentication process for REST clients [here](http://www.elasticsearch.org/guide/en/shield/current/_http_rest_clients.html).

My first thought would be to include the credentials in the URL. That should work if you have sort of a role account to access ES. Although I've never tried. Sorry.

If, like you say, you have a different credential for each request, you could probably implement that with your own [http.Transport](http://golang.org/pkg/net/http/#Transport). You need to inject the credentials into the request in `RoundTrip`. You can find an example of a transport e.g. in the [OAuth2 code](https://github.com/golang/oauth2/blob/master/transport.go). You need to pass the `http.Client` with your http transport into `NewClient` then.

**Comment by foeken** [comment]
Thats interesting, I'll try that and get back to you!

**Comment by foeken** [comment]
This works like a charm. We were already passing in a custom client with certificate support (untested so far) and this was an easy addition.

For reference I just passed it like this:

```go
package main

import (
  "net/http"
)

type BasicAuthTransport struct {
  *http.Transport
  username string
  password string
}

func (t BasicAuthTransport) RoundTrip(r *http.Request) (*http.Response, error) {
  r.SetBasicAuth(t.username, t.password)
  return t.Transport.RoundTrip(r)
}
```

```go
httpClient = &http.Client{
  Transport: &BasicAuthTransport{
    Transport: &http.Transport{},
    username:  "test",
    password:  "test",
  },
}
```

**Comment by jordan-wright** [comment]
Thanks for this @foeken - exactly what I was looking for.

**Comment by tehmoon** [comment]
Working for me too !
Thanks @foeken @olivere

**Comment by olivere** [comment]
You're welcome. For reference: It's also [in the Wiki](https://github.com/olivere/elastic/wiki/HttpTransport).
