### ISSUE TITLE
Wiki: Connecting to AWS Elasticsearch Service

### ISSUE THREAD

**Issue by tmaiaroto** [olivere/elastic#451]
### Which version of Elastic are you using?
elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
Examples from https://github.com/olivere/elastic/wiki/Using-with-AWS-Elasticsearch-Service should connect to AWS ES.

### Please describe the actual behavior
Received "no node available" errors.

-----------

Just a note here, I noticed that both alternative examples didn't work for me when connecting to AWS' Elasticsearch service.

Of course it was the first example that did work (that at first I chose to skip for one reason or another). It even worked despite the little note there about 403 errors (which I haven't seen -- edit: NOW I see them, but didn't until going to index documents...connecting and creating an index even was fine). 

The other two examples led me to no node available errors.  If I were recommending to people to sign their requests, it is that first example that I would suggest and not the other two.

This may not be the case for older versions, but for v5 this is what I experienced. I'm not sure why it'd be different, but I ran through each one and it was the first that worked while the others did not. 

Thought it was wroth mentioning in case it saved anyone from a headache and some lost time. They all seem very similar, but one of these things is not like the other =)

**Comment by olivere** [comment]
It would be even better if you just fixed the Wiki page, or wrote a blog post about your experiences and add a link to that Wiki page. I'm not using Elasticsearch on AWS, and I consider my devops skills to be limited. So I'm probably not competent enough to keep that page up-to-date. Sorry.

**Comment by tmaiaroto** [comment]
Do I have the ability to do that? I didn't want to just start rewriting someone's documentation even if I could. I honestly don't know how wiki editing works on GitHub with regard to permissions and versioning and such.

I will likely write a blog post too.

Not a problem on keeping that page up to date. I completely understand.

**Comment by olivere** [comment]
@tmaiaroto [I think you have](https://github.com/olivere/elastic/wiki/Using-with-AWS-Elasticsearch-Service/_history). If everyone acts responsibly and doesn't simple delete stuff others might find valuable, I think a Wiki is just fine.

On a side note: One of the things I find "disturbing" about maintaining an open source project is that you basically never get any positive feedback. If everything works, people keep silent. I don't even know who's using elastic. You only ever notice when something's wrong. So yeah, any news is appreciated, whether it's bug reports or wiki pages or blog posts illustrating usage patterns that I e.g. can link to in the issues and/or wiki.

And remember to give your sysadmin a hug from time to time: They suffer from the same phenomenon ;-)

**Comment by tmaiaroto** [comment]
Yes, I find that disturbing too :) Especially when you're busy and don't have the time to maintain something.

That said, I'll look into this more when I do have some time.

**Comment by tomj** [comment]
@olivere - consider this my positive feedback!  This project is a monster, thankyou for all your hard work! :)  @tmaiaroto - any chance you could just paste here your initial findings?  A wiki would be great but *anything* is better than nothing for now :)

**Comment by tmaiaroto** [comment]
I did make a slight update to the wiki. I didn't want to remove any information (may still be valid for users of older versions of things? not sure) but I did note that there's another repo that works. The first approach on the wiki with signing requests is what seemed to work for me. Just a slight confusion on an update, a pull request not yet merged in.

**Comment by olivere** [comment]
@tomj Thank you. But I wasn't fishing for compliments really.
@tmaiaroto Thanks for your support.
