### ISSUE TITLE
Golang type for IP address

### ISSUE THREAD

**Issue by dhbarman** [olivere/elastic#452]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior

If a golang struct has a field representing IP address, what type I should use for that field so that I can use a mapping as shown here: https://www.elastic.co/guide/en/elasticsearch/reference/current/ip.html ?

### Any steps to reproduce the behavior?

Use any golang struct and mapping as described.

**Comment by olivere** [comment]
A `string` should do. Here's an example:

```go
// Copyright 2012-present Oliver Eilhard. All rights reserved.
// Use of this source code is governed by a MIT-license.
// See http://olivere.mit-license.org/license.txt for details.

package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"math/rand"
	"time"

	"gopkg.in/olivere/elastic.v5"
)

func main() {
	var (
		url   = flag.String("url", "http://localhost:9200", "Elasticsearch URL")
		index = flag.String("index", "", "Elasticsearch index name")
		typ   = flag.String("type", "", "Elasticsearch type name")
		sniff = flag.Bool("sniff", true, "Enable or disable sniffing")
	)
	flag.Parse()
	log.SetFlags(0)
	rand.Seed(time.Now().UnixNano())

	if *url == "" {
		log.Fatal("missing url parameter")
	}
	if *index == "" {
		log.Fatal("missing index parameter")
	}
	if *typ == "" {
		log.Fatal("missing type parameter")
	}
	// Create an Elasticsearch client
	client, err := elastic.NewClient(elastic.SetURL(*url), elastic.SetSniff(*sniff))
	if err != nil {
		log.Fatal(err)
	}

	mapping := fmt.Sprintf(`{
  	"settings" : {
    	"number_of_shards": 1,
    	"number_of_replicas": 0
   	},
  	"mappings" : {
	    "%s" : {
	      "properties" : {
	        "name" : {
	          "type" : "keyword"
	        },
	        "address": {
	        	"type" : "ip"
	        }
	      }
	    }
  	}
	}`, *typ)

	type doc struct {
		Name    string `json:"name"`
		Address string `json:"address"`
	}

	ctx := context.Background()

	// Recreate the index
	exists, err := client.IndexExists(*index).Do(ctx)
	if err != nil {
		log.Fatal(err)
	}
	if exists {
		_, err := client.DeleteIndex(*index).Do(ctx)
		if err != nil {
			log.Fatal(err)
		}
	}
	_, err = client.CreateIndex(*index).Body(mapping).Do(ctx)
	if err != nil {
		log.Fatal(err)
	}

	// Add some documents
	doc1 := doc{
		Name:    "Router",
		Address: "192.168.1.1",
	}
	_, err = client.Index().Index(*index).Type(*typ).Id("1").BodyJson(doc1).Do(ctx)
	if err != nil {
		log.Fatal(err)
	}

	doc2 := doc{
		Name:    "Work",
		Address: "192.168.1.2",
	}
	_, err = client.Index().Index(*index).Type(*typ).Id("2").BodyJson(doc2).Do(ctx)
	if err != nil {
		log.Fatal(err)
	}

	// Get a document
	res, err := client.Get().Index(*index).Type(*typ).Id("1").Do(ctx)
	if err != nil {
		log.Fatal(err)
	}
	var doc3 doc
	if err := json.Unmarshal(*res.Source, &doc3); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("Get %q => %+v\n", doc1.Name, doc3)

	// Search for documents
	query := elastic.NewTermQuery("address", "192.168.0.0/16")
	sres, err := client.Search(*index).Type(*typ).Query(query).Do(ctx)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("Found %d documents\n", sres.TotalHits())
	for _, hit := range sres.Hits.Hits {
		var doc4 doc
		if err := json.Unmarshal(*hit.Source, &doc4); err != nil {
			log.Fatal(err)
		}
		fmt.Printf("- %+v\n", doc4)
	}
}
```

**Comment by ariden83** [comment]
When I test your code, 

`
doc1 := doc{
		Name:    "Router",
		Address: "192.168.1.1",
	}
	_, err = client.Index().Index(*index).Type(*typ).Id("1").BodyJson(doc1).Do(ctx)`
`

Or when I do 

`
res, err := client.Get().Index(*index).Type(*typ).Id("1").Do(ctx)
	if err != nil {
		log.Fatal(err)
	}
`

I've got this error : 

`
2017/07/18 14:37:50 http: panic serving 127.0.0.1:37688: runtime error: invalid memory address or nil pointer dereference
goroutine 39 [running]:
net/http.(*conn).serve.func1(0xc42032e780)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0xa17600, 0xe4d200)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
gopkg.in/olivere/elastic%2ev5.(*Client).PerformRequest(0xe5ed40, 0xe27a20, 0xc420317b00, 0xad29fe, 0x3, 0xc42033b611, 0xf, 0xc4203c6270, 0xa291a0, 0xc42033b500, ...)
	/home/adrien/work/go/src/gopkg.in/olivere/elastic.v5/client.go:1171 +0x1214
gopkg.in/olivere/elastic%2ev5.(*IndexService).Do(0xc420049898, 0xe27a20, 0xc420317b00, 0xc42033b500, 0x2, 0x2)
	/home/adrien/work/go/src/gopkg.in/olivere/elastic.v5/index.go:267 +0x13b
go.etf1.tf1.fr/etf1-platform/images-service/services/elasticsearch.Search(0xc420337952, 0x3, 0xe27a20, 0xc420317b00, 0xc420359948, 0xad5d73, 0x6, 0xc420337901, 0x3)
	/home/adrien/work/go/src/go.etf1.tf1.fr/etf1-platform/images-service/services/elasticsearch/elasticsearch.go:116 +0x1fb
go.etf1.tf1.fr/etf1-platform/images-service/controller.GetTitle(0x7f83cd069158, 0xc42000e4f8, 0xc4202f3800, 0x0, 0x0, 0x0)
	/home/adrien/work/go/src/go.etf1.tf1.fr/etf1-platform/images-service/controller/image.go:970 +0x96
go.etf1.tf1.fr/etf1-platform/images-service/vendor/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc4203463c0, 0x7f83cd069158, 0xc42000e4f8, 0xc4202f3800)
	/home/adrien/work/go/src/go.etf1.tf1.fr/etf1-platform/images-service/vendor/github.com/julienschmidt/httprouter/router.go:344 +0x813
go.etf1.tf1.fr/etf1-platform/images-service/vendor/github.com/urfave/negroni.Wrap.func1(0x7f83cd069158, 0xc42000e4f8, 0xc4202f3800, 0xc4203379c0)
	/home/adrien/work/go/src/go.etf1.tf1.fr/etf1-platform/images-service/vendor/github.com/urfave/negroni/negroni.go:46 +0x4d
go.etf1.tf1.fr/etf1-platform/images-service/vendor/github.com/urfave/negroni.HandlerFunc.ServeHTTP(0xc420340520, 0x7f83cd069158, 0xc42000e4f8, 0xc4202f3800, 0xc4203379c0)
	/home/adrien/work/go/src/go.etf1.tf1.fr/etf1-platform/images-service/vendor/github.com/urfave/negroni/negroni.go:29 +0x4e
go.etf1.tf1.fr/etf1-platform/images-service/vendor/github.com/urfave/negroni.middleware.ServeHTTP(0xe229e0, 0xc420340520, 0xc420340580, 0x7f83cd069158, 0xc42000e4f8, 0xc4202f3800)
	/home/adrien/work/go/src/go.etf1.tf1.fr/etf1-platform/images-service/vendor/github.com/urfave/negroni/negroni.go:38 +0xb4
go.etf1.tf1.fr/etf1-platform/images-service/vendor/github.com/urfave/negroni.(middleware).ServeHTTP-fm(0x7f83cd069158, 0xc42000e4f8, 0xc4202f3800)
	/home/adrien/work/go/src/go.etf1.tf1.fr/etf1-platform/images-service/vendor/github.com/urfave/negroni/negroni.go:38 +0x60
go.etf1.tf1.fr/etf1-platform/images-service/middleware.Header(0x7f83cd069158, 0xc42000e4f8, 0xc4202f3800, 0xc4203379a0)
	/home/adrien/work/go/src/go.etf1.tf1.fr/etf1-platform/images-service/middleware/header.go:18 +0x2a5
go.etf1.tf1.fr/etf1-platform/images-service/vendor/github.com/urfave/negroni.HandlerFunc.ServeHTTP(0xafa1f0, 0x7f83cd069158, 0xc42000e4f8, 0xc4202f3800, 0xc4203379a0)
	/home/adrien/work/go/src/go.etf1.tf1.fr/etf1-platform/images-service/vendor/github.com/urfave/negroni/negroni.go:29 +0x4e
go.etf1.tf1.fr/etf1-platform/images-service/vendor/github.com/urfave/negroni.middleware.ServeHTTP(0xe229e0, 0xafa1f0, 0xc420340560, 0x7f83cd069158, 0xc42000e4f8, 0xc4202f3800)
	/home/adrien/work/go/src/go.etf1.tf1.fr/etf1-platform/images-service/vendor/github.com/urfave/negroni/negroni.go:38 +0xb4
go.etf1.tf1.fr/etf1-platform/images-service/vendor/github.com/urfave/negroni.(*Negroni).ServeHTTP(0xc420342690, 0xe270e0, 0xc420097420, 0xc4202f3800)
	/home/adrien/work/go/src/go.etf1.tf1.fr/etf1-platform/images-service/vendor/github.com/urfave/negroni/negroni.go:86 +0x10d
net/http.serverHandler.ServeHTTP(0xc4203b40b0, 0xe270e0, 0xc420097420, 0xc4202f3800)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42032e780, 0xe27a20, 0xc420317980)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
`

Do you know why ?
