### ISSUE TITLE
increasing ESTABLISHED connections count

### ISSUE THREAD

**Issue by Vavilen** [olivere/elastic#453]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[*] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
I thing, that the count of connections should by near some constant value

### Please describe the actual behavior
I see, that when there are many rps to the ES, the count of connections can be more than 100K and continues to increase. Finally,  I receive two types of error:
"http: Accept error: accept tcp [::]:7783: accept4: too many open files; retrying in 1s"
and
"no Elasticsearch node available"

There is nothing strange in profiler - only two strings:
goroutine 83 [select, 3 minutes]:
gopkg.in/olivere/elastic%2ev3.(*Client).sniffer(0xc4203e4000)
	/home/me/project/go/src/gopkg.in/olivere/elastic.v3/client.go:694 +0x193
created by gopkg.in/olivere/elastic%2ev3.NewClient
	/home/user/projector/go/src/gopkg.in/olivere/elastic.v3/client.go:264 +0x665

goroutine 84 [select]:
gopkg.in/olivere/elastic%2ev3.(*Client).healthchecker(0xc4203e4000)
	/home/user/projector/go/src/gopkg.in/olivere/elastic.v3/client.go:884 +0x198
created by gopkg.in/olivere/elastic%2ev3.NewClient
	/home/me/project/go/src/gopkg.in/olivere/elastic.v3/client.go:267 +0x63b
### Any steps to reproduce the behavior?
Just run my service and wait some time
I tried to reproduce my issue, using https://github.com/olivere/elastic/issues/107
But there were not result(

Thanks!

**Comment by olivere** [comment]
Thanks for reporting. I see this kind of problems if e.g. the response body is not closed for some reason.

You said you tried #107. What exactly did you try? Did you try the [test code](https://gist.github.com/olivere/64023cb33dba39d7b5d3)? If so, was it successful or did it fail? Can you send me an extract of your code so that I can reproduce?

**Comment by Vavilen** [comment]
Thank you for fast response!
I have [https://gist.github.com/Vavilen/3420add98118582b00d3db1160d23889](this) dirty example. I have many errors - it`s normal in this situation, but I have also increasing count of connections.
Maybe I have similar situation with errors response (not 200 OK) in my service.

**Comment by olivere** [comment]
I'm sorry, I cannot reproduce. I can run this example for hours and it's constantly at 11 open file descriptors, on a Mac.

The code is very wrong BTW; running it with the race detector will give you some hints.

**Comment by Vavilen** [comment]
Sure, the code is wrong)  Only using this code I could reproduce the issue. 
I will continue research the issue. If I find any results I will report it here.
Thanks!

**Comment by olivere** [comment]
Tested on Linux for a while now, also constantly at 13-14 fds. I'm not sure what's wrong here. Let me know when you find something and I'll re-open this.
