### ISSUE TITLE
Vendoring problems with gopkg.in

### ISSUE THREAD

**Issue by olivere** [olivere/elastic#456]
For reference, if anyone else is having problems with vendoring and gopkg.in: The latest version(s) of git no longer follow redirects by default. This is [described here](https://github.com/niemeyer/gopkg/issues/50), including a workaround.

I'll close this issue once the issue in gopkg.in is fixed.

**Comment by niemeyer** [comment]
No need to change the configuration anymore. We've changed gopkg.in itself to support the new git quirks.

**Comment by olivere** [comment]
@niemeyer Thanks a lot!
