### ISSUE TITLE
bulk not running

### ISSUE THREAD

**Issue by tommoholmes** [olivere/elastic#459]
[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[x] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
I want to store use bulk 

### Please describe the actual behavior
I running my code but bulk not running when I check at ES

### Any steps to reproduce the behavior?
here my code
```
type News struct {
  ID        string    `json:"id"`
  SlugNews  string `json:"slug_news"`
  TitleNews string `json:"title_news"`
}
client, _ := elastic.NewClient(
	    elastic.SetHealthcheck(false),
	    elastic.SetSniff(false),
	    elastic.SetURL("http://127.0.0.1:9200"),
    )
bulk := client.Bulk().Index("getboards").Type("news")
ctx := context.TODO()
insert := &model.News{SlugNews: "TesT",DateNews: "2017-02-24",ID: "Test"}
bulk.Add(elastic.NewBulkIndexRequest().Id("test").Doc(insert))
_, err := bulk.Do(ctx)
if err != nil {
        log.Fatal(err)
        // os.Exit(0)
    }
```
please help me

**Comment by olivere** [comment]
What is the error you get? Also, what is the error logged in the Elasticsearch log file? What happens if you enable the trace log?

**Comment by tommoholmes** [comment]
okeee looks like I can fix it
