### ISSUE TITLE
Profile API

### ISSUE THREAD

**Issue by sundarv85** [olivere/elastic#462]
Hello,

[x] elastic.v5 (for Elasticsearch 5.x)

I see that Profile API is not yet implemented. We are having some performance issue with aggregations and we would like profile and get more information. 

https://www.elastic.co/guide/en/elasticsearch/reference/master/_profiling_aggregations.html

Any chance for this to come in soon.

**Comment by olivere** [comment]
Of course it's a part of the API that I'd love to see covered. However, it's not on my primary focus. I think it's more for debugging and profiling, which falls into the same area as the cat APIs (which are also not implemented as of today).

**Comment by sundarv85** [comment]
yes, I agree it is for debugging and profiling only. Currently I'm trying manually with the curl, but if I can get it running with go, the options for debugging would be much more. Would love to see it covered here.

**Comment by olivere** [comment]
Ha! It's now supported in [5.0.29](https://github.com/olivere/elastic/commit/1b6288276d21f325205641da265aed5978e2a5a1).
