### ISSUE TITLE
elastic.NewTermQuery don't find result with capital letters

### ISSUE THREAD

**Issue by jhayotte** [olivere/elastic#466]
### Version used
[X] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
```
key := "title"
value := "Test"
termQuery := elastic.NewTermQuery(key, value)
searchResult, err := elClient.Search().
		Index("indexsample").
		Type("product").
		Query(termQuery).
		Do(context.Background())
```
This way of search in elastic search should enable me to search the given value for the given key whatever the case is. 

### Please describe the actual behavior
It does not work for value with an UpperCase.

### Any steps to reproduce the behavior?
Insert any value with an uppercase and try to find it with ```elastic.NewTermQuery(key, value)```

### Current workaround
```
searchResult, err := elClient.Search().
		Index("indexsample").
		Type("product").
		Query(elastic.NewSimpleQueryStringQuery(value)).
		Do(context.Background())
```
It works doing so. What I don't like it is that by default we cannot filter to a specific term.

If you have any idea to enhance my workaround in the meantime ?

**Comment by olivere** [comment]
It all depends on the mapping. Maybe you're doing a fulltext query instead of a keyword query. What is the mapping of the `title` property?

See the "Why doesn’t the term query match my document?" in the [term query docs](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/query-dsl-term-query.html).

If this doesn't solve your issue, let me know.

**Comment by jhayotte** [comment]
Indead *standard analyzer* drops most punctuation, breaks up text into individual words, and lower cases them. 
That's the reason, thank you for the explanation. I was looking into your code and finding nothing about lowercase. In fact it comes from Elastic engine.
By the way, good job for this project!

**Comment by olivere** [comment]
You're welcome. Elastic is just a client. Elasticsearch is the thing you need to focus on.
