### ISSUE TITLE
Some hesitations about the threadsafety of esclient

### ISSUE THREAD

**Issue by wolfkdy** [olivere/elastic#468]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v5 (for Elasticsearch 5.x)

Is it ok to share one client between different goroutines without using any sync-methods?
Is every interface in esclient reentrant ?

hoping for your answer, thanks!

**Comment by olivere** [comment]
Yes, it is safe to share the client between Goroutines. I use it like that in production for a long time. If you want to do your own testing, the [`cluster-test`](https://github.com/olivere/elastic/tree/release-branch.v5/cluster-test) directory may be a good starter.
