### ISSUE TITLE
Getting "no Elasticsearch node available" from inside a docker container on ECS using elastic.

### ISSUE THREAD

**Issue by tiny-mouse** [olivere/elastic#470]
### Which version of Elastic are you using?
elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
Given a policy that allows actions `*` on said ES instance from specified IPs, I would expect the following code to connect.

Policy:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": "es:*",
      "Resource": "*",
      "Condition": {
        "IpAddress": {
          "aws:SourceIp": [
            "one ip",
            "another ip",
            "yet another ip",
            "one more ip"
          ]
        }
      }
    }
  ]
}
```
Code:
```
c, err := elastic.NewClient(
	elastic.SetURL(esURL),
	elastic.SetScheme(esScheme),
	elastic.SetSniff(false),
)
```

### Please describe the actual behavior
- I can use said code locally to connect and get the ES version.
- I can curl the ES instance from my ECS instance.
- I can curl the ES instance from inside the docker container on my ECS instance.
- I can write a dummy piece of go code run from inside the docker container that sends a GET to the ES instance (seen below).
- I *cannot* connect to my ES instance using elastic from go code in the docker container.  So, the same code and settings that work on my laptop do not work from within a docker container on an ECS instance.

Example dummy code:
```
package main

import (
   "log"
   "io/ioutil"
   "net/http"
)

func main() {
	resp, err := http.Get("the url to my ES instance.")
	if err != nil {
		log.Printf("ERROR: %v", err)
        } else {
		defer resp.Body.Close()
		body, err := ioutil.ReadAll(resp.Body)
		log.Printf("%v %v", string(body), err)
        }
}
```

### Any steps to reproduce the behavior?

See above.

Any help would be greatly appreciated.

**Comment by olivere** [comment]
Hi! That's typically a problem of being unable to connect to the nodes with the published HTTP address. [Here's the wiki page for it](https://github.com/olivere/elastic/wiki/Connection-Problems#how-to-figure-out-connection-problems).

Can you check what the ES nodes print as the `publish_address` here?

```
$ curl -s -XGET 'http://127.0.0.1:9200/_nodes/http?pretty=1'
{
  "_nodes" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "cluster_name" : "five",
  "nodes" : {
    "SS6BCOe5T5i_yWLpRt0U0Q" : {
      "name" : "SS6BCOe",
      "transport_address" : "127.0.0.1:9300",
      "host" : "127.0.0.1",
      "ip" : "127.0.0.1",
      "version" : "5.2.1",
      "build_hash" : "db0d481",
      "roles" : [
        "master",
        "data",
        "ingest"
      ],
      "http" : {
        "bound_address" : [
          "[fe80::1]:9200",
          "[::1]:9200",
          "127.0.0.1:9200"
        ],
        "publish_address" : "127.0.0.1:9200",
        "max_content_length_in_bytes" : 104857600
      }
    }
  }
}
```

Be sure that your application can connect to the given `publish_address`, which is `"127.0.0.1:9200"` here. You might need to reconfigure [Elasticsearch network settings](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html). You can find an example of this in [the configuration file](https://github.com/olivere/elastic/blob/release-branch.v5/config/elasticsearch.yml) I use to [start ES locally within Docker](https://github.com/olivere/elastic/blob/release-branch.v5/run-es-5.2.1.sh).

Let me know if this helps so I can close the issue.

**Comment by olivere** [comment]
I think I misread your original question. You already disabled sniffing. Elastic shouldn't call the Nodes Info API at all. That's odd. I still bet it's "just" a networking issue.

You wrote:

> 1. I can write a dummy piece of go code run from inside the docker container that sends a GET to the ES instance (seen below).
> 2. I cannot connect to my ES instance using elastic from go code in the docker container. So, the same code and settings that work on my laptop do not work from within a docker container on an ECS instance.
> 

Please double-check if the code in the containers (with elastic.v5 in it) can connect to the <ip>:<port> of the ES instance(s). In other words: If you can connect to the `<ip>:<port>` in step 1, you **must be able to connect** to that same `<ip>:<port>` in step 2. Elastic is just using `net/http` after all, but it does check for a healthy connection in `NewClient`(even if you disabled sniffing).

I'm pretty sure this is not the problem here, but I've seen installations with timing issues. E.g. the ES instance wasn't available for ~10s after startup. I'm convinced that's not your issue (it was very rare), but you could raise the timeouts with e.g. `SetHealthcheckTimeoutStartup(time.Duration)` (see [here](https://github.com/olivere/elastic/wiki/Configuration) for all config options).

**Comment by olivere** [comment]
FYI: If this is of any help, there's also an [example repository for using Elastic with Docker](https://github.com/olivere/elastic-with-docker). I've just updated it to elastic.v5.

**Comment by tiny-mouse** [comment]
Hey!  Thanks for all the help.  This is my least favorite answer to solving problems, but it "magically" started working today without code changes.  This is making me wonder if there was something that wasn't propagating for a day or so within my ECS/IAM setup.  Thanks for everything!

**Comment by olivere** [comment]
Heisenbugs ftw :-)

**Comment by tanner-bruce** [comment]
@tiny-mouse We were experiencing the exact same issue - it ended up being we needed ca-certificates installed in the environment running the code

**Comment by SunRich** [comment]
> Heisenbugs ftw :-)

 Thank you, using your method has solved the problem
