### ISSUE TITLE
Creating index: SIGSEGV

### ISSUE THREAD

**Issue by Firemango** [olivere/elastic#471]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[x] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
I expect an index to be created, using:
```
_, err = client.CreateIndex("billing").Do(ctx)
```

### Please describe the actual behavior
This errors out with:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1234c56]

goroutine 1 [running]:
gopkg.in/olivere/elastic%2ev5.(*Client).PerformRequest(0x0, 0x16c4058, 0xc420010228, 0x12cfb99, 0x3, 0xc42011c5b0, 0x8, 0xc42004fd50, 0x126b0a0, 0xc42011c5c0, ...)
        /Users/kasperbentsen/go/src/gopkg.in/olivere/elastic.v5/client.go:1133 +0x86
gopkg.in/olivere/elastic%2ev5.(*IndicesCreateService).Do(0xc42004ff18, 0x16c4058, 0xc420010228, 0x16c4058, 0xc420010228, 0xc420011320)
        /Users/kasperbentsen/go/src/gopkg.in/olivere/elastic.v5/indices_create.go:113 +0x34b
main.main()
        /Users/kasperbentsen/go/pges/main.go:32 +0xe0
```

### Any steps to reproduce the behavior?
https://gist.github.com/Firemango/b3376dcd69fa94906544a237e7b6f313

This is the full program i am running. I simply run `go run main.go` and it errors out.

**Comment by olivere** [comment]
You are not checking for an error when creating the client. I guess that the connection failed and client is nil.

**Comment by Firemango** [comment]
Of course! Silly me.

I opened a PR to extend to the examples, just so other people who are as reckless with reading examples as me gets into this situation! :)

https://github.com/olivere/elastic/pull/472
