### ISSUE TITLE
x-pack support

### ISSUE THREAD

**Issue by kmulvey** [olivere/elastic#476]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ x] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
I need client support for working with x-pack and am willing to do the work. Would you accept PRs to this repo or should I create a separate project that extends this one? Is it possible to extend this in that way?

https://www.elastic.co/guide/en/x-pack/current/xpack-api.html

**Comment by olivere** [comment]
Sure, I love PRs. Would really appreciate if you'd be willing to contribute some of your time. :-)

There's already official repositories for the X-Pack plugins which we can use for reference, e.g. [`elasticsearch-x-pack-ruby`](https://github.com/elastic/elasticsearch-x-pack-ruby).

It would be super interesting if they would have published the REST API spec for watcher / X-Pack publically, like they do for [the Elasticsearch core APIs](https://github.com/elastic/elasticsearch/tree/master/rest-api-spec). I see them referenced in the integration tests of the official clients, but [no answer yet if they are public or not](https://discuss.elastic.co/t/rest-api-spec-for-watcher-shield/46191). I will ask my contacts at Elastic. If we had those API specs, we could generate the bulk of the services with the generator in the [`generate-api` branch](https://github.com/olivere/elastic/tree/generate-api/generator). Service generation wouldn't be completely automated though.

Furthermore, I think we should do the work in the `github.com/olivere/elastic/watcher` package.

What do you think?

**Comment by kmulvey** [comment]
ok, ill have a look at that generate branch and try to start a spec file in lieu of an official one.

**Comment by olivere** [comment]
I've also started a topic on Elastic Discuss site: https://discuss.elastic.co/t/rest-api-spec-available-for-x-pack/80037

**Comment by olivere** [comment]
Ha! Specs (a bit out of date) can be found e.g. here: https://github.com/elastic/elasticsearch-net/tree/5.x/src/CodeGeneration/ApiGenerator/RestSpecification/XPack

**Comment by kmulvey** [comment]
ive started playing with the generator using the INFO api since its the simplest. Still work in progress... 

https://github.com/kmulvey/elastic/commit/f0731432207cbf07862bb48772ea05ad739aaded

**Comment by olivere** [comment]
Yes. The generator needs some care; it's a bit outdated and you need to manually fix more things than necessary. But it's still easier than writing all that code yourself.

The specs from the elasticsearch-net client should be at least a good starter. However, that's probably just half of the work. The other is creating a DSL to build the body. But we could publish a first version with xpack support without builders for the body.

**Comment by Zyqsempai** [comment]
Hi there, so i checked REST specification from  .Net Repo, generated as a test few endpoints, generator works as expected, not ideal, but it will be enough to create a backbone of the package.
I suggest to create a new branch (maybe elastic-xpack) and as Oliver mentioned above create new folder/package (xpack) at current time i have enough time to generate and fill up all the APi's one by one, so i will create merge requests into elastic-xpack and step by step we will complete xpack functionality, nearby i suppose will be Elasticsearch 6.3 release and we will just merge elastic-xpack branch into new release branch.

**Comment by olivere** [comment]
@Zyqsempai That sounds very good. I agree that we should work on it on a separate branch. I have created the [`xpack` branch](https://github.com/olivere/elastic/tree/xpack).

Maybe we should start with a simple API, e.g. [Info API](https://www.elastic.co/guide/en/elasticsearch/reference/current/info-api.html) to test how to best integrate xpack into Elastic. I'm not sure working in a separate folder will be possible without breaking the existing structure of Elastic. E.g. we need access to the `*Client` in each service, and it'll be available in `github.com/olivere/elastic` only. If we then extend `*Client` via the xpack services, we have an import cycle. We basically have three options here:

1. Wait for Elastic v7 which allows us to introduce a breaking change.
2. Restructure Elastic v6 which might be impossible without a breaking change.
3. Keep the current structure and simply add the xpack APIs (e.g. `xpack_info.go`, `xpack_security.go`) to the existing `elastic` package, just like the other APIs.

What do you think?

**Comment by Zyqsempai** [comment]
@olivere 
I think the third option is the simplest and the better one, because we will have working functionality as fast as possible and will do it without breaking compatibility, also for the Elastic users it will be clear and familiar, just another one feature.
And for ElasticSearch 7 release we can leave option one, in that case, we will have to only restructure and decomposite project.
I already started to play around with Watcher API, maybe tomorrow I will present it to you and we will discuss it more concrete.

**Comment by olivere** [comment]
@Zyqsempai Yes, I agree. We should start with method 3. Elastic is quite old and you can see its age in a lot of places. It started before we had best practices for working with packages etc.

I hope to find a chance in a major new version, such as v7, to restructure the library a bit. But I've seen way to many projects which change their structure without a necessity between minor versions, breaking people's code and wasting hours and hours of developer's time: I simply don't want that, and it has a high priority for me. You should simply be able to update and everything should continue to work.

**Comment by Zyqsempai** [comment]
@olivere Totaly agree with you.
By the way, i created first PR [https://github.com/olivere/elastic/pull/733](url)
In comments i will describe main points and problems i faced.

**Comment by olivere** [comment]
@Zyqsempai Heya! Long time no talk :-) Do you still think we can merge this in any of the next releases?
