### ISSUE TITLE
Accessing HTTP response headers when a request fail

### ISSUE THREAD

**Issue by danielfireman** [olivere/elastic#477]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

Good morning!

I am needing to check the HTTP response headers when a request fails. I am totally keen to do the work and thinking of mimicking what we what we already have for [status codes](https://github.com/olivere/elastic/blob/1368b91516f39100baf5e23a02ae9f090c0d90e2/errors.go#L55).

What do you think? I am going to send the PR as soon as I have an OK. Thanks!

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[X] elastic.v5 (for Elasticsearch 5.x)

**Comment by olivere** [comment]
Mooorning. :-)

Maybe [`Retrier`](https://github.com/olivere/elastic/wiki/Retrier-and-Backoff) already helps in that case?

I'm thinking of changing the response of the `Do` methods in the services from

```go
Do(...) (*SomeResponse, error)
```

to

```go
Do(...) (*SomeResponse, *http.Response, error)
```

in the next major version of Elastic. However, that's a breaking change, so I must delay that for 6.0.

**Comment by danielfireman** [comment]
Hi Oliver, thanks a lot for the quick response.

My goal is not to change the response, but to inspect its internals and take actions based on it. An example (using a version of elastic with the modification I proposed) can be found [here](https://github.com/danielfireman/esperf/blob/master/main.go#L205-L227). That said, I believe the Retrier does the job in this case case (although the code would be less clean). Thanks a lot for the suggestion.

About changing the `Do` method, what do you think of adding a new method? Suggesting that because the new information returned could be advanced for most users of the library, so maybe most people would be better of not even having contact with it. Furthermore, it prevents you from breaking the interface.

```go
DoInspect(...) (*SomeResponse, error, *http.Response, *http.Request)
```

I am terrible with method names. The name is actually not part of the suggestion :)

**Comment by danielfireman** [comment]
Thanks a lot for your suggestion, @olivere ! I am using the Retrier for collecting HTTP response headers. Closing this issue because the no modifications are strictly needed.

Let me know if you're keen to move forward on implementing the `DoInspect` (or alike). I am happy to send you a PR.

**Comment by olivere** [comment]
@danielfireman Sorry for the lack of responsiveness, and thanks for your support in making Elastic better.

We of course could add something like `DoWithResponse`. It's easy to add new things. The API surface gets bigger over time. People use it, people rely on it. The real problem is: How and when do you get rid of something without annoying your users then? So I let it sink in for a while and tend to think twice before adding things. I'm not quite convinced yet ;-)

**Comment by danielfireman** [comment]
Totally! Sounds great.
