### ISSUE TITLE
Infinite Retries

### ISSUE THREAD

**Issue by kylebrandt** [olivere/elastic#48]
Hi @olivere. I had a problem where my elastic cluster went down, and it *seemed* like my elastic queries kept retrying themselves without stopping. I see something about retries in one of the latest commits. Was this a known issue with this module - or should I be looking at my usage of the library?

Currently using an older vendored version.

**Comment by olivere** [comment]
Hi @kylebrandt! Hmm... in version 1 there shouldn't be any retries in Elastic. If you have two nodes, it always sticks to the first until that one goes down. Then it uses the second as a fallback. If both are down, you should simply get an `ErrNoClient` error. At least that's what happened when my cluster fell apart last time ;-)

In version 2, it does round-robin by default. If one node goes down, it is marked as dead and will not be used unless a healthcheck sets it alive again. If a request fails, it can be automatically retried several times (if configured like that via `SetMaxRetries`). If everything fails, it will even try to sniff the cluster to find if new nodes have joined the cluster recently and can be used. Of course, even with v2 you can still get `ErrNoClient`. I invested some time to [write this all down in the wiki](https://github.com/olivere/elastic/wiki).

**Comment by kylebrandt** [comment]
I was actually hitting a VIP that moves around various nodes of the elastic cluster. So this seems to be wrong way to do things for v1 from what you are describing - and I see now that I can list multiple clients for NewClient even in v1. So I'll try that.

Can you advise on how to Handle ErrNoClient in v1? Do I need to destroy the client and create a new one when this happens?

**Comment by olivere** [comment]
Unfortunately, in v1 the list of URLs in a Client is static in the sense that Elastic will only use the URLs provided on instantiation (it doesn't find new nodes in the cluster for you; only v2 will). If all those nodes go away, well...

However, even v2 needs at least "some" URLs to sniff the cluster. It will start with the ones provided at startup, and after that will use all those found in the sniffing process. Sniffing is done via the [Nodes Info API](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info). Use the `/_nodes/http` endpoint and parse the URLs. The offical ES clients also use this method. However, if your admins are cautiously adding new nodes and shut down old nodes, v2 will happily pick up the new nodes, clear up the old, and continue.

So, back to your question: I think in v1 you have to "sniff" the cluster yourself, halt the world, exchange the client, and then go on. If you need to stick to v1, maybe you can backport some of the stuff you'll find in `client.go` of v2.

BTW: There's a `cluster-test` subdirectory in v2 which I used to test the process of nodes going up and down. Maybe you'll find that helpful.

**Comment by kylebrandt** [comment]
Oh wait... I think I'm being stupid. v1 and v2 applies to this library, not elastic? If that is the case, don't see any reason I can't move to v2

**Comment by olivere** [comment]
:-)  Sorry for the confusion. With Elastic, I meant this library. Otherwise, I usually write ES or Elasticsearch. So sure, try v2 if you can. You're welcome :-)

Elasticsearch 2.0 will unfortunately bring some [breaking changes](http://www.elasticsearch.org/guide/en/elasticsearch/reference/master/breaking-changes-2.0.html) ...

**Comment by kylebrandt** [comment]
And now for something completely different....

What call gives me a list of indexes in the cluster? I can't seem to find the combination of calls in the docs.

**Comment by olivere** [comment]
On the command line, it's the keys in `curl 'localhost:9200/_all?pretty=1'` (see [here](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/indices-get-index.html)).

Actually, I think nobody ever asked for that in Elastic. I can add it if you need it now. It'll only take a few minutes.

**Comment by kylebrandt** [comment]
Ya, I have been making the http request in the past. But now that we have this fancy client, would be nice to do it via the client that more HA capability.

**Comment by olivere** [comment]
If you're on 1.4.4, you can check out master. [This commit](https://github.com/olivere/elastic/commit/afe7b6f97875f4da7fab538bcffb286c01359a05) adds the [Index GET API](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/indices-get-index.html).

However, it fails on 1.4.2 and 1.3.9, so I will need some time to investigate. I suppose they've changed the API somehow.

Anyway, feel free to create a new issue if something (else) goes wrong.

**Comment by olivere** [comment]
If you're on 1.4+, you can use the `IndexGet` services. If you're on an earlier version, you need to use the `IndexGetSettings` API. In both cases, the keys in the returned map are the index names available in your cluster.

Or you simply use the shortcut method for this: `IndexNames() (string[], error)`.

**Comment by kylebrandt** [comment]
I'm on 1.4+, and that IndexNames() method was nice and convenient - was able to remove a chunk of code. Thanks again @olivere !

**Comment by kylebrandt** [comment]
Hi @olivere I'm getting no Elasticsearch node available. Maybe I'm doing something wrong. I believe it comes from https://github.com/bosun-monitor/bosun/blob/master/cmd/bosun/expr/funcs.go at line 1065.

**Comment by olivere** [comment]
Are you running ES in a Docker container? Then maybe you should disable sniffing and see if it get's you there.

BTW: You should really cache the ES client instance. It's like *sql.DB. Start your app, create a client, and use it everywhere.

**Comment by kylebrandt** [comment]
No docker. Re BTW: You should really cache the ES client instance. It's
like *sql.DB. Start your app, create a client, and use it everywhere. I'll
get on the ASAP.

**Comment by kylebrandt** [comment]
Regarding using the same client, I shouldn't have have to do any "recreate
client on err" logic as of v2 right? That is all automagic from the library?

**Comment by olivere** [comment]
As long as the ES cluster is "stable", then: No--recreating a client is not necessary.

What do I mean by "stable"? You must not remove all nodes from a cluster and replace them by some other nodes. Elastic needs some time to pick up changes in the cluster, as nodes go up and down.

**Comment by kylebrandt** [comment]
@olivere What if all nodes fail (including the ones in the call to setURL, but come back up eventually?). Will the library recover from that or give up eventually (maybe that is retries?)

**Comment by olivere** [comment]
Yes, it should recover. Elastic will try the URLs of all nodes that you initially supplied via SetURL and those that were available in the last sniffing process. There might be edge cases, e.g. having an "eventually connected" cluster is an edge case by all means... if you're really in that situation, you must cope with it on the application level.

Regardint my previous statement, I think I wasn't clear. You CAN remove all nodes from a cluster and replace them by other nodes. You just need to give Elastic time to pick up the changes.

**Comment by olivere** [comment]
See [here](https://github.com/olivere/elastic/blob/master/client.go#L481).
