### ISSUE TITLE
Size doesn't return the correct number of results

### ISSUE THREAD

**Issue by tiancheng0307** [olivere/elastic#480]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[X] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
With this query, I get 0 results:
s.elasticsearchClient.Search().Index("service_alias").Query(geoMatchQuery).Do()  

With this query, I get 1 result:
s.elasticsearchClient.Search().Index("service_alias").Query(geoMatchQuery).Size(10).Do() 

With this query, I get 2 results:
s.elasticsearchClient.Search().Index("service_alias").Query(geoMatchQuery).Size(30).Do()                   

With this query, I get 4 results:
s.elasticsearchClient.Search().Index("service_alias").Query(geoMatchQuery).Size(100).Do() 

There are over 3000+ documents that match this query.

### Please describe the actual behavior
Should return the exact number of results as requested.

It seems that the size parameter is for the number of fields returned (not number of documents).

**Comment by olivere** [comment]
Would you please enable the trace logger and send me the output. It should tell us exactly what is sent to and received from Elasticsearch.

**Comment by tiancheng0307** [comment]
The size does return the correct data. We have some filtering logic afterwards that are triggered. sorry about that; i will close this issue.
