### ISSUE TITLE
SearchResult.Shards was removed - this is not documented in the changelog

### ISSUE THREAD

**Issue by ayashjorden** [olivere/elastic#482]
### Which version of Elastic are you using?
[ ] elastic.v2 (for Elasticsearch 1.x)
[X] elastic.v3 (for Elasticsearch 2.x)
[X] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
I'm looking into adding ES-5 support for [Bosun](https://github.com/bosun-monitor/bosun). upgrading from olivere/elastic.v3 to v5.
[SearchResult.Shards element was used to determine if the query succeeded](https://github.com/bosun-monitor/bosun/blob/master/cmd/bosun/expr/elastic.go#L283). how would it look in elastic.v5 ?

### Please describe the actual behavior
SearchResult.Shards element was removed.

Thanks in advance,
Jorden

**Comment by olivere** [comment]
Oops, okay. That shouldn't have happened. I'll add it again.

However, I think you need to take a different approach to determine an error condition. If there is no error returned from the `Do(...)`, there is no error (at least no hard error). Besides that, you can run into different kinds of problems. E.g. your search query could time out, or Elasticsearch might return a detailed error description. Both of which are part of the search response (if `err == nil`). See [here](https://github.com/olivere/elastic/blob/release-branch.v5/search.go#L403-L404).

**Comment by olivere** [comment]
5.0.30 is just running on Travis and released in a few minutes.

**Comment by kylebrandt** [comment]
Reason is in https://github.com/olivere/elastic/pull/373 (needed so I can support specifying a range of indices where some are missing.

**Comment by olivere** [comment]
@kylebrandt Ah, I see. Got it. Well, now you can access it again.
