### ISSUE TITLE
Source filtering for queries

### ISSUE THREAD

**Issue by jgoodall** [olivere/elastic#483]
The following curl query works fine (using [Source filtering](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-source-filtering.html)):

```
POST /index/type/_search
{
    "size": 10, 
    "_source": ["*IP"],
   "query": { "match_all": {}
}
```

However, I cant figure out how to do the equivalent from the docs with `elastic`. The fields are not stored separately, so the `StoredFields` method does not work. I can limit the data returned with the source using `FetchSourceContext`, but then I still have to Unmarshal the source. 

Am I missing how to do the source filtering in a way that would allow easy access to the fields like the `StoredFields` method (a map)? Or is that not possible?

**Comment by olivere** [comment]
Hmm... AFAIR source filtering only filters the parts returned from the `_source` field. So using `FetchSourceContext` is the way to go ([some examples here](https://github.com/olivere/elastic/blob/release-branch.v5/search_source_test.go#L66-L101)). You need to Unmarshal the hit as you'd have to without source filtering.

There has been a [breaking change in 5.0](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/breaking_50_search_changes.html#_literal_fields_literal_parameter) that, besides renaming `fields` to `stored_fields`, changed behavior of source filtering to no longer extract and return fields from `_source`.
