### ISSUE TITLE
Interval in Histogram Aggregation limited to integers?

### ISSUE THREAD

**Issue by jgoodall** [olivere/elastic#485]
The `Interval` field for histogram aggregations is currently limited to integers. The elasticsearch documentation says only that 'the interval must be a positive decimal' (https://www.elastic.co/guide/en/elasticsearch/reference/5.2/search-aggregations-bucket-histogram-aggregation.html), and using the HTTP API, floats work fine.

Is there a reason that `interval` has to be an int? Would it work to make it an `interface` so it could take either an int or float?

**Comment by olivere** [comment]
No, there's no reason I can think of. Maybe it was an integer in earlier versions. I just looked it up in the Java source, and it's a `double` there.

So we could change it to `interface{}` to keep existing users happy, or change it to `float64` to reflect the type in the Java source. I tend to change it to `float64`. Even if it breaks clients, it's a straightforward and simple change.

What do you think?

**Comment by jgoodall** [comment]
changing to `float64` may change existing clients, but it also is the most straightforward way to change and also be in line with the Java client. I say yes.

**Comment by olivere** [comment]
This change will be released in 5.0.32. Notice that some other fields in the histogram aggregation are also based on `float64` (e.g. min/max bounds and offset). So I changed them from `int64` to `float64` as well.

Yes, it's a breaking change. But it's easily changeable by users of elastic.
