### ISSUE TITLE
Matching a String array with an Element

### ISSUE THREAD

**Issue by dinilv** [olivere/elastic#490]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)

GET /mo_tracker/_search

{
  "took": 2,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_index": "mo_tracker",
        "_type": "msisdn",
        "_id": "661234567890",
        "_score": 1,
        "_source": {
          "msisdn": "661234567890",
          "blocked": "false",
          "offerIDs": [
            "251",
            "301"
          ],
          "updatedAt": "2017-03-24T10:12:29.496510445Z"
        }
      }
    ]
  }
}

Below query is not  for matching string array for an item is not working ?

 
offerFilter := elastic.NewTermQuery("offerIDs", offerID)
	offerBoolFilter := elastic.NewBoolQuery().Should(offerFilter)

	results, err := ESClient.Search().Index().Index(constants.MOTracker).Type(constants.MSISDN).Query(offerBoolFilter).Pretty(false).Do(context.Background())

### Any steps to reproduce the behavior?

all the documents are getting matched irrespective of filter query ?

**Comment by olivere** [comment]
Maybe you need a TermsQuery, not a TermQuery? Notice the plural s.

**Comment by dinilv** [comment]
Thanks Olivere, i got the issue..
