### ISSUE TITLE
enable/disable logging on the fly using env variable

### ISSUE THREAD

**Issue by kenng** [olivere/elastic#492]
feature suggestion: enable/disable logging on the fly using env variable

### Which version of Elastic are you using?
elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
hoping to be able to enable the log on the fly by setting env variable

### Please describe the actual behavior
currently, the log handler is passed during initialization. Hard to turn it on and off at a time later.
if the tracelog is set, response will be printed out as well resulted in very verbose output. 

### Any steps to reproduce the behavior?
not a bug, but a feature request

### this is one of the simple suggestion of purposed code
```go
func (c *Client) dumpRequest(r *http.Request) {
	// fmt.Println("os.Getenv(ES_LOG_INFO) = " + os.Getenv("ES_LOG_INFO"))
	if c.tracelog != nil {
		out, err := httputil.DumpRequestOut(r, true)
		if err == nil {
			c.tracef("%s\n", string(out))
		}
	} else if os.Getenv("ES_LOG_INFO") == "1" {
		out, err := httputil.DumpRequestOut(r, true)
		if err == nil {
			os.Stdout.Write(out)
		}
	}
}

func (c *Client) dumpResponse(resp *http.Response) {
	if c.tracelog != nil {
		out, err := httputil.DumpResponse(resp, true)
		if err == nil {
			c.tracef("%s\n", string(out))
		}
	} else if os.Getenv("ES_LOG_RES") == "1" {
		out, err := httputil.DumpResponse(resp, true)
		if err == nil {
			os.Stdout.Write(out)
		}
	}
}
```
- at anytime, we can setup a route to enable or disable the environment variable using
```go
os.Setenv("ES_LOG_INFO", "1")
```

**Comment by olivere** [comment]
Thanks for sharing your ideas. I tend to refrain from such logic because it makes things more complex.

But you can easily implement such logic yourself by wrapping the existing logger. The [wiki](https://github.com/olivere/elastic/wiki/Logging) has an example of this.

HTH.

**Comment by kenng** [comment]
thanks for review, seem to be a better suggestion, will give it a try

**Comment by kenng** [comment]
@olivere just one thought about to make this more flexible, is it possible to set the clients' options after NewClient()? Currently this seem to be only possible during client creation.

**Comment by olivere** [comment]
@kenng No, that's not possible. I don't think I want to go down that route as it might get rather complex as, depending on what you change, the client needs a complete reconfiguration. E.g. if you changed the URLs to ES, the client cannot do anything but reconfigure itself from scratch. It'd be much easier to just setup a new client in that case.

**Comment by kenng** [comment]
@olivere understand where you coming from, and it is okay because this might not be critical, just some thought for optimization, if there is any slight possibility of change in the future ;)

the reason why I bring this up again is due to following scenario
- currently, info log only echo the summary of the request, not the request body. When we need to check/debug, we need to see the request body
- so we enable the trace log, using the wrapper as suggested, but toggle the output based on environment variable
```
func (logger wrapLogger) Printf(format string, vars ...interface{}) {
	myvar := iwcfg.EsEnabledTrace
	if os.Getenv(myvar) == "1" {
		/// print the trace...
	}
}
```
- however since we cannot set the c.tracelog from outside, we cannot prevent DumpRequestOut from being called each time.... that's why I raise this again and see if you have any suggestion about this
```
func (c *Client) dumpRequest(r *http.Request) {
	if c.tracelog != nil {
		out, err := httputil.DumpRequestOut(r, true)
		if err == nil {
			c.tracef("%s\n", string(out))
		}
	}
}
```

Appreciate your effort in maintaining this :)  just some feedback after using it. 
Unless we change the core of this code, but I think it would be still good to bring it up to you first and see if there will be any alternative way. 

Cheers

**Comment by olivere** [comment]
@kenng If you find tracelog/infolog to be unsuitable for your needs, you could simply turn them off and do your own request logging via a special [`http.Transport`](https://github.com/olivere/elastic/wiki/HttpTransport).

**Comment by kenng** [comment]
@olivere great stuff, looks like what we need! Thanks again!
