### ISSUE TITLE
Refactor Suggesters

### ISSUE THREAD

**Issue by olivere** [olivere/elastic#497]
Suggesters are not in line with Elasticsearch 5.x. The different suggesters return different options, and e.g. phrase suggesters use a `score` field for the score while completion suggesters use `_score`. We probably need to have different `Options` structs for the different suggesters.

See also #493

**Comment by sinnawat** [comment]
It's also had a problem with phrase suggesters => "highlighed" when I use ```
"highlight": {
          "post_tag": "<em>",
          "pre_tag": "</em>"
        }
```

**Comment by olivere** [comment]
@sinnawat I will look into this. Maybe you can write a test that illustrates the problem?

**Comment by sinnawat** [comment]
Quick write test

```
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"testing"

	elastic "gopkg.in/olivere/elastic.v5"
)

func TestSearchSuggest(t *testing.T) {
	// Connect
	client, err := elastic.NewClient(
		elastic.SetSniff(false),
		elastic.SetURL("http://localhost:9201"))
	if err != nil {
		fmt.Println(err)
	}

	// createIndex
	mapping := `{
			"settings":{
				"number_of_shards":1,
				"number_of_replicas":0
			},
			"mappings":{
				"tweet":{
					"properties":{
						"tags":{
							"type":"string"
						}
					}
				}
			}
		}`

	if isExists, _ := client.IndexExists("twitter").Do(context.Background()); !isExists {
		_, err := client.CreateIndex("twitter").BodyString(mapping).Do(context.Background())
		if err != nil {
			// Handle error
			panic(err)
		}
	}

	// Insert tweet
	for i := 0; i < 10; i++ {
		_, _ = client.Index().
			Index("twitter").
			Type("tweet").
			BodyString(`{"tags" : "cat"}`).
			Do(context.Background())
	}

	// Flush
	_, _ = client.Flush().Index("twitter").Do(context.Background())

	// Phrase Suggest Query
	field := "tags"
	suggesterQuery := elastic.NewPhraseSuggester("phrase-suggest").
		Text("cad").
		Field(field).
		Size(4).
		Confidence(0.7).
		MaxErrors(1).
		RealWordErrorLikelihood(1).
		CandidateGenerator(elastic.NewDirectCandidateGenerator(field).
			SuggestMode("always").
			MinWordLength(2)).
		Highlight("<em>", "</em>")

	// Search
	suggestResult, _ := client.Search().
		Index("twitter").
		Type("tweet").
		Query(elastic.NewMatchAllQuery()).
		Suggester(suggesterQuery).
		Do(context.Background())

	b, _ := json.MarshalIndent(suggestResult.Suggest, "", "  ")
	gotResult := string(b)
	expectedResult := `"phrase-suggest": [
      {
        "text": "cad",
        "offset": 0,
        "length": 4,
        "options": [
          {
            "text": "cat",
            "highlighted": "<em>cat</em>",
            "score": 0.10025937
          },
          {
            "text": "cad",
            "highlighted": "cad",
            "score": 0.02488786
          }
        ]
      }`

	if gotResult != expectedResult {
		t.Errorf("Not pass : result is  %s but should be %s", gotResult, expectedResult)
	}
}

```

**Comment by olivere** [comment]
@sinnawat Thanks a lot!

**Comment by olivere** [comment]
@sinnawat Hmm... I was just looking into this, and I'm not really sure what the problem is that you're targeting. Are you confused by the 

```
"highlighted": "\u003cem\u003ecat\u003c/em\u003e"
```

... instead of ...

```
"highlighted": "<em>cat</em>"
```

?

That is something the JSON serialization in Go does by default, and it's correct as it is.

When I run your code, I get something like this as the output, which looks okay by me:

```
{
		  "phrase-suggest": [
		    {
		      "text": "cad",
		      "offset": 0,
		      "length": 3,
		      "options": [
		        {
		          "text": "cat",
		          "_index": "",
		          "_type": "",
		          "_id": "",
		          "score": 0.83854145,
		          "highlighted": "\u003cem\u003ecat\u003c/em\u003e",
		          "collate_match": false,
		          "freq": 0,
		          "_source": null
		        },
		        {
		          "text": "cad",
		          "_index": "",
		          "_type": "",
		          "_id": "",
		          "score": 0.35296276,
		          "highlighted": "cad",
		          "collate_match": false,
		          "freq": 0,
		          "_source": null
		        }
		      ]
		    }
		  ]
		}
```


Can you please point me into the right direction?

**Comment by sinnawat** [comment]
@olivere  I didn't get that result. Maybe my version is outdate.

I need to fix by myself from

`type SearchSuggestionOption struct {
	Text   string           `json:"text"`
	Index  string           `json:"_index"`
	Type   string           `json:"_type"`
	Id     string           `json:"_id"`
	Score  float64          `json:"_score"`
	Source *json.RawMessage `json:"_source"`
`

to

`type SearchSuggestionOption struct {
	Text            string           `json:"text"`
	Index           string           `json:"_index"`
	Type            string           `json:"_type"`
	Id              string           `json:"_id"`
	Score           float64          `json:"_score"`
	PhraseScore     float64          `json:"score"`
	PhraseHighlight string           `json:"highlighted"`
	Source          *json.RawMessage `json:"_source"`
}
`

**Comment by olivere** [comment]
Hmm... I've been running this with elastic 6.1.0 (on ES 6.1.1). Here's the [main.go](https://gist.github.com/olivere/32ba859374dbc9c4eedd0c2e09ba62d4) and its output.

Same with elastic 5.0.59 (on ES 5.6.5): [main.go](https://gist.github.com/olivere/4452d41d52f88d4d6c1119ba2701fcf5) and its output.

BTW: Please update to a recent version. Your `SearchSuggestionOption` is out of date. I [looks like this](https://github.com/olivere/elastic/blob/release-branch.v5/search.go#L509-L521) in 5.0.59:

```
type SearchSuggestionOption struct {
	Text         string           `json:"text"`
	Index        string           `json:"_index"`
	Type         string           `json:"_type"`
	Id           string           `json:"_id"`
	Score        float64          `json:"score"`
	Highlighted  string           `json:"highlighted"`
	CollateMatch bool             `json:"collate_match"`
	Freq         int              `json:"freq"` // from TermSuggestion.Option in Java API
	Source       *json.RawMessage `json:"_source"`
}
```

Please post again on this issue if this still doesn't clear things up. Maybe I'm still missing something.
