### ISSUE TITLE
Unneeded(?) mutex lock in ExponentialBackoff

### ISSUE THREAD

**Issue by utrack** [olivere/elastic#499]
Hi!

I was skimming through the code and found an odd piece @ https://github.com/olivere/elastic/blob/v2.0.58/backoff.go#L89

I can't find any writes happening to `b` in this section. Either something was forgotten or we just don't need that mutex.

**Comment by olivere** [comment]
Yep. Looks like it got copied over from a previous version of `ExponentialBackoff` and could be removed.

**Comment by olivere** [comment]
This issue will be fixed in the next release of v2, v3, and v5.
