### ISSUE TITLE
TermsLookup is not implemented?

### ISSUE THREAD

**Issue by ww24** [olivere/elastic#500]
Does `search_queries_terms.go` not implement Terms Lookup?

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[x] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-terms-query.html#query-dsl-terms-lookup

### Please describe the actual behavior
TermsQuery struct does not have field `index`, `type`, `id`, `path`.

https://github.com/olivere/elastic/blob/v5.0.31/search_queries_terms.go

### Any steps to reproduce the behavior?

**Comment by olivere** [comment]
Yes, looks like it is missing the Terms lookup mechanism. I need to look over what the [Java code](https://github.com/elastic/elasticsearch/blob/ee802ad63c0f21d697a5095dd05dc6f94626ee4d/core/src/main/java/org/elasticsearch/index/query/TermsQueryBuilder.java) looks like for `TermsQuery`, and then add it to elastic.
