### ISSUE TITLE
Raise "mapping.total_fields.limit" from the api

### ISSUE THREAD

**Issue by DaBlitzStein** [olivere/elastic#504]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ x] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
Raise "mapping.total_fields.limit" from the api.

### Please describe the actual behavior
I can't find nothing about in the package.

### Any steps to reproduce the behavior?
Randomly create high volume indices.

A reference:
https://discuss.elastic.co/t/total-fields-limit-setting/53004/6

Thank you!

**Comment by olivere** [comment]
There is no DSL for creating a mapping or a template. You have to pass the mapping either as a serializable JSON struct or a string via `BodyJson` or `BodyString` (see [here](https://github.com/olivere/elastic/blob/release-branch.v5/indices_put_template.go#L82-L92)).
