### ISSUE TITLE
BulkProcessor Error Handling

### ISSUE THREAD

**Issue by ththvseo** [olivere/elastic#505]
### Which version of Elastic are you using?
[ ] elastic.v5 (for Elasticsearch 5.x)

---

it seems to me that either the code or documentation (or both) for error handling in the bulk procesor could use some improvement.

documentation here:
https://github.com/olivere/elastic/wiki/BulkProcessor#error-handling
code around here:
https://github.com/olivere/elastic/blob/release-branch.v5/bulk_processor.go#L499

most importantly, the built-in retry mechanism appears to only apply to the whole bulk request as such
(which is not explicitly mentioned in the documentation).
from what i saw so far, most errors occur in sub-requests are not handled by this.
thus, one has to implement an `After()` function that will iterate over the status of the invidudual sub-requests in the response and re-queue those requests that failed.

imho:
 * the documentation should be more explicit about this
 * the BulkProcessor should be able to handle this internally, or at least a convenience function should be provided.

**Comment by ththvseo** [comment]
i see that there is `BulkResponse.Failed()`:
https://github.com/olivere/elastic/blob/release-branch.v5/bulk.go#L367
so that should be mentioned in the documentation.

**Comment by olivere** [comment]
You are correct in that the retry is on the request level. That's how Elasticsearch works. Elastic really is just a small wrapper around the HTTP endpoints. It doesn't try to be "intelligent" by offering you a different API than the one ES has to offer. From my experience, that will shoot back eventually. So, yes, I agree the documentation should probably be better. However, I do not agree that `BulkProcessor` should try to do retries on the document level.

If you think the Wiki could be improved (and yes, it can!), feel free to edit the Wiki accordingly. There's already some paragraphs about [error handling in `BulkProcessor`](https://github.com/olivere/elastic/wiki/BulkProcessor#error-handling) in the Wiki (plus a big fat warning about the "promise" of `BulkProcessor`).

Finally, if you need full control over the indexing process, maybe `BulkProcessor` is not for you. You can easily build your own indexer with `BulkService`. There's ongoing work in building a streaming bulk-indexer which I didn't have the time to complete yet.

**Comment by olivere** [comment]
There's a [recipe for doing bulk inserts](https://github.com/olivere/elastic/blob/release-branch.v5/recipes/bulk_insert/bulk_insert.go) here, just FYI.
