### ISSUE TITLE
TCP support for port 9300

### ISSUE THREAD

**Issue by ianomad** [olivere/elastic#513]
Elastic version: Elasticsearch 5.x

### Please describe the expected behavior
`elastic.NewClient(elastic.SetURL('127.0.0.1:9300'))`

### Please describe the actual behavior
Error: `panic: no Elasticsearch node available`

### Any steps to reproduce the behavior?
Yes, just try to connect via tcp port 9300

**Comment by olivere** [comment]
Elastic will only ever support the HTTP-based REST API which is available by default on port 9200.

The transport module is already marked as [deprecated](https://www.elastic.co/guide/en/cloud/current/java-transport.html), so you're not going to see clients using that protocol in the future.

**Comment by olivere** [comment]
@ianomad If you only want to connect to port 9300, you must do so with a valid URL. `"127.0.0.1:9300"` is not a valid URL, but `"http://127.0.0.1:9300"` is...

**Comment by ianomad** [comment]
thanks @olivere! makes sense
