### ISSUE TITLE
IgnoreUnmapped for Nested Queries

### ISSUE THREAD

**Issue by cforbes** [olivere/elastic#516]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ x ] elastic.v5 (for Elasticsearch 5.x)

Is there a way to set the ignore_unmapped option for nested queries? The option is referenced in the docs: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-nested-query.html

I see a similar option for sorting via SortInfo, but not for nested queries.

**Comment by olivere** [comment]
Thanks for reporting. The flag is missing in `NestedQuery`. I need to add it to that. A PR for that would be helpful.

**Comment by olivere** [comment]
Merged in [cec324](https://github.com/olivere/elastic/commit/cec324cc95fe1924ee3834acbbd7f8830864fd48).
