### ISSUE TITLE
Parse exeption against ES-5

### ISSUE THREAD

**Issue by ayashjorden** [olivere/elastic#519]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[X] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
Let Bosun query ES-5

### Please describe the actual behavior
Working on getting Bosun wot query ES-5, see [here](https://github.com/ayashjorden/bosun/tree/es_5_support)

Getting: `elastic: Error 400 (Bad Request): [terms] failed to parse field [size] [type=parsing_exception]`

`govendor` gives me a headache 

### Any steps to reproduce the behavior?
In Bosun code, change from `elastic.v3` to `elastic.v5`.

Appreciate any advice as I'm not a GO developer,

**Comment by olivere** [comment]
Puh. There's too much information missing that I can resolve this. Can you somehow create a reproducible test I could run to reproduce the underlying problem?

**Comment by ayashjorden** [comment]
Found the issue,
When using Terms aggragation, 0 (zero) can no longer be used as replacement for int.MAX_VALUE. see [here](https://github.com/elastic/elasticsearch/issues/22136).

Need to figure out a solution.

J

**Comment by MyZhang0826** [comment]
@ayashjorden  do you solve this problem?
