### ISSUE TITLE
NewBulkIndexRequest with document string

### ISSUE THREAD

**Issue by jfinnson** [olivere/elastic#521]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[X] elastic.v5 (for Elasticsearch 5.x)

THIS IS MORE OF A FEATURE REQUEST OR CLARIFICATION
(Please let me know if there is a more suitable medium for this)

You can manually index a document via struct or string (https://github.com/olivere/elastic/wiki/Index).

However for NewBulkIndexRequest it only accepts documents as structs, not strings?

**Comment by olivere** [comment]
You can use `string`, `*string`, `json.RawMessage` etc. [Here's the code](https://github.com/olivere/elastic/blob/release-branch.v5/bulk_index_request.go#L202-L221) for `BulkIndexRequest`.
