### ISSUE TITLE
how to update more filed？

### ISSUE THREAD

**Issue by guoxijun** [olivere/elastic#524]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?
[ ] elastic.v5 (for Elasticsearch 5.x)

Script(NewScript("ctx._source.tags += tag").Params(map[string]interface{}{"tag": "blue"}).Lang("groovy"))
the code can only update the filed “tags”，if i want update two filed，how to coding？

**Comment by olivere** [comment]
Feel free to look up the [Update API documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html). In your case, [updating via a partial document](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html#_updates_with_a_partial_document) might be the solution.

Sometimes, the tests are also quite helpful to get used to the Go-like syntax, [`update_test.go`](https://github.com/olivere/elastic/blob/release-branch.v5/update_test.go) in this case.
