### ISSUE TITLE
Deprecated prefix syntax

### ISSUE THREAD

**Issue by alehano** [olivere/elastic#526]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ x] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
No errors

### Please describe the actual behavior
Deprecated syntax warning in logs:
```Deprecated field [prefix] used, expected [value] instead```

### Any steps to reproduce the behavior?
Do NewPrefixQuery query:
```
q := elastic.NewBoolQuery()
q = q.Should(elastic.NewPrefixQuery("City", query))
```

Query produces something like this:
```
{ "query": {
   "bool":{
      "should":[
         {
            "prefix":{
               "City":{
                  "prefix":"а"
               }
            }
         }
      ]
   }
}
}
```

Instead of 

```
{ "query": {
   "bool":{
      "should":[
         {
            "prefix":{
               "City":{
                  "value":"а"
               }
            }
         }
      ]
   }
}
}
```

As well same issue in match_phrase_prefix

Pull request provided https://github.com/olivere/elastic/pull/527

**Comment by olivere** [comment]
Should be fixed in 5.0.38.
