### ISSUE TITLE
Size(100000) failed

### ISSUE THREAD

**Issue by jinleileiking** [olivere/elastic#534]
`elastic: Error 500 (Internal Server Error): all shards failed [type=search_phase_execution_exception]`

Size(10000) ok

**Comment by wedneyyuri** [comment]
It's the expected elasticsearch behavior, quoting from elasticsearch docs: 
> Note that from + size can not be more than the index.max_result_window index setting which defaults to 10,000. See the Scroll or Search After API for more efficient ways to do deep scrolling.
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html

See https://github.com/olivere/elastic/wiki/ScrollParallel for a best solution.

**Comment by olivere** [comment]
Thanks @wedneyyuri

**Comment by jinleileiking** [comment]
Thanks.
