### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by alehano** [olivere/elastic#535]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ X] elastic.v5 (for Elasticsearch 5.x)

Possible memory leak at https://github.com/olivere/elastic/blob/release-branch.v5/client.go#L984
or at least unexpected behaviour.

**Comment by olivere** [comment]
Why do you think this is a memory leak?

**Comment by alehano** [comment]
Sorry, my mistake. It's not a memory leak, but in case of many connections defer will called in the end for all connections, instead of for each one. You have to call close() in the end of select statement.

**Comment by olivere** [comment]
The number of connections is basically the number of ES nodes that Elastic is connected to. That'll be a few. I agree that the code could be more explicit, but I don't see this as a serious problem. Am I missing something?

**Comment by alehano** [comment]
Ok, agreed, not a big problem.

**Comment by olivere** [comment]
Still. Thanks for taking a deeper look. 👍
