### ISSUE TITLE
Get all the Index names in the server?

### ISSUE THREAD

**Issue by wgwi** [olivere/elastic#536]
### Which version of Elastic are you using?
elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
How could I get all the index's name in the elasticserver?
a command will do the job, curl 'localhost:9200/_aliases?pretty=true'
but how to translate the command to the code?

**Comment by olivere** [comment]
There's a helper for that in the client called [`IndexNames`](https://github.com/olivere/elastic/blob/release-branch.v5/client.go#L1674-L1685):

There's also a [Wiki page](https://github.com/olivere/elastic/wiki/IndexNames) explaining just that.

**Comment by wgwi** [comment]
Thanks!
