### ISSUE TITLE
ReIndex function cause segmentation violation

### ISSUE THREAD

**Issue by wgwi** [olivere/elastic#537]
### Which version of Elastic are you using?
elastic.v5 (for Elasticsearch 5.x)

### Please describe the actual behavior
curl works: curl -XPOST http://localhost:9200/_reindex -d '...',
while as I try to Reindex function like this:
```
_, err = client.Reindex(i_name, target).Do()
	if err != nil {
		ERROR(err)
		return err
	} else {
		INFO("reIndex done.")
	}
```
a segmentation violation break out each time:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x124b19a]

goroutine 1 [running]:
gopkg.in/olivere/elastic%2ev3.(*ScanCursor).Next(0x0, 0xc42015d080, 0x0, 0x1466d88)
	/Users/robert/.gvm/pkgsets/go1.8.3/global/src/gopkg.in/olivere/elastic.v3/scan.go:334 +0x3a
gopkg.in/olivere/elastic%2ev3.(*Reindexer).Do(0xc42001c600, 0xc4200fd2a0, 0xf, 0xc42015eae0)
	/Users/robert/.gvm/pkgsets/go1.8.3/global/src/gopkg.in/olivere/elastic.v3/reindexer.go:204 +0x2e6
main.doReIndex(0xc4200e8000, 0xc4200fd2a0, 0xf, 0xc42013e600, 0x5b8, 0x5b8, 0x0)
	/Users/robert/workspace/elasticsearch/fixscheme/fixscheme.go:77 +0x25f
main.main()
	/Users/robert/workspace/elasticsearch/fixscheme/fixscheme.go:130 +0x385
```

**Comment by olivere** [comment]
Can you post a working code example so that I can reproduce. It seems that one of your variables is `nil`, e.g. the `client` or the `ScanService`.

**Comment by wgwi** [comment]
ok, as you wish.
```
package main

import (
	"errors"
	"flag"
	"fmt"
	"io/ioutil"
	"os"
	"time"

	log "github.com/Sirupsen/logrus"
	"gopkg.in/olivere/elastic.v3"
)

const TimeFormat = "2006-01-02 15:04:05"
const TimeLayout = "02/Jan/2006:15:04:05 -0700"

func FATAL(err error) {
	if err != nil {
		log.WithField("time", time.Now().Format(TimeFormat)).Fatal(err)
	}
}

func INFO(info string) {
	log.WithField("time", time.Now().Format(TimeFormat)).Info(info)
}

func WARN(info string) {
	log.WithField("time", time.Now().Format(TimeFormat)).Warn(info)
}

func ERROR(err error) {
	log.WithField("time", time.Now().Format(TimeFormat)).Error(err)
}

// create index if not exist, and apply the scheme to the index
func createIndexWithLogsIfDoesNotExist(client *elastic.Client, indexName string, indexMapping string) error {
	exists, err := client.IndexExists(indexName).Do()
	if err != nil {
		return err
	}
	if exists {
		return nil
	}
	res, err := client.CreateIndex(indexName).Body(indexMapping).Do()
	if err != nil {
		return err
	}
	if !res.Acknowledged {
		return errors.New("CreateIndex was not acknowledged. Check that timeout value is correct.")
	}
	return nil
}

func getNextDay() string {
	k := time.Now()
	d, _ := time.ParseDuration("24h")
	k = k.Add(d)
	return fmt.Sprintf("logs-%d.%02d.%02d", k.Year(), k.Month(), k.Day())
}

func getToday() string {
	k := time.Now()
	return fmt.Sprintf("logs-%d.%02d.%02d", k.Year(), k.Month(), k.Day())
}

func doReIndex(client *elastic.Client, i_name string, i_mapping string) error {
	target := i_name + ".i"
	t := fmt.Sprintf("create %s based on %s", target, i_name)
	INFO(t)
	err := createIndexWithLogsIfDoesNotExist(client, target, i_mapping)
	if err != nil {
		ERROR(err)
		return err
	}
	INFO("reIndexing now...")
	_, err = client.Reindex(i_name, target).Do()
	if err != nil {
		ERROR(err)
		return err
	} else {
		INFO("reIndex done.")
	}
	t = fmt.Sprintf("Delete index %s...", i_name)
	_, err = client.DeleteIndex(i_name).Do()
	if err != nil {
		ERROR(err)
		return err
	} else {
		INFO("Deleted")
	}
	return nil
}

// step 1, check use flags to check input valide
func main() {
	remoteUrl := flag.String("s", "http://localhost:9200", "Remote elasticsearch URL")
	schemeFile := flag.String("f", "", "Specify the scheme File.")
	flag.Parse()
	if len(os.Args) < 2 {
		flag.PrintDefaults()
		INFO("Program stopped...")
		os.Exit(1)
	}

	INFO("Program running...")

	// read scheme from config
	schemeDetail, err := ioutil.ReadFile(*schemeFile)
	FATAL(err)

	// open remote elasticsearch server
	client, err := elastic.NewSimpleClient(elastic.SetURL(*remoteUrl))
	FATAL(err)

	res, err := client.IndexNames()
	FATAL(err)
	if len(res) == 0 {
		INFO("None hit. Programming Stopped.")
		os.Exit(0)
	}

	next_day := getNextDay()
	this_day := getToday()
	for _, v := range res {
		if v[:4] != "logs" {
			continue
		} else {
			if v != next_day && v != this_day {
				doReIndex(client, v, string(schemeDetail))
			}
		}
	}

	INFO("Programming Stopped.")
}
```

**Comment by olivere** [comment]
I suppose there's an error in scanning the input index. I just [added a check](https://github.com/olivere/elastic/commit/522ba3c15bb8b0f669846bfadb35b1bc7dfd6ec7) that returns an error if the scan fails. Maybe you can check with that code again and report the error message.

But there's another thing you could do: The `Reindexer` service comes from the early days of Elasticsearch when it didn't have its own reindexing process. Starting at [2.3](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/docs-reindex.html), Elasticsearch has its own Reindex API. You can access that API via `client.ReindexTask()` (instead of `client.Reindex(...)`. See [`reindex_test.go`](https://github.com/olivere/elastic/blob/release-branch.v3/reindex_test.go) for example usage.

I encourage you to switch to the ES internal Reindex API as elastic.v5 has dropped its own reindexer (which you currently try to use).

**Comment by wgwi** [comment]
While as I am using Elasticsearch 5.4 version, the feedback is not as we except. so I comment bellow code:
reindex.go: 281
'''
	// Return operation response
	- ret := new(ReindexResponse)
	- if err := s.client.decoder.Decode(res.Body, ret); err != nil {
	-	return nil, err
	- }
	- return ret, nil
	+ fmt.Println(res.Body)
	+ return nil, nil
'''
the code run, and works. but each time I find there was some of the records (1000 around)un-transported to the the new index. so I changed to use "elasticsearch-py", even worse then Go version. As "elastic search-py" said Elasticsearch has reindex api of their own, So I use python requests package to invoke the _reindex Rest api, everything works fine. Thanks for help.

**Comment by olivere** [comment]
If you're using ES 5.x, importing `"gopkg.in/olivere/elastic.v3"` is wrong. Many many users successfully use reindexing, so I guess something's wrong on your side. Anyway. If you have any more questions, I'll open the issue again.

**Comment by jinmatt** [comment]
I'm getting the same error on 5.4.3
