### ISSUE TITLE
Should I import "gopkg.in/olivere/elastic.v3" for Elasticsearch 5.x

### ISSUE THREAD

**Issue by wgwi** [olivere/elastic#539]
### Which version of Elastic are you using?
[ ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the actual behavior
reindex api works not right.

**Comment by olivere** [comment]
No. See [here](https://olivere.github.io/elastic/), [here](https://github.com/olivere/elastic/blob/release-branch.v5/README.md#releases), or [here](https://github.com/olivere/elastic/wiki/Client#how-do-i-create-a-client).

Travis CI runs e.g. [this reindexing test](https://github.com/olivere/elastic/blob/release-branch.v5/reindex_test.go#L238-L291) whenever a new version comes along. It didn't fail recently.

Can you use that test to create the error you're receiving? Thank you.
