### ISSUE TITLE
Runtime Error using Elasticsearch 5.x

### ISSUE THREAD

**Issue by vivekmehtani** [olivere/elastic#540]
Hi,

I am always getting following runtime error whenever I execute any request on client

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12367b6]

goroutine 1 [running]:
gopkg.in/olivere/elastic%2ev5.(*Client).PerformRequest(0x0, 0x13f3de0, 0xc42007a188, 0x12d2de0, 0x3, 0xc420104278, 0x8, 0xc42004bd20, 0x126d720, 0xc420104280, ...)
	/Users/vivek1019/dev/rep/go-rep/src/gopkg.in/olivere/elastic.v5/client.go:1132 +0x86
gopkg.in/olivere/elastic%2ev5.(*IndicesCreateService).Do(0xc42004bf18, 0x13f3de0, 0xc42007a188, 0x0, 0x13efbe0, 0xc420108200)
	/Users/vivek1019/dev/rep/go-rep/src/gopkg.in/olivere/elastic.v5/indices_create.go:112 +0x34b
main.main()

Following is the code I am running

func main() {
	// Create a client
	ctx := context.Background()
	client, err := elastic.NewClient()
	if err != nil {
		// Handle error
	}
	_, err = client.CreateIndex("twitter").Do(ctx)

}

**Comment by olivere** [comment]
Can you check the error after creating the client:

```
if err != nil {
  log.Fatal(err)
}
```

Your code is ignoring the error and assuming that `client` is non-nil, which is not true in your case.

**Comment by vivekmehtani** [comment]
The following is the log 

no active connection found: no Elasticsearch node available

Although I can connect with http://127.0.0.1:9200

**Comment by olivere** [comment]
Did you already read [this Wiki page](https://github.com/olivere/elastic/wiki/Connection-Problems)? Are you using Docker? Maybe [disabling sniffing](https://github.com/olivere/elastic/wiki/Sniffing) works for you.

**Comment by vivekmehtani** [comment]
Thanks for the input sniffing helped.
