### ISSUE TITLE
[v5] UpdateResponse doesn't match the actual response json from elasticsearch.

### ISSUE THREAD

**Issue by yizha** [olivere/elastic#541]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[X] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
UpdateResponse struct should match the response from Elasticsearch v5.4, but it doesn't now.

UpdateResponse definition from update.go:

    // UpdateResponse is the result of updating a document in Elasticsearch.
    type UpdateResponse struct {
    	Index     string     `json:"_index"`
    	Type      string     `json:"_type"`
    	Id        string     `json:"_id"`
    	Version   int        `json:"_version"`
    	Created   bool       `json:"created"`
    	GetResult *GetResult `json:"get"`
    }

Actual response from Elasticsearch v5.4

    {
      "_index": "test",
      "_type": "test",
      "_id": "AVyP-TFcWnJHS5P8SKUK",
      "_version": 3,
      "result": "updated",
      "_shards": {
        "total": 2,
        "successful": 1,
        "failed": 0
      }
    }

### Please describe the actual behavior
UpdateResponse struct should look like:

    type UpdateResponse struct {
    	Index     string     `json:"_index"`
    	Type      string     `json:"_type"`
    	Id        string     `json:"_id"`
    	Version   int        `json:"_version"`
    	Result    string     `json:"result"`
    }

### Any steps to reproduce the behavior?
N/A.

**Comment by olivere** [comment]
Yes, that structure changed recently. I will change it to reflect the current version. Thanks.

**Comment by olivere** [comment]
The returned structures for Update and Delete in ES 5.4.1 are actually:

```
// UpdateResponse is the result of updating a document in Elasticsearch.
type UpdateResponse struct {
	Index         string      `json:"_index"`
	Type          string      `json:"_type"`
	Id            string      `json:"_id"`
	Version       int         `json:"_version"`
	Shards        *shardsInfo `json:"_shards"`
	Result        bool        `json:"string,omitempty"`
	ForcedRefresh bool        `json:"forced_refresh,omitempty"`
	GetResult     *GetResult  `json:"get,omitempty"`
}

// DeleteResponse is the outcome of running DeleteService.Do.
type DeleteResponse struct {
	Index         string      `json:"_index"`
	Type          string      `json:"_type"`
	Id            string      `json:"_id"`
	Version       int64       `json:"_version"`
	Shards        *shardsInfo `json:"_shards"`
	Result        bool        `json:"string,omitempty"`
	ForcedRefresh bool        `json:"forced_refresh,omitempty"`
	Found         bool        `json:"found"`
}
```

I will fix that in 5.0.41.

**Comment by olivere** [comment]
Ref: [e3b7c0](https://github.com/olivere/elastic/commit/e3b7c0ab6768b7a0076c8eefa32bdcce8cf2e5e1)

**Comment by claudiuolteanu** [comment]
Can you please detail why the `Result` field from `DeleteResponse` and `UpdateResponse` is represented as a `boolean`? From what I saw in the documentation of ES 5.4.1 it is represented as a `string` and its possible values are represented in this enum:
https://github.com/elastic/elasticsearch/blob/5.4/core/src/main/java/org/elasticsearch/action/DocWriteResponse.java#L64
Here you can find the implementation of `UpdateResponse` class which extends the `DocWriteResponse`:
https://github.com/elastic/elasticsearch/blob/v5.4.1/core/src/main/java/org/elasticsearch/action/update/UpdateResponse.java#L35

If we represent the `Result` field as `bool`, it will alway be `False`.

**Comment by olivere** [comment]
@claudiuolteanu It's clearly wrong for [`UpdateResponse`](https://github.com/olivere/elastic/blob/release-branch.v5/update.go#L316). But for [`DeleteResponse`](https://github.com/olivere/elastic/blob/release-branch.v5/delete.go#L217), it is correct.

Thanks for addressing this. Maybe you can write a PR?

Tracked in #599

**Comment by claudiuolteanu** [comment]
you please take a look at https://github.com/olivere/elastic/pull/600 ?

**Comment by olivere** [comment]
@claudiuolteanu I already did. However, I need to find some time first. I hope to work on Elastic this weekend, and include some of the outstanding PRs.

**Comment by claudiuolteanu** [comment]
Ok, thanks. If I can help you with something, please let me know.

Have a nice week
