### ISSUE TITLE
Connecting to default host whith enabled sniffing

### ISSUE THREAD

**Issue by RidgeA** [olivere/elastic#542]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[X] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
To connect to specified elasticsearch host

### Please describe the actual behavior
connecting to 127.0.0.1:9200

### Any steps to reproduce the behavior?
I'm trying to create connection to my es host like this:
`	
       client, err := elastic.NewClient(
		elastic.SetURL("http://myhosthame.elasticsearch"),
	)
`
but i am connecting to localhost es, instead of `myhosthame.elasticsearch`

When I disable sniffing 
`
	client, err := elastic.NewClient(
		elastic.SetURL("http://myhosthame.elasticsearch"),
		elastic.SetSniff(false),
	)
`

I'm connecting to proper host.

**Comment by olivere** [comment]
You need to configure your cluster accordingly. See [this Wiki page](https://github.com/olivere/elastic/wiki/Connection-Problems#how-to-figure-out-connection-problems) to figure out what happens if you use the defaults.

**Comment by RidgeA** [comment]
Thanks!
