### ISSUE TITLE
v3: Switch to stdlib context

### ISSUE THREAD

**Issue by olivere** [olivere/elastic#547]
The elastic.v3 package still has references to `golang.org/x/net/context` (e.g. [client.go](https://github.com/olivere/elastic/blob/release-branch.v3/client.go)). We should switch them to `context` from stdlib, just as we've already done with v2 and v5.

**Comment by liketic** [comment]
Can I work on this?

**Comment by olivere** [comment]
Sure. Send a PR. The majority of this could be completed with `go tool fix -force context <path>`.

**Comment by olivere** [comment]
[Completed in 3.0.70](65683bdaafd0bd1522d5312c4a21415f2fb75c2e).
