### ISSUE TITLE
Export `SearchRequest.Body`

### ISSUE THREAD

**Issue by olivere** [olivere/elastic#548]
It would be nice to have access to the [request body of a `SearchRequest`](https://github.com/olivere/elastic/blob/release-branch.v5/search_request.go#L200-L202).

**Comment by jimberlage** [comment]
@olivere is this something I can help implement?

**Comment by olivere** [comment]
The issue with this is that I'm afraid of opening up a can of worms. Right now, this means read-only access to the body. Next issue is about writing the body, then mixing DSL and writing the body.

You can of course create a PR for this and complete it (should only be a few lines of code I guess). But I have to watch out for unexpected side-effects.

**Comment by jimberlage** [comment]
Hmm.  Good point.  Perhaps we can make the body read-only by copying the bytes before returning?  That coupled with explicit API documentation might work to keep people from demanding write access to the raw JSON body.  (Though it also might not.)

I have frequently wanted to inspect the search request as JSON in development, though, so this would be useful.

**Comment by olivere** [comment]
I've opened up access to `SearchRequest.Body` in 5.0.51.
