### ISSUE TITLE
Standardize which repo to use

### ISSUE THREAD

**Issue by ysimonson** [olivere/elastic#55]
The linked documentation is for github.com/olivere/elastic, but the instructions are for installing gopkg.in/olivere/elastic.v1, and there's substantial differences between the two.

This threw me off for a while because I was trying to reference functions in the github repo, and used in unit tests, but missing from the gopkg repo. In hindsight it's obvious, but after having used the lib for a few days, I totally forgot I was't using the github repo. I think this will likewise throw people off who don't know what gopkg is.

How about referencing the same repo for both docs and installation instructions, and then adding a note about the existence of the other?

**Comment by olivere** [comment]
Hi!

I don't quite understand. This is mentioned in several places, e.g. the [README](https://github.com/olivere/elastic#releases), the [Wiki](https://github.com/olivere/elastic/wiki) (and [here](https://github.com/olivere/elastic/wiki/Changes#versions)) and the [homepage](https://olivere.github.io/elastic/).

What can I do to make this even clearer?

**Comment by ysimonson** [comment]
You're right. I must've just skimmed through the notices. Thanks @olivere .

**Comment by olivere** [comment]
I apologize if I came over as rude (just read it again myself). :-)
Seriously, I'm interested: How did you find Elastic? What path did you take that made you overlook v2?

**Comment by ysimonson** [comment]
No worries at all, I didn't think it was rude.

The disconnect happened over the course of a few days and forgetting that there was both a stable v1 on gopkg and a v2 on github. After realizing the issue, I incorrectly assumed that the docs didn't provide such notice.

At this point it's nitpicking - as the docs do outline the releases clearly - but I think I wouldn't have made the mistake if there were separate godoc buttons / usage instructions (one under the "current version" section and one under the "earlier versions" section). This would have the added benefit of linking off to the online documentation for both versions of the library.

I'd be happy to make a PR with the change if you think it makes sense.

**Comment by olivere** [comment]
You are right. The links in the `release-branch.v1` branch and `v1` tag point to the godoc page of version 2. That's confusing.

I just tagged [v1.0.1](https://github.com/olivere/elastic/tree/v1.0.1) which contains an updated README and `doc.go`. The latter produces a note on the [godoc page](http://godoc.org/gopkg.in/olivere/elastic.v1) stating that this is version 1 and that there is a newer version.

Thanks for posting.
