### ISSUE TITLE
Dump response even when client request returns error

### ISSUE THREAD

**Issue by nvartolomei** [olivere/elastic#551]
### Which version of Elastic are you using?
[x] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior

Trace client response even when request errors out.

### Please describe the actual behavior

Response is only traced for successful requests.

https://github.com/olivere/elastic/blob/release-branch.v5/client.go#L1245 this line should be moved before checking response for errors

**Comment by olivere** [comment]
Thanks. Closing in favor of #297.
