### ISSUE TITLE
Empty array becomes null in source

### ISSUE THREAD

**Issue by Swarlston** [olivere/elastic#554]
### Which version of Elastic are you using?
[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[x ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
When using a terms query and passing an empty array, the query body should also
contain an empty array  []

```
included := make([]string, 0)
filter.Filter(elasticsearch.NewTermsQuery("tags", included...))
```
should result in
```
 "terms": {
     "tags": []
 }
```
### Please describe the actual behavior
but instead i get 
```
 "terms": {
     "tags": null
 }
```
This leads to an exception:
```
"type": "parsing_exception",
    "reason": "[terms] unknown token [VALUE_NULL] after [tags]",
    "line": 15,
    "col": 29
```

### Notes
I think this is because the array of values in 
search_queries_terms.go is not initialized.

I'm not sure whether this is the correct form to report this, nor do 
i know whether the problem isn't with ES itself. ( The documentation indicates that 
null and [] are equivalent at some point )

**Comment by olivere** [comment]
Thanks for supporting Elastic. I will investigate and post my findings here.

**Comment by olivere** [comment]
5.0.42 will properly initialize the values. I added a test case so that it will fail in the future if I'm missing it again.

**Comment by dongzhangit** [comment]
type_ids := []int{1, 2, 3}    
term := elastic.NewTermsQuery("type", type_ids...)

It's bug???

Error 400 (Bad Request): [terms] unknown token [END_ARRAY] after [type] [type=parsing_exception]
