### ISSUE TITLE
[V3] *DeleteService.Do() returning <nil, error("elastic: Error 404 (Not Found)"> instead of a *DeleteRsponse with false set to true

### ISSUE THREAD

**Issue by alaska** [olivere/elastic#555]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[X] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
Attempting to delete a document that doesn't exist returns me a *DeleteReponse where **found == false**

### Please describe the actual behavior
Attempting to delete document that doesn't exist, and I'm getting a nil *DeleteResponse and an error.

### Trace output
```
DELETE /myindex/mytype/myid HTTP/1.1
Host: myhost:9200
User-Agent: elastic/3.0.40 (darwin-amd64)
Accept: application/json
Accept-Encoding: gzip


```
### Curl output
```
$ curl -XDELETE "http:myhost:9200/myindex/mytype/myid"
{"found":false,"_index":"myindex_20151015","_type":"mytype","_id":"myid","_version":1}
```

So the response doesn't seem to be reaching the client perhaps?

**Comment by alaska** [comment]
Update, by looking at the test code, I've become aware of 
`elastic.IsNotFound(err)`, which is great, but my point still holds, kind of.  If the response is always going to have a nil `*elastic.DeleteReponse` with an error I have to check with `elastic.IsNotFound`, then the *found* property is kind of pointless, right?

**Comment by olivere** [comment]
I agree that the `found` property is kind of useless. The 404 indicates what happened, and there is no other useful information in the response.

After sleeping over it for a night, here's my current line of thought:

a) The "document not found" situation is comparable to `database/sql` returning an `sql.ErrNoRows` error in the case that, well, a document wasn't found. So there is at least a well-established logic behind this.

b) We cannot change the behavior as it would break existing clients.

But I'll keep this open and dig into the code over the weekend. If you have any additional arguments, please let me know.

**Comment by alaska** [comment]
I guess I balk at it a little because the library hews so closely to the ES docs otherwise (i.e., I make a request, I get a response that is a rough translation of the JSON back from ES).  It just feels like this is the exception.

**Comment by olivere** [comment]
Yes, I try to keep close to the ES request/response structure. However, returning no error here would also feel wrong as a 404 indicates a client-side error. So to be both close to ES standards, we could return an error as well as a response, just like ES does.

**Comment by olivere** [comment]
5.0.42 returns both an error (just like before) as well as a serialized response in the edge case of Delete with HTTP status code 404. See above commit.
