### ISSUE TITLE
Inconsistent behavior between distance and range aggregations

### ISSUE THREAD

**Issue by ligustah** [olivere/elastic#557]
### Which version of Elastic are you using?
elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
I expected both to accept pointers for `To` and `From` fields.

### Please describe the actual behavior
The range aggregation does not accept pointers and instead will submit empty ranges to elasticsearch for aggregation. For comparison:
- [distance aggregation](https://github.com/olivere/elastic/blob/release-branch.v5/search_aggs_bucket_geo_distance.go#L152) accepts pointers
- [range aggregation](https://github.com/olivere/elastic/blob/release-branch.v5/search_aggs_bucket_range.go#L191) does not accept pointers

**Comment by olivere** [comment]
Thanks for finding this. It should really accept pointers in both places.

**Comment by olivere** [comment]
Thanks for supporting Elastic. Inconsistencies should be fixed with 5.0.42.

**Comment by ligustah** [comment]
Awesome, thanks for you fantastic library!
