### ISSUE TITLE
IgnoreConflicts in PutMapping is no longer supported in ES 5

### ISSUE THREAD

**Issue by donutmonger** [olivere/elastic#558]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[X] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
Making a PutMapping request with IgnoreConflicts set to true should succeed and update the mapping while ignoring any conflicts.

### Please describe the actual behavior
I get an error when making the following call 
```
client.PutMapping().Index(i).Type(t).BodyString(m).IgnoreConflicts(true).Do(context.Background())
```
```
elastic: Error 400 (Bad Request): request [/logs-2017-06-21/_mapping/logs] contains unrecognized parameter: [ignore_conflicts] [type=illegal_argument_exception]
```

### Any steps to reproduce the behavior?
Make a PutMapping request with IgnoreConflicts set to true.

**Comment by AndersonZacharyT** [comment]
running into this now, does anyone know what the solution is/why this was closed?

**Comment by olivere** [comment]
I don't remember exactly, but according to the changes in https://github.com/olivere/elastic/commit/fecaf715794dacfbbdd0d532e8407cf7f52b9930 the `ignore_conflicts` has simply been renamed to `update_all_types`, no?

**Comment by AndersonZacharyT** [comment]
excellent, thanks for the insight @olivere ! I actually was misusing the API and had a similar error response; disregard me.
