### ISSUE TITLE
Some problems when using Fileds

### ISSUE THREAD

**Issue by liu1700** [olivere/elastic#56]
I'm using  a searchservice with some fields. When i get the search hits and want to access the Source, it gives me a "nil",

so i have to get the data with something like "hit.Fields["userid"].([]interface{})[0].(string)"

Is there another way to get the result from the Search with fields?
Thanks~

**Comment by olivere** [comment]
Hi!

[This test](https://github.com/olivere/elastic/blob/master/search_test.go#L302) illustrates getting the fields from the result. It's a bit cumbersome, but if I see it correctly [in the Elasticsearch source](https://github.com/elastic/elasticsearch/blob/c0fa60eb26100803ebc654b51069c6a6b289ac1d/src/main/java/org/elasticsearch/index/get/GetResult.java#L215), they sometimes return an array and sometimes just a single field. So we need to use `map[string]interface{}` here :-(

Hope this helps?!

**Comment by liu1700** [comment]
sorry for replying so late.....
ok, maybe using map[string]interface{} is a better way.
Thanks~

**Comment by olivere** [comment]
Re-open if there's still some issues. Thanks.

**Comment by hurkgu** [comment]
use fileds to get integer fileds  assert error?
