### ISSUE TITLE
When ES server is overloaded and doesn't respond well I get nil pointer exception

### ISSUE THREAD

**Issue by dinoba** [olivere/elastic#564]
I am using  elastic.v5 (for Elasticsearch 5.x).

Sometimes when Elasticsearch is not responding (overloaded) I get this exception.

Any suggestions, how to handle this exception?

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x674176]

goroutine 8463660 [running]:
gopkg.in/olivere/elastic%2ev5.(*Client).PerformRequest(0x0, 0x86a360, 0xc420010208, 0x727a0c, 0x4, 0xc420e80570, 0x23, 0xc420e805a0, 0x708c40, 0xc42466e900, ...)
	/root/gocode/src/gopkg.in/olivere/elastic.v5/client.go:1136 +0x86
gopkg.in/olivere/elastic%2ev5.(*IndexService).Do(0xc423defd38, 0x86a360, 0xc420010208, 0xc42466e900, 0x1, 0xc424c3fda0)
	/root/gocode/src/gopkg.in/olivere/elastic.v5/index.go:267 +0x13b
golang/consolidatedlogs/elasticsearch.SaveLogs(0x730236, 0x1e, 0xc42031f9e0, 0x104, 0xc4202b99b0, 0xd, 0xc4202fe1a0, 0x12, 0x0, 0x0, ...)
	/root/gocode/src/golang/consolidatedlogs/elasticsearch/elasticsearch.go:37 +0x34a
main.parseLog.func1(0xc42031f9e0, 0x104, 0xc4202b99b0, 0xd, 0xc4202fe1a0, 0x12, 0x0, 0x0, 0xc4202f62f7, 0x9, ...)
	/root/gocode/src/golang/consolidatedlogs/main.go:181 +0x95
created by main.parseLog
	/root/gocode/src/golang/consolidatedlogs/main.go:186 +0x2bd
sh: 1: New: not found
E0720 08:18:37.648928 13546 process.cpp:951] Failed to accept socket: future discarded

**Comment by olivere** [comment]
According to the logging output there seems to be something wrong with your `*elastic.Client` instance. It seems to be `nil` in the call to `PerformRequest`. I don't see how that can happen in the library.

**Comment by dinoba** [comment]
well.. it fails like every few hours after more than 10k saves it fails
this is function I use

func SaveMesosStats(elasticSearchServer *string, mesosSlave mesos.MesosSlaveSimple, latestI *string) (errReturn error, latestIndex string) {
	ctx := context.Background()
	client, err := elastic.NewClient(
		elastic.SetURL(*elasticSearchServer),
	)

	if err != nil {
		errReturn = err
	}

	currentIndex := "mesos-" + time.Now().Format("2006-01-02")

	if *latestI != currentIndex{
    *latestI = currentIndex
     _, err := client.CreateIndex(*latestI).Do(ctx)
     if err != nil {
         errReturn = err
     }
  }

	if err != nil {
		errReturn = err
	}

	_, err = client.Index().
		Index(currentIndex).
		Type("slave").
		BodyJson(mesosSlave).
		Refresh("true").
		Do(ctx)

	if err != nil {
		errReturn = err
	}

	latestIndex = currentIndex

	return
}

**Comment by olivere** [comment]
As [stated here](https://github.com/olivere/elastic/wiki/Client), a client is supposed to be long-lived. So you should better create it once and use it across your application. If you really want a short-lived client, use `NewSimpleClient` instead--it doesn't do sniffing, doesn't check for errors, doesn't do healthchecks etc.

Next, you simply do not return from your error check:

```
client, err := elastic.NewClient(
elastic.SetURL(*elasticSearchServer),
)

if err != nil {
	errReturn = err
}

// client may be nil here, so kaboom!
```

**Comment by dinoba** [comment]
Thank you.
