### ISSUE TITLE
Search Query gives back HTTP Error Code 411 on querying elasticsearch with nginx setup as a proxy

### ISSUE THREAD

**Issue by twistedlog** [olivere/elastic#565]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[x] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
Search query should respond back with data from Elasticsearch and not HTTP 411

### Please describe the actual behavior
Search query responds back with HTTP Error 411 when I have nginx 1.9 setup as a proxy to access elasticsearch cluster. This is happening due to ContentLength being set to 0 on a POST call even though the request body is of a different length. Setting the content length in a POST call in **client.go** explicitly to body length fixes the problem.

**Comment by olivere** [comment]
HTTP status 411 is a client-side error, so Elastic responds with an error. It may be a problem that needs to be fixed in your proxy, not in the Elastic code base.
