### ISSUE TITLE
Examples for SearchService for Match Queries

### ISSUE THREAD

**Issue by mohigup** [olivere/elastic#566]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?
[ ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
I am looking for examples on using SearchService for Match Queries and adding additional parameters in query such as highlighter

### Please describe the actual behavior
There are no examples in Wiki or documentation on using SearchService apart from TermQuery

### Any steps to reproduce the behavior?
NA

Please let me know how various search queries can constructed using current repo.

**Comment by olivere** [comment]
All queries implement the Query interface. So from the standpoint of SearchService, all queries are the same. There's nothing special about TermService or MatchAllQuery.

For specific examples of the features you're asking for: There's a wealth of tests that you can read. Especially the search_test.go has numerous integration tests.

**Comment by mohigup** [comment]
I will check. Thank @olivere

**Comment by mohigup** [comment]
@olivere . Thanks for the suggestion. I was able to use the Query Interface as per my needs.
