### ISSUE TITLE
getting " Error 400 (Bad Request): all shards failed [type=search_phase_execution_exception]"

### ISSUE THREAD

**Issue by blafasel42** [olivere/elastic#567]
Hi there. Probably i do something wrong, but i cannot spot my mistake.
I used the sample code to create the "twitter" index, write the user "olivere". It all works.
But when it comes to the term query for user "olivere" i get:
 Error 400 (Bad Request): all shards failed [type=search_phase_execution_exception]

Even if i create  client and then only try the term query, the error gets thrown.
Code:

```go
	termQuery := elastic.NewTermQuery("user", "olivere")
	searchResult, err := client.Search().
		Index("twitter").   // search in index "twitter"
		Query(termQuery).   // specify the query
		Sort("user", true). // sort by "user" field, ascending
		From(0).Size(10).   // take documents 0-9
		Pretty(true).       // pretty print request and response JSON
		Do(ctx)             // execute
	if err != nil {
		panic(err)
	}
```

When i issue the same term query with my rest client, it works perfectly:
```
POST /_search
{
  "query": {
    "term" : { "user" : "olivere" } 
  }
}
```

everything green in the health output, index and all shards created, no log output from ES
(using the official ES docker container)

### Which version of Elastic are you using?
[X ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
search should return a result

### Please describe the actual behavior
error message as described above

### Any steps to reproduce the behavior?

Just run the example test code.

Any ideas?

**Comment by blafasel42** [comment]
I guess i found out myself. Problem appears to be the missing mapping during index creation. Unfortunately, ES sends the wrong exception so i needed to enable debug logging to find the cause:
`Fielddata is disabled on text fields by default. Set fielddata=true on [user] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.`

**Comment by olivere** [comment]
Yes, this is the root cause. Elastic is only a client. Please consult the Elasticsearch documentation about how to correctly do your mappings. There's [an example of a correct mapping](https://olivere.github.io/elastic/) on the Elastic homepage that you should be able to use as a starter.

**Comment by JAlexoid** [comment]
@olivere - You should remove the bad code from README.md

**Comment by olivere** [comment]
@JAlexoid The code in the README reflects a snippet that doesn't work right away. It has a link to a [complete example](https://gist.github.com/olivere/114347ff9d9cfdca7bdc0ecea8b82263). That code should work fine in Elastic 3.x (for ES 2.x).

The [home page](https://olivere.github.io/elastic/) has a fully working example for v5.

I agree that the README for v5 should have a link to a fully working example for v5. You're free to send a PR.

**Comment by olivere** [comment]
@JAlexoid Ha! And you did... 👍

**Comment by taiyangc** [comment]
Was in the same boat. Would be great if the error returned can include RootCause Reasons as well... it helps debugging so much. Thanks!

**Comment by olivere** [comment]
@taiyangc If Elasticsearch returns a structured error, you should be able to handle it [like this](https://github.com/olivere/elastic/wiki/Errors). It returns an [`Error` structure](https://github.com/olivere/elastic/blob/release-branch.v5/errors.go#L62-L81) that should include the error response from ES.

**Comment by taiyangc** [comment]
@olivere ah yes sorry should have read the docs first! thanks!
