### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by DaniloPolani** [olivere/elastic#568]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[x] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
Putting a document without errors. The index exists.

### Please describe the actual behavior
It returns this error:

```
panic.go:34: runtime error: invalid memory address or nil pointer dereference
/home/danilo/Go/src/gopkg.in/olivere/elastic.v5/client.go:1181 +0x86
gopkg.in/olivere/elastic%!e(MISSING)v5.(*IndexService).Do(0xc42060ab28, 0xe06d40, 0xc420016400, 0x1d, 0x0, 0x0)
	/home/danilo/Go/src/gopkg.in/olivere/elastic.v5/index.go:267 +0x13b
```

### Any steps to reproduce the behavior?
```
type Food struct {
	ID       uint   `gorm:"primary_key" json:"id"`
	Name     string `json:"name"`
	Icon     string `json:"icon"`
	Category string `json:"category"`
}

food := models.Food{
  Name:      "Foo",
  Icon:         "Bar",
  Category: "Dog",
}
app.Db.Create(&food) // GORM

put, err := app.Elastic.Index().
  Index("foods").
  Type("food").
  Id(app.Utoa(food.ID)). // app.Utoa transforms uint to string
  BodyJson(food).
  Do(context.Background())
if err != nil {
  panic(err)
}
fmt.Printf("Indexed food %s to index %s, type %s\n", put.Id, put.Index, put.Type)
```

The "ID" is populated by GORM, so I insert item to DB, it set the "ID" field of the struct and then I index it with elastic, which is correctly connected (_Elasticsearch returned with code 200 and version 5.0.0_)

`app.Elastic` is this:

```
Elastic, err := elastic.NewClient()
	if err != nil {
		panic("Can't connect to ElasticSearch")
	}
```

**Comment by olivere** [comment]
When you see `runtime error: invalid memory address or nil pointer dereference`, there is a `nil` pointer involved. Make sure that none of your parameters are `nil`.

From the code snippets you send, I cannot see which variable is `nil`. It could be `app.Db`, or `app.Elastic`, or `food.ID`, or `food`. I don't know. If you want me to debug your code, please send a complete and executable `main`.

**Comment by DaniloPolani** [comment]
Oh, damn, `app.Elastic` was `<nil>`, I'm sorry! It confused me the fact that it was reporting as error the line `Do(ctx)`.
