### ISSUE TITLE
Problems With Sniffing

### ISSUE THREAD

**Issue by blachniet** [olivere/elastic#57]
I'm running Elasticsearch v1.4.4 in a [Docker container](https://registry.hub.docker.com/u/library/elasticsearch/). I kept having trouble getting the client to work properly. I was trying to run the sample in the README (obviously pointing to my Docker container instead of localhost). It was taking ~30 seconds to create the client, and then would fail to create the index with the error: `no Elasticsearch node available`. 

As soon as I set turned off sniffing when creating the client (`elastic.SetSniff(false)`), everything worked perfectly. It doesn't really bother me that I have to turn sniffing off, but I wanted to put this issue out to see if anyone else had seen an issue like this.

P.S. @olivere - The documentation is awesome! :+1:

**Comment by olivere** [comment]
@blachniet Thank's for using Elastic.

Yes, Docker seems to be a problem because (I assume) running ES inside a container is returning IP addresses that are not available from outside. There was a discussion about this in #42 IIRC.

Can you post the results of `curl -XGET <esserver>/_nodes/http?pretty=1`? The `http_address` is what Elastic (and the other official clients) use to find a new host. If that address is not available from outside Docker, we have a problem...

**Comment by blachniet** [comment]
Ah, that makes sense. It makes me feel better knowing I wasn't the only one seeing this. I'm perfectly fine leaving the sniffing disabled.

```
curl -XGET http://192.168.59.103:9200/_nodes/http?pretty
{
  "cluster_name" : "elasticsearch",
  "nodes" : {
    "PGNiMR5YSPaxhOzDDRn_DQ" : {
      "name" : "Aunt May Parker",
      "transport_address" : "inet[/172.17.0.2:9300]",
      "host" : "b9d7c0daafe2",
      "ip" : "172.17.0.2",
      "version" : "1.4.4",
      "build" : "c88f77f",
      "http_address" : "inet[/172.17.0.2:9200]",
      "http" : {
        "bound_address" : "inet[/0:0:0:0:0:0:0:0:9200]",
        "publish_address" : "inet[/172.17.0.2:9200]",
        "max_content_length_in_bytes" : 104857600
      }
    }
  }
}
```

**Comment by olivere** [comment]
Unfortunately, this is what happens here: Elastic will query `192.168.59.103` and registers the IP address returned there (`inet[/172.17.0.2:9200]`). Then it tries to query `172.17.0.2`, which probably won't work.

I haven't found a solution to this other than (somehow) getting the ES in Docker to return the external IP. I guess other clients have the same problem.

If you have an idea how to solve this (or a document describing the way to configure Docker), let me know :-)

**Comment by olivere** [comment]
Okay. Let me know if I can do anything here. Closing for now.

**Comment by dashaus** [comment]
Hi,
I have the same problem here:
```
panic: main: conn db: no Elasticsearch node available

goroutine 1 [running]:
log.Panicf(0x84de50, 0x11, 0xc2080c7e90, 0x1, 0x1)
	/usr/local/go/src/log/log.go:314 +0xd0
main.init·1()
	/Users/emilio/go/src/monoculum/init.go:40 +0x348
main.init()
	/Users/emilio/go/src/monoculum/main.go:334 +0xa4

goroutine 526 [select]:
net/http.(*persistConn).roundTrip(0xc2088ad1e0, 0xc2086a9d50, 0x0, 0x0, 0x0)
20:30:13 app         | 	/usr/local/go/src/net/http/transport.go:1082 +0x7ad
net/http.(*Transport).RoundTrip(0xc20806c000, 0xc2086f6000, 0xc20873ff50, 0x0, 0x0)
20:30:13 app         | 	/usr/local/go/src/net/http/transport.go:235 +0x558
20:30:13 app         | net/http.send(0xc2086f6000, 0xed4f18, 0xc20806c000, 0x21, 0x0, 
20:30:13 app         | 0x0)
	/usr/local/go/src/net/http/client.go:219
20:30:13 app         |  +0x4fc
net/http.(*Client).send(0xc08b00, 0xc2086f6000, 0x21
20:30:13 app         | , 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:142 +0x15b
20:30:13 app         | net/http.(*Client).doFollowingRedirects(0xc08b00, 0xc2086f6000, 0x97cd00, 0x0, 0x0, 0x0)
20:30:13 app         | 	/usr/local/go/src/net/http/client.go:367 +0xb25
net/http.(*Client).Do(0xc08b00, 0xc2086f6000, 0xc20873fce0, 0x0, 
20:30:13 app         | 0x0)
	/usr/local/go/src/net/http/client.go
20:30:13 app         | :174 +0xa4
github.com/olivere/elastic.(*Client).sniffNode(0xc208659d10, 0xc208569920, 0x15
20:30:13 app         | , 0x0, 0x0, 0x0)
20:30:13 app         | 	/Users/emilio/go/src/github.com/olivere/elastic/client.go:543
20:30:13 app         |  +0x16a
20:30:13 app         | 
github.com/olivere/elastic.func·014(0xc208569920, 0x15
20:30:13 app         | )
	/Users/emilio/go/src/github.com/olivere/elastic/client.go:508 +0x47
20:30:13 app         | created by github.com/olivere/elastic.(*Client).sniff
	/Users/emilio/go/src/github.com/olivere/elastic/client.go:508 +0x744

goroutine 525 [chan receive]:
20:30:13 app         | database/sql.(*DB).connectionOpener(0xc2086de960)
	/usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:452 +0x31c

goroutine 529 [IO wait]:
20:30:13 app         | net.(*pollDesc).Wait(0xc2084fe370, 0x72, 0x0
20:30:13 app         | , 
20:30:13 app         | 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2084fe370, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2084fe310, 0xc208709000, 0x1000, 0x1000, 0x0, 0xed4d48, 0xc2086a9ec8)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20896a800, 0xc208709000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0xef0410, 0xc20896a800, 0xc2088ad238, 0xc208709000, 0x1000, 0x1000, 0xeb7010, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc208569b40, 0xc208709000, 0x1000, 0x1000, 0xc207f6957f, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc2088f3c80)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc2088f3c80, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc2088ad1e0)
	/usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 530 [select]:
net/http.(*persistConn).writeLoop(0xc2088ad1e0)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc
```

This occurs sometimes... not always...

```
curl -XGET 127.0.0.1:9200/_nodes/http?pretty=1
{
  "cluster_name" : "elasticsearch",
  "nodes" : {
    "3l_Ing0oSfWu5U63US5kxg" : {
      "name" : "Rattler",
      "transport_address" : "inet[192.168.1.91/192.168.1.91:9300]",
      "host" : "Mac-Emilio",
      "ip" : "192.168.1.91",
      "version" : "1.3.4",
      "build" : "a70f3cc",
      "http_address" : "inet[/192.168.1.91:9200]",
      "http" : {
        "bound_address" : "inet[/0:0:0:0:0:0:0:0:9200]",
        "publish_address" : "inet[/192.168.1.91:9200]",
        "max_content_length_in_bytes" : 104857600
      }
    }
  }
}
```

**Comment by olivere** [comment]
@dashaus and @blachniet, can you guys please share some details about your configuration? I will try to reproduce the issue. You are both using Docker, are you? How many ES instances do you use? What's your typical load? When and how often do you get errors?

@dashaus The stack trace seems odd. According to the log the error occurs in [line 543 of client.go](https://github.com/olivere/elastic/blob/master/client.go#L543), which just does a HTTP request:

```go
res, err := c.c.Do((*http.Request)(req))
```

I cannot see what could go wrong here. It doesn't look like you're using a [custom transport](https://github.com/olivere/elastic/wiki/HttpTransport), do you?

When I know your configuration, I can at least try to set up a similar environment and run the [cluster test](https://github.com/olivere/elastic/tree/master/cluster-test). Maybe I will get similar errors.

Thanks in advance.

**Comment by dashaus** [comment]
I don't use Docker, I have installed it manually. I use only instance. The load is very low (just me with the application that i'am creating). The error occurs when the server restarts by [fresh](http://github.com/pilu/fresh) (sometimes the error is raised, other not). I create the connection like this (I don't use a custom transport):

```go
u := elastic.SetURL("127.0.0.1:9200")
m, err := elastic.NewClient(u)
```

Thanks!

**Comment by olivere** [comment]
Is it just a typo, or are you using the URL without the scheme?

When I use it like that, I'll get the same error as you do. When I change it to ...

```go
u := elastic.SetURL("http://127.0.0.1:9200")
```

... everything is okay.

**Comment by dashaus** [comment]
Yes, is a typo, really I have `http://127.0.0.1:9200`.

It is strange because not always occurs the error...

**Comment by blachniet** [comment]
I've tried 2 different Docker configurations. Below is the common details between the 2. 

- [Elasitcsearch 1.5.0 Container](https://registry.hub.docker.com/u/library/elasticsearch/)
- 1 Elasticsearch node
- Very light load: 1 document (less than 300 bytes) pushed every 10 seconds
- Rare, light querying

I ran the Elasticsearch container on Boot2Docker, on the same device as the application interacting with it. When that failed due to the problem described in the original post, I tried running the Elasticsearch container on a separate Ubuntu server with Docker installed. I ran into the same issue with this approach. 

I'm fairly new to Docker, so I'm not sure if there is some way I can configure my Docker containers or daemon to address this problem. In the meantime, I have disabled sniffing.

**Comment by blachniet** [comment]
According [this post from 2012](http://elasticsearch-users.115913.n3.nabble.com/How-to-get-my-java-client-to-discover-an-entire-cluster-tp3722990p3723528.html), it sounds like there should be a `network.host` option that can be set in the config that may solve this problem. I'll try it out and let you know how it goes.

**Comment by olivere** [comment]
Thank you, guys. I think we have two separate issues here: 1) Docker and 2) Problems while connecting. I don't think they are related. So I started #58 for the connection issue, and keep the Docker stuff here.

**Comment by olivere** [comment]
@blachniet I'm new to Docker, too. But AFAIU the option to change is [`network.publish_host`](http://www.elastic.co/guide/en/elasticsearch/reference/1.x/modules-network.html). The documentation states:

> The `network.publish_host` setting allows to control the host the node will publish itself within
> the cluster so other nodes will be able to connect to it. Of course, this can’t be
> the `anyLocalAddress`, and by default, it will be the first non loopback address (if possible),
> or the local address.
> 
> The `network.host` setting is a simple setting to automatically set both `network.bind_host` and
> `network.publish_host` to the same host value.

I found [this article here](http://mattupstate.com/coreos/devops/2014/06/26/running-an-elasticsearch-cluster-on-coreos.html) that comes with a script that sets `network.publish_host` option during Docker startup (search for `network.publish_host`). Maybe you can try something like that and let me know?!

**Comment by blachniet** [comment]
That did it, thanks for your help! Here's the steps I took to get it to work:

1. If you're using Boot2Docker, get the ip address of the virtual machine (`boot2docker ip`). If you are not using Boot2Docker, get the IP address of the machine running the Docker daemon.
2. Grab an `elasticsearch.yml` config from the [Elasticsearch release archive](https://www.elastic.co/downloads/elasticsearch).
3. Update the config file to set `network.publish_host` to the IP address from step one.
4. Start an [Elasticsearch container](https://registry.hub.docker.com/u/library/elasticsearch/) using your custom config file by mounting the directory containing the config file:  
`docker run -d -v "$PWD/config":/usr/share/elasticsearch/config elasticsearch`
5. Verify that `publish_address` is the IP address from step one when you run  
`curl -XGET http://<IPAddress>:9200/_nodes/http?pretty`

**Comment by olivere** [comment]
Thanks for your time! I made a [wiki page](https://github.com/olivere/elastic/wiki/Docker) for self-reference.

**Comment by jetsanix** [comment]
It worked for me! Thanks 👍

**Comment by jhonata-menezes-forseti** [comment]
It worked for me! Thanks 👍

**Comment by email2liyang** [comment]
this way seems not work with latest elastic search image 5.2.1

I  have tried both ways
# disable sniff by put "client.transport.sniff" to false
# override network.publish_host with my docker host ip 127.0.0.1(docker for mac)
I could see the transport address has changed to 127.0.0.1 but still could not connect to ES

if I override network.host to 127.0.0.1, we could not communicate with es from host anymore

```
curl 127.0.0.1:32825/_nodes/http?pretty
{
  "_nodes" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "cluster_name" : "elasticsearch",
  "nodes" : {
    "qCszJJYsTjuisYl8sP3x2w" : {
      "name" : "qCszJJY",
      "transport_address" : "127.0.0.1:9300",
      "host" : "127.0.0.1",
      "ip" : "127.0.0.1",
      "version" : "5.2.1",
      "build_hash" : "db0d481",
      "roles" : [
        "master",
        "data",
        "ingest"
      ],
      "http" : {
        "bound_address" : [
          "[::]:9200"
        ],
        "publish_address" : "172.17.0.3:9200",
        "max_content_length_in_bytes" : 104857600
      }
    }
  }
}
```

**Comment by olivere** [comment]
@email2liyang It does use the `publish_address` (as all other official clients) which is still `"publish_address" : "172.17.0.3:9200"`.

I just ran the testsuite on Docker for Mac with 5.2.1, which you can do too with [`run-5.2.1.sh`](https://github.com/olivere/elastic/blob/release-branch.v5/run-es-5.2.1.sh). The configuration file is [`./config/elasticsearch.yml`](https://github.com/olivere/elastic/blob/release-branch.v5/config/elasticsearch.yml).

**Comment by email2liyang** [comment]
@olivere , thanks for your prompt response, i works with  your config file, I think the key thing is that the docker instance should still bind to multiple address so that the host can communicate with es inside docker
```
curl 127.0.0.1:9200/_nodes/http?pretty
{
  "_nodes" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "cluster_name" : "elasticsearch",
  "nodes" : {
    "nAW0dbsrQPuZS2XERaTj8Q" : {
      "name" : "nAW0dbs",
      "transport_address" : "127.0.0.1:9300",
      "host" : "127.0.0.1",
      "ip" : "127.0.0.1",
      "version" : "5.2.1",
      "build_hash" : "db0d481",
      "roles" : [
        "master",
        "data",
        "ingest"
      ],
      "http" : {
        "bound_address" : [
          "[::1]:9200",
          "127.0.0.1:9200",
          "172.17.0.2:9200"
        ],
        "publish_address" : "127.0.0.1:9200",
        "max_content_length_in_bytes" : 104857600
      }
    }
  }
}
```

**Comment by email2liyang** [comment]
by the way what's _local_ and _site_ means in your config file?

**Comment by olivere** [comment]
@email2liyang You can read about all of this in [the documentation](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/modules-network.html).

**Comment by Sarvesh-D** [comment]
@olivere 
I am having trouble connecting java client to elastic search 5.4.3. I am using below stack:

- dockerised version of elasticsearch:5.4.3

- elastic search client
```
<dependency>
		<groupId>org.elasticsearch.client</groupId>
		<artifactId>transport</artifactId>
		<version>5.4.3</version>
</dependency>
```

Below is response of http://localhost:9200/_nodes/http?pretty
```
{
  "_nodes" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "cluster_name" : "elasticsearch",
  "nodes" : {
    "XU8oSxxJQFmrbwWHJTdokQ" : {
      "name" : "XU8oSxx",
      "transport_address" : "127.0.0.1:9300",
      "host" : "127.0.0.1",
      "ip" : "127.0.0.1",
      "version" : "5.4.3",
      "build_hash" : "eed30a8",
      "roles" : [
        "master",
        "data",
        "ingest"
      ],
      "attributes" : {
        "ml.enabled" : "true"
      },
      "http" : {
        "bound_address" : [
          "[::1]:9200",
          "127.0.0.1:9200",
          "172.19.0.2:9200"
        ],
        "publish_address" : "127.0.0.1:9200",
        "max_content_length_in_bytes" : 104857600
      }
    }
  }
}
```
Below is java-config:
`TransportClient client = new PreBuiltTransportClient(settings).addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName("localhost"), 9300));`

I am not getting any error while initialising the client. Whenever i perform a search query like 
```
client.prepareSearch("nat-search").setTypes("csv")
		.setQuery(QueryBuilders.termQuery("obj_val", searchRequestDto.getKeyword())).get();
```
, i am getting below response:
None of the configured nodes are available: [{#transport#-1}{52YhIsGTR76VlR9g9zsurA}{localhost}{127.0.0.1:9300}]

**Comment by olivere** [comment]
@Sarvesh-D This repository is a Go client of Elasticsearch, not a Java client. So I cannot help you, but the people over [at the ES discussion groups](https://discuss.elastic.co/) are sure to help.

**Comment by mayankdevapplift** [comment]
@olivere

I am unable to start elastic search with the given configuration in your git repo. 

ES Version 5.5.0

[2017-07-17T09:20:27,840][INFO ][o.e.n.Node               ] initialized
[2017-07-17T09:20:27,840][INFO ][o.e.n.Node               ] [1EmzCoa] starting ...
[2017-07-17T09:20:28,076][INFO ][o.e.t.TransportService   ] [1EmzCoa] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}, {172.17.0.73:9300}
[2017-07-17T09:20:28,089][INFO ][o.e.b.BootstrapChecks    ] [1EmzCoa] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
ERROR: [1] bootstrap checks failed
[2017-07-17T09:20:28,097][INFO ][o.e.n.Node               ] [1EmzCoa] stopping ...
[2017-07-17T09:20:28,135][INFO ][o.e.n.Node               ] [1EmzCoa] stopped
[2017-07-17T09:20:28,135][INFO ][o.e.n.Node               ] [1EmzCoa] closing ...
[2017-07-17T09:20:28,145][INFO ][o.e.n.Node               ] [1EmzCoa] closed

**Comment by olivere** [comment]
@mayankdevapplift Please read [this Wiki page](https://github.com/olivere/elastic/wiki/Connection-Problems#how-to-figure-out-connection-problems). IP addresses are probably wrong.

**Comment by olivere** [comment]
@mayankdevapplift Also, the above snippet shows that ES couldn't be started due to a failed bootstrap check...

**Comment by mayankdevapplift** [comment]
Thanks for the response
I am running it in docker and ip addresses couldn't be wrong as I am using the same configuration which is provided in your repo 

# bootstrap.ignore_system_bootstrap_checks: true

discovery.zen.minimum_master_nodes: 1

network.host:
- _local_
- _site_

network.publish_host: _local_


# Enable scripting as described here: https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-scripting.html
script.inline: true
script.stored: true
script.file:   true

Also the bootstrap check is getting failed if I keep the above configuration but if i Keep this configuration, everything works fine but I used to get NoNodeAvailableException

discovery.zen.minimum_master_nodes: 1

network.host: 127.0.0.1
http.host: 0.0.0.0
network.publish_host: _local_

**Comment by olivere** [comment]
@mayankdevapplift Which configuration are you referring to?

[This](https://github.com/olivere/elastic/blob/release-branch.v5/run-es-5.5.0.sh) works fine.

**Comment by mayankdevapplift** [comment]
I am referring the same configuration
# bootstrap.ignore_system_bootstrap_checks: true

discovery.zen.minimum_master_nodes: 1

network.host:
- _local_
- _site_

network.publish_host: _local_


# Enable scripting as described here: https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-scripting.html
script.inline: true
script.stored: true
script.file:   true

And the file that I am running 
./run-es-5.5.0.sh

**Comment by olivere** [comment]
Then there's something wrong with your configuration. I just ran that script and it successfully ran ES 5.5.0 in a container. That's what I use for testing different versions here for quite some time.

```
$ ./run-es-5.5.0.sh
[2017-07-17T10:00:35,177][INFO ][o.e.n.Node               ] [] initializing ...
[2017-07-17T10:00:35,233][INFO ][o.e.e.NodeEnvironment    ] [VmzE_aB] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/vda1)]], net usable_space [55.4gb], net total_space [62.7gb], spins? [possibly], types [ext4]
[2017-07-17T10:00:35,233][INFO ][o.e.e.NodeEnvironment    ] [VmzE_aB] heap size [1007.3mb], compressed ordinary object pointers [true]
[2017-07-17T10:00:35,235][INFO ][o.e.n.Node               ] node name [VmzE_aB] derived from node ID [VmzE_aBURZKan20_rJma_Q]; set [node.name] to override
[2017-07-17T10:00:35,235][INFO ][o.e.n.Node               ] version[5.5.0], pid[1], build[260387d/2017-06-30T23:16:05.735Z], OS[Linux/4.9.36-moby/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_131/25.131-b11]
[2017-07-17T10:00:35,235][INFO ][o.e.n.Node               ] JVM arguments [-Xms2g, -Xmx2g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+DisableExplicitGC, -XX:+AlwaysPreTouch, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Xms1g, -Xmx1g, -Des.path.home=/usr/share/elasticsearch]
[2017-07-17T10:00:35,652][INFO ][o.e.p.PluginsService     ] [VmzE_aB] loaded module [aggs-matrix-stats]
[2017-07-17T10:00:35,652][INFO ][o.e.p.PluginsService     ] [VmzE_aB] loaded module [ingest-common]
[2017-07-17T10:00:35,653][INFO ][o.e.p.PluginsService     ] [VmzE_aB] loaded module [lang-expression]
[2017-07-17T10:00:35,653][INFO ][o.e.p.PluginsService     ] [VmzE_aB] loaded module [lang-groovy]
[2017-07-17T10:00:35,653][INFO ][o.e.p.PluginsService     ] [VmzE_aB] loaded module [lang-mustache]
[2017-07-17T10:00:35,653][INFO ][o.e.p.PluginsService     ] [VmzE_aB] loaded module [lang-painless]
[2017-07-17T10:00:35,654][INFO ][o.e.p.PluginsService     ] [VmzE_aB] loaded module [parent-join]
[2017-07-17T10:00:35,654][INFO ][o.e.p.PluginsService     ] [VmzE_aB] loaded module [percolator]
[2017-07-17T10:00:35,654][INFO ][o.e.p.PluginsService     ] [VmzE_aB] loaded module [reindex]
[2017-07-17T10:00:35,654][INFO ][o.e.p.PluginsService     ] [VmzE_aB] loaded module [transport-netty3]
[2017-07-17T10:00:35,654][INFO ][o.e.p.PluginsService     ] [VmzE_aB] loaded module [transport-netty4]
[2017-07-17T10:00:35,655][INFO ][o.e.p.PluginsService     ] [VmzE_aB] no plugins loaded
[2017-07-17T10:00:36,688][INFO ][o.e.d.DiscoveryModule    ] [VmzE_aB] using discovery type [zen]
[2017-07-17T10:00:37,010][INFO ][o.e.n.Node               ] initialized
[2017-07-17T10:00:37,011][INFO ][o.e.n.Node               ] [VmzE_aB] starting ...
[2017-07-17T10:00:37,101][INFO ][o.e.t.TransportService   ] [VmzE_aB] publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}, {172.17.0.2:9300}
[2017-07-17T10:00:37,136][INFO ][o.e.b.BootstrapChecks    ] [VmzE_aB] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
[2017-07-17T10:00:40,174][INFO ][o.e.c.s.ClusterService   ] [VmzE_aB] new_master {VmzE_aB}{VmzE_aBURZKan20_rJma_Q}{80AHNsIoTgyuIkeO9D0nUQ}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2017-07-17T10:00:40,223][INFO ][o.e.h.n.Netty4HttpServerTransport] [VmzE_aB] publish_address {127.0.0.1:9200}, bound_addresses {127.0.0.1:9200}, {172.17.0.2:9200}
[2017-07-17T10:00:40,223][INFO ][o.e.n.Node               ] [VmzE_aB] started
[2017-07-17T10:00:40,235][INFO ][o.e.g.GatewayService     ] [VmzE_aB] recovered [0] indices into cluster_state
...
```

**Comment by mayankdevapplift** [comment]
Added configuration for system_call_filter to false and it works
bootstrap.system_call_filter: false
