### ISSUE TITLE
Get source query JSON?

### ISSUE THREAD

**Issue by aguineloootz** [olivere/elastic#570]
Hi, I need to get the json source of the query to run directly on Elasticsearch, so to validate if DSL is generating exactly what I need, is it possible? Including aggs?

Tks

**Comment by olivere** [comment]
Queries e.g. all support the [`elastic.Query`](https://github.com/olivere/elastic/blob/release-branch.v5/query.go) interface. But beware: That's not the complete request, only the query part.

**Comment by beantowel** [comment]
Hi, how can we get the full part of the request body? Like what json payload the SDK actually sent.
