### ISSUE TITLE
how to Filtering Values with partitions

### ISSUE THREAD

**Issue by zhangweilun** [olivere/elastic#573]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

[ ] elastic.v5 (for Elasticsearch 5.x)

{
   "size": 0,
   "aggs": {
      "expired_sessions": {
         "terms": {
            "field": "account_id",
            "include": {
               "partition": 0,
               "num_partitions": 20
            },
            "size": 10000,
            "order": {
               "last_access": "asc"
            }
         },
         "aggs": {
            "last_access": {
               "max": {
                  "field": "access_date"
               }
            }
         }
      }
   }
}

just like this

**Comment by olivere** [comment]
It's not currently supported. I will have a look.

**Comment by zhangweilun** [comment]
thanks
