### ISSUE TITLE
No support for boundary_scanner in Highlight

### ISSUE THREAD

**Issue by nan0tube** [olivere/elastic#574]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[x] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior

ES5 has 3 types of [`boundary_scanner`](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html#boundary-scanners): `chars`, `sentence`, and `word`. This sets the boundary scanner, and expands its functionality beyond the currently supported `boundary_chars`. 

### Please describe the actual behavior

At present, there is no way to set `boundary_scanner`.

**Comment by olivere** [comment]
Thanks for your report. I will dig into this.

**Comment by olivere** [comment]
Sorry that it took so long. But #645 fixes this. It is available in 5.0.57+.
