### ISSUE TITLE
Bulk API does not set Content-Type: application/x-ndjson

### ISSUE THREAD

**Issue by lupine** [olivere/elastic#578]
### Which version of Elastic are you ussing?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[x] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior

The [Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html) states that when using the Bulk API, ` the Content-Type header should be set to application/x-ndjson.`

### Please describe the actual behavior

The requests this library sends do not set this header. Offending area of code seems to be https://github.com/olivere/elastic/blob/release-branch.v5/bulk.go#L237 - it should pass a content-type through, but doesn't.

### Any steps to reproduce the behavior?

Make a bulk API request and check the server logs. A complaint about the missing content-type is issued.

We're observing this in  [gitlab-elasticsearch-indexer](https://gitlab.com/gitlab-org/gitlab-elasticsearch-indexer/issues/7) and I don't see a good way to fix it without an upstream patch. Happy to prepare a PR for this if it'd be welcomed?

**Comment by olivere** [comment]
Yes, I've seen this message in the log as well, then checked the ES source and found it to be non-critical. Doesn't mean I don't want to fix it, but I have to refactor the `PerformRequest` method to do that correctly. It should be a good job for the v6 update that's going to be done in the next weeks.

**Comment by lupine** [comment]
Great, thanks for picking this up!
