### ISSUE TITLE
how to use client efficently

### ISSUE THREAD

**Issue by zhangweilun** [olivere/elastic#579]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?
[ ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
i use one client in my project,but sometimes it deae

### Please describe the actual behavior

var es *elastic.Client
var once sync.Once
//single
func Instance() *elastic.Client {
	once.Do(func() {
			client, _ := elastic.NewClient(
				elastic.SetURL("http://"+es_host+":9200"),
				elastic.SetErrorLog(log.New(os.Stderr, "ELASTIC ", log.LstdFlags)),
				elastic.SetInfoLog(log.New(os.Stdout, "", log.LstdFlags)),
				elastic.SetTraceLog(log.New(os.Stderr, "[[ELASTIC]]", 0)))
			es = client
	})
	return es
}

### Any steps to reproduce the behavior?
is that right to use it

**Comment by olivere** [comment]
Using a single instance of `*elastic.Client` across your application is okay. It should be thread-safe.

However, you should *always* check for errors when creating the new client. You don't do that in your code snippet. If you're simply swallowing the error, your `*elastic.Client` will probably be `nil`, which is not what you want.
