### ISSUE TITLE
Type mandatory for indexing a document

### ISSUE THREAD

**Issue by arthurgustin** [olivere/elastic#580]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[x] elastic.v5 (for Elasticsearch 5.x)

### Background ###

Hi, we are anticipating the new version of elastic that will get ride of types. To do so, we are creating 1 index per document type, as it is the best way to handle our business requirement.

### Please describe the expected behavior
```
if _, err := m.ElasticClient.Index().
		Index(myDocumentType).
		Id(entry.ID).
		BodyJson(myProduct).
		Do(ctx); err != nil {
		return fmt.Errorf("executing the index operation failed with error: %v", err)
	}
	return nil
```
To work without error
### Please describe the actual behavior
`executing the index operation failed with error: missing required fields: [Type]`

### Any steps to reproduce the behavior?

Just use the given code

### codebase ###
```
// Validate checks if the operation is valid.
func (s *IndexService) Validate() error {
	var invalid []string
	if s.index == "" {
		invalid = append(invalid, "Index")
	}
	if s.typ == "" {
		invalid = append(invalid, "Type")
	}
	if s.bodyString == "" && s.bodyJson == nil {
		invalid = append(invalid, "BodyJson")
	}
	if len(invalid) > 0 {
		return fmt.Errorf("missing required fields: %v", invalid)
	}
	return nil
}
```

**Comment by olivere** [comment]
I will tackle that with the release of elastic.v6. Thanks for reporting.

**Comment by arthurgustin** [comment]
Nice ! Any release date planned ?

**Comment by olivere** [comment]
Interestingly, the API spec still [states to include a `type`](https://github.com/elastic/elasticsearch/blob/6.x/rest-api-spec/src/main/resources/rest-api-spec/api/index.json#L18-L22) when indexing a document.

elastic.v6 succeeds with all tests green on beta 1. Haven't found the time to test with beta 2. It's not ready yet. I hope to release around the same time as ES 6 GA.

**Comment by olivere** [comment]
Sorry... I meant it runs the Alpha, and I haven't tested the beta yet.

**Comment by arthurgustin** [comment]
I ve read somewhere in the docs that types will still work but marked as deprecated untill elastic 7.0
Anyway, we will use a default type for all our documents for now.
Thank you !

**Comment by olivere** [comment]
The Elasticsearch 6.x code seems to typically use `doc` as the type, e.g. in all tests. The 6.x series will (by default) throw if you try to add a 2nd type to an index. Indices carried over from 5.x should work fine in 6.x though. In 7.x, types will be removed altogether. So new applications should stick to the one type per index rule starting when using 6.x.

BTW you can use 6.0.0-rc2 with `github.com/olivere/elastic` now. All tests are green. There might be some breaking changes (both from ES as well as Elastic) before 6.0 GA will be released.
