### ISSUE TITLE
connect error

### ISSUE THREAD

**Issue by zhangweilun** [olivere/elastic#582]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?
[ ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
i connect a es server,but this es server is behind a nginx proxy,it real ip is not public
2017/08/12 21:07:59 elastic: http://192.168.1.15:9200 joined the cluster
ELASTIC 2017/08/12 21:08:04 elastic: http://192.168.1.15:9200 is dead
[08/12 21:08:04] [E] no active connection found: no Elasticsearch node available
 it is the error

**Comment by zhangweilun** [comment]
esHost = "es.g2l-service.com"

client, err := elastic.NewClient(
				elastic.SetURL("http://"+esHost),
				elastic.SetErrorLog(log.New(os.Stderr, "ELASTIC ", log.LstdFlags)),
				elastic.SetInfoLog(log.New(os.Stdout, "", log.LstdFlags)),
				elastic.SetTraceLog(log.New(os.Stderr, "[[ELASTIC]]", 0)),
				elastic.SetBasicAuth("admin", "4Dm1n.3s"))
			if err != nil {
				panic(err)
			}

**Comment by olivere** [comment]
Try to [disable sniffing](https://github.com/olivere/elastic/wiki/Sniffing). That should do the job.
