### ISSUE TITLE
VSCODE debug keep hang on c.mu.RLock() method (MacOS)

### ISSUE THREAD

**Issue by tvpsh2020** [olivere/elastic#584]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[V] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior

In Windows, while debugging with VSCODE, everything is fine when I initial an empty Client struct.

ex:

var (
	Client *elastic.Client
)

### Please describe the actual behavior

In Mac (darwin), while debugging with VSCODE, it will hang on client.go:1181 everytime.

c.mu.RLock()

### Any steps to reproduce the behavior?

Just initial this in darwin(MacOS) : 

var (
	Client *elastic.Client
)

**Comment by olivere** [comment]
Hmm... I will try to reproduce. However, I don't see how this can be a bug in Elastic. Are you sure there's no separate process concurrently read-locking the mutex, hence it blocks?!

**Comment by olivere** [comment]
@tvpsh2020 Working fine here with this code:

```
package main

import (
	"log"

	elastic "gopkg.in/olivere/elastic.v5"
)

func main() {
	_, err := elastic.NewClient()
	if err != nil {
		log.Fatalf("Connect failed: %v", err)
	}
	log.Print("Connected")
}
```

I can debug until the `log.Print("Connected")` line.

IIRC You should be using `delve-HEAD` on Mac, because 1.0.0-rc.1 has some issues.

**Comment by olivere** [comment]
@tvpsh2020 Also, running a request (hence hitting line 1181) will work fine as well:

```
package main

import (
	"context"
	"log"

	elastic "gopkg.in/olivere/elastic.v5"
)

func main() {
	client, err := elastic.NewClient()
	if err != nil {
		log.Fatalf("Connect failed: %v", err)
	}
	log.Print("Connected")

	_, err = client.IndexExists("twitter").Do(context.Background())
	if err != nil {
		log.Fatalf("IndexExists failed: %v", err)
	}
	log.Print("Done")
}
```
