### ISSUE TITLE
Unclear on how to use client.Update()

### ISSUE THREAD

**Issue by sea350** [olivere/elastic#588]
### Which version of Elastic are you using?
Version 5.x

### Please describe the expected behavior
It is unknown how exactly client.Update() works.  It's needed to completely change a field and to modify arrays. i.e. in the example in the wiki documentation, how would one go about appending and removing tags to a tweet or changing a tweet's content?

**Comment by olivere** [comment]
You can find extensive documentation on the Elasticsearch home page, e.g. https://www.elastic.co/guide/en/elasticsearch/reference/5.5/docs-update.html

Elastic is just a client to Elasticsearch. If you struggle with the way of transforming the JSON body/request into Go code: the tests should help you with that.
