### ISSUE TITLE
Partial update in BulkProcessor doesn't work

### ISSUE THREAD

**Issue by TFohrer** [olivere/elastic#589]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[*] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
Only the field added should be updated in the document.

### Please describe the actual behavior
The whole document get's updated and so all the other fields are empty in the Document.

### Any steps to reproduce the behavior?

Create a index with multiple fields and add some documents to it. No try to update only one field of the document with the BulkUpdateRequest. Now all the other fields of this document are empty. 
For example: 

Let's say you have a Index called Tags with the following datastructure 
```
type Tag struct {
	Title  string		json:"title"
	Identifier string 	json:"identifier"
	Parent string		json:"parent"
	Level int		json:"level"
	FullPath string		json:"fullPath"
	CreatedAt string  	json:"createdAt"
	CreatedBy string	json:"createdBy"
	ModifiedAt string 	json:"modifiedAt"
	ModifiedBy string  	json:"modifiedBy"
	Checked int		json:"checked"
}
```

When you know already have some Documents in you index and run a script checking for changes in the modified date and setting the "Checked" field to 1 via BulkProcessor : 

```
tag := Tag{Checked: checked}
		updateReq := elastic.NewBulkUpdateRequest().Index(tags).Type("tag").Id(identifier).Doc(tag)
		tagBulkRequest.Add(updateReq)
```

This updates all fields (sets other fields to empty value) and only sets checked to 1.

**Comment by olivere** [comment]
Seems fine with me. When you create a tag like this:

```
tag := Tag{Checked: true}
```

... what you get when serializing as JSON looks like this:

```
{"title":"","identifier":"","parent":"","level":0,"fullPath":"","createdAt":"","createdBy":"","modifiedAt":"","modifiedBy":"","checked":true}
```

Hence, you updated all fields (see [here](https://play.golang.org/p/g-ciFbldTU)).

Take a look at the [`bulk_update_request_test.go`](https://github.com/olivere/elastic/blob/release-branch.v5/bulk_update_request_test.go) for an example of passing e.g. only a `map[string]interface{}` so that only one field is updated:

```
NewBulkUpdateRequest().Index("...").Type("...").Id("...").Doc(struct {
	Checked bool `json:"checked"`
}{
	Checked: true,
})
```
