### ISSUE TITLE
How to add script fields to search result.

### ISSUE THREAD

**Issue by miloandmilk** [olivere/elastic#591]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ x] elastic.v5 (for Elasticsearch 5.x)

I have been looking at script fields in the elastic docs - 

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-script-fields.html

I have found NewScriptField in this library but am unable to find any way to use it to bring back computed fields in a query.

Is this supported? The docs and tests don't seem to reference any such functionality so just making sure one way or the other.

**Comment by olivere** [comment]
Yes it is. See [this test](https://github.com/olivere/elastic/blob/release-branch.v5/search_source_test.go#L121-L139).

I added that quite some time ago. And as ES is moving very fast, be prepared for minor issues / unsupported features. If you find something, please file an issue.

**Comment by miloandmilk** [comment]
Thanks! Will do.
