### ISSUE TITLE
Deadlock in the ScrollParallel example

### ISSUE THREAD

**Issue by AndreKR** [olivere/elastic#594]
In my application I'm using the scroll API and I'm running into a small problem. I'm not entirely sure but I _think_ the [ScrollParallel example](https://github.com/olivere/elastic/wiki/ScrollParallel) suffers from the same problem:

When an error happens in the second goroutine, for example during the Unmarshal, the second goroutine returns. This cancels the context, which theoretically would terminate the first goroutine during the next loop cycle. However, the first goroutine will never reach that check because it's hanging in the channel write (nothing is consumed from `hits` anymore because the second goroutine exited already).
I think for this to work properly the channel write and the ctx.Done() read have to be in the same `select`.

**Comment by olivere** [comment]
That sounds plausible to me. Can you test what happens if you put the `select` into the hits loop?

```
// Send the hits to the hits channel
for _, hit := range results.Hits.Hits {
	select {
	case hits <- *hit.Source:
	case <-ctx.Done():
		return ctx.Err()
	}
}
```

**Comment by AndreKR** [comment]
Yep, now `g.Wait()` returns.

**Comment by olivere** [comment]
Thanks for reporting. Just fixed the code in the Wiki.
