### ISSUE TITLE
elastic: Error 400 (Bad Request): Failed to parse content to map [type=parse_exception]

### ISSUE THREAD

**Issue by Fossil01** [olivere/elastic#598]
### Which version of Elastic are you using?

elastic.v5 (for Elasticsearch 5.x)

### Please describe the actual behavior
When trying to do something with Elastic from Go it throws the following error:
`elastic: Error 400 (Bad Request): Failed to parse content to map [type=parse_exception]`

Clean Elastic install, curl requests work fine om port 9200.

**Comment by jimfilippou** [comment]
Why is this closed?

**Comment by xujiangze** [comment]
check json format
