### ISSUE TITLE
How do I append to (and remove from) arrays in an existing Elastic Search doc?

### ISSUE THREAD

**Issue by sea350** [olivere/elastic#601]
### Which version of Elastic are you using?
[ ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
Append to an existing array in a specific ES document

### Please describe the actual behavior
elastic: Error 400 (Bad Request): failed to execute script [type=illegal_argument_exception]
or
no error but no changes committed either

### Any steps to reproduce the behavior?

Consider the following go struct, representing a type in ES:

    type Post struct{
        Content    string
        Likes   []string
    }

How would one go about appending and removing specific likes using this package? 

Through searching, the closest thing I got to append directly from ES is as follows:

    script := elastic.NewScript("ctx._source.Likes += Like").
    	Param("Like", newLikerID).
    	Lang("groovy")

    resp, err := elastic.NewUpdateService(eclient).
    	Index(ENTRY_INDEX).
    	Type(ENTRY_TYPE).
    	Id("AV5yAitA0M7oYBrcyH_q").
    	Script(script).
    	Do(ctx)

we also tried

    resp, err := elastic.Update.(eclient).
    	Index(ENTRY_INDEX).
    	Type(ENTRY_TYPE).
    	Id("AV5yAitA0M7oYBrcyH_q").
    	Script(script).
    	Do(ctx)

But the execution of this generates the error above.

**Comment by olivere** [comment]
The `illegal_argument_exception` indicates that the update failed. The best way to debug this is to first find the correct way to do so with a pure REST call, then translate that into Go code.

You might also want to have a look at the [tests](https://github.com/olivere/elastic/blob/release-branch.v5/update_test.go). They should give you some hints into how to use the API.

**Comment by mrb721** [comment]
Hello, is it possible to use the API to handle simultaneous changes to a document? Suppose I'm creating a forum with posts containing an array of posts to act as comments. If more than one comment is added simultaneously, how would the API or Elasticsearch prevent one comment form overwriting the other?

**Comment by olivere** [comment]
@mrb721 ES supports [partial updates](https://www.elastic.co/guide/en/elasticsearch/guide/current/partial-updates.html) via the [Update API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html). That's the only way to modify documents in-place. More often, in larger installations, you simply reindex data with the Bulk API, sometimes with a sliding window technique. See [Modeling data](https://www.elastic.co/guide/en/elasticsearch/guide/current/modeling-your-data.html) in the Definite Guide.

Please make sure to not treat ES as a SQL database. Although they share some ideas, their concepts and goals are different.

**Comment by thejuniordevops** [comment]
I wonder if it is possible to index new data into existing index using your package. I tried to use NewBulkIndexRequest but there is no data inserted if the index already exists. I wonder if you have a solution.

**Comment by olivere** [comment]
@thejuniordevops If you want do to bulk updates, use a `BulkUpdateRequest`. If you want to update outside the Bulk API, use the Update API which allows partial updates. This is more of an Elasticsearch problem, not a problem related to the Go driver. You might be better off to ask this on discuss.elastic.co.
