### ISSUE TITLE
Create interface for http client

### ISSUE THREAD

**Issue by shz117** [olivere/elastic#602]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[x] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
As a user I'd like to insert my own http client implementation (with customized filter/logger etc)

### Please describe the actual behavior
[SetHttpClient](https://github.com/olivere/elastic/blob/v5.0.45/client.go#L429) method only takes http.Client concrete type as parameter.
As mentioned in [this link](https://github.com/golang/go/issues/16047), the proper way is for olivere.elastic to define an interface, so users can insert a implementation to it.

### Any steps to reproduce the behavior?
see SetHttpClient implementation.

**Comment by olivere** [comment]
You typically use a `http.RoundTripper` for that. It's a bit more low-level, but it works fine and is most common way to configure a `http.Client`. See [the Wiki](https://github.com/olivere/elastic/wiki/HttpTransport) for some examples.
