### ISSUE TITLE
Scripts that use Param don't work

### ISSUE THREAD

**Issue by cmitchell** [olivere/elastic#603]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[X] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behaviorwhe
When  using the Param function to substitute parameters into a script, I expect the value to be substitute for the named key.

### Please describe the actual behavior
The substitution either doesn't take place, or something else causes ES to output
"Query execution failed": "Elasticsearch query failed: elastic: Error 500 (Internal Server Error): all shards failed [type=search_phase_execution_exception]"
Removing the Param() and just hardcoding, or doing good old fashioned concatenation of the script string and the variable works just fine, so this is NOT caused by the query itself.

### Any steps to reproduce the behavior?

In my case, I'm trying to add a script to an aggregation. The source of the aggregation, using the Param() looks like this

 map[terms:map[script:map[inline:if (doc['commsCluster.commsNode.role'].getValue() == 'DEST' ) { String val = doc['commsCluster.commsNode.identifiers.value'].getValue(); return val.substring(0, val.indexOf(delimiter)) } params:map[delimiter::]] size:50]] <nil>
(the delimiter is actually meant to be a :)

The golang code that produced that map looks like this
							agg.Script(elastic.NewScriptInline("if (doc['"+conditionPath+"'].getValue() == '"+condition.Value+"' ) { String val = doc['"+path+"'].getValue(); return val.substring(0, val.indexOf(delimeter)) }").Param("delimeter", ":"))

**Comment by olivere** [comment]
@cmitchell Elastic doesn't do anything with your string. It just passes it through, so I'm 99% sure that something is wrong with the script and/or language you used.

Can you please transform it to a pure REST API call? Then I can probably help you transform it into Go code. You might also want to look at the [script tests](https://github.com/olivere/elastic/blob/release-branch.v5/script_test.go).

**Comment by cmitchell** [comment]
Simply removing the Param() and hardcoding it entirely in the script works fine, so I'm sure the query itself is ok.  It seems to be an issue related to using the Param() function, i.e. the Param() function is not inserting the value from the params map into the script string.  Thanks for pointing me to the script_test.go file, but I already referenced that before posting this issue.

But here's the REST version that you asked for (and that succeeds).

GET _search?type=nanostorm-event
{
  "query": {
    "match_all": {}
  },
  "aggs": {
    "type-agg": {
      "nested": {
        "path": "commsCluster"
      },
      "aggs": {
        "term-agg": {
          "terms": {
            "script": {
              "inline": "if (doc['commsCluster.commsNode.role'].getValue() == 'DEST') { String val = doc['commsCluster.commsNode.identifiers.value'].getValue(); return val.substring(0, val.indexOf(':')) }"
            }
          }
        }
      }
    }
  }
}

**Comment by olivere** [comment]
When using painless, you need to reference parameters with the `params` namespace: `val.indexOf(params.delimeter)` instead of `val.indexOf(delimeter)`. See [here](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/modules-scripting-using.html#modules-scripting-file-scripts).

**Comment by cmitchell** [comment]
Thanks for the help. That solved my problem.  It wasn't clear from the tests you pointed me to because 2 of the 3 test functions in script_test.go don't have the .Lang() specified and the default if not specified is painless, yet those same tests also do not use the params

**Comment by olivere** [comment]
You're welcome.

The tests in `script_test.go` are unit test, not integration tests, i.e. they test if Elastic does generate correct JSON. But I agree that it's confusing, and it should at least use the correct syntax. Maybe you can send a PR to fix the tests.
