### ISSUE TITLE
Bool Query + scriptFields not working

### ISSUE THREAD

**Issue by aymone** [olivere/elastic#605]
### Elastic Search version
[x] elastic.v5 (for Elasticsearch 5.x)

### Expected behavior
https://github.com/olivere/elastic/blob/1b6288276d21f325205641da265aed5978e2a5a1/search_source_test.go#L125

###  Actual behavior
```
query := elastic.NewBoolQuery()
query.Filter(elastic.NewRangeQuery("sample").Lte(1))
r, err := e.Search().
                Index(IndexID).
		Query(query).
		ScriptFields(elastic.NewScriptField("test", elastic.NewScript("doc['sample'].value * 2")))
		
```
output: 
```
e.Search().Query(query).ScriptFields undefined (type *elastic.SearchService has no field or method ScriptFields)
```

### Steps to reproduce

just try use scriptFields with bool query

Elastic Search source code example:
```
GET index/_search
{
  "query": {
    "bool": {
      "filter": [
        {
          "range": {
            "sample": {
              "lte": 1
            }
          }
        }
      ]
    }
  },
  "script_fields": {
    "test": {
      "script": {
        "lang": "expression",
        "inline": "(doc['sample'].value * 2)
      }
    }
  }
}

```

**Comment by olivere** [comment]
Scripting seems to be hitting a moving target. Had a similar issue just yesterday.

Script fields do work, but the syntax is misleading. And I think this is even true for [the documentation](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/search-request-script-fields.html).

If you use the `params` prefix/namespace, everything works fine here:

Does *not* work:

```
$ curl 'localhost:9200/elastic-test/order/_search?pretty=true' -d '{"query":{"match_all":{}},"script_fields":{"test1":{"script":"doc['price'].value"}}}'
...
```

Does work:

```
$ curl 'localhost:9200/elastic-test/order/_search?pretty=true' -d '{"query":{"match_all":{}},"script_fields":{"test1":{"script":"params.doc.price.value * 2"}}}'
```

**Comment by aymone** [comment]
At elastic search works fine... i need help to use the LIB.

**Comment by olivere** [comment]
Here's an [example of using script fields](https://github.com/olivere/elastic/blob/release-branch.v5/search_source_test.go#L121-L139), and here's an example of using [SearchSource](https://github.com/olivere/elastic/blob/release-branch.v5/search_test.go#L662-L674).

Let me know if you need something else.

**Comment by aymone** [comment]
@olivere But i need help to use with bool query....

**Comment by olivere** [comment]
@aymone There's [many tests](https://github.com/olivere/elastic/blob/release-branch.v5/search_queries_bool_test.go) that may help.

**Comment by olivere** [comment]
@aymone You need to set up a `SearchSource`, then pass that to the search service. `SearchSource` is like a placeholder for the query + all options for search. Java API has the same.

Something like this (not tested):

```go
boolQ := elastic.NewBoolQuery().Must(elastic.NewTermQuery(...))...
src := elastic.NewSearchSource().
  Query(boolQ).
  ScriptFields(...).
  From(0).
  Size(2)
res, err := client.Search().
		Index("index-name").
		SearchSource(src).
		Do(context.TODO())
	if err != nil {
		t.Fatal(err)
	}
```

**Comment by aymone** [comment]
Ok, thanks for this example, i will try to implement this.

**Comment by aymone** [comment]
@olivere This worked for me!!!!
