### ISSUE TITLE
Range Query

### ISSUE THREAD

**Issue by parvathi-nair** [olivere/elastic#606]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
**Purpose: I want to want to find documents that have age gt > 10**

Based on the Elasticsearch Documentation: https://www.elastic.co/guide/en/elasticsearch/reference/5.2/query-dsl-range-query.html
query": {
        "range" : {
            "age" : {
                "gt" : 10
            }
        }
}

### Please describe the actual behavior
**Here is the generated query from the elastic generated query for RangeQuery. I created a RangeQuery -** 

```
case LT, GT, GTE, LTE:
                rangeQuery := elastic.NewRangeQuery(keyword)
                if op == "lt" {
                        rangeQuery.Lt(value)
                } else if op == "lte" { //GT Case
                        rangeQuery.Lte(value)
                } else if op == "Gte" { //GTE Case
                        rangeQuery.Gte(value)
                } else { //GT Case
                        rangeQuery.Gt(value)
                }
```

This seems to get transformed to this query.
 ```
"range":{  
      "age":{  
         "from":10,
         "include_lower":false,
         "include_upper":true,
         "to":null
      }
   }
```

**Is this a valid query. It does not return any result in my case.
Shouldn't the Source Code of Range Query be transforming query to include gt, gte, lt, and lte instead of 
from, to, include_lower, include_upper?**

### Any steps to reproduce the behavior?

Yes, create a normal range query in any elastic search later than 5.x

**Comment by olivere** [comment]
Yes. This is exactly how the [Java API](https://github.com/elastic/elasticsearch/blob/5.6/core/src/main/java/org/elasticsearch/index/query/RangeQueryBuilder.java#L180-L185) does it as well.

If you find an issue, let me know.

**Comment by dearboll** [comment]
I met the same problem when I am trying to build a time range query based field '@timestamp'. How can I solve this problem?

**Comment by olivere** [comment]
@dearboll There are [some tests](https://github.com/olivere/elastic/blob/release-branch.v6/search_queries_range_test.go) to illustrate usage.

**Comment by dearboll** [comment]
@olivere Thanks a lot. What confused me is how to combine the range query with bool query. How can I do it ?

**Comment by olivere** [comment]
@dearboll That's something along the lines of:

```
rq := elastic.NewRangeQuery(...)
bq := elastic.NewBoolQuery().Must(rq).Should(...).MustNot(...).ShouldNot(...).PostFilter(...)
```

See [the bool query test file](https://github.com/olivere/elastic/blob/release-branch.v6/search_queries_bool_test.go) for an example as well.

**Comment by dearboll** [comment]
Thank you so much!~
