### ISSUE TITLE
Match Phrase Prefix Query is called using "phrase_prefix"

### ISSUE THREAD

**Issue by rgejji** [olivere/elastic#607]
### Which version of Elastic are you using?

- [x] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior

According to the elasticsearch documentation:
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query-phrase-prefix.html

a match phrase prefix query should be called with "match_phrase_prefix"

### Please describe the actual behavior

Currently "phrase_prefix" is created and tested against in the unit tests

### Any steps to reproduce the behavior?

Create a function using NewMatchPhraseQuery and observe the lucene is incorrect and fails on elasticsearch

**Comment by rgejji** [comment]
I am observing that the lucene is being made is of the form 
{
 "match": "fieldname",
  "query": "value",
  "type": "phrase_prefix"
}

I don't see this as currently supported on ES's api  and noticed a problem with missing a custom analyzer when I used this lucene, which fails, vs.
{
    "multi_phrase_prefix": 
    {
       "field": { 
           "query": "value"
    }
}
which succeeds.

**Comment by olivere** [comment]
Thanks for bringing this up. I will address this in the next update.

#609 seems to be related, or even a duplicate. I'll find out.

**Comment by olivere** [comment]
I fixed this in 4ca1c1181fb40a6ca2cab98f88e08247e2d6ba52, or version 5.0.47.
