### ISSUE TITLE
How to use geo point in a right way

### ISSUE THREAD

**Issue by liu1700** [olivere/elastic#61]
how to store a geo_point in my structs.  When i define a location in my struct and create a index for it. It will be mapped as 
![image](https://cloud.githubusercontent.com/assets/6064238/7006913/87d5e560-dcb7-11e4-8873-9d5eb7e7152b.png)
but not a 
![image](https://cloud.githubusercontent.com/assets/6064238/7006925/a9677fae-dcb7-11e4-8467-4bbd76c8f365.png)

**Comment by olivere** [comment]
Hi! Is your problem a) creation of the index or b) storing geo points while indexing?

For a), it's up to you to provide a correct mapping.
For b), you're responsible for providing a Geo Point to ES [in a supported format](http://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-geo-point-type.html#_input_structure).

For b), Elastic has [helpers for geo points](https://github.com/olivere/elastic/blob/master/geo_point.go) (see also the [test](https://github.com/olivere/elastic/blob/master/geo_point_test.go)).

Maybe also [SuggesterContextGeo](https://github.com/olivere/elastic/blob/master/suggester_context_geo.go#L86) gives you an idea how to work with Geo Points.

**Comment by liu1700** [comment]
Thanks for your answer! It helps me a lot
