### ISSUE TITLE
Interesting Question - codebase

### ISSUE THREAD

**Issue by y00rb** [olivere/elastic#611]
I saw you putting most codes on root_path, and functionality codes and test codes in same path.
any benefit? or only habit(one kind of practice)? Do you have programming by meta-programming?

**Comment by olivere** [comment]
Thanks for asking. :-)

The main reason is that this library started in 2012. That's a long time before the dust on Go coding standards and good practices settled.

So while I would do things a bit different now, it also has its positive sides. E.g. if you were to put all search-related queries into package `"elastic.go/search/queries"` and all aggregations into `"elastic.go/search/aggs"`, you would more often than not always import all of these packages when performing a search. Without the extra packages you can just import anything with a one-line import. And when you had to mix Elastic with other search-related things in your code, you would probably even have to alias the `"elastic.go/search/queries"` as `esqueries "elastic.go/search/queries"` to prevent name clashes.

Notice I'm not saying that the above slicing of namespaces would be a good idea. I'm just trying to say that sometimes the naive way of organizing code also has its benefits.

I'm not sure what you mean by "programming by meta-programming"?

**Comment by y00rb** [comment]
Thank you for explaining!
Imagine the huge files in root, so hard to manage, so I thought you might have scripts to generating the functionality codes, that is I said "mete-programming"(coding by codes 😄 )

**Comment by olivere** [comment]
@y00rb Oh, I see. Yes, there is a generator in the [`generate-api` branch](https://github.com/olivere/elastic/tree/generate-api/generator). It reads the [REST API spec](https://github.com/elastic/elasticsearch/blob/6.x/rest-api-spec/README.markdown) and builds Go code from it.

It's not perfect, i.e. you have to edit the generated files afterwards and fix a few things. But yes, that's how most of the services have been generated.

HTH.
