### ISSUE TITLE
Client is never closed

### ISSUE THREAD

**Issue by ComeBurguburu** [olivere/elastic#612]
[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[x] elastic.v5 (for Elasticsearch 5.x)

In the documentation the elastic client is never close and cause CPU consomation because a new client is created after each call and the background context is never close.

The solution is to close the client in a defer after creating it (solution by @metal3d)

```````````````````````````````````````````````````go// Create a client
client, err := elastic.NewClient()
if err != nil {
  // Handle error
  panic(err)
}
defer client.Stop()
```````````````````````````````````````````````````````````
I update the wiki page but we must update each example to close client 
Regards

**Comment by olivere** [comment]
A client is stopped when the program exits. So there usually is no need to close the client manually.

Which wiki page did you refer to?

**Comment by olivere** [comment]
Ah... I see it's [this page](https://github.com/olivere/elastic/wiki/Client). Yes, it's a good idea to add it to the example code there. Thanks.

**Comment by ComeBurguburu** [comment]
I forgot to mention that I used elastic in an API so the program never end. Each handler use is own client to allow parallel  call

**Comment by olivere** [comment]
@ComeBurguburu You mean an API server, or in a library that builds upon Elastic? The latter would really make it different. It might be a good example to use the [`SimpleClient`](https://github.com/olivere/elastic/blob/release-branch.v5/client.go#L336-L351) then, depending on the kind of library. Using `NewSimpleClient` doesn't set up any background goroutines or such.

You might also allow the client to pass an instance to `*elastic.Client`, so that the caller itself is responsible on instantiating and managing the client. YMMV.

**Comment by ComeBurguburu** [comment]
An API server

**Comment by olivere** [comment]
Okay, so that's a long running service. It should only create one `*elastic.Client` when it starts up, and use that throughout the application. A `Client` instance is safe for use from multiple goroutines.

**Comment by metal3d** [comment]
@olivere right, that's not a bad idea to have only one client but I've got two questions to be able to make it working as we want:
- is there a way to check if client is always connected (to recreate a connection if needed) ?
- what if several API requests need to use the client ? Our API will probably need 10 call/API request, and that for more that 10 client/s (and maybe more later)

I'm afraid about bottlenecks... :)

A last suggestion: Go convention is to use a .Close() method, can you add a simple function alias calling .Stop() to respect that convention ? (Yes, we can make a simple composition to add it, but I tell that for the base project ;) )

**Comment by metal3d** [comment]
Precision, I will check SimpleClient anyway. And thanks for your quick answers (and for you package)

**Comment by olivere** [comment]
@metal3d Thanks for your suggestions. Let me address them one by one.

There is the [`IsRunning`](https://github.com/olivere/elastic/blob/release-branch.v5/client.go#L696-L702) method, but it isn't quite helpful as it is always set to `true` if you initialize a client with `NewClient` or `NewSimpleClient`.

You can `Start` and `Stop` a client, so while `Close` is more common, it's not the opposite of `Start`. I find it a rather minor issue, really.

Elastic doesn't use a persistent connection to connect to ES but uses straightforward HTTP request/response. So if you have issues with that, you can pretty much translate them to issues with HTTP request/response in plain-old Go (and I've yet to see a performance bottleneck with that).

What Elastic does is when you run `NewClient` is start background processes to perform healthchecks and sniff new nodes/remove old nodes. The whole process is what all official clients implement and is described in [the Wiki](https://github.com/olivere/elastic/wiki). When you use `NewSimpleClient`, there are no goroutines started and you're responsible for handling problems when ES nodes go down or are added to the cluster.
