### ISSUE TITLE
Is there a way to see what request you're sending?

### ISSUE THREAD

**Issue by kamok** [olivere/elastic#613]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[x] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
I wish to know if it's possible to write a query with elastic, and see the exact http request that's being made.

**Comment by olivere** [comment]
Sure. Just enable [trace logging](https://github.com/olivere/elastic/wiki/Logging).

**Comment by kamok** [comment]
@olivere Thanks you very much for your timely and cordially response.
