### ISSUE TITLE
Missing MaxExpansions method in MatchPhrasePrefixQuery of v5

### ISSUE THREAD

**Issue by tiago4orion** [olivere/elastic#615]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[x] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior

In elastic.v3, the MatchPhrasePrefixQuery had a MaxExpansions method:
https://godoc.org/gopkg.in/olivere/elastic.v3#MatchQuery.MaxExpansions

but in v5 it was refactored in a new struct type [MatchPhrasePrefixQuery](https://godoc.org/gopkg.in/olivere/elastic.v5#MatchPhrasePrefixQuery) but the `MaxExpansions` is missing.

### Please describe the actual behavior

No way to cap the max expansions of a prefix phrase query.

**Comment by tiago4orion** [comment]
@olivere Would you accept a PR for adding the method? Or this is working as intended?

**Comment by olivere** [comment]
@tiago4orion Ah well... the [field is there](https://github.com/olivere/elastic/blob/release-branch.v5/search_queries_match_phrase_prefix.go#L17), but the method is missing. A PR would be helpful, thanks in advance.

**Comment by olivere** [comment]
Will be available soon in 5.0.48.

**Comment by tiago4orion** [comment]
Thanks ;)
