### ISSUE TITLE
Nil pointer dereference

### ISSUE THREAD

**Issue by swizzley** [olivere/elastic#616]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[x] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
scroll through results, returning results

### Please describe the actual behavior
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x123d126]

goroutine 856867 [running]:
gopkg.in/olivere/elastic%2ev3.(*Client).PerformRequestC(0x0, 0x0, 0x0, 0x130b559, 0x4, 0xc43204baa0, 0x18, 0xc4322475f0, 0x12b3ba0, 0xc432247620, ...)
	~/go/src/gopkg.in/olivere/elastic.v3/client.go:1111 +0x86
gopkg.in/olivere/elastic%2ev3.(*ScrollService).first(0xc432354000, 0x0, 0x0, 0xc431b625d8, 0xc432057f80, 0xc431b62758)
	~/go/src/gopkg.in/olivere/elastic.v3/scroll.go:279 +0x137
gopkg.in/olivere/elastic%2ev3.(*ScrollService).DoC(0xc432354000, 0x0, 0x0, 0xc431b62678, 0xc431b62670, 0xc425a26540)
	~/go/src/gopkg.in/olivere/elastic.v3/scroll.go:230 +0x88
gopkg.in/olivere/elastic%2ev3.(*ScrollService).Do(0xc432354000, 0x131bff8, 0xc431e82000, 0xc432057f80)
	~/go/src/gopkg.in/olivere/elastic.v3/scroll.go:220 +0x3d

### Any steps to reproduce the behavior?

My best guess as to why this is happening that perhaps my server is getting overwhelmed... I see similar behavior for no apparent reason occasionally when accessing NewClient()

Any thoughts or suggestions would be greatly appreciated. I'm beginning to wonder if I should switch to the v5 client to see if these problems go away.

**Comment by olivere** [comment]
It looks like you're not checking errors when creating the client.

If you still think you don't know what's wrong, show me the code :-)

**Comment by swizzley** [comment]
yeah, you nailed it. Thank you
