### ISSUE TITLE
Why doesn't Index service have a Doc function?

### ISSUE THREAD

**Issue by buchanae** [olivere/elastic#618]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[x] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior

```
type Foo struct {
  // ...fields
}
f := Foo{}

es.Index().
  Index("index-name").
  Type("type-name").
  Id("id-1").
  Doc(&f).
  Do(ctx)
```

### Please describe the actual behavior

IndexService does not have a function `Doc`. I resorted to using `json.Marshal` and `BodyString`.

I'm sure there's a good reason, but I couldn't find an answer in the docs. 

Related question is, what's the best way to insert a new document of a given type?

Thanks!

**Comment by olivere** [comment]
Hey there. Nowadays, there's no good reason to now use a single `Doc` for passing the body, be it a `string` or a `map[string]interface{}` or anything that is serializable to JSON. I guess it's just history. I've always tried to stay close to the Java code, and they probably used `setBodyString(...)` and `setBodyJson(...)` in the Java API years ago.

There is [`BodyJson(...)`](https://github.com/olivere/elastic/blob/release-branch.v5/index.go#L149) and [`BodyString(...)`](https://github.com/olivere/elastic/blob/release-branch.v5/index.go#L155) now.

Regarding your 2nd question: I don't quite understand. You pass the `Type(...)` like you did in your example code. Notice that [ES 6.0 deprecates types](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/removal-of-types.html). In the long run, there will be only indices.

**Comment by buchanae** [comment]
> Hey there. Nowadays, there's no good reason to not use a single Doc for passing the body, be it a string or a map[string]interface{} or anything that is serializable to JSON. I guess it's just history. I've always tried to stay close to the Java code, and they probably used setBodyString(...) and setBodyJson(...) in the Java API years ago.

Fair enough.

> Regarding your 2nd question: I don't quite understand. You pass the Type(...) like you did in your example code. Notice that ES 6.0 deprecates types. In the long run, there will be only indices.

I guess I was wondering if Update() + DocAsUpsert(true) was better. You answered my question indirectly. Interesting that they'll deprecate types, I guess that makes sense?

Thanks!
