### ISSUE TITLE
decoder should be a global, not everywhere reference encoding / json

### ISSUE THREAD

**Issue by zplzpl** [olivere/elastic#621]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

 elastic.v5 (for Elasticsearch 5.x)

**Comment by olivere** [comment]
I don't understand. Can you explain with an example? Did you notice that you [can configure your own decoder](https://github.com/olivere/elastic/wiki/Decoder)?

**Comment by olivere** [comment]
Closing until I get more details.
