### ISSUE TITLE
about func (c *Client) newResponse(res *http.Response) 

### ISSUE THREAD

**Issue by zplzpl** [olivere/elastic#622]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?
[*] elastic.v5 (for Elasticsearch 5.x)

json package:
`
type RawMessage []byte
`

elsatic package:
`// Response represents a response from Elasticsearch.
type Response struct {
	// StatusCode is the HTTP status code, e.g. 200.
	StatusCode int
	// Header is the HTTP header from the HTTP response.
	// Keys in the map are canonicalized (see http.CanonicalHeaderKey).
	Header http.Header
	// Body is the deserialized response body.
	Body json.RawMessage
}

// newResponse creates a new response from the HTTP response.
func (c *Client) newResponse(res *http.Response) (*Response, error) {
	r := &Response{
		StatusCode: res.StatusCode,
		Header:     res.Header,
	}
	if res.Body != nil {
		slurp, err := ioutil.ReadAll(res.Body)
		if err != nil {
			return nil, err
		}
		// HEAD requests return a body but no content
		if len(slurp) > 0 {
			if err := c.decoder.Decode(slurp, &r.Body); err != nil {
				return nil, err
			}
		}
	}
	return r, nil
}`

slurp data type has been [] byte, why do you need to decode for *json.RawMessage???

**Comment by olivere** [comment]
Good point, thank you. On the first tests, this is a clear win, reducing JSON serialization time from ~1500 ns/op to ~1000 ns/op. Amazing!

See a220ed3647601882a8d6c140c87436a0270260e8

**Comment by olivere** [comment]
Thanks a lot. This will be part of 5.0.53, which will be released soon. 👍

**Comment by agbetz64** [comment]
Have you ever considered/tested jsoniter?

**Comment by olivere** [comment]
@agbetz64 No. I want to stay close to the standard library. But you can [use your own `Decoder`](https://github.com/olivere/elastic/wiki/Decoder) if you like.

**Comment by olivere** [comment]
@agbetz64 @zplzpl There is performance-related work on the way in #667 to increase performance for at least Bulk API. If you have time to support/review/test, that'd be appreciated.
