### ISSUE TITLE
Force refresh = bad request

### ISSUE THREAD

**Issue by arthurgustin** [olivere/elastic#624]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[x] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
I don't know what the behavior should be, I just tried the Force() refresh option

### Please describe the actual behavior
```
Error 400 (Bad Request): request [/privileges/_refresh] contains unrecognized parameter: [force] [type=illegal_argument_exception]
```

### Any steps to reproduce the behavior?
```
_, err = esClient.Refresh("yourIndex").Force(true).Do(ctx)
```

**Comment by olivere** [comment]
Interesting. [It's been removed in v6](https://github.com/elastic/elasticsearch/commit/c5b79cd46021075e3696eee3b6bae45d71af31fa) but I cannot find anything in the list of [breaking changes for 5.x](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes.html).

According to [#25234](https://github.com/elastic/elasticsearch/issues/25234), other clients have been hit by this as well.

I will add it to the list of changes for the next release.

**Comment by olivere** [comment]
The `force` parameter will be removed in 5.0.53 which will be released soon. Thanks!
