### ISSUE TITLE
Client logs non-obvious error on failure to verify https endpoint

### ISSUE THREAD

**Issue by tanner-bruce** [olivere/elastic#625]
[x] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
Receive an error message related to the issue

### Please describe the actual behavior
Receive an error message: `"no Elasticsearch node available"`

### Any steps to reproduce the behavior?
Have elastic behind a reverse proxy. Run the elastic client in an environment without ca-certificates

**Comment by olivere** [comment]
Elastic simply uses `net/http` under its covers. You can provide your own `*http.Client` via options or configure a `http.RoundTripper`, so it should be fairly flexible for all environments.

The `"no Elasticsearch node available"` error is typically invoked when initial health checks fail when the client is started. This is probably the most common error I see with Elastic. You can e.g. disable sniffing or health checks, or use `elastic.NewSimpleClient` if you want a simple "throwaway" client that just executed your HTTP requests. Read all the details in [the wiki](https://github.com/olivere/elastic/wiki).
