### ISSUE TITLE
Get status code in SearchService.Do()

### ISSUE THREAD

**Issue by arthurgustin** [olivere/elastic#626]
### Which version of Elastic are you using?

[x] elastic.v5 (for Elasticsearch 5.x)

Hi, I want to do asserts on status code after the SearchService Do() function. The reason is that we use x-pack, and we want to generate understandable error message when elastic respond with 403 or 401.
I looked in the code, and it seems we lose the information here: 

https://github.com/olivere/elastic/blob/release-branch.v5/search.go#L388-L398

**Comment by olivere** [comment]
If you receive an error from Elasticsearch, it should be an error of [this kind](https://github.com/olivere/elastic/blob/release-branch.v5/errors.go#L62-L66). This error contains the Status code of the response. For certain errors, we have helpers such as [`IsNotFound(...)`](https://github.com/olivere/elastic/blob/release-branch.v5/errors.go#L92-L97).

If you want to check for a specific status code, you can use [`IsStatusCode(...)`](https://github.com/olivere/elastic/blob/release-branch.v5/errors.go#L115-L130).

**Comment by arthurgustin** [comment]
Hi, thank you for your fast answer !
Maybe (and I hope !) I missed something, but, this function only returns a pointer to a SearchResult, and I think the helper function you provided won't work.

```
// Do executes the search and returns a SearchResult.
func (s *SearchService) Do(ctx context.Context) (*SearchResult, error) {
	// Check pre-conditions
	if err := s.Validate(); err != nil {
		return nil, err
	}

	// Get URL for request
	path, params, err := s.buildURL()
	if err != nil {
		return nil, err
	}

	// Perform request
	var body interface{}
	if s.source != nil {
		body = s.source
	} else {
		src, err := s.searchSource.Source()
		if err != nil {
			return nil, err
		}
		body = src
	}
	res, err := s.client.PerformRequest(ctx, "POST", path, params, body)
	if err != nil {
		return nil, err
	}

	// Return search results
	ret := new(SearchResult)
	if err := s.client.decoder.Decode(res.Body, ret); err != nil {
		return nil, err
	}
	return ret, nil
}
```

**Comment by olivere** [comment]
The `Do(...)` method returns a `*SearchResult` and an `error`. The `error` is the one you can pass to the helper functions.

**Comment by arthurgustin** [comment]
Well I definitively missed something, thank you it works as expected :)
