### ISSUE TITLE
Deprecation warning: `Deprecated field [inline] used, expected [source] instead`

### ISSUE THREAD

**Issue by olivere** [olivere/elastic#627]
This probably has something to do with inline scripts. Need to review.

**Comment by mddos** [comment]
In 5.6 they switched from having the scripting payload field name from being called inline to calling it source.  The source field name is not backwards compatible.

**Comment by olivere** [comment]
@mddos Exactly. That's why I created this issue. It should be pretty easy to resolve. Interested?

**Comment by mddos** [comment]
@olivere  I will take a stab at this issue.

**Comment by olivere** [comment]
Fixed with in v5 with 3c424ca8458cd544edee9e16f798d99fcb61e373 and in v6 with fa15f3c405f42c70ed51edc98bb7a18b5209a814.
