### ISSUE TITLE
aggregation/subaggregation problem v5

### ISSUE THREAD

**Issue by agbetz64** [olivere/elastic#628]
[ ] elastic.v5 (for Elasticsearch 5.x)

I am trying to get a query to work but it appears to stick a "terms" {} at the end which causes the query to fail otherwise it would work. Furthermore,  I would like to show one record with the aggregations attached. I cannot find any documentation regarding this.

The desired query

{ "size": 1
    ,"_source": ["brand_link", "brand", "shop", "domain"]
    ,"query": 
        { "bool": 
            { "filter": [ { "term" : { "brand_link": "bubu" } } ] } 
        } 
    ,"aggs" : 
        { "serie": { 
            "terms": { "field": "serie", 	  "size" : 100 }
            ,"aggs": { "serie_link" : { "terms": { "field": "serie_link" }},
                        "shop" : { "terms": { "field": "shop" }}
                     }
            }
        ,"category": { 
            "terms": { "field": "category", "size" : 100 }
            ,"aggs": { "category_link" : { "terms": { "field": "category_link" }},
                        "shop" : { "terms": { "field": "shop"}}
                    }
            }
        ,"pBFNuNa" : { 
            "terms": { "field": "pBFNuNa", "size" : 200 }
            ,"aggs": { "pattern_link" : { "terms": { "field": "pattern_link" }}
            }
        }
    }
}

my attempt to get the aggregations to work:

slink := elastic.NewTermsAggregation().Field("serie_link")
sshop := elastic.NewTermsAggregation().Field("shop")
serieaggr := elastic.NewTermsAggregation().Field("serie").Size(100)
serieaggr = serieaggr.SubAggregation("serie_link", slink)
serieaggr = serieaggr.SubAggregation("shop", sshop)

clink := elastic.NewTermsAggregation().Field("category_link")
cshop := elastic.NewTermsAggregation().Field("shop")
categoryaggr := elastic.NewTermsAggregation().Field("category").Size(100)
categoryaggr = categoryaggr.SubAggregation("category_link", clink)
categoryaggr = categoryaggr.SubAggregation("shop", cshop)

plink := elastic.NewTermsAggregation().Field("pattern_link")
patternaggr := elastic.NewTermsAggregation().Field("pBFNuNa").Size(200)
patternaggr = patternaggr.SubAggregation("pBFNuNa", plink)

agg := NewTermsAggregation()
agg = agg.SubAggregation("serie", serieaggr)
agg = agg.SubAggregation("category", categoryaggr)
agg = agg.SubAggregation("pBFNuNa", patternaggr)

**Comment by olivere** [comment]
It's looking good at first sight... I guess this line is making the empty `terms` aggregation:

```
agg := NewTermsAggregation()
```

HTH

**Comment by agbetz64** [comment]
I guess I phrased my question wrong. At the moment I 'connect' it to agg :=
NewTermsAggregation() and then use: it in the query as follows.

searchResult, err := client.Search().
    Index("stock").
    Query(query).
    Aggregation(agg).
    Do(ctx)

How do I do this without agg := NewTermsAggregation()?

As a newbie to your fantastic library, I am struggling with slightly more
complex queries.

Thanks

‌
<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

**Comment by olivere** [comment]
Thanks. You seem to be adding three different aggregations to the query. So you can do something like

```
res, err := client.Search().
  Index("stock").
  Query(query).
  Aggregation("serie", slink).
  Aggregation("category", clink).
  Do(ctx)
```

[See here](https://github.com/olivere/elastic/blob/release-branch.v6/search_aggs_test.go#L107-L111) for an example.

**Comment by agbetz64** [comment]
I find it rather tricky to get my head around retrieving sub-aggregation
into a  []struct. What I have appears to work, but I don't feel it is very
elegant. Is there a better way? Note: the query has by design always only
one item in the sub-aggregations.


type Serie struct {
Name  string
Link  string
Shop  string
Count int64
}

type BrandData struct {
Brand string `json:"brand"`
Series []Serie
}

         brand := &BrandData{}

err = json.Unmarshal(*searchResult.Hits.Hits[0].Source, brand)
if err != nil {
panic(err)
}

var count int64
var name  string
var link  string
var shop string

// get series in brand
seriesdata, found := searchResult.Aggregations.Terms("serie")
if found {
i := 0
for _, bucket := range seriesdata.Buckets {

name = bucket.Key.(string)
count = bucket.DocCount

serie_link, found := seriesdata.Buckets[i].Terms("serie_link")
if found {
link = serie_link.Buckets[0].Key.(string)
}
serie_shop, found := seriesdata.Buckets[i].Terms("shop")
if found {
shop = serie_shop.Buckets[0].Key.(string)
}

brand.Series = append(brand.Series, Serie{name, link, shop, count})

i = i + 1
}
}

‌

**Comment by olivere** [comment]
It's not too bad for my eyes:

```
package main

import (
	"encoding/json"

	"github.com/olivere/elastic"
)

type Serie struct {
	Name  string
	Link  string
	Shop  string
	Count int64
}

type BrandData struct {
	Brand  string `json:"brand"`
	Series []Serie
}

func main() {
	var searchResult *elastic.SearchResult // ...

	brand := &BrandData{}

	err := json.Unmarshal(*searchResult.Hits.Hits[0].Source, brand)
	if err != nil {
		panic(err)
	}

	seriesdata, found := searchResult.Aggregations.Terms("serie")
	if found {
		for _, bucket := range seriesdata.Buckets {
			serie := Serie{
				Name:  bucket.Key.(string),
				Count: bucket.DocCount,
			}

			links, found := bucket.Terms("serie_link")
			if found {
				serie.Link = links.Buckets[0].Key.(string)
			}
			series, found := bucket.Terms("shop")
			if found {
				serie.Shop = series.Buckets[0].Key.(string)
			}

			brand.Series = append(brand.Series, serie)
		}
	}
}
```

I still struggle to find a use case where you need a single item result with aggregations. Aggregations operate on field values of a large number of results, not on a single one. They e.g. yield averages or group results by a key. If you have a single result, shouldn't the aggregated values be part of that single result (or at least derivable from it)?

**Comment by agbetz64** [comment]
I use elastic search for most my backend of my online shops.

Let's assume a user searches for a particular brand, the link will be
onlineshop.com/karl_lagerfeld
<https://mailtrack.io/trace/link/1eff0b18119d365beb5476e56ed185967c53bbfd?url=http%3A%2F%2Fonlineshop.com%2Fkarl_lagerfeld&userId=2094524&signature=4719054d19c895b0>.
I search elastic for the url path karl-lagerfeld and aggregate on
categories, series, patterns. As a trick I sub-aggregate on serie_link,
serie_link, pattern_link and any other fields I need (always only one
result). These sub-aggregations are a low-cost trick to get additional
aggregation specific data. This way I can get my complete brand specific
navigation including product counts in each category, serie, pattern in one
single elastic query with minimal further computing requirements.  I put
everything in a struct which makes any further handling incredibly easy.


Similarly, instead of getting products by I use a filter search based on
brand/product_name/ and aggregate on size and patterns and sub-aggregate on
availability. This way I get all product specific data together with all
the patterns/colours and sizes.

An example: aggregation Bübu Sneaker, sub-aggregations availability and
link.

Bübu Sneaker, size 6, available, buebu-sneaker/size-6
Bübu Sneaker, size 7, pre-order, buebu-sneaker/size-7
Bübu Sneaker, size 8, out of stock, buebu-sneaker/size-8

A lot of the information such as the product description,
infographics, etc. is shared amongst all of them. This I get from the main
query which is again restricted to size = 1 and only lists shared fields.

This way, I get everything I need for all the links, image_links, product
specific, size, colours, and availability in one single query, which is
only marginally slower than a GET based on ID.

People always think of large data statistics when dealing with aggregations
and sub-aggregations, but you can also do very clever stuff with them
reducing the number of DB requests which people usually use to build site
navigations. It might be a slightly unconventional use case, but it makes
sites blazingly fast.









‌
<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>
