### ISSUE TITLE
Using BulkService api to send the data, some data are always failed!

### ISSUE THREAD

**Issue by BrotherGao** [olivere/elastic#629]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[*] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
I have programmed a monitor for redis. In my monitor, I use **BulkService** api to send data to ES for efficiency. I set up a crontab to run the monitor which will send 22 records to ES(ElasticSearch) every minute. If everything is ok, I can query 22 records in ES every minute.
### Please describe the actual behavior
However, I check total the number of record in ES and find that there are some records lost,i.e., less than 22 records are successfully received by ES. Then, I use **BulkResponse** api to print all **BulkResponseItem** and I found some Status of BulkResponseItem is 429 instead of 201 !!! 
I give up using crontab and run monitor manually. all Status of BulkResponseItem are 201 and I can get 22 record from ES!!!
I try to use **IndexService** instead of **BulkService** to send record one by one. Everything is ok, even if I use crontab to run my monitor. All records can be found in ES every minute. 
I'm confused!!!!

**Comment by olivere** [comment]
Hello! Let me assure you that the Bulk API works just fine. We're indexing millions of documents every day.

If the Bulk API responds with status code 429, you need to figure out why that is. A 429 status is typically used by a server (like ES) to protect itself for too many requests (see [here for a rather old article](https://www.elastic.co/blog/performance-considerations-elasticsearch-indexing) or [here for the documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/tune-for-indexing-speed.html)).

Why are there too many requests? I don't know without looking at your code. E.g. are you refreshing the results on every commit? Are you using large documents or small documents? Is there load on ES from other applications? In any way, I cannot say anything without knowing your use case.

**Comment by BrotherGao** [comment]
Hi, olivere. Thank you for your reply and suggestion.
My point is usage of crontab. When I use crontab to run my monitor, there are always some records failed! But I run monitor manually and everything is ok. All records can be insert into ES successfully!
My crontab profile is as follows：
`* * * * * root (cd /home/work/opbin/monitor_redis/bin && ./monitor > /dev/null)`
My code which send data to ES  is as follows:
```
esData := ESData{Name: "klose", Id: "123456", InsertTime: time.Now().Format("2006-01-02T15:04:05Z07:00")}
bulkRequest := esClient.Bulk()
for i := 0; i < 22; i++ {
	req := elastic.NewBulkIndexRequest().Index(_index).Type(_type).Doc(esData)
	bulkRequest.Add(req)
}
bulkResponse, _ := bulkRequest.Do()
```
The above code will only run once !!! There is no other application sending data to my ES cluster except for my monitor. I think the size of every  documents is not large and it has only three fields(name,id,insertTime).
I found whether or not to use crontab to call BulkService api will produce different results!!!

**Comment by olivere** [comment]
I guarantee that Elastic doesn't behave differently if being called by a daemon (like cron) or a shell.

As I said, a 429 status is sent from ES if being sent to many requests. I don't know why that happens in your case with cron, but that's the source of the issue. In any case, you are responsible for handling these kind of errors, not the library or Elasticsearch. How you do that depends on your application: Some don't care if entries are lost, some are much more sensitive and require retries.

**Comment by BrotherGao** [comment]
Thanks for your help! I have found the answer to the my question. I think I overestimate request processing of ES. In fact, I have more than 4000 redis instances sending data to ES every minute. the monitor run  manually is not at beginning of every minute. So every record is recived by ES successfully!
