### ISSUE TITLE
single item results

### ISSUE THREAD

**Issue by agbetz64** [olivere/elastic#630]
[x] elastic.v5 (for Elasticsearch 5.x)

A lot of my queries have single item results (with aggregations - as in product detail: name, price, availability, size[s/m/l/xl], colour[red, blue, yellow]). 
It seems cumbersome to do a 'fake' iteration to get to the result (name, price, availability) is there a better way? Maybe I am missing something as I am new to this. Iterating through the aggregations is obviously fine.

**Comment by olivere** [comment]
I don't understand. You typically extract the aggregations by name and type from the search response, like so: 

```
sizes, found := searchResponse.Aggregations.Terms("sizes")
if found {
  for _, bucket := range sizes.Buckets {
    log.Printf("Key %s, Count %d", bucket.Key, bucket.DocCount)
  }
}
```

[See here](https://github.com/olivere/elastic/blob/release-branch.v6/search_aggs_test.go#L214) for examples of the different aggregation types.

**Comment by agbetz64** [comment]
That's kind of my point. It's great for aggregations, odd for a result with
only one hit as I have to iterate through the Data, despite knowing from
the start that there will be only one hit because I set Search().Size(1). I
would assume that anybody with a product catalogue who wants to show a
detail page would have a similar search strategy. Think of a sneaker that
comes in 5 sizes and 3 colours, but with all other product details being
the same. I am just worried that I have misunderstood something
fundamentally.

[...]

    type Data struct {
        Name    string `json:"name"`
        Price     string `json:"price"`
    }

 searchResult, err := client.Search().
        Size(1).
    Index("stock").
        Query(query).
        FetchSourceContext(fsc).
        Aggregation("serie", sizeaggr).
        Aggregation("serie", colouraggr).


var ttyp Data
for _, item := range searchResult.Each(reflect.TypeOf(ttyp)) {
        t := item.(Data)
        fmt.Printf("Poduct: %s, %s\n", t.Name, t.Price)
}


‌

**Comment by olivere** [comment]
I'm still not quite sure what you're actually looking for: A helper for getting the first item of an array in case there is only one?

The use cases I've seen so far typically use the Search API for retrieving a list of results, then using the Get API to get a document by id.

If you are absolutely sure there is one and exactly one hit in your search result, and you want a shortcut for that, use something like this:

```
var v Data
doc, err := json.Unmarshal(searchResult.Hits.Hits[0], &v)
if err != nil { ... }
```

**Comment by agbetz64** [comment]
That's exactly what I was looking for, a helper to get the first (and in
this case only) item of the array. I guess the following will do, albeit a
helper function would be much nicer:

 type Data struct {
        Bubu      string `json:"bubu"`
        Waga     string `json:"waga"`
    }

   var d Data
   err = json.Unmarshal(*searchResult.Hits.Hits[0].Source, &d)
   if err != nil { panic(err) }

    fmt.Println(b)

I am a little surprised that this was never requested before. By using a
term filter search in combination with aggregations, I could 'compress'
what was previously done with 4 complex (and thus slow) MySQL queries into
one very fast elastic query. Admittedly pulling out the results turns out
to be a bit of a challenge.


Many thanks
‌
