### ISSUE TITLE
Updating the Query String Query -Top Level parameters 

### ISSUE THREAD

**Issue by mddos** [olivere/elastic#631]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[X] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
The query_string top level parameters are out of sync with the newest offerings. 

### Please describe the actual behavior
In particular the ability to access the all_fields value which tells the query sting to search all "Searchable" fields. This is a desired behavior for "Universal" Style searches. Without this forces the enumeration of all fields.

### Any steps to reproduce the behavior?
[5.6 Query String Query List] https://www.elastic.co/guide/en/elasticsearch/reference/5.4/query-dsl-query-string-query.html

### Design Theory 
The split_on_whitespace has the following verbage

Whether query text should be split on whitespace prior to analysis. Instead the queryparser would parse around only real operators. Defaults to true. **It is not allowed to set this option to false if auto_generate_phrase_queries is already set to true.**

I am not going to add any validation or attempt to **Fix** any misbuilt queries. Instead I plan on letting them just flow through and return an error from Elastic Search.  
 

 

### Notes
I am going to update all the options while in here but wanted an issue to track changes against.

**Comment by olivere** [comment]
Thanks for the hint. I will update `QueryStringQuery` for v5 and v6 based on the Java sources for the next release.

**Comment by olivere** [comment]
Notice that several fields in [`QueryStringQueryBuilder`](https://github.com/elastic/elasticsearch/blob/6.0/core/src/main/java/org/elasticsearch/index/query/QueryStringQueryBuilder.java) are deprecated in 6.0, including [`split_on_whitespace`](https://github.com/elastic/elasticsearch/blob/6.0/core/src/main/java/org/elasticsearch/index/query/QueryStringQueryBuilder.java#L102-103).

**Comment by olivere** [comment]
I will update the `QueryStringQuery` accordingly for v5 and v6. Notice however that I keep the freedom to not implement deprecated settings that have a simple workaround. In 6.0 these are e.g.:

* `all_fields` can be achieved by setting `default_field` to `*`
* `split_on_whitespace` is ignored in 6.0
* `locale`, `lowercase_expanded_terms` are ignored in 6.0, and the decision to use it is made by the analyzer
* `auto_generate_phrase_queries` is deprecated in favor of setting `type` to `phrase`
* `use_dis_max` can be replaced with setting `tie_breaker` to `1`

I think you need to plan accordingly if you want a smooth migration to ES 6.x and Elastic v6.

However, I will add the non-deprecated missing fields to v5. All changes will be available in the next release of v5 and v6.

**Comment by mddos** [comment]
Thanks for the heads up. 
From a planning point the all fields is the win I was looking for.

**Comment by olivere** [comment]
@mddos Yes. You will get that in the next release, which I'm currently working on. Should be out in a few hours.
