### ISSUE TITLE
Pattern for unit testing with interfaces?

### ISSUE THREAD

**Issue by Grindlemire** [olivere/elastic#632]
Hi!

Apologies if this is an already answered question, I was unable to find a satisfactory answer online. I am trying to find a way to write unit tests for one of my services however I feel this example could apply outside of unit tests to more general encapsulation of code.

I want to mock the client so I can simulate a specific type of request (in my case bulk requests) without going all the way to a test ElasticSearch instance. Ideally there would be an interface to allow me to generate a mock in my tests. For example what I want is an interface like so:

```Go
type IBulkClient interface {
    Bulk() IBulkService // return the BulkService interface
    ...
}

type IBulkService interface {
   Add(requests ...E.BulkableRequest) IBulkService
   Do() (IBulkResponse, error) // return the BulkResponse interface (not shown here)
   ...
}
```

This would allow me to mock `BulkClient` and `BulkService` to better test my code. The reason why I can't do this myself right now is that the real [BulkService.Add()](https://godoc.org/gopkg.in/olivere/elastic.v5#BulkService) returns a `*BulkService` which screws up the interface as I want my IBulkClient to return another interface not a pointer to a struct. 

[Here](https://play.golang.org/p/L2kbSoVvpF) is a go playground with the issue I am talking about and [here](https://play.golang.org/p/CoOupZxE-n) is it working with an interface reference rather than a pointer to a struct.

My ultimate question is this: Is it possible for the API to provide interfaces for all its structs? This would allow for better unit testing and also allow the user to better encapsulate their code. If there is a reason why there shouldn't be interfaces how do you recommend writing unit tests that don't go all the way to ElasticSearch or mocking the response at an http level?

**Comment by olivere** [comment]
Hmm... when I write unit tests I typically do so on a higher level. I don't know if that applies to your use case as well, but here's what I typically do.

Suppose I have a model like `Person` that has some kind of storage backend. Then I typically define a `Repository` interface that implements all the functions around storing and retrieving or bulk-importing data around the `Person` model. Something like this (not tested):

```
type Repository interface {
  Create(context.Context, *Person) error
  Get(context.Context, int64) (*Person, error)
  Import(context.Context, ...*Person) error
  ...
}
```

Then I'll provide different implementations of that `Repository` interface. E.g. if you use MySQL, you can implement a `MysqlRepository`, for MongoDB you use `MgoRepository`. You can of course use a combination of MySQL and Elasticsearch as well. Up to you.

For testing, I typically create a `MockRepository` with callbacks for the functions defined by the `Repository` interface. Something like this:

```
type MockRepository struct {
  OnCreate func(ctx context.Context, p *Person) error
}

func NewMockRepository() *MockRepository {
  return &MockRepository{}
}

func (r *MockRepository) Create(ctx context.Context, p *Person) error {
  return r.OnCreate(ctx, p)
}

...
```

By doing so, you can pass the `Repository` implementation of `*MockRepository` everywhere in your tests. You can also test errors in the storage engine very elegantly and very quickly.

Ben Johnson provides something similar in [github.com/benbjohnson/wtf](https://github.com/benbjohnson/wtf/blob/master/mock/mock.go).

Notice that this only works for unit tests. If you want integration tests, you probably need to hit Elasticsearch/MySQL etc.

HTH.

**Comment by Grindlemire** [comment]
Ok I can see how you might encapsulate your interface at the object level and how that might allow you to unit test your business logic. Basically you are requiring that your db interface (in your example `MysqlRepository` and `MgoRepository`) be tested using integration tests rather than unit tests but you do allow your business logic to be tested by adding a layer of abstraction.

It is not exactly ideal for me as every added layer of abstraction adds more complexity but I can see how that may be the state of the library. Thanks for your advice!

**Comment by olivere** [comment]
It's not too much abstraction layers in my experience. You wire up things in `main` and pass interfaces into the dependent components. When working on e.g. a microservice, we typically only have two or threee of those abstractions.

**Comment by mkadin** [comment]
I'd too would love to see a solution to something like this.

I have a repository layer in my code as you describe above, and I can use that to unit test my business logic at the level above.  However, what about testing the code in the repository itself?  There's logic in there responsible for parsing an ElasticSearch response - how can this be unit tested?

For instance, using your example above, the `Get` method presumably parses the response from an ES call and constructs a Person struct. That code can't be unit tested if we stay one level above.

I've gotten around this with by wrapping every struct / method I use from this library, which is a bit verbose, but works around this issue:

```
// ElasticSearchInteractor provides access to elasticsearch operations
type ElasticSearchInteractor struct {
	client SearchProvider
}

// SearchProvider allows for mocking the elastic.Client's search method.
type SearchProvider interface {
	Search(indices ...string) SearchExecutionProvider
}

// SeachExecutionProvider allows for mocking elastic.SearchService
type SearchExecutionProvider interface {
	Aggregation(name string, aggregation elastic.Aggregation) SearchExecutionProvider
	Do(ctx context.Context) (*elastic.SearchResult, error)
}

type MyElasticClient struct {
	*elastic.Client
}

type MySearchService struct {
	*elastic.SearchService
}

func (service MySearchService) Aggregation(name string, agg elastic.Aggregation) SearchExecutionProvider {
	service.SearchService = service.SearchService.Aggregation(name, agg)
	return service
}

func NewMyElasticClient(url string) (SearchProvider, error) {
	client, err := elastic.NewClient(
		elastic.SetURL(url),
		elastic.SetSniff(false),
	)

	return MyElasticClient{
		Client: client,
	}, err
}

func NewMySearchService(searchService *elastic.SearchService) MySearchService {
	return MySearchService{
		SearchService: searchService,
	}
}

func (client MyElasticClient) Search(indices ...string) SearchExecutionProvider {
	newSearch := client.client.Search(indices...)
	return NewMySearchService(newSearch)
}
```

With this I can create mocks of `SearchProvider` to stand in for `MyElasticClient`.  I can set them up to return mocks of `SearchExecutionProvider` in place of `MySearchService` which I can have return `elastic.SearchResult`s with made up data.

**Comment by olivere** [comment]
If you want to test the Repository, you could e.g. mock the HTTP responses by using [`net/http/httptest`](https://golang.org/pkg/net/http/httptest/).

With regard to testing, you have to be careful not to test Elasticsearch instead of your code ;-)

**Comment by mkadin** [comment]
I agree with you if I was mocking the HTTP response from ES, then I'd be testing your library :)

In this case, I'm looking to test the code responsible for directly interacting with the structs your library provides.  I'm not obsessed about 100% coverage, but many people are.  Here's an example of what the code I'm looking to test might look like:

```
func GetDateHistogram(
	indexPattern string,
	timeField string,
	termFilters map[string]interface{},
	interval string,
) (*elastic.SearchResult, error) {
	client := elastic.NewClient()
        search := client.Search(indexPattern)
	agg := elastic.NewDateHistogramAggregation().Field(timeField).Interval(interval)
	mustQueries := []elastic.Query{}

	// We need to do these filters in order so the tests are consistent...
	termKeys := []string{}
	for key := range termFilters {
		termKeys = append(termKeys, key)
	}
	sort.Strings(termKeys)
	for _, key := range termKeys {
		mustQueries = append(mustQueries, elastic.NewTermQuery(key, termFilters[key]))
	}
	query := elastic.NewBoolQuery().Must(mustQueries...)

	return search.Aggregation(
		"my_beautiful_histogram", agg,
	).Query(
		query,
	).Do(context.TODO())
}
```

Without a mockable interface for `SearchService` and `Client` I can't test that I've created the `SearchService` with the correct index pattern, and I can't make sure I'm passing the right `Query` and the `Aggregation` to the `SearchService`.

Anyway, this ticket is closed, and I have a workaround that is verbose but works, so I won't bug you!  Just providing my 2 cents that this might be valuable for people, and including the code from my previous comment as a pattern for the next passerby who wants to do something similar.

Thank you so much for your work on this library!

**Comment by olivere** [comment]
@mkadin First of all, your code should not create an `*elastic.Client` in every function call. `NewClient` creates a long-running, thread-safe client that you typically create only once in your app. If you're not careful, you're starting tens of thousands of goroutines with your code.

I think what you should do to test your code is to start a [`httptest.NewRecorder`](https://golang.org/pkg/net/http/httptest/#example_ResponseRecorder), then create a [`elastic.NewSimpleClient`](https://github.com/olivere/elastic/blob/release-branch.v6/client.go#L331) with the URL of the recorder. Then you start your code and check that the recorder recorded the correct HTTP request(s). You can even mock the response to test for successful and failed search requests.

**Comment by Grindlemire** [comment]
Hey @olivere I have been trying to work through unit testing my code using your library for the past several months and I feel I am still running into the same issue time and again with interfaces. The situation I keep running into is as follows:  

```Go
func MyBusinessLogicFunc(e *elastic.Client) {
    // Do business logic here that I want decoupled from my client or db
    ...
    // I want to do some query (let's say a bool query search)
    resp, err := e.Search().Index(myIndex).Query(myBoolQuery).Do()
    ...
    // Do something with the response associated with my business logic
    ...
}
```
Normally what I want to do to encapsulate my business logic is the following:
```Go
type DBClient interface {
    Search() *SearchService // <-- won't work because not an interface
}
...
func MyBusinessLogicFunc(e DBClient) {
    // Do business logic here that I want decoupled from my client or db
    resp, err := e.Search().Index(myIndex).Query(myBoolQuery).Do()
    ...
    // Do something with the response associated with my business logic
    ...
}
```
Unfortunately I can't do this as a call to `Search` returns a pointer to a `SearchService` and not an interface. 

As @mkadin pointed out as his solution you can solve this problem by wrapping all of the structs I use from the library (which would require wrapping at least the client itself, as well as every searchservice/bulkservice/etc. I create). This seems like a pretty verbose solution that requires quite a bit of boiler plate as well as maintenance when I want to extend the code.

I could additionally mock Elasticsearch and it's responses at the http level using [httptest](https://golang.org/pkg/net/http/httptest/) as you pointed out but that also seems like a pretty fragile and verbose way to test my business logic as I would have to hand craft responses that are byte compatible with Elasticsearch's responses.

My current solution is the one you suggested on November 8th up above but I have had a lot of difficulty maintaining it. This is because there is often quite a bit of configuration that I need to pass to my DB handler to define the proper query. Here is a simple example of what I am talking about:
```Go
type MyDBInterface interface {
    SearchWithMaxSubAgg(startTime, endTime time.Time, maxField, userName string, ascending bool) // <-- The arguments are used in the bool query and the max sub aggregation
}
func MyBusinessFunc(db MyDBInterface) {
    // business logic
    ...
    // now I want to do an aggregation with a bool query, but I want to abstract it from my business logic
   resp, err := db.SearchWithMaxSubAgg(myStartTime, myEndTime, myMaxField, myUserName, false)
    ...
}
```
As you can see above my business logic keeps leaking into the client because each client function does a very specific query. The result is that the client and business logic become tightly coupled. My `DBInterface` explodes in size as I need very specific types of nested aggregations and queries for each business function. I tried making the client super general but found myself just rewriting a wrapper around your library

So here is my conundrum: I can't quite figure out how to keep my business logic separate from my client logic without interfaces around your library. If the the library exposed interfaces to the the user rather than pointers to structs I could keep my interfaces much smaller and my business logic fully encapsulated. Additionally I could unit test my business logic by itself and also have integration tests to test the client layer as well. Am I perhaps missing something when it comes to how you recommend to wrap your library and keep it encapsulated away from business logic?

All that being said I love this library and I am super thankful for all the work you put into maintaining it! My goal is to ask about how to best approach this problem in a maintainable way and not criticize past design decisions. :)

**Comment by olivere** [comment]
@Grindlemire First of all, do you really want to do unit tests (i.e. not hitting Elasticsearch _at all_ but rather simulate a response), or do you want to do integration tests? Because when you really want to check if your queries succeed when working against Elasticsearch, there is no other way than to really hit ES.

Let's assume you want to do unit tests. Then you need to abstract away Elastic, just like you abstract away a database connection or a TCP connection to some service.

In Go, this is typically done by interfaces. You define an interface like e.g.

```
type Storage interface {
  Search(Request) (*Response, error)
}
```

Then you could implement the interface based on a real connection to Elasticsearch, and one that does e.g. mock the Elasticsearch response, like so:

```
type LiveStorage struct {
  es *elastic.Client
  ...
}

func NewLiveStorage(es *elastic.Client) *LiveStorage {
  return &LiveStorage{es: es}
}

type MockStorage struct {
  OnSearch func(Request) (*Response, error)
}

func NewMockStorage() *MockStorage {
  return &MockStorage{}
}

func (c *MockStorage) Search(req Request) (*Response, error) {
  return c.OnSearch(req)
}
```

Using the `MockStorage` is quite simple and very fast:

```
c := NewMockStorage()
c.OnSearch = func(_ Request) (*Response, error) {
  return &Response{...simulated response parameters...), nil
}
...
res, err := c.Search(...some request)
...
```

I've yet to see a situation where this strategy doesn't work. It's a bit cumbersome to set-up the correct way of mocked responses. But that's typically a sign that your code is still too complex. E.g. in your comment you said that you have a myriad of methods on your `DBInterface`: But maybe you could get away with having only one generic `Search` method but different implementations for `Request` and `Response`, no?

I've seen other strategies as well. I think the standard library has a strategy of adding hooks for testing. They have a very low overhead, or are even optimized away when compiling. The strategy looks like this:

```
var (
  testHook = func(Request) (*Response, error) {}
)

func Search(req Request) (*Reponse, error) {
  if testHook != nil {
    return testHook(req)
  }
  ... normal process ...
}

// In your tests, you set the testHook before running the test
testHook = func(Request) (*Response, error) {
  ...
)
...
```

There's a whole world of testing strategies. See e.g. [this video by Mitchell Hashimoto recorded at GopherCon 2017](https://www.youtube.com/watch?v=8hQG7QlcLBk).

**Comment by olivere** [comment]
@Grindlemire Notice that there is no reason for Elastic to define the interfaces. You could do it yourself, and use mocking to your advantage. See [this gist as an example](https://gist.github.com/olivere/b285ce788a4eeca24626c9bd3d699df1).

**Comment by Grindlemire** [comment]
Hey @olivere thanks for the responses. I want to do both unit and integration tests. I want to be able to test my business logic with a bunch of different edge cases without having to reproduce all the different states that would yield those edge cases in Elasticsearch. I also want to be able to run integration tests with real data hitting a real ES instance. I agree that the only way to test whether a query really succeeds is to hit Elasticsearch, which is why integration tests are valuable in addition to unit tests. I also agree with you that mocking is the way to go (I am using gomock) and that is where I was thinking that having interfaces on the service structs elastic exposes would simplify this issue. 

Thanks for linking the example, my question would be how that pattern works when you have an expanded API? If you have many complex queries you run into either 

a). A really big interface for your client (which is bad due to coupling and leaking business logic) e.g.
```Go
type MyDB interface {
    SearchWithMaxSubAgg(...)
    SearchWithTermsSubAgg(...)
    ScrollRead(...)
    ...
}
```
or 

b). Needing to createa a bunch of general interfaces that recreate the service methods (e.g. SearchService, BulkService, etc.) as well as some boilerplate to get the right interface back from your local DB interface (for example when you call `e.Bulk()` it would need to return the local interface representing the BulkService struct). e.g.
```Go

type MyDB interface{
    Bulk() BulkDoer
    Scroll() ScrollDoer
}

type BulkDoer interface {
    Do() (*BulkResponse, error)
    // all the other BulkService functions that elastic exposes
}

type ScrollDoer interface {
    Do() (*ScrollResponse, error)
    // all the other ScrollService functions that elastic exposes
}
```

I am advocating for b). My question is are there any negatives to putting those interface definitions in the library as opposed to making every client recreate those interfaces in their own code?

I understand that this has expanded beyond the scope of the original question and I don't want to waste your time. To me it seems that there would be value in returning interfaces for your services rather than struct pointers but if the answer is that every client has to do it then that is the answer.

**Comment by Grindlemire** [comment]
https://github.com/Grindlemire/elastic/pull/1 is an example of what I would think it looks like to have an interface over the service structs (using the BulkService as an example). I just did a PR to a local fork of this library so I don't mess up your PR queue.

**Comment by olivere** [comment]
@Grindlemire May I ask whether you've been a C#/.NET programmer before learning Go?

**Comment by Grindlemire** [comment]
Haha I did use C# (I did some amount of C# before using Go full time). I know what you are getting at and I agree it does seem somewhat verbose. I have been struggling with this interface problem in an existing code base for a while and this is a solution that would help with my current problem (and what I imagine is a somewhat common problem).

Maybe this all stems from the fact that I am considering Elasticsearch query building and parsing to be business logic when in reality it is not and the only way I _should_ test that logic is with integration tests but that is perhaps a more existential question. :)

**Comment by olivere** [comment]
Yes, the 2nd paragraph summarizes very well what I think is the core issue with your problem. You're trying to abstract from something that you cannot abstract from due to the problem space.

Maybe you should forget about all that services and simply abstract the request/response part. That's because, in the end, all services call [`Client.PerformRequest`](https://github.com/olivere/elastic/blob/release-branch.v6/client.go#L1179). And you could very simply mock that with the strategy outline before.

I don't think adding interfaces to Elastic is necessary. Quite the opposite really: If we define those interfaces, people start relying on them, and we'd lock ourselves into something we'll never get away from. And, as we found out earlier today, there is no need to define them: You can do that in the way you need it in your app. And every app uses a different kind of abstraction, so who are we to define the abstraction via a general contract. Some people would rather use a full interface (like you did in your issue), some would only want to define a `Doer` interface to define a protocol for the `Do` method.

**Comment by Grindlemire** [comment]
Ok thanks for your help, patience, and discussion!

**Comment by initialcontext** [comment]
YMMV, but I hit this problem too, and [came up with this silly thing](https://github.com/elireisman/go_mock_stubs) to generate interface and mock structs with stub implementations for public APIs presented as pointers to structs. The code it generates against this lib compiles in my project, and I was able to write some unit tests with it.

**Comment by Sahasrara** [comment]
Not to be annoying, but I think you need interfaces too.  The alternative is to either simulate an ElasticSearch server which is work, or to write your own interfaces, which is a bad solution since it forces every consumer of the library to re-write the same code that's omitted from the library.  Also it couples the code of any consumer of this library to this library should you add more methods or change signatures.

**Comment by mrhwick** [comment]
I wrapped the BulkService with an interface in my code to test things unrelated to this library. The only methods I'm using are `Add()` and `Do()`. Fortunately, I am not doing any chained operation off of the `bulkService.Add()` call in the code under test. That call must return an object of type `*elastic.BulkService`, which isn't my interface, so that return value can't be a mock.

In my mocked implementation of the interface I just return nil there, but anyone who uses chaining won't be able to inject a mock using their own interfaces.

```go
func (mock *mockBulkESService) Add(requests ...elastic.BulkableRequest) *elastic.BulkService {
        mock.addCallCount++
	for _, req := range requests {
		mock.addRequests = append(mock.addRequests, req)
	}
	return nil
}
```

**Comment by bgadrian** [comment]
The major disadvantage of this lib is the fact that you cannot mock it. Even if you try you will see that the entire lib is built with Structs instead of interfaces, making it impossible to test the repository code. 
Testing with a real ES is not an option since you often need control which ES does not offer and building a HTTPMock server or client requires deep knowledge on ES APIs.

**Comment by olivere** [comment]
@bgadrian Again, as outlined above, I strongly believe the library shouldn't be mocked for the same reasons that e.g. the Go driver for MySQL shouldn't be mocked. Instead of mocking the driver, you should mock your application. If you find yourself mocking the driver, your abstractions are typically wrong. You should want your application to be decoupled from the actual technology used to implement it. In other words, your application code should look more like this ...

```
type Searcher interface {
  Search(context.Context, SearchRequest) (*SearchResponse, error)
}
```

... instead of e.g. ...

```
func Search(ctx context.Context, es *elastic.Client, req SearchRequest) (*SearchResponse, error) {
  ...
}
```

**Comment by bgadrian** [comment]
@olivere this is exactly how my use cases are implemented, there is no ES logic leaked outside of the model. But more complex ES apps have some logic in the model that is linked to the ES like routing, batching and so on that needs to be tested.

**Comment by olivere** [comment]
I set up a [wiki page](https://github.com/olivere/elastic/wiki/Testing) that describes two approaches to testing with Elasticsearch and this library.
