### ISSUE TITLE
Warning: 299 Elasticsearch-5.6.3-1a2f265 "Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header."

### ISSUE THREAD

**Issue by jsiembida** [olivere/elastic#633]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[x] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior

HTTP reply without the titular warning (seems similar to #511)

### Please describe the actual behavior

HTTP reply with the warning

### Any steps to reproduce the behavior?

Send `/_bulk` index with `Content-Type: application/x-ndjson; charset=UTF-8` instead of `Content-Type: application/x-ndjson` (seems the `charset=UTF-8` triggers the warning).

Example call:

```
POST /_bulk HTTP/1.1
Host: metrics
Accept-Encoding: identity
Content-Length: 2213
Content-Type: application/x-ndjson; charset=UTF-8
```

Reply:

```
HTTP/1.1 200 OK
Warning: 299 Elasticsearch-5.6.3-1a2f265 "Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header." "Thu, 09 Nov 2017 12:27:08 GMT"
content-type: application/json; charset=UTF-8
content-length: 1492
```

Again, removing the `charset=UTF-8` makes the warning go:

```
POST /_bulk HTTP/1.1
Host: metrics
Accept-Encoding: identity
Content-Length: 2213
Content-Type: application/x-ndjson
```

And the clean reply now:

```
HTTP/1.1 200 OK
content-type: application/json; charset=UTF-8
content-length: 1492
```

Not sure that is expected, especially that ES itself uses `charset=UTF-8` in replies.

**Comment by olivere** [comment]
Oh, okay. I'll have a look into this for the next release.

**Comment by olivere** [comment]
@jsiembida I don't see how/where Elastic will send `Content-Type: application/x-ndjson; charset=UTF-8` anywhere? It will only [send `Content-Type: application/x-ndjson`](https://github.com/olivere/elastic/blob/release-branch.v6/bulk.go#L242).

Can you explain how you triggered this?

**Comment by olivere** [comment]
That's also what ES specifies [here](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docs-bulk.html).

**Comment by olivere** [comment]
@jsiembida Friendly ping.

**Comment by jsiembida** [comment]
Hi, thanks for feedback. I think you are absolutely right, this seems more like an ES issue.
