### ISSUE TITLE
Support for self signed certs for HTTPS connection to ElasticSearch

### ISSUE THREAD

**Issue by alexk307** [olivere/elastic#636]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[x] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
The elastic client will connect to an elastic search server being served via https with a self signed certificate.

### Please describe the actual behavior
Unable to connect.

### Any steps to reproduce the behavior?
```
client, err = elastic.NewClient(
		elastic.SetURL("https://<your_server_here>:443"),
	)
```

I believe we can disable the certificate authentication check within the http client itself. Maybe add another parameter to `NewClient` to specify if you want to verify the ssl, such as `VerifySSL=true`.

**Comment by alexk307** [comment]
Sorry, had to look through source code. Have to use `setScheme`

**Comment by alexk307** [comment]
Can someone post an example on how to connect via HTTPS? Even with a valid cert, it doesn't seem to be working?

**Comment by olivere** [comment]
@alexk307 We're successfully working with Elastic Cloud, which uses https to connect. So https with a valid certificate is definitely working here.

If you're using your own certificate, you can either ignore verification or set up and pass a configured HTTP client to Elastic. There's a [Wiki page for that](https://github.com/olivere/elastic/wiki/HttpTransport). This is it in a nutshell:

```
httpClient = &http.Client{
  ...
}
client, err := elastic.NewClient(elastic.SetHttpClient(httpClient))
```

If you want to ignore validation, this is typically done with `InsecureSkipVerify` in [`tls.Config`](https://golang.org/pkg/crypto/tls/#Config). Please refer to the Go documentation for setting up your HTTP client accordingly.

**Comment by alexk307** [comment]
@olivere I've tried all of the steps but I'm still unable to connect to the ES cluster.


```
	tr := &http.Transport{
        	TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
    	}
	client := &http.Client{Transport: tr}
	bs.esClient, err = elastic.NewClient(
		elastic.SetHttpClient(client),
		elastic.SetURL("https://<my_valid_url>:443"),
		elastic.SetScheme("https"),
	)
```

I get:

```
no Elasticsearch node available | Initializing elasticsearch client
```

Even thought I can definitely reach my cluster from my box, and the cluster has a valid cert.

**Comment by olivere** [comment]
I'll look into this again.

**Comment by olivere** [comment]
Can you try to first connect directly to see if HTTP works at all? Something like this: https://github.com/jcbsmpsn/golang-https-example/blob/master/https_client.go

**Comment by alexk307** [comment]
@olivere yes I was able to hit it with the golang http client:

```
&{200 OK 200 HTTP/1.1 1 1 map[Content-Length:[343] Connection:[keep-alive] Access-Control-Allow-Origin:[*] Content-Type:[application/json; charset=UTF-8]] 0xc42020fcc0 343 [] false false map[] 0xc42006e500 0xc4205860b0}
<nil>
{
  "name" : "uGH7Tka",
  "cluster_name" : "194590077900:raj-alex-test-53",
  "cluster_uuid" : "xmA2_6EnStWrXUC4yJ-hsg",
  "version" : {
    "number" : "5.3.2",
    "build_hash" : "Unknown",
    "build_date" : "2017-04-28T21:44:52.237Z",
    "build_snapshot" : false,
    "lucene_version" : "6.4.2"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by olivere** [comment]
Okay. Can you please add `elastic.SetSniff(false)` to the list of options to see if that makes a difference? If it does, what is the output of `curl https://<your-es-instance-url>/_nodes/http?pretty=true`?

**Comment by alexk307** [comment]
When I added `SetSniff`, I got:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xbfd93d]

```


```
☺  curl https://<my_host>:443/_nodes/http?pretty=true
{
  "_nodes" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "cluster_name" : "194590077900",
  "nodes" : {
    "uGH7Tka9SZSgyWExudmpHg" : {
      "name" : "uGH7Tka",
      "version" : "5.3.2",
      "build_hash" : "Unknown",
      "roles" : [ "master", "data", "ingest" ]
    }
  }
```

**Comment by olivere** [comment]
You got a segfault with this?

```
bs.esClient, err = elastic.NewClient(
		elastic.SetHttpClient(client),
		elastic.SetURL("https://<my_valid_url>:443"),
		elastic.SetScheme("https"),
		elastic.SetSniff(false),
	)
```

The pasted output doesn't seem to be right. There should be a `http` section, like this:

```
{
  "_nodes" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "cluster_name" : "my-cluster-name",
  "nodes" : {
    "imK7EhRzTYWLHb0pW5Nm2Q" : {
      "name" : "imK7EhR",
      "transport_address" : "172.18.0.3:9300",
      "host" : "172.18.0.3",
      "ip" : "172.18.0.3",
      "version" : "5.6.4",
      "build_hash" : "8bbedf5",
      "roles" : [
        "master",
        "data",
        "ingest"
      ],
      "http" : {
        "bound_address" : [
          "0.0.0.0:9200"
        ],
        "publish_address" : "172.18.0.3:9200",
        "max_content_length_in_bytes" : 104857600
      }
    }
  }
}
```

**Comment by olivere** [comment]
Or are you connecting to a node in the cluster where the REST API is disabled?! It is enabled by default on all cluster node roles.

**Comment by alexk307** [comment]
Yes I got a segfault from that line.

This is an instance generated from AWS Elastic Search.

**Comment by alexk307** [comment]
It seems like the API is enabled since I'm able to hit with an HTTP client, no?

**Comment by olivere** [comment]
Yes. But I wonder why the http section is missing from the Nodes API. That section is used to sniff the HTTP endpoints of the cluster nodes. And when it’s missing, it cannot do that. Hence the problem, that’s the theory at least...

Sorry. Leaving the office for today.

**Comment by alexk307** [comment]
@olivere I think we figured it out. I rebuilt and then I was able to set the `SetSniffer(true)`. We think it's because of the way that AWS hides their networking behind the scenes.

Closing this. Thanks for your help.
