### ISSUE TITLE
json.Marshal() on a result.Aggregations returns invalid JSON

### ISSUE THREAD

**Issue by FireArrow** [olivere/elastic#64]
When marshaling to the result of a aggregation to JSON it produces invalid JSON. The code below is the relevant snippet from my code:

```go
termsAgg := elastic.NewTermsAggregation().
        Field("_type").
        OrderByAggregation("topScore", false).
        SubAggregation("topScore", elastic.NewMaxAggregation().Script("_score")).
        SubAggregation("types", elastic.NewTopHitsAggregation().Size(5))

searchRequest := client.Search().
        Index("myindex").
        Query(query).
        Aggregation("top_results", termsAgg)

result, err := searchRequest.Do()
if err != nil {
        //Actually doing real error handling here, but I cut that for readability
        log.Println("Error: SearchHandler:", err)
        return
}

aggRes := result.Aggregations

topResults, found := aggRes.Terms("top_results")
if !found {
        log.Println("Error: no results found")
        return
}

resultJson, err := json.Marshal(topResults)
```

Result (trimmed):
```json
{  
   "Aggregations":{  
      "buckets":[  ],
      "doc_count_error_upper_bound":0,
      "sum_other_doc_count":0
   },
   "DocCountErrorUpperBound":0,
   "SumOfOtherDocCount":0,
   "Buckets":[  
      {  
         "Aggregations":{  
            "doc_count":39,
            "key":"ne",
            "topScore":{  
               "value":2.060434579849243
            },
            "types":{  
               "hits":{  
                  "total":39,
                  "max_score":2.0604346,
                  "hits":[  
                     {  },
                     {  },
                     {  },
                     {  },
                     {  }
                  ]
               }
            }
         },
         "Key":"ne",
         "KeyNumber":ne,
         "DocCount":39
      }
   ]
}
```

Notice the unquoted value of `KeyNumber`.

It look like this is an oversight when solving #51, but I'm not sure.

**Comment by olivere** [comment]
As I said in #51: Serializing data back to JSON is not the primary use case of Elastic.

What's your use case for serializing results back into JSON?

**Comment by FireArrow** [comment]
No, I noticed that, and I realize it is a low priority bug. I thought I'd still report it though, as it still is a bug.

I use it to verify I built correct requests. I have a system generating searches, and while developing I find it handy to be able to read the response.

**Comment by olivere** [comment]
I recognize it'd be handy to have something like that. But I'm not sure if I'd call it a bug. Can you do the same with official clients in Ruby, Python, or JavaScript?

If you want to read the response, you can [enable tracing](https://github.com/olivere/elastic/wiki/Logging). If you want even more control, you can specify [your own `http.Transport`](https://github.com/olivere/elastic/wiki/HttpTransport).

**Comment by FireArrow** [comment]
I think I have expressed myself unclear. The only thing I think is a bug is the unquoted string value of `KeyNumber`, which causes the Marshal() to generate invalid json. It's not part of the curl response, so it must be something added by elastic (the library). I'm honestly not even sure what `KeyNumber` is there for. Should it be some iteration value maybe? Or a numeric representation of the key? 

`KeyNumber` is defined as a json.Number, which is really a string. However, the string in a json.Number is supposed to represent a number. There is apparently no check that the string you set a json.Number to actually do represents a number.

So, my conclusion is that `KeyNumber`is set to an incorrectly (as it is set to a non-number string), but I don't know what is was intended to contain, so I can't fix it for you.

I have worked around this problem, so it is in no way a critical bug (for me at least) but I still think it is a bug.

**Comment by olivere** [comment]
See [`json.Number`](http://golang.org/pkg/encoding/json/#Number) and [`UseNumber`](http://golang.org/pkg/encoding/json/#Decoder.UseNumber) as well as #26 and #37 for insight as to why there is a `KeyNumber` in there. IIRC the tl;dr version is that keys can be numeric values as well as strings, and we were looking for a convenient way of extracting the numeric value, which is exactly what `json.Number` does. So sometimes, you need use `Key`, sometimes you use `KeyNumber`.

As I said, marshaling is out of scope for Elastic (as it probably is for all official clients). Aggregations have proven to be especially tricky to deserialize, so serializing those is an extra effort I probably won't go.

However, I do wonder why `json.Number` does serialize as `"ne"` in `json.Marshal`. I'll leave this issue open and look into it when I have more time.

**Comment by FireArrow** [comment]
I see. Thank you for explaining!

**Comment by olivere** [comment]
This issue is rather old and I'm not even sure what's the problem even after re-reading the discussion :-) FWIW marshaling is out of scope for Elastic as it's just a client library.

Please re-open if this is still an issue.
