### ISSUE TITLE
Search returns EOF

### ISSUE THREAD

**Issue by carantunes** [olivere/elastic#640]
### Configuration

	client, err := elastic.NewClient(
		elastic.SetURL(config.URL), // http://localstack:4571
		elastic.SetSniff(false), //Keep the list of IPs initially given, and don't care about updates in the cluster.
		elastic.SetErrorLog(log.New(os.Stderr, "ELASTIC ", log.LstdFlags)),
		elastic.SetInfoLog(log.New(os.Stdout, "ELASTIC ", log.LstdFlags)),
		elastic.SetTraceLog(log.New(os.Stdout, "ELASTIC ", log.LstdFlags)),
	)

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ x] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v6 (for Elasticsearch 6.x)

With elasticsearch 5.3.0

### Please describe the expected behavior

The search should return a valid answer.

When I use curl to make the request it returns a hit.

`curl "http://localstack:4571/test-search/_search?pretty" -X POST -H 'Content-Type: application/json' -d '{"from":0,"query":{"term":{"city":"teste"}},"size":9}'`

A Get() returns successfully.

```
response, err := client.elastic.Get().
		Index("test-search").
		Type("test").
		Id("8").
		Do(ctx)
```

### Please describe the actual behavior

Logs:

```
ELASTIC 2017/11/17 12:00:08 POST /test-search/_search?pretty=true HTTP/1.1
Host: localstack:4571
User-Agent: elastic/5.0.53 (linux-amd64)
Transfer-Encoding: chunked
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip

58
{"from":0,"query":{"term":{"city":"teste"}},"size":10,"sort":[{"city":{"order":"asc"}}]}
0


ELASTIC 2017/11/17 12:00:08 elastic: http://localstack:4571 is dead
```

```
2017/11/17 12:00:08 [Recovery] panic recovered:
POST /search HTTP/1.1
Host: 127.0.0.1:8080
Accept: */*
Content-Length: 2
Content-Type: application/x-www-form-urlencoded
User-Agent: curl/7.54.0


Post http://localstack:4571/test-search/_search?pretty=true: EOF
```

### Any steps to reproduce the behavior?

#Request made 
```
	termQuery := elastic.NewTermQuery("city", "teste")

	searchResult, err := client.elastic.Search().
		Index("test-search").
		Query(termQuery).  // specify the query
		Sort("city", true). // sort by "user" field, ascending
		From(0).Size(10).   // take documents 0-9
		Pretty(true).       // pretty print request and response JSON
		Do(ctx)
```

**Comment by olivere** [comment]
Hi! It seems to me the node is dead, hence the `io.EOF`:

```
ELASTIC 2017/11/17 12:00:08 elastic: http://localstack:4571 is dead
```

So Elastic is trying to send the request to the given node, but that node is not responding. The `elastic: http://localstack:4571 is dead` also points in that direction.

I'm wondering about this log entry you pasted. The `POST /search HTTP/1.1` and `Host: 127.0.0.1:8080` does not align with the URL you posted below that: `Post http://localstack:4571/test-search/_search?pretty=true: EOF`.

Is there a proxy involved, perhaps (the 127.0.0.1:8080)?

**Comment by carantunes** [comment]
Hi! That Host is from my machine. The node is not dead, because I can make the same request using curl, and I can use the method Get() from your client successfully. Seems to be a problem when the method is a POST.

**Comment by olivere** [comment]
This code is perfectly okay and is tested thoroughly in the [unit tests](https://travis-ci.org/olivere/elastic/builds):

```
termQuery := elastic.NewTermQuery("city", "teste")

searchResult, err := client.elastic.Search().
	Index("test-search").
	Query(termQuery).  // specify the query
	Sort("city", true). // sort by "user" field, ascending
	From(0).Size(10).   // take documents 0-9
	Pretty(true).       // pretty print request and response JSON
	Do(ctx)
```

Some things in your issue report confuse me. E.g. this snippet definitely doesn't come from Elastic:

```
2017/11/17 12:00:08 [Recovery] panic recovered:
POST /search HTTP/1.1
Host: 127.0.0.1:8080
Accept: */*
Content-Length: 2
Content-Type: application/x-www-form-urlencoded
User-Agent: curl/7.54.0


Post http://localstack:4571/test-search/_search?pretty=true: EOF
```

Elastic does not use the `/search` endpoint and doesn't use the `127.0.0.1:8080` if you configured the URL as `http://localstack:4571`. That `Post http://localstack:4571/test-search/_search?pretty=true: EOF` however is a valid URL that may come from Elastic, but I don't know how the two sections relate to each other.

I'm pretty confident that Elastic works fine when searching. It is used in quite some projects, so I think I'd already received some bug reports if something this basic would be wrong.

I don't know how to continue from here. Maybe you can write a standalone program and see if it works correctly with a smaller surface area. The [connect recipe](https://github.com/olivere/elastic/blob/release-branch.v6/recipes/connect/connect.go) may be a starter, or the [code from `example_test.go`](https://github.com/olivere/elastic/blob/release-branch.v6/example_test.go#L30-L236). Just change the URL and it should work fine.

**Comment by carantunes** [comment]
Sorry for the issue, seems like the problem is caused by another framework integration with elasticsearch (Localstack).

Thanks anyway!

**Comment by olivere** [comment]
No problem! Cheers.
