### ISSUE TITLE
 [script] unknown field [source], parser not found

### ISSUE THREAD

**Issue by aymone** [olivere/elastic#643]
[x] elastic.v5 (for Elasticsearch 5.1.1)

Im using v5 for build some queries and actually is returning this error: 
elastic: Error 400 (Bad Request): [script] unknown field [source], parser not found [type=illegal_argument_exception]

Is there any change to affect this? In new builds, this began to happen ... in old builds, no errors occur.

**Comment by olivere** [comment]
@aymone Hmm... there was a [script-related change](https://github.com/olivere/elastic/commit/3c424ca8458cd544edee9e16f798d99fcb61e373) recently. But that should've been a fix for 5.x and not break something.

Can you post a reproducible example where this happens?

**Comment by aymone** [comment]
I think the problem is this line:
https://github.com/olivere/elastic/commit/3c424ca8458cd544edee9e16f798d99fcb61e373#diff-dfc827036953b6615f2165f673c4d874R91

I will create a fork before this commit to work with elastic 5.1.1 (AWS version).

**Comment by olivere** [comment]
Yes. That's what triggered the change mentioned above (see #627). However, using `source` there instead of `inline` is correct [according to the documentation](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/modules-scripting-using.html) and the Java source.

**Comment by olivere** [comment]
... and [this integration test](https://github.com/olivere/elastic/blob/3c424ca8458cd544edee9e16f798d99fcb61e373/update_integration_test.go#L13) proves that it actually works with `source`.

**Comment by aymone** [comment]
Yes, but only for ES >5.6... 
https://www.elastic.co/guide/en/elasticsearch/reference/5.1/modules-scripting-using.html

**Comment by olivere** [comment]
Oh well. So the guys from Elastic did a breaking change in a minor version.

- [5.6](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/modules-scripting-using.html)
- [5.5](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/modules-scripting-using.html)
- [5.4](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/modules-scripting-using.html)
- [5.3](https://www.elastic.co/guide/en/elasticsearch/reference/5.3/modules-scripting-using.html)
- [5.2](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/modules-scripting-using.html)
- [5.1](https://www.elastic.co/guide/en/elasticsearch/reference/5.1/modules-scripting-using.html)
- [5.0](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/modules-scripting-using.html)

Okay. That definitely needs a workaround...

**Comment by aymone** [comment]
Im really disapointted too...

**Comment by olivere** [comment]
I've never seen that. I will create 5.0.56 with a fix tomorrow (it's 11p.m. here).

**Comment by aymone** [comment]
thanks @olivere , once more time, u are helping me.

**Comment by olivere** [comment]
I'll release 5.0.56 soon which reverts the scripting changes back to using `inline` instead of `source` for 5.x.

**Comment by saeedansari** [comment]
Hi,
I am using ES High Level Rest Client 5.6.2 and ES on AWS version 5.5; I get the same error. Should I use client 5.5 instead?

Thank you

**Comment by saeedansari** [comment]
We started with client 5.6 and when we deployed ES on AWS, it was supporting 5.5;
Although it is supporting 5.6 now, but it would be lots of work to upgrade all environments to new version. So either we should downgrade our client to 5.5 or do a workaround for 5.6

**Comment by olivere** [comment]
Just to understand: What do you mean with „client 5.6“? The latest version of Elastic for Elasticsearch 5.x is 5.0.65.
