### ISSUE TITLE
URL can't have prefix path

### ISSUE THREAD

**Issue by ZaniaDeveloper** [olivere/elastic#644]
### Which version of Elastic are you using?

- [ ] elastic.v2 (for Elasticsearch 1.x)
- [ ] elastic.v3 (for Elasticsearch 2.x)
- [x] elastic.v5 (for Elasticsearch 5.x)
- [ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
In code:
```go
    client, err := elastic.NewClient(
        elastic.SetURL("http://host.xx:9000/prefix/path"),
        …
    )
```
The prefix path “_/prefix/path_” is not used all the time. When i logged HTTP requests, i found a request to the URL __http://host.xx:9200__, but the port 9200 doesn't accept connection on my server.

Therefore, the `err` variable contains error: "no active connection found: no Elasticsearch node available"

Note: A request with __curl__ to the URL http://host.xx:9000/prefix/path/index/mapping/_search works.

**Comment by olivere** [comment]
I have to check if official clients accept path prefixes as well. I personally find it rather confusing.

When sniffing is enabled (the default), you probably cannot use URL prefix as well. The reason is that when sniffing is enabled, your original URLs are only used to find any responding Elasticsearch node, then sniff the HTTP publish address (host name and port) from the configuration reported by `curl http://.../_nodes/http?pretty=true'. The `http/publish_address` entry there will not include your path prefix.

I will review and check if this will create other problems.

**Comment by ZaniaDeveloper** [comment]
For information, Google use it in a self-managed service or a deployed service in Kubernetes.

**Comment by ZaniaDeveloper** [comment]
Another information, if i disable the sniffer, it works, but some URL traced has the form http://x.x.x.x:9200 when in the config the URL is http://x.x.x.x:9000 (or http://x.x.x.x:9000/prefix/path)

**Comment by ZaniaDeveloper** [comment]
Concerning your comment, with python official client, we can configure URL prefix.

This is a piece of Python Help on ElasticSearch class:
```
 |  Different hosts can have different parameters, use a dictionary per node to
 |  specify those::
 |  
 |      # connect to localhost directly and another node using SSL on port 443
 |      # and an url_prefix. Note that ``port`` needs to be an int.
 |      es = Elasticsearch([
 |          {'host': 'localhost'},
 |          {'host': 'othernode', 'port': 443, 'url_prefix': 'es', 'use_ssl': True},
 |      ])
```

**Comment by olivere** [comment]
According to the unit tests, Elastic should already support a URL prefix: https://github.com/olivere/elastic/blob/release-branch.v6/canonicalize_test.go

Be sure to disable sniffing though.

I don't have the time to check this currently.

**Comment by olivere** [comment]
I just added [this test](https://github.com/olivere/elastic/blob/release-branch.v5/client_test.go#L715-L761), which should make sure the `PerformRequest` picks up a URL including its prefix when building HTTP requests.

Not sure where that `...:9000` comes from in your code.

**Comment by ZaniaDeveloper** [comment]
So, we must disable sniffer when we want use a prefix.
May it appear in documentation (wiki, etc.) ?
Cause it's not obvious.

**Comment by olivere** [comment]
I agree: It may be logical, but not obvious.

ES only reports the `publish_host` (`host:port`) when querying the cluster, so the URL prefix is lost.  While you could try to use the prefix from `NewClient`, that may still not help as you may have nodes with different URL prefixes...

Does it work as expected when you disable sniffing?

**Comment by ZaniaDeveloper** [comment]
Yes, once the sniffer disabled all the left works as expected.
