### ISSUE TITLE
Customizable retry for BulkProcessorService

### ISSUE THREAD

**Issue by rwynn** [olivere/elastic#646]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[X] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
Methods are available on the BulkProcessorService to override the default initialTimeout, maxTimeout, or set the retrier/policy that is used.  Alternatively, the BulkProcessorService uses the associated client's retrier which is customizable. 

### Please describe the actual behavior
Unless I am missing something, the BulkProcessorService does not expose a way to set the initialTimeout or maxTimeout for retries.  There is also no way to opt into a retrier or policy different than ExponentialBackoff.  This makes it impossible to opt out or customize retry for bulk.  Finally, the BulkProcessorService has access to the client's retrier but does not use it.  

### Any steps to reproduce the behavior?
N/A

**Comment by olivere** [comment]
Yes. I think #610 is rather similar. I think both BulkProcessor as well as Bulk API and Scroll API need to be able to configure their own custom retrier.

There are [different Retrier implementations](https://github.com/olivere/elastic/wiki/Retrier-and-Backoff) though, with configurable initial timeout and a maximum timeout as well. Plus, you can simply create your own retrier implementation. However, Elastic uses the same Retrier for all API calls. But retries may e.g. be dangerous for scrolling as #610 correctly points out.

**Comment by rwynn** [comment]
Yes, I am aware of the different retrier implementations and that I can create my own.  I'm just not able to set one or even override the timeouts on BulkProcessor due to the fields being private (and no public methods to set them - there is Before, After, Name, Workers, etc but not InitialTimeout or MaxTimeout).  I think you may be agreeing with me, but I'm not sure with your 2nd paragrah.

By the way, Elastic is an amazing library.  You are doing awesome work here and I love the way Elastic is designed.

Can you explain what you mean by Elastic uses the same retrier for all API calls?  The default retrier for the NewClient is a StopRetrier which means no retry by default.  That is great and it can be overriden which is also great.  But then when we get to BulkProcessor, the retry policy set on the client is not reused.  Rather, the retrier is hard coded there to always retry.  So, even with a default of no retry on the client, you always get retries if you use BulkProcessor.   

I will work on a pull request and submit it for your review.

**Comment by olivere** [comment]
Thanks Ryan.

With regard to retriers, I hope [this comment](https://github.com/olivere/elastic/issues/610#issuecomment-336880307) clears up what I think should be done for Scroll API. Scroll API is dangerous when using retries, so we probably need to be able to specify a different retrier on the ScollService.

As you correctly point out, Bulk API (and BulkProcessor) maybe also need to be able to set their own Retrier, just like Scroll API.

Other APIs (e.g. Search API, Get API) use the retrier set on the Client.

**Comment by rwynn** [comment]
Thanks Oliver.  

I gave it a shot and submitted a pull request, but now reading your last comment if may not be as flexible a change as your proposed in your comment (since it's a Backoff and not a Retrier).  However, it should keep the existing behavior intact and let one customize the backoff used.  Thanks for your consideration on this request.

**Comment by olivere** [comment]
Merged this in ddb058ca128ab8faf97562416199b02be2467f55 which will be released with elastic 6.1.0 and backported to v5 in 5.0.59. Thanks!

**Comment by rwynn** [comment]
Thank you for merging the PR and for building this great client.  Looking forward to trying 6.1.0.

**Comment by olivere** [comment]
Thanks. And happy new year :-)
