### ISSUE TITLE
Update API results in 400 Bad Request [type=illegal_argument_exception]

### ISSUE THREAD

**Issue by shugydw** [olivere/elastic#648]
### Which version of Elastic are you using?

- [x] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
The Update API shall update the field with an `upsert`

### Please describe the actual behavior
The code below throws as error: `panic: elastic: Error 400 (Bad Request): failed to execute script [type=illegal_argument_exception]`

### Any steps to reproduce the behavior?

```go
script := elastic.
	NewScript("ctx._source.Intersections += i")
	Param("i", 10)

result, err := client.
	Update().
	Index("index").
	Type("type").
	Id(valid_id).
	Script(script).
	Upsert(map[string]interface{}{"Intersections": 0}).
	ScriptedUpsert(true).
	Do(ctx)

if err != nil {
	panic(err)
}

fmt.Println(result)
```

Thanks for your help!

**Comment by shugydw** [comment]
Figured, the script should be `ctx._source.Intersections += params.i`

**Comment by olivere** [comment]
Yeah, I always forget about that (and use the unit tests as a sort of reminder for using the correct syntax). :-)
