### ISSUE TITLE
error "no Elasticsearch node available" returned when using docker elasticsearch

### ISSUE THREAD

**Issue by guilhermebr** [olivere/elastic#65]
When running elasticsearch inside docker container (I only tested in Mac OS with boot2docker vagrant box), NewClient always returns error: no ElasticSearch node available.

This is solved setting sniff to false.

**Comment by olivere** [comment]
Does [this Wiki entry](https://github.com/olivere/elastic/wiki/Docker) help?

**Comment by guilhermebr** [comment]
@olivere Thank you!
