### ISSUE TITLE
Issue on search 5.6.3

### ISSUE THREAD

**Issue by dinilv** [olivere/elastic#651]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?
[ ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
We were using elastic.v2 then upgraded to v5 (elastic search is 5.6.3)
Search queries are failing now while connecting to master cluster

### Please describe the actual behavior
 elastic: Error 400 (Bad Request): maxConcurrentShardRequests must be >= 1 [type=illegal_argument_exception]

### Any steps to reproduce the behavior?
elasticsearch.yml
 
node.name: master
node.data: false
http.host : <internal ip>

**Comment by olivere** [comment]
Never seen that. Does actually look like this, no? https://github.com/elastic/kibana/issues/13950

**Comment by dinilv** [comment]
Please close this issue. Did anybody report regarding Elastic 5.6.3 process stopped issue in ubuntu machines ? I am sorry the issue is due to Elastic Particular version i guess

**Comment by olivere** [comment]
Maybe updating to 5.6.4 already helps? The [release notes](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/release-notes-5.6.4.html) don't show anything obvious though.
