### ISSUE TITLE
v6 tag

### ISSUE THREAD

**Issue by kmulvey** [olivere/elastic#654]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ x] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
glide should install with the following settings:
  - package: github.com/olivere/elastic
    version: ^6.0.0

### Please describe the actual behavior
[WARN]  --> Unable to find semantic version for constraint github.com/olivere/elastic ^6.0.0                                                       
[ERROR] Failed to set version on github.com/olivere/elastic to ^6.0.0: Unable to update checked out version: exit status 1    
[ERROR] Failed to set initial config references: Unable to update checked out version: exit status 1

### Any steps to reproduce the behavior?
glide up

in order for this to work doesn't there have to be a tag: v6.0.0? I only see v6.0.0-rc2

**Comment by olivere** [comment]
Yes. It's not published yet. Try to use `release-branch.v6` for now.

**Comment by olivere** [comment]
FYI: I hope to tag 6.0.0 over the weekend.

**Comment by olivere** [comment]
Sorry, took a few days more. But v6.0.0 is tagged now, with v6.1.0 coming soon.
