### ISSUE TITLE
Error in docs

### ISSUE THREAD

**Issue by tomercagan** [olivere/elastic#655]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[X] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
The documentation of Refresh method in bulk.go states
> "wait_for" (wait for the changes to be made visible by a refresh before applying)

Also, documentation for Refresh methods for delete.go, index.go, update.go is lacking (I think it should be the same as in bulk)

### Please describe the actual behavior
According to the [elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-refresh.html), `wait_for` waits before **replying**

**Comment by olivere** [comment]
Yeah. Documentation is hard. :-)

**Comment by olivere** [comment]
Updated the docs.
