### ISSUE TITLE
Can't parse timestamp

### ISSUE THREAD

**Issue by cooperspencer** [olivere/elastic#656]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[x] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the actual behavior
`panic: elastic: Error 500 (Internal Server Error): failed to parse timestamp [26 Nov 17 19:23 +0000] [type=timestamp_parsing_exception]`

### Any steps to reproduce the behavior?
```
parsedtime, _ := time.Parse("02/Jan/2006:15:04:05 -0700", values["timestamp"]) #values["timestamp"] = "26/Nov/2017:19:23:15 +0000"

put, err := client.Index().
	Index(viper.GetString("index")).
	Type("Test").BodyJson(values).Timestamp(parsedtime.String()).Do(context.Background())
```

**Comment by olivere** [comment]
I guess the format is just wrong. Can you try `time.RFC3339`? And you shouldn't swallow the error that may come from `jodaTime.Parse`.

BTW: `_timestamp` is [deprecated as of 5.0](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/breaking_50_mapping_changes.html#_literal__timestamp_literal_and_literal__ttl_literal).

**Comment by cooperspencer** [comment]
I just redid it with the time library from golang
`parsedtime, _ := time.Parse("02/Jan/2006:15:04:05 -0700", values["timestamp"]) `

Jesus Christ! It is working with RFC3339!

Now my only problem left is that I can't see any data in kibana and I can only take "created at" as time filter field name

**Comment by olivere** [comment]
Yes, that's because ES uses [`"strict_date_optional_time||epoch_millis"` as the default format for the `date` datatype](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/date.html).

Well. I'm not an expert on Kibana, sorry.
