### ISSUE TITLE
IndexResponse Version prop is int - shouldn't it int64?

### ISSUE THREAD

**Issue by vsiv** [olivere/elastic#657]
Hi olivere!

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[X] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the actual behavior
IndexResponse Version prop is int - shouldn't it int64?

type IndexResponse struct {
	// TODO _shards { total, failed, successful }
	Index   string `json:"_index"`
	Type    string `json:"_type"`
	Id      string `json:"_id"`
	Version int    `json:"_version"`
	Created bool   `json:"created"`
}

### Any steps to reproduce the behavior?

Thanks!
V

**Comment by olivere** [comment]
Thanks for reporting. I will have to look this up in the Elasticsearch code, and if it's a `long` there, I'll have to see if this breaking change is worth the change. I can still change it in v6, as I've not tagged 6.0.0 yet (will probably do so over the weekend).

**Comment by olivere** [comment]
I changed this to `int64` in v5 and v6 lately.
