### ISSUE TITLE
ElasticSearch v6 - unable to set elastic.SetURL

### ISSUE THREAD

**Issue by Vesli** [olivere/elastic#659]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[x] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
Being able to connect to a remote ES cluster

### Please describe the actual behavior
```
client, err := elastic.NewClient(
	elastic.SetSniff(false),
	elastic.SetHealthcheck(false),
	elastic.SetURL("http://myIP.amazonaws.com:9200"),
)
if err != nil {
	log.Fatal("Client: ", err)
}
```

### Any steps to reproduce the behavior?
I simply tried to set up a new connexion to an external cluster.

Now, you have to know that I can ping the server (I used telnet with the port), I can even do a:
`curl -X POST 'http://myip.amazonaws.com:9200/indexname/_count'`
Which returns:
`{"count":9445,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0}}`

and the:
`curl 'http://myIp.amazonaws.com:9200/_nodes/http?pretty'`
returns:
```
{
  "_nodes" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "cluster_name" : "docker-cluster",
  "nodes" : {
    "YQ9PlmEPS7O1D787jnLRvQ" : {
      "name" : "YQ9PlmE",
      "transport_address" : "10.42.133.176:9300",
      "host" : "10.42.133.176",
      "ip" : "10.42.133.176",
      "version" : "6.0.0",
      "build_hash" : "8f0685b",
      "roles" : [
        "master",
        "data",
        "ingest"
      ],
      "attributes" : {
        "ml.max_open_jobs" : "10",
        "ml.enabled" : "true"
      },
      "http" : {
        "bound_address" : [
          "0.0.0.0:9200"
        ],
        "publish_address" : "10.42.133.176:9200",
        "max_content_length_in_bytes" : 104857600
      }
    }
  }
}
```
So I've tried pretty much everything I could come across and it's still not working..
Any ideas?

**Comment by olivere** [comment]
That's strange. If you disable sniffing and health checks, the requests should just use the provided URL(s) passed into `NewClient`. Does it fail when creating the `Client`, or does it fail on the first request? If it does fail with `NewClient`, can you try to figure out where exactly it is failing (or try `NewSimpleClient` which does not do any sniffing/healthchecks whatsoever)?

**Comment by Vesli** [comment]
Hey you know what, I don't really know what happened, but since I added authentication and rewrote my port and accesses to ES - it's working.

Thus, until I find a way of undoing my changes I can't reproduce it.

So let's say that if one isn't respecting the best practice for elasticsearch (like keeping it's direct ip:port private) they might experience some troubles in general, even with your plugin.

But this is just assumptions as it's now working for me.

**Comment by olivere** [comment]
> So let's say that if one isn't respecting the best practice for elasticsearch (like keeping it's direct ip:port private) they might experience some troubles in general, even with your plugin.

What do you mean by that?

**Comment by Vesli** [comment]
By that I mean that elasticsearch ip should be accessible internally only.
I set it public at first (public-ip:9200) and I had troubles connecting to it through your (very cool!) library.

But since I put a basic auth + nginx proxy and restricting the access to 'internal-only' everything works far better.

**Comment by olivere** [comment]
I see. I have several users working with [Elastic Cloud](https://www.elastic.co/cloud) offerings here, which offers a public IP. Works fine so far. So it's probably not a public IP vs. internal IP issue.

Anyway. Just reopen if you see it again.
