### ISSUE TITLE
How to use a defined query template in our query?

### ISSUE THREAD

**Issue by ishare** [olivere/elastic#66]
How to use a defined query template `find_user_tpl`, in our query?

query := elastic.NewTemplateQuery("find_user_tpl").Var("query_string", "Lin")
parse to "query": "find_user_tpl"..

**Comment by olivere** [comment]
Hi there! Do [these tests](https://github.com/olivere/elastic/blob/master/search_queries_template_query_test.go) help?

**Comment by ishare** [comment]
Got it, very useful. I have another question, does it support wrapper several kinds of query in a Query?
Thanks very much!

**Comment by olivere** [comment]
You mean something like [boolean queries](https://github.com/olivere/elastic/blob/master/search_queries_bool_test.go) ([docs on elastic.co](http://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html))?

In case you missed it, [Elasticsearch - The Definite Guide](http://www.elastic.co/guide/en/elasticsearch/guide/current/index.html) is a fantastic online book for learning many of the details of Elasticsearch. Elastic, the Go client, is simply a DSL to all that, and the tests in this repository will probably help you find out about the correct syntax.

Hope this helps :-)

**Comment by ishare** [comment]
I notice this, your code generate this json:
{"template":{"id":"find_user_tpl","params":{"query_string":"Lin"}}}

Actually, below json code is needed.
curl -XGET localhost:9200/users/_search/template -d '{
    "template": {
        "id": "find_user_tpl"    
    },  
    "params": {
        "query_string": "Lin"    
    }  
}'

**Comment by olivere** [comment]
Are you sure this is correct? The [docs](http://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-template-query.html#_stored_templates) state that `params` is below `template` and on the same level as `id`.

**Comment by ishare** [comment]
I'm sure, you can find in the end of this official page below:
http://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html#_more_template_examples

**Comment by ishare** [comment]
I test the docs you provided, using the following command:

curl -XPUT localhost:9200/_search/template/my_template1 -d '{
  "template": { "query": {"match": { "name": "{query_string}" }}}
}'


curl -XGET localhost:9200/users/_search -d '
{
  "query" : {
    "template": {
        "id": "my_template1",    
        "params": {
          "query_string": "sbzt1234"    
        }
    }
  }
}'

I cannot get any result. But using the query below, I can fetch the result.
curl -XGET localhost:9200/users/_search -d '{
  "query": {"match": { "name": "sbzt1234" }}
}'

**Comment by ishare** [comment]
if I use this query, 
curl -XGET localhost:9200/users/_search -d '
{
  "query" : {
    "template": {
        "id": "my_template1",    
        "params": {
          "query_string": "Lin"    
        }
    }
  }
}'

I find errors in elasticsearch logs:
org.elasticsearch.search.SearchParseException: [users][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [
{
  
    "template": {
        "id": "tpa",    
        "params": {
          "query_string": "Lin"    
        }
    }
  
}]]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:721)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:557)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:529)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:291)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.search.SearchParseException: [users][1]: from[-1],size[-1]: Parse Failure [No parser for element [template]]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:703)
	... 9 more
[2015-04-24 14:28:22,930][DEBUG][action.search.type       ] [White Tiger] [users][0], node[Ns63JdBSTsyhhTtAeS-8bA], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@455da0f6] lastShard [true]

**Comment by olivere** [comment]
I see. Search templates are really confusing IMHO. Let's figure this out...

Can you successfully run this in your ES installation (notice that it creates a `test` index and a `my_template2` search template)?

```
# Set up the index and add some documents
echo Delete index...
curl -XDELETE 'localhost:9200/test/'
echo
echo Create index...
curl -XPUT 'localhost:9200/test/' -d '{"settings":{"index":{"number_of_shards":1,"number_of_replicas":0}}}'
echo

# Add some documents
echo Add documents...
curl -XPOST 'localhost:9200/test/testtype/1' -d '{"text":"value1_foo"}'
curl -XPOST 'localhost:9200/test/testtype/2?refresh=true' -d '{"text":"value2_foo value3_foo"}'
curl -XPOST 'localhost:9200/test/_refresh'
echo

# Now set up a template for querying by name via match
echo Delete search template...
curl -XDELETE 'localhost:9200/_search/template/my_template2'
echo
echo Create search template...
curl -XPUT 'localhost:9200/_search/template/my_template2' -d '{
  "template": {
    "query": {
      "match": {
        "text" : "{{my_value}}"
      }
    }
  }
}'
curl -XPOST 'localhost:9200/_refresh'
echo

# Now use the search template to search by keyword
echo Searching with template...
curl -XGET 'localhost:9200/test/_search/template' -d '{
  "template": {
    "id": "my_template2"
  },
  "params": {
    "my_value": "value1_foo"
  }
}'
echo
```

It should return the first document in the index (`value1_foo`).

The output should be something like this:

```
Delete index...
{"acknowledged":true}
Create index...
{"acknowledged":true}
Add documents...
{"_index":"test","_type":"testtype","_id":"1","_version":1,"created":true}{"_index":"test","_type":"testtype","_id":"2","_version":1,"created":true}{"_shards":{"total":1,"successful":1,"failed":0}}
Delete search template...
{"found":true,"_index":".scripts","_type":"mustache","_id":"my_template2","_version":3}
Create search template...
{"_id":"my_template2","_version":4,"created":true}{"_shards":{"total":117,"successful":116,"failed":0}}
Searching with template...
{"took":1,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":1,"max_score":1.0,"hits":[{"_index":"test","_type":"testtype","_id":"1","_score":1.0,"_source":{"text":"value1_foo"}}]}}
```

**Comment by olivere** [comment]
BTW: There seems to be something wrong on the Elasticsearch documentation page. I posted [this issue](https://github.com/elastic/elasticsearch/pull/10768) to clarify. IIRC Mustache tags must be written as `{{...}}`. The [Search Template docs](http://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html) use the `{{...}}` syntax, while the [Template Query docs](http://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-template-query.html) use `{...}`.

Can you check your code against this, too?

**Comment by olivere** [comment]
As far as i can tell it turns out that it works like this.

The template gets expanded as is. So there's two ways to make your query work.

**a) Searching with the `/_search/template` endpoint**

```
# Register template
curl -XPUT 'localhost:9200/_search/template/my_template2' -d '{
  "template": {
    "query": {
      "match": {
        "text" : "{{my_value}}"
      }
    }
  }
}'

# Search
curl -XGET 'localhost:9200/test/_search/template' -d '{
  "template": {
    "id": "my_template2"
  },
  "params": {
    "my_value": "value1_foo"
  }
}'
```

**b) Searching with the `/_search` endpoint**

```
# Register template
curl -XPUT 'localhost:9200/_search/template/my_template3' -d '{
  "template": {
    "match": {
      "text" : "{{my_value}}"
    }
  }
}'

# Search
curl -XGET 'localhost:9200/test/_search?pretty' -d '{
  "query": {
    "template": {
      "id": "my_template3",
      "params": {
        "my_value": "value1_foo"
      }
    }
  }
}'
```

Notice the subtle differences both in registering the template (the `query` is missing in b)) and the way to pass parameters when searching.

Can you confirm my findings?

As far as I can see, Elastic (the Go client) currently only supports b).

**Comment by ishare** [comment]
Thanks very much for your explanation. I try several method include with two {{. Thanks to your comment, I notice there is no "query" following template when PUT the template.

**Comment by olivere** [comment]
Yes. When you think of it, it's pretty clear. The defined template just gets expanded and replaced in-place. So when you add a `query` to it (like in a)), you get `{"query":{"query":{...}}}" if you use it in b).

Does this solve your issues with search and search templates?

P.S.: I have some tests for the search templates [here](https://github.com/olivere/elastic/blob/master/search_templates_test.go) in case you need working code.

**Comment by ishare** [comment]
Nice, it's working in my project. Thanks for your useful golang client, and the clear test cases.

**Comment by olivere** [comment]
You're welcome. I'll close the issue then. Feel free to create another one when necessary.
