### ISSUE TITLE
No scores when scrolling

### ISSUE THREAD

**Issue by hscells** [olivere/elastic#661]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[x] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior

Documents should have a score when scrolling (although not always).

### Please describe the actual behavior

Retrieved documents when scrolling have a score of `nil`.

### Any steps to reproduce the behavior?

```go
svc := client.Scroll("twitter").
	Type("tweet").
	Size(1000)

for {
	result, err := svc.Do(context.Background())
	if err == io.EOF {
		break
	}
	if err != nil {
		return nil, err
	}

	for _, hit := range result.Hits.Hits {
		fmt.Println(*hit.Score) // <- Oops! nil pointer dereference
	}
}
```

Why does this happen? Calculating score is expensive (https://www.elastic.co/guide/en/elasticsearch/guide/current/_sorting.html#_sorting_by_field_values)

This can be overwritten by using `track_scores`; e.g.

```go
svc := client.Scroll("twitter").
	Type("tweet").
	SearchSource(elastic.NewSearchSource().From(0).Size(10000).TrackScores(true))
```

However, this was unintuitive for me and cost me some time to figure out that this client was adding a sort by default (line 369 in scroll.go of the `bodyFirst()` method). Do you agree that this approach may not be as intuitive as a flag that could be set on the ScrollService? This isn't really a bug but it's something that I can see others possibly having issues with as well in the future.

**Comment by olivere** [comment]
Hmm... Elastic does use negative infinity to represent a "default" score. However, Elastic will also [send a `null` score](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/search/SearchHit.java#L440-L444) if the document's score is `NaN`, so we need to be able to handle that.

I think I'll keep this as is for now (as it is also a breaking change).
