### ISSUE TITLE
NewSimpleClient does not return an error for dead cluster

### ISSUE THREAD

**Issue by kmulvey** [olivere/elastic#663]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[x ] elastic.v5 (for Elasticsearch 5.x)
[x ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
elastic.NewSimpleClient() should return an error when there is no connection

### Please describe the actual behavior
a conn is returned and it does NOT think its dead.

### Any steps to reproduce the behavior?

```
scratch > cat main.go 
package main

import (
        log "github.com/Sirupsen/logrus"
        "github.com/olivere/elastic"
)

func main() {

        var client, clientErr = elastic.NewSimpleClient(
                elastic.SetURL("http://localhost:9512"),
                elastic.SetBasicAuth("username", "password"),
                elastic.SetScheme("https"),
                elastic.SetErrorLog(log.New()),
                elastic.SetInfoLog(log.New()))

        log.Info(client, clientErr)
}
> go run main.go 
INFO[0000] http://localhost:9512 [dead=false,failures=0,deadSince=<nil>] <nil> 

```

**Comment by olivere** [comment]
That's expected. [`NewSimpleClient`](https://github.com/olivere/elastic/wiki/Client#newsimpleclient) creates a client that does not sniff and does no healthchecks. Think of such a client as if you configured a `*http.Client` without ever performing a request.

What did you expect instead? If we do no sniffing we cannot know if the connection is dead or not, hence it's not dead by default.
