### ISSUE TITLE
how can i assign every boost value to each fields when initializing a new MultiMatchQuery and 

### ISSUE THREAD

**Issue by panjf2000** [olivere/elastic#671]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[x ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
i want to initialize a new MultiMatchQuery with boost of fields,but i didn't find a appropriate way to do that.

### Please describe the actual behavior
func NewMultiMatchQuery(text interface{}, fields ...string) *MultiMatchQuery {
	q := &MultiMatchQuery{
		text:        text,
		fields:      make([]string, 0),
		fieldBoosts: make(map[string]*float64),
	}
	q.fields = append(q.fields, fields...)
	return q
}
the above codes initialized field "fieldBoosts" but didn't assign values to it.
so how can i assign boosts to each fields?
@olivere

**Comment by panjf2000** [comment]
i just found out that i can pass the field list to MultiMatchQuery by setting it to "name^10.2",is it right?

**Comment by olivere** [comment]
You can either do that or use [`FieldWithBoost(...)`](https://github.com/olivere/elastic/blob/release-branch.v6/search_queries_multi_match.go#L55-L60). Field name and boost will simply [be concatenated](https://github.com/olivere/elastic/blob/release-branch.v6/search_queries_multi_match.go#L212-L220). But you're right: There is no test for it.

**Comment by panjf2000** [comment]
@olivere ok,thanks a lot!
