### ISSUE TITLE
Error 400 (Bad Request): all shards failed on nested query 

### ISSUE THREAD

**Issue by wedancedalot** [olivere/elastic#672]
### Which version of Elastic are you using?
elastic.v5 

### Please describe the expected behavior
In my application we have an object in elasticsearch which has an array of objects of different type. We are setting an index mapping like this:
`{
    "myindex": {
        "mappings": {
            "mytype": {
                "properties": {
                    "list": {
                        "type": "nested"
                    }
                }
            }
        }
    }
}`

Once I setup this mapping and if there is no data in elasticsearch yet, I receive an error when trying to query myindex/mytype with any kind of filter. Once any single record is inserted and even removed back, an error disappears. When quering myindex/mytype via curl and not via the lib there's no any error:

`{
    "took": 1,
    "timed_out": false,
    "_shards": {
        "total": 5,
        "successful": 5,
        "failed": 0
    },
    "hits": {
        "total": 0,
        "max_score": null,
        "hits": []
    }
}`

Any idea where to look? Thanks

**Comment by olivere** [comment]
What does ES return the same when you invoke your query on the empty index with `curl`? Is it different? If it is, can you extract some Go code for me to reproduce?

**Comment by wedancedalot** [comment]
On empty index the response is same. This is a part of code i have

`// I've tried to switch from nested queries to parent-child mapping, and receive the same error. Steps to reproduce: 

const indexSettings = `{
    "mappings": {
        "address": {},
        "transaction": {
            "_parent": {
                "type": "address"
            }
        }
    }
}`

func setupMappings() error {
    indexExists, err := di.Get().Elastic.IndexExists(ApiIndex).Do(context.TODO())
    if err != nil {
        return err
    }

    if !indexExists {
        _, err = di.Get().Elastic.CreateIndex(ApiIndex).
            BodyString(indexSettings).
            Do(context.TODO())
    }

    return err
}


// Trying to get results
svc := diContainer.Elastic.
    Scroll(ApiIndex).
    Type(TypeAddress).
    Size(conf.ElasticResultsetChunkSize).
    Sort("created_at", true)

searchResult, err := svc.Do(context.TODO())

// I get Error 400 (Bad Request): all shards failed [type=search_phase_execution_exception] here`

**Comment by olivere** [comment]
I honestly do believe that it doesn't has to do anything with the nested query. Maybe you can start with the [Slice Scroll recipe](https://github.com/olivere/elastic/blob/release-branch.v5/recipes/sliced_scroll/sliced_scroll.go) and see if that works. When it does, slowly tweak it until you get the error.

What would be especially helpful is the original error you get from Elasticsearch. To do that, enable the [trace log](https://github.com/olivere/elastic/wiki/Logging), or look into the Elasticsearch log output.

**Comment by wedancedalot** [comment]
Thank you, trace log helped. The problem was not in nested query, but instead because i tried to sort on not existing field:
"reason":"No mapping found for [created_at] in order to sort on".
Sorry and thank you again
