### ISSUE TITLE
complex search

### ISSUE THREAD

**Issue by itgeniusshuai** [olivere/elastic#673]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[*] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
I want to search with term query ,sorted by some fields and return not all fields  

### Please describe the actual behavior
I use source().query().sortBy() but actual result without term query conditions and sort is not right ,
source or query can't use at same time?

**Comment by olivere** [comment]
Please post the code so I can reproduce.

**Comment by itgeniusshuai** [comment]
client,_ := elastic.NewClient(elastic.SetURL("http://localhost:9200"))

	query := elastic.NewTermQuery("cityId",20)
	fields := make([]string,0,0)
	fields = append(fields, "cityId")
	fields = append(fields, "id")
	source := make(map[string]interface{},0)
	source["_source"] = fields
	sorter := elastic.NewFieldSort("id")
	result, err := client.Search().Index("productIndex").Source(source).Query(query).SortBy(sorter).From(int(0)).Size(int(20)).Do(ctx)
	

now sort is ok

**Comment by olivere** [comment]
How is `cityId` specified in the mapping?

**Comment by itgeniusshuai** [comment]
int value, I create a document by java client, so field type is the type that actual value type i insert and java type is int

**Comment by olivere** [comment]
I'm sorry, I cannot reproduce with a complete example.

I guess it has to do with `.Source(source)` setting the body of the search, manually. That overrides all the sorting (`.SortBy(...)`) and query (`.Query(...)`) you set afterwards. See [here](https://github.com/olivere/elastic/blob/release-branch.v6/search.go#L54-L59) and [here](https://github.com/olivere/elastic/blob/release-branch.v6/search.go#L386-L394). Either you use `Source` and are responsible for the complete search body, or you use the Elastic DSL for specifying the fields you want with e.g. `FetchSourceContext`. See [here](https://github.com/olivere/elastic/blob/release-branch.v6/search_source_test.go#L84-L101) for an example.

**Comment by itgeniusshuai** [comment]
I think so.I have used the first one you advised, I will change the second one ,because it is easier.Thank you very much for your answers

**Comment by olivere** [comment]
Please [enable trace log](https://github.com/olivere/elastic/wiki/Logging) to see what happening "on the wire."

**Comment by itgeniusshuai** [comment]
code:
ctx,_ := context.WithCancel(context.Background())
	client,_ := elastic.NewClient(elastic.SetURL("http://localhost:9200"),
		elastic.SetErrorLog(log.New(os.Stderr, "ELASTIC ", log.LstdFlags)),
		elastic.SetInfoLog(log.New(os.Stdout, "Stdout", log.LstdFlags)),
		elastic.SetTraceLog(log.New(os.Stderr, "[[ELASTIC]]", 0)))
	query := elastic.NewTermsQuery("cityId",201,301)
	fields := make([]string,0,0)
	fields = append(fields, "cityId")
	fields = append(fields, "id")
	source := make(map[string]interface{},0)
	source["_source"] = fields
	sorter := elastic.NewFieldSort("cityId")
	result, _ := client.Search().Index("productIndex").Source(source).Query(query).SortBy(sorter).From(int(0)).Size(int(20)).Do(ctx)

result:
[[ELASTIC]]POST /productIndex/_search HTTP/1.1
Host: localhost:9200
User-Agent: elastic/6.1.0 (windows-amd64)
Transfer-Encoding: chunked
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip

1
{
1a
"_source":["cityId","id"]}
0


Stdout2018/01/12 17:34:52 POST http://localhost:9200/productIndex/_search [status:200, request:0.017s]
[[ELASTIC]]HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8

{"took":2,"timed_out":false,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0},"hits":{"total":20,"max_score":1.0,"hits":[{"_index":"productIndex","_type":"productIndex","_id":"110162201","_score":1.0,"_source":{"cityId":201,"id":"110162201"}},{"_index":"productIndex","_type":"productIndex","_id":"113539201","_score":1.0,"_source":{"cityId":201,"id":"113539201"}},{"_index":"productIndex","_type":"productIndex","_id":"190003299301","_score":1.0,"_source":{"cityId":301,"id":"190003299301"}},{"_index":"productIndex","_type":"productIndex","_id":"190009466201","_score":1.0,"_source":{"cityId":201,"id":"190009466201"}},{"_index":"productIndex","_type":"productIndex","_id":"110162301","_score":1.0,"_source":{"cityId":301,"id":"110162301"}},{"_index":"productIndex","_type":"productIndex","_id":"1213681801","_score":1.0,"_source":{"cityId":1801,"id":"1213681801"}},{"_index":"productIndex","_type":"productIndex","_id":"19001509504","_score":1.0,"_source":{"cityId":2904,"id":"19001509504"}},{"_index":"productIndex","_type":"productIndex","_id":"1101621016","_score":1.0,"_source":{"cityId":1016,"id":"1101621016"}},{"_index":"productIndex","_type":"productIndex","_id":"21567941","_score":1.0,"_source":{"cityId":201,"id":"21567941"}},{"_index":"productIndex","_type":"productIndex","_id":"21591491","_score":1.0,"_source":{"cityId":201,"id":"21591491"}}]}}


from log ,request body lack query conditions

**Comment by olivere** [comment]
Yes. That confirms what I said in a previous comment.

When you do something like this:

```
source := map[string]interface{}{
  "_source": fields,
},
sorter := elastic.NewFieldSort("id")
result, err := client.Search().Index("productIndex").Source(source).Query(query).SortBy(sorter).From(int(0)).Size(int(20)).Do(ctx)
```

... you are overriding the search body with what you have in `source`. As you can see from the HTTP request:

```
POST /productIndex/_search HTTP/1.1
Host: localhost:9200
User-Agent: elastic/6.1.0 (windows-amd64)
Transfer-Encoding: chunked
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip

1
{
1a
"_source":["cityId","id"]}
0
```

There is no `query` and no `sorter` in there, like you said. That's because the `Source(something)` will forget everything else you set in your Search API call, and just use (the serialized version of) `something` as the body of the HTTP request.

You are probably looking for `FetchSourceRequest`, not `Source`. See [here](https://github.com/olivere/elastic/blob/release-branch.v6/search_source_test.go#L84-L101) for an example.

**Comment by itgeniusshuai** [comment]
I use FetchSourceRequest and I get a right result,below are code and request body
[code]
fsc := elastic.NewFetchSourceContext(true).Include("cityId","id")
	result, _ := client.Search().Index("productIndex").Query(query).FetchSourceContext(fsc).SortBy(sorter).From(int(0)).Size(int(20)).Do(ctx)

[request]
Host: localhost:9200
User-Agent: elastic/6.1.0 (windows-amd64)
Transfer-Encoding: chunked
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip

1
{
85
"_source":{"includes":["cityId","id"]},"from":0,"query":{"terms":{"cityId":[201,301]}},"size":20,"sort":[{"cityId":{"order":"asc"}}]}
0

Before this，I see your wiki ,but it seems not contains FetchSourceRequest,so I try Source(elastissearch api has it),I will see your demos more, Thank you

**Comment by olivere** [comment]
You're welcome.
