### ISSUE TITLE
FieldStatsService causes elasticsearch deprecation log messages

### ISSUE THREAD

**Issue by oldenbur** [olivere/elastic#675]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[X] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v6 (for Elasticsearch 6.x)

elasticsearch v5.5.1 to be exact

### Please describe the actual behavior
When [FieldStatsService.Do()](https://godoc.org/gopkg.in/olivere/elastic.v5#FieldStatsService.Do) is called, elasticsearch will log a line like the following into it's deprecation log (e.g. `/var/log/elasticsearch/mycluster_deprecation.log`):
```
[2018-01-15T19:47:04,883][WARN ][o.e.d.r.a.RestFieldStatsAction] [_field_stats] endpoint is deprecated! Use [_field_caps] instead or run a min/max aggregations on the desired fields.
```

### Any steps to reproduce the behavior?
I believe any call to [FieldStatsService.Do()](https://godoc.org/gopkg.in/olivere/elastic.v5#FieldStatsService.Do) when running against an elasticsearch v5.4 or greater will trigger this behavior. Elasticsearch documentation says that the [_fields_stats API was deprecated in elasticsearch 5.4](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/search-field-stats.html).

I see that the [v5 code](https://github.com/olivere/elastic/blob/v5.0.61/field_stats.go#L127) uses the deprecated API.

**Comment by olivere** [comment]
Thanks for reporting. I will check and fix it when I find some more time.

**Comment by olivere** [comment]
The next version of elastic v5 and v6 include the [Field Capabilities API](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/search-field-caps.html). It replaces the old Field Stats API.
