### ISSUE TITLE
Please support _source fetching for bulk updates

### ISSUE THREAD

**Issue by dynaxis** [olivere/elastic#677]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[v] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
`BulkService` should be able to use for updates with `_source` fetching.

### Please describe the actual behavior
`UpdateResponse` has `GetResult` field, but the counter part in `BulkResponseItem` doesn't.
Also there is no way to specify fetching of  `_source` after updates.

**Comment by olivere** [comment]
Yes, that's a long standing issue, although never reported. I will have to check how this can be done best.

**Comment by olivere** [comment]
I added this to both v5 and v6, and new versions will be pushed today.

First, set [`ReturnSource(true)`](https://github.com/olivere/elastic/blob/a2bbdd2baa18ba9062d73ecdc69d38fe6fbc4354/bulk_test.go#L216), then read the returned document via [`GetResult`](https://github.com/olivere/elastic/blob/a2bbdd2baa18ba9062d73ecdc69d38fe6fbc4354/bulk_test.go#L338-L353).

**Comment by dynaxis** [comment]
Thanks. I've never expected you to add this feature this soon. 👍
