### ISSUE TITLE
Get the final request JSON from SearchService?

### ISSUE THREAD

**Issue by pratapan9** [olivere/elastic#681]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[X ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
After issuing the query through SearchService I dont get any response back even for 'MatchAll' request. I am able to get the query source through .Source() call. That works when I try it in Kibana, but I am not sure whats wrong with the final request thats sent to ES. 

From the SearchRequest is there a way to get the final request JSON and not just the query as above. My From/Size also seem to be correct

**Comment by olivere** [comment]
There is an example of working with `SearchService` in [example_test.go](https://github.com/olivere/elastic/blob/release-branch.v6/example_test.go#L159-L210).

**Comment by pratapan9** [comment]
Thanks.. Ive been doing very similar to above..  I am able to use .Source() on the Query object to get the JSON query which looks correct..  But still  I am getting no results.. (same query works in Kibana) 
To debug this is there a way to get the final JSON query thats dispatched to ES when we do SearchService.Do(context) ?  I didnt see any getters for it

**Comment by olivere** [comment]
You can [enable the trace log](https://github.com/olivere/elastic/wiki/Logging) to log both requests and response.
