### ISSUE TITLE
ReindexService does not return 'task id' when WaitForCompletion is false

### ISSUE THREAD

**Issue by ArcticSnowman** [olivere/elastic#682]
### Which version of Elastic are you using?

[ x ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v6 (for Elasticsearch 6.x)

When ReIndexService is executed with 'WaitForCompletion' set to 'false'  ES returns a task ID.  This is ignored by the GO package.

A simple fix would be to add a 'task' element to the ReindexServiceResponse (v3) and BulkIndexByScrollResponse (v5+) to capture this and make it available to use with the Task API

**Comment by olivere** [comment]
I just backported the relevant APIs and structures to v3 (see d43d481409c12eca37b0776cc74b92a920dacee0). Please use `DoAsync` instead of `Do` for starting the reindex task in the background.

Switching to 3.0.72 should enable the same behavior as v5 and v6 already have. I will close your #683.

Notice that elastic.v3 is no longer supported.

**Comment by ArcticSnowman** [comment]
Why do you support 'WaitForCompletion' if your asking users to do DoAsync rather than Do?  Seems like your branching your own api design model for this one?   Other items (like SnapshotCreateService) just use 'Do' for both 'block' and 'non-block' requests...

**Comment by olivere** [comment]
Yep, I agree it's not the best design. However, those methods return two completely different response structures. So you either return an `interface{}`, shoehorn everything into a single response structure, or create two different functions.

I don't know right now, but if `SnapshotCreateService` and other APIs behave the same, they should probably do the same.

**Comment by olivere** [comment]
Turns out you can use a single `Do` as `SnapshotCreateService` returns a [unique response](https://github.com/olivere/elastic/blob/release-branch.v6/snapshot_create.go#L168-L191), regardless of `wait_for_completion`. See also [`CreateSnapshotResponse.java`](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/create/CreateSnapshotResponse.java#L69-L96).

**Comment by ArcticSnowman** [comment]
Um,   `tasks_get_task`  may not work in ES < 5.x as tasks details do not stay around when the tasks complete.  
2.4 returns the follow when you call  `_tasks/r0SlPN4-RdSTFXZchOS7Gw:15228569?pretty`

```
{
  "nodes" : {
    "r0SlPN4-RdSTFXZchOS7Gw" : {
      "name" : "reqes003-test2",
      "transport_address" : "192.168.124.73:9300",
      "host" : "192.168.124.73",
      "ip" : "192.168.124.73:9300",
      "attributes" : {
        "max_local_storage_nodes" : "1",
        "master" : "true"
      },
      "tasks" : {
        "r0SlPN4-RdSTFXZchOS7Gw:15228569" : {
          "node" : "r0SlPN4-RdSTFXZchOS7Gw",
          "id" : 15228569,
          "type" : "transport",
          "action" : "indices:data/write/reindex",
          "start_time_in_millis" : 1516291103034,
          "running_time_in_nanos" : 719849518919
        }
      }
    }
  }
}
```

**Comment by olivere** [comment]
The Tasks List API for 2.4 is [specified here](https://github.com/elastic/elasticsearch/blob/2.4/rest-api-spec/src/main/resources/rest-api-spec/api/tasks.list.json).

Tasks Get API isn't document in 2.4, you are correct. I will have to check again.

**Comment by olivere** [comment]
Okay. So we have integration tests for both the [sync](https://github.com/olivere/elastic/blob/release-branch.v3/reindex_test.go#L202-L262) and the [async](https://github.com/olivere/elastic/blob/release-branch.v3/reindex_test.go#L264-L335) case. Both succeed with Elasticsearch 2.4.6.

Regarding the Tasks Get API, you are correct: It doesn't exist in 2.4 (and I'll remove it in v3.0.73). You can simulate behavior with Tasks List API though by periodically polling via Tasks List API, passing the TaskId you're looking for. If the task is still busy, the length of the `Nodes` field in the response structure is 1; if it's done, it is 0. The async test case [uses this heuristic](https://github.com/olivere/elastic/blob/release-branch.v3/reindex_test.go#L310-L334). Not perfect, but without a fully-fledged Tasks Get API, I assume there's nothing we can do.

On the wire, it looks like this:

```
POST /_reindex?pretty=1&wait_for_completion=false HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/3.0.73 (darwin-amd64)
Transfer-Encoding: chunked
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip

44
{"dest":{"index":"elastic-test2"},"source":{"index":"elastic-test"}}
0


HTTP/1.1 200 OK
Content-Length: 45
Content-Type: application/json; charset=UTF-8

{
  "task" : "ALYjwhIIT6yllnFpvCCD-g:7744"
}

GET /_tasks/ALYjwhIIT6yllnFpvCCD-g%3A7744?pretty=1 HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/3.0.73 (darwin-amd64)
Accept: application/json
Accept-Encoding: gzip


HTTP/1.1 200 OK
Content-Length: 520
Content-Type: application/json; charset=UTF-8

{
  "nodes" : {
    "ALYjwhIIT6yllnFpvCCD-g" : {
      "name" : "Power Skrull",
      "transport_address" : "127.0.0.1:9300",
      "host" : "127.0.0.1",
      "ip" : "127.0.0.1:9300",
      "tasks" : {
        "ALYjwhIIT6yllnFpvCCD-g:7744" : {
          "node" : "ALYjwhIIT6yllnFpvCCD-g",
          "id" : 7744,
          "type" : "transport",
          "action" : "indices:data/write/reindex",
          "start_time_in_millis" : 1516309818741,
          "running_time_in_nanos" : 7071700
        }
      }
    }
  }
}

GET /_tasks/ALYjwhIIT6yllnFpvCCD-g%3A7744?pretty=1 HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/3.0.73 (darwin-amd64)
Accept: application/json
Accept-Encoding: gzip


HTTP/1.1 200 OK
Content-Length: 282
Content-Type: application/json; charset=UTF-8

{
  "node_failures" : [ {
    "type" : "failed_node_exception",
    "reason" : "Failed node [ALYjwhIIT6yllnFpvCCD-g]",
    "caused_by" : {
      "type" : "resource_not_found_exception",
      "reason" : "task [ALYjwhIIT6yllnFpvCCD-g:7744] is missing"
    }
  } ],
  "nodes" : { }
}
```

Regarding your comment as to tasks not staying around: I guess there's nothing we can do.

**Comment by ArcticSnowman** [comment]
@olivere  - The method of polling the tasks is what I had already implemented..  My comment on tasks not staying around was to reinforce my point that the TasksGetTask.go would not work .  

Great work on this GO Library..  It really helping up migrate from ES 1.7 to ES 5.6... (vis ES 2.4)

**Comment by olivere** [comment]
@ArcticSnowman Thanks, much appreciated. We're still on 1.7 for one app. ES is moving too fast for us :-)
