### ISSUE TITLE
[v5] TaskId (string) from ReindexService.DoAsync() does not work with TasksList.TaskId() which expects a int64

### ISSUE THREAD

**Issue by ArcticSnowman** [olivere/elastic#685]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ x ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior

According to https://www.elastic.co/guide/en/elasticsearch/reference/2.4/tasks.html the TaskID is a string not just a int64.

TasksList.TaskId() should accept a string not a int64.

**Comment by olivere** [comment]
`TaskId` is a combination of a `nodeId` (`string`) and a numeric `taskId`. It is defined in [`TaskId.java`](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/tasks/TaskId.java#L36-L37).

You have to be very careful as to where it is used. Sometimes the combination of both is required/allowed, sometimes only the numeric part is used/returned. You can only see that by looking at the Java code.

I will review again, but at first sight, it doesn't look like nothing has changed in v5 or v6.

**Comment by olivere** [comment]
I think we're good to go. I changed `TaskId` where the REST API and the Java source wants a `string`. This is a breaking change, but easy to fix and makes the code behave correctly. I changed both v5 and v6, and even backported some changes to v3.

Let me know if I've missed something. Thanks you supporting elastic.

**Comment by enrichman** [comment]
I was trying to use the CancelTask API but it seems that it still reference the TaskID as an int64: https://github.com/olivere/elastic/blob/release-branch.v6/tasks_cancel.go#L24

**Comment by olivere** [comment]
@enrichman Can you post a separate issue with an example of "what you expected" and "what actually happened" for this so we can track it? I will look into it when I find some time. IIRC it wasn't clear what to use where in the Tasks API: While the structures from ES returned a numerical task id, the HTTP request required a combination of [`node_id:task_id` for e.g. the Task Cancel API](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/tasks.html#task-cancellation). But that may have changed.
