### ISSUE TITLE
Deprecated field [_routing] used, expected [routing] instead on 6.1.2

### ISSUE THREAD

**Issue by swift1911** [olivere/elastic#686]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?
Deprecated field [_routing] used, expected [routing] instead on 6.1.2

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[* ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
change _routing to use routing

### Please describe the actual behavior
Deprecated field [_routing] used, expected [routing] instead in deprecation.log

### Any steps to reproduce the behavior?
Must appear

**Comment by olivere** [comment]
I've seen some places where this is required, but some places also where it hasn't changed from `routing` to `_routing`. Which API did you use?

**Comment by swift1911** [comment]
I use index Api Like:

elastic.NewBulkIndexRequest().Index(index_name).Type(log_model).Doc(item_json).Routing(app_name)

**Comment by olivere** [comment]
Which version of elastic are you using?

The Bulk API has recently been changed. It [is `_routing` now](https://github.com/olivere/elastic/blob/release-branch.v6/bulk_index_request.go#L50).

Please try to update to elastic.v6@v6.1.2 (or wait a few more hours to go to 6.1.3). That's the version of `elastic.v6`, _not_ Elasticsearch.

**Comment by olivere** [comment]
Plus: With 6.1.2 you should get [better performance](https://github.com/olivere/elastic/commit/e771061479895d1c7dffafd0d90ead7c9456d7cb) with Bulk API.

**Comment by swift1911** [comment]
![image](https://user-images.githubusercontent.com/9301003/35107546-32ed24c4-fcac-11e7-9efe-a93cce05fc93.png)

**Comment by swift1911** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/6.1/docs-bulk.html#bulk-routing

@olivere

**Comment by olivere** [comment]
Sorry, I mixed up [`retry_on_conflict`](https://github.com/olivere/elastic/blob/release-branch.v6/bulk_index_request.go#L48-L49) with `routing`/`_routing`.

They really shouldn't change these things in minor releases, at least without documenting it in the [breaking changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-6.1.html).

I will fix it in elastic@v6.1.4.

**Comment by olivere** [comment]
Will be fixed in 6.1.4. It's still only deprecated, and will probably be removed in 7.x.

**Comment by Smasherr** [comment]
[gitlab-elasticsearch-indexer](https://gitlab.com/gitlab-org/gitlab-elasticsearch-indexer) uses olivere/elastic currently in version 5. We would like to [get rid of deprecation](https://gitlab.com/gitlab-org/gitlab-elasticsearch-indexer/issues/34) warnings there as well and I already suggested a [MR](https://gitlab.com/gitlab-org/gitlab-elasticsearch-indexer/merge_requests/34) with update to v7. We want to stay compatible with elasticsearch 5.6 though, so update to oliviere/elastic/v7 is questionable.
@olivere Would that be somewhat possible to backport this change to v5 branch?

**Comment by olivere** [comment]
@Smasherr Changing this in elastic.v5 due to a (breaking) change in ES 6.x would potentially break all users that use `elastic.v5` with ES 5.x, [as advised](https://github.com/olivere/elastic/blob/release-branch.v7/README.md#releases). While v5 might work with ES 6.x, and potentially a mix with other versions, I explicitly don't support this, so use at your own risk.
