### ISSUE TITLE
adding a timestamp field at put step

### ISSUE THREAD

**Issue by pilere** [olivere/elastic#690]
I know that _timestamp is no longer provided and I would like to fill it manually ...

### Which version of Elastic are you using?

[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior

```
put1, err := client.Index().
			Index("matable").
			Type("montype").
			BodyJson(m).
			Do(ctx)
```
I would like to add some kind of magic to add a json timestamp at insertion time ...

**Comment by olivere** [comment]
You should probably add it to your `m` struct. Or am I missing something?

**Comment by pilere** [comment]
Le 22/01/2018 à 15:40, Oliver Eilhard a écrit :
>
> You should probably add it to your |m| struct. Or am I missing something?
>

I probably could ... the json is coming directly from an external API so 
I thought I could mess around directly with either the mapping in ES or 
the client elastic that would 'add' a current time timespan ...
I am kind of lost here ...

Stéphane

**Comment by olivere** [comment]
You could simply wrap the `m` with something along the lines of:

```
type TypeOfM struct {
  Name string `json:"name"`
}

type MWithTimestamp struct {
  TypeOfM
  Timestamp time.Time `json:"timestamp"`
}

put, err := client.Index("idx").BodyJson(MWithTimestamp{TypeOfM: m, Timestamp: time.Now().UTC()}).Do(ctx)
...
```

It's late and I had a busy day in the office, so forgive me if I'm missing something.

**Comment by pilere** [comment]
Le 22/01/2018 à 18:42, Oliver Eilhard a écrit :
>
> You could simply wrap the |m| with something along the lines of:
>
> |type TypeOfM struct { Name string `json:"name"` } type MWithTimestamp 
> struct { TypeOfM Timestamp time.Time `json:"timestamp"` } put, err := 
> client.Index("idx").BodyJson(MWithTimestamp{TypeOfM: m, Timestamp: 
> time.Now().UTC()}).Do(ctx) ... |
>
> It's late and I had a busy day in the office, so forgive me if I'm 
> missing something.
>

that's so easy !
thank you so much !

Stéphane
