### ISSUE TITLE
`healthcheck` method in `Client` doesn't work

### ISSUE THREAD

**Issue by ZaniaDeveloper** [olivere/elastic#693]
### Which version of Elastic are you using?

- [ ] elastic.v2 (for Elasticsearch 1.x)
- [ ] elastic.v3 (for Elasticsearch 2.x)
- [ ] elastic.v5 (for Elasticsearch 5.x)
- [x] elastic.v6 (for Elasticsearch 6.x)

`curl 'http://127.0.0.1:9200/'` gives:
```json
{
  "name" : "my-es",
  "cluster_name" : "my-cluster",
  "cluster_uuid" : "XSwwybHQRCiNm-Kj7yyuCg",
  "version" : {
    "number" : "6.1.1",
    "build_hash" : "bd92e7f",
    "build_date" : "2017-12-17T20:23:25.338Z",
    "build_snapshot" : false,
    "lucene_version" : "7.1.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

### Please describe the expected behavior
`Client.healthcheck` method declares connection as dead but it should be alive.

### Please describe the actual behavior
The program show:
```console
ES-ERROR: elastic: http://127.0.0.1:9200 is dead [status=400]
panic: no Elasticsearch node available

goroutine 1 [running]:
main.main()
        /data/projects/ramefral/proto/elastic/elastic.go:59 +0xf35
```

I saw that `NewClient` function (Client Constructor) calls 2 methods if Health Check is enabled:
1. first, the 'startupHealthcheck' method
2. then, the 'healthcheck' method

The 'startupHealthcheck' method succeeded, because it sends HEAD HTTP request to the URL `http://127.0.0.1:9200/`.

I checked by `curl --head 'http://127.0.0.1:9200/'` and it returns:
```console
HTTP/1.1 200 OK
content-type: application/json; charset=UTF-8
content-length: 428
```
It's ok.

But the 'healthcheck' method failed, because it sends HEAD HTTP request to the URL `http://127.0.0.1:9200/?timeout=5000ms`.

Indeed, I checked by `curl --head 'http://127.0.0.1:9200/?timeout=5000ms'` and it returns:
```console
HTTP/1.1 400 Bad Request
content-type: application/json; charset=UTF-8
content-length: 245
```

So i could suppose that the ElasticSearch 6.x API is badly used because the ElasticSearch is alive and not dead.

### Any steps to reproduce the behavior?
Here the source code used:
```go
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/olivere/elastic"
)

// Connection parameters
const (
	URL     = "http://127.0.0.1:9200"
	INDEX   = "my_index"
	MAPPING = "my_type"
)

func main() {
	// Configuration
	cfg := []elastic.ClientOptionFunc{
		elastic.SetURL(URL),

		elastic.SetSniff(false),

		elastic.SetInfoLog(log.New(os.Stdout, "ES-INFO: ", 0)),
		elastic.SetTraceLog(log.New(os.Stdout, "ES-TRACE: ", 0)),
		elastic.SetErrorLog(log.New(os.Stdout, "ES-ERROR: ", 0)),
	}

	// New Client
	client, err := elastic.NewClient(cfg...)
	if err != nil {
		panic(err)
	}

	query := client.Search().Index(INDEX).Type(MAPPING)

	result, err := query.Do()
	if err != nil {
		panic(err)
	}

	fmt.Println("Document count:", result.Hits.TotalHits)
	fmt.Println()
}
```

**Comment by ZaniaDeveloper** [comment]
Thank you

**Comment by olivere** [comment]
Hmm... I'm sorry, I cannot reproduce. The [`healthcheck` uses `context.WithTimeout`](https://github.com/olivere/elastic/blob/release-branch.v6/client.go#L1017-L1019) and [`startupHealthcheck` uses a `http.Client` with an implicit timeout](https://github.com/olivere/elastic/blob/release-branch.v6/client.go#L1082). AFAICS there is no healthcheck-related `timeout` query parameter in elastic.v2 to elastic.v6. So I don't know see any requests like `http://127.0.0.1:9200/?timeout=5000ms`.

Can you check to see what [version](https://github.com/olivere/elastic/blob/release-branch.v6/client.go#L29) you are using?

**Comment by olivere** [comment]
Sorry. Wasn't meant to be closed.

**Comment by olivere** [comment]
Any news on this?

**Comment by ZaniaDeveloper** [comment]
I've already detailed that, i use ElasticSearch 6.1.1 and when i do:
```shell
curl -I 'http://127.0.0.1:9200/?timeout=5000ms'
```

It responds:
```shell
HTTP/1.1 400 Bad Request
content-type: application/json; charset=UTF-8
content-length: 245
```

With:
```shell
curl 'http://127.0.0.1:9200/?pretty&timeout=5000ms'
```

It responds:
```shell
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "request [/] contains unrecognized parameter: [timeout]"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "request [/] contains unrecognized parameter: [timeout]"
  },
  "status" : 400
}
```

But after updating your library, i tested with this code:
```go
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/olivere/elastic"
)

// Connection parameters
const (
	URL     = "http://127.0.0.1:9200"
	INDEX   = "my_index"
	MAPPING = "my_type"
)
package main

import (
	"context"
	"fmt"
	"log"
	"os"

	"github.com/olivere/elastic"
)

// Connection parameters
const (
	URL     = "http://127.0.0.1:9200"
	INDEX   = "my_index"
	MAPPING = "my_type"
)

func main() {
	// Configuration
	cfg := []elastic.ClientOptionFunc{
		elastic.SetURL(URL),

		//elastic.SetSniff(false),

		elastic.SetInfoLog(log.New(os.Stdout, "ES-INFO: ", 0)),
		elastic.SetTraceLog(log.New(os.Stdout, "ES-TRACE: ", 0)),
		elastic.SetErrorLog(log.New(os.Stdout, "ES-ERROR: ", 0)),
	}

	// New Client
	client, err := elastic.NewClient(cfg...)
	if err != nil {
		panic(err)
	}

	query := client.Search().Index(INDEX).Type(MAPPING)

	result, err := query.Do(context.Background())
	if err != nil {
		panic(err)
	}

	fmt.Println("Document count:", result.Hits.TotalHits)
	fmt.Println()
}
```

And it works.

**Comment by charlesvdv** [comment]
Hi @ZaniaDeveloper, 

I've the same problem as you had with version `6.1.7` of this package. I'm currently using ElasticSearch version `6.2.1`. Which version of `olivere/elastic` are you using ?

Thanks!

**Comment by olivere** [comment]
@charlesvdv Please double-check that you really use the latest version. I promise there is no `"timeout"` query parameter passed anywhere in `client.go`. Did you use a dependency manager to pin the version of `github.com/olivere/elastic` that you use? Make sure you didn't accidentally checkout the `master` branch, but `release-branch.v6`.

**Comment by charlesvdv** [comment]
Here is what contains my `Gopkg.lock`: 

```toml
[[projects]]
  name = "github.com/olivere/elastic"
  packages = [
    ".",
    "config",
    "uritemplates"
  ]
  revision = "9f4560b20fb3bd4bb855fada3e6feea59b26ce66"
  version = "v6.1.7"
```

Thanks for your response!

**Comment by olivere** [comment]
That commit is very recent. And it failed with e.g. the above code that ZaniaDeveloper created?

**Comment by charlesvdv** [comment]
I found my problem. The url I was using was looking like: `elasticsearch:9200` and it was working great with curl but it looks like go or this package requires the protocol prefix before like `http://elasticsearch:9200`.

**Comment by olivere** [comment]
@charlesvdv Oh, I see. I had that discussion a while ago, and reached the conclusion that `elasticsearch:9200` is not the URL you think it is.

```
package main

import (
	"fmt"
	"net/url"
)

func main() {
	u, err := url.Parse("elasticsearch:9200")
	if err != nil {
		panic(err)
	}
	fmt.Printf("%#v\n", u)
}
```

... prints:

```
&url.URL{Scheme:"elasticsearch", Opaque:"9200", User:(*url.Userinfo)(nil), Host:"", Path:"", RawPath:"", ForceQuery:false, RawQuery:"", Fragment:""}
```

... for recent versions of Go, while it error'd for (I think) 1.6 and earlier.

See https://play.golang.org/p/wbaSdFSrnlj
