### ISSUE TITLE
Composite aggregation support?

### ISSUE THREAD

**Issue by snowzach** [olivere/elastic#695]
Is anyone already working on Composite aggregation support?
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-composite-aggregation.html

I couldn't find anything about it... Is there a supportable way to still use the library to do custom endpoints that aren't supported yet? The function list is a little overwhelming to comb through so I'm sure I'm missing something.

**Comment by snowzach** [comment]
I went ahead and did PR #696 adding support for this.

**Comment by olivere** [comment]
Done in 326718fbca3bf9e863894f36bc488398e0904f0b.
