### ISSUE TITLE
possible duplicated index when retry in bulk processor

### ISSUE THREAD

**Issue by wangxiangyu** [olivere/elastic#697]
hi, @olivere 
I look through the code of bulk processor  and don't find the logic which to parse the bulk response of each request. 
So  for example `doc A` in bulk request, successfully indexed after first bulk request， but there is error for other request,  the bulk request is retried. I s it possible that `doc A is indexed more than once`? 
Thank you

**Comment by olivere** [comment]
Bulk processor uses `BulkService` for comitting data and parsing the response (see [here](https://github.com/olivere/elastic/blob/release-branch.v6/bulk_processor.go#L472-L476)). The actual call and JSON response parsing [happens here](https://github.com/olivere/elastic/blob/release-branch.v6/bulk.go#L245-L262). Bulk index, update, and delete requests are serialized in `bulk_index_request.go`, `bulk_update_request.go` and `bulk_delete_request.go` respectively.

If something goes wrong, you (i.e. the application) is responsible for deciding what happens next, not `BulkProcessor`, as I [wrote in the Wiki](https://github.com/olivere/elastic/wiki/BulkProcessor#error-handling). If you need more control over the bulk indexing process, using Bulk API with `BulkService` is fairly straightforward to do yourself.

Let me know if this does not answer your question, and I'll re-open the issue.

**Comment by olivere** [comment]
Oh, one final thing: Yes, Bulk Processor uses the same retry logic as any other service in Elastic by default. Maybe that's why some docs get indexed more than once. But [in a recent update](d2219c2438ba6598db654794f018522c0f88c918), I allowed setting your own retrier in the Bulk and Scroll API.

**Comment by wangxiangyu** [comment]
@olivere I understand what you mean.

**Comment by wangxiangyu** [comment]
@olivere  I  try to implement retry just as   [logstash retry](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#_retry_policy).
 When I parse [BulkResponse](https://github.com/olivere/elastic/blob/release-branch.v5/bulk.go#L259), I can get the failed items.  But how can I the get the according request item by the fail item?
Any idea? Thank you!

**Comment by olivere** [comment]
Hi! What do you mean by "retry is implicit"? It is on by default, yes. But you can control it with your own backoff.

With regards to the `BulkResponse`: The document is not returned by the Bulk API, so Elastic won't have it. You just create the `BulkableRequest` again and send it into the processor. For finding out which document failed, you can use e.g. its ID.

If all of this is too complicated with `BulkProcessor`, it's very easy to do on your own with the normal `BulkService`. Then you have a lot of control over the whole process.
