### ISSUE TITLE
Wiki out-of-date?

### ISSUE THREAD

**Issue by cemremengu** [olivere/elastic#702]
### Which version of Elastic are you using?
[-] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
I expect the examples in the wiki work

For example [this ](https://github.com/olivere/elastic/wiki/BulkIndex) that I am using

### Please describe the actual behavior
Don't think any of them works 😄 

### Any steps to reproduce the behavior?
Give it a try

**Comment by cemremengu** [comment]
This actually led me to discover the `BulkProcessor`, for which the examples, work and is actually what I really want. Great work!

**Comment by olivere** [comment]
Can you explain what doesn't work?

Notice that you need to use [different clients for different Elasticsearch](https://olivere.github.io/elastic/) versions. I won't have the time to create examples for any supported combination of Elastic/Elasticsearch. Most of the time, it's just a change in the import path anyway.

**Comment by cemremengu** [comment]
Functionality works, the errors are about syntax. For example `Do` requires `context` but most of the examples doesnt mention it.

**Comment by olivere** [comment]
Yeah, okay. Documentation is time-consuming. I'm sorry about this. I need to update with v7, really. I created #703.
