### ISSUE TITLE
Can't use automatic slicing in a reindex operation

### ISSUE THREAD

**Issue by semafor** [olivere/elastic#706]
### Which version of Elastic are you using?

[x] elastic.v5 (for Elasticsearch 5.x)
[x] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
Elastic has, since 5.1, supported [automatic slicing](https://www.elastic.co/guide/en/elasticsearch/reference/5.1/docs-reindex.html#docs-reindex-automatic-slice), and olivere/elastic should trivially support this.

### Please describe the actual behavior
I can't find support in olivere/elastic for this.

**Comment by olivere** [comment]
Yep. Looks like I've missed that.

**Comment by olivere** [comment]
I've added support for this in v5.0.64 and v6.1.7. Thanks for your support.
