### ISSUE TITLE
MatchQuery generates bad request for ES 5.6

### ISSUE THREAD

**Issue by ArcticSnowman** [olivere/elastic#708]
[ x ] elastic.v5 (for Elasticsearch 5.x)

Using the following code 
```
func DateQuery (start time.Time, end time.Time) (*es5.RangeQuery) {
    return es5.NewRangeQuery(opts.DateField).Gte(start.Unix()).Lte(end.Unix())
}

func MustQuery (queries ...es5.Query) (*es5.BoolQuery) {
    return es5.NewBoolQuery().Must(queries...)
}

func IdQuery(ids []string) (*es5.MatchQuery) {
    return es5.NewMatchQuery(opts.IdField, ids)
}
func TransferDocs ( start time.Time, end time.Time, src ESIndex, dst ESIndex, ids []string) {
    //Get the documents from source

    date_q := DateQuery(start,end)
    id_q   := IdQuery(ids)

    source_cxt := es5.NewFetchSourceContext(true)

    search_src := es5.NewSearchSource().Query(MustQuery(date_q,id_q)).FetchSourceContext(source_cxt).Size(len(ids))

    if ! IsOldESVer(src.ESVersion) {
        search_src = search_src.NoStoredFields()
    }

    results, err := src.Client.Search().Index(src.Index).SearchSource(search_src).Do(context.Background())
```

Generates a POST request trace 
```
Trace:2018/02/13 22:03:20 POST /request-sync-test-01/_search HTTP/1.1
Host: test2-request:9200
User-Agent: elastic/5.0.62 (linux-amd64)
Transfer-Encoding: chunked
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip

dd
{"_source":true,"query":{"bool":{"must":[{"range":{"epoch":{"from":1512802800,"include_lower":true,"include_upper":true,"to":1512804600}}},{"match":{"uuid":{"query":["CAA0370E-DCB1-11E7-9B14-B76131E2394B"]}}}]}},"size":1}
0
```

which then fails due to
```
Trace:2018/02/13 22:03:20 HTTP/1.1 400 Bad Request
Content-Length: 255
Connection: keep-alive
Content-Type: application/json; charset=UTF-8
Date: Tue, 13 Feb 2018 22:03:20 GMT
Server: nginx

{"error":{"root_cause":[{"type":"parsing_exception","reason":"[match] unknown token [START_ARRAY] after [query]","line":1,"col":166}],"type":"parsing_exception","reason":"[match] unknown token [START_ARRAY] after [query]","line":1,"col":166},"status":400}
```

**Comment by ArcticSnowman** [comment]
ES 1.7 is OK with that request..

**Comment by ArcticSnowman** [comment]
Updating the way the Match is created:
```func IdQuery(ids []string) (*es5.MatchQuery) {

    if len(ids) > 1 {
        return es5.NewMatchQuery(opts.IdField, strings.Join(ids," OR "))
    } else {
        return es5.NewMatchQuery(opts.IdField, ids[0])
    }

}
```   this now works with 5.6 and 1.7

**Comment by olivere** [comment]
MatchQuery will construct a query based on text/dates/numerical values. It’s meant to be used for full text search. For your use case, Ids or Terms query look more adequate (https://www.elastic.co/guide/en/elasticsearch/reference/6.0/query-dsl-ids-query.html and https://www.elastic.co/guide/en/elasticsearch/reference/6.0/query-dsl-terms-query.html), no?

**Comment by ArcticSnowman** [comment]
In my case I'm creating an app to sync indices in two clusters, that can handle using an field as the key to match documents.  As the field can be analysed or not,  MatchQuery works for that while Term/IDs queries only work for non-analyses fields whose values are in the reverse table fully not broken up.

At least that my take on the documentations.. :smile: 

This might make a good addition to the wiki on how to combine different query ticket in a search..

**Comment by olivere** [comment]
When you're working with keys that represent identity (like, in your case, guids), you typically don't want any kind of fuzziness you might get with fulltext queries, hence my thoughts. But I don't know your use case, so use what's appropriate.

**Comment by ArcticSnowman** [comment]
Thanks, turns out MatchQuery was not the right choice....   in the es 5.6 it was returning all the wrong documents for the list of fields..   So switched to IdsQuery and TermQuery..
