### ISSUE TITLE
ScrollService does not support 'scan' type to prevent any sorting

### ISSUE THREAD

**Issue by ArcticSnowman** [olivere/elastic#709]
[x ] elastic.v5 (for Elasticsearch 5.x)

ScrollService does not support 'scan' type to prevent any sorting.

If you want to scroll all the results without caring about score or sorting, the 'scan' search type needs to be supported..

Support is present in SearchService

**Comment by olivere** [comment]
Do you mean search_type=scan? That’s unsupported as of 5.0, see https://www.elastic.co/guide/en/elasticsearch/reference/5.5/breaking_50_search_changes.html

**Comment by ArcticSnowman** [comment]
ok... then the docs need an update as they
list scan and count...

**Comment by olivere** [comment]
Fixed documentation for v5 and v6. Thanks.
