### ISSUE TITLE
Query Index Through Alias Name

### ISSUE THREAD

**Issue by ZacharyJude** [olivere/elastic#712]
Hi, 
I'm new to elasticsearch, and using elastic.v5, and I want to get the index that has a specific alias name.

As I can find the solution from elasticsearch API document as below, how can I do it with olivere elastic client?

Solution by pure http request.
https://www.elastic.co/guide/en/elasticsearch/reference/5.0/indices-aliases.html

Example from document:
GET /_alias/2016

Response:
{
  "logs_20162801" : {
    "aliases" : {
      "2016" : {
        "filter" : {
          "term" : {
            "year" : 2016
          }
        }
      }
    }
  }
}

I am hoping to find some APIs in olivere elastic wrapping the above query.

I found solution in
https://github.com/olivere/elastic/wiki/Listing-all-indices-of-an-alias
It seems solve the problem in this way will cause a much bigger query as it needs to get all the alias info from elasticsearch?

**Comment by olivere** [comment]
Hi. That should be the AliasesService and should (without trying) translate to something like:

```
res, err := client.Aliases().Index("2016").Do(context.Background())
if err != nil {
  panic(err)
}
```

There are helpers on the result `res`(`AliasesResult` ) like `IndicesByAlias` and `HasAlias`.

**Comment by ZacharyJude** [comment]
Thanks olivere! I'll try this.
