### ISSUE TITLE
Client doesn't work with AWS Elasticsearch service

### ISSUE THREAD

**Issue by Napas** [olivere/elastic#715]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[x] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
Successful connection

### Please describe the actual behavior
No connection with error: "no active connection found: no Elasticsearch node available"

### Any steps to reproduce the behavior?
Try to connect to the AWS Elasticsearch service ( https://aws.amazon.com/elasticsearch-service/ )

```
	esClient, err := elastic.NewClient(
		elastic.SetURL(os.Getenv("ES_URL")),
		elastic.SetSniff(false),
		elastic.SetHealthcheck(false),
		elastic.SetErrorLog(app.Log),
		elastic.SetInfoLog(app.Log),
		elastic.SetTraceLog(app.Log),
		elastic.SetScheme(os.Getenv("ES_SCHEME")))
```

Output of _nodes/http:
```
{
  "_nodes": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "cluster_name": "xxx:baq",
  "nodes": {
    "xxxxx": {
      "name": "MrgSTcd",
      "version": "6.0.1",
      "build_hash": "d951bbf",
      "roles": [
        "master",
        "data",
        "ingest"
      ]
    }
  }
}
```

Reading other tickets I see that Elasticsearch has to return publish_address, which it doesn't in AWS Elasticsearch service. Any solutions how to workaround that?

**Comment by olivere** [comment]
I'm sorry, I'm not familiar with using Amazon Elasticsearch Service. However, I'm pretty sure you need to sign the requests. There is a [Wiki entry for AWS](https://github.com/olivere/elastic/wiki/Using-with-AWS-Elasticsearch-Service), although I'm not sure if it's up to date.

Disabling sniffing should not generate a request to the `_nodes/http` endpoint. However, the IPs must be stable if you disable sniffing.

**Comment by Napas** [comment]
It has to be a user error then. Thanks!
