### ISSUE TITLE
Seeing a data race at app startup

### ISSUE THREAD

**Issue by vsiv** [olivere/elastic#716]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[X] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
Seeing a data race at app startup - I am able to consistently reproduce it - wasn't an issue earlier - I did update my golang to `v1.10`, and updated my vendor libs - so elastic got updated from `v5.0.63` to `v5.0.65`.

Using `go1.10 darwin/amd64`

Basically, some *shared* client state is being mutated? by this line, which is being called for every connection in a separate goroutine (`client.go:1047`):
```
res, err := c.c.Do((*http.Request)(req).WithContext(ctx))
```

```
==================
WARNING: DATA RACE
Read at 0x000002b62a88 by goroutine 90:
  net/http.(*Client).deadline()
      /usr/local/Cellar/go/1.10/libexec/src/net/http/client.go:189 +0x45
  net/http.(*Client).Do()
      /usr/local/Cellar/go/1.10/libexec/src/net/http/client.go:500 +0xc2
  bitbucket.com/appcompany/app/vendor/gopkg.in/olivere/elastic%2ev5.(*Client).healthcheck.func1()
      /Users/myuser/Developer/appcompany/go/src/bitbucket.com/appcompany/app/vendor/gopkg.in/olivere/elastic.v5/client.go:1047 +0xf6

Previous write at 0x000002b62a88 by main goroutine:
  [failed to restore the stack]

Goroutine 90 (running) created at:
  bitbucket.com/appcompany/app/vendor/gopkg.in/olivere/elastic%2ev5.(*Client).healthcheck()
      /Users/myuser/Developer/appcompany/go/src/bitbucket.com/appcompany/app/vendor/gopkg.in/olivere/elastic.v5/client.go:1038 +0x36f
  bitbucket.com/appcompany/app/vendor/gopkg.in/olivere/elastic%2ev5.(*Client).healthchecker()
      /Users/myuser/Developer/appcompany/go/src/bitbucket.com/appcompany/app/vendor/gopkg.in/olivere/elastic.v5/client.go:1006 +0x118
==================

```

**Comment by olivere** [comment]
Okay, I will check that.

**Comment by olivere** [comment]
The [CI tests are running with the `-race` flag](https://github.com/olivere/elastic/blob/release-branch.v6/.travis.yml), and [no red flags are coming up](https://travis-ci.org/olivere/elastic/builds/346707217).

Can you try to create a test that fails with the given data race?

**Comment by vsiv** [comment]
Ok, let me try that..

**Comment by vsiv** [comment]
Update-

**Comment by olivere** [comment]
Can you post a runnable code example of that?

**Comment by vsiv** [comment]
@olivere sorry a bit swamped, I can repro this consistently but let me get back to you with a runnable code example.

Here's how I am initializing the client (regardless of the max retries or health check timeout settings, I see the race condition) -

```
esClient, err := elastic.NewClient(elastic.SetURL(hosts...), elastic.SetMaxRetries(10), elastic.SetHealthcheckTimeoutStartup(20*time.Second))
if err != nil {
    log.Println("es: get client: new client: " + err.Error())
    return
}
if esClient == nil {
    log.Printf("could not obtain es client: %v", hosts)
    return
}

ctx := context.Background()
info, code, err := esClient.Ping(hosts[0]).Do(ctx)
	
```

Thanks.
V

**Comment by olivere** [comment]
I'm really confused. How do you get the race condition?

```go
package main

import (
	"context"
	"testing"
	"time"

	"github.com/olivere/elastic"
)

func TestIssue716(t *testing.T) {
	hosts := []string{"http://127.0.0.1:9200"}

	esClient, err := elastic.NewClient(elastic.SetURL(hosts...), elastic.SetMaxRetries(10), elastic.SetHealthcheckTimeoutStartup(20*time.Second))
	if err != nil {
		t.Fatalf("es: get client: new client: %v", err)
	}
	if esClient == nil {
		t.Fatalf("could not obtain es client: %v", hosts)
	}

	ctx := context.Background()
	info, code, err := esClient.Ping(hosts[0]).Do(ctx)
	if err != nil {
		t.Fatal(err)
	}
	_ = info
	_ = code

	t.Log("ok")
}
```

Run as a test:

```
$ go test -race -v .
=== RUN   TestIssue716
--- PASS: TestIssue716 (0.02s)
	main_test.go:30: ok
PASS
ok  	github.com/olivere/elastic/tmp/issue-716	1.047s
```

**Comment by vsiv** [comment]
Honestly I don’t know. The above race condition is logged in my console - every time. And as you can see the goroutine stacks show where shared memory is  read but not not where it was written (stack unavailable). 

Like I mentioned earlier, it appears that - Basically, some shared client state is being mutated? by this line, which is being called for every connection in a separate goroutine (client.go:1047)

**Comment by vsiv** [comment]
@olivere Ok, I tried reproducing with the test case u posted, even tweaking it a bit, but I am not able to reproduce it via a test. But my app, I am able to everytime. But one thing I realized, I am connecting to elastic in an init() function and my app is a large one with lots of other init routines also using net/http - and that might probably the reason..

`res, err := c.c.Do((*http.Request)(req).WithContext(ctx))`

The lib is calling this line (above) from multiple goroutines (one per connection) with a shared elastic.Client which houses a net/http.Client. Acc to the net/http docs/code it is safe - ([https://golang.org/src/net/http/client.go](https://golang.org/src/net/http/client.go))

> // The Client's Transport typically has internal state (cached TCP
> // connections), so Clients should be reused instead of created as
> // needed. Clients are safe for concurrent use by multiple goroutines.
> 

So, I looked into the code of net/http/client.go - line 189 - and found the variable go is complaining - it is `c.Timeout`.

```
func (c *Client) deadline() time.Time {
	if c.Timeout > 0 {  //  <=== THIS IS THE LINE
		return time.Now().Add(c.Timeout)
	}
	return time.Time{}
}

```
It is being accessed and written by `net/http` - Does that say something to you?

Thanks.

**Comment by olivere** [comment]
Aha! Hmm... I see a single use of `http.Client.Timeout` [here](https://github.com/olivere/elastic/blob/release-branch.v6/client.go#L1082) in `startupHealthcheck`, but that copies the original `http.Client` to change its `Timeout` value. That's probably the issue you see!

Can you try to disable healthchecks so that that code isn't called anymore, just to test if that solves the problem? We might be able to change that code to use `context.WithTimeout(...)` instead of relying on the shared variable.

**Comment by olivere** [comment]
Can you please try the [`issue-716` branch](https://github.com/olivere/elastic/tree/issue-716). I have switched the code to use `context.WithTimeout` instead of relying on the shared variable `Timeout` on `http.Client` (see 15afd4aadf7fcac24d0da431f0a63e7fa3841f47).

**Comment by vsiv** [comment]
yes! this seems to have fixed the data race. good team work! 👍 
u can close this once u merge the change. 

thanks!

**Comment by olivere** [comment]
Let me know what you find. In the meantime, I'm merging the changes in the `issue-716` branch, as that's a valid change anyway.

**Comment by olivere** [comment]
Please re-open if you can reproduce it or find any more hints about what's going on.

**Comment by vsiv** [comment]
Hi @olivere 

update - concurrently reading/writing `net/http client (line 189)` `Timeout` variable on the http client is what causing the data race.

and this is the line that is triggering the possible read/write in the elastic client code -
```
res, err := c.c.Do((*http.Request)(req).WithContext(ctx))
```

Honestly, I don't have any other clues to offer at this point. I am consistently able to see the data race (every time). If you can think of anything, you can open this issue. Otherwise, if I run into more clues, I will continue posting them here.

Thanks.
V

**Comment by olivere** [comment]
I will have another look. Don’t like the elastic.Request anyway.
