### ISSUE TITLE
How to define the analyzer when creating index?

### ISSUE THREAD

**Issue by ishare** [olivere/elastic#72]
I'm here for asking questions: How to define the analyzer when creating index?

It seems by default it will not using the default analyzer I defined in `elasticsearch.yml`.
`index.analysis.analyzer.default.type: ik`

If I request: 
`http://localhost:9200/useridx/_search?q=Lin` it doesn't using the default analyzer.

And this works:
`http://localhost:9200/useridx/_search?analyzer=ik&q=Lin`

**Comment by olivere** [comment]
Hi. I'm afraid I don't have the time to answer general questions regarding Elasticsearch. There's good documentation, e.g. [here](http://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html) and [here](http://www.elastic.co/guide/en/elasticsearch/guide/current/configuring-analyzers.html). There's a [mailing list](https://groups.google.com/forum/?fromgroups#%21forum/elasticsearch) as well.

if you have any problems on applying the documentation to Elastic (the Go library) feel free to ask. The tests provided in Elastic are also a good way to learn about the exact syntax; there should be at least one example for every non-trivial feature.

**Comment by ishare** [comment]
I mean can I use `client.CreateIndex(indexName).Do()`, this kind of code to create index with analyzer?

**Comment by olivere** [comment]
Sure. That's it. See [this test](https://github.com/olivere/elastic/blob/master/index_test.go#L117). Cheers :-)

**Comment by ishare** [comment]
I found this is weird, Could you help me find out? according to the doc.
http://www.elastic.co/guide/en/elasticsearch/guide/master/_controlling_analysis.html

At search time, the order is as follows:
The analyzer defined in the query itself, else  ---- not defined, if defined,will work.
The analyzer defined in the field mapping, else  ------ no analyzer defined in field mapping.
The default analyzer for the type, which defaults to ---- not defined
The analyzer named default in the index settings, which defaults to 
 --- use client.CreateIndex(indexName).Body(xx) defined
`{"settings" : {
      "index" : {
        "analysis" : {
          "analyzer" : {
            "default" : {
              "type" : "ik",
              "tokenizer" : "ik"
            }
          }
        }
     }
}}`

The analyzer named default at node level, which defaults to --- defined in elasticsearch.yml.
`index.analysis.analyzer.default.type: ik`

The standard analyzer --- the last

I wonder why this request doesn't use ik analyzer? `http://localhost:9200/useridx/_search?q=Lin`

**Comment by olivere** [comment]
I personally don't like defining analyzers in elasticsearch.yml, but on the index level. IIRC you can use two logical names for defining default index/search analyzers, i.e. `default_index` and `default_search`.

The logic for finding analyzers is [described here](http://www.elastic.co/guide/en/elasticsearch/guide/master/_controlling_analysis.html#_default_analyzers).

**Comment by ishare** [comment]
I've check all the order of settings from the doc. I add `default_index` and `default_search` to my index setting, but still not work when I query `http://localhost:9200/useridx/_search?q=Lin`. Weird..TT

{
  "useridx" : {
    "settings" : {
      "index" : {
        "analysis" : {
          "analyzer" : {
            "default_search" : {
              "type" : "ik",
              "tokenizer" : "ik"
            },
            "default" : {
              "type" : "ik",
              "tokenizer" : "ik"
            },
            "default_index" : {
              "type" : "ik",
              "tokenizer" : "ik"
            }
          }
        }
}}

**Comment by olivere** [comment]
Did you look into the log file for an exception/parse error? Often it's a problem that a previous operation didn't succeed and you get followup errors that seem implausible.

**Comment by ishare** [comment]
I lookup the log file, no error found. I found it may be related to the analyzer, https://github.com/medcl/elasticsearch-analysis-ik .

I found in elasticsearch.yml,  `index.analysis.analyzer.default.type: ik`  will not use I declared `ik` below.

index:
    analysis:
        analyzer:
            ik:
                # type: org.elasticsearch.index.analysis.IkAnalyzerProvider
                alias: [ik_analyzer]
                tokenizer: ik
                filter: [synonym]

**Comment by olivere** [comment]
Well. Perhaps can you follow the steps outlined in that [elasticsearch-analysis-ik](https://github.com/medcl/elasticsearch-analysis-ik) repository first and see if that works at all? Is the plugin successfully registered and everything?

[Testing analyzers](http://www.elastic.co/guide/en/elasticsearch/guide/current/analysis-intro.html#analyze-api) is also invaluable for your problem. If that doesn't work, it means that the analyzer is not correctly working. Then your problem is probably not the mapping, but the analyzer.

**Comment by ishare** [comment]
the analyzer is working. but I found in `elasticsearch.yml`, `index.analysis.analyzer.default.type: ik` will not use I declared `ik` in index.analysis....

it works if I request:
`http://localhost:9200/useridx/_search?analyzer=ik&q=Lin`

And I want to know whether there's a good connection pool? 
for example: we use two elastic node, with different ip.

**Comment by olivere** [comment]
There is no connection pool. Just create two clients and share them in your application.
It uses `net/http` under the cover, and `net/http` already has a connection pool.

**Comment by ishare** [comment]
Get it, thanks.
