### ISSUE TITLE
`dep` tool imports both github.com and gopkg.in

### ISSUE THREAD

**Issue by jgoodall** [olivere/elastic#720]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[X] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior

I would expect `dep` to only import `gopkg.in/olivere/elastic.v6` since that is the only import used by the application.

### Please describe the actual behavior

`dep status` shows both `gopkg.in/olivere/elastic.v6` and `github.com/olivere/elastic`.

### Any steps to reproduce the behavior?

`main.go`:

```
package main

import (
	"fmt"
	elastic "gopkg.in/olivere/elastic.v6"
)

func main() {
	client, _ := elastic.NewClient(elastic.SetURL("http://localhost:9200"))
	fmt.Printf("client info: %v", client)
}
```

Run `dep`:
```
$ dep init
  Locking in v6.1.8 (2982cec) for transitive dep github.com/olivere/elastic
  Locking in v0.8.0 (645ef00) for transitive dep github.com/pkg/errors
  Using ^6.1.8 as constraint for direct dep gopkg.in/olivere/elastic.v6
  Locking in v6.1.8 (2982cec) for direct dep gopkg.in/olivere/elastic.v6
  Locking in master (4a8a4c1) for transitive dep github.com/mailru/easyjson

$ dep status
PROJECT                      CONSTRAINT     VERSION        REVISION  LATEST   PKGS USED
github.com/mailru/easyjson   branch master  branch master  4a8a4c1   4a8a4c1  4
github.com/olivere/elastic   v6.1.8         v6.1.8         2982cec   v6.1.8   2
github.com/pkg/errors        v0.8.0         v0.8.0         645ef00   v0.8.0   1
gopkg.in/olivere/elastic.v6  ^6.1.8         v6.1.8         2982cec   v6.1.8   1
```

I dont know if, in practice, this really matters, but it seems weird to include both.

**Comment by olivere** [comment]
Oh, you shouldn't use `gopkg.in` with v6 at all. Simply import `github.com/olivere/elastic` and ask `dep` to e.g. import `^6.1.8`.

**Comment by jgoodall** [comment]
Thanks - so in my code I import `github.com/olivere/elastic`, then run `dep init` it correctly gets latest version 6 of `github.com/olivere/elastic`, but it also gets dependencies from `gopkg.in` - the following are both in my `Gopkg.lock` file:

```
[[projects]]
  name = "github.com/olivere/elastic"
  packages = [
    ".",
    "config",
    "uritemplates"
  ]
  revision = "f9243358b15391d76b5d0e2cb816442f9cded8cc"
  version = "v6.1.12"


[[projects]]
  name = "gopkg.in/olivere/elastic.v5"
  packages = [
    ".",
    "config",
    "uritemplates"
  ]
  revision = "dbe820f35164384c998099db63481b583d53f73b"
  version = "v5.0.66"
```

What did I do wrong? Thanks.

**Comment by olivere** [comment]
Oh, you did get these on a clean project, with only import from `github.com/olivere/elastic`? Because it looks like either you or me is referencing `gopkg.in/olivere/elastic.v5` somewhere in our codebase. I will try myself.

**Comment by olivere** [comment]
Hmm... I cannot reproduce. If I do it on a clean project, `Gopkg.toml` has only one entry after `dep init`, that is:

```
[[constraint]]
  name = "github.com/olivere/elastic"
  version = "6.1.12"
```

And `Gopkg.lock` only has a reference to `github.com/olivere/elastic`. Are you sure you're not referencing v5 somewhere?

**Comment by jgoodall** [comment]
Ok, I just started from scratch and got the same results. I cant find a v5 reference, but I guess it has to be in my existing project somewhere...

**Comment by jgoodall** [comment]
Ah, sorry - v5 was referenced by another package! Thanks.
