### ISSUE TITLE
no Elasticsearch node available

### ISSUE THREAD

**Issue by cosastro** [olivere/elastic#721]
### Which version of Elastic are you using?
[ ] elastic.v2 (for Elasticsearch 1.x)
[* ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
normally access server from remote client

### Please describe the actual behavior
no Elasticsearch node available

### Any steps to reproduce the behavior?
After starting es service, the first connection is no problem, but the next time it's going to be a mistake at line "req, err := http.NewRequest("HEAD", url, nil)" in code, and when I visited http://10.10.21.19:9200/  in my browser there was no problem in the next several minutes. 

thanks.

**Comment by olivere** [comment]
Did you already [this](https://github.com/olivere/elastic/wiki/Connection-Problems#how-to-figure-out-connection-problems)?

**Comment by cosastro** [comment]
it's the problem of configuration, and has been fixed, thanks a lot.
