### ISSUE TITLE
Wiki Info Missing for MultiMatchQuery for ES 5.x

### ISSUE THREAD

**Issue by kgrvamsi** [olivere/elastic#727]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ *] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior

Was looking out for some examples on how to write a MultiMatchQuery Search and seems like Wiki is missing the info

### Please describe the actual behavior

This is not a bug but a request to add a snippet for MultiSearch Query

**Comment by olivere** [comment]
Documentation is always far from complete I guess. For now, all I can do is to [guide your to the tests for `MultiMatchQuery`](https://github.com/olivere/elastic/blob/release-branch.v6/search_queries_multi_match_test.go). They should illustrate how to work with that Search API. Let me know if you're still confused and I'll reopen the issue.

**Comment by kgrvamsi** [comment]
@olivere  Thank you and i was looking out on how to combine two queries and i got it worked with the Must and BoolQuery....sorry for this ...started reading all the ES queries now :)

**Comment by olivere** [comment]
Yes. The tests are a good reference.
