### ISSUE TITLE
How to Build a Query like this?

### ISSUE THREAD

**Issue by Dexus** [olivere/elastic#729]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?
[x] elastic.v6 (for Elasticsearch 6.x)

I have this source found at https://blog.trifork.com/2014/03/26/server-side-clustering-of-geo-points-on-a-map-using-elasticsearch-continued/
```JSON
{
    "query": {
        "match_all": {}
    },
    "size": 0,
    "aggs": {
        "filtered_cells": {
            "filter": {
                "geo_bounding_box": {
                    "location": {
                        "top_left": "50.1234, 4.0000",
                        "bottom_right": "52.1234, 4.5555"
                    }
                }
            },
            "aggs": {
                "cells": {
                    "geohash_grid": {
                        "field": "location",
                        "precision": "precision"
                    },
                    "aggs": {
                        "center_lat": {
                            "avg": {
                                "script": "doc['location'].lat"
                            }
                        },
                        "center_lon": {
                            "avg": {
                                "script": "doc['location'].lon"
                            }
                        }
                    }
                }
            }
        }
    }
}
```

How can i build this? i know that i can use [geocentroid](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-geocentroid-aggregation.html) but I don't know how to build the querys with elastic.

Can you please guide me. Thank you.

**Comment by olivere** [comment]
I understand that documentation is not as good as it should be. But please understand that I also simply don't have enough time to implement each individual request for converting the JSON API to the Go API.

Having said that, here's a few hints.

First, the tests really are helpful. They not only serve to ensure we have a solid basis when making changes, but also as a way to illustrate usage. E.g. [`search_aggs_test.go`](https://github.com/olivere/elastic/blob/release-branch.v6/search_aggs_test.go) illustrates using most aggregation types in an integration test.

Your query should basically look like this (without having tested it in any way):

```go
// Create a client
client, err := elastic.NewClient(...)
...
// Create the query
query := elastic.NewMatchAllQuery()
...
// Create the aggregations (best to setup from inside to outside)
cellsAgg := ...
filteredCellsAgg := elastic. NewFilterAggregation().Filter(
    elastic.NewGeoBoundingBoxQuery("location").
      TopLeft(50.1234, 4.0000).
      BottomRight(52.1234, 4.5555)
    ).
    SubAggregation("cells", cellsAgg))
...
// Execute the search
resp, err := client.Search().
  Index(...).Type(...).
  Query(query).
  Aggregation("filtered_cells", filteredCellsAgg).
  Do(context.TODO())
...
// Check the search response
filteredCellsAggRes, found := agg.Filter("cells")
if !found {
  ...
}
if filteredCellsAggRes == nil {
  ...
}
if filteredCellsAggRes.DocCount != 2 {
  ...
}
...
```

HTH.

**Comment by Dexus** [comment]
@olivere thank you for you example, now I got the result as expect. 

Thank you!
