### ISSUE TITLE
Debug method has been removed but remains in docs

### ISSUE THREAD

**Issue by pferdefleisch** [olivere/elastic#73]
Debug was removed in this merge https://github.com/olivere/elastic/commit/78b87db2a9c53fb29acfaca1c16764d66a7ac519#diff-059dc0366ae402fcb2b70107da19b22d but it remains in the docs. I would make a pull request but there I don't know how the project is handling this now.

Thank you

**Comment by pferdefleisch** [comment]
It's in the wiki too https://github.com/olivere/elastic/wiki/Search

**Comment by olivere** [comment]
Oh, you're correct. Sorry. Thanks for reporting.

**Comment by olivere** [comment]
I hope I didn't miss a `Debug` somewhere...
