### ISSUE TITLE
Fielddata error when sorting the rows from the index

### ISSUE THREAD

**Issue by kgrvamsi** [olivere/elastic#731]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[* ] elastic.v5 (for Elasticsearch 5.x)  -->Elastic Search: 5.6.8
[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior

Was trying to execute the following code 

```
hostquery := elastic.NewBoolQuery().Must(elastic.NewTermQuery("last_updated", date))
	res, err := eclient.Search().
		Index("testing.inventoryhosts").
		Type("InventoryHosts").
		Query(hostquery).
		From(0).Size(6000).
		Pretty(true).
		Sort("last_updated", true).
		Do(ctx)
	if err != nil {
		return nil, err
	}
```
and i get the following error

![image](https://user-images.githubusercontent.com/1199031/37472183-74d001a0-2839-11e8-8609-127edeb5f25e.png)

Index details for the field last_updated

![image](https://user-images.githubusercontent.com/1199031/37472211-8a17b92c-2839-11e8-94c6-531c7ea923ea.png)

@olivere can we have fielddata set to true?i was checking some information from the elasticsearch docs and they say that execution of the query based on the fielddata happens from the heap memory and it is not recommended way but can use the keyword instead of the keeping fielddata as true.

Reference url: 
https://www.elastic.co/guide/en/elasticsearch/reference/current/fielddata.html

``
Instead, text fields use a query-time in-memory data structure called fielddata. This data structure is built on demand the first time that a field is used for aggregations, sorting, or in a script. It is built by reading the entire inverted index for each segment from disk, inverting the term ↔︎ document relationship, and storing the result in memory, in the JVM heap.
``

Can you please suggest me a way on how to achieve this fetching around 6000+ records from a particular index(looking out for a efficient way).Any code examples will help

**Comment by olivere** [comment]
You should be able to simply use ...

```
elastic.NewTermQuery("last_updated.keyword", date)
```

... in your query above and everything should be fine.

If that doesn't work, respond and I'll reopen the issue. We'll find a way.

**Comment by olivere** [comment]
I'm sorry, you should also use `last_updated.keyword` for sorting.

**Comment by kgrvamsi** [comment]
@olivere just for my understanding what is the difference between last_updated and last_updated.keyword?

When i changed this from last_updated to last_updated.keyword it worked and changing this value will be impacted on the heap size or its a general query that ES takes?

**Comment by olivere** [comment]
@kgrvamsi When you use `last_updated`, it uses the default field specified in your mapping. When you use `last_updated.keyword`, it uses the field registered under the name `keyword` in your mapping:

```
{
  "last_updated": {
    "type": "text",
    "fields": {
      "keyword": {
        "type": "keyword"
      }
    }
  }
}
```

As the default field uses `"type": "text"`, it is suitable for full-text queries. Using `last_updated.keyword`, it will refer to the field with the type `"type": "keyword"`, which is suitable for exact matches and e.g. sorting.

This is pretty amazing ES stuff you should get used to. If you're unsure, [the docs are great](https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-fields.html).

**Comment by kgrvamsi** [comment]
@olivere thanks for making my life so easy with the above explanation and have started reading all the docs.
