### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by abhishekamte** [olivere/elastic#738]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?
elastic.v5 (for Elasticsearch 5.x)

My elasticsearch cluster is accessible only via https, does this library support this? If yes, how?

**Comment by olivere** [comment]
Sure. It uses the default HTTP client if you don’t pass your own configured client. See the Wiki for an example on how to configure and pass your own net/http.Client/Transport.

**Comment by abhishekamte** [comment]
I get an error saying 
> no active connection found: no Elasticsearch node available

Here is my http client setup code 

    cert, err := tls.LoadX509KeyPair(certFile, keyFile)
	if err != nil {
		return nil, err
	}
	caCert, err := ioutil.ReadFile(caFile)
	if err != nil {
		return nil, err
	}
	caCertPool := x509.NewCertPool()
	caCertPool.AppendCertsFromPEM(caCert)

	// Setup HTTPS client
	tlsConfig := &tls.Config{
		Certificates: []tls.Certificate{cert},
		RootCAs:      caCertPool,
		InsecureSkipVerify: true,
	}
	tlsConfig.BuildNameToCertificate()
	transport := &http.Transport{
		Dial: (&net.Dialer{
			Timeout: 5 * time.Second,
		}).Dial,
		TLSClientConfig:     tlsConfig,
		TLSHandshakeTimeout: 5 * time.Second,
	}

	httpClient:= &http.Client{
			Transport: transport,
			Timeout:   time.Second * 10,
	}
        esClient, err := elastic.NewClient(elastic.SetHttpClient(httpClient),
		elastic.SetURL("https://198.200.150.35:9200"))

	if err != nil {
		log.Println("error")
		log.Fatal(err)
	}`

If I use the httpClient directly, then I get the response.

**Comment by olivere** [comment]
Could you try to disable sniffing, please. Otherwise Elastic will Query the cluster for the node IPs, and they may not be reachable from the outside. See the Wiki again.

**Comment by toravir** [comment]
you can either do elastic.SetSniff(false) OR you can add elastic.SetSchema("https") - when calling elastic.NewClient(). The thing with sniffing is - it uses default schema - "http"..

**Comment by olivere** [comment]
@toravir When you enabling sniffing, it will just use whatever the cluster returns as the Node IPs/URLs. If it returns a `http`-based URL, it will use that. If that URL is `https`, it will use that. I tried to [explain it in the Wiki](https://github.com/olivere/elastic/wiki/Sniffing).

What does `curl -XGET 'http://<your-initial-elasticsearch-cluster-url>/_nodes/http?pretty=true'` print for you?

**Comment by toravir** [comment]
The code adds the 'scheme' in the both the return statements in  https://github.com/olivere/elastic/blob/release-branch.v6/client.go#L985

Yes, i understand the disabling Sniff option from the wiki. When i tried setting the scheme to 'https' it worked with Sniff..

anyways the _nodes output is here:
```
[root@swtb75-ifc1 ~]# curl --cacert /cacert.crt --cert /server.crt --key /server.key 'https://1XXXXXX:9200/_nodes/http?pretty=true' -k                                                                    
{                                                                                                                                                            
  "_nodes" : {                                                                                                                                               
    "total" : 1,                                                                                                                                             
    "successful" : 1,                                                                                                                                        
    "failed" : 0                                                                                                                                             
  },
  "cluster_name" : "elasticsearch",
  "nodes" : {
    "9dQmEH4tQC62b2nfW5cyEA" : {
      "name" : "sxxxxxx",
      "transport_address" : "10.0.0.1:9300",
      "host" : "10.0.0.1",
      "ip" : "10.0.0.1",
      "version" : "6.1.1",
      "build_hash" : "bd92e7f",
      "roles" : [
        "master",
        "data",
        "ingest"
      ],
      "http" : {
        "bound_address" : [
          "10.0.0.1:9200"
        ],
        "publish_address" : "10.0.0.1:9200",
        "max_content_length_in_bytes" : 104857600
      }
    }
  }
}
[root@swtb75-ifc1 ~]#
```
ES Version:

```
  "version" : {
    "number" : "6.1.1",
    "build_hash" : "bd92e7f",
    "build_date" : "2017-12-17T20:23:25.338Z",
    "build_snapshot" : false,
    "lucene_version" : "7.1.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
```

**Comment by olivere** [comment]
@toravir If that server had been configured to use `https` internally, that `curl` command should return something like this:

```
{
  ...
  "nodes" : {
    "9dQmEH4tQC62b2nfW5cyEA" : {
      ...
      "https" : {        // <- there should be a "https" here, not a "http"
        ...
      }
    }
  }
}
```

**Comment by toravir** [comment]
I guess it may depend on the security plugin used in ES. Am using Searchguard plugin. Refer to this: https://github.com/khezen/docker-elasticsearch. May be if using X-Pack - it may be showing https... I couldn't find a docker image with Xpack readily available to try this..

If you want to recreate to these steps:
```
$ docker run -d --rm --name essg -p 9200:9200 -p 9300:9300 -e ELASTIC_PWD=changeme -e KIBANA_PWD=changeme  khezen/elasticsearch:latest

$ docker exec -it essg bash
bash-4.4# cd /elasticsearch/config/searchguard/ssl/

## After about 30 secs for ES to come up...

bash-4.4# curl --cacert ca/chain-ca.pem --key ./elastic.key.pem --cert ./elastic.crt.pem:changeme https://127.0.0.1:9200/_nodes/http?pretty=true
```

**Comment by olivere** [comment]
@toravir I'm not aware of that plugin. Elastic is transparent with regards to any middleware. If you have anything in between elastic, the Go client, and Elasticsearch, the server, you are responsible for configuring the two to get it to work. You can do so by e.g. using your own `*http.Client` (because the middleware e.g. uses TLS/certificates) that elastic simply re-uses, disabling sniffing/healthchecks (because your middleware already does that) etc.
