### ISSUE TITLE
elastic.RandomFunction - Missing field param (also shown in deprecation log)

### ISSUE THREAD

**Issue by vsiv** [olivere/elastic#739]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[X ] elastic.v6 (for Elasticsearch 6.x)

Hi olivere-

I am seeing this in the deprecation log- you might already be familiar with this
```
[o.e.d.i.q.f.RandomScoreFunctionBuilder] As of version 7.0 Elasticsearch will require that a [field] parameter is provided when a [seed] is set
```

`elastic.RandomFunction` is not exposing a field param - it would be great if we can add it as I can certainly use it! For example, you can set it to `_seq_no`...

[elastic.co ref link](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#function-random)

**Comment by olivere** [comment]
I will add a `Field` method to `RandomFunction` in the next release, due later today.

Thanks.
