### ISSUE TITLE
Regarding Stream data from Mysql DB 

### ISSUE THREAD

**Issue by roushanj** [olivere/elastic#743]
[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior

I want to stream data from mysql db which has multiple table's directly , currently i am able to create a client from aws elastic search.

Is automatic indexing is possible ? if yes then how?if No help me with right path.

### Any steps to reproduce the behavior?

We can do it by using a config file called ( .toml ) to setup our sql db and add some rules into for indexing but don't know how to use it.

**Comment by olivere** [comment]
I don't know if someone has created a package for automatic indexing from MySQL to Elasticsearch. I know @rwynn has a package for doing so with MongoDB (https://github.com/rwynn/monstache). Maybe that's extensible, or you can use it as a blueprint.

When I use MySQL and ES in combination, I typically do that at the code level. When a document is created, I also add it to ES; when it is updated and deleted, I also update and delete the document from ES. However, that might not be feasible if you have high-volume traffic or your application code is divided into separate siloes.

Besides that, it's pretty easy to do with your own bulk indexing code or [bulk processor](https://github.com/olivere/elastic/wiki/BulkProcessor).

HTH.
