### ISSUE TITLE
NodesInfoNode struct should include roles field

### ISSUE THREAD

**Issue by snowzach** [olivere/elastic#744]
Including the roles field would allow us to use the SetSnifferCallback to exclude nodes that were say master only.

### Which version of Elastic are you using?
6.x

### Please describe the expected behavior
The roles would be included in the NodesInfoNode

### Please describe the actual behavior
Not There

**Comment by snowzach** [comment]
Create Pull #745

**Comment by olivere** [comment]
Merged with #745
