### ISSUE TITLE
Marshalling Error with % Symbol

### ISSUE THREAD

**Issue by niallnsec** [olivere/elastic#748]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[x] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
% symbols in strings should be marshalled as is.

### Please describe the actual behavior
% symbols in strings are treated as format specifiers.

### Any steps to reproduce the behavior?

I am searching a data set that contains data extracted from the meta tags of HTML web pages. The data is stored as an array of objects that have the following format:

```
{
  "name": "twitter:creator",
  "value": [
    "yorbaorganics"
  ]
},
{
  "name": "twitter:title",
  "value": [
    "Yorba Organics: 100% Natural Origin Skincare"
  ]
},
```

It seems that if any of the strings in the value arrays contain a % symbol then they are not marshalled correctly. The above data is returned as follows when running a TermsQuery:

```
{
    "name": "twitter:creator",
    "value": ["@yorbaorganics"]
},
{
    "name": "twitter:title",
    "value": ["Yorba Organics: 100%!N(MISSING)atural Origin Skincare"]
}
```

This can also result in invalid JSON being returned, the following data is an example:

```
{
  "name": "msapplication-TileColor",
  "value": [
    "hsla(0",
    "0%",
    "100%",
    "0)"
  ]
},
```

This data, when obtained through a TermsQuery is marshalled as:
```
{"name":"msapplication-TileColor","value":["hsla(0","0%!"(MISSING),"100%!"(MISSING),"0)"]}
```

**Comment by niallnsec** [comment]
It looks like this may actually be an issue with the Go standard libraries json.Unmarshal function.
And __INCREDIBLY__ hacky workaround is to change line 26 in decoder.go to read:
```go
return json.Unmarshal([]byte(strings.Replace(string(data), "%", "%%", -1)), v)
```
Although this may cause issues in other parts of the document.

**Comment by olivere** [comment]
I'm not exactly sure which side is responsible for that. I'm pretty sure Go correctly encodes JSON, as well as Elasticsearch. And Elastic is using the `encoding/json` for all encoding. Can you maybe send a small reproducible test case that illustrates the problem.

Regarding the workaround: That's not going to happen ;-)

**Comment by niallnsec** [comment]
Thanks for the quick reply, I have to apologise here because while I was trying to put together a test case I found that the issues was completely my fault. There is (apparently) a filter program also written in Go that is sat between elasticsearch and my machine which was mangling the JSON before it was output. I didn't learn this fact until about 10 minuets ago so it never crossed my mind that it could be the cause.

My stupid temporary hack above only worked because it escaped the % upstream.
Sorry again for wasting your time.

**Comment by olivere** [comment]
No problem. We all have those days, don't we :-)
