### ISSUE TITLE
How to create subfilter for ScoreFunction

### ISSUE THREAD

**Issue by carash** [olivere/elastic#749]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[x] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior

I am currently tring to make a query like this, using subfilters so specific features can be boosted.

- https://www.elastic.co/guide/en/elasticsearch/guide/current/function-score-filters.html#CO117-3
- https://www.elastic.co/guide/en/elasticsearch/guide/current/function-score-filters.html#CO117-4
- https://www.elastic.co/guide/en/elasticsearch/guide/current/function-score-filters.html#CO117-5

```
{
  "query": {
    "function_score": {
      "functions": [ 
        {
          "filter": { "term": { "features": "wifi" }}, 
          "weight": 1
        },
        {
          "filter": { "term": { "features": "garden" }}, 
          "weight": 1
        },
        {
          "filter": { "term": { "features": "pool" }}, 
          "weight": 2 
        }
      ],
      "score_mode": "sum", 
    }
  }
}
```

From what I understand, the **FunctionScoreQuery** can be given a top-level `filter`, but there is no way (that I know of) to create subfilters for a **ScoreFunction**. Is there actually a way to do this or is it currently not yet implemented?

**Comment by olivere** [comment]
I hope [this test](https://github.com/olivere/elastic/blob/release-branch.v6/search_queries_fsq_test.go#L168-L187) solves your issue. If it doesn't, feel free to respond and I'll re-open the issue.
