### ISSUE TITLE
missing quote_field_suffix in simple_query_string

### ISSUE THREAD

**Issue by slawo** [olivere/elastic#750]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[X] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
The following code should be valid:

```
main() {
	ID := "1234"
	q := elastic.NewSimpleQueryStringQuery(`"` + ID + `"`)
	q.Field("items.id")
	q.Field("discounts.id")
	q.QuoteFieldSuffix(".exact")
	//...
}
```

### Please describe the actual behavior

`SimpleQueryStringQuery` doesn't implement `QuoteFieldSuffix()`

### Any steps to reproduce the behavior?

The code above.

Refer to https://www.elastic.co/guide/en/elasticsearch/reference/master/mixing-exact-search-with-stemming.html for another example of a valid query.

**Comment by olivere** [comment]
Yep. That makes sense. Thanks for letting me know.
