### ISSUE TITLE
Help on applying updates immediately

### ISSUE THREAD

**Issue by yuva29** [olivere/elastic#753]
It takes about ~25s for any update (through bulk operation to be specific) to reflect in search. Is there any way to make the changes reflect immediately. Below are options I tried but no luck. 

1. Setting `Refresh(true)` on the bulk service.
2. Flushing the index before search request.

Any help would be grateful.

**Comment by olivere** [comment]
That‘s unusually slow. Refresh is the way to go if you want your results to immediately be returned in search queries. This usually slows down indexing so if you don’t need it, don’t do it. See 
https://www.elastic.co/guide/en/elasticsearch/reference/6.2/docs-refresh.html.

We’re indexing several thousand documents per second, and our documents are larger than usual. It should be even faster than that. There must be something wrong with your cluster, but that’s hard to tell without further details.

**Comment by yuva29** [comment]
@olivere thank you for the quick response. I figured the root cause of the issue. It was mainly due to our system, nothing to do with elastic search itself.
