### ISSUE TITLE
GetService doesn't ignore 404 error when a document is not found

### ISSUE THREAD

**Issue by gavillom** [olivere/elastic#754]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[x ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
When I run a e.Client.Get().Index("myIndex").	Id("notFoundId").Do(e.Ctx), I don't expect an error to be returned by the Elasticsearch client. I should just be able to understand the document has no been found regarding the "found" attribute of the response.

I expect this behavior due to the documentation Getting Started code : 

if get1.Found {
		fmt.Printf("Got document %s in version %d from index %s, type %s\n", get1.Id, get1.Version, get1.Index, get1.Type)
	}

### Please describe the actual behavior
Currently the client return an error in this case. The HTTP 404 Not found error is not ignored by the client and considered as an unexpected behaviour from Elasticsearch server.

### Any steps to reproduce the behavior?
 1. Create an index with no document
 2. Try to launch a client.Get().Index("myIndex").Id("oneId").Do(ctx)

**Comment by olivere** [comment]
This is the standard behavior of Elasticsearch. If you retrieve a document that doesn't exist, Elasticsearch returns a 404, which we will just forward to the caller:

```
$ curl -I 'localhost:9200/twitter/_doc/1?pretty=true'
HTTP/1.1 404 Not Found
content-type: application/json; charset=UTF-8
content-length: 504

```

This is what the Java REST Client does as well. See [here](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-low-usage-responses.html):

> A ResponseException is not thrown for HEAD requests that return a 404 status code because it is an expected HEAD response that simply denotes that the resource is not found. All other HTTP methods (e.g., GET) throw a ResponseException for 404 responses unless the `ignore` parameter contains 404.

Elastic has that `ignore` parameter as well, but it's not the default for the Get API, see [`PerformRequest`](https://github.com/olivere/elastic/blob/release-branch.v6/client.go#L1169).

To differentiate between "not found" and other errors, you can use error helpers like [`elastic.IsNotFound`](https://github.com/olivere/elastic/blob/release-branch.v6/errors.go#L103):

```
res, err := client.Get().Index("twitter").Id("1").Do(ctx)
switch {
case elastic.IsNotFound(err):
  ...
case elastic.IsConnErr(err):
  ...
case elastic.IsTimeout(err):
  ...
case err != nil:
  ...
}
```

TBH I really don't know why there is a `found` property in the response of the Get API. Maybe that's just a relict from earlier versions. E.g. in some response structs, they already removed it or changed it to something more general, like `result`. This is what I've e.g. found in ES 6.0.0-alpha1 recently with the Delete API, which also doesn't make too much sense:

```
{
	"found": false,
	...
	"result": "not_found",
	...
}
```

They removed the `found` property from Delete API in 6.0.0-alpha2 I think.

**Comment by olivere** [comment]
Okay, sorry for the confusion. I think the code still works in 6.2 though, but perhaps it's no longer idiomatic. Feel free to post an issue for that and link back to this issue, if you will.

I think the idiomatic way to work with the Get API is to just retrieve the document, then check if it's not found. It's a bit like opening a file, then checking that it doesn't exist. Checking beforehand is two roundtrips while just trying to retrieve is just one.

Something like this:

```
res, err := client.Get("twitter").Id("1").Do(ctx)
if err != nil {
  if elastic.IsNotFound(err) {
    ...
  } else {
    ...
  }
}
```

... or with the `switch` case I mentioned previously to handle even more error cases.
