### ISSUE TITLE
how to one time upsert bulk  struct slice like  []struct{...}{}

### ISSUE THREAD

**Issue by fancyecommerce** [olivere/elastic#758]
define  struct slice :
 []struct{...}{}

how can i bulk upsert(1. exist to update, 2 not exist to create)  struct slice

https://godoc.org/github.com/olivere/elastic#BulkUpdateRequest.Source

Sorry, I don't understand the document

**Comment by fancyecommerce** [comment]
i have get code

```
package main

import (
	"fmt"
	"gopkg.in/olivere/elastic.v2"
	"strconv"
)

type Tweet struct {
	User    string `json:"user"`
	Message string `json:"message"`
}

func main() {
	client, err := elastic.NewClient()
	if err != nil {
		fmt.Println("%v", err)
	}

	n := 0
	for i := 0; i < 1000; i++ {
		bulkRequest := client.Bulk()
		for j := 0; j < 10000; j++ {
			n++
			tweet := Tweet{User: "olivere", Message: "Package strconv implements conversions to and from string representations of basic data types. " + strconv.Itoa(n)}
			req := elastic.NewBulkIndexRequest().Index("twitter").Type("tweet").Id(strconv.Itoa(n)).Doc(tweet)
			bulkRequest = bulkRequest.Add(req)
		}
		bulkResponse, err := bulkRequest.Do()
		if err != nil {
			fmt.Println(err)
		}
		if bulkResponse != nil {

		}
		fmt.Println(i)
	}
}
```

if upsert, change

```
req := elastic.NewBulkIndexRequest().Index("twitter").Type("tweet").Id(strconv.Itoa(n)).Doc(tweet)
```

to

```
req := elastic.NewBulkUpdateRequest().Index("twitter").Type("tweet").Id(strconv.Itoa(n)).Doc(tweet).DocAsUpsert(true)
```

**Comment by olivere** [comment]
Yes. Upsert is: create if the document doesn't exist, update otherwise.

If you set `DocAsUpsert(true)`, Elasticsearch will use `doc` as the document to create if it doesn't already exist. Otherwise, it will update the document with the keys specified in `doc`. Upserts save you one roundtrip to the server. See [the documentation](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/docs-update.html#_literal_doc_as_upsert_literal).

**Comment by olivere** [comment]
BTW: There is a [bulk insert](https://github.com/olivere/elastic/blob/release-branch.v6/recipes/bulk_insert/bulk_insert.go) and a [bulk processor](https://github.com/olivere/elastic/blob/release-branch.v6/recipes/bulk_processor/main.go) recipe to illustrate typical usage patterns, e.g. for [Bulk Processor](https://github.com/olivere/elastic/wiki/BulkProcessor).

**Comment by icesmartjuan** [comment]
@olivere thanks to your valuable info,does Bulk Processor support upsert ?
