### ISSUE TITLE
How can I use it with an ES plugin

### ISSUE THREAD

**Issue by vishr** [olivere/elastic#759]
I installed https://github.com/NLPchina/elasticsearch-sql for SQL interface, however, I am not able to identify an API that will go with it.

Below is the ES query which generates the similar result as `_search`:

```sh
http://localhost:9200/_sql?sql=select * from indexName limit 10
```

### Which version of Elastic are you using?

- [ ] elastic.v2 (for Elasticsearch 1.x)
- [ ] elastic.v3 (for Elasticsearch 2.x)
- [ ] elastic.v5 (for Elasticsearch 5.x)
- [x] elastic.v6 (for Elasticsearch 6.x)

**Comment by olivere** [comment]
Hello. There is no direct support for this plugin.

As a workaround you can use the generic [`PerformRequest`](https://github.com/olivere/elastic/blob/release-branch.v6/client.go#L1160-L1179) method on `*elastic.Client`. It should look roughly like this (untested):

```
client, err := elastic.NewClient(...)
if err != nil { ... }

ctx := context.Background()
params := url.Values{}
params.Set("sql", "select * from indexName limit 10")
res, err := client.PerformRequest(ctx, elastic.PerformRequestOptions{
	Method: "GET",
	Path:   "/_sql",
	Params: params,
	Body:   nil,
})
if err != nil { ... }
// TODO Parse response res here. If it is a normal search response, you can try this:
ret := new(elastic.SearchResult)
if err := json.Unmarshal(res.Body, ret); err != nil {
	...
}
```

By using it, you can make use of Elastic's support for (simple) load-balancing and health checks. However, you're on your own when parsing the response.
