### ISSUE TITLE
Response body unmarshal error:  cannot unmarshal number into Go value of type string

### ISSUE THREAD

**Issue by TheEngineGuy** [olivere/elastic#76]
If TermsFacet field are not string type ( int/long/boolean),  the search request will throw error:

"json: cannot unmarshal number into Go value of type string"

It happened because searchFacetTerm.Term is defined as "string".   It should be "interface{}". 

search.go:
type searchFacetTerm struct {
	Term  interface{} `json:"term"`
	Count int    `json:"count"`
}

**Comment by olivere** [comment]
Sorry for the delay. I will set up a test for this and work it out. You should really switch to Aggregations; facets are deprecated. Thanks for reporting.
