### ISSUE TITLE
NodesInfoNode struct should include roles field

### ISSUE THREAD

**Issue by cesarjimenez** [olivere/elastic#761]
Including the roles field would allow us to use the SetSnifferCallback to exclude nodes that were say master only.

It is exactly the same change proposed in #744, but for Elasticsearch 5.X.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[x] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
Roles would be included in NodesInfoNode.

### Please describe the actual behavior
No roles info at all.

**Comment by cesarjimenez** [comment]
Created pull request #760.

**Comment by olivere** [comment]
Completed with e3859f4a9f87fff0d78273fd060b7155fb17b8ad.
