### ISSUE TITLE
How to disable hits tracking

### ISSUE THREAD

**Issue by lordnynex** [olivere/elastic#763]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ X] elastic.v6 (for Elasticsearch 6.x)

I have a very large Cardinality Aggregation Query. In my manual query I set `"track_total_hits": false`. I don't see a way to set this in `SearchSource` struct. Without this, my query takes quite awhile to run each time. With this value, I believe ES cache helps subsequent runs return quickly. 

Is there a way to do this?

**Comment by olivere** [comment]
Looks like it’s missing. I will add it to the relevant files. It’s a long weekend, and I hope to finally get my hands on Elastic again in the next days.

**Comment by lordnynex** [comment]
@olivere Thanks! For what it's worth, I noticed that this feature is also missing from the ES REST clients. Since they change their API so frequently, do you think it would make sense to add a method to add additional 'properties' to the query?

**Comment by olivere** [comment]
@lordnynex I see what you're after. Adding a `properties` field will make things worse in the long run, I guess. People start using it and you won't have a chance to get them back to the specific property once you add it. Also, for simple properties this might work. But what about more complex properties like `object`? I think we open up a can of worms with `properties`.

While we're never up to date it's also a chance for me to keep up-to-date with changes in Elasticsearch.
