### ISSUE TITLE
Bug: Wrong json tag for Score field in SearchSuggestionOption

### ISSUE THREAD

**Issue by jjhbw** [olivere/elastic#764]
Hi all,

First, let me thank you for your work on this brilliant library!

I came across a minor issue when using the completion suggester. Below snippet shows the `SearchSuggestionOption` struct, which unwraps each of the options proposed by the ES completion suggester. 

I think the json tag `score` is wrong, as this key in the **ES (6.2.4)** response seems to be `_score` (with an underscore prefix). 

I verified this with my own queries and with the [corresponding ES documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-completion.html#querying).

https://github.com/olivere/elastic/blob/a9051ca3a94d78a79a8d5684f24c2e2cc9650355/search.go#L521-L533

(edit: updated snippet to point at release branch v6)

**Comment by olivere** [comment]
See #747. When I last looked it up, the documentation was wrong and [the Java source still has it as `score`](https://github.com/elastic/elasticsearch/blob/6.2/server/src/main/java/org/elasticsearch/search/suggest/Suggest.java#L625), not `_score`. I just did a new release over the weekend with 6.2.4 as the basis. And as there even is [a unit test for this](https://github.com/olivere/elastic/blob/release-branch.v6/search_suggester_test.go#L159-L161), I'm pretty sure that it's still `score`, not `_score` (as it should be).

Feel free to add any observations on #747.
