### ISSUE TITLE
no elasticsearch node available

### ISSUE THREAD

**Issue by lordnynex** [olivere/elastic#767]
@olivere Sorry for making another bug with this title! I've been struggling with this off and on and it's been driving me crazy! Even with sniff set to false I was getting this error. What I realized was using govendor, it does not appear to be obeying your repositories default branch settings for v6. It pulls in master from 2016 which appears to have a bug around sniff. 

This is no longer an issue once I realized it and upgraded my vendors. It's impressive how little the API has changed that I didn't have serious compilation problems! 

Anyways, the point of this issue is to ask if you want to do anything about it? I thought about adding it to the wiki, but then I also thought the issue might go away if you periodically merge to master? 

Please feel free to close the issue, I just wanted to bring this to your attention.

**Comment by olivere** [comment]
Thanks for letting me know. I've been moved to [dep](https://github.com/golang/dep) in all of my projects recently, and that's working fine. I personally have no experience with govendor.

The master branch is waaay out of date. It's a very early version that'd probably only work with Elasticsearch 1.x and/or 2.x. The reason that sniffing fails is that Elasticsearch changed the return structure of the `/_nodes/http` endpoint between major versions. Hence sniffing fails in subtle ways if you don't use the correct version of Elastic for your Elasticsearch installation.

The reason there are different branches (and I'll switch the default branch with every major release) is that gopkg.in uses the branch name for versioning. With v6, I've switched to be compatible with `dep` as that had a high potential of being merged into the Go toolchain at that time. The algorithm that `dep` uses is [described here](https://github.com/golang/dep/blob/master/docs/FAQ.md#how-does-dep-decide-what-version-of-a-dependency-to-use).

To conclude, I think I cannot simply move to the `master` branch and think this is a problem with govendor, not Elastic.

But thanks for keeping a note here, as others might have the same problem and they can read up the conclusions here.

**Comment by josemojena** [comment]
I have the same problem too, I am using elasticsearch v6  and the last version of olivere (github.com/olivere/elastic) all I handle it by dep, but even altough disabled the sniff config always return the error "no Elasticsearch node available", please wich version I should be to use for elastic version 6

**Comment by olivere** [comment]
@josemojena I have 3 lines like this in my `Gopkg.toml` and it works fine:

```
[[constraint]]
  name = "github.com/olivere/elastic"
  version = "^6.1.22"
```

What lines do you have there in your `Gopkg.toml`?

**Comment by josemojena** [comment]
Now its working, I did not specify the version at  Gopkg.toml, thanks you for the fast answer
