### ISSUE TITLE
Failed when type is not appended

### ISSUE THREAD

**Issue by rgavriel** [olivere/elastic#770]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

Since ElasticSearch 6.0.0 type are [deprecated.](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-type-field.html)
The current code force us to work with them.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[X] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behaviour
Be able to PUT document without providing a Type parameter

### Please describe the actual behaviour
Failed on validation

### Any steps to reproduce the behaviour?
Call `client.Index()` without providing a Type.

**Comment by olivere** [comment]
As far as I understand it, [types start to be optional beginning with ES 7.x](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html#_schedule_for_removal_of_mapping_types).

Can you try to send me a `curl` request that adds a document to an Elasticsearch 6.x cluster without a type?

```
$ curl -H 'Content-Type: application/json' -XPUT 'localhost:19201/tweets/1' -d '{"user":"olivere","message":"Welcome to Golang"}'

{"error":"Incorrect HTTP method for uri [/tweets/1] and method [PUT], allowed: [POST]","status":405}

$ curl -H 'Content-Type: application/json' -XPUT 'localhost:19201/tweets/_doc/1' -d '{"user":"olivere","message":"Welcome to Golang"}'

{"_index":"tweets","_type":"_doc","_id":"1","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1}
```

I'd be happy to be proven incorrect. Just let me know.

**Comment by rgavriel** [comment]
You are correct, their documentation was not fully clear to me.
