### ISSUE TITLE
Request body compression

### ISSUE THREAD

**Issue by xose** [olivere/elastic#771]
ElasticSearch, at least on recent versions, allows for the request body to be compressed. There should be a setting on the client to compress data before sending it to ElasticSearch. This would result in big savings in bandwidth costs, especially when bulk operations are involved.

I patched elastic.Request to always compress the request body which lowered my bandwidth usage by >90%. Patch is available at xose@89f2f341b5fde4338ccfbc03734433bf40afd76b (big hack only for testing, don't merge!)

**Comment by olivere** [comment]
I'm surprised. The [default `http.Transport`](https://golang.org/pkg/net/http/#Transport) should transparently use compression. You can disable it by setting [`DisableCompression`] to `true`.

You can experiment with using different `http.Client`'s as described in [the wiki](https://github.com/olivere/elastic/wiki/HttpTransport).

**Comment by xose** [comment]
That option only requests compressed responses from the server by setting the "Accept-Encoding" header and decompressing the response. I want to compress the request body payload **sent by the client to the server**. This is especially useful when bulk inserting a lot of data.

There is currently no way to do this directly with Go's http.Client.

**Comment by olivere** [comment]
I'll have to check again. That's basically asking to revert [this commit](https://github.com/olivere/elastic/commit/30c702213d63d9815a4d195dc1f41744fd5e17d2#diff-d9c546c27e20f6a2acfc4ac7b74c1a26).

**Comment by pietv** [comment]
@olivere any decision on this request. We'd (very much) like the body compression too.

**Comment by messias72** [comment]
Hi,

I have the same issue. I want to compress the payload sent to the Elasticsearch. As xose has mentioned for a bulk you can save a lot of network traffic and costs.

best regards
Torsten

**Comment by olivere** [comment]
I have reverted [this commit](https://github.com/olivere/elastic/commit/30c702213d63d9815a4d195dc1f41744fd5e17d2#diff-d9c546c27e20f6a2acfc4ac7b74c1a26) in 6.1.20, which will be released shortly.
