### ISSUE TITLE
Parsing SubAggregation results on a Filter Aggregation

### ISSUE THREAD

**Issue by carmenbondrajr** [olivere/elastic#773]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

Using elastic.v6 on an Elasticsearch 6.2.4 cluster, I'm unable to parse buckets out of the following aggregation definition:

```
return elastic.NewFilterAggregation().Filter(elastic.NewBoolQuery().Must(queries...)).
		SubAggregation(name, elastic.NewTermsAggregation().Field(name))
```

I'd like to aggregate on a field called "Setting" while applying a few queries in a bool filter. Ultimately I'm trying to get to what I believe is the AggregationBucketKeyItems at the bottom of this struct.

The result of searchResults.Aggregations.Filter("Setting") is below:
```
{
  "Aggregations": {
   "Setting": {
    "doc_count_error_upper_bound": 0,
    "sum_other_doc_count": 0,
    "buckets": [
     {
      "key": "Large Town",
      "doc_count": 1
     },
     {
      "key": "Rural Community",
      "doc_count": 1
     }
    ]
   },
   "doc_count": 2
  },
  "DocCount": 2,
  "Meta": null
 }
```

I would expect to parse these results with something like the following:
```
filtered, _ := searchResults.Aggregations.Filter("Setting")
items, _ := filtered.Aggregations.Terms("Setting")
```
At this point, I'm anticipating items to contain *AggregationBucketKeyItems, but it is nil. 
I've noticed also that in `search_aggs.go:335` the error of unmarshaling the raw into that struct is swallowed. 

I've tried various combinations of Filter/Terms/Nested to no avail, so perhaps I'm just using it wrong, but it seems like the structure of the aggregation result does not fit into the result parsing offered.

I appreciate any and all help, thanks in advance!

**Comment by olivere** [comment]
There are a lot of tests that you might find useful. In [`search_aggs_test.go`](https://github.com/olivere/elastic/blob/release-branch.v6/search_aggs_test.go) I tend to test all kinds of different aggregations. This also illustrates [how to use `FilterAggregation` in the request](https://github.com/olivere/elastic/blob/release-branch.v6/search_aggs_test.go#L100-L103) as well as [parsing the response](https://github.com/olivere/elastic/blob/release-branch.v6/search_aggs_test.go#L585-L595), also [sub-aggregations](https://github.com/olivere/elastic/blob/release-branch.v6/search_aggs_test.go#L642-L648).

If you still can't get it to work let me know. It would really help to have a runnable test/code snippet. See [the recipes](https://github.com/olivere/elastic/tree/release-branch.v6/recipes) for a list of templates you might use.

**Comment by carmenbondrajr** [comment]
Thanks for the response, and for the helpful links. What I'm seeing in your examples is SubAggregations being accessed by keying into the Aggregations like so:

`subAgg, found := samplerAggRes.Aggregations["tagged_with"]`

which leaves you with a *json.RawMessage instead of a specific struct. It looks to me that at this point the only way to easily reference this data is to json.Marshal and json.Unmarshal this RawMessage into an AggregationBucketKeyItems struct. It works this way, I was just surprised and wondering if there was a more established way of doing this. 

For example of what I'm doing:
```
// Execute Search
searchResults, err := css.searchClient.
		Search("test-index").
		Type("test-type").
		Query(elastic.NewTermQuery("test-field", "test-val")).
		Aggregation("fooAgg",
			elastic.NewFilterAggregation().Filter(elastic.NewTermQuery("other-field", "other-value")).
				SubAggregation("subAgg", elastic.NewTermsAggregation().Field("foo"))).
		Do(context.Background())

// Parse Results
aggs := searchResults.Aggregations
queryFilterAggRes, found := aggs.Filter(name)
if !found {
	//
}

subAgg, found := queryFilterAggRes.Aggregations[name]
if !found {
	//
}

b, err := json.Marshal(subAgg)
if err != nil {
	//
}

items := &elastic.AggregationBucketKeyItems{}
err = items.UnmarshalJSON(b)
if err != nil {
        //
}

for _, bucket := range items.Buckets {
	term := bucket.Key.(string)
	label := bucket.Key.(string)
        count: int32(bucket.DocCount)
        // do something
}

```

**Comment by olivere** [comment]
You can access sub-aggregations by its type, but you need to know the type. Here's [an example for a sub-aggregation of type `Avg`](https://github.com/olivere/elastic/blob/release-branch.v6/search_aggs_test.go#L1787-L1800). There is [a rather long list of methods on the `Aggregations` type](https://github.com/olivere/elastic/blob/release-branch.v6/search_aggs.go#L23-L716) to get the sub-aggregation you want.

**Comment by olivere** [comment]
Oops. Wasn't supposed to close.

**Comment by olivere** [comment]
The [Query DSL page in the wiki](https://github.com/olivere/elastic/wiki/QueryDSL) was recently updated and illustrates creating aggregations and sub-aggregations, both from the query and retrieval side.

Let me know if I that doesn't solve the issue, and I will reopen.

**Comment by liuqianhong6007** [comment]
have resolution for this problem?

**Comment by olivere** [comment]
@littledog6007 What problem are you referring to?
