### ISSUE TITLE
DeleteIndex doesn't remove indices

### ISSUE THREAD

**Issue by ericox** [olivere/elastic#774]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ x] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
I would expect that if I have two indices in a green state

```
elasticsearch@b923a6b129ad:/$ curl localhost:9200/_cat/indices
green open prod1_index5af46372 AhPJF5fiReC5pzLYtrrtCw 5 0    0 0 1.1kb 1.1kb
green open prod2_index5af46372 UHNIUBPSQk-IGbP6JiIxnw 5 0 3038 0 2.4mb 2.4mb
```
And I execute the function

```
func tearDownIndex(client *elastic.Client, index string) {
        exists, err := client.IndexExists(index).Do(context.Background())
        if err != nil {
                log.Fatalf("%v", err)
        }
        if exists {
                _, err = client.DeleteIndex(index).Do(context.Background())
                if err != nil {
                        log.Fatalf("%v", err)
                }
        }
}
```
would remove the indices

### Please describe the actual behavior
calling the above function removes the documents in prod2_index5af46372 and both indices are in a yellow state instead of being removed

```
yellow open prod_doc_metadata_index5af46372 AhPJF5fiReC5pzLYtrrtCw 5 1    0 0 1.1kb 1.1kb
yellow open prod_rev_metadata_index5af46372 UHNIUBPSQk-IGbP6JiIxnw 5 1    0 0 1.1kb 1.1kb
```

If I curl -XDELETE localhost:9200/{index} the indices are removed.

**Comment by olivere** [comment]
This works like a charm here. Try e.g. this [code](https://github.com/olivere/elastic/blob/release-branch.v6/recipes/mapping/mapping.go) which creates and deletes an index if it already exists on the 2nd run.

It is correct that in the "expected behavior" you used `prod1_index5af46372`, while in the actual behavior you have `prod_doc_metadata_index5af46372 `, which are not the same.

**Comment by ericox** [comment]
That's a typo. I was renaming the index for sake of simplifing the
write-up. The indices are the same.
