### ISSUE TITLE
Using OAuth

### ISSUE THREAD

**Issue by swtch1** [olivere/elastic#781]
Not really a bug, just something that is either unsupported or I don't know how to do.

### Which version of Elastic are you using?

[x] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
I would like to query elasticsearch using an OAuth bearer token, which realistically means I just need to add an Authorization header.  I see I can *SetHttpClient* for the *NewClient* but I don't believe that allows me to pass the request, which is where I would set the headers.

### Please describe the actual behavior
The documentation seems to only provide *SetBasicAuth* for the *NewClient* func.

### Any steps to reproduce the behavior?
Try to add an Authorization header to *elastic.NewClient*, or through some other method.

I could just be completely ignorant of the implementation but any guidance would be greatly appreciated.

**Comment by olivere** [comment]
You can change the `*http.Request` in a multitude of ways in your own `http.Transport` implementation. The call to `SetBasicAuth` [in the Wiki](https://github.com/olivere/elastic/wiki/HttpTransport) was just one example. You could add a header for e.g. `Authorization` (that's exactly [how the Go oauth2 library uses `http.Transport`](https://github.com/golang/oauth2/blob/master/transport.go#L36-L58)), or even [change the underlying URL](https://github.com/olivere/balancers/).

I see these things as an orthogonal concept to this library so I mostly refer to custom implementations that solve that particular problem and just try to make them work within Elastic.

**Comment by olivere** [comment]
I think the [github.com/golang/oauth2](https://github.com/golang/oauth2) package would solve your problem without further ado. After all, it returns a custom `*http.Client` to you that you should be able to use seamlessly in combination with Elastic.
