### ISSUE TITLE
TotalIndexingBufferInBytes unmarshal error

### ISSUE THREAD

**Issue by NeoCN** [olivere/elastic#782]
### Which version of Elastic are you using?

 elastic.v6

### Please describe the expected behavior
run the following code
```
_, err = esClient.NodesInfo().Human(true).Do(context.Background())
````
When the cluster is OK, the `err` is expected to be `nil`

### Please describe the actual behavior
got the following error
```
json: cannot unmarshal string into Go struct field NodesInfoNode.total_indexing_buffer_in_bytes of type int64
```
when `.Human(true)`, `total_indexing_buffer_in_bytes` is present in the node info api response, e.g.
```
    "total_indexing_buffer_in_bytes": "197.9mb",
    "total_indexing_buffer": 207591833,
```
`total_indexing_buffer_in_bytes` is string

### Any steps to reproduce the behavior?
```
_, err = esClient.NodesInfo().Human(true).Do(context.Background())
````
run with `.Human(true)`

**Comment by olivere** [comment]
Thanks. Will merge the PR in the next release. 👍
