### ISSUE TITLE
Unable to use stored scripts in _update_by_query

### ISSUE THREAD

**Issue by tom10271** [olivere/elastic#785]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[x] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
Use stored scripts in _update_by_query should not have any problem. 
In ES version below 6.3, you need to set `lang` to `nil` in order to bypass this bug

### Please describe the actual behavior
It should not return:
```
{
    "error": {
        "reason": "lang cannot be specified for stored scripts",
        "root_cause": [
            {
                "reason": "lang cannot be specified for stored scripts",
                "type": "illegal_argument_exception"
            }
        ],
        "type": "illegal_argument_exception"
    },
    "status": 400
}

panic: elastic: Error 400 (Bad Request): lang cannot be specified for stored scripts [type=illegal_argument_exception]
```

### Any steps to reproduce the behavior?
https://github.com/elastic/elasticsearch/issues/28002
There is a sample procedures to recreate this bug

https://github.com/olivere/elastic/blob/release-branch.v6/script.go#L90
Can we set `lang` to `nil` if we know it is using stored script?

**Comment by olivere** [comment]
Oh well, let me see if I can provide a quick fix (though 6.3 should be out very soon).

**Comment by tom10271** [comment]
Thank you so much for helping

**Comment by tom10271** [comment]
I have tested the code again. The fix proposed is not working.

I tried to modify code in script.go to
```go
	if s.lang == "null" || s.lang == "nil" {
		// HACK(oe) Hotfix for https://github.com/elastic/elasticsearch/issues/28002; remove when 6.3 and/or 7.x are out.
		// If stored script id is set, you don't need to provide lang hint to ES
	} else if s.lang != "" {
		source["lang"] = s.lang
	}
```

then it works

**Comment by olivere** [comment]
@tom10271 The workaround in elastic/elasticsearch#28002 states that it should be set to `null`. So that is wrong? I think we have to test that for every ES version in the test matrix. A simple "works here" almost always goes wrong. I remember having a problem or two with that `lang` setting and the ID I guess.

**Comment by tom10271** [comment]
I understand your concern and here is the request body I tested and the error I got:
https://github.com/elastic/elasticsearch/issues/28002#issuecomment-391213836

**Comment by olivere** [comment]
TBH if this is correct I don't understand how this failed in the first place. Before the change it was:

```
if s.lang != "" {
	source["lang"] = s.lang
}
```

... and you propose this change now:

```
if s.lang == "null" || s.lang == "nil" {
	// HACK(oe) Hotfix for https://github.com/elastic/elasticsearch/issues/28002; remove when 6.3 and/or 7.x are out.
	// If stored script id is set, you don't need to provide lang hint to ES
} else if s.lang != "" {
	source["lang"] = s.lang
}
```

... which is 100% the same as before?!

**Comment by olivere** [comment]
The only thing you had to do was set `.Lang("")` ... I will revert the quick fix now (I hate quick fixes: they tend to make things worse).

**Comment by tom10271** [comment]
The problem is the request body will be:
```json
{
    "script": {
        "id": "merge-asset-profiles",
        "lang": "",
        "params": {
            "updated_at": 1527048588
        }
    }
}
```

but the working one and probably the correct one should be:
```json
{
    "script": {
        "id": "merge-asset-profiles",
        "params": {
            "updated_at": 1527048588
        }
    }
}
```

**Comment by olivere** [comment]
No problem. I revert the changes in 6.1.22. I added an integration test to a) illustrate usage of UpdateByQuery with a stored script and b) to guard against regressions.

You should probably use `NewScriptStored(...)` instead of `NewScript(...)` because the latter is an alias for `NewScriptInline(...)`. If you use `NewScriptStored`, you don't even have to set `Lang("")`. It just works.

**Comment by olivere** [comment]
[Link to integration test](https://github.com/olivere/elastic/blob/release-branch.v6/update_integration_test.go#L60-L132) for UpdateByQuery API with a stored script and parameters.

**Comment by olivere** [comment]
6.1.22 will also add the GetScript, PutScript, and DeleteScript APIs ([docs](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/modules-scripting.html)). So now one can manage the stored scripts with Elastic as well.
