### ISSUE TITLE
wrong aggr result

### ISSUE THREAD

**Issue by itgeniusshuai** [olivere/elastic#788]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

The pId is the field I order by ,cityId is the field I aggr

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ *] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
[{"cityId":1401,"cityId_count":25}{"cityId":524,"cityId_count":19},{"cityId":610,"cityId_count":16}]

### Please describe the actual behavior
[{"cityId":1401,"cityId_count":25},{"pId":153022,"pId_count":1},{"cityId":524,"cityId_count":19},{"cityId":610,"cityId_count":16}]

### Any steps to reproduce the behavior?
query es per 5 seconds untill reproduce

**Comment by olivere** [comment]
I'm sorry but without further details I'm unable to solve this issue. If you post a small test case or a runnable program, that would help.

However, I'm pretty sure that you're having an issue with the index not being refreshed (see [here](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/indices-refresh.html) and [here](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/docs-refresh.html)) when you start your query. Besides that, Elastic is just a client and will serialize the response from Elasticsearch. So you're having an Elasticsearch issue, not an issue with Elastic.
