### ISSUE TITLE
how can i search the result with more than one terms

### ISSUE THREAD

**Issue by szy441687879** [olivere/elastic#790]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[1 ] elastic.v6 (for Elasticsearch 6.x)

I need to search the result with more than one terms,such as direct.keyword:gz AND cpu_used:>0.4 in query,how can i  explain it in olivere/elastic,

**Comment by olivere** [comment]
You should understand [how to do this with Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html), then translate it to the syntax that Elastic required.

There's a myriad of ways how to achieve this. So I can't really help with a simple sentence. You might e.g. use a [boolean query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html) that combines a [term query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html) and a [range query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-range-query.html), or you could do this with a full text query like [query string query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html) or [simple query string query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html).

Once you struggle with the Elastic query setup, let me know and I can help. Look into the tests to see how to do it.
