### ISSUE TITLE
Removal of duplicate based on some condition

### ISSUE THREAD

**Issue by ssenthil416** [olivere/elastic#793]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?
[ x ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
We have millions of rows as part of elastic, in that we found many duplicate IDs, we want to clean it up
We have query to first 10000 record to return duplicate
agg := elastic.NewTermsAggregation().Field("_id").MinDocCount(2).Size(10000)
search = client.Search("employee")
search = search.Aggregation("myterm", agg)
sr, err := search.Do(context.TODO())### Please describe the actual behavior

### Any steps to reproduce the behavior?
but we want this query to run for all millions of record we have and we want to get use of scroll API of elastic for it....

Can any one please help us

**Comment by olivere** [comment]
If I understand correctly, you want to have more information about using the Scroll API with Elastic?

So [here's an entry in the Wiki](https://github.com/olivere/elastic/wiki/ScrollParallel) and a [recipe for doing sliced scroll](https://github.com/olivere/elastic/blob/release-branch.v6/recipes/sliced_scroll/sliced_scroll.go). As always, you can look into the [tests](https://github.com/olivere/elastic/blob/release-branch.v6/scroll_test.go) to see how to create a scrolling iterator.

Notice that scrolling is fast and most efficient if you do not sort: See [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html).
