### ISSUE TITLE
Get All Documents and not only 10 

### ISSUE THREAD

**Issue by niso120b** [olivere/elastic#797]
Hi, If I want to get all the document in search its always return only 10, but I have more and I don't want to use From and Size function, how can I do it?!
Thanks

**Comment by olivere** [comment]
Well, there has to be a default value for `Size` which looks like it is `10`. Returning all documents by default is obviously a bad choice. Just imaging you have billions of documents (like we do). Why don't you want to use `From` and `Size`? That's the way to go.

Also remember that there is a default upper bound for `Size` (10000 I think) which you can increase (although that's a bad idea resource-wise). If you have millions or billions of documents, you should use the Scroll API and iterate over all documents like a cursor in a database.
