### ISSUE TITLE
unable to upsert array of objects

### ISSUE THREAD

**Issue by bryceageno** [olivere/elastic#798]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[* ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
I am trying to upsert a array of objects to elastic search

### Please describe the actual behavior
What is inserted into ES is a array of empty objects with the same number of objects inserted.

query result
{
  "took": 3,
  "timed_out": false,
  "_shards": {
    "total": 29,
    "successful": 29,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_index": "testing_array_mapping_test",
        "_type": "metadata",
        "_id": "",
        "_score": 1,
        "_source": {
          "keywords": [
            {

            },
            {

            }
          ]
        }
      }
    ]
  }
}

### Any steps to reproduce the behavior?
type Keyword struct{
	keywordId   string `json:"keywordId,omitempty"`
	keywordType string `json:"keywordType,omitempty"`
	weight      int64  `json:"weight,omitempty"`
	weightValue int64  `json:"weightValue,omitempty"`
	confidence  int64  `json:"confidence,omitempty"`
	vocabId     int64  `json:"vocabId,omitempty"`
	category    int64  `json:"category,omitempty"`
	keywordText string `json:"keywordText,omitempty"`
}

func (e *ElasticsearchClientWrapper) UpsertTestDoc(indexName string) error {
	keywords := []Keyword {
		Keyword {
			keywordId:   "60004",
			keywordType: "Assigned",
			weight:      5,
			weightValue: 0,
			confidence:  5,
			vocabId:     1,
			category:    -1,
		},
		Keyword {
			keywordId:   "173578",
			keywordType: "Assigned",
			weight:      2,
			weightValue: 0,
			confidence:  2,
			vocabId:     1,
			category:    -1,
		},
	}

	_, err := e.esClient.
		Update().
		Index(indexName).
		Type("metadata").
		Doc(map[string]interface{}{"keywords": keywords}).
		DocAsUpsert(true).
		Refresh("true").
		Do(context.TODO())

	return err
}

**Comment by olivere** [comment]
In Go, if you want to serialize/deserialize with `encoding/json` or `encoding/xml`, you need to make the fields of your object public. This won't work:

```
type Keyword struct{
  keywordId string json:"keywordId,omitempty"
  keywordType string json:"keywordType,omitempty"
  weight int64 json:"weight,omitempty"
  weightValue int64 json:"weightValue,omitempty"
  confidence int64 json:"confidence,omitempty"
  vocabId int64 json:"vocabId,omitempty"
  category int64 json:"category,omitempty"
  keywordText string json:"keywordText,omitempty"
}
```

but this will:

```
type Keyword struct{
  KeywordId string json:"keywordId,omitempty"
  KeywordType string json:"keywordType,omitempty"
  Weight int64 json:"weight,omitempty"
  WeightValue int64 json:"weightValue,omitempty"
  Confidence int64 json:"confidence,omitempty"
  VocabId int64 json:"vocabId,omitempty"
  Category int64 json:"category,omitempty"
  KeywordText string json:"keywordText,omitempty"
}
```

**Comment by bryceageno** [comment]
thanks
