### ISSUE TITLE
Is it possible to unmarshal JSON to a filter that can be then be used with the builders?

### ISSUE THREAD

**Issue by jbrook** [olivere/elastic#80]
I want to use the builders to construct a Scan with a query for use in an export web service. The user can specify a filter that they want to use using JSON. It will consist of a "must" or "should" filter containing an array of term filters, etc.  I would like to build a Filter from the user defined JSON and then add it to my Scan and run it. At the moment I can't see how that's possible without writing my own unmarshal code.

**Comment by olivere** [comment]
Hmm... Elastic currently doesn't have a builder that picks up JSON and fills a "structured" query. Well, [SearchSource](https://github.com/olivere/elastic/blob/master/search_source.go) is basically a builder, but it doesn't start with JSON. 

I'm not sure if I understand correctly, but this is how I'd address something like that:

Services that accept a query basically take everything that implements the [elastic.Query](https://github.com/olivere/elastic/blob/master/query.go) interface. It's very simple actually. You just need to have a function called `Source` that returns an `interface{}` (usually a `map[string]interface{}`).

In your case, I'd write my own query that simple wraps a [FilteredQuery](https://github.com/olivere/elastic/blob/master/search_queries_filtered.go) and adds your "must" and "should" filters parsed in via JSON in a [BoolFilter](https://github.com/olivere/elastic/blob/master/search_filters_bool.go#L13). On first sight, it just seems to be a bit of JSON parsing and juggling with `map[string]interface{}`.

As your newly created query implements the [Query](https://github.com/olivere/elastic/blob/master/query.go) interface, you can use it in [Scan.Query](https://github.com/olivere/elastic/blob/master/scan.go#L103).

Forget me if I'm on the wrong track and didn't understand your question correctly.

**Comment by jbrook** [comment]
Thank you. That's basically it. My user specified query is a boolean filter (must or should) containing a flat collection of basic filters. I'll write the custom filter wrapper you suggest and do the json juggling. Perhaps for each basic filter I can use the Source to simplify the parsing.

The user posts the above type of filter JSON to my web service and then I combine it with some security related filters and perform a scan.

**Comment by olivere** [comment]
Nice.

Just FYI: The situation regarding the `Scan` and `Scroll` service in Elastic is a bit of a mess. I will probably do some refactoring in the next major version of Elastic. But that won't happen before Elasticsearch 2.0. However, the `Filter` and `Query` interfaces probably won't change.
