### ISSUE TITLE
What are the different status codes?

### ISSUE THREAD

**Issue by darwinyip** [olivere/elastic#801]
https://github.com/olivere/elastic/blob/62adf5e0850464bd898a3a5577649e77d3ffaf62/index.go#L289

For Responses, what are the different status codes?

**Comment by olivere** [comment]
Please have a look at the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/index.html). In general, status codes 200-299 indicate success, 400-499 indicate a problem on your side and 500-599 indicate a problem on the server side.

I don't think the status codes are actually specified in the [REST API spec](https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/README.markdown).
