### ISSUE TITLE
No ElasticSearch Node Available

### ISSUE THREAD

**Issue by wjzhangcsu** [olivere/elastic#807]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v2 (for Elasticsearch 1.x)
[x] elastic.v3 (for Elasticsearch 2.x)
[x] elastic.v5 (for Elasticsearch 5.x)
[√] elastic.v6 (for Elasticsearch 6.x)
![1](https://user-images.githubusercontent.com/11661685/41634333-d6c1913e-7475-11e8-85fc-895669faad41.png)
![2](https://user-images.githubusercontent.com/11661685/41634339-dc255e9e-7475-11e8-8437-6ce7939656a4.png)

![3](https://user-images.githubusercontent.com/11661685/41634104-aee8a34c-7474-11e8-8fa6-5d002715ca3d.png)

 it work with "http://127.0.0.1:9200"!

**Comment by olivere** [comment]
Yes, that's expected. When you start with a default `NewClient`, a sniffing process starts. Sniffing finds all nodes in the cluster, and then does a round-robin between these nodes. It finds the nodes by calling the `/_nodes/http` endpoint, which you also called in the last screenshot. The last node in that screenshot tells Elastic that it needs to contact the node at `172.17.0.53:9200` which your code probably cannot route to, hence the error message.

You either need to tell the ES nodes to bound to an accessible IP/interface, or you need to disable sniffing (which `NewSimpleClient` does by default).

See [the wiki](https://github.com/olivere/elastic/wiki/Sniffing) for a longer discussion.

**Comment by wjzhangcsu** [comment]
@olivere ok! Thank you very much~
