### ISSUE TITLE
Is elastic v6 compatible with the elasticsearch 5.x

### ISSUE THREAD

**Issue by UCSBGauchos** [olivere/elastic#809]
I want to use elastic V6 to connect elasticsearch 5.x cluster, is it compatible?

client: elastic V6
cluster: 5.X

**Comment by olivere** [comment]
It's not tested and not guaranteed. Also, Elasticsearch 5.x and 6.x are not guaranteed to be compatible. You're strongly advised to use Elastic v6 with Elasticsearch 6.x and Elastic v5 with Elasticsearch 5.x.
