### ISSUE TITLE
When Multistage Build on Docker file " No Elastic Node Aviable "

### ISSUE THREAD

**Issue by Navapon** [olivere/elastic#810]
Using ElasticSearch Version 

[ ] elastic.v6 (for Elasticsearch 6.1.2)

## Expect move binary file to small images && Can run normally

I'm wanna use Docker multistage build images with Olivere / elastic 
but when I'm trying to move an executed  go binary file from builder stage has to error 
`
time=09-09-26068 09:09:00 level=error msg=no active connection found: no Elasticsearch node available host=045b4f45f939 layer=STORAGE model=NewElastic`

But !! if i don't move execute file from builder stage just leave it in to builder container and delete seconds build stage this error is not happen i'm currious what i'm missing 

Is this library require some lib. Below is my Dockerfile

```
FROM 3dsinteractive/go-librdkafka:v1 as builder
ADD ./api-consumer/ /go/

WORKDIR /go/src/pushandmotion.com/pushconsumer

RUN curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh && \
    dep ensure && \
    go build -o /app/pushconsumer -tags static_all

#This can run normally
ENTRYPOINT ["/app/pushconsumer"]

EXPOSE 8000

#Promblem is happen when copy binary file from builder
FROM alpine:3.6
    
WORKDIR /root/
COPY --from=builder /app/pushconsumer .
ENTRYPOINT ["/root/pushconsumer"]
```

## When move execute file to small image has promble " No Elastic Node Aviable "

I'm already open elasticsearch in browser and ping inside the container it's work fine

**Comment by olivere** [comment]
This doesn't have to do anything with Docker and/or multi-stage builds. It has to do something with the way sniffing works (see [details in the Wiki](https://github.com/olivere/elastic/wiki/Sniffing)). The node IPs are probably not accessible from your application.

**Comment by Navapon** [comment]
actually,  my app can access the node I'm trying by exec in the container and curl to elastic directly

<img width="545" alt="screen shot 2561-06-26 at 23 19 00" src="https://user-images.githubusercontent.com/23555986/41925756-b6411200-7997-11e8-98a5-65ad9e6bd316.png">

but when logging this error still happen 

<img width="714" alt="screen shot 2561-06-26 at 23 19 33" src="https://user-images.githubusercontent.com/23555986/41925778-c4c002f0-7997-11e8-856f-d42924757e16.png">

What i'm doing wrong cause it's work normal when i'm put build file on top image not second images

**Comment by olivere** [comment]
Any news here?

**Comment by Navapon** [comment]
Oh, my bad sorry for no response. After your suggestion, I'm disabled health checks its work fine

**Comment by olivere** [comment]
@Navapon I have been trying to reproduce this with https://github.com/olivere/elastic-with-docker (now updated to work with ES 6.x), but I couldn't. Maybe you can try it with that repo, and I'll re-open here if you can get the bug there. Thank you.
