### ISSUE TITLE
Question: What correct way to add index have type GeoPoint ? 

### ISSUE THREAD

**Issue by thuandoan274** [olivere/elastic#813]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ x] elastic.v6 (for Elasticsearch 6.x)

### Please describe the actual behavior
I want to add index to elastic search mapping like this
```
{
  "mappings": {
    "business": {
      "properties": {
        "location": {
          "type": "geo_point"
        }
      }
    }
  }
}
```
But I have failed when add index in go lang, when assign GeoPoint have a struct 
```type MerchantIndex struct {
	Location  *elastic.GeoPoint     `json:"location,omitempty"`
}
```

```
tmpIndex.Location = elastic.GeoPointFromLatLon(lat, lon)
```
But when add I got a message 

```
elastic: Error 400 (Bad Request): failed to parse [type=mapper_parsing_exception]
```

**Comment by olivere** [comment]
Hmm... in the test mapping, it is [defined as a `geo_point`](https://github.com/olivere/elastic/blob/release-branch.v6/setup_test.go#L82-L84) but [marked as a `string`](https://github.com/olivere/elastic/blob/release-branch.v6/setup_test.go#L209). You can also [define it as a `*GeoPoint`](https://github.com/olivere/elastic/blob/ffff59e3260c9f7d14ff60707c19ae0ccfe03b7a/suggester_context_geo.go#L86), but then [you need to run `.Source()`](https://github.com/olivere/elastic/blob/ffff59e3260c9f7d14ff60707c19ae0ccfe03b7a/suggester_context_geo.go#L117) to properly serialize into JSON.

But I agree that's not very obvious and marked it as issue #813.
