### ISSUE TITLE
startupHealthcheck not cancellable with context

### ISSUE THREAD

**Issue by bendikro** [olivere/elastic#815]
It would be nice to be able to pass a context to NewClient to be used for the [startupHealthcheck](https://github.com/olivere/elastic/blob/master/client.go#L817)
Currently, the only way to be able to abort within a reasonable time is by setting `healthcheckTimeoutStartup` to a low value?

**Comment by olivere** [comment]
Hmm... I have to look into this, but I think it'd not be a good idea to pass a specific (cancelable) context just for health checks. Maybe we could have a context for canceling `NewClient` early. I suppose that's your use case?

Notice that I cannot change `NewClient` in minor versions, so the only chance would be to wait for 7.x or add a `NewClientWithContext(...)` method.

**Comment by lihuiat** [comment]
- 

- [ ] 
``
1. [](url

> `[)]([url]([url]([url]([url]([url]([url]([url]([url]([url]([url]([url]([url]([url]([url]([url]([url]([url](

- [ ] 

- 1. url

))))))))))))))))))`

**Comment by bendikro** [comment]
@olivere Yes, the use case is to be able to abort early on when receiving a SIGINT signal.
