### ISSUE TITLE
Question: How to write query elastic search ?

### ISSUE THREAD

**Issue by thuandoan274** [olivere/elastic#816]
I have a index review like this
```
{
        "_index": "zody_review",
        "_type": "review",
        "_id": "5b3c6c9e68cf860e1af5f7fd",
        "_score": null,
        "_source": {
          "user": "571899623dc63af34d67a662",
          "merchant": "56f8f80119a4c1ae791cf7bf",
          "point": 3,
          "score": 2,
          "createdAt": "2018-07-04T13:43:42.331+07:00",
          "location": {
            "lat": 16.07054040054832,
            "lon": 108.22062939405441
          },
          "feedback": "Phuc vu khong tot lam "
        }
      },
```
How can I query to get list review, but limit get 5 reviews for each group by field merchant ? 
Thank you!

**Comment by olivere** [comment]
Maybe you could use the [TopHits aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-top-hits-aggregation.html)? Best to ask is in the [Elasticsearch forum](https://discuss.elastic.co/). Elastic is just a Go driver for Elasticsearch.
