### ISSUE TITLE
Refresh when using BulkProcessor

### ISSUE THREAD

**Issue by chuntley** [olivere/elastic#820]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[x] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
Need the ability to wait_for a refresh when using a BulkProcessor

It looks like in `bulk_processor.go`, line 505, you can brute-force this by changing it to:

```res, err = w.service.Refresh("wait_for").Do(ctx)```

This seems to get the desired behavior, however after digging into the code I'm not sure if this behavior is already supported in some way? My current initialization code is:

```
bulker, err := client.
   BulkProcessor().
   BulkSize(5000).
   Workers(10).
   Do(context.Background())
```

Thank you!

**Comment by olivere** [comment]
Adding a Refresh in line 505 would have a severe impact on the performance of the bulk processor.

You can set a flush interval, which is not exactly what you want (it re-opens the index reader(s) AND commits changes to disk), but that's what bulk processor has right now. It would of course be possible to add a `BulkProcessor.Refresh` method to manually refresh. But I think that would defeat the purpose of bulk processor.

If you want fine grained control over your bulk indexing, do not use bulk processor but implement your own indexer with Bulk API. It's [not that hard](https://github.com/olivere/elastic/blob/release-branch.v6/recipes/bulk_insert/bulk_insert.go).

**Comment by chuntley** [comment]
I'm not necessarily interested in speed but instead more interested in a guarantee that the data added is available to query. I'll work on my own Bulk API implementation, thank you for the pointers!
