### ISSUE TITLE
Massive updates

### ISSUE THREAD

**Issue by ricardozd** [olivere/elastic#821]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[x] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v6 (for Elasticsearch 6.x)

I can update, registers via Id. For example, I have this json:

```
{
  "_index": "test",
  "_type": "test",
  "_id": "59748f1c8a5da57f1578b4fb",
  "_version": 1,
  "_score": 2,
  "_source": {
    "id": "59748f1c8a5da57f1578b4fb",
    "geo": [
      -0.784572,
      37.814063
    ],
    "lat": 0,
    "lng": 0,
    "name": "Test name",
    "photo": "https://test.com",
    "rating": 10,
    "restaurant_id": "596dbabfc0001db465480640",
    "restaurant_name": "Restaurant name",
    "description": "test description",
    "time": "2017-07-23T13:57:16.833+02:00",
    "user_id": "mtJZngDOy6Qj22Qv9MEf1MhSLVb2",
    "user_name": "Test",
    "user_nick": "Test nick",
    "users_id_likes": null,
    "counter_comments": 0
  },
  "fields": {
    "time": [
      1500811036833
    ]
  }
}

```
I update perfectly the json via Id:

```
func UpdateById(client *elastic.Client, id string, test interface{}) error {
	ctx := context.Background()
	update, err := client.Update().Index("test").Type("test").Id(id).Doc(test).Do(ctx)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("updated id: ", update.Id)
	return nil
}
```

How can update all registers of my type via user_id?

**Comment by olivere** [comment]
Are you looking for something like [Update by Query API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update-by-query.html)?

**Comment by olivere** [comment]
Let me know if this issue is still unresolved and I'll re-open.

**Comment by ricardozd** [comment]
Yes , thanks, the solution:

POST {index}/{type}/_update_by_query
{
  "script": {
    "inline": "ctx._source.user_name = 'test'",
    "inline": "ctx._source.user_nick = 'test test'"
  },
  "query": {
    "match": {
      "user_id": "mtJZngDOy6Qj22Qv9MEf1MhSLVb2"
    }
  }
}

**Comment by ricardozd** [comment]
Thanks for your help, the last question... I'm a noob in golang :)

I try with this code but I don't update anything

```
out_name, err := client.UpdateByQuery().Index("index").Type("type").Script(elastic.NewScriptInline("ctx._source.user_name=" + user.Name)).Query(elastic.NewTermQuery("user_id", id)).Do(ctx)
	if err != nil {
		log.Println(err)
	}
	fmt.Println("update all name: ", out_name.Updated)
```

Can you help me?

Thanks

**Comment by ricardozd** [comment]
The solution:

```
out_name, err := client.UpdateByQuery().Index("gofoodie").Type("feed").Query(query_two).Script(elastic.NewScriptInline("ctx._source.user_name = '" + user.Name + "'")).Do(ctx)
	if err != nil {
		log.Println(err)
	}
```

Thanks for all :)
