### ISSUE TITLE
Document Get() returns Error with 404 status and nil *GetResult

### ISSUE THREAD

**Issue by andrew-leung** [olivere/elastic#822]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[X] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
I was expecting a GetService Get() request that does not find a Document to follow similar semantics outlined for the Elastic Java client (https://www.elastic.co/guide/en/elasticsearch/client/java-rest/6.0/java-rest-high-document-get.html#java-rest-high-document-get-response), specifically "Note that although the returned response has 404 status code, a valid GetResponse is returned rather than an exception thrown. Such response does not hold any source document and its isExists method returns false.".

### Please describe the actual behavior
A Get() on a Document ID that does not exist returns an error with status 404 and a nil *GetResult, rather than setting GetResult{Found: false}.

### Any steps to reproduce the behavior?
I'm mostly curious if this is by design or an unintended divergence from what Elastic's Java REST client does. If this is the intended behavior, is the suggested route to us IsNotFound(), or directly use PerformRequestWithOptions to ignore 404 errors or another approach?

**Comment by olivere** [comment]
Hmm... we had that in #754 a while ago. Seems like there's a difference between the low-level Java client and the high-level Java client. Maybe something changed on the server-side between then and now?

I'm afraid I cannot change the behavior between minor versions as that would be a breaking change. So the only chance we have is to change the behavior with 7.x.

**Comment by andrew-leung** [comment]
OK, thanks for letting me know. It might be use to update to example in the docs as it seems to imply the Found field used:

From the example in the docs:
`// Get tweet with specified ID
get1, err := client.Get().
    Index("twitter").
    Type("tweet").
    Id("1").
    Do(context.Background())
if err != nil {
    // Handle error
    panic(err)
}
if get1.Found {
    fmt.Printf("Got document %s in version %d from index %s, type %s\n", get1.Id, get1.Version, get1.Index, get1.Type)
}`

**Comment by olivere** [comment]
@andrew-leung Thanks. I've [update the example code](https://github.com/olivere/elastic/commit/5c21102675543f6a91c9dc3d55412fa1eec5817b).
