### ISSUE TITLE
Help with Client mocking / setupTestClientAndCreateIndex example

### ISSUE THREAD

**Issue by michaelByrne** [olivere/elastic#826]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[X ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
Following the example in setup_tests, I expect to be able to create a mock client with a simple index. 

### Please describe the actual behavior
I return an error:

`panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1326ab6]
`

### Any steps to reproduce the behavior?
Create and a reduced version of setupTestClientAndCreateIndex as follows: 

`const (
	testIndexName  = "elastic-test"
	testIndexName2 = "elastic-test2"
	testIndexName3 = "elastic-test3"
	testMapping    = `
{
	"settings":{
		"number_of_shards":1,
		"number_of_replicas":0
	},
	"mappings":{
		"doc":{
			"properties":{
				"user":{
					"type":"keyword"
				},
				"message":{
					"type":"text",
					"store": true,
					"fielddata": true
				},
				"tags":{
					"type":"keyword"
				},
				"location":{
					"type":"geo_point"
				},
				"suggest_field":{
					"type":"completion",
					"contexts":[
						{
							"name":"user_name",
							"type":"category"
						}
					]
				}
			}
		}
	}
}
`)

type logger interface {
	Error(args ...interface{})
	Errorf(format string, args ...interface{})
	Fatal(args ...interface{})
	Fatalf(format string, args ...interface{})
	Fail()
	FailNow()
	Log(args ...interface{})
	Logf(format string, args ...interface{})
}

func setupTestClient(options ...elastic.ClientOptionFunc) (client *elastic.Client) {
	//var err error

	client, _ = elastic.NewClient(options...)
	//if err != nil {
	//	t.Fatal(err)
	//}

	//client.DeleteIndex(testIndexName).Do(context.TODO())

	return client
}

func setupTestClientAndCreateIndex(t logger, options ...elastic.ClientOptionFunc) *elastic.Client {
	client := setupTestClient(options...)

	cl, _ := client.CreateIndex(testIndexName).Body(testMapping).Do(context.TODO())
	fmt.Println(cl)
	//if err != nil {
	//	t.Fatal(err)
	//}
	//if createIndex == nil {
	//	t.Errorf("expected result to be != nil; got: %v", createIndex)
	//}

	return client
}

func TestFind(t *testing.T) {
	cl := setupTestClientAndCreateIndex(t)
	fmt.Println(cl)
}`

Execute the test

**Comment by olivere** [comment]
There were some issues already regarding testing. I personally think that if you need to mock `*elastic.Client`, you're actually testing on the wrong layer of abstraction. See https://github.com/olivere/elastic/issues/795#issuecomment-398376126 for a discussion and some hints.

**Comment by michaelByrne** [comment]
Fair enough. Thank you
