### ISSUE TITLE
health check timeout

### ISSUE THREAD

**Issue by LesioS** [olivere/elastic#829]
[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[X] elastic.v6 (for Elasticsearch 6.x)

```
func (c *Cluster) Send2(sess SessionData) {
	httpClient := &http.Client{
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{
				InsecureSkipVerify: true,
			},
		},
		Timeout: time.Second * 30,
	}
	client, err := elastic.NewClient(elastic.SetHttpClient(httpClient), elastic.SetURL(c.url), elastic.SetScheme("https"), elastic.SetSniff(false))
	if err != nil {
		return
	}

	bulkReq := client.Bulk()
	req := elastic.NewBulkIndexRequest().Index(sess.SessionIndexName).Type("sess").Id(sess.SessionID).Doc(sess.SessionDoc)
	bulkReq.Add(req)

	bulkResp, err := bulkReq.Do(context.Background())
	if err != nil {
		return
	}
	if bulkResp != nil {
		return
	}
}
```

### Please describe the expected behavior
Loading doc into ES

### Please describe the actual behavior
After 10 secs (not 30) I receive error: "health check timeout; no ElasticSearch node available"

### Any steps to reproduce the behavior?
ES node is configured as demo (demo certs) with user/password.

Any tips why I cannot locate ES installation?

**Comment by olivere** [comment]
Please read the wiki about [health checks](https://github.com/olivere/elastic/wiki/Healthcheck) and [sniffing](https://github.com/olivere/elastic/wiki/Sniffing).

Please see https://github.com/olivere/elastic-with-docker repository to see how to configure Docker to make it work.

If you don't need health checks, disable them.
