### ISSUE TITLE
SearchResult does not return scores

### ISSUE THREAD

**Issue by cakirmuha** [olivere/elastic#832]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[x] elastic.v6 (for Elasticsearch 6.x)(6.2.4)

### Please describe the expected behavior
In kibana, this query sorts the results by their scores and shows scores

```
GET /places/doc/_search
{
  "query": {
    "bool": {
      "must": [
            {
              "simple_query_string": {
                "fields" : [ "name^3", "tags.name^2", "region_name"],
                "query" : "st*"
              }
           },
        {
          "term": {"region": "r1"}}
      ]
    }
  }
}
```

### Please describe the actual behavior
In golang, 

- the hits returns scores as 0 and are not sorted like Kibana
   bq := elastic.NewBoolQuery().Must().Filter(lq)
- the hits returns scores as 1 and are not sorted like Kibana
   bq := elastic.NewBoolQuery().Must(elastic.NewMatchAllQuery()).Filter(lq)

```
lq := elastic.NewRawStringQuery(fmt.Sprintf(`{"bool": {
      "must": [
            {
              "simple_query_string": {
                "fields" : [ "name^3", "tags.name^2", "region_name"],
                "query" : "st*"
              }
           },
        {
          "term": {"region": "r1"}}
      ]
    }}`))
bq := elastic.NewBoolQuery().Must().Filter(lq)
ss := ess.Search("places").Type("doc").Query(bq)
rr, err := ss.FetchSource(true).TrackScores(true).Do(ess.ctx)

for i, item := range rr.Each(reflect.TypeOf(res)) {
	fmt.Println(*rr.Hits.Hits[i].Score)
        ...
}
```

How can I achieve this?
Thanks.

**Comment by olivere** [comment]
From the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/_executing_filters.html):

> The bool query that we introduced in the previous section also supports filter clauses which allow to use a query to restrict the documents that will be matched by other clauses, *without changing how scores are computed*.

Filters don't compute scores, only queries do. In other words, the Go code uses your query as a filter whereas your REST query doesn't. Something like this should do the job (not tested):

```
...
sq := elastic. NewSimpleQueryStringQuery("st*").
  FieldWithBoost("name", 3.0).
  FieldWithBoost("tags.name", 2.0).
  FieldWithBoost("region_name", 1.0)
tq := elastic.NewTermQuery("region", "r1")
bq := elastic.NewBoolQuery().Must(lq).Must(tq)
res, err := client.Search("places").Type("doc").Query(bq).Do(context.Background())
...
```
