### ISSUE TITLE
Using '_source' in a script with SearchService 

### ISSUE THREAD

**Issue by winhung** [olivere/elastic#833]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[*] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
Search runs with the script

### Please describe the actual behavior
I am trying to run a simple script that needs to access '_source' with SearchService. However, a null_pointer_exception is thrown at 'ctx.'.
Here's the code snippet,
```
modScriptText := "int count = ctx._source.Versions?.size();""
modScript := elastic.NewScript(modScriptText)
modScriptQuery := elastic.NewScriptQuery(modScript)

boolQuery := elastic.NewBoolQuery()
boolQuery.Must(modScriptQuery)

searchResult, err := esClient.
				Search().
				FetchSource(true).
				Index("test_index").
				Query(boolQuery).
				Size(9999).
				Do(context.Background())
if err != nil {
				t.Fatal("Failed to get a response from ES client: ", err)
			}
```

JSON (Pretty),
```
{
   "error":{
      "root_cause":[
         {
            "type":"script_exception",
            "reason":"runtime error",
            "script_stack":[
               "count = ctx._source.Versions?.size();",
               "           ^---- HERE"
            ],
            "script":"int count = ctx._source.Versions?.size();",
            "lang":"painless"
         }
      ],
      "type":"search_phase_execution_exception",
      "reason":"all shards failed",
      "phase":"query",
      "grouped":true,
      "failed_shards":[
         {
            "shard":0,
            "index":"test_index",
            "node":"G9e3ushES4e3mnGOCjWm6A",
            "reason":{
               "type":"script_exception",
               "reason":"runtime error",
               "script_stack":[
                  "count = ctx._source.Versions?.size();",
                  "           ^---- HERE"
               ],
               "script":"int count = ctx._source.Versions?.size();",
               "lang":"painless",
               "caused_by":{
                  "type":"null_pointer_exception",
                  "reason":null
               }
            }
         }
      ]
   },
   "status":500
}
```

Raw JSON,
`
{"error":{"root_cause":[{"type":"script_exception","reason":"runtime error","script_stack":["count = ctx._source.Versions?.size();","           ^---- HERE"],"script":"int count = ctx._source.Versions?.size();","lang":"painless"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"test_index","node":"G9e3ushES4e3mnGOCjWm6A","reason":{"type":"script_exception","reason":"runtime error","script_stack":["count = ctx._source.Versions?.size();","           ^---- HERE"],"script":"int count = ctx._source.Versions?.size();","lang":"painless","caused_by":{"type":"null_pointer_exception","reason":null}}}]},"status":500}
`

### Any steps to reproduce the behavior?
1) Create a script
2) Run it with a SearchService

**Comment by olivere** [comment]
Please use a valid script according to the [Painless scripting docs](https://www.elastic.co/guide/en/elasticsearch/painless/6.3/painless-examples.html).

I've [added a test](https://github.com/olivere/elastic/blob/8bd59ebad7778b29e375c2f88088658619a9bb91/search_test.go#L1322-L1353) for illustration purposes.

**Comment by winhung** [comment]
Apologies for the late reply.

Just to close this question properly, i have found the problem.
'ctx._source' does not work with search requests.
To access it, my script had to use 'params._source' instead.

References:
https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-scripting-fields.html#_update_scripts
This is where is found out that ctx._source only works with update, update-by-query, or reindex API.

https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-scripting-fields.html#modules-scripting-stored
From this same page, i see an example of using 'params._source'.

**Comment by winhung** [comment]
Yes, when it comes to this i will ask them instead.
Thank you for creating the test though.
