### ISSUE TITLE
CatAliases returning index_not_found exception

### ISSUE THREAD

**Issue by cludden** [olivere/elastic#841]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[x] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
I would expect `elastic.CatAliases().Alias("alias1", "alias2")` to return a (potentially empty) filtered response of alias information

### Please describe the actual behavior
Instead, I receive the following error. I believe the url on [this line](https://github.com/olivere/elastic/blob/release-branch.v6/cat_aliases.go#L92) should be `/_cat/aliases/{name}"` instead of `/_cat/indices/{name}"`, as per the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/cat-alias.html)
```
elastic: Error 404 (Not Found): no such index [type=index_not_found_exception]
```

### Any steps to reproduce the behavior?
Perform a `CatAliases` request with one or more `Alias` filters

**Comment by olivere** [comment]
Yes, you're correct. Thanks for your findings. I will fix the typo and add a test to prevent this from happening again in the future.
