### ISSUE TITLE
How to add custom fields for a document in elasticsearch using GO

### ISSUE THREAD

**Issue by vijaygo** [olivere/elastic#843]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
How do we add fields and there values to a particular document in elasticsearch using the docid and indexname.
Example: 
"hits" : [
      {
        "_index" : "idx001",
        "_type" : "sdoc",
        "_id" : "https://custom.pdf",
        "_score" : 1.0,
        "_source" : {
          "col" : "1",
          "colname" : "sharepoint",
          "language" : "en",
          "uid" : "f07d3ad282fb5303156851317bc36c29",
          "uid_old" : "https://custom.pdf",
          "keywords" : ""
}
above is part of elasticsearch result.
And after adding a custom filed and its value it becomes,
"hits" : [
      {
        "_index" : "idx001",
        "_type" : "sdoc",
        "_id" : "https://custom.pdf",
        "_score" : 1.0,
        "_source" : {
          "col" : "1",
          "colname" : "sharepoint",
          "language" : "en",
          "uid" : "f07d3ad282fb5303156851317bc36c29",
          "uid_old" : "https://custom.pdf",
          "keywords" : "",
           **"offices"  : "pub"**
}
Here in above example offices is the field name and pub is the field value

Help appreciated.

**Comment by olivere** [comment]
I'm not sure but it seems you're looking for the [Update API](https://www.elastic.co/guide/en/elasticsearch/reference/6.3/docs-update.html).

[Here](https://github.com/olivere/elastic/blob/release-branch.v6/update_test.go) and [here](https://github.com/olivere/elastic/blob/release-branch.v6/update_integration_test.go) is some example code for how to work with Update in Elastic.
