### ISSUE TITLE
missing quote_field_suffix in simple_query_string v5

### ISSUE THREAD

**Issue by texvex** [olivere/elastic#847]
Hi, 

### Which version of Elastic are you using?

[x ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
main() {
	ID := "1234"
	q := elastic.NewSimpleQueryStringQuery(`"` + ID + `"`)
	q.Field("items.id")
	q.Field("discounts.id")
	q.QuoteFieldSuffix(".exact")
	//...
}

### Please describe the actual behavior
SimpleQueryStringQuery doesn't implement QuoteFieldSuffix()

### Any steps to reproduce the behavior?
Like this issue (but for elastic 6) #750
https://www.elastic.co/guide/en/elasticsearch/reference/5.2/query-dsl-simple-query-string-query.html

thanks,

**Comment by olivere** [comment]
It's there in [v6](https://github.com/olivere/elastic/blob/release-branch.v6/search_queries_simple_query_string.go#L70-L75) but missing in v5 unfortunately. Feel free to add a PR. Otherwise I'll backport it to v5 in the next release.
