### ISSUE TITLE
Function score weight not supported parsing exception

### ISSUE THREAD

**Issue by andywhittle** [olivere/elastic#85]
As per the discussion in https://github.com/olivere/elastic/issues/74#issuecomment-105446354, the function weighting is still causing an issue. I am getting the following exception raised when adding the weight onto a score function, as per the test example (https://github.com/olivere/elastic/blob/master/search_queries_fsq_test.go#L72)

            QueryParsingException[[.....] field_value_factor query does not support [weight]

As far as I can tell this needs adding to the FunctionScoreQuery similar to the original PR implementation.

Thanks

**Comment by olivere** [comment]
Hi, and sorry for the delay.

You are correct. [FieldValueFactorFunction](https://github.com/elastic/elasticsearch/blob/1.6/src/main/java/org/elasticsearch/index/query/functionscore/fieldvaluefactor/FieldValueFactorFunctionBuilder.java#L33) does not have a `weight` property. Instead, I need to add the `missing` property (as described [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#_field_value_factor)).

However, I still don't see how your original PR is compatible with the way the Java side works. In [#74 (comment)](https://github.com/olivere/elastic/issues/74#issuecomment-105446354) I said:

> However, when comparing the Java code with your implementation, I see that in Java the weights
> are only applied to the score functions whereas in your PR you add them to the FunctionScoreQuery.
> Do we agree that it is the correct thing to add them to the score functions?

Can you send me the valid, JSON-encoded query you are trying to send to Elasticsearch and which you cannot create with Elastic?

**Comment by olivere** [comment]
Actually, the situation is more complex. Most (all?) score functions (e.g. [`RandomScoreFunctionBuilder`](https://github.com/elastic/elasticsearch/blob/1.6/src/main/java/org/elasticsearch/index/query/functionscore/random/RandomScoreFunctionBuilder.java)) in Java derive from [`ScoreFunctionBuilder`](https://github.com/elastic/elasticsearch/blob/1.6/src/main/java/org/elasticsearch/index/query/functionscore/ScoreFunctionBuilder.java) which comes with a `weight` field. However, when serializing into in [`doXContent`](https://github.com/elastic/elasticsearch/blob/1.6/src/main/java/org/elasticsearch/index/query/functionscore/random/RandomScoreFunctionBuilder.java#L71), the `weight` property is not used.

I'm looking into this...

**Comment by olivere** [comment]
Actually, scrap that. [`ScoreFunctionBuilder.toXContent`](https://github.com/elastic/elasticsearch/blob/1.6/src/main/java/org/elasticsearch/index/query/functionscore/ScoreFunctionBuilder.java#L45) is what's called from the query builders. It adds the `weight` (if specified), then wraps the derived query with `doXContent`.

So I guess the generated JSON in Elastic is wrong, hence your syntax error.

I'll check that now.

**Comment by andywhittle** [comment]
Hi @olivere,

Thanks for looking into this, the original PR was raised not by myself but by @autochthe, sorry for the confusion, I just happened to be working on this at present.

I just quickly forked it to get a working example, if this is any use to you then this is my commit that seems happier for my particular use case (https://github.com/andywhittle/elastic/commit/d88ab0e8377df346b144a75d52d51104a1e3aa53)

Again I appreciate you picking this up so fast.

**Comment by olivere** [comment]
Thanks for your proposal. I refrain from specifying a struct for `Weight` and handling score functions differently whether they have a weight or not. In the Java client, they all derive from `ScoreFunctionBuilder`, so they all have a weight.

I have a different solution which isn't remotely as nice as your code, but I'm looking for correctness first. Can you please try the [fsq-weight](https://github.com/olivere/elastic/tree/fsq-weight) branch and see if this fixes your issue?

**Comment by andywhittle** [comment]
Yep ok cool that makes sense, that branch is looking correct for me. Thanks

**Comment by olivere** [comment]
Okay. Now some cleanup, then I'll merge into master later in the evening. Cheers.

**Comment by andywhittle** [comment]
Awesome, thanks again for all your efforts with this repo.

**Comment by olivere** [comment]
Okay, I did some cleanup, more documentation, and aligned with function score queries with the 1.6 version of Elasticsearch. Do you mind to review the changes (and check with your code)? Travis is still building as I write...

**Comment by andywhittle** [comment]
Changes look good :+1: All my tests are passing and it appears to be working correctly for me.
