### ISSUE TITLE
ScrollSearch seems to work differently on windows

### ISSUE THREAD

**Issue by SvenDowideit** [olivere/elastic#850]
I'm doing a variation on https://github.com/olivere/elastic/wiki/ScrollParallel to `tail` my elastic based log store, and the code on Linux and OSX appears to get the `EOF`. However, on Windows, the `scroll.Do()` seems to not return an EOF, but instead returns the same results over and over.

I've only just started playing with el, and your library, so haven't dug very deeply - I'd be happy to just hear that someone else has it working fine :)

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[x] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior

That it works identically on Windows :)

### Please describe the actual behavior

Windows never exits the for loop

**Comment by olivere** [comment]
That shouldn't happen. Let me see if I find a Windows VM somewhere...

**Comment by olivere** [comment]
Here's [another example](https://github.com/olivere/elastic/blob/release-branch.v6/recipes/sliced_scroll/sliced_scroll.go) which you might check. Does that work correctly?

**Comment by SvenDowideit** [comment]
sorry, I'll get back to this soon - `$work` needs something else first :)

**Comment by olivere** [comment]
Any news here?

**Comment by olivere** [comment]
Closing for age. Let me know any details and I'll re-open.
