### ISSUE TITLE
are "script_fields" supported?

### ISSUE THREAD

**Issue by mvpmvh** [olivere/elastic#851]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ x ] elastic.v6 (for Elasticsearch 6.x)

Was looking to add some [script fields](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-script-fields.html) functionality to my project, but it seems to not be possible?

**Comment by olivere** [comment]
Heja! I wasn't quite sure, but yes, script fields are supported. See [here](https://github.com/olivere/elastic/blob/release-branch.v6/search_source_test.go#L121-L139) for an example.

**Comment by olivere** [comment]
[Here's an example](https://github.com/olivere/elastic/blob/release-branch.v6/search_test.go#L762-L774) of using `SearchSource`. Please lookup the tests. The suite is quite big, and it covers a lot of usage examples.
