### ISSUE TITLE
Logging source before or after send it.

### ISSUE THREAD

**Issue by dennypenta** [olivere/elastic#852]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[x] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior

Logging source after build request if I want.
It makes sure that I built request correctly.

### Please describe the actual behavior

.source field of services is private and they do not have any methods to get this property or to log it.

### Any steps to reproduce the behavior?

Implement request and send it.

### Any idea to implement it

- Make option for services or service builders turn on logging source.
- Implement custom http.Clint with custom transport and logging it via RoundTripper interface.

**Comment by olivere** [comment]
You can enable [trace logging](https://github.com/olivere/elastic/wiki/Logging). If you want to use your own logging mechanism and have direct access to the request and response, you can [implement your own transport](https://github.com/olivere/elastic/wiki/HttpTransport).
