### ISSUE TITLE
Get from gb does not work

### ISSUE THREAD

**Issue by AkulovNV** [olivere/elastic#853]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[x] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior

gb collector is not working now

```
/go # gb vendor fetch gopkg.in/olivere/elastic.v6
fetching recursive dependency github.com/google/uuid
fetching recursive dependency github.com/mailru/easyjson
fetching recursive dependency github.com/olivere/elastic
fetching recursive dependency github.com/olivere/elastic/v6
FATAL: command "fetch" failed: lstat /tmp/gb-vendor-010316371/v6: no such file or directory
FATAL: command "vendor" failed: exit status 1
```
However, 

```go get gopkg.in/olivere/elastic.v6```

works without errors

### Please describe the actual behavior

Install gb and elastic commands
 
```
go get github.com/constabulary/gb/... && \
gb vendor fetch gopkg.in/olivere/elastic.v6
```

### Any steps to reproduce the behavior?

I use docker image golang:alpine

**Comment by olivere** [comment]
Can you please use `github.com/olivere/elastic` as [described here](https://github.com/olivere/elastic/blob/release-branch.v6/README.md#releases).

I'm not sure how to get `gb` to use the `release-branch.v6` (which is set as the default branch for `github.com/olivere/elastic` as of now). Dependency managers like `dep` work fine with that.

**Comment by olivere** [comment]
Seems [you can tag a specific release](https://godoc.org/github.com/constabulary/gb/cmd/gb-vendor) with something like:

```
$ gb vendor fetch -tag v6.2.7 github.com/olivere/elastic
```
