### ISSUE TITLE
Code can't create it's own body, validation will prevent this case (Snapshot / Create Repository)

### ISSUE THREAD

**Issue by philcaetano** [olivere/elastic#854]
https://github.com/olivere/elastic/blob/d025b692e2782519d6f68ab4989a37985f848c52/snapshot_create_repository.go#L138

	body := map[string]interface{}{
		"type": s.typ,
	}

I can't see any scenario where the code will build the body if the (Json is Nil or Body is empty) since on the execution of Do the validation prevents the person from having Json Nil or Body empty :

func (s *SnapshotCreateRepositoryService) Validate() error { ..

I think you want to check if settings have been assigned to ignore the check of nil and empty?

**Comment by olivere** [comment]
Thanks for reporting. a268a4f191b45eb3e8f28927ea604d06b480ef42 should fix that.

**Comment by olivere** [comment]
Backported to v5 in 3d8acdf3c2f1f8e7cd7a1799a60b7b2ba8c4c06e.
