### ISSUE TITLE
 Elastic matching special characters

### ISSUE THREAD

**Issue by liuxin95** [olivere/elastic#856]
Hi all
I'm using elastic to search data. But the value of one of my fields contains special characters, for example:
`"hostname=alery0-0"`
This key-value pair contains a special character `-`, and i am new a match query,  But it can't match special characters`-`
I am querying Google, some people say that special characters can be escaped. But I didn't find the escaped function in elastic-go api library.

Is there any good solution to this problem?

Any help would be appreciated.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[*] elastic.v6 (for Elasticsearch 6.x)

**Comment by olivere** [comment]
You didn't say where you send this parameter: In a query string, in a JSON body etc. So I don't know yet if this might be a bug or something you need to do on your side.

If you want to encode query parameters, you can use e.g. [`url.QueryEscape`](`https://golang.org/pkg/net/url/#QueryEscape`. The JSON body should be automatically encoded by the Go standard library. It might as well be something on the server side, e.g. ES doesn't expect you to send these characters.

Without further details, I'm afraid I cannot do anything.
