### ISSUE TITLE
elastic: Error 404 (Not Found)

### ISSUE THREAD

**Issue by vk18vk** [olivere/elastic#857]
### Which version of Elastic are you using?

[ ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
Document should get updated with sent fieldname and value 

### Please describe the actual behavior
getting 404 error even though the document exists with that ID

### Any steps to reproduce the behavior?

`update, err := client.Update().Index(indexname).Type("sdoc").Id(p.Docid).Doc(struct {
								Offices  []string `json:"Offices"`
								FileType string   `json:"FileType"`
							}{
								Offices:  p.Offices,
								FileType: extension,
							}).DetectNoop(true).Do(ctx)
							if err != nil {
								fmt.Println(" error", err.Error())
								//panic(err)
							} else {
								fmt.Println("New version of result is", update.Id, update.Version, update.Result)
}`
please update on this

**Comment by olivere** [comment]
There are [quite a few integration tests](https://github.com/olivere/elastic/blob/release-branch.v6/update_integration_test.go) regarding Update API. All of these tests run with every commit. Please double check your code, or fully working failing test case.
