### ISSUE TITLE
QueryStringQuery returns empty array always

### ISSUE THREAD

**Issue by Avik1993** [olivere/elastic#858]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.
QueryStringQuery not working as expected.
I am trying to search for keyword throughout all fields of an ES index, while i hit ES using curl I get expected output but from Elastic client I always get a blank array.

### Which version of Elastic are you using?
[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
It should return documents if any field contains the keyword

### Please describe the actual behavior
It returns blank array

### Any steps to reproduce the behavior?
Code:
```
	q := elastic.NewQueryStringQuery(queryStr)  //I create string from entered keyword. eg: json is converted to *json*
	q = q.DefaultField("*")
	searchResult, err := elasticClient.Search().
		Index(<index>).
		Query(q).
		Do(ctx)

```

**Comment by olivere** [comment]
What is the `curl` command you mentioned?

**Comment by Avik1993** [comment]
I used this:-
curl -X GET "<host>:<port>/_search?pretty=true" -H 'Content-Type: application/json' -d'
{
    "query": {
        "query_string" : {
            "default_field" : "*",
            "query" : "*JSON*"
        }
    }
}

**Comment by olivere** [comment]
Did a quick test here, working fine. Can you enable tracing and/or return the error?

**Comment by Avik1993** [comment]
Can you please share your test case and maybe ES index details too maybe?  I will try and check it at my end till then

**Comment by olivere** [comment]
I added [this test](https://github.com/olivere/elastic/blob/release-branch.v6/search_queries_query_string_test.go#L49-L72).

**Comment by Avik1993** [comment]
All seem fine at my end too. Could it be because of some configs or mapping i missed out at ES end? i have added fieldData=true option to all the text fields i would require a search on already

**Comment by olivere** [comment]
Probably. Mappings must be correct at all times. We use dynamic templates now through all our projects, but that comes with different problems.

Have a nice weekend.

**Comment by Avik1993** [comment]
Hi @olivere.. I tried using mappings similar to those present in [this test case](https://github.com/olivere/elastic/blob/release-branch.v6/search_queries_query_string_test.go#L49-L72) but with no luck.
Any way you can help me debug the same?

Pieces of code:
Mapping for new index:-
`
{
	"settings":{
		"number_of_shards":1,
		"number_of_replicas":0
	},
	"mappings":{
		"doc":{
			"properties":{
				"name":{
					"type":"keyword"
				},
				"description":{
					"type":"text",
					"store":true,
					"fielddata":true
				},
				"tags":{
					"type":"keyword"
				}
			}
		}
	}
}`

Entity Creation:
`

entityIndexSmall, err := client.CreateIndex("entitysmall").Body(newEntityMappingSmall).Do(context.TODO())
	if err != nil {
		log.Error(err)
	}
	if entityIndexSmall == nil {
		log.Error("expected result to be != nil")
	}
`

Document Insertion:
`	

    ent1 := entity{Name: "Test", Description: "Test Description"}

	ent2 := entity{Name: "ShouldNot", Description: "Should not come"}

	_, err := client.Index().Index("testEntity").Type("doc").Id("1").BodyJson(&ent1).Do(context.TODO())
	if err != nil {
		log.Error(err)
	}
	_, err = client.Index().Index("testEntity").Type("doc").Id("2").BodyJson(&ent2).Do(context.TODO())
	if err != nil {
		log.Error(err)
	}
`


QueryString Query:
`	q := elastic.NewQueryStringQuery("Test")
	searchResult, err := client.Search().
		Index("testEntity").
		Query(q).
		Pretty(true).
		Do(ctx))
`

**Comment by olivere** [comment]
@Avik1993 Again: What's the error returned by Elasticsearch? You can see so by enabling the trace log or e.g. look into the log file of Elasticsearch itself.

At first sight, it seems like there's something wrong with the data types, e.g. you're searching for something that's not full text searchable. But the error message will tell us more.
