### ISSUE TITLE
NewTermsQuery does not produce expected output when input is a slice

### ISSUE THREAD

**Issue by Pungyeon** [olivere/elastic#859]
So, basically I am referring to the code in `search_queries_terms.go`, in which you have the following code:

```go
// NewTermsQuery creates and initializes a new TermsQuery.
func NewTermsQuery(name string, values ...interface{}) *TermsQuery {
	q := &TermsQuery{
		name:   name,
		values: make([]interface{}, 0),
	}
	if len(values) > 0 {
		q.values = append(q.values, values...)
	}
	return q
}
```

Basically, this works fine when invoke the function as such: `NewTermsQuery("name", "value1", "value2")`. But, it produces incorrect output, if you use it with a slice, such as: `NewTermsQuery("name", []string{"value1", "value2"})`. The problems is that the query output is something similar to:

```json
"bool": {
    "must": [ 
        { "terms": { "source": [
            ["192.168.162.184", "216.58.213.238"]
        ] } }
    ]
}
```
The issue being the double brackets surrounding the `source` property of the terms query.

I'm not sure if there is a nice workaround to this, or even how to implement a fix in the code, if that is the road to go down. However, very willing to help out on this, if anyone has good ideas.

Thanks!

**Comment by olivere** [comment]
The signature does not expect an array. It's a [variadic function](https://gobyexample.com/variadic-functions). If you have a slice, you could add triple trailing dots:

```
values := []string{"value1", "value2"}
NewTermsQuery("name", values...)
```

(Introduced a temporary variable to make it more evident.)

**Comment by Pungyeon** [comment]
Hm, I don't think that works. If I input something like `NewTermsQuery("name", []string{"value1", "value2"}...)` this results in a compiler error: "cannot use (type []string) as type []interface{} in argument to elastic.NewTermsQuery"

So, I though ok. I can convert this to an `[]interface{}` and then use the converted slice... but nope. I still get the double brackets that are causing me issues. Am I doing something wrong? This is an example of what I'm trying to do... if the output is contained in brackets then it won't work together with `NewTermsQuery`.

**Comment by olivere** [comment]
You're correct. You need to manually copy them over to a `[]interface{}` first, then append the `...`, [like so](https://play.golang.org/p/JmEy35DimX3).

**Comment by Pungyeon** [comment]
Great that seems to work. Thanks a lot for the quick response!

**Comment by olivere** [comment]
You're welcome.
