### ISSUE TITLE
SetURL seems to be ignored

### ISSUE THREAD

**Issue by tamagokun** [olivere/elastic#86]
Trying a really basic example:

```go
  client, err := elastic.NewClient(
    elastic.SetHealthcheck(false),
    elastic.SetSniff(false),
    elastic.SetURL("http://xx.xxx.xx.xxx:9200"),
    elastic.SetErrorLog(log.New(os.Stderr, "ELASTIC ", log.LstdFlags)),
    elastic.SetInfoLog(log.New(os.Stdout, "", log.LstdFlags)),
  )
  if err != nil {
    panic(err)
  }

  info, code, err := client.Ping().Do()
  if err != nil {
    panic(err)
  }
  log.Printf("Elasticsearch returned with code %d and version %s", code, info.Version.Number)
```

Here's the result:

```
PANIC: Get http://127.0.0.1:9200/: dial tcp 127.0.0.1:9200: connection refused
```

It seems like somehow `SetURL` is getting overwritten or ignored.

I can consistently `curl` the URL I am trying to connect to and it works. I am working off the master branch and on go 1.4.2 (mac).

**Comment by olivere** [comment]
Oh. The `Ping` service is special in that it doesn't use the URLs of the client but the one specified via the `URL` member of the `PingService` (which is `http://127.0.0.1:9200` by default).

So use this code to issue the ping to your URL instead:

```
info, code, err := client.Ping().URL("http://xxx.xxx.xxx.xxx:9200").Do()
...
```

The reason for this are as follows. First, you typically use `Ping` to find not only your current cluster, but also other Elasticsearch instances as well. Second, you can specify many URLs for your cluster and it happily does round-robin to load balance between the nodes. If you use many URLs, which one do you use by default for the `PingService`?

Anyway, just specify a `URL` with your `Ping` and you should be fine. :-)

**Comment by tamagokun** [comment]
Thanks!

**Comment by trihatmaja** [comment]
I found the same problem and my solution is add the slash at the end of the URL. elastic.SetURL("http://xx.xxx.xx.xxx:9200/"). It works like a charm. Ping service should do the same.
