### ISSUE TITLE
Ability to append headers to requests

### ISSUE THREAD

**Issue by GarrettKelley** [olivere/elastic#862]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ x ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
As of ES6, you can add a the X-Opaque-ID header to requests in order to be able to trace/track tasks as they execute. This functionality is found in the ES documentation here:
https://www.elastic.co/guide/en/elasticsearch/reference/6.2/tasks.html#_identifying_running_tasks
The current version of this API doesn't allow headers to be appended.  I modified the source code to resolve this, but it appears I can't make a branch to make a PR without first creating an issue.

### Please describe the actual behavior
That the library provides a way to attach headers to the requests that are submitted to ES.

### Any steps to reproduce the behavior?
If you show the list of running tasks, the headers field is always empty.  The impacted files are attached.  I only modified the ScrollService and TaskList (as opposed to all services) because that was the service I needed to use for my personal case.

Here are the modified files:
[elasticHeaders.zip](https://github.com/olivere/elastic/files/2290216/elasticHeaders.zip)

**Comment by olivere** [comment]
Add in 51d010201ba7bcb2dec3d84f225fec8617de11d5 and 51d010201ba7bcb2dec3d84f225fec8617de11d5.
