### ISSUE TITLE
RetryOnConflict for BulkUpdateRequest on Elasticsearch 6.0

### ISSUE THREAD

**Issue by dbakti7** [olivere/elastic#870]
I am trying to use RetryOnConflict on BulkUpdateRequest with Elasticsearch 6.0.
I am aware that from v6.1+, the parameter expected is retry_on_conflict, whereby for 6.0 is _retry_on_conflict.
Is there any way for me to use elastic.v6 that supports _retry_on_conflict?

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[x] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
RetryOnConflict is compatible with Elasticsearch 6.0 with _retry_on_conflict parameter.

### Please describe the actual behavior
RetryOnConflict is used with retry_on_conflict parameter.

### Any steps to reproduce the behavior?
Use RetryOnConflict on Elasticsearch 6.0

**Comment by olivere** [comment]
Right now, there's no way in Elastic. Any reason you don't upgrade to a 6.x version; it might fix other bugs in ES as well? Other than that: The only chance I see it to copy the existing `BulkUpdateRequest` and change the code accordingly, then use that class to push to Bulk API. As long as it implements `BulkableRequest` interface, you're ready to got.
