### ISSUE TITLE
'sliced-scroll'  query ES data  used   for a long time

### ISSUE THREAD

**Issue by yyyyykkkk** [olivere/elastic#871]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[x] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
I run this 'sliced_scroll' ，

print logs :
Scrolled through a total of 13378 documents in 8.024080607s
Slice  0 received 663 documents
Slice  1 received 649 documents
Slice  2 received 685 documents
Slice  3 received 663 documents
Slice  4 received 700 documents
Slice  5 received 652 documents
Slice  6 received 690 documents
Slice  7 received 646 documents
Slice  8 received 664 documents
Slice  9 received 660 documents
Slice 10 received 713 documents
Slice 11 received 704 documents
Slice 12 received 611 documents
Slice 13 received 717 documents
Slice 14 received 662 documents
Slice 15 received 645 documents
Slice 16 received 658 documents
Slice 17 received 659 documents
Slice 18 received 686 documents
Slice 19 received 651 documents

i do not know why  it used so much  long time ....
How to get a large amount of data to reduce time ?

**Comment by olivere** [comment]
Without any data and code, I cannot do anything to help you.

**Comment by olivere** [comment]
I think you were just testing the `sliced_scroll` recipe, right? On a single server, sliced scroll will probably have worse performance than normal scroll. It's when you have a large cluster that sliced scroll will help.

Here's my results on a MacBook:

```
$ go run sliced_scroll.go -index=testdata -type=_doc -n=16
Scrolled through a total of 20000 documents in 7.002732099s
Slice  0 received 1100 documents
Slice  1 received 1337 documents
Slice  2 received 1338 documents
Slice  3 received 1347 documents
Slice  4 received 1317 documents
Slice  5 received 993 documents
Slice  6 received 1277 documents
Slice  7 received 1324 documents
Slice  8 received 1301 documents
Slice  9 received 1317 documents
Slice 10 received 1025 documents
Slice 11 received 1339 documents
Slice 12 received 1344 documents
Slice 13 received 1332 documents
Slice 14 received 1309 documents
Slice 15 received 1000 documents
$ go run sliced_scroll.go -index=testdata -type=_doc -n=4
Scrolled through a total of 20000 documents in 4.519559985s
Slice  0 received 8061 documents
Slice  1 received 3953 documents
Slice  2 received 4006 documents
Slice  3 received 3980 documents
$ go run sliced_scroll.go -index=testdata -type=_doc -n=2
Scrolled through a total of 20000 documents in 4.161829244s
Slice  0 received 12067 documents
Slice  1 received 7933 documents
```

**Comment by yyyyykkkk** [comment]
thanks for your replay!
when i use `curl -XGET http://xxxx:9200/index/_search?size=10000`  ,the way  responsed  so quickly. 

20000 docs spent 4 seconds normal?

**Comment by yyyyykkkk** [comment]
Is there any better and faster way to get around 50,000 docs?

**Comment by olivere** [comment]
Doing that `curl` query takes 5s on my machine:

```
curl -XGET 'http://localhost:9200/testdata/_search?size=10000' 
...
0.01s user 0.03s system 0% cpu 5.005 total
```

But you have to make sure that you don't spend time waiting for screen output. What are the numbers if you don't count that...?

**Comment by olivere** [comment]
The time it takes is very dependent on the data you save. E.g. do you have 10 bytes of JSON per document, or 2MB? There's so many different things that you cannot simply take a stop watch to make any statements about performance.

**Comment by yyyyykkkk** [comment]
thanks!
The 4s is  used the 'sliced_scroll' demo , and  not included waiting for screen output.
10000 docs is around 3MB.
