### ISSUE TITLE
How can I reverse the sequence of time, I really can not find where the document is.

### ISSUE THREAD

**Issue by bugfan** [olivere/elastic#875]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v6 (for Elasticsearch 6.x)

**Comment by olivere** [comment]
You can find documentation for Elasticsearch [here](https://www.elastic.co/guide/en/elasticsearch/reference/6.4/index.html). What you need is [sorting](https://www.elastic.co/guide/en/elasticsearch/reference/6.4/search-request-sort.html).

Please read the official documentation for Elasticsearch first. Then come back to Elastic, the Go client, and implement your solution. You can see many examples in the tests, e.g. [`search_test.go`](https://github.com/olivere/elastic/blob/release-branch.v6/search_test.go) and the [Wiki](https://github.com/olivere/elastic/wiki).
