### ISSUE TITLE
can not parse timestamp.

### ISSUE THREAD

**Issue by wjzhangcsu** [olivere/elastic#876]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[X] elastic.v6 (for Elasticsearch 6.x)

### Please describe the actual behavior
```
elastic: Error 400 (Bad Request): request [/player_log/player_log/1] contains unrecognized parameter: [timestamp] [type=illegal_argument_exception]
```

### Any steps to reproduce the behavior?

![image](https://user-images.githubusercontent.com/11661685/44643171-23147580-aa02-11e8-8c14-3b54a35ca54c.png)
I have attempted other time formats ,too. All return this result.

**Comment by olivere** [comment]
I think you have found a very very old bug. Seems like `timestamp` was [deprecated in Elasticsearch 2.0.0-beta2](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/mapping-timestamp-field.html), years ago. We need to remove it from Index API.

**Comment by olivere** [comment]
Watch out for timezones!

**Comment by wjzhangcsu** [comment]
I just want to use olivere/elastic to do something like fluentd. I am not sure it can do it or not.

**Comment by olivere** [comment]
You want to build something like fluentd, in Go, using just this library? I'm not an expert with fluentd, but in a nutshell, it looks like you only need to get input from the source and use Bulk API to write output to Elasticsearch. Something like the [Bulk Insert recipe](https://github.com/olivere/elastic/blob/release-branch.v6/recipes/bulk_insert/bulk_insert.go).

But I'm pretty sure fluentd cares for a lot of things that you might not even know right now.
