### ISSUE TITLE
Add support for index prefix

### ISSUE THREAD

**Issue by arthurgustin** [olivere/elastic#879]
I have a use-case where I want differents delivery platforms use the same elasticsearch cluster.
The same code is deployed on each environnement (can be in different version) and I don't want them to collide on applicative-indices.
The solution I've found is to use a different configuration prefix in each environnement, understable by the application.
For instance, a index would be named `dev_foo` on the `dev` platform but would be named `int_foo` on the `integration` platform.
It means that on all microservices using elastic search, I have a configuration variable somewhere that is used in every elastic call like this:

```golang
indexResponse, err := m.ElasticClient.Index().
    Index(m.conf.IndexPrefix+"foo").
    Type("default").
    Id(myId).
    BodyJson(myBodyJson).
    Do(ctx)
```

This solution works, but its a pain to do this everywhere and it can be a source of confusion and mistakes for me and other developers.
A better solution would be to set the prefix in the `elastic.NewClient()` method like this:

```golang
func (p *ElasticSearchProvider) Provide(ctx context.Context) (*elastic.Client, error) {
	httpClient := &http.Client{Transport: &runAsUserTransport{Transport: http.DefaultTransport}}
	return elastic.NewClient(
		elastic.SetBasicAuth(p.EsUsername, p.EsPassword),
		elastic.SetURL(p.EsContactPoint),
		elastic.SetSniff(false),
		elastic.SetHealthcheck(false),
		elastic.SetRetrier(elastic.NewBackoffRetrier(elastic.NewExponentialBackoff(1*time.Second, 20*time.Second))),
		elastic.SetHealthcheckTimeoutStartup(0),
		elastic.SetHttpClient(httpClient),
                elastic.SetIndexPrefix("foo_") // <--- 
	)
}
```
 
Allowing my applicative code to be clean (only main function would be impacted)

I know this is very specific, but what do you think about all this ?

**Comment by olivere** [comment]
I see your point. It's basically a special case of [multi-tenancy](https://www.elastic.co/blog/found-multi-tenancy). However, I'm not sure if that's a good solution for the library. Suppose you, for some certain API, want to skip the index prefix: How do we do that? Make an exception to the rule. This might end up in a configuration nightmare.

Maybe it would make sense to [set up index aliases](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html) so you use the same index from within your application but end up in different indices from the outside.

Another, and maybe even the best approach might be to abstract away the `*elastic.Client` instance and hide it behind an interface. This obviously depends on how many features of Elastic you're using. But, done correctly, this will simplify your code and make testing an ease. See #632 for a previous discussion.
