### ISSUE TITLE
Correct way to import package with go 1.11

### ISSUE THREAD

**Issue by JamieH** [olivere/elastic#881]
elastic.v6 (for Elasticsearch 6.x)

When trying to build with an import path ending with `/v6` I get the following error:
`main.go:17:2: unknown import path "github.com/olivere/elastic/v6": cannot find module providing package github.com/olivere/elastic/v6`

Should I be importing without `/v6` until [this commit](https://github.com/olivere/elastic/commit/66b430cdba34722e4a9656f651df616fe5f0503f) is reverted? If so I think the README needs correcting too.

Thanks!

**Comment by olivere** [comment]
README was fixed just now. Yes, remove that `/v6` at the end and you should be ready to go.

If you want the latest version in your Go modules based project, use something like:

```
$ go get -u github.com/olivere/elastic@v6.2.2
```
