### ISSUE TITLE
Percolator query does not allow searches on existing documents

### ISSUE THREAD

**Issue by seanlaff** [olivere/elastic#884]
### Which version of Elastic are you using?

[ x ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
I'm trying to percolate on an existing document, as described here https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-percolate-query.html#_percolating_an_existing_document

I would expect that I could do
```go
percolatorQuery := elastic.NewPercolatorQuery().
		IndexedDocumentId(id).
		Field(percolatorField)
```

### Please describe the actual behavior
I get an error "elastic: Document is required in PercolatorQuery" because of this check in the library https://github.com/olivere/elastic/blob/d677dbe6d6a14f0b4f10dd28e906452f1e1d6d06/search_queries_percolator.go#L81-L83

**Comment by olivere** [comment]
Heya! Looks like that is possible now. I wasn't aware of that. Let me look into that in the next release.
