### ISSUE TITLE
DOC: synced flush api is not supported yet

### ISSUE THREAD

**Issue by taylorchu** [olivere/elastic#886]
I am testing a feature that requires elasticsearch synced flush https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-synced-flush.html. Although the readme says that is supported, I cannot find that in the source code. Could you clarify this? Thanks!

### Which version of Elastic are you using?

[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
synced flush api is available. It says it is available in the readme. 

### Please describe the actual behavior
synced flush api is actually not supported. 

https://github.com/olivere/elastic/blob/ca207b1b9b00633638fa8ee13382477b8015aa95/indices_flush.go#L99

Could you provide an example on how to use it to sync flush with the current api?
Thanks!

**Comment by olivere** [comment]
Yes, it was missing in the repository. Thanks for addressing that. It's in the v6 branch now and will be released with 6.2.5. See [`indices_flush_synced_test.go`](https://github.com/olivere/elastic/blob/release-branch.v6/indices_flush_synced_test.go) for example usage.

**Comment by taylorchu** [comment]
Thank you!
