### ISSUE TITLE
The SearchResult is not correct

### ISSUE THREAD

**Issue by Maybrittnelson** [olivere/elastic#889]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v6 (for Elasticsearch 6.x)
[x] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
I have four records，One was on September 3rd.
![image](https://user-images.githubusercontent.com/20365012/44990760-a9155b00-afc4-11e8-9c40-dc744efd5fe8.png)
### Please describe the actual behavior
But when I set the TermQuery with a field value, it doesn't go away
![image](https://user-images.githubusercontent.com/20365012/44991284-28eff500-afc6-11e8-88c6-cd15281d4397.png)
But in Kibana it can be shown normally
![image](https://user-images.githubusercontent.com/20365012/44991326-4f159500-afc6-11e8-9527-f910168eaa19.png)
### Any steps to reproduce the behavior?
i use this query
![image](https://user-images.githubusercontent.com/20365012/44991611-3063ce00-afc7-11e8-84c6-10066a5beaf6.png)
I guess there's a problem with elasticsearch，I create the client in this way```func NewClient(options ...ClientOptionFunc) (*Client, error)```
![image](https://user-images.githubusercontent.com/20365012/44991705-8173c200-afc7-11e8-95e7-01e438981c6b.png)

**Comment by olivere** [comment]
Can you please post the mapping of the specified index?

**Comment by Maybrittnelson** [comment]
![image](https://user-images.githubusercontent.com/20365012/45006316-d09f0e80-b02a-11e8-9e0b-861fa5d837ec.png)
