### ISSUE TITLE
Stored number as interface is always a float

### ISSUE THREAD

**Issue by pavolloffay** [olivere/elastic#891]
Hi, 

I am storing `map[string]interface{}` mapped to object datatype. When reading numbers I always get `float64` even if the field was stored as `int64`. For example stored int64(0) is always read as float64(0).

### Which version of Elastic are you using?

[ ] elastic.v6 (for Elasticsearch 6.x)
[ x] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

Stored integers should be read as integers not floats.

### Please describe the actual behavior

I am storing `map[string]interface` as an object datatype to ES. With following dynamic template mapped to all fields in the map.
```
"mapping": {
  'type": "keyword",
  "ignore_above": 256
},
```

```
tagsMap := map[string]interface{}{}
tagsMap["1_int"] = int64(1)
tagsMap["0_int"] = int64(0)
```

When reading `1_int` and `0_int` is always returned as `float64`.

**Comment by pavolloffay** [comment]
This is related to https://github.com/jaegertracing/jaeger/pull/1018. We are trying to store `interface{}` and properly read stored type.

**Comment by olivere** [comment]
Ehm. I'm not sure about the issue, but do you expect to parse the JSON from Elasticsearch into a `map[string]interface{}` and expect to get a value of type `int64`? That'd probably never work because JSON doesn't have an integer type.

Let me know if I misunderstood the issue.

**Comment by pavolloffay** [comment]
yes I expect it to be int64 if it was int64 when storing it.

**Comment by pavolloffay** [comment]
If it does not have fraction part e.g. `.x` it could be parsed to int

**Comment by pavolloffay** [comment]
Standard golang json returns always float https://play.golang.org/p/qshk0x7s5i_1

**Comment by olivere** [comment]
Yes. There's no way around that, as there is no type information in the JSON data returned from Elasticsearch. If you specify a `type` with `json` flags, Go does the type conversion for you. Otherwise you have to do it yourself. But as you are the one storing the data, you should be responsible for converting it back to its correct type.

BTW: No need to `reflect` in your example. You can simple use `fmt.Printf("%T\n", f.Val)`.

**Comment by pavolloffay** [comment]
Btw I have this at the moment https://github.com/jaegertracing/jaeger/pull/1018/files#diff-c8ffac58acc675245a73d9a1e9a177a1R155. The only issue is with floats like `1.0`, `1`. They are always converted to int. Not sure if we can get better than that.

**Comment by olivere** [comment]
I don't know any details of Jaeger, sorry. Do you control the mapping? If you do, maybe you can control the field names and derive the type from the field name when deserializing. Like having a `_i64` suffix to store an `int64` etc. That's what most people do with [dynamic templates](https://www.elastic.co/guide/en/elasticsearch/reference/6.4/dynamic-templates.html) to a) force ES to pick the correct type and b) allow the schema to grow over time.

**Comment by aglick-thumbtack** [comment]
This becomes a legitimate issue using large ints.  Forcing a large (~17+ digit) 64 bit int (something json definitely supports and ES correctly returns) into a float results in precision loss.  Go's json library provides a clean path with `Decoder.UseNumber()`.  That at least enables the consumer to have the opportunity to read the int before truncation.

**Comment by pavolloffay** [comment]
@aglick-thumbtack do you have a workaround in place?

**Comment by olivere** [comment]
You can always [configure your own decoder](https://github.com/olivere/elastic/wiki/Decoder).

**Comment by pavolloffay** [comment]
thanks!
