### ISSUE TITLE
Query returns (Internal Server Error): all shards failed [type=search_phase_execution_exception]

### ISSUE THREAD

**Issue by philrogers** [olivere/elastic#892]
Hi Guys,
I am new to golang but a coder for a long time. We have been using elasticsearch a lot lately and a requirement came up use golang for some queries.

I came across this library olivere/elastic. The elasticsearch cluster is version 5.5.

I have now reached a state where I am going to ask for help as I have been trying to get to the bottom of this for a few days now. So would appreciate some help.

I need to perform a simply query on an index called st2.action_execution_d_b  of type action_execution_d_b

I am searching for all records that have a status.keyword: succeeded OR  status.keyword: delayed
AND have a start_timestamp  from the date time right now - 24hrs to the date time now.  Dates are stored in epoch ms in the elasticsearch field start_timestamp

The following code is being used to build the query

var yesterday = time.Now().AddDate(0, 0, -1)
yesterdaymillis := yesterday.UnixNano() / 1000000
stryesterdaymillis := strconv.FormatInt(yesterdaymillis, 10)
var today = time.Now()
todaymillis := today.UnixNano() / 1000000
strtodaymillis := strconv.FormatInt(todaymillis, 10)
matchQuery1 := elastic.NewQueryStringQuery("status.keyword:succeeded OR status.keyword:delayed")
matchQuery2 := elastic.NewRangeQuery("start_timestamp").From(stryesterdaymillis).To(strtodaymillis)
	
query1 := elastic.NewBoolQuery().Must(matchQuery1).Filter(matchQuery2)
 
I then dump out the query source
src, err := query1.Source()
if err != nil {
	panic(err)
}
data, err := json.MarshalIndent(src, "", "  ")
if err != nil {
	panic(err)
}
fmt.Println(string(data))

The debug output of data variable is

{
  "bool": {
    "filter": {
      "range": {
        "start_timestamp": {
          "from": "1536040932770",
          "include_lower": true,
          "include_upper": true,
          "to": "1536127339321"
        }
      }
    },
    "must": {
      "query_string": {
        "query": "status.keyword:succeeded OR status.keyword:delayed"
      }
    }
  }
}

I then execute the search
searchResult, err := client.Search().
 	Index("st2.action_execution_d_b"). // search in index "twitter"
	Type("action_execution_d_b").
	Query(query1).
	Sort("start_timestamp", true). // sort by "timestamp" field, ascending
	From(0).Size(100000). // take documents 0-9
	Pretty(true).         // pretty print request and response JSON
	Do(ctx)               // execute
	

       if err != nil {
		// Handle error
		panic(err) <----- panics here
	}
The code panics  with 
elastic: Error 500 (Internal Server Error): all shards failed [type=search_phase_execution_exception]

To debug 
I then copy the query lines below to the postman rest utility https://github.com/postmanlabs/postman-app-support/ and make a rest call directly to the elasticsearch cluster with the query generated by the code above.
http://clustername:9200/st2.action_execution_d_b/action_execution_d_b/_search
Body

 {
  "bool": {
    "filter": {
      "range": {
        "start_timestamp": {
          "from": "1536040932770",
          "include_lower": true,
          "include_upper": true,
          "to": "1536127339321"
        }
      }
    },
    "must": {
      "query_string": {
        "query": "status.keyword:succeeded OR status.keyword:delayed"
      }
    }
  }
}

I receive a different error to what the go panic presented.
Postman error
{
    "error": {
        "root_cause": [
            {
                "type": "parsing_exception",
                "reason": "Unknown key for a START_OBJECT in [bool].",
                "line": 2,
                "col": 11
            }
        ],
        "type": "parsing_exception",
        "reason": "Unknown key for a START_OBJECT in [bool].",
        "line": 2,
        "col": 11
    },
    "status": 400
} 

If I then add to the start of the query string { "query" :   and add a closing bracket at the end. and execute it in postman. The query is successful and returns the correct results
{
"query" : {
  "bool": {
    "filter": {
      "range": {
        "start_timestamp": {
          "from": "1536040932770",
          "include_lower": true,
          "include_upper": true,
          "to": "1536127339321"
        }
      }
    },
    "must": {
      "query_string": {
        "query": "status.keyword:succeeded OR status.keyword:delayed"
      }
    }
  }
}
}

I am puzzled what is going on internally I have stepped through debug looking but I cant see the answer.

The cluster is available
I run this code when the code starts
info, code, err := client.Ping(elasticserver).Do(ctx)
	if err != nil {
		// Handle error
		panic(err)
	}
	fmt.Printf("Elasticsearch returned with code %d and version %s\n", code, info.Version.Number)

	// Getting the ES version number is quite common, so there's a shortcut
	esversion, err := client.ElasticsearchVersion(elasticserver)
	if err != nil {
		// Handle error
		panic(err)
	}
	fmt.Printf("Elasticsearch version %s\n", esversion)

Elasticsearch returned with code 200 and version 5.5.0
Elasticsearch version 5.5.0

### Which version of Elastic are you using?
Tried Both
[ ] elastic.v6 (for Elasticsearch **6.x)**
[ ] elastic.v5 (for Elasticsearch 5.x)

I would appreciate any advise to get past this

Regards
Phil

**Comment by olivere** [comment]
You can make your life so much easier by enabling the `TraceLog` (see [here](https://github.com/olivere/elastic/wiki/Logging)). Then you can see what's being sent and what comes back from Elasticsearch.

Can you post a small example of your code in a runnable program, like e.g. [this one](https://github.com/olivere/elastic/blob/release-branch.v6/recipes/mapping/mapping.go)?

**Comment by olivere** [comment]
BTW: When you're looking for exact matches, don't use `QueryStringQuery` or its friend, use `TermQuery`. While you can achieve the same with `QueryStringQuery`, they are typically meant to be used for full text queries, while `TermQuery` and friends are more like SQL-equality/-inequality checks.

**Comment by olivere** [comment]
Also, `size` cannot be greater than 10.000 by default (see [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html)). You can increase `index.max_result_window` but probably should use the Scroll API instead.

**Comment by philrogers** [comment]
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"strconv"

	//"gopkg.in/olivere/elastic.v5"

	"time"

	"github.com/gorilla/mux"
	"github.com/olivere/elastic"
)

var elasticserver = "http://servername:9200"
var client, err = elastic.NewClient(elastic.SetURL(elasticserver), elastic.SetHealthcheckTimeout(15), elastic.SetHealthcheck(true), elastic.SetGzip(false))

// The QueueStats Type (more like an object)
type QueueStats struct {
	Queued int64  `json:"queued"`
	STot   string `json:"firstname,omitempty"`
}

// main function to boot up everything
func main() {
	fmt.Printf("Starting up connection to " + elasticserver)
	ctx := context.Background()
	if err != nil {
		// Handle error
		panic(err)
	}
	fmt.Printf("connectioned to " + elasticserver)
	// Obtain a client and connect to the default Elasticsearch installation
	// on 127.0.0.1:9200. Of course you can configure your client to connect
	// to other hosts and configure it in various other ways.

	// Obtain a client and connect to the default Elasticsearch installation
	// on 127.0.0.1:9200. Of course you can configure your client to connect
	// to other hosts and configure it in various other ways.

	// Ping the Elasticsearch server to get e.g. the version number
	info, code, err := client.Ping(elasticserver).Do(ctx)
	if err != nil {
		// Handle error
		panic(err)
	}
	fmt.Printf("Elasticsearch returned with code %d and version %s\n", code, info.Version.Number)

	// Getting the ES version number is quite common, so there's a shortcut
	esversion, err := client.ElasticsearchVersion(elasticserver)
	if err != nil {
		// Handle error
		panic(err)
	}
	fmt.Printf("Elasticsearch version %s\n", esversion)

	router := mux.NewRouter()
	router.HandleFunc("/api/v1/stackstorm/queuestats", GetQueueStats).Methods("GET")
	log.Fatal(http.ListenAndServe(":8000", router))
}

func GetQueueStats(w http.ResponseWriter, r *http.Request) {
	ctx := context.Background()
	// termQuery := elastic.NewTermQuery("status", "status")
	var yesterday = time.Now().AddDate(0, 0, -1)
	yesterdaymillis := yesterday.UnixNano() / 1000000
	stryesterdaymillis := strconv.FormatInt(yesterdaymillis, 10)
	var today = time.Now()
	todaymillis := today.UnixNano() / 1000000
	strtodaymillis := strconv.FormatInt(todaymillis, 10)
	matchQuery1 := elastic.NewQueryStringQuery("status.keyword:succeeded OR status.keyword:delayed")
	matchQuery2 := elastic.NewRangeQuery("start_timestamp").From(stryesterdaymillis).To(strtodaymillis)

	query1 := elastic.NewBoolQuery().Must(matchQuery1).Filter(matchQuery2)

	// debug code
	src, err := query1.Source()
	if err != nil {
		panic(err)
	}
	data, err := json.MarshalIndent(src, "", "  ")
	if err != nil {
		panic(err)
	}
	fmt.Println(string(data))
	// end of debug
	searchResult, err := client.Search().
		//    Search(). //
		Index("st2.action_execution_d_b"). // search in index "twitter"
		Type("action_execution_d_b").
		Query(query1).
		Sort("start_timestamp", true). // sort by "timestamp" field, ascending
		From(0).Size(1000).            // take documents 0-9
		Pretty(true).                  // pretty print request and response JSON
		Do(ctx)                        // execute
	if err != nil {
		// Handle error
		panic(err)
	}
	if searchResult.Hits.TotalHits > 0 {
		fmt.Printf("Found a total of %d records \n", searchResult.Hits.TotalHits)
	}
	var queuestats []QueueStats
	queuestats = append(queuestats, QueueStats{Queued: searchResult.Hits.TotalHits, STot: "Test"})

	json.NewEncoder(w).Encode(queuestats)
}

**Comment by philrogers** [comment]
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"strconv"

	//"gopkg.in/olivere/elastic.v5"

	"time"

	"github.com/gorilla/mux"
	"github.com/olivere/elastic"
)

var elasticserver = "http://servername:9200"
var client, err = elastic.NewClient(elastic.SetURL(elasticserver), elastic.SetHealthcheckTimeout(15), elastic.SetHealthcheck(true), elastic.SetGzip(false))

// The QueueStats Type (more like an object)
type QueueStats struct {
	Queued int64  `json:"queued"`
	STot   string `json:"firstname,omitempty"`
}

// main function to boot up everything
func main() {
	fmt.Printf("Starting up connection to " + elasticserver)
	ctx := context.Background()
	if err != nil {
		// Handle error
		panic(err)
	}
	fmt.Printf("connectioned to " + elasticserver)
	// Obtain a client and connect to the default Elasticsearch installation
	// on 127.0.0.1:9200. Of course you can configure your client to connect
	// to other hosts and configure it in various other ways.

	// Obtain a client and connect to the default Elasticsearch installation
	// on 127.0.0.1:9200. Of course you can configure your client to connect
	// to other hosts and configure it in various other ways.

	// Ping the Elasticsearch server to get e.g. the version number
	info, code, err := client.Ping(elasticserver).Do(ctx)
	if err != nil {
		// Handle error
		panic(err)
	}
	fmt.Printf("Elasticsearch returned with code %d and version %s\n", code, info.Version.Number)

	// Getting the ES version number is quite common, so there's a shortcut
	esversion, err := client.ElasticsearchVersion(elasticserver)
	if err != nil {
		// Handle error
		panic(err)
	}
	fmt.Printf("Elasticsearch version %s\n", esversion)

	router := mux.NewRouter()
	router.HandleFunc("/api/v1/stackstorm/queuestats", GetQueueStats).Methods("GET")
	log.Fatal(http.ListenAndServe(":8000", router))
}

func GetQueueStats(w http.ResponseWriter, r *http.Request) {
	ctx := context.Background()
	// termQuery := elastic.NewTermQuery("status", "status")
	var yesterday = time.Now().AddDate(0, 0, -1)
	yesterdaymillis := yesterday.UnixNano() / 1000000
	stryesterdaymillis := strconv.FormatInt(yesterdaymillis, 10)
	var today = time.Now()
	todaymillis := today.UnixNano() / 1000000
	strtodaymillis := strconv.FormatInt(todaymillis, 10)
	matchQuery1 := elastic.NewQueryStringQuery("status.keyword:succeeded OR status.keyword:delayed")
	matchQuery2 := elastic.NewRangeQuery("start_timestamp").From(stryesterdaymillis).To(strtodaymillis)

	query1 := elastic.NewBoolQuery().Must(matchQuery1).Filter(matchQuery2)

	// debug code
	src, err := query1.Source()
	if err != nil {
		panic(err)
	}
	data, err := json.MarshalIndent(src, "", "  ")
	if err != nil {
		panic(err)
	}
	fmt.Println(string(data))
	// end of debug
	searchResult, err := client.Search().
		//    Search(). //
		Index("st2.action_execution_d_b"). // search in index "twitter"
		Type("action_execution_d_b").
		Query(query1).
		Sort("start_timestamp", true). // sort by "timestamp" field, ascending
		From(0).Size(1000).            // take documents 0-9
		Pretty(true).                  // pretty print request and response JSON
		Do(ctx)                        // execute
	if err != nil {
		// Handle error
		panic(err)
	}
	if searchResult.Hits.TotalHits > 0 {
		fmt.Printf("Found a total of %d records \n", searchResult.Hits.TotalHits)
	}
	var queuestats []QueueStats
	queuestats = append(queuestats, QueueStats{Queued: searchResult.Hits.TotalHits, STot: "Test"})

	json.NewEncoder(w).Encode(queuestats)
}

**Comment by olivere** [comment]
I can't help you unless you give me real data and real code I can execute. The above code doesn't even compile.

See [this example](https://gist.github.com/olivere/f354941dcefd29453b0d2fc0fe50483f) which should be something similar to what you're trying to do. I hope that illustrates the things you're looking for.
