### ISSUE TITLE
returns error if using wildcard index and using SetHttpClient

### ISSUE THREAD

**Issue by mosimosi1100** [olivere/elastic#894]
### Which version of Elastic are you using?
elastic.v6 (for Elasticsearch 6.3) 
AWS ES

### Please describe the actual behavior
When using wildcard index and using SetHttpClient, it returns error "elastic: Error 403 (Forbidden)".

### Any steps to reproduce the behavior?
This is working well.
```
var url string = os.Getenv("AWS_ELASTICSEARCH_ENDPOINT")
signingClient := aws.NewV4SigningClient(awsauth.Credentials{
	AccessKeyID:     os.Getenv("AWS_ACCESS_KEY_ID"),
	SecretAccessKey: os.Getenv("AWS_SECRET_ACCESS_KEY"),
})

client, err := elastic.NewClient(
	elastic.SetURL(url),
	elastic.SetSniff(false),
	elastic.SetHttpClient(signingClient),
)

ctx := context.Background()
searchResult, err := client.Search().
	Index("test-2018").
	Pretty(true).
	Do(ctx)

```
if I use wildcard index such as here, returns errror.
```
searchResult, err := client.Search().
	Index("test-*").
	Pretty(true).
	Do(ctx)
```

Does it changes request to endpoint if use SetHttpClient?
Thanks.

**Comment by olivere** [comment]
Maybe solved by #895?!

**Comment by olivere** [comment]
What is the exact error message of the `403`? Can you [enable trace logging](https://github.com/olivere/elastic/wiki/Logging) and send the output? I only see `403` from ES when there's an expired license or you're authenticating via X-Pack and the user is using invalid credentials.

**Comment by mosimosi1100** [comment]
@olivere  Thank you for your reply.
Here is whole error message from aws.
```
{"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."}
```
Above is returned only using wildcard only.  When I try without wildcard working correctly.

So I try to request searching with wildcard to ES on Aws via postman set Authorization. 
=> Response is good.  Oops..
Aws accepts a request with wildcard index  and authorization token.

I'm suspecting around headers too.
thanks.
