### ISSUE TITLE
Unexpected SearchShardsService.Do() error when shards are relocating

### ISSUE THREAD

**Issue by lr-paul** [olivere/elastic#897]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v6 (for Elasticsearch 6.x)
[ X ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
`SearchShardsService.Do()` does not return an error when the cluster is otherwise alive and healthy but shards are relocating.

### Please describe the actual behavior
This error is returned by `SearchShardsService.Do()`: `SearchShards error: json: cannot unmarshal string into Go struct field ShardsInfo.relocating_node of type bool`

### Any steps to reproduce the behavior?
Call `SearchShardsService.Do()` while shards are relocating.

**Comment by olivere** [comment]
Thanks for your support. Will be part of 6.2.6 and 5.0.76.
