### ISSUE TITLE
Add format specifier to date_histogram composite aggregation

### ISSUE THREAD

**Issue by skrynauw** [olivere/elastic#899]
Version 6.3 of elasticsearch adds the format specifier to date_histogram Composite Aggregations

### Which version of Elastic are you using?
[X] elastic.v6 (for Elasticsearch 6.4)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

**Comment by olivere** [comment]
Thanks for your support. Will be released in 6.2.6 soon.
