### ISSUE TITLE
Ping attempts to connect to local server even when specified otherwise

### ISSUE THREAD

**Issue by ysimonson** [olivere/elastic#90]
Ping appears to be connecting to the 127.0.0.1:9200, even when it's specified otherwise. Observed with both a commit from a few weeks ago, and the latest from HEAD.

Here's an example that's reproducing the issue:

    package main

    import (
    	"github.com/olivere/elastic"
    	"os"
    )

    func main() {
    	conn, err := elastic.NewClient(
    		elastic.SetURL(os.Getenv("ELASTICSEARCH_URL")),

    		// With sniffing enabled, the elastic client resolves the IP
    		// address(es) of the server and makes requests directly there. This
    		// doesn't work with found elasticsearch, presumably because it needs
    		// to know the Host to route requests to the correct database. So we
    		// disable it here.
    		elastic.SetSniff(false),
    	)

    	if err != nil {
    		panic(err)
    	}

    	_, _, err = conn.Ping().Do()

    	if err != nil {
    		panic(err)
    	}
    }

My `ELASTICSEARCH_URL` points to a cloud-hosted instance of elasticsearch:

    $ echo $ELASTICSEARCH_URL
    http://<subdomain>.foundcluster.com:9200

When I run this, I get this error:

    panic: Get http://127.0.0.1:9200/: dial tcp 127.0.0.1:9200: connection refused

    goroutine 1 [running]:
    main.main()
        /home/ubuntu/themuse/muselytics/src/muselytics/test.go:27 +0x22d

    goroutine 10 [select]:
    github.com/olivere/elastic.(*Client).sniffer(0xc208000ea0)
        /home/ubuntu/themuse/muselytics/src/muselytics/Godeps/_workspace/src/github.com/olivere/elastic/client.go:518 +0x1ae
    created by github.com/olivere/elastic.NewClient
        /home/ubuntu/themuse/muselytics/src/muselytics/Godeps/_workspace/src/github.com/olivere/elastic/client.go:218 +0x5bb

    goroutine 8 [IO wait]:
    net.(*pollDesc).Wait(0xc208010e60, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
    net.(*pollDesc).WaitRead(0xc208010e60, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
    net.(*netFD).Read(0xc208010e00, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x7fedc44d2b20, 0xc20800b028)
        /usr/local/go/src/net/fd_unix.go:242 +0x40f
    net.(*conn).Read(0xc208038088, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:121 +0xdc
    net/http.noteEOFReader.Read(0x7fedc44d3f40, 0xc208038088, 0xc20807a108, 0xc20800f000, 0x1000, 0x1000, 0xc208052580, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1270 +0x6e
    net/http.(*noteEOFReader).Read(0xc20801ea80, 0xc20800f000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
        <autogenerated>:125 +0xd4
    bufio.(*Reader).fill(0xc208050780)
        /usr/local/go/src/bufio/bufio.go:97 +0x1ce
    bufio.(*Reader).Peek(0xc208050780, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xf0
    net/http.(*persistConn).readLoop(0xc20807a0b0)
        /usr/local/go/src/net/http/transport.go:842 +0xa4
    created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:660 +0xc9f

    goroutine 17 [syscall, locked to thread]:
    runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

    goroutine 9 [select]:
    net/http.(*persistConn).writeLoop(0xc20807a0b0)
        /usr/local/go/src/net/http/transport.go:945 +0x41d
    created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:661 +0xcbc

    goroutine 11 [select]:
    github.com/olivere/elastic.(*Client).healthchecker(0xc208000ea0)
        /home/ubuntu/themuse/muselytics/src/muselytics/Godeps/_workspace/src/github.com/olivere/elastic/client.go:684 +0x1b3
    created by github.com/olivere/elastic.NewClient
        /home/ubuntu/themuse/muselytics/src/muselytics/Godeps/_workspace/src/github.com/olivere/elastic/client.go:219 +0x5d5
    exit status 2

**Comment by olivere** [comment]
Hi there. The issue is that Ping does not use the ES URL by default (contrary to all other services). I think [this comment](https://github.com/olivere/elastic/issues/86#issuecomment-112910510) explains the reasoning behind it. Let me know if that doesn't solve your problem. Cheers.

**Comment by ysimonson** [comment]
Makes sense, thanks @olivere
