### ISSUE TITLE
Index API using bulk thread at ES cluster

### ISSUE THREAD

**Issue by ishail** [olivere/elastic#901]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?
ES cluster: 6.2

Lib version: `v6.1.18`

[[projects]]
  name = "github.com/olivere/elastic"
  packages = [
    ".",
    "config",
    "uritemplates"
  ]
  revision = "4586a6964b5cb45a2dadd67577f83f00b1ec5029"
  version = "v6.1.18"

### Please describe the expected behavior
I'm using Index API to index documents into ES cluster.
`esClient.Index().Index(indexName).Type(docType).Id(docID).BodyJson(pref).Do(ctx)`
I think it should ideally use dedicated index thread from thread_pool.

### Please describe the actual behavior
When I checked from kibana(/_cat/thread_pool), I see bulk thread from thread_pool is being used. Is there any specific config I'll have to use?

**Comment by olivere** [comment]
I don't understand. AFAIC I see no way to control which thread pool ES is using internally just by invoking a REST endpoint. Or did I misunderstand the issue?

**Comment by olivere** [comment]
I don't think so. And I'd be surprised if you could, but I'm not into the specifics of ES. Elastic should only support the official REST API, no more and no less.
