### ISSUE TITLE
Go module doesn't pick the latest version

### ISSUE THREAD

**Issue by xitonix** [olivere/elastic#903]
Hi Oliver,

I am not actually sure if this is a bug in `go mod` or there is something specific to this repo's setup (or maybe this is the expected behaviour), but I thought maybe I consult it with you before I raise it with the Go team, if that's an issue. I'd appreciate it if you could shed some light on this please.

### Which version of Elastic are you using?

[X ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

I expect go module to go with the latest released version, which is v6.2.5 at the time

### Please describe the actual behaviour

For some reason go module picks `v6.1.25` instead and marks it as `incompatible`. 

Here is the entry in my `go.mod` file:
`github.com/olivere/elastic v6.1.25+incompatible`

Also, if I try to pin the dependency to the latest version by running `go get github.com/olivere/elastic@v6.2.5` this is how my `go.mod` gets updated:

`github.com/olivere/elastic v0.0.0-20180831175714-e6cae211ee80`

### Any steps to reproduce the behavior?

* Create a brand new repo outside of $GOPATH with the reference to `github.com/olivere/elastic` 
* Run `go mod init your_example_package`
* Run `go build`

**Comment by olivere** [comment]
I was an early adopter of Go modules for v6, but it has caused some pain (see #877). So I rolled it back and decided that v7 will be the first release to support Go modules.

Regarding the version selection mechanism: Thanks for reporting. I'm not exactly sure why Go 1.11 does this, really. I'd be more than happy if you could dig into it because I'm quite busy with my day job these days. Forcing the version number works though, as you already found out.

**Comment by xitonix** [comment]
Thanks mate. I will see what I can find.

**Comment by xitonix** [comment]
Hi Oliver. I did a bit of investigation and I believe the issue is cause by https://github.com/olivere/elastic/commit/66b430cdba34722e4a9656f651df616fe5f0503f . Basically, you removed the SEMver from the import path but you probably forgot to remove the `go.mod` file. That's why `go mod` thinks that it's a valid module which is not true. `v6.1.25` is basically the last release without the `go.mod` file and that's why `go build` stops there. Check out [this code](https://github.com/golang/vgo/blob/master/vendor/cmd/go/internal/modfetch/coderepo.go#L121) in the vgo repo please, which is basically the bit that filters out any versions above `v6.1.25`. 

Given that `go mod` is backward compatible, I believe removing `go.mod` and releasing a new tag will solve this problem, until you properly support go modules as planned for v7. 

I forked your repo and tested it out and it worked. Feel free to have a look plese: https://github.com/xitonix/elastic/releases

Thanks @johnnyluo for helping me to find the issue :)
