### ISSUE TITLE
The Aggregation and Sort function cannot take effect at the same time

### ISSUE THREAD

**Issue by Maybrittnelson** [olivere/elastic#907]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v6 (for Elasticsearch 6.x)
[x] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
The values returned after aggregation are sorted by sort
### Please describe the actual behavior
Aggregation takes effect, but sort fails(The @timestamp field mapping is good)
### Any steps to reproduce the behavior?
`{
    "query" : {
      "bool" : {
        "must" : [
          {
            "term" : {
                "kubernetes.container.name" : "plat-log-server"
            }
          }
        ],
        "filter": [
          {"range":{
            "@timestamp" : {
              "gte":"2018-09-13",
              "lte":"now"
            }
          }}
          ]
      }
    }
    ,"aggs": {
    "property_type": {
      "terms": {
        "field": "kubernetes.pod.name",
        "size":100
      }}},
      "sort": [
        {
          "@timestamp": {
            "order": "desc"
          }
        }
      ]
}
`

[Another solution](https://stackoverflow.com/questions/29016271/how-to-get-latest-values-for-each-group-with-an-elasticsearch-query#comment89692964_29017140)，that use [top_hits](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-top-hits-aggregation.html) also not good
`{
  "size":0,
    "query" : {
      "bool" : {
        "must" : [
          {
            "term" : {
                "kubernetes.container.name" : "plat-log-server"
            }
          }
        ],
        "filter": [
          {"range":{
            "@timestamp" : {
              "gte":"2018-09-13",
              "lte":"now"
            }
          }}
          ]
      }
    }
    ,"aggs": {
    "top_agg_hit": {
      "terms": {
        "field": "kubernetes.pod.name",
        "size":100
      },
      "aggs": {
        "top_agg_hit": {
          "top_hits": {
            "size": 1,
      "sort": [
        {
          "@timestamp": {
            "order": "desc"
          }
        }
      ]
          }
        }
      }
    }}
}`
I found a solution to sort using the sort field in the resp，but I don't think it's the optimal solution
![image](https://user-images.githubusercontent.com/20365012/45619881-7e8bcd80-baad-11e8-96b3-3a2a493d44fd.png)

why size=0
![image](https://user-images.githubusercontent.com/20365012/45618039-f1de1100-baa6-11e8-8cd0-bb8b2006b62b.png)

**Comment by olivere** [comment]
Just asking: You want the [aggregations to be sorted](https://www.elastic.co/guide/en/elasticsearch/reference/6.4/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-order), or the search results (aka `hits`)?

**Comment by olivere** [comment]
Sorting has at least [3 integration tests](https://github.com/olivere/elastic/blob/release-branch.v6/search_test.go#L243-L467), so I guess something's wrong with your code. Can you post a reproducible test case?

**Comment by Maybrittnelson** [comment]
I have some documents indexed on Elasticsearch, looking like these samples:
`{'country': 'France', 'collected': '2015-03-12', 'value': 20}
{'country': 'Canada', 'collected': '2015-03-12', 'value': 21}
{'country': 'Brazil', 'collected': '2015-03-12', 'value': 33}
{'country': 'France', 'collected': '2015-02-01', 'value': 10}
{'country': 'Canada', 'collected': '2015-02-01', 'value': 11}
{'country': 'Mexico', 'collected': '2015-02-01', 'value': 9}`

but after  [top_hits](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-top-hits-aggregation.html)，it result like this
`{'country': 'France', 'collected': '2015-03-12', 'value': 20}
{'country': 'Canada', 'collected': '2015-03-12', 'value': 21}
{'country': 'Mexico', 'collected': '2015-02-01', 'value': 9}
{'country': 'Brazil', 'collected': '2015-03-12', 'value': 33}`

I want it to look like this，The results should be sorted by the collected field.
`{'country': 'France', 'collected': '2015-03-12', 'value': 20}
{'country': 'Canada', 'collected': '2015-03-12', 'value': 21}
{'country': 'Brazil', 'collected': '2015-03-12', 'value': 33}
{'country': 'Mexico', 'collected': '2015-02-01', 'value': 9}
`

**Comment by Maybrittnelson** [comment]
> aka

also the search results that after [top_hits](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-top-hits-aggregation.html)，should be sorted by field

**Comment by Maybrittnelson** [comment]
> Just asking: You want the [aggregations to be sorted](https://www.elastic.co/guide/en/elasticsearch/reference/6.4/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-order), or the search results (aka `hits`)?

also the search results that after [top_hits](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-top-hits-aggregation.html)，should be sorted by field

**Comment by olivere** [comment]
I'm still not sure what you're trying to achieve. Sorting aggregations and search results works well, see [this gist](https://gist.github.com/olivere/050fc4313ad112fe536360e1e93ada1e). Can you modify the code and/or the data to produce a reproducible test case that illustrates your problem?

**Comment by olivere** [comment]
Oh, I see your comment just now. I will change the gist to reflect on your comment.

**Comment by olivere** [comment]
Still confused. But [this gist](https://gist.github.com/olivere/2e07531dac54c8ec4c4ea230a7b5eb91) is an example illustrating how sorting the aggs doesn't interfere with sorting the hits in any way. Maybe you can build on that.

**Comment by Maybrittnelson** [comment]
> Still confused. But [this gist](https://gist.github.com/olivere/2e07531dac54c8ec4c4ea230a7b5eb91) is an example illustrating how sorting the aggs doesn't interfere with sorting the hits in any way. Maybe you can build on that.

Thank you very much,I got the right result through your sample code.I guess the order parameter in Terms Aggregation plays a role.So I still have a question as to why Max Aggregation can be ordered, but Top hits Aggregation can't be ordered?
![image](https://user-images.githubusercontent.com/20365012/45661897-23e88500-bb32-11e8-8076-e03930eac01c.png)
![image](https://user-images.githubusercontent.com/20365012/45661988-7cb81d80-bb32-11e8-9a63-365399d61795.png)

**Comment by olivere** [comment]
It's in the error message:

> Buckets can only be sorted on a sub-aggregator path that is built out of zero or more single-bucket aggregations within the path and a final single-bucket or a metrics aggregation at the path end. Sub-path [last_collected] points to non single-bucket aggregation.

So the `top_hits` aggregation, even though returning just one document, seems to be considered as a multi-bucket aggregation.

From [the docs](https://www.elastic.co/guide/en/elasticsearch/reference/6.4/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-order):

> It is also possible to order the buckets based on a "deeper" aggregation in the hierarchy. This is supported as long as the aggregations path are of a single-bucket type, where the last aggregation in the path may either be a single-bucket one or a metrics one.

These kinds of aggregation and sorting also seems to be rather expensive.
