### ISSUE TITLE
Several Aggregation struct member functions fail to take instance by reference

### ISSUE THREAD

**Issue by autochthe** [olivere/elastic#91]
Several Aggregation structs improperly take and pass the current instance by *value* instead of scope.  I didn't realize this, but declaring the first example below passes in a by value, while the second example passes in a by reference!

```
func (a AvgAggregation) Field(field string) AvgAggregation {
       a.field = field
       return a
}

func (a *AvgAggregation) Field(field string) *AvgAggregation {
       a.field = field
       return a
}
```
In the first form, the value of field is never seen by the calling instance, while in the second form, the field value is properly updated.

This error is pervasive throughout the FooAggregation struct definitions.

**Comment by olivere** [comment]
Thanks for reporting. I'd prefer to have them as pointers in the aftermath. However, this is a breaking change, which I want to prevent if possible. Can you elaborate why this is a problem for you? It works fine with value types ([example](http://play.golang.org/p/SDFYBh6SHR)).

**Comment by autochthe** [comment]
So you are right.  This is not what is actually causing the bug that I am seeing, which is that the json Marshaller [can't handle unexported types](http://stackoverflow.com/a/11129474), which was causing problems with the `rangeAggregationEntry` type when unmarshalling a `RangeAggregation`.  I will close this issue for now and open a proper issue for this problem.
