### ISSUE TITLE
Chinese highlighting issues

### ISSUE THREAD

**Issue by Maybrittnelson** [olivere/elastic#910]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v6 (for Elasticsearch 6.x)
[x ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
First i set the parameter `default_operator ` in `Simple Query String Query` to be equal to `and`，So when I set keyword as a phrase, it doesn't return the words in the phrase as query results.
eg: my keywords is `拼车`，the result is only `拼车车`, no more `车` `拼`。
but highlighting does't work like the above，the result is `<tag>拼车</tag><tag>车</tag>`，I hope result is `<tag>拼车</tag>车`
### Any steps to reproduce the behavior?
![image](https://user-images.githubusercontent.com/20365012/45749544-87f86f80-bc3e-11e8-88b9-d0cb2c0fb554.png)

**Comment by olivere** [comment]
Did you tokenize the fields with a Chinese analyzer, e.g. 
https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-smartcn.htm?

I think this is a general Elasticsearch question, not related to the Go client. Maybe you should ask on discuss.elastic.co?!

**Comment by Maybrittnelson** [comment]
today, i get it。[Simple Query String Syntax](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/query-dsl-simple-query-string-query.html#_simple_query_string_syntax)，" wraps a number of tokens to signify a phrase for searching。
