### ISSUE TITLE
Query with range expression

### ISSUE THREAD

**Issue by nikhil133** [olivere/elastic#913]
how can I implement query with range expression in golang
where condition of range are as follow
gte: greater than or equal to
lte : less than or equal to
gt: greater than
lt: less than
on specific index
in elastic search v6

Query I constructed
`{
    "query": {
        "range" : {
            "amount" : {
                "gte" : 5000
             }
        }
    }
}`

expected behaviour 
It should hit every document having amount greater than or equal to 5000

Please revert with an example

**Comment by olivere** [comment]
```
q := elastic.NewRangeQuery("amount").Gte(5000.0)
```

See https://github.com/olivere/elastic/blob/release-branch.v6/search_queries_range.go#L44-L50
