### ISSUE TITLE
BulkProcessor handling of 503 (ServiceUnavailable) status code

### ISSUE THREAD

**Issue by rwynn** [olivere/elastic#914]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[X ] elastic.v6 (for Elasticsearch 6.x)
[X ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

Requeue any 503 status lines since this means that the server was not available to process them at request time.  This ensures that they are not lost.

### Please describe the actual behavior

Currently, the bulk processor requeues lines with status 429 (too many requests), but in negative testing by bringing down the Elasticsearch server I've seen failures with status code 503 (Service Unavailable).  If might be nice to also requeue code 503 so that if Elasticsearch comes back up these lines will not be lost.

### Any steps to reproduce the behavior?
Run a workload on the bulk processor and then bring down Elasticsearch.  Observer that some requests may fail with lines failures indicating a status of 503.  These lines will not be retried since the overall request actually finished without error.  

This may be as simple as adding to the list of status codes.

```
if result.Status == 429 || result.Status == 503 { // too many requests or service unavailable
							w.service.Add(reqs[i])
						}
```

**Comment by olivere** [comment]
I'd prefer a more general solution. Either we pass a list of status codes directly as a configuration parameter into `BulkProcessor`, or we use a specific `Retrier` to work around this. You can try the latter today, simply implementing a `Retrier` that retries HTTP requests on the given status codes.

**Comment by rwynn** [comment]
Hi @olivere 

I think the problem with using a `Retrier` is that the retry only happens on an error.  And in this case you don't have an error.  You have a bulk request completing with nil error from service `Do`...

https://github.com/olivere/elastic/blob/release-branch.v6/bulk.go#L271

But then you have line items in the response that indicate that the line item was not committed.  So we actually would need the commit function...

https://github.com/olivere/elastic/blob/release-branch.v6/bulk_processor.go#L501

To reach into those line items and return some sort of error from the commit function indicating that not all of them committed for the `Retrier` to be activated.

https://github.com/olivere/elastic/blob/release-branch.v6/bulk_processor.go#L544

At least that's how I read the current code.

**Comment by rwynn** [comment]
Maybe what we need is some sort of interface that can be set on the BulkProcessor which is consulted in the `commitFunc` to evaluate the response line items to elevate the overall response to an error even though none was reported by service `Do`.  

Also this interface would need to be able to provide status codes that need to be re-queued (such as 429 and 503) since that information will be needed by the `commitFunc`.

**Comment by olivere** [comment]
Well, the Bulk Processor's `Do` func will report errors if Elasticsearch will report errors. Not trying to nitpick but it's consistent in its behavior.

Having said that, I understand your point. And maybe we should simply add 503 as just another kind of error that we should retry. The reason I'm hesistant with simply retrying errors it that I don't want Bulk Processor drift into muddy waters, trying different obscure things to force push data into Elasticsearch, while the right thing would be do "just ask the caller."

Would adding the given requests with an [`afterFunc`](https://github.com/olivere/elastic/blob/release-branch.v6/bulk_processor.go#L552) work?

**Comment by rwynn** [comment]
I tried to put together a generic solution in https://github.com/rwynn/elastic/commit/97857e6ee7981d617f0d770a43ba1ee908f85b5f

I think it’s pretty clear and simple.  The response line items need to be checked because a certain set may be retryable errors than need to be kept in the service for delivery. 

Besides re-queuing the commit also now returns an error in the presence of retryable line items to trigger the Retrier.

**Comment by olivere** [comment]
First of all: I'm really not trying to discourage you in any way. I think we have the same goal: To strive for a clean and simple solution.

The problem I see with `StatusChecker` is that we now introduce a third "thing" that does something like checking for errors and retry. First, we have `BeforeFunc` and `AfterFunc`, then we have `Retrier`, and now we get `StatusChecker`. When do I use what, and why? You see: It makes things even more complex, not simpler.

E.g. what can `StatusChecker` do that `AfterFunc` can't? If `AfterFunc` doesn't work, can't we reuse the existing `Retrier` in any way?

**Comment by rwynn** [comment]
One difference is AfterFunc cannot cause RetryNotify to retry the request. RetryNotify only retries with backoff if the commitFunc returns a non nil error.  commitFunc only returns a non-nil error for line items with the attached PR. 

AfterFunc would need to manually retry the request but that’s already the job of RetryNotify. 

Also AfterFunc does not have a pointer to the service. So it cannot re-queue line items. 

Each of these things has distinct jobs. StatusChecker determines if a status code is retriable.  RetryNotify does the actual retry. And Backoff tells RetryNotify when to stop retrying. 

StatusChecker could be a slice of codes but not as nice as an interface in my opinion. 

Sorry I don’t mean to be difficult. I just think that it’s a small change that ensures line items are not dropped and not all library users need to handle same case in an AfterFunc.

**Comment by rwynn** [comment]
To answer “when do I use that and why” for StatusChecker. Normally you don’t use it. The default should have all the retryable status codes. But in the event that a new status is introduced you could supply your own checker. Or maybe you disagree with the default codes. A more general solution.

**Comment by rwynn** [comment]
You asked if we can use the existing Retrier here. I don’t think a Retrier is useful at all here. Retriers in elastic are only triggered when a request returns an error or a status code outside the range defined in errors.go. In this case this is a bulk request that Elasticsearch is responding to with a success 200 code but the response has line items that have soft failed (not committed). So a Retrier is not consulted.

**Comment by rwynn** [comment]
For example, this link shows what we are dealing with for Bulk and why a Retrier on the client would not be used by elastic in this scenario. 

https://github.com/elastic/libbeat/issues/192

**Comment by olivere** [comment]
I'd favour a simple additional parameter, e.g. `RetryItemStatusCodes []int` for `BulkProcessor` that lists the status codes for which individual items should be re-enqueued, even if the request as a whole was successful.

I should've never added `BulkProcessor` to the core library in the first place. Its usage patterns are simply too specific for a general approach.

**Comment by olivere** [comment]
Will probably change a few bits I'm not certain about, but that won't change the approach.

I apologize for maybe being a bit rude around this issue.

**Comment by rwynn** [comment]
No problem. I have a little experience at how onerous it can be to answer the barrage of issues and PRs that come in.  I try to submit PRs to lessen the burden but it can be hard when design is involved.  I’m sure you’ve spent loads of time crafting this. 

You’ve done a great job with this client.  The breadth of it is pretty amazing.
