### ISSUE TITLE
Field Capabilities not implemented correctly

### ISSUE THREAD

**Issue by seanlaff** [olivere/elastic#915]
### Which version of Elastic are you using?

[x ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

The response format for this elasticsearch endpoint is https://www.elastic.co/guide/en/elasticsearch/reference/5.4/search-field-caps.html
```json
{
    "fields": {
        "rating": { 
            "long": {
                "searchable": true,
                "aggregatable": false,
                "indices": ["index1", "index2"],
                "non_aggregatable_indices": ["index1"] 
            },
            "keyword": {
                "searchable": false,
                "aggregatable": true,
                "indices": ["index3", "index4"],
                "non_searchable_indices": ["index4"] 
            }
        },
        "title": { 
            "text": {
                "searchable": true,
                "aggregatable": false

            }
        }
    }
}
```

In this library, the response is marshalled to `FieldCapsResponse`

https://github.com/olivere/elastic/blob/18b71235c09c127a0138e941e99524b93687898b/field_caps.go#L171-L176

However `FieldCapsResponse` is not aware of that the field caps are nested "within" a key describing the type.
https://github.com/olivere/elastic/blob/18b71235c09c127a0138e941e99524b93687898b/field_caps.go#L190-L192

 For example, in the above response look at the "rating" field.  The caps for that field ("searchable", "aggregatable", etc) are nested under `long`, but this library expects them to be nested directly under `rating`.

Its a silent failure because the marshaling doesn't fail, you'll just get back zero values for `aggregatable`, `searchable`, etc.

**Comment by olivere** [comment]
Okay, I wasn't aware of this. As the response structures are only vaguely documented (not being part of the REST API), these things happen. I'm sorry about that. I will have to reengineer from the Java source.
