### ISSUE TITLE
BulkUpdateRequest's stringified json doc behavior differs from BulkIndexRequest's

### ISSUE THREAD

**Issue by seanlaff** [olivere/elastic#923]
### Which version of Elastic are you using?

[ x ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

`BulkIndexRequest` has type assertion that allows you to pass a document as a string, which is quite handy
https://github.com/olivere/elastic/blob/bd115a1132ece51519151c33b5d74e1387d3265a/bulk_index_request.go#L216-L235
However `BulkUpdateRequest` is missing that switch statement, so when passed a json string, it double marshals it. The resulting string ends up with escaped double quotes, for example:

```
{"doc":"{\"test\":{\"name\":\"testing123\",\"metricId\":\"9f5e5a4d94a8d13fb8b0539d9a4524ab688eea8384a8661461f801c551d110cb\"}}","doc_as_upsert":true}
```

Causing ElasticSearch to error with something like this 
```
Document failure during bulk processing: &{mapper_parsing_exception failed to parse     false map[type:not_x_content_exception reason:not_x_content_exception: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes] [] []}"
```

**Comment by seanlaff** [comment]
Actually, since `Doc()` takes an `interface{}`, I can turn my string into a `json.RawMessage` and it all works good!

**Comment by olivere** [comment]
Okay. I see, I'll fix it in the next release.
