### ISSUE TITLE
Help using Elastic on AWS.

### ISSUE THREAD

**Issue by jacklaaa89** [olivere/elastic#924]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
When performing an index operation on AWS ES, I always get a parse error in the form:
```{"error":{"root_cause":[{"type":"parse_exception","reason":"request body is required"}],"type":"parse_exception","reason":"request body is required"},"status":400}```

### Any steps to reproduce the behavior?
my request looks as follows:
```
'PUT' /search_index/result/expense%3A11f9bce1-0332-4148-b8c3-1e922bb48f53?version=39704&version_type=external HTTP/1.1
2018-10-03 16:35:02
Host: vpc-test-es-domain-ryqxvbzhdpbob33haoksj3b3pi.eu-west-1.es.amazonaws.com 
User-Agent: elastic/6.2.8 (linux-amd64)
Transfer-Encoding: chunked
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip

126
{"company_id":"2d94096d-672c-4fc2-8fd3-fd84d3433069","user_id":"9178607f-e4a4-41f1-b997-c9a54c15ed4d","raw_document":"gah1c2VybmFtZbVqYWNrdGltYmxpbkBnbWFpbC5jb20=","terms":["1, 3, 4","jack"],"type":"user","uuid":"9178607f-e4a4-41f1-b997-c9a54c15ed4d","created":"2018-10-03T15:46:17.771929391Z"}
0
```
My code looks like:
```
client.Index().Index(es.IndexResult).
		Type(DocumentTypeResult).
		Version(int64(r.GetVersion())).
		VersionType(externalVersionType).
		Id(doc.Id()).
		BodyJson(doc).
		Do(ctx)
```

**Comment by jacklaaa89** [comment]
I fixed the issue using the official AWS SDK for Go. Basically the signer in your current implementation always provides `nil` as the body, so `HEAD`, `GET` etc (requests with no body) work correctly, however `POST`, `PUT` etc (requests with a body) do not work as they were not being used as part of the signer.

I fixed it by updating your AWS v4 signing code to include:
```
// RoundTrip uses the underlying RoundTripper transport, but signs request first with AWS V4 Signing
func (st V4Transport) RoundTrip(req *http.Request) (*http.Response, error) {
	var body io.ReadSeeker = nil
	if req.Body != nil {
		d, err := ioutil.ReadAll(req.Body)
		if err != nil {
			return nil, err
		}

		body = bytes.NewReader(d)
	}

	_, err := st.signer.Sign(req, body, "es", st.region, time.Now())
	if err != nil {
		return nil, err
	}
	return st.client.Do(req)
}
```

It has to be read first as AWS uses a `io.ReadSeeker` to build the hash, but it replaces the `req.Body` after generating the hash from it.

**Comment by olivere** [comment]
Oh, okay. I'll have to fix that. Thanks for reporting.

**Comment by olivere** [comment]
Have to delay it until 6.2.10. I need further testing on a live cluster on AWS.
