### ISSUE TITLE
Skipping the unwanted field in Elasticsearch results

### ISSUE THREAD

**Issue by orangemail** [olivere/elastic#926]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior.

As a part of my elasticsearch Im getting entire structure as json.

type SearchHit struct {
    Score          *float64                       `json:"_score"`          // computed score
    Index          string                         `json:"_index"`          // index name
    Type           string                         `json:"_type"`           // type meta field
    Id             string                         `json:"_id"`             // external or internal
    Uid            string                         `json:"_uid"`            // uid meta field (see MapperService.java for all meta fields)
    Routing        string                         `json:"_routing"`        // routing meta field
    Parent         string                         `json:"_parent"`         // parent meta field
    Version        *int64                         `json:"_version"`        // version number, when Version is set to true in SearchService
    Sort           []interface{}                  `json:"sort"`            // sort information
    Highlight      SearchHitHighlight             `json:"highlight"`       // highlighter information
    Source         *json.RawMessage               `json:"_source"`         // stored document source
    Fields         map[string]interface{}         `json:"fields"`          // returned (stored) fields
    Explanation    *SearchExplanation             `json:"_explanation"`    // explains how the score was computed
    MatchedQueries []string                       `json:"matched_queries"` // matched queries
    InnerHits      map[string]*SearchHitInnerHits `json:"inner_hits"`      // inner hits with ES >= 1.5.0
    Nested         *NestedHit                     `json:"_nested"`         // for nested inner hits

}

I need only following in Json 

Index          string                         `json:"_index"`          // index name
Id             string                         `json:"_id"`             // external or internal
Source         *json.RawMessage               `json:"_source"`         // stored document source

I.e 

I'm performing the search like given below.

fetchContext := elastic.NewFetchSourceContext(true).Include("date")

    res, err := client.Search().
            Index("xxxx").
            Query(query).
            FilterPath(
                    "hits.total",
                    "hits.hits._id",
                    "hits.hits._source",
                    "hits.hits._index",
            ).
            FetchSourceContext(fetchContext).
            Pretty(true).
            From(0).Size(1).
            Do(ctx)
Then

hit, err := json.Marshal(res.Hits.Hits)
if err != nil {

            fmt.Printf("Error:%s\n", err)
    } else {
            fmt.Println(string(hit))
    }
this prints outcome as

[{"_score":null,"_index":"xxxx","_type":"","_id":"yyyy","_uid":"","_routing":"","_parent":"","_version":null,"sort":null,"highlight":null,"_source":{"date":1.529907000446799E9},"fields":null,"_explanation":null,"matched_queries":null,"inner_hits":null,"_nested":null}]

But I need only :

_index
_id
_source

**Comment by orangemail** [comment]
I was able to exclude fields inside" _source" field but is there a way to skip the fields like "_score" and "_explanation" field ?

**Comment by olivere** [comment]
If you don’t want an explanation from e.g. the Search API, use Explain(false). But that’s the default. As I said: I don’t think ES sends this; it’s just serialised by Go as such because omitempty is missing.

**Comment by orangemail** [comment]
Hi. Thank you so much for response. 


I have tried as you suggested. I tried Explain(false) like given below.

res, err := client.Search().
        Index("xxxx").
        Query(query).
        Explain(false).
        FilterPath(
                "hits.total",
                "hits.hits._id",
                "hits.hits._source",
                "hits.hits._index",
        ).
        FetchSourceContext(fetchContext).
        Pretty(true).
        From(0).Size(1).
        Do(ctx)

I didn't work out for me. Still same response.

You have mentioned "it’s just serialised by Go as such because omitempty is missing" . Is there a way to skip this empty fields ?

**Comment by orangemail** [comment]
By adding the changes to existing structure, I was able to make the changes.

// SearchHit is a single hit.
type SearchHit struct {
        Score          *float64                       `json:"_score,omitempty"`          // computed score
        Index          string                         `json:"_index,omitempty"`          // index name
        Type           string                         `json:"_type,omitempty"`           // type meta field
        Id             string                         `json:"_id,omitempty"`             // external or internal
        Uid            string                         `json:"_uid,omitempty"`            // uid meta field (see MapperService.java for all meta fields)
        Routing        string                         `json:"_routing,omitempty"`        // routing meta field
        Parent         string                         `json:"_parent,omitempty"`         // parent meta field
        Version        *int64                         `json:"_version,omitempty"`        // version number, when Version is set to true in SearchService
        Sort           []interface{}                  `json:"sort,omitempty"`            // sort information
        Highlight      SearchHitHighlight             `json:"highlight,omitempty"`       // highlighter information
        Source         *json.RawMessage               `json:"_source,omitempty"`         // stored document source
        Fields         map[string]interface{}         `json:"fields,omitempty"`          // returned (stored) fields
        Explanation    *SearchExplanation             `json:"_explanation,omitempty"`    // explains how the score was computed
        MatchedQueries []string                       `json:"matched_queries,omitempty"` // matched queries
        InnerHits      map[string]*SearchHitInnerHits `json:"inner_hits,omitempty"`      // inner hits with ES >= 1.5.0
        Nested         *NestedHit                     `json:"_nested,omitempty"`

        // Shard
        // HighlightFields
        // SortValues
        // MatchedFilters
}
I followed you thread given below.

https://github.com/olivere/elastic/issues/927. 

But actually I'm relying on  elastic.v6 (for Elasticsearch 6.x). Can you push this optional field as patch in version 6.0 official code ?

**Comment by olivere** [comment]
Completed in ee9b5933b11cc4757471bef4a4638f1cdcee170c.
