### ISSUE TITLE
Can't use struct in unmarshal

### ISSUE THREAD

**Issue by MonaxGT** [olivere/elastic#928]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[*] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

searchResult return object, which have been unmarshaling in struct with success. I create struct like 

```
type Jsonresponse struct {
	Index   string      `json:"_index,omitempty"`
	Type    string      `json:"_type,omitempty"`
	ID      string      `json:"_id,omitempty"`
	Version int         `json:"_version,omitempty"`
	Score   interface{} `json:"_score,omitempty"`
	Source  struct {
		EventID   int    `json:"event_id"`
		Message   string `json:"message"`
		Version   string `json:"@version"`
}
}
```

and then
```
if searchResult.Hits.TotalHits > 0 {
		fmt.Printf("Found a total of %d tweets\n", searchResult.Hits.TotalHits)
		for _, hit := range searchResult.Hits.Hits {
			// Deserialize hit.Source into a Tweet (could also be just a map[string]interface{}).
			var t Jsonresponse
			err := json.Unmarshal(*hit.Source, &t)
			if err != nil {
				fmt.Println("There was an error:", err)
			}
			fmt.Println(t.Source.Message,t.Source.HostID, t.Source.EventData.EventName)
		}
	} else {
		// No hits
		fmt.Print("Found no tweets\n")
	}
```
I want to see values of keys

### Please describe the actual behavior

As writing above, i try take values, but i get only null data.
```
Query took 7 milliseconds
Found a total of 10801 tweets
  
map[]
  
map[]
  
map[]
.......
```
If i use `map[string]interface{}` in `err := json.Unmarshal(*hit.Source, &t)`, i see the message, but it is not convenient for me

### Any steps to reproduce the behavior?

Log in elasticsearch
```
{
  "_index": "log-win",
  "_type": "doc",
  "_id": "hD84P2YBrtYvt1Xjl_VU",
  "_version": 1,
  "_score": null,
  "_source": {
   "message": "Process Create:\nRuleName: \nUtcTime:",
    "@version": "1",
    "event_id": 1
}
}
```

**Comment by olivere** [comment]
You only deserialize the `Source`, not the whole response from Elasticsearch. So your `Jsonresponse` should be:

```
type Jsonresponse struct {
	EventID   int    `json:"event_id"`
	Message   string `json:"message"`
	Version   string `json:"@version"`
}
```
