### ISSUE TITLE
Sort Query

### ISSUE THREAD

**Issue by nikhil133** [olivere/elastic#930]
[ ] elastic.v6 (for Elasticsearch 6.x)

how to achieve this query using golang

```
{
    "query" : {
        "bool" : {
            "filter" : {
                "term" : {
                    "phone" : "1234567890"
                }
            }
        }
    },
    "sort" : {
        "uts": {"order": "desc",               
                "mode":"max" 
               }
    },
  "size":1
}

```
This query helps me to get latest phone detail of 1234567890 according to timestamp

**Comment by olivere** [comment]
Something like this should do the job (untested):

```
query := elastic.NewBoolQuery().
	Filter(elastic.NewTermQuery("phone", "123"))
res, err := client.Search().
	Index(testIndexName).
	Query(query).
	SortBy(elastic.NewFieldSort("uts").Desc().SortMode("max")).
	Size(100).
	Pretty(true).
	Do(context.Background())
```

Please read the docs, the tests, and the wiki, e.g. [`search_test.go`](https://github.com/olivere/elastic/blob/release-branch.v6/search_test.go) and [`sort_test.go`](https://github.com/olivere/elastic/blob/release-branch.v6/sort_test.go).

**Comment by nikhil133** [comment]
I did figured out.
I used NewMatchQuery("phone")
And used in search query with sortby.
Thanks for your help, It's apriciated
