### ISSUE TITLE
I can't configure the full example to work wih ELK stack

### ISSUE THREAD

**Issue by ngrigoraki** [olivere/elastic#937]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
Display results in kibana

### Please describe the actual behavior
Hello Oliver! Thanks a lot for the code and all the help you provide us. 
I'm a newbie to all of this and I'm trying to make your client working with ELK Stack.

### Any steps to reproduce the behavior?
I followed [these](https://logz.io/blog/elk-mac/) instructions and set up the ELK Stack on my Mac.
Then I run the executable (of your [example](https://olivere.github.io/elastic/)) and although I get results in the output, I don't see them into kibana:

Output:
-----------------------
```
Elasticsearch returned with code 200 and version 6.4.2
Elasticsearch version 6.4.2
Index exists false
Indexed tweet 1 to index twitter, type tweet
Indexed tweet 2 to index twitter, type tweet
Got document 1 in version 842350562816 from index twitter, type tweet
Query took 12 milliseconds
Tweet by olivere: Take Five
Tweet by olivere: It's a Raggy Waltz
Found a total of 2 tweets
Found a total of 2 tweets
Tweet by olivere: Take Five
Tweet by olivere: It's a Raggy Waltz
New version of tweet "1" is now 2
```

What am I doing wrong? 
Is there any other configuration I have to do?
Any other ideas, please?

Thanks in advance.

P.S. It' not an issue but I really need help.

**Comment by olivere** [comment]
The output of the example code does in fact show that you succeeded in reading/writing data into Elasticsearch. However, the example code also does remove the data at the end, so it seems clear that you don't see the data in Kibana.

If you remove the last lines in the example code and NOT delete the index, you should be able to see the data in Kibana. Use the DevTools at (something like) http://<your-kibana-host>/app/kibana#/dev_tools?_g=() and use a query like `GET /twitter/_search`. That should print some data.

The friendly folks over the at [discuss.elastic.co](https://discuss.elastic.co) have a forum for you. They have the resources to help you through your first steps with Elasticsearch, regardless of the programming language and platform.

**Comment by ngrigoraki** [comment]
OMG! 
I never saw the line that deletes the index! I'm really sorry!
I would be trying for ages to make it work! 

Thank you Oliver! 
You are my guy! :)
