### ISSUE TITLE
Incorrect time passed in aws_v4 signer

### ISSUE THREAD

**Issue by fndradmin** [olivere/elastic#938]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

I provisioned an AWS Elasticsearch domain and tried using the AWS v4 signer but was always getting 403 on all requests. With the same setup python and curl with signing worked. Found that the time being passed in aws_v4.go in signing request is incorrect:

`_, err := st.signer.Sign(req, body, "es", st.region, time.Unix(0, 0))`

### Please describe the actual behavior

It should be:

`_, err := st.signer.Sign(req, body, "es", st.region, time.Now())`

After making this change locally things worked fine.

### Any steps to reproduce the behavior?

Need to setup ES in AWS and try interacting with it.

**Comment by olivere** [comment]
Fixed in b081362bf578a51367a27ca4d4bb5f7997a15b2c.
