### ISSUE TITLE
Build failed 

### ISSUE THREAD

**Issue by AhmedAbdraboh** [olivere/elastic#942]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
the elastic package should be built

### Please describe the actual behavior
go build github.com/olivere/elastic/uritemplates: no Go files in

### Any steps to reproduce the behavior?
build the latest version of the package

**Comment by AhmedAbdraboh** [comment]
I am using all elastic functionalities in a separate package(es.go for example) in my project then when I use 
go get -u es 
it updates the es package and updates all packages inside it including github.com/olivere/elastic
which in turn produces this error

**Comment by olivere** [comment]
You shouldn't do that. This works fine and will get all required dependencies, e.g. `github.com/olivere/elastic/uritemplates`:

```
$ go get -u github.com/olivere/elastic
```
