### ISSUE TITLE
Setting Shards for an index

### ISSUE THREAD

**Issue by nikhil133** [olivere/elastic#945]
[ ] elastic.v6 (for Elasticsearch 6.x)
How to set shards to 0 from default 5

**Comment by olivere** [comment]
You can either set the number of shards at [creation time](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html) ([example code](https://github.com/olivere/elastic/blob/release-branch.v6/recipes/mapping/mapping.go)) or later via [Update Indices Settings API](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-update-settings.html) ([example code](https://github.com/olivere/elastic/blob/release-branch.v6/indices_put_settings_test.go#L47-L63)).
