### ISSUE TITLE
How to use Bulk API to index 1k docs 

### ISSUE THREAD

**Issue by thuandoan274** [olivere/elastic#946]
### Which version of Elastic are you using?

[x ] elastic.v6 (for Elasticsearch 6.x)
I have more than 1000 reviews which I want to index to ES, so I use Bulk 
I split array to each array has 300 reviews in divided
``` golang
for _, groupIndexs := range divided {
    p := Client.Bulk().Index(NameIndexReview).Type(typeReview)
    for _, indexReview := range groupIndexs {
        indexReview.AssignHashtagsIndex()
        request := elastic.
            NewBulkIndexRequest().
            Id(indexReview.ID.Hex()).
            Doc(indexReview)
        p.Add(request)
    }
    p.Do(context.Background())
}
```
But It only index 300, 400 docs

**Comment by olivere** [comment]
There's many things that could go wrong here, and you're not checking any errors returned. So nobody knows for sure. There might even be no error but just a slight delay before the new documents are visible to the index reader. Also, you're reusing the loop iterator variable in the inner loop which [might pose a problem in certain circumstances](https://github.com/golang/go/wiki/CommonMistakes#using-goroutines-on-loop-iterator-variables).

Here's a [recipe](https://github.com/olivere/elastic/blob/release-branch.v6/recipes/bulk_insert/bulk_insert.go) for doing bulk inserts in parallel. Maybe you can find some inspiration from that.
