### ISSUE TITLE
Multi Search with Raw query

### ISSUE THREAD

**Issue by johndpknt** [olivere/elastic#947]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Any steps to reproduce the behavior?

Hello Team, 

I am a newbie to golang. Trying to implement elasticsearch's msearch functionality on golang.

below is my code:

               url : = "https://example.com:9200"
		client, err := elastic.NewClient(elastic.SetURL(url),
			elastic.SetScheme("https"),
			elastic.SetSniff(false),
		)
		if err != nil {
			fmt.Println("THis is panic case")
			panic(err)
		}

		s := `{
			"query": {
			  "bool": {
				"must": {
				  "terms": {
					"lang_code": [
					  "hi"
					]
				  }
				},
				"must_not": {
				  "term": {
					"search_tags": "hot"
				  }
				},
				"filter": {
				  "range": {
					"moderation_level": {
					  "gte": 2
					}
				  }
				}
			  }
			},
			"from": 0,
			"size": 10,
			"sort": {
			  "created_date": {
				"order": "desc"
			  }
			}
		  }\n{
			"query": {
			  "bool": {
				"must": {
				  "terms": {
					"lang_code": [
					  "en"
					]
				  }
				},
				"filter": {
				  "range": {
					"moderation_level": {
					  "gte": 2
					}
				  }
				}
			  }
			},
			"from": 0,
			"size": 10,
			"sort": {
			  "created_date": {
				"order": "desc"
			  }
			}
		  }\n`
		//ctx := context.Background()
		res, err := client.Search().Source(s).Do(c)

I am passing two query with \n separated but getting results for only first query.

Please help ?

**Comment by olivere** [comment]
Please see the tests in 
https://github.com/olivere/elastic/blob/release-branch.v6/msearch_test.go. It should help you succeed.
