### ISSUE TITLE
"nested_path" and "nested_filter" are deprecated since 6.1

### ISSUE THREAD

**Issue by avsima** [olivere/elastic#951]
Hello.
It says in the official documentation that "nested_path" and "nested_filter" in the "Sort" section are deprecated in the latest versions of elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#nested-sorting

### Which version of Elastic are you using?
[x] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
"path" and "filter" should be used instead of "nested_path" and "nested_filter" in the "Sort" section.

### Please describe the actual behavior
"nested_path" and "nested_filter" is used in the "Sort" section.

### Any steps to reproduce the behavior?
Try to use the nested sort with the 6.1 version of elasticsearch. There will be the next messages in a log:

Warning: 299 Elasticsearch-6.2.4-ccec39f "[nested_path] has been deprecated in favor of the [nested] parameter" "Tue, 30 Oct 2018 03:57:48 GMT"
Warning: 299 Elasticsearch-6.2.4-ccec39f "[nested_filter] has been deprecated in favour for the [nested] parameter" "Tue, 30 Oct 2018 03:57:48 GMT"

**Comment by olivere** [comment]
Thanks for reporting. I will have to look into this.

**Comment by olivere** [comment]
This will be fixed in 6.2.12 and later. However, I will keep the `NestedFilter`, `NestedPath` and `NestedSort` for compatibility issues. If you want to get rid of the deprecation warnings, use `Filter`, `Path` and `Nested` instead.

**Comment by avsima** [comment]
Thank you.

**Comment by yudidi** [comment]
https://github.com/olivere/elastic/issues/951#issuecomment-435574960
```
If you want to get rid of the deprecation warnings, use Filter, Path and Nested instead.
```
Did you mean Use `Filter` to replace `NestedFilter` directly? But it doesn't work, and I get error msg like 
```
{"error":{"root_cause":[{"type":"x_content_parse_exception","reason":"[1:1085] [field_sort] unknown field [filter], parser not found"}],"type":"x_content_parse_exception","reason":"[1:1085] [field_sort] unknown field [filter], parser not found"},"status":400}
```

* GOOD:
```
 "sort": [
    {
      "activity_info.order": {
        "nested_filter": {
          "term": {
            "activity_info.id": 39737
          }
        },
        "nested_path": "activity_info",
        "order": "desc"
      }
    }
  ]
```

* Bad:
```
  "sort": [
    {
      "activity_info.order": {
        "filter": {
          "term": {
            "activity_info.id": 39737
          }
        },
        "order": "desc",
        "path": "activity_info"
      }
    }
  ]
```
