### ISSUE TITLE
NewMatchQuery and NewCommonTermsQuery acts different when using same CutoffFrequency

### ISSUE THREAD

**Issue by david30907d** [olivere/elastic#958]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

- [x] elastic.v6 (for Elasticsearch 6.x)
### Please describe the expected behavior

i've read these two doc and persumed that these function would have the same results when setting cutofffrequency
* <https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-common-terms-query.html>
* <>https://www.elastic.co/guide/en/elasticsearch/reference/6.2/query-dsl-match-query.html

### Please describe the actual behavior

maybe they should behave in the same way?

### Any steps to reproduce the behavior?

you can check whether these two query return the same results

* `elastic.NewMatchQuery(field, query).Analyzer("some_analyzer").CutoffFrequency(0.0001)`
* `elastic.NewCommonTermsQuery(field, query).Analyzer("some_analyzer").CutoffFrequency(0.0001)`
<https://github.com/olivere/elastic/blob/release-branch.v6/search_queries_common_terms.go#L102>
<https://github.com/olivere/elastic/blob/release-branch.v6/search_queries_match.go#L179>

**Comment by olivere** [comment]
The PR is merged, thank you!

From the client perspective, I think it shouldn't care if two different queries now return the same results. If there are two APIs/DSLs that do the same, the client should have them, unless they've been deprecated.

**Comment by david30907d** [comment]
@olivere  thanks, it's my pleasure to have a commit in this repo.

Sorry but i still have an unrelated and newbie question:

1. `minimum_should_match` in `match query` means high frequency minimum_should_match or low frequency?
2. `operator` in `match query` means high frequency operator or low frequency

That is, this Match Qeury

```
GET /_search
{
    "query": {
        "match": {
            "body": {
                "query": "nelly the elephant as a cartoon",
                "cutoff_frequency": 0.001,
                "minimum_should_match": 2,
                "operator": "or"
            }
        }
    }
}
```

Is it  roughly equivalent to the DSL below or not ?

```
GET /_search
{
    "query": {
        "bool": {
            "must": {
                "bool": {
                    "should": [
                    { "term": { "body": "nelly"}},
                    { "term": { "body": "elephant"}},
                    { "term": { "body": "cartoon"}}
                    ],
                    "minimum_should_match": 2
                }
            },
            "should": [
                { "term": { "body": "the"}},
                { "term": { "body": "as"}},
                { "term": { "body": "a"}}
                ]
        }
    }
}
```

Sorry for bothering you~

**Comment by olivere** [comment]
Oh, I'm sorry. I only build the Go client. Please post your question on [discuss.elastic.co](https://discuss.elastic.co/) or StackExchange to get a quick response. Also, the official docs are pretty good in describing the inner workings.

**Comment by olivere** [comment]
E.g. here's the documentation for [Minimum Should Match](https://www.elastic.co/guide/en/elasticsearch/reference/6.4/query-dsl-minimum-should-match.html).
