### ISSUE TITLE
Context is not passed

### ISSUE THREAD

**Issue by themihai** [olivere/elastic#960]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v6 (for Elasticsearch 6.x) 

### Please describe the expected behavior
I expect the context that I pass to be used for the requests

### Please describe the actual behavior

The library is creating "background" context 
### Any steps to reproduce the behavior?
Here is a clear example : https://github.com/olivere/elastic/blob/release-branch.v6/client.go#L1145

### How is it affecting me: 
I'm using a custom http client (using [SetHttpClient](https://godoc.org/github.com/olivere/elastic#SetHttpClient)  )which is expecting a valid context that I pass to `elastic` library. However the library is not passing my context to the http requests. Instead of that it creates null/background contexts. Is there any reason for that?

**Comment by olivere** [comment]
Yes, that looks like a bug. We should've used `parentCtx` in https://github.com/olivere/elastic/blob/release-branch.v6/client.go#L1145. I will write a test for this, then fix it in one of the next releases.

Thanks for reporting.

**Comment by olivere** [comment]
Notice that your context should be correctly passed, and there are tests for checking that behaviour (e.g. [here](https://github.com/olivere/elastic/blob/release-branch.v6/client_test.go#L228-L268)). If you find a case where it doesn't happen as expected, please write a test case or a small program to illustrate.

**Comment by olivere** [comment]
Yes. That’s just the timeout for a single ping. A few lines below that we check the parentCtx for e.g. timeout. So it might still be correct, but I must test that in detail.
