### ISSUE TITLE
Question: Do we have function that verifies a Data Math?

### ISSUE THREAD

**Issue by afiune** [olivere/elastic#961]
### Which version of Elastic are you using?

[X] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
I want to find or contribute if it doesn't exist, with a function that will verify an Elasticsearch 'Date Math' 
value. 

https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#date-math

I can't find it in the code base, do we have something like that?

### Please describe the actual behavior
N/A

### Any steps to reproduce the behavior?
N/A

**Comment by olivere** [comment]
The library just passes the request/functions you use on to Elasticsearch, i.e. if ES has that feature, so will Elastic. E.g. here is [a test for a `RangeQuery`](https://github.com/olivere/elastic/blob/d677dbe6d6a14f0b4f10dd28e906452f1e1d6d06/search_queries_range_test.go#L33) that used date math.

**Comment by zanes2016** [comment]
It seems that the client introduces a change/formatting of Date Math that isn't compatible with the ES Index searching. See #1009
