### ISSUE TITLE
How to use Transport in elastic go client <ElasticSearch V6.x>

### ISSUE THREAD

**Issue by rohitravi22** [olivere/elastic#964]
Hi Oliver,

How do we implement tcp proxy using elastic go client? Any lead would be appreciated.....  I have written code using http in golang... but now I want it to convert it using elastic go client...

client := &http.Client{}
	ret := os.Getenv("SOCKS5_PROXY")
	if (ret != "") {
		log.Println("Environment variable SOCKS5_PROXY set to: " + os.Getenv("SOCKS5_PROXY"))

		// create a socks5 dialer
		dialer, err := proxy.SOCKS5("tcp", ret, nil, proxy.Direct)
		if err != nil {
			fmt.Fprintln(os.Stderr, "can't connect to the proxy:", err)
			os.Exit(1)
		}

		// setup a http client
		httpTransport := &http.Transport{}

		// set our socks5 as the dialer
		httpTransport.Dial = dialer.Dial
		client = &http.Client{Transport: httpTransport}
	}

I am not able to implement same by using elastic go client...(ex: client, err := elastic.NewClient() ).. Can you please help me.

**Comment by olivere** [comment]
I'm not sure about configuring the HTTP proxy. But if you are sure that your code is correct, you should be able to simply set the `*http.Client` to use via the `elastic.SetHttpClient(...)` option.

See [here](https://github.com/olivere/elastic/wiki/HttpTransport#http-basic-authentication) for an example (doing something different, but essentially passing a configured `*http.Client`).
