### ISSUE TITLE
Does call to *BulkService.Do() from multiple Goroutines happen sequentially?

### ISSUE THREAD

**Issue by akshayjbhat** [olivere/elastic#965]
### Which version of Elastic are you using?
[ ] elastic.v5 (for Elasticsearch 5.x)

### Query
I have 8 Goroutines and each one does following:
Create Bulkservice using func NewBulkService(client *Client). Add 3000 records. Then call *BulkService.Do()

I believe the Do() call does not happen in parallel even when called from separate goroutines since I could not see any performance change when I had only 1 goroutine do all the job.
Can you please let me know if this is correct. If yes, is there a way to parallelize it?

Here is the sample code:
``` Golang
for i:=0;i<8;i++{
	go somefunc()
}
func somefunc(){
	client, _ := elastic.NewClient(elastic.SetURL(esURL))
	bulkRequest1 := elastic.NewBulkService(client)
	for i:=0;i<3000;i++{
		request := elastic.NewBulkIndexRequest().
			Index("index").
			Doc(map[string]interface{}{
				"k1": v1,
				"k2": v2,
			})
		bulkRequest1 = bulkRequest1.Index("index").Type("doc").Add(request)
	}
	bulkRequest1.Do(context.Background())
}
```

**Comment by olivere** [comment]
Hi! First of all, you should really just create one client, not one in every `somefunc`. Besides that, please see the [bulk insert recipe](https://github.com/olivere/elastic/blob/release-branch.v6/recipes/bulk_insert/bulk_insert.go) which illustrates how to do parallel bulk indexing. Maybe that helps.

**Comment by akshayjbhat** [comment]
Thanks a lot Oliver for the prompt response.

**Comment by olivere** [comment]
Closing for now. If you have a followup questing, I will re-open.
