### ISSUE TITLE
connect to remote host

### ISSUE THREAD

**Issue by mrsiano** [olivere/elastic#968]
### Which version of Elastic are you using?

[x] elastic.v6 (for Elasticsearch 6.x)

#### expected behavior
being able to use http client, or remote server.

#### actual behavior
cannot login (ping) to remote ES server.
on the other hand, I was able to login via curl `curl -k http://<domain>:9200`.
no basic auth required.

#### steps to reproduce
I tried to use both implementations,
```
	httpClient := &http.Client{Timeout: 10000}
	client, err := elastic.NewClient(
		elastic.SetURL(server),
		elastic.SetHttpClient(httpClient),
	)
	if err != nil {
		fmt.Println("ops! something gets wrong.")
		panic(err)
	}
```

```
	client, err := elastic.NewClient(
		elastic.SetURL(server),
	)
	if err != nil {
		fmt.Println("ops! something gets wrong.")
		panic(err)
	}
``` 

do I missed something ?!

**Comment by thendiscard** [comment]
@mrsiano I think I had the same issue as you have. I'm not that familiar with Elasticsearch nor this library but I think it's related to *miss-configured* Elasticsearch clusters + *sniffing* https://godoc.org/github.com/olivere/elastic#NewClient : 

> The list of nodes found in the sniffing process will be used to make connections to the REST API of Elasticsearch.

In my case I have a single node in the Elasticsearch search reachable at 192.168.100.114:9200 but which reports `"publish_address": "127.0.0.1:9200",`: 

```bash
user ~ $ curl http://192.168.100.114:9200/
{
  "name" : "node0.es-cluster.example.net",
  "cluster_name" : "es-cluster.example.net",
  "cluster_uuid" : "TAXt8V7kQI5bL3rqQcDAqB",
  "version" : {
    "number" : "6.3.2",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "053779d",
    "build_date" : "2018-07-20T05:20:23.451332Z",
    "build_snapshot" : false,
    "lucene_version" : "7.3.1",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}

user ~ $ curl http://192.168.100.114:9200/_nodes/http | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   497  100   497    0     0  55222      0 --:--:-- --:--:-- --:--:-- 62125
{
  "_nodes": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "cluster_name": "es-cluster.example.net",
  "nodes": {
    "jCD_3ksPTajHM1dbgKcCmv": {
      "name": "node0.es-cluster.example.net",
      "transport_address": "127.0.0.1:9300",
      "host": "127.0.0.1",
      "ip": "127.0.0.1",
      "version": "6.3.2",
      "build_flavor": "default",
      "build_type": "tar",
      "build_hash": "053779d",
      "roles": [
        "master",
        "data",
        "ingest"
      ],
      "attributes": {
        "xpack.installed": "true"
      },
      "http": {
        "bound_address": [
          "192.168.100.114:9200"                    <<<<<<<<<<<<<<<
        ],
        "publish_address": "127.0.0.1:9200",        <<<<<<<<<<<<<<<
        "max_content_length_in_bytes": 104857600
      }
    }
  }
}
```

In my case passing `elastic.SetSniff(false)` as an additional option helped (it should be the same if you use `elastic.NewClient()`):

```go
        // Elasticsearch setup.
        ctx := context.Background()
        client, err := elastic.DialContext(ctx, elastic.SetURL(esURL),
                elastic.SetSniff(false))
        if err != nil {
                return errors.Wrap(err, "elastic.DialContext failed")
        }

```

I don't know if there are any downsides to disabling *sniffing*.

Hope this helps :)

**Comment by olivere** [comment]
@mrsiano @thendiscard Hi there. This "problem" comes up quite some often. If you want to know the details of why this goes wrong, you can [read it up on the Wiki](https://github.com/olivere/elastic/wiki/Sniffing).

In a nutshell, sniffing means you simply pass a URL to the client that will be used to look up all nodes in the cluster, then being forgotten. The cluster state returned by the initial request will return the URLs of all nodes in the cluster. These are used to send requests to after the initial lookup. However, the URLs returned by the cluster are often unreachable by your client. E.g. if you start up your cluster via Docker Compose, ES typically uses internal IPs that are not routable outside your Docker environment. Hence, they are not reachable by your code, only by other Docker containers on the same network. In that case, you need to disable sniffing; the client will then NOT ask the cluster for the IPs of the nodes, but simply route all requests to the URL you passed into NewClient.

The benefit of using the sniffing process is the elastic, the client library, will check your cluster for nodes that might have died, and marks them as such, no longer sending any requests to it (until it finds them to be healthy again). Furthermore, your load is spread across the nodes in your cluster in a round-robin fashion. Finally, when you add new nodes to your cluster, elastic will find them and add them to the list of available nodes to send requests to. So sniffing (and healthchecks) are very beneficial, and I wouldn't run it disabled in production.

Notice that you can achieve the load-balancing and such on the server-side as well, using e.g. nginx or haproxy… and I personally prefer this to the client-side mechanisms in general. But the official clients all have this ability, so I build it into elastic (the client library) as well.
