### ISSUE TITLE
Access to SearchResut.shardsInfo.failures array

### ISSUE THREAD

**Issue by carldunham** [olivere/elastic#969]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

I would like to be able to access the per-shard errors, if there are any, returned in a search.

### Please describe the actual behavior

This mainly comes up for me when scripting, but I've also seen it with index type mis-matches, etc. A sample result might look like:
```
{
  "took": 62,
  "timed_out": false,
  "_shards": {
    "total": 115,
    "successful": 105,
    "skipped": 0,
    "failed": 10,
    "failures": [{
      "shard": 0,
      "index": "xyz-2018-11-19",
      "node": "SDcB7JoZSfC9z9Lyr43WDg",
      "reason": {
        "type": "class_cast_exception",
        "reason": "class_cast_exception: java.lang.String cannot be cast to java.lang.Number"
      }
    }
  },
  "hits": {
    "total": 0,
    "max_score": 0.0,
    "hits": []
  },
  "aggregations": {
    "a0": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 0
    }
  }
}
```
SearchService.Do() does not return an error, and the `failures` array is hidden in `SearchResult.shardInfo`, a private field. I don't see any functions to access anything there.

When doing this, I see that different shards may return the same error in slightly different ways, not sure why. But I'm happy to deal with that at the application layer.

### Any steps to reproduce the behavior?

Bad programming, resulting in shard-level search errors.

**Comment by olivere** [comment]
Hmm... I'm changing it to a public field. But that only gives you the chance to use it outside of the library. While I don't see a reason why you would want to do that, it doesn't hurt. So I will change it.

You can already access the shard-related information by something like this:

```
res, err := client.Search(...)
if err != nil { ... }
fmt.Println(res.Shards.Total)
fmt.Println(res.Shards.Successful)
fmt.Println(res.Shards.Failed)
```

**Comment by carldunham** [comment]
Thanks, @olivere, this is very helpful. The main use case is presenting information on why the query failed to an upstream consumer. At the moment, all I can do is say that it failed in some of the shards.
