### ISSUE TITLE
elastic: Error 400 (Bad Request): [terms] failed to parse field [size] [type=parsing_exception]

### ISSUE THREAD

**Issue by MyZhang0826** [olivere/elastic#970]
### Which version of Elastic are you using?

[ ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior

test success

### Please describe the actual behavior
![image](https://user-images.githubusercontent.com/16998719/48835672-bd931380-edbb-11e8-9e3b-087b09686dce.png)

### Any steps to reproduce the behavior?
test

**Comment by olivere** [comment]
I have no idea what's going on here. Please provide a small, runnable example that reproduces the problem when I run the code.

**Comment by MyZhang0826** [comment]
@olivere thx，i solved this problem by https://github.com/olivere/elastic/issues/519.
