### ISSUE TITLE
Phrase suggester CollateQuery double quotes issue

### ISSUE THREAD

**Issue by mathewvp** [olivere/elastic#976]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[* ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

When a json string is passed to  elastic.NewPhraseSuggester().CollateQuery(), the double quotes within the json get escaped and get sent to the elastic server which causes no results

eg :- s := elastic.NewPhraseSuggester("suggestedKeyword").Text("mere).Field("field5").Size(1).RealWordErrorLikelihood(0.95).MaxErrors(0.5).GramSize(2).CollateQuery(\`{"source": { "bool": { "filter": { "term": { "field1": "f" } }, "must": { "multi_match": { "fields": ["field2^12", "field3^4", "field4^4", "field5^1"], "operator": "AND", "query": "{{suggestion}}"}}}}}\`)

### Please describe the actual behavior
{"suggestedKeyword":{"text":"mere","phrase":{"collate":{"query":"{\\"source\\": {\ \"bool\\": { \\"filter\\": { \\"term\\": { \\"field\1\":\\"f\\" } }, \\"must\\": { \\"multi_match\\": {\\"fields\\": [\\"field2^12\\", \\"field3^4\\", \\"field4^4\\", \\"field5^1\\"], \\"operator\\": \\"AND\\", \\"query\\": \\"{{suggestion}}\\"}}}}}"},"field":"text_all","gram_size":2,"max_errors":0.5,"real_word_error_likelihood":0.95,"size":1}}}}

The above is the string being sent to elastic with all double quotes escaped which results in no result

**Comment by olivere** [comment]
If you want to use a query with a raw string, use [`elastic.RawStringQuery`](https://github.com/olivere/elastic/blob/release-branch.v6/search_queries_raw_string.go) ([tests](https://github.com/olivere/elastic/blob/release-branch.v6/search_queries_raw_string_test.go)), i.e. change

```
CollateQuery(`{...}`)
```

to

```
CollateQuery(elastic.RawStringQuery(`{...}`))
```

**Comment by mathewvp** [comment]
This is still not working. elastic.RawStringQuery has to be typecasted to string to pass to CollateQuery

ie CollateQuery(string(elastic.RawStringQuery(`{...}`)) And this still produces query with escaped quotes, there is no difference

**Comment by mathewvp** [comment]
This is working when sent as a separate suggest call to elasticsearch instead of as part of normal query. Thanks.

**Comment by olivere** [comment]
Yep, you are correct. I need to change `CollateQuery(string)` to `CollateQuery(*elastic.Script)`, as that's what it's really is, [see here](https://github.com/elastic/elasticsearch/blob/6.x/server/src/main/java/org/elasticsearch/search/suggest/phrase/PhraseSuggestionBuilder.java#L90).
