### ISSUE TITLE
elasticsearch cluster-stats is question ?

### ISSUE THREAD

**Issue by test987654123** [olivere/elastic#978]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
elasticsearch cluster stats is error,  please view 
https://www.elastic.co/guide/en/elasticsearch/reference/6.4/cluster-stats.html

1.  query_cache , not  is filter_cache 
![image](https://user-images.githubusercontent.com/14846522/49197700-cd69b380-f3ca-11e8-9d5f-cd5223b1f848.png)

**Comment by olivere** [comment]
Yes, seems like `query_cache` is missing and used to be `filter_cache` a looong time ago. Will fix that.

Note to self: See [`ClusterStatsIndices.java`](https://github.com/elastic/elasticsearch/blob/6.x/server/src/main/java/org/elasticsearch/action/admin/cluster/stats/ClusterStatsIndices.java) for the current version in 6.x branch.

**Comment by olivere** [comment]
This will be fixed in 6.2.14. Notice that a lot changes happened in this structure. E.g. there also is no longer an `id_cache` and a `percolate` entry. See 1ee1e7278a2f134df4892487921190c88653b67e.
