### ISSUE TITLE
Function Undefined error

### ISSUE THREAD

**Issue by nikhil133** [olivere/elastic#980]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v6 (for Elasticsearch 6.x)

Getting undefined error for NewV4SigningClient(cred,clusterLocation)

**Comment by olivere** [comment]
You're getting that error when you're doing what?

**Comment by nikhil133** [comment]
I am trying to hit elastic cloud .
I used the code from aws_v4_test.go
with my credentials of elastic cluster.
imported files are
net/http
net/http/httptest
GitHub.com/aws/aws-sdk-go/aws/credentials
GitHub.com/Oliver/elastic

**Comment by olivere** [comment]
Okay. I'm just trying to fix a different error on AWS Elasticsearch service. I can look at this as well. But for now, I don't get any compile time errors (if that's what you get).

**Comment by olivere** [comment]
Please also see the example code in [`recipes/aws-connect-v4`](https://github.com/olivere/elastic/blob/release-branch.v6/recipes/aws-connect-v4/main.go). There will be another AWS recipe soon, for illustrating/testing CRUD lifecycle.

**Comment by nikhil133** [comment]
Yes it's a compile time error stating undefined NewV4SigningClient

**Comment by nikhil133** [comment]
Will try this one

**Comment by nikhil133** [comment]
getting compile time error as below when using
aws.NewV4SigningClient(cred,cluster-location)

go/src/github.com/olivere/elastic/aws/sign_v4.go:10:2: cannot find package "
github.com/smartystreets/go-aws-auth" in any of:

        /usr/local/Cellar/go/1.10.3/libexec/src/
github.com/smartystreets/go-aws-auth (from $GOROOT)

        /Users/bon/go/src/github.com/smartystreets/go-aws-auth (from
$GOPATH)

**Comment by nikhil133** [comment]
go get GitHub.com/olivere/elastic/aws/v4 worked for me.
Got connection established response.
Thank you

**Comment by olivere** [comment]
You should really use a dependency management tool like [`dep`](https://github.com/golang/dep) or--even better--[Go modules](https://github.com/golang/go/wiki/Modules).

**Comment by olivere** [comment]
I'm afraid I don't know too much about AWS Elasticsearch Service. I'm currently fighting with another issue (#962). There's a problem with signing the request. I bet that's your problem as well. Please see #962 for follow-ups on what I found.

**Comment by nikhil133** [comment]
why ts.URL is pointing to
http://127.0.0.1:56757

**Comment by olivere** [comment]
You didn’t post the code, so I really cannot know.

**Comment by nikhil133** [comment]
this my code

from main function

func main() {

    var req *http.Request
    ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r
*http.Request) {
        switch r.URL.Path {
        case "/":
            req = r // capture the HTTP request
            w.WriteHeader(http.StatusOK)
            fmt.Fprintln(w, `{
                "name" : "instance-0000000xxx",
                "cluster_name" : "08270ccxxxxx4d5c90xxxxxb5722ef1",
                "cluster_uuid" : "Xxx7WCSxxxxxx",
                "version" : {
                    "number" : "6.5.1",
                    "build_flavor" : "default",
                    "build_type" : "tar",
                    "build_hash" : "xx3xx0",
                    "build_date" : "2018-11-16T02:22:42.182257Z",
                    "build_snapshot" : false,
                    "lucene_version" : "7.5.0",
                    "minimum_wire_compatibility_version" : "5.6.0",
                    "minimum_index_compatibility_version" : "5.0.0"
                },
                "tagline" : "You Know, for Search"
            }`)
            return
        default:
            w.WriteHeader(http.StatusInternalServerError)
            return
        }
    }))
    defer ts.Close()
    cred := credentials.NewStaticCredentials("elastic", "password", "")
    signingClient := awsx.NewV4SigningClient(cred, "ap-southeast-1")
    client, err := elastic.NewClient(
        elastic.SetURL(ts.URL),
        elastic.SetHttpClient(signingClient),
        elastic.SetHealthcheck(false),
        elastic.SetSniff(false),
    )

    //reader := bufio.NewReader(os.Stdin)
    //client, err := elastic.NewClient()
    if err != nil {
        // Handle error
        panic(err)
    }
    // Ping the Elasticsearch server to get e.g. the version number
    info, code, err := client.Ping(ts.URL).Do(context.Background())
    if err != nil {
        // Handle error
        panic(err)
    }
    fmt.Printf("Elasticsearch returned with code %d and version %s\n",
code, info.Version.Number)
    fmt.Printf(ts.URL)

**Comment by olivere** [comment]
That's because `httptest.NewServer(...)` creates a new listener on a random port on localhost, [see here](https://golang.org/src/net/http/httptest/server.go#L63).

**Comment by olivere** [comment]
I'm not sure what you're trying to achieve. If you want to connect to an Elasticsearch instance, use the URL of that instance. If you're using something like the AWS Elasticsearch service, you can find the URL on the AWS Console. It looks something like `https://xxxx.eu-west-1.es.amazonaws.com`. But notice that it doesn't seem to work right now because of the error mentioned above.

**Comment by nikhil133** [comment]
this how my curl looks like

curl -I HEAD -u elastic:password "
https://08xxxccacxxx4d5cx0xxx797bxxx2ef1.ap-southeast-1.aws.found.io:9243/indexname
"


which help me connect to elastic-cloud and check the index exists or not.

If I am using this url without username and password it gives
authentication error

If I use user and password as above pattern it gives the error some what
like colon should not precede before https

**Comment by olivere** [comment]
Please see [the Wiki](https://github.com/olivere/elastic/wiki/Configuration):

```
client, err := elastic.NewClient(
  elastic.SetURL("https://08xxxccacxxx4d5cx0xxx797bxxx2ef1.ap-southeast-1.aws.found.io:9243/"),
  elastic.SetBasicAuth("username", "password"),
  elastic.SetSniff(false), // maybe, depends on how you use it
   ..., // other options
)
```

**Comment by nikhil133** [comment]
ya this works for me
