### ISSUE TITLE
Can I create a document with the update API if the document doesn't exist yet

### ISSUE THREAD

**Issue by baiyufei** [olivere/elastic#981]
### Which version of Elastic are you using?
elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
 I want to use directly my update request to index the document directly if it doesn't exist yet.
just like this
https://stackoverflow.com/questions/25034605/can-i-create-a-document-with-the-update-api-if-the-document-doesnt-exist-yet

### Please describe the actual behavior
I don't know which api i should use
I try this
> update, err := client.Update().Index(index).Type(index).Id(id).Doc(data).Do(elasticCtx)

return error
 elastic: Error 404 (Not Found): [peer][94d44511-2062-42dd-bd13-f92356cf3c06]: document missing [type=document_missing_exception]

**Comment by olivere** [comment]
You do just like the 1st answer on StackOverflow says: You use `doc_as_upsert`. [Here is a snippet](https://github.com/olivere/elastic/blob/release-branch.v6/update_test.go#L162-L167) illustrating that for elastic. You can use your `data` instance instead of a map as well.
