### ISSUE TITLE
Get IndicesGetSettingsService raw response

### ISSUE THREAD

**Issue by bendikro** [olivere/elastic#986]
The current [IndicesGetSettingsService.Do](https://github.com/olivere/elastic/blob/v6.2.14/indices_get_settings.go#L154) (`v6.2.14`) function returns a `map[string]*IndicesGetSettingsResponse`.
It would be useful to get access to the raw respone to do the json unmarshalling manually.

A simple way to solve this is to make [IndicesGetSettingsService.buildURL](https://github.com/olivere/elastic/blob/v6.2.14/indices_get_settings.go#L98) public, which makes it easy to use [Client.PerformRequest](https://github.com/olivere/elastic/blob/v6.2.14/client.go#L1250) to get the raw response.

@olivere In [#436](https://github.com/olivere/elastic/issues/436) you respond `The purpose of elastic's services is exactly to not having to deal with raw response.`. I'd say that is only half the purpose. Building the requests is the other half. By making `buildURL` public it's possible to get both.

**Comment by olivere** [comment]
Hmm... for the moment it's symmetrical unfortunately, so if you want to deal with raw responses, you should be prepared to send raw requests with `Client.PerformRequest`. I could think about opening up the `buildURL` functions, but that'd be a feature for the next major version.

**Comment by olivere** [comment]
Unfortunately Elastic will not open up the `buildURL` functions and not allow access to raw response. If you want that, you can now use the [official Go client](https://github.com/elastic/go-elasticsearch), which is low-level while Elastic stays a high-level client.
