### ISSUE TITLE
Backport making ShardInfo on SearchResult public to elastic.v5?

### ISSUE THREAD

**Issue by elireisman** [olivere/elastic#987]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v6 (for Elasticsearch 6.x)
[x] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

I'm aggregating results from a fanout of queries and I'd like to capture the summary stats under `_shards` but the structure is [private in elastic.v5](https://github.com/olivere/elastic/blob/release-branch.v5/errors.go#L159-L164).

We can't move off ES5 quickly, and would be very appreciative if we could [backport that change from elastic.v6](https://github.com/olivere/elastic/blob/release-branch.v6/errors.go#L167-L173)? I'd be happy to make the change myself and submit a PR if you like.

Thanks so much!

**Comment by elireisman** [comment]
To be clear, while we can _capture_ the stats from those structures now, we can't easily aggregation _into_ one while it's private. So, we can work around it in the worst case but having access would be really useful, if its not too much of a PITA to get the change into elastic.v5

**Comment by olivere** [comment]
No, not at all. It’s just the busiest time of the year. Apologies.

**Comment by elireisman** [comment]
🙇 Totally understandable, and thanks for the prompt reply! Take your time sir, and thanks again for the great library!

**Comment by olivere** [comment]
Will push 5.0.77 soon. Merry christmas ;-)

**Comment by elireisman** [comment]
🎄 thanks! 🎅 good present this year! 🙇
