### ISSUE TITLE
How can I use GeoBoundsAggregation and GeoDistanceQuery

### ISSUE THREAD

**Issue by wzkun** [olivere/elastic#989]
elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
Can anyone gives example about the usage of GeoBoundsAggregation or GeoDistanceQuery.

**Comment by olivere** [comment]
There's a huge test suite for basically all aggregation types [here](https://github.com/olivere/elastic/blob/release-branch.v6/search_aggs_test.go#L78-L192). You must dig into the code, however.
