### ISSUE TITLE
Can't limit scroll-search results count

### ISSUE THREAD

**Issue by imilo** [olivere/elastic#990]
### Which version of Elastic are you using?

[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

When I do a scroll-search I need to limit results count - and `elastic` returns exactly the specified amount of entries.

### Please describe the actual behavior

`elastic` returns all the existing Elasticsearch entries.

### Any steps to reproduce the behavior?

As a base I use your example for a scroll search. My latest try contains:
```go
searchJSON = `{
  "from": 0,
  "size": 5,
  "terminate_after" : 5,
  "query" : {
    "match_all" : {}
  }
}`

...

// 1st goroutine sends individual hits to channel.
hits := make(chan json.RawMessage)
g, ctx := errgroup.WithContext(context.Background())

g.Go(func() error {
	defer close(hits)

	// Initialize scroller. Just don't call Do yet.
	scroll := p.c.Scroll("name-*").Body(searchJSON).Size(5)

	for {
		results, err := scroll.Do(p.ctx)
		if err == io.EOF {
			return nil // all results retrieved
		}
		if err != nil {
			return err // something went wrong
		}

		// Send the hits to the hits channel
		for _, hit := range results.Hits.Hits {
			select {
			case hits <- *hit.Source:
			case <-ctx.Done():
				return ctx.Err()
			}
		}
	}

	return nil
})

...
```
Here I expect `5` returned entries, but I get millions instead. Am I missing something or in the current scroll-search limiting is not working?

**Comment by olivere** [comment]
You get 5 every time you call the Scroll API via `scroll.Do`. But you'll get all matching documents, of course.

There actually is a [test case `TestScrollWithBody` here](https://github.com/olivere/elastic/blob/release-branch.v6/scroll_test.go#L194-L327) and it's working fine as far as I can see it. I also added a simple example of Scroll API in [`recipes/scroll`](https://github.com/olivere/elastic/blob/release-branch.v6/recipes/scroll/scroll.go) just to check if there's a regression, but that's working fine as well.

So I'm not really sure what's going on with your data set.

**Comment by imilo** [comment]
Oh, so I should just replace `for {` with a limited loop instead. I was thinking that setting the `size` or something else is enough. This issue can be closed.
