### ISSUE TITLE
Return hits source data is not expected.

### ISSUE THREAD

**Issue by HSUCHING** [olivere/elastic#991]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v6 (for Elasticsearch 6.x)
[ x ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
We test "http post" on elk on postman app:
![image](https://user-images.githubusercontent.com/1451599/49893709-0b64de00-fe87-11e8-9e65-0a85c874fedf.png)

### Please describe the actual behavior
We get data from go api code:
![image](https://user-images.githubusercontent.com/1451599/49893954-abbb0280-fe87-11e8-85bc-f95bb7b6fd70.png)

### Any steps to reproduce the behavior?
	client, err := elastic.NewClient(elastic.SetURL("http://elk.******.cn:9200/"), elastic.SetBasicAuth("admin","CIJetur3XiohNyV4"),elastic.SetSniff(false),elastic.SetHealthcheckInterval(10*time.Second),elastic.SetErrorLog(log.New(os.Stderr, "ELASTIC ", log.LstdFlags)),elastic.SetInfoLog(log.New(os.Stdout, "", log.LstdFlags)))
	queryString := `{"match_all":{}}`
	searchResult,_:=client.Search().FetchSource(true).Index("xxxxxxx_messenger_task_visit_info_aggs").Query(elastic.RawStringQuery(queryString)).Do(context.Background())

I see the variable "searchResult"( elk search data), but value of key "hits>hits>source" in search object is list: []int, not map object(postman correct result).I want to know where is code error?

**Comment by olivere** [comment]
I'm sorry, I don't quite understand the question. The highlighted frame represents a `*json.RawMessage`, which basically is a `*[]byte`. If you cast it to a `string`, you will actually get the JSON from that byte slice. So that's correct, you just need to deserialize it into a struct that you specified.

See the [example on the project homepage here](https://olivere.github.io/elastic/):

```
...
// Iterate through results
for _, hit := range searchResult.Hits.Hits {
	// hit.Index contains the name of the index

	// Deserialize hit.Source into a Tweet (could also be just a map[string]interface{}).
	var t Tweet
	err := json.Unmarshal(*hit.Source, &t)
	if err != nil {
		// Deserialization failed
	}

	// Work with tweet
	fmt.Printf("Tweet by %s: %s\n", t.User, t.Message)
}
...
```
