### ISSUE TITLE
docValueField(s) should include format

### ISSUE THREAD

**Issue by dhrp** [olivere/elastic#992]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v6 (for Elasticsearch 6.x)
[x] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
When defining my query I can select / elect to include a specific docValue (works) and the docValue _format_ (not possible, as far as I can find).

In addition, Elasticsearch (6.5.1) is starting to give warnings llke: 
```
There are doc-value fields which are not using a format. The output will change in 7.0 when doc value fields get formatted based on mappings by default. It is recommended to pass [format=use_field_mapping] with a doc value field in order to opt in for the future behaviour and ease the migration to 7.0: ["@timestamp"]
```
This suggests such feature should be added for 7.0 (anyways)

A naive solution would be to allow entering json in this field, e.g. like so::
ss := elastic.NewSearchSource().DocvalueField(`{"field":"@timestamp","format":"epoch_millis"}`)

### Please describe the actual behavior

Since docvalue_fields format cannot be represented, you alway get the default value, this is not always what you want or need.

### Any steps to reproduce the behavior?

Try to reproduce this query:
```
GET _search
{
  "query": {
    "match_all": {}
  },
    "docvalue_fields": [
      {
        "field": "@timestamp",
        "format": "epoch_millis"
      }
    ]
}
```

**Comment by olivere** [comment]
Thanks for the detailed error report. 👍 I will look into this and fix it in the next release.

**Comment by olivere** [comment]
In 6.2.15, I'll add a way to specify a docvalue field either as field-only or field with format. I'll introduce a new `DocvalueField` struct for that, which will be used by e.g. `SearchSource` or `InnerHit`.

Some services, e.g. `DeleteByQuery` also support docvalue fields. However, they do so in the query string. I'm not sure why this may be used, but I'll review this in the 7.0 release.

For now, you should be able to use either `DocvalueField(string)` / `DocvalueFields(...string)` and their new counterparts `DocvalueFieldWithFormat(DocvalueField)`/ `DocvalueFieldsWithFormat(...DocvalueField)`. I'll probably remove the former in the 7.0 release as well.

Example:

```
	matchAllQ := NewMatchAllQuery()
	builder := NewSearchSource().Query(matchAllQ).
		DocvalueFields("test1", "test2").
		DocvalueFieldsWithFormat(
			DocvalueField{Field: "test3", Format: "date"},
			DocvalueField{Field: "test4", Format: "epoch_millis"},
		)
```

or

```
	searchResult, err := client.Search().
		Index(testIndexName).
		Query(NewMatchAllQuery()).
		DocvalueFields("user", "retweets").
		DocvalueFieldsWithFormat(
			// DocvalueField{Field: "user"},
			// DocvalueField{Field: "retweets", Format: "long"},
			DocvalueField{Field: "created", Format: "epoch_millis"},
		).
		Pretty(true).
		Do(context.Background())
```

Let me know if that's going to work for you. As I said, I'll probably have to come back at this again in the 7.0 release.
