### ISSUE TITLE
Display the json request on the QueryDSL documentation example

### ISSUE THREAD

**Issue by casertap** [olivere/elastic#993]
### Which version of Elastic are you using?
 elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
I have the exact same code as your QueryDSL example: https://github.com/olivere/elastic/wiki/QueryDSL
I would like to display (using fmt) the request that is sent to elasticsearch as a json payload.

### Please describe the actual behavior
I read a few comments from few years ago on how to do it but because everything is wrapped into a Finder struct I got confused and I could not retrieve the request

```
	search := client.Search().Index(indexName).Type(typeName).Pretty(f.pretty)
	search = f.query(search)
	search = f.aggs(search)
	search = f.sorting(search)
	search = f.paginate(search)

	// TODO Add other properties here, e.g. timeouts, explain or pretty printing
	// Execute query
	sr, err := search.Do(ctx)
```

Thanks

**Comment by olivere** [comment]
You can do so by adding trace logging to the client (see [the wiki](https://github.com/olivere/elastic/wiki/Logging)). Here's an example of enabling the trace log and using stdout as output:

```
client, err := elastic.NewClient(
  elastic.SetURL(...),
  ...
  elastic.SetTraceLog(log.New(os.Stdout, "", 0)), // <- log requests/response to stdout
  ...
)
...
```

**Comment by ghost** [comment]
`elastic.SetTraceLog(log.New(os.Stdout, "", 0))`
Got result like this
![image](https://user-images.githubusercontent.com/13598499/61290703-160d9a00-a7ff-11e9-99e7-b69734ad9704.png)
how can i do it

**Comment by olivere** [comment]
Okay. That looks like a gzip compressed raw HTTP body. Can you disable gzip compression to see the uncompresed body?

**Comment by ghost** [comment]
@olivere thanks, disable gzip get correct value,  looks like enable gzip can't got dsl query
