### ISSUE TITLE
DeleteByQuery - Support for task-id

### ISSUE THREAD

**Issue by vhung92** [olivere/elastic#994]
### Which version of Elastic are you using?

[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

The Elasticsearch Delete By Query API allows setting `wait_for_completion=true` as an URL-parameter which changes the returned response from calling `/_delete_by_query`.

Expected behavior is that when calling `searchClient.Client.DeleteByQuery(indexName).WaitForCompletion(false).Query(query).Do(ctx)` the returned response would include the task-id returned from Elasticsearch.

### Please describe the actual behavior

The response returned does not contain the task-id.

### Any steps to reproduce the behavior?

Call `searchClient.Client.DeleteByQuery(indexName).Do(ctx)` with `waitForCompletion=false` vs `waitForCompletion=true`. The returned responses are the same.

curl:ing elasticsearch produces different responses.
```
curl -XPOST -H 'Content-Type: application/json' "localhost:9200/indexName/_doc/_delete_by_query?wait_for_completion=true" -d '{
  "query" : {
    "bool" : {
      "must" : [
        { "term" : { "user" : "kimchy" } }
      ]
    }
  }
}
'
{"took":101,"timed_out":false,"total":44,"deleted":44,"batches":1,"version_conflicts":0,"noops":0,"retries":{"bulk":0,"search":0},"throttled_millis":0,"requests_per_second":-1.0,"throttled_until_millis":0,"failures":[]}
```

```
curl -XPOST -H 'Content-Type: application/json' "localhost:9200/indexName/_doc/_delete_by_query?wait_for_completion=false" -d '{
  "query" : {
    "bool" : {
      "must" : [
        { "term" : { "user" : "kimchy" } }
      ]
    }
  }
}
'
{"task":"6FGY2eLgQ6qPqR3wStITyA:683"}
```

**Comment by olivere** [comment]
IIRC I found differences with regards to task id over minor 6.x versions. Some endpoints did return a task id, some didn't (although documented). I will look at it again, maybe things have changed. Thanks for notifying.

**Comment by olivere** [comment]
I noticed that when you want to start the task asynchronously, you simply need to run `DoAsync(ctx)` instead of `Do(ctx)`, [illustrated here](https://github.com/olivere/elastic/blob/release-branch.v7/delete_by_query_test.go#L185-L210). You will get back a struct which has the ID of the task.
