### ISSUE TITLE
Deprecated missing field on CompositeAggregationHistogramValuesSource

### ISSUE THREAD

**Issue by universonic** [olivere/elastic#996]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

No error should be present.

Just replace `missing interface{}` with `missing_bucket bool`.

### Please describe the actual behavior

From logger:
```
299 Elasticsearch-6.5.3-159a78a "[missing] is deprecated. Please use [missing_bucket] instead." "Thu, 20 Dec 2018 10:45:58 GMT"
```

### Any steps to reproduce the behavior?

Use it to send a query to Elasticsearch 6.5.3.

**Comment by olivere** [comment]
Thanks. I'm looking into this and fix it for the next release.
