### ISSUE TITLE
How to get all indexes from es with api?

### ISSUE THREAD

**Issue by wzkun** [olivere/elastic#999]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
I want to get all indexes from es with an api.

**Comment by olivere** [comment]
Hi @wzkun. You should be able to use wildcards like `*` in the index names as specified [in the docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-index.html). Although not discussed there, a `?` should also be possible as a placeholder for a single character.

An alternative would be to use [`client.IndexNames(...)`](https://github.com/olivere/elastic/blob/release-branch.v6/client.go#L1973-L1984) and filter on the application side.
